### ISSUE TITLE
ctrl click on link does not work properly

### ISSUE THREAD

**Issue by kafisatz** [julia-vscode/julia-vscode#1004]
When clicking on a link, there seems to be a suffix ")" which invalidates the link.
E.g. for 
```
using Distributions
?Gamma
```

the right link is shown, but when I click on it, Chrome tries to open this page (INCLUDING closing bracket):

"https://en.wikipedia.org/wiki/Gamma_distribution)"

**Comment by ZacLN** [comment]
Hiya, what OS and version of the extension are you using?

**Comment by davidanthoff** [comment]
Are you clicking on these links in the terminal area, in the Julia REPL? Or in the hoover in the text editor?

**Comment by kafisatz** [comment]
Windows 10, Julia 1.0.5 
Extension, I think it is 0.13.1 (see screenshot for more details)
![screenshot2](https://user-images.githubusercontent.com/15026865/74954803-faf1b100-5403-11ea-87ea-8f73fcdda32c.PNG)
![screenshot](https://user-images.githubusercontent.com/15026865/74954807-fc22de00-5403-11ea-8283-a6ec42137136.PNG)

**Comment by kafisatz** [comment]
I am clicking the links in VS Code ('Terminal), as shown in the screenshot. The screenshot actually shows that the URL, which Chrome will try to open, has a trailing )

**Comment by davidanthoff** [comment]
So then you need to open an issue with VS Code itself, we have no control over these links in the terminal, as far as I can tell.

**Comment by kafisatz** [comment]
Ok. I filed this here: 
https://github.com/microsoft/vscode/issues/91133

**Comment by ZacLN** [comment]
Fixed upstream apparently
