### ISSUE TITLE
julia.additionalArgs doesn't accepts multiple args

### ISSUE THREAD

**Issue by utotch** [julia-vscode/julia-vscode#1006]
I want to set multiple options to Julia: Additional Args, but it doesn't accept multiple args.

e.g.
```javascript
"julia.additionalArgs": ["--sysimage=filename.so"]
```
works well but
```javascript
"julia.additionalArgs": ["-g 2 --sysimage=filename.so"]
```
doesn't work.

in https://github.com/julia-vscode/julia-vscode/blob/master/src/repl.ts
```javascript
let jlarg1 = ['-i','--banner=no'].concat(vscode.workspace.getConfiguration("julia").get("additionalArgs"))
```
doesn't split and add multiple args.

**Comment by davidanthoff** [comment]
Can you try `"julia.additionalArgs": ["-g", "2", "--sysimage=filename.so"]`? I think that is how it is meant to be done.

**Comment by davidanthoff** [comment]
I'm closing this, please let us know if this is still an issue.
