### ISSUE TITLE
Execute code block: echo in terminal needed or not

### ISSUE THREAD

**Issue by luboshanus** [julia-vscode/julia-vscode#1007]
The code does not appear/echo in the terminal when a block of code is executed.

Related discussion is at https://discourse.julialang.org/t/julia-vscode-on-macos-vs-windows/29718 

And as @davidanthoff pointed out the line of code is responsible for not printing code is here:
https://github.com/julia-vscode/julia-vscode/blob/master/scripts/terminalserver/terminalserver.jl#L153

This issue may start a discussion if printing the block is needed. I would welcome to see the executed block of code. While a line of code is echoed I don't see difference between executing a line of code and a block and not echoing the block.

**Comment by davidanthoff** [comment]
I think maybe we should enable it for one release and see how it goes?

Should we print the echoed code in some other color, or something? Just to visually distinguish echoed code from normal output? Or we could also put something like `> ` in front of every line that is choed, or some other visual indicator?

**Comment by luboshanus** [comment]
I am asking for this because I use SublimeText and there you just send code to Terminal and you see what you have sent that is my main point. I'd like to see what was sent. The same actually is in VScode when you execute python, you just see what has been sent. 

I do not mind to change colour but it is not necessary to put '> ' in front of each line. The reason is that, for example, to copy it from R console is pain [or maybe I do not know a trick].

Also, additionally, when I hit send/execute block and I am at the bottom line of the script it runs the whole script, which I find unfortunate.

**Comment by kbarros** [comment]
I imagine there is another camp that appreciates not having the block code echoed. If people are divided on this, maybe it should be specifiable as a config option?

**Comment by SyxP** [comment]
I think the reason why we should consider having the block sent, is sometimes you're not sure what exactly the block starts/ends and hence having visual feedback of what exactly you're sending would be useful.

**Comment by luboshanus** [comment]
Yes, that is mainly the point. And if you have an error in Repl, for example, then you don't see what you sent and if that did or did not produce the same error. This is the situation that bothers me most of the times.

**Comment by CameronBieganek** [comment]
Another problem with not echoing the block is that the block that was just run does not enter the REPL history, so you can't use the up-arrow to re-run the code or edit and re-run the code.

**Comment by davidanthoff** [comment]
I'm convinced we should echo by default :) Ideally we would make it an option, but I think for now we should just echo. My plan right now is to echo in a slightly different color.

Echoing woulnd't add the code to the REPL history, though... I agree, that would also be good, but I don't know how that would be done (the REPL code base is one huge undocumented mystery to me...). I think we should track the REPL history thing in a separate issue, @CameronBieganek do you mind opening a new issue?

**Comment by CameronBieganek** [comment]
> Echoing wouldn't add the code to the REPL history, though... I agree, that would also be good, but I don't know how that would be done (the REPL code base is one huge undocumented mystery to me...). I think we should track the REPL history thing in a separate issue, @CameronBieganek do you mind opening a new issue?

Oh, that's interesting. Executing a single line of code from a file with `Ctrl + Enter` does enter the line into the REPL history. Do you have any idea why that works but executing a block doesn't?

**Comment by davidanthoff** [comment]
`Ctrl+Enter` just sends that text to the REPL, it is more like copy-paste. `Alt+Enter` sends the code via a named pipe to the REPL process and is then executed on a background task, completely bypassing the REPL.

**Comment by NightMachinary** [comment]
I think while having options is the best, echoing should be the default.
