### ISSUE TITLE
The script interpreter declaration line should not be formatted?

### ISSUE THREAD

**Issue by biluohc** [julia-vscode/julia-vscode#1009]
Thank you for your work.

 I found this problem with formatting Julia code with vscode.

```sh
-#! /usr/bin/env julia
+# ! /usr/bin/env julia
```

version: MacOS && Julia 1.3.1 && julia-vscode v0.13.1

**Comment by davidanthoff** [comment]
Duplicate of https://github.com/julia-vscode/DocumentFormat.jl/issues/80.
