### ISSUE TITLE
Linter doesn't recognize do...block

### ISSUE THREAD

**Issue by Roger-luo** [julia-vscode/julia-vscode#1010]
It says 

> An incorrect number of function arguments has been passed.

![image](https://user-images.githubusercontent.com/8445510/74897802-2b830d80-5366-11ea-9bac-dc06939e2776.png)

**Comment by davidanthoff** [comment]
Which version of the extension?

**Comment by Roger-luo** [comment]
Oh sorry I forgot that. It's on the current release 0.13.1

**Comment by davidanthoff** [comment]
Then I'm going to close this, I believe this is fixed on `master`.
