### ISSUE TITLE
error with JuliaPro1.3.1, missing package in its dependencies

### ISSUE THREAD

**Issue by zhangliye** [julia-vscode/julia-vscode#1015]
I am developing a package, and registered locally using the command,
`Pkg> dev --local c:/julia_dev/hotspot`. 
It can be imported using `using Hotspot` and tested successfully in Julia1.3.1 from Julialang.org.
However, when I use JuliaPro1.3.1, although it can be successfully imported and built using `using Hotspot`, I got error when debug with Julia-vscode both 0.15 alpha 7/8. The error is as following.

`ERROR: LoadError: ArgumentError: Package Hotspot does not have ArchGDAL in its dependencies:
- If you have Hotspot checked out for development and have
  added ArchGDAL as a dependency but haven't updated your primary
  environment's manifest file, try `Pkg.resolve()`.
- Otherwise you may need to report an issue with Hotspot
Stacktrace:
 [1] require(::Module, ::Symbol) at .\loading.jl:900
 [2] include at .\boot.jl:328 [inlined]
 [3] include_relative(::Module, ::String) at .\loading.jl:1105
 [4] include(::Module, ::String) at .\Base.jl:31
 [5] top-level scope at none:2
 [6] eval at .\boot.jl:330 [inlined]
 [7] eval(::Expr) at .\client.jl:425
 [8] top-level scope at .\none:3
in expression starting at C:\julia_dev\hotspot\src\Hotspot.jl:5
`
I checked Project.toml and Manifest.toml, ArchGDAL is there.
[deps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"

[[ArchGDAL]]
deps = ["DataStreams", "Dates", "GDAL", "GeoInterface"]
git-tree-sha1 = "16f2d6af2e0760de065881202cdc197975535fff"
uuid = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
version = "0.3.1"

**Comment by davidanthoff** [comment]
We had many reports that JuliaPro has some weird, non-standard setup story... Not sure whether that is still the case, but the fact that things seem to work with normal Julia but not with JuliaPro suggests to me that this is a problem with JuliaPro, and not with the VS Code extension...

**Comment by zhangliye** [comment]
Is this possibly because the register-related directory of JuliaPro is a bit different from the standard version of Julia, which is located in "C:\Users\zhangly\.juliapro\JuliaPro_v1.3.1-1\*" rather than "C:\Users\zhangly\.julia\*"  ?

**Comment by zhangliye** [comment]
> We had many reports that JuliaPro has some weird, non-standard setup story... Not sure whether that is still the case, but the fact that things seem to work with normal Julia but not with JuliaPro suggests to me that this is a problem with JuliaPro, and not with the VS Code extension...
> 
> EDIT: So my suggestion would be to just not use JuliaPro, I think...

Some packages cannot be properly installed using the standard Julia and can be installed from JuliaPro.  Or there is almost no reason to use JuliaPro for me. 

[sqlite install error](https://discourse.julialang.org/t/sqlite-jl-install-error-with-julia1-3-1/35007/4 )

**Comment by davidanthoff** [comment]
Hm, so I guess you could try to configure the extension to use the Julia binary that is shipped with JuliaPro, and then you would also have to make sure that env variables like `JULIA_DEPOT_PATH` etc. are properly set before you start VS Code. That _may_ work, but not sure...

**Comment by zhangliye** [comment]
Thanks! It works!
Just set JULIA_DEPOT_PATH  pointing to that of JuliaPro.  All the packages can be used in standard Julia.  julia-vscode can use JuliaPro1.3.1 after setting this.
