### ISSUE TITLE
Unacceptable high CPU usage

### ISSUE THREAD

**Issue by ohmsweetohm1** [julia-vscode/julia-vscode#1016]
I am experiencing huge amounts of CPU usage if i start VSCode with Julia.
No Revise.jl and **just an open editor** with a Julia file.
There is a Julia.exe running that consumes already **30% of my i5**. If I just start the Julia.exe for itself it is next to nothing.
Any ideas?

**Comment by davidanthoff** [comment]
Yes, that is a known problem: when you start the extension the first time it will try to index all the packages in your env and cache the result of that. 

Our next release will improve on that: the indexing is faster, it will store partial results on disc and the indexing process gets a lower process priority.

**Comment by ohmsweetohm1** [comment]
If I open two instances of VSCode both of them seem to do the indexing.

**Comment by davidanthoff** [comment]
Good point: https://github.com/julia-vscode/SymbolServer.jl/issues/106. I don't have a solution, nor do I think we'll get to that anytime soon.

**Comment by ak24watch** [comment]
> Yes, that is a known problem: when you start the extension the first time it will try to index all the packages in your env and cache the result of that.
> 
> Our next release will improve on that: the indexing is faster, it will store partial results on disc and the indexing process gets a lower process priority.

**Still not solved i am experiencing same but even higher usage of cpu even when precompiling libraries**
