### ISSUE TITLE
Alt+Entering a blank line results in an warning.

### ISSUE THREAD

**Issue by SyxP** [julia-vscode/julia-vscode#1019]
After loading the Julia Language Server, position the cursor on a blank line and press Alt-Enter (Execute code block). 

This gives the warning "Illegal argument: character must be non-negative", which is not very informative.

**Comment by davidanthoff** [comment]
Thanks, and just to confirm, this is on the 0.14 insider branch, right?

**Comment by SyxP** [comment]
Yes I am using 0.14.9 Julia Insider, with 
```
julia> versioninfo()
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 7 PRO 3700U w/ Radeon Vega Mobile Gfx
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, znver1)
Environment:
  JULIA_EDITOR = "/usr/lib/electron6/electron"
  JULIA_NUM_THREADS = 8
```

**Comment by davidanthoff** [comment]
@ZacLN I can close this, right?
