### ISSUE TITLE
Change current directory to source of send to REPL command

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/julia-vscode#102]
If one sends code from a given file to the REPL, make sure the current directory of the REPL process is the one where the file is located.

This is probably difficult with the current design, but once we move back to the model where the code is sent to the REPL process over a named pipe, this should be simple.

**Comment by bthlgd** [comment]
I think this can be solved, by following code snippnet, before sending the text to the REPL.

```
    let filename = vscode.window.activeTextEditor.document.fileName;
    text = 'cd(dirname("' + filename + '"))\n' + text
```

**Comment by davidanthoff** [comment]
Yes, that would work, but I think it would be weird if the user saw additional code pasted in the REPL...

I'm actually not even sure this is a good idea in the first place, i.e. mucking around with the current directory of the REPL process... In some way, the REPL process should just be under the user's control, and I'm not sure a change like this issue might not be too intrusive...

But I'm just generally not sure, right now.

Another option would be to re-enable the named pipe server, add another command that changes directories... That would probably also work.

But in terms of timeline, I think it makes most sense to put this on the backlog and wait until we have moved to a model where all code is always sent via the named pipe, otherwise we'll just have to redo things again in the future.

**Comment by ZacLN** [comment]
I agree, we should wait until the pipe connection is used and add a simple command to change to current directory. We could then have it (if we wanted to) to cd in and out of the file's directory when evaluating code...but you're right, this might be a bit weird

**Comment by bthlgd** [comment]
I agree with you that the solution ugly.

One thing is the user has full control, so they can change the working directory by their own by typing directly in the REPL.

BTW, should we create a pool about requested features for the REPL?

**Comment by daravi** [comment]
Can't this be done by adding a settings that instead of the default ${workspaceFolder} could be set to ${fileDirname}?

**Comment by davidanthoff** [comment]
Yes, I really like that setting idea. And we have the pipe server now, so at least for Alt+Enter we could easily change the current folder for just the execution of that piece of code.

**Comment by hraftery** [comment]
Excuse the intrusion, but what was the completion? I can set the CWD with `"cwd": "${fileDirname}",` in `launch.json` for the run command, but I cannot figure out the same for "Execute active file in REPL". Was `julia.cwd` added in the end? Where is it specified?

**Comment by mbUSC** [comment]
@hraftery Were you able to figure this out?
Should be such a simple thing to do...

**Comment by hraftery** [comment]
Hmm, not that I recall. I'm sure I would have documented it if I had figured it out.

**Comment by pfitzseb** [comment]
I'd recommend not relying on `pwd` for cases like this. If you want to refer to a path relative to the current file, use `@__DIR__` etc.
