### ISSUE TITLE
\div (÷) doesn't get autocompletion

### ISSUE THREAD

**Issue by norru** [julia-vscode/julia-vscode#1022]
Typing `\div` to get autocompletion to the symbol ÷ for integer division, as you would `\alpha`, `\beta`, `\lambda` has no effect.

**Comment by ZacLN** [comment]
I can't replicate this, could you provide a bit more context (in terms of the code within which you're trying to get the completion). Thanks!

**Comment by ZacLN** [comment]
Closing, as above I can't replicate this
