### ISSUE TITLE
Run code/blocks/file without re-open the terminal panel

### ISSUE THREAD

**Issue by stakaz** [julia-vscode/julia-vscode#1026]
It would be great if there would be an option to leave the terminal hidden while running parts of code, blocks or files.

The current behavior is to always reopen the terminal panel when julia code is executed but in some cases it is not necessary to see the output and it become a nightmare to close the terminal after each computation. 

I think there is even an option for this when providing tasks to VS code so basically this would only need a new setting to become possible.

**Comment by stakaz** [comment]
Or an even "better" solution would be to have shortcuts for run code in "background", i. e. without pop-up the terminal.

**Comment by davidanthoff** [comment]
Hm, so then there would essentially be no visual indiciation at all that one ran something, right?

**Comment by stakaz** [comment]
Yes. But one could think about an icon in the status panel.

**Comment by davidanthoff** [comment]
Yes, we should probably have some visual "busy" indicator in the status bar no matter what.

**Comment by pfitzseb** [comment]
Pretty sure this works fine now.
