### ISSUE TITLE
Working with DrWatson?

### ISSUE THREAD

**Issue by haberdashPI** [julia-vscode/julia-vscode#1027]
I'd like to be able to make use of [DrWatson](https://github.com/JuliaDynamics/DrWatson.jl) to find source files, but it messes up linting. Example:

The following is correctly found

```julia
include(joinpath("..", "..", "src", "julia", "setup.jl"))
```

While the following fails to find the included source file:
```julia
using DrWatson; @quickactivate("german_track")
include(joinpath(srcdir(), "julia", "setup.jl"))
```

For some context: in a typcial DrWatson folder layout, the source files are organized separately from the scripts (a `src` folder and a `scripts` folder); in my case there is an additional subfolder as there are also R and Matlab files in the project.

What would it take to make julia-vscode recognize `srcdir()`? If it sounds feasible, I am happy to help contribute towards making this work if I have some pointers regarding where I would start.

**Comment by davidanthoff** [comment]
So this would have to live in the LanguageServer.jl repo.

But, to be honest, I'm not keen that we add too much special casing for individual packages there... I think I also don't really understand the use case here: why can't one just use `include("../../src/julia/setup.jl")`? That works cross platform and seems much easier in general?

**Comment by haberdashPI** [comment]
It's about robustness: depending on your environment the directory the script is run from could be different or the location of the script could be different (e.g. re-organize code to different locations). With the DrWatson approach, as long as those two lines are run from within the project directory, it will find the correct directory.

I recognize it might not be easy or worthwhile to account for this.

**Comment by haberdashPI** [comment]
For example, I keep my working directory in the base directory of my project, so normally when I run individual lines from this script, they are being run from that base directory; however, this is inconsistent with the expected directory for the Linter (the directory of the file itself) or the directory you would get if you just ran the script directly from the command line (e.g. `julia myanalysis.jl`).

**Comment by davidanthoff** [comment]
So I think the _only_ scenario where this helps is if you move files around. From where you start your script shouldn't matter, `include` calls are not relative to the current working folder, but relative to the file location of where the `include` statement appears.

**Comment by davidanthoff** [comment]
There _is_ a problem when you run code in VS Code via "send to terminal", but if you use `Alt+Enter` to run your code blocks/lines, it should all work, irrespecitve of your current working directory.

**Comment by haberdashPI** [comment]
Ah... I see.

My problem is that I have a custom setup for my terminal: I work with multiple languages (matlab, R, julia) for different parts of my analysis, depending what is easiest to express a particular problem. Thus, I make use of a little [extension](https://github.com/haberdashPI/terminal-polyglot) I wrote that sends text to the REPL based on what language mode you're in.

I've been meaning to find a way for that extension more compatible with julia-vscode... this looks like an inspiration to look more into that possibility.

**Comment by davidanthoff** [comment]
We could expose [this](https://github.com/julia-vscode/julia-vscode/blob/master/src/repl.ts#L611) as a proper extension command, and I think then other extensions could call it to execute code? But that also only works with the Julia that is started via the "Start Julia REPL" command, so probably doesn't help you, right?

Maybe we need another option that allows one to start julia from a shell in the integrated terminal, and then "connect" it to the Julia extension, so that stuff like that and the plot pane etc starts to work?

**Comment by haberdashPI** [comment]
Yes! If I could "connect" to the extension via an opened terminal that would be *amazing*.  Again, I'm happy to contribute if you can point me in the right direction.

**Comment by davidanthoff** [comment]
https://github.com/julia-vscode/julia-vscode/issues/1030. This is a complicated thing to do, and right now we have too many other big things pending, so I think this will have to wait quite a while, until all these other things have settled down. But I really like the idea!
