### ISSUE TITLE
Revise not working correctly

### ISSUE THREAD

**Issue by cojua8** [julia-vscode/julia-vscode#1028]
Hello,

I'm developing a package, but changes are not being made by Revise. My startup.jl file already has the suggested code in the wiki

I have to do a manual Revise.revise() every time I need to debug some code.

How can I (or you) make it automatic?

Thank you!

**Comment by davidanthoff** [comment]
How are running your code? I think we might have a bug with respect to this if you run your code with Alt+Enter. Is that how you are executing code?

**Comment by cojua8** [comment]
Just F5

**Comment by davidanthoff** [comment]
Ah, ok. F5 uses the same mechanism that Alt+Enter uses, so I'm pretty positive that it is the same underlying issue. Should actually be fairly simple to fix, in theory.
