### ISSUE TITLE
Persist REPL process on remote

### ISSUE THREAD

**Issue by xgdgsc** [julia-vscode/julia-vscode#1035]
Is it possible to persiste REPL process when using with vscode-remote? That would save time from reloading datasets and generating variables by code lines on disconnects from remote server.

**Comment by davidanthoff** [comment]
Good question, I think that might be more of a feature request for the VS Code Remote extensions, I don't think we can do anything about that in our extension.

**Comment by pfitzseb** [comment]
There's an option for starting the REPL in a tmux session now.
