### ISSUE TITLE
Memory leak (not sure about the source)

### ISSUE THREAD

**Issue by IljaK91** [julia-vscode/julia-vscode#1036]
Hi everyone,

I am using Julia insider (0.14.13) and Julia 1.3.1. Recently I have observed this weird behaviour where Julia has some load on my CPU (fluctuating between 5% and 30%) and takes up excessive amounts of RAM (2-3 GB), although I am not executing any code. My take is that it has something to do with the plugin, but I do not know how to check it. If you can tell me what information you need, I will gladly provide it.

![grafik](https://user-images.githubusercontent.com/13484803/76077307-c142ad80-5fa0-11ea-95cc-7c0cbb168e16.png)

Thank you very much!

**Comment by davidanthoff** [comment]
This is most likely our indexing process. Once it is done it should go away, but that can take a while (sometimes hours).

I'm going to close this issue: this is a known issue, we have some ideas on how to improve this, but it is a tricky area...

**Comment by ohmsweetohm1** [comment]
What purpose does the indexing serve? Can I disable it and still use the extension?

**Comment by davidanthoff** [comment]
The indexing is really core to the editing features and can’t be disabled.
