### ISSUE TITLE
VScode extension Julia Devours RAM

### ISSUE THREAD

**Issue by neoabs** [julia-vscode/julia-vscode#1041]
After I launch VS Code Julia starts eating ridicoulus amounts of RAM without end:

[picture](https://imgur.com/a/fJlpT5Q) - and growing
In terminal Julia behaves normally.
  
`julia> versioninfo()`
`Julia Version 1.3.1`
`Commit 2d5741174c (2019-12-30 21:36 UTC)`
`Platform Info:`
`  OS: Linux (x86_64-pc-linux-gnu)`
`  CPU: AMD Ryzen Threadripper 2990WX 32-Core Processor`
`  WORD_SIZE: 64`
`  LIBM: libopenlibm`
`  LLVM: libLLVM-6.0.1 (ORCJIT, znver1)`
`Environment:`
`  JULIA_NUM_THREADS = 64`
`

BTW: Insider version of extension had the same issue

**Comment by neoabs** [comment]
Also version info from VSCode:
`versioninfo()`
`Julia Version 1.3.1`
`Commit 2d5741174c (2019-12-30 21:36 UTC)`
`Platform Info:`
`  OS: Linux (x86_64-pc-linux-gnu)`
`  CPU: AMD Ryzen Threadripper 2990WX 32-Core Processor`
`  WORD_SIZE: 64`
`  LIBM: libopenlibm`
`  LLVM: libLLVM-6.0.1 (ORCJIT, znver1)`
`Environment:`
`  JULIA_NUM_THREADS = 64`
`  JULIA_EDITOR = "/usr/lib/electron6/electron"`

**Comment by davidanthoff** [comment]
@neoabs is there some way that you can figure out whether this is the language server process or the symbol server process? If you could show us that command line args that were passed to the offending process, we should be able to tell.

**Comment by neoabs** [comment]
[Julia with command line args](https://imgur.com/L3R3h6g.png)

This?

**Comment by davidanthoff** [comment]
So I think that means it is a problem in the LS... Probably some infinite loop or something like that...

Tricky to debug, unfortunately. @neoabs is there a chance that you might be able to share your env and the whole folder of code that you have open in VS Code with us? No need to do it publicly, you could email me or @ZacLN the stuff and we wouldn't share it with anyone other than between the two of us.

**Comment by davidanthoff** [comment]
@ZacLN I've just sent you a file on slack that repos this problem, it is something in CSTParser.jl

**Comment by ZacLN** [comment]
Ta, I'll have a look
