### ISSUE TITLE
Include executed code blocks in REPL history

### ISSUE THREAD

**Issue by CameronBieganek** [julia-vscode/julia-vscode#1058]
Echoing wouldn't add the code to the REPL history, though... I agree, that would also be good, but I don't know how that would be done (the REPL code base is one huge undocumented mystery to me...). I think we should track the REPL history thing in a separate issue, @CameronBieganek do you mind opening a new issue?

_Originally posted by @davidanthoff in https://github.com/julia-vscode/julia-vscode/issues/1007#issuecomment-599355599_

**Comment by pfitzseb** [comment]
There's an option for this now.
