### ISSUE TITLE
Step over nested function calls in debugger

### ISSUE THREAD

**Issue by janbruedigam** [julia-vscode/julia-vscode#1059]
Very glad the debugger is coming along so well!
One option I'm missing coming from Atom/Juno is the option to step over function calls in a nested statement to step into a specific function call. Take for example:
+(1,+(2,+(3,4)))
where I want to step into the last function call +(1,...).

As far as I see it, currently I can only step over the entire statement or step into each individual function call until I reach the one I actually want to step into.
Let me know if I just didn't see that option and it does exist.

**Comment by davidanthoff** [comment]
I don't think the VS Code UI supports that, so I don't think we can implement this until there is an option in the debug adapter protocol for this. Or maybe I missed it in the protocol, but not clear to me how we would implement this.

Agreed, this would be very helpful.

**Comment by janbruedigam** [comment]
Just did a bit of research and agreed, it doesn't seem like there is direct support for that yet. A few things I found along the way:

- Simply using F11 and Shift+F11 does what I'm looking for but a single key would be even nicer.

- The Visual Studio debugger (not VS Code) has a short-cut Alt+Shift+F11 that lets you select which function to step into in a single line. This is currently not implemented in VS Code, but also seems like a nice feature. Maybe for now we could add the Alt+Shift+F11 short-cut to call F11 + Shift+F11 in debug mode without adding a button to the UI? Not sure if something like this is possible or gets to messy if it doesn't exist in VS Code.

- There is an option in VS Code to set a breakpoint by specifying a function name. This could be used to step into the desired function call but isn't implemented with the Julia extension yet / I get an error. I'll open a separate issue for that.

**Comment by davidanthoff** [comment]
We generally can't add our own keyboard shortcuts, UI or anything like that. We implement https://microsoft.github.io/debug-adapter-protocol/ and all the UI is provided by VS Code. So generally we can only support things that are covered by the DAP, _and_ are implemented in VS Code. 

I think we just have to wait for VS Code to implement this, see https://github.com/microsoft/vscode/issues/90793.

> There is an option in VS Code to set a breakpoint by specifying a function name. This could be used to step into the desired function call but isn't implemented with the Julia extension yet / I get an error. I'll open a separate issue for that.

That should actually work, if it doesn't it is just a bug.

**Comment by davidanthoff** [comment]
I believe the UI work for this is on the May 2020 milestone for VS Code, so we might soon have an API that allows us to implement this.

**Comment by janbruedigam** [comment]
Awesome, thanks for staying on it!

**Comment by davidanthoff** [comment]
The UI part on the VS Code side of things was just merged (https://github.com/microsoft/vscode/issues/90793), so we can try to implement this now.

What we need to do is implement the `StepInTargets` request. @pfitzseb is there maybe code from the Juno side of things that could help here? We essentially just need a way to extract all the possible step in targets at a given stopped location, and return each with an ID and label. And then later we might get a `stepin` request that specifies one of those IDs.

The VS Code team is currently looking for extensions to test this out, so it might be nice if we could help them out there.

**Comment by pfitzseb** [comment]
That's not at all how it's handled in Juno, so I don't think we have any code for that. Extracting all function calls on a line seems like an easy job for CSTParser though.

> however if you feel that is the right way you can always contribute to it from your extensions since the debug toolbar is open to contributions.

That sounds like we could implement expression-stepping?

**Comment by davidanthoff** [comment]
>> however if you feel that is the right way you can always contribute to it from your extensions since the debug toolbar is open to contributions.

> That sounds like we could implement expression-stepping?

Ah, yes, we apparently can  add our own custom commands to the toolbar, I didn't know that! I guess one question whether we want both stepInTargets and that, or only one of the two? And then we would also need some UI to show what the next step would be, right?

**Comment by davidanthoff** [comment]
And they seem to be adding a stepping granularity option to the DAP, which we could probably also utilize for this: https://github.com/microsoft/debug-adapter-protocol/pull/112.

**Comment by pfitzseb** [comment]
This is possible now with the `Step Into Targets...` functionality.

**Comment by HusterRichard** [comment]
> And they seem to be adding a stepping granularity option to the DAP, which we could probably also utilize for this: [microsoft/debug-adapter-protocol#112](https://github.com/microsoft/debug-adapter-protocol/pull/112).

Do julia and julia-vscode support the SteppingGranularity of DAP?

when I'm debugger julia, it usually need to press F10 two times to run one line code.
I think the 'line' mode of stepping granularity maybe solve this problem.

how can i resolve it?

**Comment by pfitzseb** [comment]
This is for top-level code, I assume? If so, that's unrelated to this issue.
