### ISSUE TITLE
LanguageServer gets stuck and stops responding

### ISSUE THREAD

**Issue by 8uurg** [julia-vscode/julia-vscode#1063]
Can be reproduced using the same minimal example as in #849, though rather than crashing, CPU is being continuously utilized and any functionality provided by the language server stops working.

![CPU Usage](https://user-images.githubusercontent.com/3746853/77228045-e29cbf80-6b84-11ea-91d3-e3ef2a38b324.png)

'Defusing' the minimal example stops the issue from occurring.

Quick Update: The issue is probably located in `StaticLint.jl`. If the cause is the same, then if b is a Binding with a cycle (eg. you will end up at the same position with .prev) the 'while true' loop will never stop, as b.prev is never nothing and always a Binding. https://github.com/julia-vscode/StaticLint.jl/blob/master/src/linting/checks.jl#L240

**Comment by davidanthoff** [comment]
Did https://github.com/julia-vscode/StaticLint.jl/pull/121 fix this? Can we close this issue?

I had one repo case for these infinite loops, and that has been fixed on `master` now.

**Comment by davidanthoff** [comment]
I pushed a new version out that hopefully fixed this. If not, please open a new issue!
