### ISSUE TITLE
REPL does not understand shell

### ISSUE THREAD

**Issue by lyon-fnal** [julia-vscode/julia-vscode#1066]
When I do "Julia: Start REPL", that REPL does not seem to understand shell commands. For example...

```
# I press ; to get into shell mode
shell> ls
/bin/bash: ls: No such file or directory
```

Furthermore, when adding packages, Julia can't find things like curl or gzip. 

Everything works fine when I start julia outside of VSCode. Or even in the VSCode terminal. 

Any ideas? Thanks! -- Adam

**Comment by davidanthoff** [comment]
We start `julia` directly, without a shell around it, maybe that explains it?

**Comment by lyon-fnal** [comment]
It likely does explain it. Thanks for labeling this a bug.

**Comment by hsm207** [comment]
Is this still a bug?

I'm using extension version 0.15.19 and can run the shell commands just fine inside the Julia REPL, in Windows and WSL.

**Comment by pjssilva** [comment]
Another related problem. I setup conda sourcing the appropriate conda.sh and activating the desired environment. Of course this does not work with you open Julia without bash around it. In this case how to set up conda properly? I don't want yet another conda install in my .julia dir.

**Comment by davidanthoff** [comment]
I think we should just consider to start the Julia REPL inside a shell. I'll look into how we might best do that. Maybe also just a config option.

**Comment by davidanthoff** [comment]
@pfitzseb and @aviatesk how do you do this in Juno?

While I guess we could start Julia inside a shell, it does of course add more things where things can go wrong: presumably if a user has a shell startup script that for example has a bug, we'll have a problem for example... So maybe doing this as an option is the more safe way?

**Comment by pfitzseb** [comment]
Juno starts Julia directly and we tell people to start Atom in your favourite shell if you need anything specific to that (most commonly sourcing your `.bashrc` or whatever).

**Comment by pjssilva** [comment]
Interesting, I found what looks to be a workaround. I have create a file named
`/usr/loca/bin/julia`. It is actually a bash script with the contents:
```bash
#!/bin/bash
# Activate python 3. has to come after path is set.
source /opt/miniconda3/etc/profile.d/conda.sh
conda activate py3
exec /opt/julia/bin/julia "$@"
```
I then have set the REPL path in the options to this file and it seems to work. It even understands shell commands right now.

**Comment by lyonsquark** [comment]
Thanks @pjssilva ! That almost worked for me. I had to do 
```bash
#!/bin/bash -l
# ...
exec /opt/julia/bin/julia "$@"
```
(the `-l` is the important part).

Thanks for the work-around.
