### ISSUE TITLE
code works inside REPL but not in debugger

### ISSUE THREAD

**Issue by xgdgsc** [julia-vscode/julia-vscode#1079]
I have an issue that the following code works inside REPL but would freeze and never return in Debugger. I'm using the externsion in ssh remote.
```
using DelimitedFiles
println("here")
sig = readdlm("/tmp/sig.csv", ',')
```
readdlm would never return in debugger.

launch config is like:

```
        {
            "type": "julia",
            "request": "launch",
            "name": "Launch julia Program",
            "program": "${workspaceFolder}/test_mz_bug.jl",
            "stopOnEntry": false
        },
```
using version 0.15.18 on windows host vscode 1.43.2 and remote ubuntu 16.04.

**Comment by davidanthoff** [comment]
How long did you wait? The debugger is quite slow because it interprets everything, and in particular something like reading files can take forever... There is nothing we can do on our end about that, this will have to be sorted out over in https://github.com/JuliaDebug/JuliaInterpreter.jl.

**Comment by xgdgsc** [comment]
Thanks for the tip. It turns out to be that slow.

**Comment by davidanthoff** [comment]
Ok, I'm closing because there is nothing we can do here :)
