### ISSUE TITLE
include not working when debugging

### ISSUE THREAD

**Issue by Eggiverse** [julia-vscode/julia-vscode#1080]
When debugging a source file which includes other source files, the included source file will not be found. 

Is seems that current_task().storage is returning "...\julialang.language-julia-0.15.18\scripts\debugger\run_debugger.jl" rather than the main source file.
This causes julia to look for included source file in folder "...\julialang.language-julia-0.15.18\scripts\debugger\“ rather than the working folder.

**Comment by lmpanalytics** [comment]
I got it to work by giving the absolute path to each included file in the module.
