### ISSUE TITLE
Add function argument names to parameter hints bubble

### ISSUE THREAD

**Issue by CameronBieganek** [julia-vscode/julia-vscode#1086]
From looking at the GIF in the wiki section on Intellisense, it appears that the function parameter hints bubbles used to include the names of the arguments. Now they don't, which leads to a loss of information. Consider `readdlm`:

![image](https://user-images.githubusercontent.com/8310743/78057583-956ed980-734c-11ea-9e5a-3cfe6c7343f9.png)

The input types are very generic, so it's hard to know what they represent just based on the type information. The full signature in the docstring (omitting keyword args) is

```julia
readdlm(source, delim::AbstractChar, T::Type, eol::AbstractChar)
```

Here we can see that the argument names are very helpful in describing what each argument means. Also, if possible it would be nice to also get keyword argument names. :)

**Comment by ZacLN** [comment]
This behaviour has been changed somewhere in the recent past.
 
`read(s::Base.BufferStream, ::Core.Type{Core.UInt8})`
