### ISSUE TITLE
How to set JULIA_EDITOR in a Julia REPL in a docker container?

### ISSUE THREAD

**Issue by hsm207** [julia-vscode/julia-vscode#1090]
I have the following line In `devcontainer.json`:

`"runArgs": [ "-e", "JULIA_EDITOR=code-insiders"]`

While inside the container, if I execute `Julia: Start REPL`  check the value of the `JULIA_EDITOR` environment variable:
```
julia> ENV["JULIA_EDITOR"]
"\"/home/user/.vscode-server-insiders/bin/6cf3dd97465b2f4f666b66758991d720e003b0f4/node\""
```

On the other hand, if I instead create a new integrated terminal and run Julia from inside it, the value of `ENV["JULIA_EDITOR"]"` is equal to the value set in `runArgs`.

Is there a config somewhere that hard codes the value of `JULIA_EDITOR` inside a Julia REPL?

I am using version 0.15.

**Comment by davidanthoff** [comment]
We currently set these env vars before we start the Julia REPL [here](https://github.com/julia-vscode/julia-vscode/blob/master/src/repl.ts#L173) and [here](https://github.com/julia-vscode/julia-vscode/blob/master/src/repl.ts#L199). One thing that is almost certainly wrong there is that those two lines of code are different :)

The other questions is what the ideal setting for the remote case is... Presumably the current setting does not work, right?

**Comment by hsm207** [comment]
Yes, the current setting does not work for me.

What was the reason to define this environment variable in the first place?

I only came across this bug because I tried to use the @edit macro. Looking the Julia code [here](https://github.com/JuliaLang/julia/blob/b8e9a9ecc62ab49003bd4f1834771bdeb8cb1aa2/stdlib/InteractiveUtils/src/editless.jl#L167-L179), it already has fallbacks when none of the `JULIA_EDITOR`, `VISUAL` or `EDITOR` environment variables are defined.

**Comment by davidanthoff** [comment]
We want to make sure that if you use `@edit` inside the REPL, files open up in VS Code.

**Comment by hsm207** [comment]
if that's the case, why do we need to call `"${process.execPath}"`? Don't we just need to set the environment variables to be `code` or `code-insiders` regardless of platform?

**Comment by davidanthoff** [comment]
That would probably not work if someone didn't add VS Code to the `PATH`, right?

**Comment by hsm207** [comment]
I created a Debian container and installed VS code using this [instructions](https://code.visualstudio.com/docs/setup/linux#_debian-and-ubuntu-based-distributions). Executing `which code` returns `/usr/bin/code`.

On my Windows 10 machine, I can run `code-insiders` without having to tweak any environment variables.

Inside a docker container, `code-insiders` is in `/home/user/.vscode-server-insiders/bin/6cf3dd97465b2f4f666b66758991d720e003b0f4/bin/` and this directory is already inside `PATH`. I did not set this myself.

So it seems that if users follow the official VS Code installation instructions, everything just works and they don't have to fiddle with environment variables.

**Comment by davidanthoff** [comment]
I have a vague memory that the installer on Windows asks whether one wants to add VS Code to the PATH? I might misremember. I guess we could also just try it for a while and see whether it breaks things...

**Comment by hsm207** [comment]
I had a look at the installation instructions for [Windows](https://code.visualstudio.com/docs/setup/windows), [macOS ](https://code.visualstudio.com/docs/setup/mac)and [Linux](https://code.visualstudio.com/docs/setup/linux).

So, for Windows, `PATH` is automatically updated if it's installed using the installer (the alternative is to use a Zip archive).

For macOS, the user needs to run a command from VS Code to update `PATH`.

For Linux, `PATH` is automatically updated too (at least on Debian). I'm not sure what happens if it is installed via Snap.

**Comment by davidanthoff** [comment]
I guess another option (and maybe more stable) would be to figure out whether we can somehow reliably find the path. For example, we could detect when the call to `process.execPath` returns the `/home/user/.vscode-server-insiders/bin/6cf3dd97465b2f4f666b66758991d720e003b0f4/node` path, we could from that deduce that we need to set the env var to `/home/user/.vscode-server-insiders/bin/6cf3dd97465b2f4f666b66758991d720e003b0f4/bin/code` (or `code-insider`), right?

**Comment by hsm207** [comment]
I think it's a good idea and made PR #1103 based on it.
