### ISSUE TITLE
The extension becomes unresponsive

### ISSUE THREAD

**Issue by manuelelucchi** [julia-vscode/julia-vscode#1097]
Hi, I have a big problem. After some coding the extension becomes completely unresponsive, no more linter/intellisense, if i hover on a keyword it just gets stuck in an infinite "loading". Before i thought it was because of the package env, so i tried with some files in a folder and i realized it happens when you try to include other files. After it broke, even if i restart the computer the folder will be forever gone and i have to move all the files in another folder. Another strange thing (that could be related) is that if i try to start the debugger in a file with an inclusion, the debugger will crash being unable to find the inclusion (again, all the files are in the same folder and i include them with include("filename.jl"))

I hope I've been clear

**Comment by davidanthoff** [comment]
Do you get a message that the language server crashed? If so, the most helpful step is to send a crash report to us, that has a lot of info that can help us fix the problem.

**Comment by manuelelucchi** [comment]
I've got it only the first time it happened but it fixed itself after the reload of the extension. By the way, i just managed to fix it commenting a line, reloading the extension and then remove the comment. Tomorrow i'll let you know if it brokes again

**Comment by manuelelucchi** [comment]
Sorry for the wait, I managed to find a situation while the incriminated behavior happens (there's an MP4 inside the zip). As you can see i just write something, delete it and the extension stop working. I noticed this mostly happens while working with includes (now i was transforming mi project to an actual module, but it's basically impossible this way)

[example.zip](https://github.com/julia-vscode/julia-vscode/files/4499699/example.zip)

**Comment by manuelelucchi** [comment]
Oh, in the meantime i was writing the issue above the extension started working again. It took something like 2-3 minutes, now next time I'll observe the background processes

**Comment by manuelelucchi** [comment]
While "loading..."

![image](https://user-images.githubusercontent.com/17146198/79693589-ca938b00-826b-11ea-8d75-64b0dd068cd5.png)

**Comment by davidanthoff** [comment]
Is this still an issue? If so, please reopen!
