### ISSUE TITLE
Treat .jmd markdown julia files as `julia` language

### ISSUE THREAD

**Issue by phlavenk** [julia-vscode/julia-vscode#1100]
Is it possible to allow in `Weave.jl` files *.jmd to have the same code execution logics as in *.jl files.
So that language-julia.executeJuliaCellInREPL  also works well in *.jmd files and executes either `##` fencing, or ```julia fencing, whatever comes first.

**Comment by davidanthoff** [comment]
So my plan is to change the whole editing experience for jmd files over to the new notebook UI that the VS Code team is working on. Once we do that the whole code running experience for jmd files will be different (more like a Jupyter notebook). I'm hesitant to add features now to the jmd experience that we will then have to remove in a few weeks when the notebook stuff is ready...

I'm marking this as ` wontfix` for now, but we can revisit if some of the plans around notebooks change.
