### ISSUE TITLE
Cannot use PackageCompiler when I start a repl using julia-vscode extension

### ISSUE THREAD

**Issue by zekeriyasari** [julia-vscode/julia-vscode#1118]
I created a sysimage using `PackageCompiler`. The problem is that when I start a repl using julia-vscode extension, the packages bundled in the sysimage are not loaded. But, when I start a repl using the terminal, the packages bundled in the sysimage are loaded and ready to used without precompilation. Am I missing something using PackageCompiler in vscode?

I am using `julia-vscode v0.15.19`

```
julia> versioninfo()
Julia Version 1.4.0
Commit b8e9a9ecc6 (2020-03-21 16:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
julia> 
```

**Comment by davidanthoff** [comment]
Are you using the VS Code built in command to create the sysimage? If so, it should automatically load that sysimage.

I would strongly recommend against replacing the default sysimage, that has the potential to break the extension in pretty thorough ways.

**Comment by zekeriyasari** [comment]
Thank you so much for your response @davidanthoff 

Initializing the repl using the VS Code built-in command and then creating the sysimage solved the problem. By the way, as you recommended, I replaced the default sysimage. Everything works fine. 

Thank you so much for this great extension.
