### ISSUE TITLE
Color coding in for loops

### ISSUE THREAD

**Issue by nicochunger** [julia-vscode/julia-vscode#1121]
Issue Type: <b>Bug</b>

I don't know if this is expected behavior, but when writing a very simple for loop the word "in" is not color-coded and stays white. I would expect it to show in another color to visually separate the variable from the iterable.

```
for i in 1:10
    println(i)
end
```

Extension version: 0.15.19
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T17:50:03.709Z)
OS version: Linux x64 5.3.0-46-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 3537)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|15.42GB (1.04GB free)|
|Process Argv|--force-user-env --no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ZacLN** [comment]
`in` is an operator and should match the highlighting of other operators. Using a theme that colours operators differently to symbols should give you the effect you're after

**Comment by davidanthoff** [comment]
I don't know, I think one can make a reasonable argument that `in` here should be treated like a language keyword, right? I mean, the syntax here makes only the use of `in` and `=` legal here, one can't just put any arbitrary operator at that position. Plus, the use of `in` here is actually distinct from the normal `in` operator, right?

**Comment by ZacLN** [comment]
I'm not sure there's much in that argument to be honest. `in` is an operator at the syntactical level and is always treated as such, the restriction on what can be used to define the iterator in loops are those you mention as well as `∈` (i.e. all operators). 

Most themes show the distinction between operators and symbols so what's to be gained from treating it as a keyword?

**Comment by davidanthoff** [comment]
> I'm not sure there's much in that argument to be honest.

Well, I guess I have to give you that ;) In any case, changes to syntax highlighting have to be made in https://github.com/JuliaEditorSupport/atom-language-julia, so if someone wants to change that, an issue or PR over there would do it :)
