### ISSUE TITLE
Add option to execute startup.jl in the LS

### ISSUE THREAD

**Issue by NightMachinary** [julia-vscode/julia-vscode#1133]
I have some helper functions and some useful imports in my `startup.jl` file, and I like to load that in the language server. I know this is "bad" practice, but perfect is the enemy of the good, and for my current needs this is the most headache-free solution.
Relevant to https://github.com/julia-vscode/julia-vscode/issues/307 , but I think not a duplicate.

**Comment by davidanthoff** [comment]
I don't want to add this to the general product, I think the LS process should never run any user code (all the trouble we go through in terms of process isolation etc. is only to achieve that goal).

We will at some point find a solution for the `LOAD_PATH` problem, hopefully, right now we just have too many other bugs that are higher priority that we need to fix first.

Is there anything else (other than the `LOAD_PATH` stuff) where this would help? I think it would be good for us to understand that, maybe we can find some other way to enable that scenario.
