### ISSUE TITLE
PWD is different between language-julia.executeJuliaBlockInREPL and language-julia.executeJuliaCellInREPL

### ISSUE THREAD

**Issue by NightMachinary** [julia-vscode/julia-vscode#1136]
`language-julia.executeJuliaCellInREPL` sets PWD to the current file's directory, while the other one sets it to the project's root. This breaks include statements.

**Comment by davidanthoff** [comment]
I think everything other than Ctrl+Enter should handle `include` statements with relative paths correctly, right?

The way Ctrl+Enter is implemented doesn't allow us to change anything about paths, it is essentially just a copy-paste of the raw code into the terminal. That is one of the main reason why we have Alt+Enter, which handles this correctly.

I guess one thing we could consider is to change Ctrl+Enter to the same code execution model that we use for Alt+Enter, just without the reliance on the language server... I have to think a bit about that, but it would probably resolve this.

**Comment by NightMachinary** [comment]
@davidanthoff You're right, I was mistaken. Only C-Enter is currently 'buggy'. Is there some magic for include statements in particular? `pwd()` always returns the project's root, and when I save plots to disk they also use the project's root as `./`.

**Comment by davidanthoff** [comment]
Yes, `include` statements pick up a task local storage value for `SOURCE_PATH`, if it is set. If that is set, `include` operates relative to that, not relative to the current `pwd`. We can't set that value for Ctlr+Enter, but for all the other execution modes we do [here](https://github.com/julia-vscode/julia-vscode/blob/master/scripts/terminalserver/repl.jl#L56).
