### ISSUE TITLE
toggle debugger support?

### ISSUE THREAD

**Issue by tbenst** [julia-vscode/julia-vscode#1137]
Hello, I saw https://github.com/julia-vscode/julia-vscode/pull/957 was merged which is super exciting. I tried using through `F9` - toggle breakpoint, but unlike Python I did not see a red dot appear nor did the debugger launch. Am I missing something obvious? Thanks!

**Comment by davidanthoff** [comment]
The debugger should just work, [here](https://discourse.julialang.org/t/ann-vs-code-extension-v0-15-released-with-debugger/36415/20) is the documentation that exists right now.

If that doesn't resolve it, please reopen this issue or follow up in some other way.

**Comment by tbenst** [comment]
Ah, thanks. The issue was that this extension requires VSCode ^1.4.4 while I was on 1.4.2. Developer console gave an error.
