### ISSUE TITLE
Debugger fails to find non-core pkgs

### ISSUE THREAD

**Issue by tbenst** [julia-vscode/julia-vscode#1138]
a file with `using LinearAlgebra` succeeds when run in debugger, but a file with `using HDF5` fails, as does any other package I try that is not from core Julia. I get:

```
Exception has occurred: ArgumentError
ArgumentError: Package StatsBase not found in current path:
- Run `import Pkg; Pkg.add("StatsBase")` to install the StatsBase package.
```

Note that shift-enter loads this package just fine, and the REPL also succeeds. The bottom bar says Julia env: v1.4, which is where I have HDF5 installed. Clicking that also shows an option for 1.0. Oddly, just doing the line `versioninfo()` in debugger fails with UnudefVarError, which makes me think that the debugger is not using PATH and somehow finding an ancient version of Julia (not sure when `versioninfo()` was added...)

Edit: if my file simply says `VERSION` I get this error:
```
ERROR: type Nothing has no field pc
Stacktrace:
 [1] getproperty(::Nothing, ::Symbol) at ./Base.jl:33
 [2] debug_request(::Base.PipeEndpoint, ::Main.VSCodeDebugger.DebuggerState, ::String, ::String) at /home/tyler/.vscode/extensions/julialang.language-julia-0.15.25/scripts/debugger/debugger_requests.jl:44
 [3] startdebug(::String) at /home/tyler/.vscode/extensions/julialang.language-julia-0.15.25/scripts/debugger/debugger.jl:80
 [4] top-level scope at /home/tyler/.vscode/extensions/julialang.language-julia-0.15.25/scripts/debugger/run_debugger.jl:6
 [5] include(::Module, ::String) at ./Base.jl:377
 [6] exec_options(::Base.JLOptions) at ./client.jl:288
 [7] _start() at ./client.jl:484
```

If my file says `println(VERSION)` and I run in debugger, this prints `1.4.0` as expected, so PATH is not the issue.

In case not clear, here are cases that work for me:
```julia
2+2
```
```julia
using LinearAlgebra
```

```julia
println(VERSION)
```

And here are failure cases
```julia
VERSION
```
```julia
using StatsBase
```
```julia
versioninfo()
```

**Comment by davidanthoff** [comment]
How are you starting the debugger?

**Comment by tbenst** [comment]
I open a text file named test.jl, and launch debugger using the debugger tab on the left column of vscode.

**Comment by davidanthoff** [comment]
I can't replicate this, I'm afraid... Note that `versioninfo` is expected to not work in a script: it is defined in `InteractiveUtils`, and that only gets loaded in interactive REPL sessions.

But what I tried now is to have an env that has `StatsBase` in it, and then I run the following file with F5:
```
VERSION

using StatsBase

println(VERSION)
```
That works just fine.

**Comment by davidanthoff** [comment]
I'm going to close this for now as we can't really do much more about this without more information.

**Comment by joaquincabezas** [comment]
I am having the same issue under a VSCode 1.51.1 on a Ubuntu 20.04. 

If a try it in a VSCode 1.51.1 on a Windows 10 machine, it works with the exact same files.

**Comment by joaquincabezas** [comment]
After updating Julia to version 1.5.3 it works under Ubuntu.
