### ISSUE TITLE
Julia REPL hangs when using @run

### ISSUE THREAD

**Issue by tbenst** [julia-vscode/julia-vscode#1139]
It seems even if I do not launch my script with the debugger, that when I do ‘using Debugger‘ in REPL and subsequently use the @run and @bp macro and run in REPL, a new REPL is opened and my old REPL is now hung. I don’t have a minimal example to reproduce this yet, but a slight variation shows a bug that’s possibly related:

```Julia
> using Debugger
> function test()
    @bp
    2
end
> @run test()
```
A debugger REPL pops open and seems to crash. Note that we do not enter the debugger.

Edit:
Figured out how to reproduce hang! If instead of `@run` REPL, you do `@enter`, I see in the bottom bar, “Starting Jupyter server: registering kernel”, which spins indefinitely

**Comment by davidanthoff** [comment]
You should not use Debugger.jl at all, the VS Code extension has its own debugging front-end that is completely independent from Debugger.jl.
