### ISSUE TITLE
Allow setting of environment variables for Julia

### ISSUE THREAD

**Issue by vchuravy** [julia-vscode/julia-vscode#1142]
I found myself in need to set `LD_LIBRARY_PATH` before starting Julia and it would be nice if I could set environment variables in general.

**Comment by davidanthoff** [comment]
Yes, we should just have a setting for that!

**Comment by oschulz** [comment]
Oh, yes, please, that would be super helpful.

**Comment by Roger-luo** [comment]
bump any updates on this?

**Comment by pfitzseb** [comment]
You can set env variables for all terminals started in VSCode already with the `terminal.integrated.env.linux` setting (adjust for your OS, of course).
