### ISSUE TITLE
[FR] Minimal Notebook: Add eval command variants that paste their output as comments

### ISSUE THREAD

**Issue by NightMachinary** [julia-vscode/julia-vscode#1145]
For example, we invoke the `eval block and paste` on this line:
```
89 + 10
```
And get:
```
89 + 10
# => 99
```
A multiline example:
```
@benchmark stdN()  samples = 10^6 seconds = Inf
# => BenchmarkTools.Trial: 
#       memory estimate:  0 bytes
#       allocs estimate:  0
#       --------------
#       minimum time:     70.875 ns (0.00% GC)
#       median time:      81.860 ns (0.00% GC)
#       mean time:        89.648 ns (0.00% GC)
#       maximum time:     55.928 μs (0.00% GC)
#       --------------
#       samples:          1000000
#       evals/sample:     97
#       <=
```
Invoking this command again should first delete the previous result. I think just using this simple `# =>` and the `# <=` should be enough to recognize the comments produced previously by this command.

We can also use exotic Unicode characters to be sure, e.g., `# ⇶` `# ⬱`.

These commands will allow a minimal notebook workflow, and work pretty well as long as we don't need images.

**Comment by davidanthoff** [comment]
That is actually a clever idea!

But, I think at this point the plan is to actually add full notebook support to the extension as soon as they ship the UI support for that  in the VS Code core product (which I think is close). And I think we don't really need this at that point.

**Comment by NightMachinary** [comment]
@davidanthoff In that case, can we at least have the current eval commands copy their output to the clipboard? It's pretty interrupting to select the output from the REPL and copy it manually ... (This can be a user option, no need to add new commands ... Though if commands should accept arguments that offers the maximum extensibility.)

**Comment by davidanthoff** [comment]
Hm, I'm a bit hesitant to add something like that because I don't know any other IDE that behaves in that way. Could you maybe just use the [clipboard](https://docs.julialang.org/en/latest/stdlib/InteractiveUtils/#InteractiveUtils.clipboard) function from the REPL to copy output to the clipboard?

**Comment by NightMachinary** [comment]
@davidanthoff I think it should be possible to hook into the ‘display’ of Julia to use this clipboard function every single time? I should also study creating extensions for vscode ... I’ll close the issue, thanks!

**Comment by davidanthoff** [comment]
Yes, I think it should be feasible to add a new display type that you push onto the multimedia stack that copies things to the clipboard all the time. Such a solution would then not just work in VS Code, but also in the normal REPL,  which would also be nice.
