### ISSUE TITLE
Cannot use REPL with Julia 1.4

### ISSUE THREAD

**Issue by sdewaele** [julia-vscode/julia-vscode#1148]
I can't start the REPL when using Julia 1.4 on Ubuntu. For example, when I run the command "Julia: start REPL" the Terminal tab is briefly highlighted, but nothing shows up. It works fine with Julia 1.3.1.

```
julia> versioninfo()
Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
```

**Comment by davidanthoff** [comment]
Hm, that is very strange... No idea right now what might cause this.

**Comment by sdewaele** [comment]
I am using plugin version 0.15.25.

I there is a way to produce a more detailed debug log, please let me know; I am happy to provide it.

**Comment by davidanthoff** [comment]
What do you have configured for `julia.executablePath`? Also, can you try to open a normal terminal in VS Code, and see what happens if you start Julia in there?

**Comment by sdewaele** [comment]
Thanks for the pointer to the settings. When I took a closer look, I noticed that I started the REPL with a custom system image generated with package compiler in 1.3, which did not work with 1.4. It works again now!

**Comment by sdewaele** [comment]
One minor comment is that there was no error message, which makes it harder to figure out what is going on.
