### ISSUE TITLE
Project module gives `missing reference` when used in `test/runtests.jl`.

### ISSUE THREAD

**Issue by akdor1154** [julia-vscode/julia-vscode#1150]
Using VSCode to create a julia pkg (my first, so this could easily be my own mistake). My package is called JWUtils and was generated with `pkg generate`.
Editing the package code in `src` works fine, but I get issues trying to write tests: in `test/runtests.jl`, when I do `using JWUtils`, VS Code reports a missing reference for this module.
![image](https://user-images.githubusercontent.com/6732831/80560265-a3834900-8a23-11ea-9d39-db0f4308d31a.png)

I am using the env of my project, my test env is not available to select in the status bar. 
Actually running the tests with `pkg test` in my JWUtils env works fine.

There was a note in the `pkg` docs that your module is automatically added to your test environment, so maybe that is some magic that the vscode extension should duplicate?

EDIT: ah this might actually be #1023, I assumed it was specific to the test system.

**Comment by davidanthoff** [comment]
Yeah, I think this is a duplicate, this is on our radar and hopefully we can fix it soon. I'm going to close this issue.
