### ISSUE TITLE
How to run a file without debugger and without lint

### ISSUE THREAD

**Issue by MartinOtter** [julia-vscode/julia-vscode#1151]
I switched to 0.15.xx just now and running a file with F5 needs about 45 seconds to start. In 0.14.x, it started within 1-2 seconds. The reason seems to be that debugger is automatically started and also lint. 

How to run a julia file in a convenient way without debugger (I do not want to type in the command "include(<file>)" in the REPL)?

**Comment by MartinOtter** [comment]
In the Toolbar it is stated:

<Ctrl> F5: Run without debugging

But on my machine (Windows 10), this has no effect (runs with the debugger)

**Comment by davidanthoff** [comment]
Ctrl+F5 does run things in a non-debug mode, but the first time you use it might be a bit slow.

The linter should not have any impact on any of this.

I don't think there is anything we can do about this at the moment, so I'm going to close this issue.

**Comment by MartinOtter** [comment]
I just tried a small Julia program that uses DifferentialEquations.jl (so pre-compiled, huge Julia package). Both when running it with <ctrl> F5 and then a second time with <ctrl> F5 it needs about 55 seconds until the program starts executing. After termination, the following statement is displayed:

![image](https://user-images.githubusercontent.com/7248038/80695180-d423bb00-8ad5-11ea-83b8-d7c5def084ff.png)

When doing the same thing with
```
include(raw"<filename>.jl")
```
it needs about 55 seconds until execution starts when this is called the first time when the julia session was started. When it is called the second time, the program starts immediately.

So, this seems that <shift> F5 always starts a new Julia session and all pre-compiled code is always newly loaded. This seems to be not practical when working with large pre-compiled Julia packages and the only remedy seems to be to manually type in the "include(..)" statement which is also not nice.

**Comment by davidanthoff** [comment]
Yes, Ctrl+F5 starts a new Julia instance evertime you run it, that behavior is just the default in VS Code.

We do have `Julia: Execute File` command (doesn't have a keyboad shortcut right now, but you can configure one) that executes the file in the REPL, in which case it will not start a new Julia instance everytime you run it.

**Comment by MartinOtter** [comment]
> We do have `Julia: Execute File` command (doesn't have a keyboad shortcut right now, but you can configure one) that executes the file in the REPL, in which case it will not start a new Julia instance everytime you run it.

Thanks for this hint. I searched a bit: When "right clicking" on the file in the explorer, the command
`Julia: Execute File` can be selected and then the file is executed.

The only minor drawback is that first the content of the file is displayed and then the file is executed. Is there an option to not display the content of the file?

**Comment by davidanthoff** [comment]
Yeah, we are going to fix the echoing soon: https://github.com/julia-vscode/julia-vscode/issues/1153
