### ISSUE TITLE
Script is being echoed to the terminal

### ISSUE THREAD

**Issue by ArchieCall** [julia-vscode/julia-vscode#1153]
On vsix 0.15.27 the whole script is being echoed to the terminal before any execution starts. If the script is long (say 2000 lines) there is a sizeable time lag, and the terminal is cluttered up with needless lines that are just repeating what is already in the editor.

**Comment by davidanthoff** [comment]
So my current idea is that when one executes a whole file, that we just echo an `include("bla bla")`? Would that make sense?

**Comment by ZenanH** [comment]
I also ran into the problem above🙋, if terminal can just return “include(...)” or show nothing as before, both are fine for me.

**Comment by ArchieCall** [comment]
That is how I work around the issue on the latest version.  It must have
worked that way with the version that was only 10 days old as it does not
echo to the terminal.

**Comment by ArchieCall** [comment]
This issue is shown as being closed and I do not think it has been corrected!  Also if it opened back up, could the Juno Parity label be applied... Thanks.

**Comment by davidanthoff** [comment]
Issue is still open :)

I'm not going to apply the Juno label, mostly because this issue is quite trivial to fix and we want to keep the Juno label for big features where we are missing parity, i.e. the things where the two teams need to have some extensive design discussions.

**Comment by pfitzseb** [comment]
Fiexd now.
