### ISSUE TITLE
executable path

### ISSUE THREAD

**Issue by Bestelwagentje99** [julia-vscode/julia-vscode#1156]
Hello

I just installed the julia extension for VS Code, but I couldn't find the executable julia file. could you tell me how to find it? (what it's name is would already help) I work on Ubuntu 18.04 (and still getting to know it, probably the reason why I can't find the file ;)).

Thank you very much!!

**Comment by davidanthoff** [comment]
It all depends where you installed it :) The name should just be `julia`.

If `julia` is on your path, the extension should just find it automatically.

I think if you have more questions on this, ideally ask over at https://discourse.julialang.org/c/tools/vscode/42, we use the issues here to track the work for the dev team.
