### ISSUE TITLE
Cache "Indexing" results for standalone Julia files?

### ISSUE THREAD

**Issue by kbarros** [julia-vscode/julia-vscode#1162]
Hi, I'm currently running Julia Insider, v0.15.29.

When I open a Julia package directory within a VSCode workspace, it indexes all environment packages once, and then (presumably) caches that analysis to disk. If I restart the VSCode application and reload that workspace, then the plugin quickly recovers the indexing analysis. (By the way, where is it being stored on disk?)

However, if I open a standalone Julia file (`foo.jl`) not part of a Julia package or a VSCode workspace, then it appears the VSCode analysis caching mechanism is broken. Every time I restart the VSCode application and open this file, the indexing analysis must be restarted from scratch.

I would expect that the indexing analysis could be cached to disk for both Julia packages and Julia standalone files.

Related issues are https://github.com/julia-vscode/julia-vscode/issues/577 and https://github.com/julia-vscode/julia-vscode/issues/927 .

**Comment by CameronBieganek** [comment]
+1

I think I'm having this problem also. It seems like basically every time I open VS Code the Language Server has to recreate the index. VS Code is still usable while this happens, but the Language Server gets my laptop fan running for 10-15 minutes every time I open VS Code. ☹️

**Comment by davidanthoff** [comment]
Hm, so there really shouldn't be a difference between these two cases... BUT, we did recache everything in the past whenever we shipped a new version of the extension. Which we started doing fairly frequently, so maybe you just happened to try this between extension updates?

The latest version we shipped should preserve the cache across extension version updates. Maybe you could check  whether this problem is still there with the latest version?

**Comment by kbarros** [comment]
I will try again and report back soon. Just to confirm, I am running 0.15.29, which seems to be the latest version on Julia Insider. Is this the "latest version" you're referring to?

**Comment by CameronBieganek** [comment]
> maybe you just happened to try this between extension updates?

Yeah, that could be. I didn't do a very careful test of my claim. :)

**Comment by kbarros** [comment]
Perhaps I was also caught between updates, because I can no longer reproduce the reported behavior.

**Comment by davidanthoff** [comment]
Excellent!
