### ISSUE TITLE
latex styled variables in vs code

### ISSUE THREAD

**Issue by mayaoguangtc** [julia-vscode/julia-vscode#1163]
As in Julia REPL, we can type in latex styled variables by using tab and \epsilon to get the greek letter and give it a value. Since I mainly write Julia codes in VS Code now, I was wondering if we could do that in vs code also? 
if yes, what is the shortcut? Seems like the REPL way is not working

**Comment by davidanthoff** [comment]
The editor should have latex completion support in the same way that it has completions support for lots of other things. You might have to wait a bit initially until the language server has started up.

**Comment by mayaoguangtc** [comment]
Thanks for the answer. I don't know if my environment is set up correctly. I have VScode and Julia extension installed. add the Julia exe path in the extension settings. The program I wrote works fine. I just can't get the latex completion work  : (

**Comment by NightMachinary** [comment]
This issue can be closed. @mayaoguangtc
