### ISSUE TITLE
command 'language-julia.debug.getActiveJuliaEnvironment' not found

### ISSUE THREAD

**Issue by Gengar-lab** [julia-vscode/julia-vscode#1165]
When I try to run my julia file in VS Code, It gives error **command 'language-julia.debug.getActiveJuliaEnvironment' not found**

![image](https://user-images.githubusercontent.com/42458260/80960165-f6933c80-8e25-11ea-9a0d-662561d410ed.png)

**Comment by daniellivingston** [comment]
I'm getting the same error on macOS.

```
Running the contributed command: 'language-julia.debug.getActiveJuliaEnvironment' failed.
```

### `julia-vscode`

- Version 1.2.5

settings.json:

```json
{
    ...
    "julia.runlinter": true,
    "terminal.integrated.commandsToSkipShell": [
        "language-julia.interrupt"
    ],
    "julia.lint.missingrefs": "all",
    "julia.environmentPath": ""
}
```

### Julia

Julia was installed via Brew:

```sh
$ which julia
/usr/local/bin/julia

$ julia --version
julia version 1.6.0
```

### VSCode

```
Visual Studio Code

Version: 1.56.2
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:44:30.902Z (1 mo ago)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 18.7.0
```

**Comment by daniellivingston** [comment]
Follow-up: issue is resolved.

`Julia: Executable Path` in `Preferences -> Settings` was set to an invalid path. Removing that path fixed the issue for me.
