### ISSUE TITLE
Document expected indexing behavior of Language Server

### ISSUE THREAD

**Issue by CameronBieganek** [julia-vscode/julia-vscode#1169]
Just wondering if we could have documentation somewhere that explains when the Language Server indexing is expected to run. Since I don't have a good understanding of when indexing is expected to run, I can't tell if the indexing that is occurring is normal or not. :)

In particular:

- Will indexing be run every time I add or update a package?
    - If so, when? And will every single package need to be re-indexed?
- Are there different indexes for different environments, projects, etc?

**Comment by davidanthoff** [comment]
I'll give a quick answer:

There is one cache file per package/version combination. Whenever you have an active project that has any package/version combination that hasn't been indexed, it will index it _only_ the missing package/version combos.

So if you add a new package to an environment, and all the other packages stay at the same version and have been indexed already, only one new package/version combo will be indexed.

Indexing is triggered at folder load time, and when you change the active environment in the VS Code UI. We should also trigger it if the `Manifest.toml` changes on disc, but that is on my TODO list.

**Comment by CameronBieganek** [comment]
Thanks! A couple follow up questions:

- Does incrementing the patch version of a package trigger a re-index?
- What happens when you have packages in develop mode?

------

> and all the other packages stay at the same version

^ Once again, I haven't been paying too close attention to this, but it seems that merely adding or updating one package triggers updates/downgrades for various other packages that are already installed. But I suppose that's unavoidable and there's not much you can do about that. :joy:

**Comment by davidanthoff** [comment]
> Does incrementing the patch version of a package trigger a re-index?

Yes, we use the same content hash id strategy that is used in `Manifest.toml` as the atomic unit that can be cashed in one file.

> What happens when you have packages in develop mode?

We compute a content hash of the folder and store that in the cache. When we check whether we need to index that deved package, we compute the content hash again, if it differs, we reindex.

> how are jll artifacts treated?

The jll packages like any other packages,  artifacts themselves we don't have as a concept at all.

> it seems that merely adding or updating one package triggers updates/downgrades for various other packages that are already installed. But I suppose that's unavoidable and there's not much you can do about that.

Yes, even simple package operations often change the version for a whole number of packages, and then all of them need to be reindexed.

**Comment by CameronBieganek** [comment]
Thanks! I guess the reason why I see a lot of indexing is because I have a package in `develop` mode and/or I frequently add or update packages. For the record, the indexing usually doesn't take too long (5-10 minutes) and it's not actually disruptive, except for my laptop fan running. 🙂

Oh, for completeness:

- Do you use a similar content hash strategy for individual Julia scripts (that are not part of a package)?
    - For example, I have some project directories (that are not packages) with multiple Julia files. How is that handled? These files are typically connected to each other via `include` statements. Does it matter which particular folder in the directory tree I open as the "root" folder in VS Code? To clarify, these projects typically don't have their own environment, I just use the default `@v1.4` environment.

Sorry for all of the possibly naive questions. :)

**Comment by davidanthoff** [comment]
Oh, you might also want to look at https://discourse.julialang.org/t/vs-code-julia-language-server-caching/38967/2, where I talk a bit about some future plans. I think once we compute the caches in the cloud and then download them, we'll only need the indexing for deved packages (and when you are offline).

We only cache packages, never individual Julia script files. Any file that is in the workspace that you are opening in VS Code is _not_ loaded or run, but instead CSTParser parses all the files and then StaticLint extracts the information from that. So essentially the story for files that are not in packages is completely different.

> Sorry for all of the possibly naive questions.

Not at all, writing these things down is a good idea no matter what!

**Comment by CameronBieganek** [comment]
> Oh, you might also want to look at https://discourse.julialang.org/t/vs-code-julia-language-server-caching/38967/2, where I talk a bit about some future plans.

Wow, that's funny. Basically the same question at the same time in two different locations. :joy:

**Comment by davidanthoff** [comment]
Yeah, instead of writing down bits and pieces in two locations I should just have written one good piece in one location ;) Well, now I'm too lazy to consolidate the info :)

**Comment by CameronBieganek** [comment]
Package indexing has seen a lot of improvements, so I'm just going to close this.
