### ISSUE TITLE
Add missing configuration options

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/julia-vscode#1170]
@ZacLN I think we probably need new configuration settings here in `package.json`, right? I just updated all the submodules and other deps here in the repo, but I'm not entirely sure what we might need in terms of new config options. Could you fix that?

**Comment by davidanthoff** [comment]
@ZacLN we now need new PRs for various packages to reflect the config options in #1172 before we can ship a new version, right?

**Comment by ZacLN** [comment]
I don't think so, which did you have in mind?

**Comment by davidanthoff** [comment]
`julia.lint.missingrefs`, I thought because the values of the enum are new we would have to update something in the packages to match those values?

**Comment by ZacLN** [comment]
No, fortunately the handling of the option in [StaticLint](https://github.com/julia-vscode/StaticLint.jl/blob/master/src/linting/checks.jl#L492) doesn't care about the name of the intermediate (i.e. nogetfield) mode.

**Comment by davidanthoff** [comment]
Ah, cool :) I'll update submodules and tag now.
