### ISSUE TITLE
Backtrace highlighting

### ISSUE THREAD

**Issue by pfitzseb** [julia-vscode/julia-vscode#1178]
Whenever Juno displays a backtrace, all lines mentioned in it are also highlighted in open editors:

![image](https://user-images.githubusercontent.com/6735977/81555233-80905780-9388-11ea-8fb6-7329bd387c51.png)

**Comment by CameronBieganek** [comment]
On a somewhat related note, if such a thing were implemented in VS Code, I would hope that there would be an option to choose between a stacktrace and an inverted stacktrace. I know that python uses an inverted stack trace like the one shown above, but I always found that confusing. It's a stack, so the most recent call should be on top of the stack. 🙂
