### ISSUE TITLE
Process Cycler

### ISSUE THREAD

**Issue by pfitzseb** [julia-vscode/julia-vscode#1180]
Juno has a mode that keeps a few Julia processes running at all times to reduce restart time. julia-vscode doesn't load too much code into the Julia process, so I'm not sure if this is particularly useful.

**Comment by davidanthoff** [comment]
I have thought a bit about this, and I'm not sure how we could implement this... Right now the Julia process for the REPL is started with the terminal creation [here](https://github.com/julia-vscode/julia-vscode/blob/148e39dff1805b315e20e699fa801ad3eda78380/src/repl.ts#L218).

I'm not sure whether [this](https://code.visualstudio.com/api/references/vscode-api#ExtensionTerminalOptions) API might allow us to somehow start a Julia process, and then later create a terminal that it connects to?

**Comment by pfitzseb** [comment]
Let's not do this.
