### ISSUE TITLE
Disable linter not working

### ISSUE THREAD

**Issue by CameronBieganek** [julia-vscode/julia-vscode#1182]
I see there's a closed issue for this (#813), but I'm running into this problem again. I normally like using the linter, but when you clone somebody else's large codebase, the number of linter warnings is too much to handle, so I disabled the linter in my workspace settings:

```julia
{
    "julia.lint.run": false,
    "julia.environmentPath": "/Users/bieganek/projects/MLJBase.jl"
}
```

However, the linter is still running over the MLJBase.jl project tree.

System: macOS 10.14.6
Julia Extension: 0.15.32
VS Code: 1.45

**Comment by ZacLN** [comment]
Same issue as #1184, closing in favour of that
