### ISSUE TITLE
Documentation Pane

### ISSUE THREAD

**Issue by aviatesk** [julia-vscode/julia-vscode#1183]
Juno's documentation pane works in two ways (and I would like to say this is _very_ useful):
- show documentation for a symbol under a cursor: just use Julia's builtin documentation system
- search for documentation with fuzzy keyword matching: we have [DocSeeker.jl](https://github.com/JunoLab/DocSeeker.jl) for that

In order to have this in VSC, we need to have our own UI within webview, since VSC doesn't offer such an API AFAIU.

**Comment by aviatesk** [comment]
ops, sorry I didn't check the existing issues

**Comment by davidanthoff** [comment]
No worries :) Always better to just close something as a duplicate than not getting it in the first place!
