### ISSUE TITLE
julia.lint.call setting ignored

### ISSUE THREAD

**Issue by CameronBieganek** [julia-vscode/julia-vscode#1184]
I have

```julia
"julia.lint.call": false
```

in my settings but I'm still getting this:

![image](https://user-images.githubusercontent.com/8310743/81585450-d0b3ed80-9379-11ea-87f4-5492f2686bf1.png)

**Comment by ZacLN** [comment]
I think we've been working under the assumption that a return of `null` from the client in response to a config request means we should set the default. It appears this isn't the case - a quick check seems to show that  for `bool` config options defaulting to true, setting the config to `false` in vscode means `null` gets sent. 

This seems mad?

**Comment by davidanthoff** [comment]
Wow, that is bad... But at least easy to fix, right?

**Comment by ZacLN** [comment]
Yeah should be straightforward though it's probably worth someone else sense checking the phenomenon before we do so though. 

You would just need to fiddle with your settings while watching the language-server-trace output pane (set to 'verbose'). "julia.lint.run", for example, should be the penultimate entry on the return message

**Comment by CameronBieganek** [comment]
This is getting a little painful. :joy:

<img src="https://user-images.githubusercontent.com/8310743/82240676-70382980-9900-11ea-87e6-3232f1a9e970.png" height="250">
