### ISSUE TITLE
Change default value of julia.useCustomSysimage from "false" to false

### ISSUE THREAD

**Issue by CameronBieganek** [julia-vscode/julia-vscode#1189]
![image](https://user-images.githubusercontent.com/8310743/81610458-2ea6fc00-939f-11ea-848e-f04b29797957.png)

https://github.com/julia-vscode/julia-vscode/blob/148e39dff1805b315e20e699fa801ad3eda78380/package.json#L473

This creates a big pink warning message in the VS Code Settings UI.

**Comment by davidanthoff** [comment]
Do you want to open a  PR?
