### ISSUE TITLE
`] activate` in Pkg mode won't take me back to default environment

### ISSUE THREAD

**Issue by CameronBieganek** [julia-vscode/julia-vscode#1194]
I don't seem to have this problem with a vanilla Julia REPL, but if I open a Julia project in VS Code when I do `] activate` in the integrated Julia REPL it won't take me back to the `@v1.4` environment. It does work if I do `] activate @v1.4`.

**Comment by davidanthoff** [comment]
Hm, maybe a single `activate` just activates whatever was active when Julia was started?

**Comment by pfitzseb** [comment]
It does, yes.

**Comment by CameronBieganek** [comment]
Oh, interesting. I didn't realize that. I guess this isn't really a bug then.

Though it's interesting that the extension remembers what environment to activate when I open a workspace even though it's not actually storing the `julia.environmentPath` setting in my workspace `settings.json` file.

**Comment by davidanthoff** [comment]
If there is no setting stored, and there is a `Project.toml`/`Manifest.toml` combo in the root, it will use that env. I suspect that is what you are seeing?

I'm closing this for now.
