### ISSUE TITLE
Syntax highlighting for function names with certain unicode characters seems broken

### ISSUE THREAD

**Issue by janbruedigam** [julia-vscode/julia-vscode#1200]
I was told this is an editor issue: https://github.com/JuliaLang/julia/issues/35866 (copy below)

Syntax highlighting for function names with a \partial symbol "∂" (and some other unicode characters) seems to be broken:
```julia
# broken:
function ∂f∂var() end # only var is highlighted 
function ∑vars() end # ∑ is not highlighted
function is⊥() end # nothing is highlighted

# works:
function ΔfΔvar() end
function δfδvar() end
function dfdvar() end
```
GitHub apparently also has some issues highlighting correctly, but for me using VS code and Julia 1.4 ΔfΔvar is highlighted correctly whereas ∂f∂var is not. I had the same issue before when using Atom.

**Comment by pfitzseb** [comment]
VSCode and GitHub both use the same syntax highlighting as Atom. 

The correct regex for valid Julia identifiers is 
``` 
r"(?:[[:alpha:]_\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}⅀-⅄∿⊾⊿⊤⊥∂∅-∇∎∏∐∑∞∟∫-∳⋀-⋃◸-◿♯⟘⟙⟀⟁⦰-⦴⨀-⨆⨉-⨖⨛⨜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃ⁱ-⁾₁-₎∠-∢⦛-⦯℘℮゛-゜𝟎-𝟡]|[^\p{^So}←-⇿])(?:[[:word:]_!\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\p{Sc}⅀-⅄∿⊾⊿⊤⊥∂∅-∇∎∏∐∑∞∟∫-∳⋀-⋃◸-◿♯⟘⟙⟀⟁⦰-⦴⨀-⨆⨉-⨖⨛⨜𝛁𝛛𝛻𝜕𝜵𝝏𝝯𝞉𝞩𝟃ⁱ-⁾₁-₎∠-∢⦛-⦯℘℮゛-゜𝟎-𝟡\p{Mn}\p{Mc}\p{Nd}\p{Pc}\p{Sk}\p{Me}\p{No}′-‷⁗]|[^\p{^So}←-⇿])*"
```
(see [here](https://gist.github.com/pfitzseb/1e5cb6c52b196bb556983959c1aef02b)). Unfortunately I couldn't get that to work with [language-julia](https://github.com/JuliaEditorSupport/atom-language-julia) yet.

**Comment by janbruedigam** [comment]
Seems like this is fixed now, thanks!
