### ISSUE TITLE
Single-line md"" doesn't parse correctly

### ISSUE THREAD

**Issue by fonsp** [julia-vscode/julia-vscode#1201]
As the screenshot demonstrates, a markdown string literal continues indefinitely:

![image](https://user-images.githubusercontent.com/6933510/81861141-1209f000-9568-11ea-89c0-531f7865df86.png)

**Julia extension `v0.15.32`**

**VS Code:**
```
Version: 1.45.0 (user setup)
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T16:18:48.860Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

Thanks for all your work!

**Comment by fonsp** [comment]
For copy paste:
```
using Markdown

f(1 + "2")

html"asdf"

f(1 + "2")

md"asdf"

f(1 + "2")
```

**Comment by fonsp** [comment]
It looks like the bug is specifically about a _single-line_ `md_str` expressions:

These fail:
```julia
md"# Hello"

md"""world"""
```

And these are fine:
```julia
md"# Hello
"

md"""
world"""
```

**Comment by pfitzseb** [comment]
Yep. I thought we had disabled markdown highlighting when the grammar transitioned into core VSCode, but this still seems to be an issue.

**Comment by IanButterworth** [comment]
Just a friendly bump on this. It breaks highlighting in this Pkg.jl source file from here onwards
https://github.com/JuliaLang/Pkg.jl/blob/1a1958fc7ee6b845bb9cd121ec3a80d08cef02c3/src/REPLMode/REPLMode.jl#L434

**Comment by fonsp** [comment]
This has been fixed!! 

<img width="245" alt="image" src="https://user-images.githubusercontent.com/6933510/155774620-4670ac0c-8cd6-4e46-b8f1-e2119eb437ec.png">

🙏🙏🙏 thank you! Now I can edit pluto notebooks with syntax highlighting!
