### ISSUE TITLE
"Default constructor" suggestion not really idiomatic

### ISSUE THREAD

**Issue by KristofferC** [julia-vscode/julia-vscode#1202]
I have a struct and the extension tells me to add this "default constructor"

```
mutable struct Parser
    data::String
    pos::Int
    prevpos::Int
    column::Int
    line::Int
    startpos::Int
    current_char::Char
    root::Dict{String, Any}
    # Suggested constructor below
    function Parser(args...)

        new(data, pos, prevpos, column, line, startpos, current_char, root)
    end
end
```

I don't think this is a very good suggestion to make. First, using inner constructors should be done rarely, cf the Julia manual:

> It is good practice to provide as few inner constructor methods as possible: only those taking all arguments explicitly and enforcing essential error checking and transformation.

Having an inner constructor removes the convert constructor for example. Also, using `new` it is possible to forget to initialize fields. 

The suggested form of the inner constructor also uses varargs which can be bit of a performance trap.

**Comment by davidanthoff** [comment]
That sounds very reasonable to me, i.e. I do think we should only offer suggestions that are in line with Julia best practices.

**Comment by pfitzseb** [comment]
Looks like were not doing this anymore.
