### ISSUE TITLE
Weird single character colored differently inside string

### ISSUE THREAD

**Issue by xgdgsc** [julia-vscode/julia-vscode#1217]
![image](https://user-images.githubusercontent.com/1189869/82187526-214dbc80-991f-11ea-9f1e-91e53985d358.png)

Weird single character colored differently inside string when using PyCall. see that "s,d.r"

**Comment by pfitzseb** [comment]
FWIW, I can't repro this, neither in VSCode nor in Atom. Are you sure this isn't happening because of some other extension?

**Comment by xgdgsc** [comment]
Doesn' t happen for me now either, nevermind,  no big deal.
