### ISSUE TITLE
zoomable and panable plot pane as in Juno

### ISSUE THREAD

**Issue by heliosdrm** [julia-vscode/julia-vscode#1227]
context: https://github.com/JunoLab/Atom.jl/pull/327 and https://discourse.julialang.org/t/ann-juno-0-12-5/39744

**Comment by davidanthoff** [comment]
Some of this might already be implemented in https://github.com/julia-vscode/julia-vscode/pull/956, not sure.

**Comment by harryscholes** [comment]
Also it would be nice if a reset button was implemented to reset the plot to the original zoom and pan

**Comment by cdsousa** [comment]
Maybe it is possible to steal the "plot viewer" of Jupyter extension https://code.visualstudio.com/docs/python/jupyter-support#_plot-viewer ...
