### ISSUE TITLE
plot didn't show image

### ISSUE THREAD

**Issue by Xinyu-Wu-0000** [julia-vscode/julia-vscode#1229]
Issue Type: <b>Bug</b>

```julia
x=0.01:0.01:1
f=x->1/(1-exp(x))
y=f.(x)
using Plots
gr()
plot(x,y,label="σ")
println("hi")
```
"hi" is printed but plot didn't work.

Extension version: 0.15.32
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:22.494Z)
OS version: Linux x64 5.4.0-31-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 4028)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|7.56GB (1.17GB free)|
|Process Argv|--no-sandbox --unity-launch /home/wuxinyu/桌面/julia.code-workspace|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by msaroufim** [comment]
When I tried to plot something today it opened in a different file, can you check if the same is happening with you please?


![image](https://user-images.githubusercontent.com/3282513/82613036-39b91380-9b79-11ea-8176-9334c268b000.png)

**Comment by Xinyu-Wu-0000** [comment]
I have checked it both in windows and ubuntu, but it didn't open in a different file. Could you please give me a code example so I can check if the problem is in my code or launch.json file.
in ubuntu:
![image](https://user-images.githubusercontent.com/57612792/82625882-e72f3400-9c18-11ea-8338-f14c1c5b6155.png)

**Comment by Xinyu-Wu-0000** [comment]
sorry very much! I have tried it in my terminal, and it failed to show the image too. So, I think the problem is in my system. Therefore, I'd close it, thanks for your time.
![image](https://user-images.githubusercontent.com/57612792/82626177-b1d71600-9c19-11ea-899f-c1d662273728.png)

**Comment by Xinyu-Wu-0000** [comment]
I am really confused. I installed some additional dependencies in Ubuntu: apt install libxt6 libxrender1 libxext6 libgl1-mesa-glx libqt5widgets5, and then it worked in my terminal, but still didn't work in vscode.

![image](https://user-images.githubusercontent.com/57612792/82626830-5c9c0400-9c1b-11ea-9e0d-ffb36bc4b944.png)

**Comment by msaroufim** [comment]
Yeah in VSCode by default it'll render images to a different tab. See the top of the 2 screenshots I posted. 

If this doesn't work for you either, can you send me a screenshot of it not working on VS Code?

![image](https://user-images.githubusercontent.com/3282513/82627798-13f33500-9ba0-11ea-9d69-5ef51bf61a07.png)

![image](https://user-images.githubusercontent.com/3282513/82627809-1b1a4300-9ba0-11ea-996b-3dd5fe69d40b.png)

**Comment by Xinyu-Wu-0000** [comment]
I have tried it, but it still didn't work.
![image](https://user-images.githubusercontent.com/57612792/82628407-5576f500-9c1f-11ea-9b87-ac3545259fa3.png)
![image](https://user-images.githubusercontent.com/57612792/82628434-6b84b580-9c1f-11ea-8502-5491dc88adaf.png)

**Comment by msaroufim** [comment]
Try removing the last ```println()``` statement

**Comment by Xinyu-Wu-0000** [comment]
still didn't work
![image](https://user-images.githubusercontent.com/57612792/82628629-e77efd80-9c1f-11ea-9c33-12681fe1c4e1.png)

**Comment by msaroufim** [comment]
How are you running the file? Try this

![image](https://user-images.githubusercontent.com/3282513/82628694-646b9200-9ba2-11ea-8d89-c3cdc8dfc7b9.png)

**Comment by Xinyu-Wu-0000** [comment]
It worked. Is it normal that F5 cann't work? 
![image](https://user-images.githubusercontent.com/57612792/82628839-860b5e80-9c20-11ea-9c40-ea4c07ace490.png)

**Comment by msaroufim** [comment]
I'm not sure why, hopefully one of the core maintainers of this library can comment on why F5 won't work

**Comment by Xinyu-Wu-0000** [comment]
And it didn't work with the `println` in the end. Thank you for your time again.

**Comment by davidanthoff** [comment]
Only the REPL is integrated with the plot pane, if you run a file with F5 or Ctrl+F5 it will spawn a new Julia process that is not connected to the plot gallery.

**Comment by Xinyu-Wu-0000** [comment]
Thank you for the answer！
