### ISSUE TITLE
Path completions

### ISSUE THREAD

**Issue by pfitzseb** [julia-vscode/julia-vscode#1245]
Would be nice to have path completions:
![image](https://user-images.githubusercontent.com/6735977/83035766-235bfd80-a03a-11ea-930b-2bf34c7ded67.png)
![image](https://user-images.githubusercontent.com/6735977/83035961-6322e500-a03a-11ea-9c4b-c035f471d284.png)

**Comment by ZacLN** [comment]
We do: https://github.com/julia-vscode/LanguageServer.jl/blob/master/src/requests/completions.jl#L344 but I don't think they're look for the `~` homedir indicator. @aviatesk , want to make a PR?

**Comment by aviatesk** [comment]
yeah, I do want, thanks for pinging me :)

**Comment by aviatesk** [comment]
well, separate from the original issue, how about making path completions list the file/directories if we don't provide a prefix ?

> in Juno:
![image](https://user-images.githubusercontent.com/40514306/83049123-a3f41b80-a085-11ea-8c52-e49f808ecc24.png)

> in vscode (completions don't activated)
![image](https://user-images.githubusercontent.com/40514306/83049291-e4539980-a085-11ea-98f1-89b6e329d1e9.png)

I think that would make it easier to find files, etc

**Comment by ZacLN** [comment]
Currently this has to be triggered manually (Ctrl-Space on my setup). I think this behaviour could be altered by adding `/` to the completionsTrigger char list
