### ISSUE TITLE
Debugging support

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/julia-vscode#125]
Currently we are waiting for some more work upstream. See [this](https://discourse.julialang.org/t/debugger-wire-protocol/488/7) discussion.

**Comment by ZacLN** [comment]
Is this possible now?

**Comment by davidanthoff** [comment]
I think to do this right we need out-of-process debugging support, i.e. ideally there would be one julia process that implements the VS Code debug adapter protocol, and then the user code that we want to debug would actually run in another julia process. I think @Keno was working on an out-of-process debugger at some point?

**Comment by ZacLN** [comment]
Can we not just control it by Stein/out?

**Comment by davidanthoff** [comment]
I think we need to be able to respond to messages even while some client code is running... There are also things like attaching to a running instance etc. But it has been a while that I looked at the debug protocol, might be worth taking a second look.

**Comment by KristofferC** [comment]
ASTInterpreter2 will only be able to step through code and will not have breakpoint support. That will likely take quite some time so I don't think you need to rush this. Of course, getting the pieces into place is a good thing though.

**Comment by ZacLN** [comment]
My thoughts were (pre-breakpoint support) to evaluate an automatically modified version of code w/ `@enter` inserted at the start of the function enclosing the breakpoint to at least allow you to get variable info and limited step-through functionality (within that closure). 

I'm aware we'd have to provide some sort of protection against nested calls but could this feasibly work? If it did then it'd allow us to get all the infrastructure into place for when proper breakpoints are supported

**Comment by davidanthoff** [comment]
@Keno what is your current thinking about an out-of-process debugger? I kind of feel a lot depends on the plans for that, given how different the whole design would be if we had that.

**Comment by szalmaf** [comment]
@davidanthoff Just curious, is there any new activity on a debugger in VS Code. It'd be so nice to have one.

**Comment by davidanthoff** [comment]
No progress so far. My best guess is that we'll have to wait until julia 1.0 ships and the core julia teams starts to work on the debugger again. But that is a guess, I have no inside info.

**Comment by Ken-B** [comment]
There seems to be some things moving on the debugger front in Julia!

Firstly, there's a debugger available in IDEA/pycharm with breakpoints:
https://discourse.julialang.org/t/jetbrains-ides-debugger-support/19703

Secondly, big improvements are being worked on at the original debugger ASTInterpreter2: 
https://github.com/JuliaDebug/ASTInterpreter2.jl/pull/37

I don't know if this will make a matlab-style debugger possible with VS Code, but I'm very hopeful nonetheless :)

**Comment by ZacLN** [comment]
This would be an ideal medium sized project for someone wanting to contribute to the extension but not knowing where to start as it's implementation would be largely orthogonal to the language server side of things

**Comment by timholy** [comment]
There's discussion ongoing in the PR flagged above. For large-scale structure https://github.com/JuliaDebug/ASTInterpreter2.jl/pull/37#issuecomment-457194413 is a good place to start. A stub implementation of [CodeTracking.jl](https://github.com/timholy/CodeTracking.jl) is available. 

Participation by vscode devs would be welcome. Also consider opening PRs/issues for fleshing out exactly what kind of "query" support you'd like to see in CodeTracking. (A PR can be just a stub implementation of an API, since the package is nothing but stub implementations for now.)

**Comment by davidanthoff** [comment]
Very exciting to see that there is stuff happening on the debugger side of things!

I won't have time anytime soon to engage with that, though, I'm afraid...

If anyone wants to work on this, there place to start at would be https://microsoft.github.io/debug-adapter-protocol/ on the VS Code side of things.

I also, more by accident, stumbled across https://github.com/judy-vscode/Judy and https://github.com/judy-vscode/Adapter. As far as I can tell that is not even using ASTInterpreter2.jl, but instead starting from scratch? Not sure, but it might be worth reaching out to that team and see what they are up to :)

I think from our end, as @ZacLN already mentioned, we would love nothing more if someone were to add a debugging story to the main julia extension itself!

**Comment by twadleigh** [comment]
Now that the debugging story for Julia proper has [achieved substantial clarity](https://julialang.org/blog/2019/03/debuggers), I suppose it is just a matter of following one's nose to make this happen at this point.

The vast majority of the time I spend in Julia involves interfacing with custom-written C++. What I would love to see for this plugin's eventual Julia debugging interface is an option to simultaneously attach gdb to the julia process and have an interface that seemlessly merges the two call stacks, _etc_.

I would love to help make that happen, but my available time for extra projects is very limited and I have more immediate priorities elsewhere. Still, I at least wanted to point out this possibility in the hope that it might get someone else with more time and capability excited enough about the potential to actually take the plunge.

**Comment by otobrzo** [comment]
The Judy debugger has following status:

> Sorry, currently we have no plan for continuing this project

**Comment by twadleigh** [comment]
I'm starting to look at this. My initial thought is to add the DAP functionality to `LanguageServer.jl` so that:
1. we can reuse the existing infrastructure for the JSON-based messaging;
2. we wouldn't need to instantiate a new process to manage a new debugging instance.

**Comment by davidanthoff** [comment]
Yes, agreed, I think if we can keep the LS and DAP stuff entirely separate, it would be better. Maybe at some point we can factor some sort of common JSON RPC package out.

I think the DAP code will actually have to run in the REPL process, right? Or, "also" run in the REPL process.

I thought we would have two modes: 1) if one presses F5 and starts the standard debug story, it would start a new Julia process and run the script one is debugging in debug mode. This is kind of the debug story that VS Code has mostly in mind, 2) if one types something like `@debug foo()` in the REPL, it would send a message to the extension that a debug session starts, starts the DAP in the REPL process, and then the extension would connect to the DAP session that is running in the REPL.

Awesome if you have time to look into this! And let me know how I can help. I don't have the time to pull this off myself right now, but happy to iterate on design and feedback etc.

**Comment by ZacLN** [comment]
I've written up most of the interface code for the debug adapter (i.e. the Julia implementation of the spec), I'll dump it into a repo tonight

**Comment by ZacLN** [comment]
https://github.com/julia-vscode/DebugAdapter.jl

**Comment by ZacLN** [comment]
Is it worthwhile at this time pulling JSONRPC out of LanguageServer? (though I think the implementation used in the debug adapter protocol is slightly different)

**Comment by twadleigh** [comment]
@ZacLN, if you're up for it, sure. Otherwise I'll make due with some copy and paste for now.

**Comment by davidanthoff** [comment]
If we pull it out, then after v0.12.0 ships? 

If they are different, then maybe it is not worth the trouble?

We will also have to come up with a plan for using packages in the REPL process in general. I think probably a custom stacked env that we ship out of the box, but in general I think that will be more robust if we have less nested dependencies.

**Comment by ZacLN** [comment]
Yep that sounds fine. I think the only difference is that DebugAdapter omits the Content-Type part of the header (so should be easy to handle both).

**Comment by rapus95** [comment]
What is the current state of this? I really don't want to switch to Atom (slow laptop etc) thus I wait. But I'm curious nevertheless :D

**Comment by micampbell** [comment]
I am also curious to see how this goes but I'm doubtful I could be of much help.

**Comment by schlichtanders** [comment]
Juno on atom is soooo slow these days.
It is one reason, why I still cannot fully recommend julia to my colleagues.
Having full Julia support, incl. Debugger on VSCode would be perfect.

Also other open languages go for VSCode (e.g. Scala 3), so VSCode will be a natural choice for industry.

**Comment by davidanthoff** [comment]
Agreed, it would be great to have the debugger her. BUT, I don't see that happening anytime soon, unless someone new shows up and pulls this over the finishing line. Zac and I have been busy with other things, and we have a long backlog of bugs that we need to fix first.

I think that maybe in a year I might have the time to give this a go, unless of course someone else beats me to it :)

**Comment by KristofferC** [comment]
(the text interface to the debugger is pretty good and can be used from anywhere :))

**Comment by schlichtanders** [comment]
@KristofferC can you provide a link? I only used ``Juno.@enter`` so far which is not text-based

**Comment by ZacLN** [comment]
I started writing out the [debug adapter](https://github.com/julia-vscode/DebugAdapter.jl) interface with @twadleigh. tbh I got a bit stumped getting the communication with vscode

**Comment by rapus95** [comment]
@schlichtanders try Debugger.jl (`@enter command`) maybe that's where Juno.@enter comes from, not sure though.

**Comment by davidanthoff** [comment]
I can take a look at the communication part, I actually had a prototype somewhere at some point that had the communication working (but then didn't do anything).

**Comment by KristofferC** [comment]
> maybe that's where Juno.@enter comes from, not sure though.

No, the Juno debugger is a completely independent front end to the debugging functionalities in JuliaInterpreter.jl.

**Comment by davidanthoff** [comment]
This will most likely come in v0.15.0. If you want to try a _very_ brittle, early version of this, take a look at https://github.com/julia-vscode/julia-vscode/releases/tag/v0.15.0-alpha.1.

**Comment by zhangliye** [comment]
Waiting for this feature. I have tested Juno, still a lot of bugs and very difficult to use.  Thanks for providing such useful IDE for Julia community.

**Comment by amrit-poudel** [comment]
vscode julia debugger still does not work. It fails miserably even for a simple one-liner code.

**Comment by pfitzseb** [comment]
What one-liner is that?
