### ISSUE TITLE
discussion: change cell delimiter regex ?

### ISSUE THREAD

**Issue by aviatesk** [julia-vscode/julia-vscode#1256]
Currently julia vscode extension uses `^##` as a cell delimiter regex, while from v0.12.5 we had modified Juno's default delimiter so that it won't recognize YAS style section headers as cells, and we ended up with `^##(?!#)` by default.
(if interested, see https://github.com/JunoLab/atom-julia-client/pull/721 or https://discourse.julialang.org/t/ann-juno-0-12-5/39744/2?u=aviatesk).
Maybe we also want to use this here as well ?

**Comment by davidanthoff** [comment]
I can never wrap my head around regex. What would this mean in practice for how cells are delimited?

**Comment by pfitzseb** [comment]
Everything works as usual, except for `##` followed directly by another `#` (so e.g. `###`). I think we made that change because some people tend to write big
```
###########################
####### Some Header #######
###########################
```
blocks, which would count as three cells.

**Comment by davidanthoff** [comment]
Sounds good to me!
