### ISSUE TITLE
Expand selection action skips certain scopes

### ISSUE THREAD

**Issue by cloudgiant** [julia-vscode/julia-vscode#1260]
The "Expand selection" action sometimes skips certain scopes. 

### Expand selection for JS file
![js](https://user-images.githubusercontent.com/359092/83328994-23047200-a287-11ea-8fd0-b1ec4f208bf6.gif)

Different scopes like for the `if` and `for` statements are recognized properly.

### Expand selection for Julia file
![julia](https://user-images.githubusercontent.com/359092/83328997-24359f00-a287-11ea-935d-0af07de07609.gif)
the selection jumps from correct selection expansions of the `print` statement to the global scope.

Julia extension version: 0.15.36

**Comment by davidanthoff** [comment]
Interesting, I don't even know how/where this feature is implemented :) @ZacLN, is the LS handling this?

**Comment by cloudgiant** [comment]
@davidanthoff Thanks for the LS pointer. I looked at the language server protocol specification and found `Selection Range Request` (https://microsoft.github.io/language-server-protocol/specification#textDocument_selectionRange) which sounds like the part, that is not working properly.

**Comment by cloudgiant** [comment]
Should I create a new issue at https://github.com/julia-vscode/LanguageServer.jl and link this issue for context after closing it?

**Comment by ZacLN** [comment]
@davidanthoff, nope not the LS. Perhaps it vscode does something clever with the syntax highlighting file?

**Comment by davidanthoff** [comment]
@cloudgiant, yes, an issue over there would be great! It seems likely that VS Code would use that request if we supported it.

**Comment by pfitzseb** [comment]
Fixed nowadays.
