### ISSUE TITLE
VS code for Julia installation instructions

### ISSUE THREAD

**Issue by azev77** [julia-vscode/julia-vscode#1268]
I would modify the current instructions to:
1 install Julia: https://julialang.org/downloads/
2 install vscode: https://code.visualstudio.com/download
3 Install the Julia extension ... 

It might even be worth having a simple "how to install vscode for Julia" video ...

**Comment by davidanthoff** [comment]
Yes, I think simplifying them would be good, they are a bit verbose right now.

We also have the doc site, which is at https://github.com/julia-vscode/docs (hosted at https://www.julia-vscode.org/docs/dev/), probably would make sense to update that as well.

PRs would be welcome!

**Comment by azev77** [comment]
PR submitted
