### ISSUE TITLE
`Julia: Execute Code Block` raises an error on 0.16.0 insiders

### ISSUE THREAD

**Issue by singularitti** [julia-vscode/julia-vscode#1277]
I met the following error when running `Julia: Execute Code Block` after selecting a block of code

```
Command 'Julia: Execute Code Block' resulted in an error (command 'language-julia.executeJuliaBlockInREPL' not found)
onDidChangeNotification @ notificationsAlerts.ts:40
```

```julia
julia> versioninfo()
Julia Version 1.5.0-beta1.0
Commit 6443f6c95a (2020-05-28 17:42 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```

**Comment by davidanthoff** [comment]
I'm labeling this showstopper, but it just means we need to fix it before we ship the next version, there is no version out there in the release channel that has this problem.

**Comment by pfitzseb** [comment]
Turns out I forgot to remove that command. Just use `Julia: Execute Code` instead.

**Comment by luboshanus** [comment]
Hi, why you just do this? If you use `alt + enter on a Mac. Currently, it executes and moves forward but again it does not show the input I have sent to the console/REPL. (I raised something similar here: https://github.com/julia-vscode/julia-vscode/issues/1007)

What was wrong with the command `Execute Code Block`? Actually, it has been a few months that VS Code was working with julia quite well. I do not understand the motivation to remove such command...

**Comment by pfitzseb** [comment]
There's a setting for echoing the current command in the REPL.
