### ISSUE TITLE
[FR] A few missing inline-related commands

### ISSUE THREAD

**Issue by marius311** [julia-vscode/julia-vscode#1278]
(From my comment on Slack regarding 0.16.0, split into a few issues)

It would be nice to have bindable commands for:
* [ ] Move up/down by a cell 
* [x] Choose current module (currently could only find how to do so by clicking on the status bar area)
* [ ] `workbench.action.terminal.clear` moves focus to the terminal which is often unwanted as you're doing inline evaluation. might be nice if julia-vscode provided its own clear command that kept focus on the editor.

(edited to reflect things that are done)

**Comment by pfitzseb** [comment]
I think we have all of these now.
