### ISSUE TITLE
[FR] Inline results hover improvements

### ISSUE THREAD

**Issue by marius311** [julia-vscode/julia-vscode#1279]
(From my comment on Slack regarding 0.16.0, split into a few issues)

* I'm guessing that hijacking the hover to display expdandable output is a necessary (and clever) workaround of VSCode's limitations with regards to showing output, but it does mean I have to enable hover, which I otherwise had off because I find it distracting. Is there any way to enable hover only for the inline results, but not for other stuff in my Julia files?

* When hovering to expand output, it seems like the the current line gets highlighted, which is slightly disorienting (if anything should get highlighted, I'd say it should be the inline result itself which you're expanding)

* Would be nice if the hover aligned to the inline result rather the beginning of the line, and perhaps if it was only ever below the output, although maybe VSCode handles that not you guys.

**Comment by pfitzseb** [comment]
> I'm guessing that hijacking the hover to display expdandable output is a necessary (and clever) workaround of VSCode's limitations with regards to showing output, but it does mean I have to enable hover, which I otherwise had off because I find it distracting. Is there any way to enable hover only for the inline results, but not for other stuff in my Julia files?

No, I don't think there is.

> When hovering to expand output, it seems like the the current line gets highlighted, which is slightly disorienting (if anything should get highlighted, I'd say it should be the inline result itself which you're expanding)

Fixed with https://github.com/julia-vscode/julia-vscode/pull/1287.

> Would be nice if the hover aligned to the inline result rather the beginning of the line, and perhaps if it was only ever below the output, although maybe VSCode handles that not you guys.

Mostly fixed with https://github.com/julia-vscode/julia-vscode/pull/1287. VSCode collects all highlights on the current line (or maybe cursor position), so we can't guarantee positioning.
