### ISSUE TITLE
[FR] Indicator of just-evaluated code

### ISSUE THREAD

**Issue by marius311** [julia-vscode/julia-vscode#1282]
(From my comment on Slack regarding 0.16.0, split into a few issues)

* I really like the thing Juno does where it flashes the evaluated code, so you get a visual confirmation that you evaluated just the part you thought you were evaluating. Is that possible here?

**Comment by pfitzseb** [comment]
https://github.com/julia-vscode/julia-vscode/pull/1211 might be an alternative.
