### ISSUE TITLE
Exec code on last character of file evaluates entire file

### ISSUE THREAD

**Issue by marius311** [julia-vscode/julia-vscode#1284]
(From my comment on Slack regarding 0.16.0, split into a few issues)

Put this in an editor and make sure there is no newline or space at the very end. Then, with the cursor at the end of the final line, run exec-code or exec-code-and-move. The whole file is evaluated. A newline or space after the cursor fixes it, as does evaluating with the cursor earlier in the line. Exec-cell seems to be unnaffected.

```julia
println(1)
##
println(2)
println(3)
```

**Comment by pfitzseb** [comment]
This is an "upstream" issue:https://github.com/julia-vscode/LanguageServer.jl/issues/716.

**Comment by marius311** [comment]
This got fixed.
