### ISSUE TITLE
Missing VS code features?

### ISSUE THREAD

**Issue by azev77** [julia-vscode/julia-vscode#1292]
I'm starting to transition to VS Code from Juno. Here are some things I'm looking to do. 
If these features already exist, please let me know how. 

1. in Juno, I can click a button on top left to automatically open a new Julia file. 
How can I do this in VS Code? 
2. In Juno I can see my "Workspace". Is this possible in VS Code?
3. In Juno, I can click button at top called "Juno" where I can interrupt Julia/ Stop Julia etc

**Comment by davidanthoff** [comment]
In VS Code you just create a new empty file with the .jl extension, there is no specific command to create a new Julia file.

Workspace is coming, but not yet done.

The only interrupt option we have is to delete the terminal.

Ideally, for questions like this, could you use the Julia discourse forum? We use this issue tracker to track our TODO lists. Also, at least here in the issue tracker it is much easier for us to not have combo issues that bring up unrelated topics.

**Comment by azev77** [comment]
> In VS Code you just create a new empty file with the .jl extension, there is no specific command to create a new Julia file.
How can I create a new empty file with the .jl extension?

OK I will use Discourse for this

**Comment by azev77** [comment]
My question got commented out: 
How can I create a new empty file with the .jl extension?

**Comment by davidanthoff** [comment]
The new file command in VS Code allows you to name your file, just give it a name that ends with .jl.

**Comment by pfitzseb** [comment]
There's also the `Change Language Mode` command.
