### ISSUE TITLE
TableView messed up when there are many columns

### ISSUE THREAD

**Issue by tk3369** [julia-vscode/julia-vscode#1299]
The table view is literally unusable when many columns are being displayed.  The columns are squeezed together and you cannot see any column name or cell values.  See [this video](https://youtu.be/aEdIEwQoJsY) for a demonstration.

Here's the code that you can use to reproduce the problem:
```julia
using DataFrames
df = DataFrame(["c$i" => rand(100) for i in 1:100]...)
```

**Comment by pfitzseb** [comment]
Should be fixed in the next version of the extension.
