### ISSUE TITLE
Tighter support for the JuliaFormatter used in Juno 

### ISSUE THREAD

**Issue by jlperla** [julia-vscode/julia-vscode#1309]
I know you are all aware of this but I didn't see any top level issues, so I thought I would create one so you don't lose it in the great editor merger.

The features of JuliaFormatter are far ahead of the default one in vscode, and it has been "tested in the wild" with Juno.  There is even https://github.com/julia-actions/julia-format to automatically add to CI and have it submit PRs.

To me, I don't see any reason you would want to use the existing VS Code formatter, though I understand that you may want to make the default settings minimalist.  I suspect that if there is something that JuliaFormatter.jl is missing to be more barebones, it could be added.

**Comment by davidanthoff** [comment]
The code formatting in the extension is powered by https://github.com/julia-vscode/DocumentFormat.jl, which also powers PkgDev.jl, the language server and the package butler story (which includes github actions that open PRs and lint). The code has been around and shipping for a very long time (certainly longer than JuliaFormatter.jl), and we have a couple of years of crash reporting for the code base, so just in terms of "does it have bugs that crash things", I'm much more comfortable with it than anything else. One thing we have learned is that you don't hear about something like 90% of bugs that crash things via issues and forums, but with crash reporting you can actually track down the long tail of problems.

I don't see us replacing DocumentFormat.jl in this entire ecosystem anytime soon. Doing so would require a lot of review and understanding work on @ZacLN's and my part, and we have an existing TODO list for the language server side of things (where this code lives) that is much higher priority and that I think will take all the bandwidth that the LS team has for at least the next year. I'm generally pretty opposed to a model where we try to just swap large chunks of working code out for something new, in my experience that is the best way to derail projects. I'm not saying "never", but I'm pretty firmly in the "certainly not anytime soon" camp.

I think the most realistic path to get improvements into the extension at this point is that folks make incremental PRs against DocumentFormat.jl, we're always happy to merge those.

**Comment by jlperla** [comment]
I have no idea (and it is none of my business!) on why the new JuliaFormatter package was created instead of patching the existing one.

What I do know is:  The current `DocumentFormat.jl` is not in any way comparable to the standard formatting tools that you would expect in other languages while  `JuliaFormatter.jl` is.  Every-time I have tried the formatter in vscode, I have `ctrl-z` back as it doesn't do the standard sorts of cleanup and spacing you would expect.

So while it is true that the code is stable, it may be because it doesn't do all that much.  Have you looked at the telemetry to see what proportion of users actually use the format feature in vscode compared to something like Juno (which uses the `JuliaFormater.jl`) let alone something like python black.  I could easily be wrong here.

> I don't see us replacing DocumentFormat.jl in this entire ecosystem anytime soon.

I wasn't suggesting you do.  I was making sure there was an issue somewhere to see if you could make the `JuliaFormatter.jl` which is standard in Juno easier to use in vscode as part of your merger.

In fact, I am not even sure why a single formatter support needs to be built into the main package at all, as it isn't with python.  https://code.visualstudio.com/docs/python/editing#_formatting  

What I had in mind not a replacement but rather just a setting to chose your formatter along those lines.  Then if someone else comes up with an even better one, or more likely a more specialized one (JuliaFormatter supports YAS but there are other styles out there) it could be swapped in.

> I think the most realistic path to get improvements into the extension at this point is that folks make incremental PRs against DocumentFormat.jl, we're always happy to merge those.

Sure.  Maybe the Juno crew can negotiate that given that the main "customer" for `JuliaFormatter.jl` is disappearing.  In the meantime, I think that a way to choose the formatting provider in vscode makes plenty of sense if it is feasible.
