### ISSUE TITLE
Error/Warning on startup and Workspace not working, Insider 16.1

### ISSUE THREAD

**Issue by IljaK91** [julia-vscode/julia-vscode#1310]
When I start Julia by executing a command, I get:

```
julia> 
Stacktrace:
julia> 1+1REPL
.LineEditREPL, ::Symbol) at .\Base.jl:33
 [2] get_main_mode() at c:\Users\Ilja\.vscode\extensions\julialang.language-julia-insider-0.16.1\scripts\terminalserver\repl.jl:15
 [3] hook_repl at c:\Users\Ilja\.vscode\extensions\julialang.language-julia-insider-0.16.1\scripts\terminalserver\terminalserver.jl:458 [inlined]
 [4] (::var"#10#12"{REPL.LineEditREPL})()2 at 
.\task.jl:358

julia> 
```

Moreover, the workspace is always empty for me.

**Comment by pfitzseb** [comment]
Do you have anything in your startup.jl?

**Comment by IljaK91** [comment]
Yes, actually a bunch of things:

```
atreplinit() do repl
    try
        @eval using Revise
        @async Revise.wait_steal_repl_backend()
        @info "Loaded Revise, 1st try."
    catch
        @warn "Could not load Revise, 1st try."
        try
            @eval using Revise
            @async Revise.wait_steal_repl_backend()
            @info "Loaded Revise, 2nd try."
        catch
            @warn "Could not load Revise, 2nd try."
        end
    end
end

@info "Loading common packages..."

using  Statistics,
       Random,
       LinearAlgebra,
       Distributions,
       AutomaticDocstrings,
       DataFrames,
       QuantEcon,
       Parameters,
       Printf,
       Plots,
       LaTeXStrings

ENV["NEWS_API_KEY"]          = MyKey
ENV["PLOTS_DEFAULT_BACKEND"] = "pyplot"
```

Is there something I should remove?

**Comment by pfitzseb** [comment]
Can you try without the `atreplinit` block?

**Comment by IljaK91** [comment]
That fixed the error message and the workspace is working now. I take that the julia extension in vscode starts with Revise activated anyways, if the appropriate box is ticked in the settings for the extension?

**Comment by pfitzseb** [comment]
Yes.

This is still something we need to fix before the actual release though.

**Comment by davidanthoff** [comment]
Are we running into an issue that [this](https://github.com/julia-vscode/julia-vscode/blob/master/scripts/terminalserver/terminalserver.jl#L468) hook of ours and the Revise hook [here](https://github.com/timholy/Revise.jl/blob/ed7236de87acece0e4f731fae245fa5682c77c9c/src/Revise.jl#L1146-L1189) are getting in each others way? Or is this some other root problem?

I am wondering whether https://github.com/julia-vscode/julia-vscode/pull/1283 might be the easiest solution to all of this... We could then also unify the hooks and just have the Julia REPL hook into things and from our hook call `revise`, which seems also cleaner.

If we were to do that, we would probably need a patch release of Revise.jl that at startup checks for say an env variable called `env["JULIA_VSCODE"]=="true"`, and if that is the case just does nothing, i.e. doesn't hook into anything etc. That would allow us to have a situation where if folks have code in their startup.jl, that would _not_ load Revise inside VS Code, but instead then defer to our own private loading of Revise.

CC @timholy.
