### ISSUE TITLE
Code completion stops working

### ISSUE THREAD

**Issue by hkraus94** [julia-vscode/julia-vscode#1322]
Hi,

when I work with the extension, I get very odd behavior. After starting vsc, everything works fine, I get the auto completions, can set unicode characters via tab-complete etc.
But sometimes, for no apparent reason, everything stops working: I get no auto completions, when trying to get some via ctrl + space, I get the "loading" button for ever. So I can't really work with the extension from that point on and need to restart vsc (if I want features other than syntax highlighting).

I am working with multiple files and using the include-command and I read on the Julia forums that someone had similar issues. If necessary, I would share the private GitHub repository with the developers of the extension.

**Comment by tautomer** [comment]
> Ok, lets just hope that this is the same problem that we are trying to fix right now.
> 
> Once we ship v0.16, if this still occurs, could you reopen this issue? For now I'm going to close it, assuming it is a duplicate.

The same problem with 0.16.11.

I think whenever I type an unicode character, the code completion will be gone a couple of sceonds after that, then I have to resatart VS Code.

https://youtu.be/X_aaHLpFBcM

**Comment by tautomer** [comment]
@davidanthoff seems the problem is already fixed in 0.17.x somehow. I haven't been seeing this issue since then.

**Comment by davidanthoff** [comment]
Great! Does anyone else still have this problem, or can we close this issue?

**Comment by hkraus94** [comment]
No problems so far with autocompletion. 16.x fixed it already.
