### ISSUE TITLE
Latex completions not working with multiple cursors

### ISSUE THREAD

**Issue by marius311** [julia-vscode/julia-vscode#1334]
julia-vscode-insider 0.6.14 / vscode 1.45.1 :

![ocr](https://user-images.githubusercontent.com/1510968/84451129-f9443700-ac06-11ea-88e6-ba399d095bd4.gif)

(PS thanks for the lightning fast fix of my other issue)

**Comment by pfitzseb** [comment]
So this is definitely a bug in our implementation, but there _also_ seems to be a bug in VSCode which makes the fix hard/impossible.

@ZacLN In theory something like
```diff
--- a/src/requests/completions.jl
+++ b/src/requests/completions.jl
@@ -56,9 +56,8 @@ end
 function latex_completions(doc, offset, partial, CIs)
     for (k, v) in REPL.REPLCompletions.latex_symbols
         if startswith(string(k), partial)
-            t1 = TextEdit(Range(doc, offset - sizeof(partial) + 1:offset), "")
-            t2 = TextEdit(Range(doc, offset - sizeof(partial):offset - sizeof(partial) + 1), v)
-            push!(CIs, CompletionItem(k[2:end], 11, missing, missing, v, missing, missing, missing, missing, missing, missing, t1, TextEdit[t2], missing, missing, missing))
+            t1 = TextEdit(Range(doc, (offset - sizeof(partial)):offset), v)
+            push!(CIs, CompletionItem(k[2:end], 11, missing, missing, v, missing, missing, missing, missing, missing, missing, t1, missing, missing, missing, missing))
         end
     end
 end
```
should work, but including the leading `\` stops VSCode from showing the completion item completely.

**Comment by marius311** [comment]
Fyi the https://github.com/YellPika/vscode-latex-input extension has this working, so presumably whatever they do can be copied?
