### ISSUE TITLE
Feature request: Jump the cursor to the end of cell right after an "Execute Code Cell and Move" command is triggered

### ISSUE THREAD

**Issue by cdsousa** [julia-vscode/julia-vscode#1339]
Feature request: Jump the cursor to the end of cell right after an "Execute Code Cell and Move" command is triggered rather than only after the code in the cell has finished its execution.
This would align more with what Juno does. But more than that, it provides better feedback to the user to know that the cell is being executed since the "circular arrow" symbol is shown in the last line of the cell (especially when the cell does not fit the visible lines).

**Comment by pfitzseb** [comment]
That's already how this works, no?
![Peek 2020-06-15 10-59](https://user-images.githubusercontent.com/6735977/84638485-5d147b80-aef7-11ea-8d1a-c2e0c4ff00b7.gif)
