### ISSUE TITLE
Disable Lint.jl

### ISSUE THREAD

**Issue by joaquimg** [julia-vscode/julia-vscode#135]
In some cases I get w whole bunch of red and green underlines in a perfectly functional code.
Being able to disable the underlines would be good.

**Comment by ZacLN** [comment]
At the moment one can disable the linter globally by adding
```    "julia.runlinter": false,```
to your user settings file. There's no way for us to disable it for a single arbitrary file at the moment as far as I can tell

**Comment by joaquimg** [comment]
returns: `Unknown configuration setting`

**Comment by joaquimg** [comment]
Disabling globally was exactly what I was looking for.

**Comment by ZacLN** [comment]
Ah apologise, this isnt in the 0.5 release. It should work if you pull the latest master branch

**Comment by davidanthoff** [comment]
But be warned, running master is not simple and might occasionally not work. Unless you are really enterprising I would wait for the next release.

**Comment by stevengj** [comment]
I have to say that having this Linting on by default is incredibly annoying.  As I type, it turns on and off squiggly underlining for almost the whole file, which is a huge visual distraction — it seems to underline practically everything while I'm in the middle of writing an expression.

**Comment by davidanthoff** [comment]
I think in general if the parser just gives up on a file, it should maybe put a little red line under the part where things go wrong, but not the whole file. That would be a heck of a lot less distracting...

@ZacLN is that something that could be done fairly easily? I think @stevengj is pretty spot on with his comment...

**Comment by ZacLN** [comment]
I'm amenable to this (isn't that how it was originally?), it may have to wait a bit though . It easy to turn off...

**Comment by stevengj** [comment]
Shouldn’t it be turned off by default until it can be improved?

It’s not that easy to turn off for new users who don’t even know where to look.

**Comment by Kiruse** [comment]
In the current version (0.14.13) the setting "julia.runlinter" no longer exists. The squiggly lines are highly distracting.

**Comment by davidanthoff** [comment]
I think we can close this issue, right? We now have a setting to turn it on and off.
