### ISSUE TITLE
Autocomplete fails sometimes

### ISSUE THREAD

**Issue by juliohm** [julia-vscode/julia-vscode#1354]
I've started playing with the IDE recently and noticed that some autocomplete combinations do not work. For instance, typing `\sigma[TAB]\^2[TAB]` does not autocomplete in VS code.

**Comment by pfitzseb** [comment]
For `\^2` you need to explicitly invoke the auto-completion menu (with e.g. `Ctrl-Space`). I suspect this happens because VSCode only triggers autocompletions when letters are typed?

**Comment by juliohm** [comment]
Do you think it would be possible to fix it or that would require a change in the IDE itself? Perhaps open an issue on VScode directly?

**Comment by pfitzseb** [comment]
This should be possible, yes.

**Comment by juliohm** [comment]
This got fixed.
