### ISSUE TITLE
Dot is inserted after pressing two spaces quickly

### ISSUE THREAD

**Issue by juliohm** [julia-vscode/julia-vscode#1358]
When I type `a[SPACE][SPACE]` very quickly a dot is inserted in the editor: `a .` Is this an issue that can be solved? This often occurs when I am trying to align a set of assignments:

```Julia
a = "foo"
long = "bar"
```

to look like:

```Julia
a    = "foo"
long = "bar"
```

**Comment by pfitzseb** [comment]
Can you check whether this happens in non-Julia files as well? I can't repro this, and afaict the extension can't (shouldn't be able to) cause that behaviour.

**Comment by juliohm** [comment]
You are correct, the behaviour is not specific to Julia files. It just happened on Markdown files. Maybe another plugin is causing it? I have `Vim`, `Julia` and `Better TOML` installed.

**Comment by pfitzseb** [comment]
https://github.com/VSCodeVim/Vim/issues/2108#issuecomment-347977957

**Comment by juliohm** [comment]
Unbelievable how MacOS has some weird settings. That is a good catch, appreciate the link!
