### ISSUE TITLE
 inline results not shown

### ISSUE THREAD

**Issue by xgdgsc** [julia-vscode/julia-vscode#1365]
`"julia.execution.resultType": "inline",` and `"julia.execution.resultType": "inline",` not working. I' m on Version: 1.46.1  julia-vscode 0.16.7

**Comment by pfitzseb** [comment]
What does "not working" mean? How did you run your code?

**Comment by xgdgsc** [comment]
In julia file and ctrl enter

**Comment by pfitzseb** [comment]
Ctrl-Enter pastes the current line into the REPL, so it doesn't use inline evaluation at all. Please use Alt-Enter instead to evaluate the current block in the editor.

**Comment by xgdgsc** [comment]
Thanks. Didn' t know that.
