### ISSUE TITLE
Visual distinction between code and inline results

### ISSUE THREAD

**Issue by jlperla** [julia-vscode/julia-vscode#1377]
The checkmark and the working gear are fine.  But having the same font/width/etc. for the inline output makes it hard to distinguih from the code itself.  For example, the results of the first is tough to tell apart from the next lines code.

![image](https://user-images.githubusercontent.com/13106721/85184594-2915bf00-b245-11ea-8d67-794e436f511d.png)

Maybe consider if it is possible to have transparency on the text, drop the font weight or change the color, etc.?

If this is all due to my font choice, then I am happy to change it and no need to change anything.

**Comment by davidanthoff** [comment]
The inline variable viewer for the debugger changes the background color of inline results to yellow, that might be another angle we could tweak.

**Comment by pfitzseb** [comment]
The visual clarity here very much depends on your theme:
![image](https://user-images.githubusercontent.com/6735977/85199189-dfcd7a00-b2ed-11ea-9f2c-facf43fd83f1.png)

Right now we're using VSCode's "widget color" (which is also used for the find overlay, for example). In theory that should provide a good amount of contrast, but apparently not for all themes.

**Comment by xgdgsc** [comment]
Is the space between code and inline result configurable?

**Comment by aviatesk** [comment]
no

**Comment by jlperla** [comment]
But you could pad things with unicode whitespace to emulate that?

**Comment by pfitzseb** [comment]
_We_ can configure that, but you, as the end user, cannot. Do you think we should move the results further to the right?

**Comment by jlperla** [comment]
> We can configure that, but you, as the end user, cannot. Do you think we should move the results further to the right?
Yeah, that doees't need user configuration.  I think more padding to the right is a good idea... or maybe there is even an innocuous looking unicode character generally not used in code  that you could use to distinguish the break between code and results (e.g. http://constructs.stampede-design.com/2014/12/unicode-symbols-replacement-font-icons/  or something like that).

@pfitzseb  While things are little better for your font (and I have no particular attachment to mine!) I think more could be done.  @davidanthoff  suggest of yellow might be a great approach.  Pretty much anything besides white.

**Comment by aviatesk** [comment]
I _guess_ yellow highlight would look too much eye-catching. I would like to suggest making the inline result **bold** or something a bit more modest.

**Comment by pfitzseb** [comment]
What do ya'll think of this?
![Peek 2020-06-22 18-26](https://user-images.githubusercontent.com/6735977/85311567-ead30680-b4b5-11ea-8eec-ed8530f06498.gif)

**Comment by jlperla** [comment]
@pfitzseb   I like it!
