### ISSUE TITLE
No documentation for debugger

### ISSUE THREAD

**Issue by lewisl** [julia-vscode/julia-vscode#1393]
Without documentation, the debugger really is impossible to setup and use.

Every language works differently in VS Code and there is no similarity between this Julia debugger and the debugger in Juno.

I have a configuration for my project, but there is no way to choose it and all the extension does is crash.

Just start with an example rather than a lengthy explanation of every option.

I am sure it must work to some degree or even as "experimental" you wouldn't have released it.  Maybe just a cut and paste of your config and how you invoked it and use of stepping, breakpoints.  

Just enough to even run it at all.

**Comment by davidanthoff** [comment]
Take a look at https://discourse.julialang.org/t/ann-vs-code-extension-v0-15-released-with-debugger/36415 until we have debugger content in the normal documentation.

You don't need any setup or config. Just open a Julia file and press F5 to start debugging.

**Comment by lewisl** [comment]
Thanks. It is non-trivial code. Functions need to be called with appropriate inputs. Should I write a tiny stub function for that (easy).

Is there compiled mode?

Is there step into since breakpoints in called functions are not seen in compiled mode?

- Lewis

On Jun 24, 2020, at 1:44 PM, David Anthoff <notifications@github.com> wrote:

﻿

Take a look at https://discourse.julialang.org/t/ann-vs-code-extension-v0-15-released-with-debugger/36415 until we have debugger content in the normal documentation.

You don't need any setup or config. Just open a Julia file and press F5 to start debugging.

**Comment by davidanthoff** [comment]
> It is non-trivial code. Functions need to be called with appropriate inputs. Should I write a tiny stub function for that (easy).

If you use F5 debugging, you just need a Julia file that runs, there are no restrictions. How you structure that is up to you. The mental model is that the file should run if you were to run it with `julia myfile.jl`, that is essentially what F5 is doing, only that it will break on breakpoints etc.

If you start the debugger from the REPL, then you'll just need to call the functions with whatever args they need.

Your other questions are all covered in my announcement post.

**Comment by lewisl** [comment]
Cool.  Will give it a try.

Will read the announcement post.

**Comment by faisal-taj** [comment]
Thanks for the excellent documentation so far, really helped in on-boarding. I have running debug setup now, with which I am able to debug in VS code. However, one thing is bothering me currently. The debugger is not able to step-into the invoked function [invoked ](https://docs.julialang.org/en/v1/base/base/#Base.invokelatest) . Is there someway to get around this issue?

**Comment by heliosdrm** [comment]
I think this issue might be closed, since the docs do have a debugger section since quite long ago.
