### ISSUE TITLE
command "Julia: Execute Code" resulted in an error (Cannot read property 'sendRequest' of null)

### ISSUE THREAD

**Issue by Jerrywang959** [julia-vscode/julia-vscode#1394]
Hi, I'm new to julia. When I type `shift+ctrl+P` and choose  `Julia:execute code`, it send me a message that `命令"Julia: Execute Code"导致错误 (Cannot read property 'sendRequest' of null)`. I don't know why, so I open this issue.

![image](https://user-images.githubusercontent.com/59097122/85731452-1dd2ff80-b72d-11ea-8989-a9ed4d02ec7b.png)

![image](https://user-images.githubusercontent.com/59097122/85732501-02b4bf80-b72e-11ea-9770-190c06ecfbc3.png)

I use vscode in Chinese language, so this messege in English means  `command "command "Julia: Execute Code" resulted in an error (Cannot read property 'sendRequest' of null)`

However, I could send a line to repl and run it. And When I run, it always shows  that `Starting Julia Language Server` in the bottom.

![image](https://user-images.githubusercontent.com/59097122/85732338-df8a1000-b72d-11ea-8d72-d23c90dfd778.png)

julia-vscode:0.16.7. vscode: 1.46.1

```julia
julia> versioninfo()
Julia Version 1.4.2
Commit 44fa15b150* (2020-05-23 18:35 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 5 4600U with Radeon Graphics
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, znver1)
Environment:
  JULIA_PKG_SERVER = https://mirrors.bfsu.edu.cn/julia/static
```

**Comment by pfitzseb** [comment]
That's an issue that happens when the language server isn't yet started up. Should be handled more gracefully though.

**Comment by Jerrywang959** [comment]
Can I ask a question? What is the "Julia language server" used for?

**Comment by pfitzseb** [comment]
Static analysis/linting/completions -- everything besides evaluating code.

**Comment by Jerrywang959** [comment]
Thank you. So How can I start Julia language server? Its status has always been "starting". Does this mean there are some problem with my configuration
