### ISSUE TITLE
Add clean inline results commands to ...

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/julia-vscode#1396]
Could we add commands that clean e.g. the inline eval results to the little `...` in the top right corner of the doc?

![image](https://user-images.githubusercontent.com/1036561/85776626-bc337680-b6d5-11ea-8ddb-41557fb653d8.png)

And maybe also the right click context menu in the editor?

**Comment by aviatesk** [comment]
We can even add markdown links to clear result/results in hover as error highlight:
![image](https://user-images.githubusercontent.com/40514306/85812526-d33c9c00-b79b-11ea-8634-b533e4633c31.png)

**Comment by pfitzseb** [comment]
Would also be good if we could use `Escape` as the keybinding for clearing the current inline result. That requires some set-up to allow the right `when` clause to trigger, and I couldn't figure out a good way for this yet.

**Comment by aviatesk** [comment]
To subscribe to cursor movements/command invocations and then check if there is an inline result or not won't be enough ?

**Comment by aviatesk** [comment]
Will we like this ?
![image](https://user-images.githubusercontent.com/40514306/86022246-0cf3f800-ba65-11ea-9d23-4c8a1b64c2af.png)
