### ISSUE TITLE
tableview gone since 0.16.8

### ISSUE THREAD

**Issue by andrstef** [julia-vscode/julia-vscode#1402]
It seems that the clickable tableview icon in the workspace window has gone with version 0.16.8.

![image](https://user-images.githubusercontent.com/49398091/85830209-81d8e080-b78c-11ea-819f-4a0cd4736f1b.png)
 
vs. 0.16.7:
![image](https://user-images.githubusercontent.com/49398091/85831280-5a831300-b78e-11ea-98d0-fac29383ec44.png)

in the meantime: Is there another way to launch the tableViewer?

I'm on Windows 10, VS Code 1.46.1 and Julia 1.4.1.

Thanks very much!

**Comment by pfitzseb** [comment]
Thanks for the report! 
You can use `vscodedisplay(df)` until this is fixed.
