### ISSUE TITLE
Julia:Execute File behaves differently than include()

### ISSUE THREAD

**Issue by pauljurczak** [julia-vscode/julia-vscode#1414]
Repost of: https://discourse.julialang.org/t/vs-code-julia-execute-file-workflow/42145

This file ("err.jl"):
```
function f()
  error("some error")
end

f()
```
produces a blank line when run with Julia:Execute File. When run with REPL:
```
julia> include("err.jl")
ERROR: some error
```
it behaves as expected. Tested with Julia v1.4.2 and VS Code extension v0.16.8.

**Comment by pfitzseb** [comment]
Dup of https://github.com/julia-vscode/julia-vscode/issues/1373. Will be fixed in the next release.

**Comment by pauljurczak** [comment]
Thank you.
