### ISSUE TITLE
Fails to import package in tests

### ISSUE THREAD

**Issue by fusion809** [julia-vscode/julia-vscode#1419]
Hi,

I've noticed some errors similar to this one described in other issues, such as [this one](https://github.com/julia-vscode/julia-vscode/issues/1204), but I think this is a distinct enough for its own issue. If I open VSCode with this extension installed to my [FunctionIntegrator.jl](https://github.com/fusion809/FunctionIntegrator.jl) repository and start tweaking the test files I get linting errors that are essentially to the effect that the functions FunctionIntegrator exports are not defined. If I go to test/runtests.jl where FunctionIntegrator is imported I see this:

![Screenshot_20200629_072219](https://user-images.githubusercontent.com/4717341/85958527-71697580-b9d9-11ea-88f1-864e1c364180.png)

I know this is an issue with julia-vscode and not my package for three reasons:

* Running my tests manually returns no errors. 
* Running the tests in Travis returns no errors.
* Juno does not report any errors. 

Thanks for your time.

**Comment by davidanthoff** [comment]
Yes, we know the linting for test folders doesn't work right now, we hope to tackle that properly after Juliacon.

**Comment by fusion809** [comment]
Is there a way to disable linting for these files until this is fixed?

**Comment by pfitzseb** [comment]
Not for the user, unfortunately. We'll hopefully get https://github.com/julia-vscode/LanguageServer.jl/pull/776 in soon though.
