### ISSUE TITLE
Publish julia-vscode at https://open-vsx.org/

### ISSUE THREAD

**Issue by bmatthiss** [julia-vscode/julia-vscode#1436]
Would it be possible to publish the julia-vscode plugin at https://open-vsx.org/? By doing so it could be used with other editors such as vs-codium.

Thx!

**Comment by davidanthoff** [comment]
The way to do this is to integrate it into our Azure Pipelines setup. We have two deploy steps, and I think we could just add another "Deploy to vsx" stage, that is behind the same approval that we have for the release channel.

**Comment by aviatesk** [comment]
Just for record here is how-to-publish: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions
Another note: our extension seems to be published there by @appelgriebsch (under the same name, but this doesn't seem to be kept updated), so it's possible it will collide with our future publications ? Not sure.

**Comment by drentsoft** [comment]
It does seem like someone has done this now. https://open-vsx.org/extension/julialang/language-julia

**Comment by amrods** [comment]
> It does seem like someone has done this now. https://open-vsx.org/extension/julialang/language-julia

But there the latest release is still 0.16.11.

**Comment by davidanthoff** [comment]
We really should integrate this into our normal CI pipeline so that things get pushed automatically.

**Comment by davidanthoff** [comment]
Ok, I just took a look at the instructions, that seems really simple, I'll have a go at this.

**Comment by davidanthoff** [comment]
I just tried this: it all works now. We are now publishing to open vsx as part of our normal CI workflow, both the release and insider version of the extension.

**Comment by amrods** [comment]
Is there any danger that the extension in open-vsx.org can be hijacked? I still see this warning at the top:
```
The namespace julialang is public, which means that everyone can publish new versions of the “Julia” extension. If you would like to become the owner of julialang, please read this guide.
```

**Comment by davidanthoff** [comment]
Yes, right now that is the case, but I requested that I/we get exclusive publishing rights for it, I think as soon as that is approved we should be good.
