### ISSUE TITLE
Crash at errors in inline evaluation

### ISSUE THREAD

**Issue by heliosdrm** [julia-vscode/julia-vscode#1441]
I have not found this reported in other current issues, perhaps my failure:

In the REPL I can run code that throws some error -- also if sent from the editor to the REPL with ctrl + Enter. But if I try to evaluate inline such code (alt + Enter), the Julia extension crashes. Attached screenshot just before the REPL terminal was closed.

(It starts with a warning telling that "Some Julia code in the VS Code extension crashed", and then a "Method error". Both related to `show_backtrace`.)

I'm using the latest extension (0.16.11) with Julia 1.3.1 in Windows 10.

![image](https://user-images.githubusercontent.com/10651028/86452081-18247d80-bd1c-11ea-8e57-77a849e62224.png)

**Comment by pfitzseb** [comment]
Fixed by https://github.com/julia-vscode/julia-vscode/pull/1435.
