### ISSUE TITLE
Crash when using "Execute File" before REPL is open

### ISSUE THREAD

**Issue by oschulz** [julia-vscode/julia-vscode#1447]
When I use "Execute File" and have no Julia REPL open yet, things crash:

```
[ Info: Precompiling VSCodeServer [9f5989ce-84fe-42d4-91ec-6a7a8d53ed0f]
[ Info: Loaded Revise.
[ Info: Loaded Rebugger.
┌ Warning: Some Julia code in the VS Code extension crashed with
│   e = type Nothing has no field current_mode
└ @ VSCodeServer ~/.vscode-server/extensions/julialang.language-julia-0.16.11/scripts/error_handler.jl:5
julia> ERROR: 
```

The crash happens in "VSCodeServer/src/repl.jl", in `hideprompt(f)` at `mode = mistate.current_mode`.

When I use "Start REPL" before "Execute File", all is fine. It used to work without, though (sorry, can't remember which version of the extension that was).

**Comment by pfitzseb** [comment]
I can't repro this error on master, so I think this should be fixed in 0.17.0 (which is on the insiders channel since yesterday).

**Comment by oschulz** [comment]
Thanks! Uh - how do I activate the insiders channel?

**Comment by pfitzseb** [comment]
It's a separate plugin:
![image](https://user-images.githubusercontent.com/6735977/86585021-0a723080-bf86-11ea-83d2-0f8a48880af8.png)

**Comment by oschulz** [comment]
Silly me, should have seen that - thanks, Sebastian!

**Comment by oschulz** [comment]
Merci!
