### ISSUE TITLE
Bug in 'single spacing following keywords' setting

### ISSUE THREAD

**Issue by srgk26** [julia-vscode/julia-vscode#1466]
Just a minor detail, but saw this while browsing Julia settings. This is for the latest julia-vscode extension. I'm not sure if this is only for my setup, but wanted to give a heads up if this is universal.

![vscode-julia-keywordspacing](https://user-images.githubusercontent.com/49290594/87092060-5adedc00-c26d-11ea-899c-4ab090413907.png)

**Comment by pfitzseb** [comment]
Should be fixed in the next version of the extension.
