### ISSUE TITLE
Auto Indent lines does not work correctly with basic function documentation

### ISSUE THREAD

**Issue by neoabs** [julia-vscode/julia-vscode#1483]
Title says it all here is before auto indent:
![image](https://user-images.githubusercontent.com/53402602/87311391-753fe080-c51f-11ea-8a6c-fc5e1bb8b597.png)
and here is after auto indent
![image](https://user-images.githubusercontent.com/53402602/87311446-8688ed00-c51f-11ea-9278-9f0019c1ffdc.png)

as result description does not work. It should look like below:
![image](https://user-images.githubusercontent.com/53402602/87311541-a7514280-c51f-11ea-90e5-632b4c97786e.png)

but after autoindent and script execution it looks as below:
![image](https://user-images.githubusercontent.com/53402602/87311624-c51ea780-c51f-11ea-94ee-efcde85e006a.png)

noncritical but extremely annoying

**Comment by aviatesk** [comment]
I guess this is a bug in our grammar spec; maybe the first `Function` word force the next line to get indented in any case.

**Comment by pfitzseb** [comment]
I don't think we can do anything about this (just like in Juno). the [`indentationRule`](https://code.visualstudio.com/api/references/vscode-api#IndentationRule)s apply regardless of whether you're in a string or not.

**Comment by aviatesk** [comment]
agh,... single line matching ...

**Comment by neoabs** [comment]
So I should write about it to MS?

BTW is there some trick to baypass it? Other than putting whole description in a single line with \n.

**Comment by neoabs** [comment]
https://github.com/microsoft/vscode/issues/83064
https://github.com/microsoft/vscode/issues/67174
...

**Comment by pfitzseb** [comment]
Don't use the auto-indent feature?
We could potentially move the indentation features here to use `onEnterRules` instead.

**Comment by pfitzseb** [comment]
Should be fixed in the next version of the extension.
