### ISSUE TITLE
Error while precompiling VSCodeServer

### ISSUE THREAD

**Issue by ericphanson** [julia-vscode/julia-vscode#1484]
I get an error when doing "start REPL" from VSCode on WSL2: 
```
[ Info: Precompiling VSCodeServer [9f5989ce-84fe-42d4-91ec-6a7a8d53ed0f]
ERROR: WARNING: --output requested, but no modules defined during run
LoadError: LOAD_PATH entries cannot contain ':'
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] load_path_setup_code(::Bool) at ./loading.jl:1137
 [3] load_path_setup_code at ./loading.jl:1130 [inlined]
 [4] create_expr_cache(::String, ::String, ::Array{Pair{Base.PkgId,UInt64},1}, ::Base.UUID) at ./loading.jl:1164
 [5] compilecache(::Base.PkgId, ::String) at ./loading.jl:1261
 [6] _require(::Base.PkgId) at ./loading.jl:1029
 [7] require(::Base.PkgId) at ./loading.jl:927
 [8] require(::Module, ::Symbol) at ./loading.jl:922
 [9] include(::Module, ::String) at ./Base.jl:377
 [10] exec_options(::Base.JLOptions) at ./client.jl:288
 [11] _start() at ./client.jl:484
in expression starting at /home/eric/.vscode-server/extensions/julialang.language-julia-0.17.1/scripts/terminalserver/terminalserver.jl:3
```

**Comment by ericphanson** [comment]
If I put a `@show joinpath(@__DIR__, "..", "packages")` in `/home/eric/.vscode-server/extensions/julialang.language-julia-0.17.1/scripts/terminalserver/terminalserver.jl` at the start, I get `/home/eric/.vscode-server/extensions/julialang.language-julia-0.17.1/scripts/terminalserver/../packages` which doesn't have a `:`, so I don't really understand the error.

**Comment by pfitzseb** [comment]
Do you have the `JULIA_LOAD_PATH` env variable set? What does `@show get(ENV, "JULIA_LOAD_PATH", "nope")` and/or  `@show Base.LOAD_PATH` print?

**Comment by ericphanson** [comment]
No I don't; I get `LOAD_PATH = ["@", "@v#.#", "@stdlib", "/home/eric/.vscode-server/extensions/julialang.language-julia-0.17.1/scripts/packages"]` if I call `@show` after the `push!` in `/home/eric/.vscode-server/extensions/julialang.language-julia-0.17.1/scripts/terminalserver/terminalserver.jl`

**Comment by ericphanson** [comment]
Huh! I just restarted VSCode and tried again, and now it worked without error. It's strange because I had seen the same error on Friday in a different session. I guess I can't reproduce so I'll close for now...

**Comment by pfitzseb** [comment]
We have some logic that's consistent with the error at
https://github.com/julia-vscode/julia-vscode/blob/b766a131cc2c4225fa8b81cf0781421957bf18bd/src/extension.ts#L134
but that shouldn't be called for the REPL process at all. Glad it's working for you though.
