### ISSUE TITLE
Revise bug : Old method not overwritten when no longer existing in file

### ISSUE THREAD

**Issue by JhnCular** [julia-vscode/julia-vscode#1485]
When I define a method in a file, then delete that method and write a new one that has a different signature, the old method is not deleted. Instead, the new method is added to the old one.

` f(x)=2`

returns ` f (generic function with 1 method)`

then file is cleared, and the following code is added and then run:

```
f(x,y)=3
```
returns `f (generic function with 2 methods)`

in the repl:

```
julia> f(1)
2

julia> f(2,3)
3
 
```

Windows 10, Julia 1.5 RC1 and julia vscode 0.17.3

pkg st : 

```
[6e4b80f9] BenchmarkTools v0.5.0
  [a93c6f00] DataFrames v0.21.4
  [587475ba] Flux v0.10.4
  [38e38edf] GLM v1.3.9
  [7073ff75] IJulia v1.21.2
  [916415d5] Images v0.22.4
  [add582a8] MLJ v0.11.5
  [91a5bcdd] Plots v1.5.2
  [438e738f] PyCall v1.91.4
  [295af30f] Revise v2.7.3
```

**Comment by davidanthoff** [comment]
This seems like a Revise.jl issue, not an extension issue?

**Comment by JhnCular** [comment]
I assumed it had something to do with the extension's revise integration. I'll try to isolate.

**Comment by JhnCular** [comment]
@davidanthoff Does my example work for you? Do I need to do anything specific to activate the revise integration?

**Comment by pfitzseb** [comment]
FWIW, I can't repro this. Did you make sure to `includet` the file you were editing?

**Comment by JhnCular** [comment]
@pfitzseb  thanks.  Executing `includet` and saving the file after editing solved the problem. Is the save step supposed to be necessary?

**Comment by pfitzseb** [comment]
Yes, that's how Revise works.

**Comment by davidanthoff** [comment]
So we can close this, right? If not, please reopen or ping us here!
