### ISSUE TITLE
julia REPL started with vscode path issue

### ISSUE THREAD

**Issue by xgdgsc** [julia-vscode/julia-vscode#1486]
In the julia REPL started with "julia: start REPL":
```
julia> Sys.which("julia")

julia> Sys.which("bash")

```
returns nothing.

While julia process started outside works.

**Comment by xgdgsc** [comment]
Suddenly it got worse.
```
compaudit:133: command not found: getent
/home/sgao/.oh-my-zsh/oh-my-zsh.sh:66: command not found: rm
detect-clipboard:33: command not found: uname
/home/sgao/.oh-my-zsh/plugins/git/git.plugin.zsh:244: command not found: awk
/home/sgao/.oh-my-zsh/custom/plugins/navi/navi.plugin.zsh:1: command not found: dirname
/home/sgao/.env:11: command not found: ls
/home/sgao/.env:11: command not found: shuf
cowsay: Could not find  cowfile!
/home/sgao/.zshrc:107: command not found: thefuck
```
only happens in julia vscode windows, outside it is fine. It used to work for `julia` command in `tasks.json` files. Now it doesn' t load the path of julia, making tasks not able to run.

**Comment by xgdgsc** [comment]
The last one only happens when using workspace file, directly opening the folder works. I guess not related to this extension. The original issue still occurs in single folder.

**Comment by likanzhan** [comment]
Is it related with the problem that the `ENV["PATH"]` is not assigned in the `Julia REPL`? 
I got the same problem.

**Comment by xgdgsc** [comment]
I found it was because `"terminal.integrated.inheritEnv": true,` set to false previously. I was trying to avoid some python `source ~/...anaconda/` on every terminal launch. Setting it to true resolves this.

**Comment by likanzhan** [comment]
Thanks, @xgdgsc 

```
"terminal.integrated.inheritEnv": true
```

solves my problem.

**Comment by davidanthoff** [comment]
Is this about the REPL that you start with `Julia: Start REPL`? Or a Julia instance that you start from a shell in the integrated terminal?

**Comment by likanzhan** [comment]
@davidanthoff. It is about the REPL started from `Julia: Start REPL`, NOT the REPL started from the shell in the integrated terminal.

**Comment by davidanthoff** [comment]
Thanks! I hadn't been aware that the `terminal.integrated.inheritEnv` setting affects that... Not super happy about that, I guess :)
