### ISSUE TITLE
Julia execution within markdown code fences

### ISSUE THREAD

**Issue by kescobo** [julia-vscode/julia-vscode#1488]
At the moment, when opening a file with language julia markdown (I've tried with both `.jmd` files and `.md` files where I manually change the language), the keyboard shortcuts for code execution (at least `Julia: execute code and move` and `Julia: send current line or selection to the REPL`) don't work.

I can run code by opening the command palette and running the proper command. 

I also attempted to change the keyboard shortcut "when" expression to `editorTextFocus && editorLangId == 'julia' || editorTextFocus &&  editorLangId == 'markdown'`, but that caused the following error:

```
Command 'Julia: Execute Code And Move' resulted in an error (document LanguageServer.URI2("file:///Users/ksb/repos/courses/CoVAnalysis/notebooks/1-sequence-stats.md") requested but not present in the JLS)
```

**Comment by kescobo** [comment]
I don't know what org-babel is, but no, I would not expect the results to be added to the file, I'd expect them to generate inline results or be sent to the REPL as they are in a `.jl` file. 

The commands work as expected when run from the command pallette, just not with keyboard shortcuts

**Comment by reumle** [comment]
On a .jmd file, `ctrl enter` now works and sends code to the REPL, but `alt enter` does nothing,.

I would expect it to show inline results as it does for my .jl files.

Feature request: enable `alt enter` to inline results on a jmd file.

Great work and thank you!

**Comment by pfitzseb** [comment]
Should be fixed in the next version of the extension (at least for actual jmd files).
