### ISSUE TITLE
LanguageServer hangs with code-insiders

### ISSUE THREAD

**Issue by lyon-fnal** [julia-vscode/julia-vscode#1490]
I’m using Julia 1.4.2 with VSCode Insiders and the Julia Insiders extension v0.17.5 on a Mac with Catalina.

Ever since extension v0.17, the LanguageServer hangs. I’m in a directory with empty Project.toml and Manifest.toml files (though I get a similar hang in an environment with dependencies - just takes longer to get to the hang). I can see the julia process that runs the LanguageServer. It runs for about 18 seconds and then never takes more CPU time. The “Starting Julia Language Server” in the VSCode status bar never changes. IntelliSense and Julia help do not work in the editor.

Here’s what I see in the Output window …

```
[ Info: Starting the Julia Language Server
[ Info: Symbol server store is at '/Users/lyon/Library/Application Support/Code - Insiders/User/globalStorage/julialang.language-julia-insider/symbolstorev2'.
[ Info: Received new data from Julia Symbol Server.
```
If I quit VSCode, the Julia Language Server process persists, never taking more CPU time. I have to manually kill the process.

Is this a known problem? Is there a way to debug this? It’s really frustrating to lose the ability to edit Julia code effectively (note that I’ve tried the regular Julia extension - which today is at the same version as the insiders - and I have the same problem).

Thanks for any help/advice! – Adam

[Note that I originally posted this to https://discourse.julialang.org/t/how-to-debug-languageserver-in-vscode-problems/43104 ]

**Comment by lyon-fnal** [comment]
On Discourse, @ZacLN suggested that I kill the LanguageServer process while VSCode is running and send the contents of the Output. Here it is...

```
[ Info: Starting the Julia Language Server
[ Info: Symbol server store is at '/Users/lyon/Library/Application Support/Code - Insiders/User/globalStorage/julialang.language-julia/symbolstorev2'.
[ Info: Received new data from Julia Symbol Server.

signal (15): Terminated: 15
in expression starting at /Users/lyon/.vscode-insiders/extensions/julialang.language-julia-0.17.5/scripts/languageserver/main.jl:19
kevent at /usr/lib/system/libsystem_kernel.dylib (unknown line)
unknown function (ip: 0x0)
Allocations: 29617290 (Pool: 29608738; Big: 8552); GC: 29
[Info  - 5:51:05 PM] Connection to server got closed. Server will restart.
[ Info: Starting the Julia Language Server
[ Info: Symbol server store is at '/Users/lyon/Library/Application Support/Code - Insiders/User/globalStorage/julialang.language-julia/symbolstorev2'.
[ Info: Received new data from Julia Symbol Server.
```

VSCode still says `Starting Julia LanguageServer...` and no more CPU time taken.

I do have message tracing turned on. Nothing exciting there ...

```
[Trace - 5:43:37 PM] Sending request 'initialize - (0)'.
[Trace - 5:51:05 PM] Sending request 'initialize - (0)'.
```

Thanks for looking into this. Let me know if there's something else I can try.

**Comment by lyon-fnal** [comment]
So, I'm assuming that the LanguageServer is working for most (all?) others. Any suggestions in figuring what's wrong with my Julia or VSCode setup/cache/configuration? Should I just delete my Julia and VSCode installations and start over? Is there a cache area that may be corrupted? Thanks for any help.

**Comment by lyon-fnal** [comment]
I did a little debugging and I discovered that the `LanguageServer` works fine with regular VSCode. It fails for VSCode-insiders...

I added a lot of `@info` statements to the LanguageServer code. When using VSCode-insiders, I can see `initialize` being called on the LanguageServer. That returns. Then VSCode never makes another request to the `LanguageServer`. My guess is that something in the initialize return convinces VSCode-insiders that it doesn't need to talk to the LanguageServer anymore. 

So it looks like there's a change in VSCode-insiders that breaks how the `LanguageSever` works. Let me know what I can do to help you figure that out.

**Comment by chelseas** [comment]
I think I am using regular VSCode with the regular Julia extension and getting this problem. 

VSCode info:
Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.5.0

Julia version: 1.4

**Comment by davidanthoff** [comment]
Do you maybe have both the insider and regular version of the extension installed? That is a scenario that doesn't work...

**Comment by richardrl** [comment]
```
 Info: Loading JuliaInterpreter from cache... (50%)
┌ Warning: CodeTracking not stored on disc
└ @ SymbolServer ~/.vscode/extensions/julialang.language-julia-1.38.2/scripts/packages/SymbolServer/src/SymbolServer.jl:247
[ Info: Loading Highlights from cache... (50%)
[ Info: Received new data from Julia Symbol Server.
```

Have same probelm. I don't have both versions installed.
