### ISSUE TITLE
Stop showing user errors for workspace in REPL

### ISSUE THREAD

**Issue by pfitzseb** [julia-vscode/julia-vscode#1491]
See https://discourse.julialang.org/t/julia-vscode-new-version-issue-with-jump/43134.

Minimal fix would be to just remove the various `@error` statements, but we could also move them into the tree view itself. Not sure if that's appropriate before JuliaCon though because it smells like a feature :)

**Comment by davidanthoff** [comment]
Yeah, lets do after Juliacon, this is weird but not really breaking anyone's workflow, right?

**Comment by pfitzseb** [comment]
It does break most REPL-centric workflows. The workspace is updated after each code execution action, so you get spammed with ~2 pages of errors no matter what you do, potentially interleaved with your intended output (because two tasks print at the same time).

**Comment by davidanthoff** [comment]
Ah, didn't realize that. I think then we should remove the `@error` statements?
