### ISSUE TITLE
Unicode autocompletion fails with multiple cursors

### ISSUE THREAD

**Issue by piever** [julia-vscode/julia-vscode#1495]
When using multiple cursors in vscode in a julia file, the unicode completion only works for one of the cursors. That is, if I try to type `\epsilon` and autocomplete on three lines, I get this result (vertical line is the three cursors):

![multicursor_unicode](https://user-images.githubusercontent.com/6333339/87692028-2f835200-c783-11ea-9a44-da1d27a8fa9a.png)

Hope the image is clear, otherwise I can see if I can somehow manage to produce a gif.

**Comment by pfitzseb** [comment]
Dup of https://github.com/julia-vscode/julia-vscode/issues/1334.
