### ISSUE TITLE
Linter finds only syntax errors and missing include files

### ISSUE THREAD

**Issue by dojt** [julia-vscode/julia-vscode#1518]
I cannot make Linting work beyond simple errors. Weirdly, it worked two weeks or so ago...??

![image](https://user-images.githubusercontent.com/57910358/88418231-edde5100-cdeb-11ea-8ce8-c14d67b2d402.png)

![image](https://user-images.githubusercontent.com/57910358/88419621-2f6ffb80-cdee-11ea-94d2-ad706bb035f0.png)

VS-Code Versions:
1.47.0 and 1.47.2 identical behavior
Version 1.47.2:
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:22:15.161Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.19.113-08528-g5803a1c7e9f9

Julia: 1.4.2

julia-vscode, StaticLint, LanguageServer, etc: I cannot find that out.

**Comment by pfitzseb** [comment]
What do you have the "Missingrefs" setting set to? It should be on `symbols` or `all`:
![image](https://user-images.githubusercontent.com/6735977/88424040-24689b80-cded-11ea-90cb-85f10c79a06f.png)

**Comment by dojt** [comment]
@pfitzseb It was set to "None" (although I didn't touch it (consciously)). I set it to "All", it works, and I feel like an idiot 😖.
Sorry for wasting you guys' time.
