### ISSUE TITLE
Argument not used in body when referenced only after the interpolation of a double quote in single quotes occurs

### ISSUE THREAD

**Issue by mattBrzezinski** [julia-vscode/julia-vscode#1519]
Extension version: `v0.17.8`

This is a super obscure bug (which I fully do not expect to be fixed), but I wanted to bring it to the light anyways. 😄 

```julia
function my_func(a::String, b::String, c::String)  # 'a' is displayed with no errors. 'b' and 'c' are greyed out saying they are not used in the body
    println(a)
    foo = "$(println('"'))"

    println(b)
    println(c)
end
```

This also occurs if `foo = "$(println('\"'))"`

All of the below examples do not result in a warning:
```julia
foo = "$(println('"'))"
foo = "$(println("'"))"
foo = "$(println('\''))"
foo = "$(println("\""))"
foo = "$(println('a'))"
foo = "$(println("a"))"
foo = "$(println(1))"
```

**Comment by ZacLN** [comment]
Thanks for reporting - this doesn't seem obscure to me at all and is  causing the parser some problems. A fix will be coming

**Comment by pfitzseb** [comment]
Pretty sure the underlying Tokenize bug here is fixed.

**Comment by mattBrzezinski** [comment]
> Pretty sure the underlying Tokenize bug here is fixed.

Yep, looks like it's resolved! 🚀
