### ISSUE TITLE
ReadLine is broken?

### ISSUE THREAD

**Issue by caseykneale** [julia-vscode/julia-vscode#1529]
```julia
function ask()
    println("...")
    lbl = readline()
    return lbl
end
s1 = ask()
```

Then in the REPL...
```julia
...
this is my user input.
```
immediately turns into,
```julia
julia> this is my user input.
ERROR: syntax: extra token "is" after end of expression
Stacktrace:
 [1] top-level scope at REPL[1]:1
```

Seems to take the user input, and turn it immediately into a REPL read function rather then interpret it as a string...

**Comment by pfitzseb** [comment]
Yeah, `readline` and other interactions with the REPL are broken when running things in the editor. "Don't do that for now" is the workaround ;)

**Comment by caseykneale** [comment]
gotchya just copy pasta into the REPL. Figured I'd let you all know because I know how big of a pain it was to get that sorted for Atom.

**Comment by pfitzseb** [comment]
Ctrl-Enter will also do the trick (because it makes the pasta for you ;))

**Comment by pfitzseb** [comment]
Dup of https://github.com/julia-vscode/julia-vscode/issues/785.
