### ISSUE TITLE
Remote Julia path does not work 

### ISSUE THREAD

**Issue by jgslazzaro** [julia-vscode/julia-vscode#1531]
Hi, I've been trying to use remote development with Julia-vscode. I can access the server perfctly via remote-ssh so there is no connection issue.

The Julia path in the server is: 

module load julia ; julia

or

module load julia && julia 

also works

But when I try to put those commands in the  executable path Julia-vscode does not recognize it.

**Comment by davidanthoff** [comment]
You can't put commands like that in there, you would only put `julia` in there.

**Comment by jgslazzaro** [comment]
Just putting julia won't work either. I have to load the module julia in
that server before using Julia.

It works in Juno, so I guess it should somehow work here too. I can't use
atom anymore so I am trying to move to vscode...

**Comment by davidanthoff** [comment]
I think you would really need https://github.com/microsoft/vscode-remote-release/issues/141 to work in your situation, right?

Another thing to try might be to open a shell in the integrated terminal and try to execute the load command there? But I'm not sure whether that load would affect the process in which the extension runs... But maybe worth a try.

**Comment by pfitzseb** [comment]
Easiest solution is to just create a shell script that does the necessary setup for you and pass through all arguments. We have instructions for that [here](http://docs.junolab.org/latest/man/remote/#Customizing-the-command-to-launch-Julia-1).

**Comment by jgslazzaro** [comment]
> I think you would really need [microsoft/vscode-remote-release#141](https://github.com/microsoft/vscode-remote-release/issues/141) to work in your situation, right?
> 
> Another thing to try might be to open a shell in the integrated terminal and try to execute the load command there? But I'm not sure whether that load would affect the process in which the extension runs... But maybe worth a try.

That would probably work, but I found the other method simpler. Thanks for your help!


> Easiest solution is to just create a shell script that does the necessary setup for you and pass through all arguments. We have instructions for that [here](http://docs.junolab.org/latest/man/remote/#Customizing-the-command-to-launch-Julia-1).

I had tried a shell script, I was not aware that the argument "$@" was needed.  Now it works like a charm!
Thanks for the help!
