### ISSUE TITLE
Ctrl+enter does not display inline result when enabled

### ISSUE THREAD

**Issue by ChrisRackauckas** [julia-vscode/julia-vscode#1540]

**Comment by pfitzseb** [comment]
That's by design. All Ctrl-Enter is supposed to do is copy-paste the current line into the REPL. I wouldn't recommend it if you can live with the initial startup time until Alt-Enter etc work.

**Comment by ChrisRackauckas** [comment]
Is that a VSCode-wide thing that Ctrl+Enter is always just pasting into the terminal?

**Comment by davidanthoff** [comment]
Should we close this? For now this is by design, and we have existing plans to redesign the execution keyboard shortcuts once the notebook stuff ships, so I don't think there is anything to do beyond that?

**Comment by ChrisRackauckas** [comment]
Sounds great, I'll be excited for the Alt+Enter future.
