### ISSUE TITLE
Ctrl+enter moves to the next line when evaluating

### ISSUE THREAD

**Issue by ChrisRackauckas** [julia-vscode/julia-vscode#1543]

**Comment by davidanthoff** [comment]
That is by design.

**Comment by ChrisRackauckas** [comment]
When will the design be fixed?

**Comment by pfitzseb** [comment]
It wont. The behaviour of this command (probably) won't change, but Ctrl-Enter will very likely resolve to a different command once the keybinding rework is in.

**Comment by ChrisRackauckas** [comment]
Why have both ctrl+enter and alt+enter have the same behavior there? Seems a little odd to make 2 key commands have that behavior and 0 have the other, instead of one command for each.

**Comment by davidanthoff** [comment]
The behavior of Alt+Enter is the future, but right now it only starts to work once the language server is up and running, which is slow right now. So we are keeping Ctrl+Enter around until we have fixed the LS startup performance problems. Once that is done, we'll probably retire the Ctrl+Enter behavior entirely and just have the behavior of Alt+Enter. At that point we might well use Ctrl+Enter as the keybinding for that behavior.

**Comment by ChrisRackauckas** [comment]
What about using Shift+Enter to reverse mirror Juno?

**Comment by davidanthoff** [comment]
Shift+Enter is already bound to execute cell and move.

But in general, we will wait with the big keyboard shortcut overhaul until the VS Code base product has shipped the notebook support and we know what keyboard bindings they are using. Whatever they decide will constrain us and then we'll have to find a story that works within that constraint.

**Comment by ChrisRackauckas** [comment]
>Shift+Enter is already bound to execute cell and move.

If Shift+Enter is execute and move, why would Ctrl+Enter and Alt+Enter both be execute and move as well?

I guess they'll have to add fix this when the notebooks are added, since it's a part of the standard Jupyter notebook interface:

```
Shift + Enter run the current cell, select below
Ctrl + Enter run selected cells
Alt + Enter run the current cell, insert below
```

With the same Ctrl+Enter and Shift+Enter behavior as Juno. For reference, RStudio has the option as well:

```
Run current line/selection | Ctrl+Enter | Cmd+Return
Run current line/selection (retain cursor position) | Alt+Enter | Option+Return
```

Spyder does too:

```
Ctrl + Enter Run cell
Shift + Enter Run cell and advance
```

and RStudio is the odd one that doesn't retain the position with Ctrl, but it's not really a big deal as long as there's an option.
