### ISSUE TITLE
Column-selection via Alt?

### ISSUE THREAD

**Issue by ChrisRackauckas** [julia-vscode/julia-vscode#1546]
Most editors (Notepad++, Sublime, IntelliJ, ...) always had a feature where you can hold alt to do column selection. Then Atom didn't have it, but it had a "Sublime-style column selection extension", and now I cannot find the equivalent.

**Comment by pfitzseb** [comment]
For the record, Alt-Shift-Click is the VSCode shortcut for this. I haven't yet found a way to switch to Alt-Click.
