### ISSUE TITLE
Automatic selection of threads to match cores

### ISSUE THREAD

**Issue by ChrisRackauckas** [julia-vscode/julia-vscode#1547]

**Comment by davidanthoff** [comment]
I think last time we discussed this we left it at this: we don't want to do anything different than base Julia out of the box, i.e. as long as Julia by default doesn't select a thread count that matches the core count, we also don't want to do that in the extension.

My preference here would actually be that Julia base would accept some value like `auto` for the `JULIA_NUM_THREADS` env variable, and then our existing logic at https://github.com/julia-vscode/julia-vscode/blob/3ef9a9c70d38974841e4728ae19b11a1484ec318/src/utils.ts#L33 would just work and be consistent with what is happening in Julia base.

**Comment by ChrisRackauckas** [comment]
Then what's the current workflow for getting multithreading working on cloud resources or with the remote execution?

**Comment by davidanthoff** [comment]
Configure `numThreads` in the remote setting to the number of threads you want? Or set `JULIA_NUM_THREADS` on your cloud resource to right value.

**Comment by ChrisRackauckas** [comment]
https://github.com/julia-vscode/julia-vscode/pull/2666 isn't a fix. It allows for `auto`, but it doesn't by default give you auto @pfitzseb

**Comment by davidanthoff** [comment]
> It allows for auto, but it doesn't by default give you auto

See previous response above:

> I think last time we discussed this we left it at this: we don't want to do anything different than base Julia out of the box, i.e. as long as Julia by default doesn't select a thread count that matches the core count, we also don't want to do that in the extension.
