### ISSUE TITLE
Add toggle view plot pane command and keybinding

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/julia-vscode#1549]
But maybe we should wait until we have a clearer picture what we will do about the plot pane in general, i.e. whether we for example will use the new plot pane we have already designed, or whether we're going to wait for a solution where the thumbnails appear as a panel...

**Comment by pfitzseb** [comment]
The uncertain future of the current implementation shouldn't stop us from exposing the commands/keybindings, because we'll need them anyways.
