### ISSUE TITLE
replacement of ASCII with no space

### ISSUE THREAD

**Issue by mmikhasenko** [julia-vscode/julia-vscode#1559]
replacement of ASCII symbols does not work when the next expression follows without space

E.g. `\theta↓SOMETHING` with a cursor at ↓ would not make the replacement after pressing `<TAB>`

**Comment by mmikhasenko** [comment]
the other thing with the replacements: I cannot find the upper indices:
`\^1`,  `\^2` - does not work,
while `\^beta` does work.

Should I write a separate issue?

**Comment by pfitzseb** [comment]
Very much depends on what follows `\theta` -- works fine when followed by something more obviously a non-word char like `.`.

That other issue can be worked around by hitting Ctrl-Space after typing `\^1`, which will open the autocomplete popup.

**Comment by mmikhasenko** [comment]
> Very much depends on what follows `\theta` -- works fine when followed by something more obviously a non-word char like `.`.

Here is an example: I want to change `θ_dep` to `ϕ_dep`. The autocompletion won't work.

> That other issue can be worked around by hitting Ctrl-Space after typing `\^1`, which will open the autocomplete popup.

nice, thanks!

**Comment by davidanthoff** [comment]
I take it that we are OK with the current behavior? I'm closing for now, but please speak up if anyone disagrees with that.
