### ISSUE TITLE
REPL process wrapper to show errors

### ISSUE THREAD

**Issue by pfitzseb** [julia-vscode/julia-vscode#1560]
...instead of hiding the terminal and all interesting output.

Upstream fix is discussed in https://github.com/microsoft/vscode/issues/70444.

**Comment by pfitzseb** [comment]
Another advantage of this is that the wrapper script could translate exit codes into something more understandable. E.g. instead of `The terminal process 'julia ...' terminated with exit code 137` we could show a "Hey, your Julia session (probably) got OOM-killed message (check [here](https://www.google.com/search?q=error+code+137) for other possible meanings)" message.

**Comment by davidanthoff** [comment]
I think ideally that wrapper would be written in Javascript, but I don't think that works, see https://github.com/microsoft/vscode/issues/100891.

We could write it in Julia, but that has a high memory and startup overhead, so we would have the same problem we had with the debugger...

Another option might be to write platform specific shell wrapper scripts, i.e. a bat file on Windows, and some simple `sh` script everywhere else?

**Comment by pfitzseb** [comment]
Closing in favor of https://github.com/julia-vscode/julia-vscode/issues/1788.
