### ISSUE TITLE
Feature Request: List Functions in a package

### ISSUE THREAD

**Issue by timothyslau** [julia-vscode/julia-vscode#1561]
It would be very convenient for the editor/console to list all the functions available inside a package:
![image](https://user-images.githubusercontent.com/3031952/89207668-5958b900-d578-11ea-998a-44ce3ab5d256.png)

similar to `R` in RStudio:
![image](https://user-images.githubusercontent.com/3031952/89207494-10086980-d578-11ea-8594-621a24bf6371.png)

or `Python` in IntellijIDE:
![image](https://user-images.githubusercontent.com/3031952/89207633-46de7f80-d578-11ea-977d-0e1f7b7f4958.png)

**Comment by pfitzseb** [comment]
Not sure what you mean -- both the REPL and the editor autocompletions are exactly what you're looking for, no?
![](https://user-images.githubusercontent.com/6735977/89211553-51256b80-d5c2-11ea-8828-1dc6f7b1a2ee.png)

**Comment by timothyslau** [comment]
Interesting, my IDE wasn't giving me that.
Must be an issue on my end, I thought it was a missing feature.
