### ISSUE TITLE
REPL Fails to open w/ Julia 1.5

### ISSUE THREAD

**Issue by markilg** [julia-vscode/julia-vscode#1569]
Fresh install vs code portable (.zip) 1.47 on windows 10. Extension versions 1.0.2, 1.0.1... REPL Opens to Julia prompt and immediately closes.

**Comment by markilg** [comment]
Fresh install vs code portable (.zip) 1.47 on windows 10.  Extension versions 1.0.2, 1.0.1... REPL Opens to Julia prompt and immediately closes.

**Comment by pfitzseb** [comment]
Try disabling the "Use Revise" option on the settings (see https://discourse.julialang.org/t/vs-code-extension-on-macos/44244).

**Comment by markilg** [comment]
Solved.
