### ISSUE TITLE
Case on table headers doesn't match data

### ISSUE THREAD

**Issue by alecloudenback** [julia-vscode/julia-vscode#1583]
The table viewer should show the field names as they are, not case modified.

This:
```julia
julia> sample = DataFrame("example" => [1, 2, 3])
3×1 DataFrame
│ Row │ example │
│     │ Int64   │
├─────┼─────────┤
│ 1   │ 1       │
│ 2   │ 2       │
│ 3   │ 3       │
```

Shows as this (note capitalized "E"):

![image](https://user-images.githubusercontent.com/711879/89713559-1aeb4180-d95e-11ea-9e05-0e52124d5d51.png)

Causes issues if you are trying to reference the table view's field names when writing code.

**Comment by pfitzseb** [comment]
Should be fixed in the next version of the extension.
