### ISSUE TITLE
Autocomplete list does not show Unicode characters

### ISSUE THREAD

**Issue by dpsanders** [julia-vscode/julia-vscode#1584]
If I start typing `\cap`, autocomplete shows the possible completions, but does not show the corresponding Unicode characters, which would be very useful.

**Comment by darsnack** [comment]
Does it never suggest Unicode characters (note that the Unicode characters themselves are not shown, just the name of the character)? I have a similar issue, except for me the Unicode characters normally appear if there is a space following my cursor. But if there is no space following, then autocomplete needs to be manually triggered, and Unicode characters do not show up in the suggestions.

**Comment by pfitzseb** [comment]
I think this has been fixed by https://github.com/julia-vscode/LanguageServer.jl/pull/811:
![image](https://user-images.githubusercontent.com/6735977/89758766-dc35c280-dae8-11ea-9177-ea443eec5bd4.png)

Note that you can expand the docs-preview thing already to get the preview:
![image](https://user-images.githubusercontent.com/6735977/89758793-f079bf80-dae8-11ea-92bb-5f9c0b525010.png)

**Comment by darsnack** [comment]
Just wanted to double-check if that resolved the issues I was trying to describe. I took screenshots this time.

Working example:
<img width="134" alt="Screen Shot 2020-08-09 at 5 00 25 PM" src="https://user-images.githubusercontent.com/4811350/89786073-fbc8ed00-dae0-11ea-90a9-202b0a17dde8.png">

Not working (auto-complete manually triggered):
<img width="116" alt="Screen Shot 2020-08-09 at 5 00 47 PM" src="https://user-images.githubusercontent.com/4811350/89786129-0edbbd00-dae1-11ea-90a2-ec83cb8b5486.png">

Not working (auto-complete manually triggered):
<img width="150" alt="Screen Shot 2020-08-09 at 5 01 12 PM" src="https://user-images.githubusercontent.com/4811350/89786158-1b601580-dae1-11ea-9e58-60b9a0acff72.png">

I think I understand now what @dpsanders was explaining which is different from what I was trying to say. I am assuming that PR did not fix the issues above? Should I file a new issue?
