### ISSUE TITLE
parameters refered in CMD literals (backticks) are not recognized

### ISSUE THREAD

**Issue by ylxdzsw** [julia-vscode/julia-vscode#1585]
![Screenshot from 2020-08-09 18-05-03](https://user-images.githubusercontent.com/7145046/89729717-fcbf3780-da6a-11ea-84ee-079a9bd8362b.png)

**Comment by pfitzseb** [comment]
Closing in favor of https://github.com/julia-vscode/julia-vscode/issues/1654.
