### ISSUE TITLE
Add a way to restart the extension

### ISSUE THREAD

**Issue by NightMachinary** [julia-vscode/julia-vscode#1586]
Sometimes the extension hits a bug, and hangs. A way to restart the extension will help in such situations.

I have encountered this in two situations:

1. The REPL display had an infinite loop bug for one of my datastructures (I don't know why, possibly there was a circular refrence in that structure somewhere.). This caused a stackoverflow and sometimes crashes. It, fortunately, didn't hang for more than 10-20 seconds.
2. The Julia explorer got stuck on showing a variable. (Possibly because of the same cause as the previous one, though the variables weren't exactly the same.) This I could not fix without restarting the whole VSCode.

**Comment by davidanthoff** [comment]
I don't think there is anything in the VS Code API that would allow us to do that, I'm afraid...

**Comment by pfitzseb** [comment]
It's also not necessary for this use case. You can just click the paper bin icon to kill the currently active Julia process. After that both of the things you mentioned should work fine again.

**Comment by NightMachinary** [comment]
[**@pfitzseb**](https://github.com/pfitzseb) commented on [Aug 10, 2020, 8:56 PM GMT+4:30](https://github.com/julia-vscode/julia-vscode/issues/1586#issuecomment-671456067 "2020-08-10T16:26:51Z - Replied by Github Reply Comments"):
> It's also not necessary for this use case. You can just click the paper bin icon to kill the currently active Julia process. After that both of the things you mentioned should work fine again.

I'm 80% sure I did that, and it didn't help for the second case. (Clicking on that bin is my standard response when Julia acts funny.)

@davidanthoff Should I close the issue since there is not enough upstream support?

**Comment by davidanthoff** [comment]
Yeah, I think we can close this. If there are concrete things that don't work after you clicked paper bin icon, then we should fix those.
