### ISSUE TITLE
Inline evaluation results not showing to right of executed expression

### ISSUE THREAD

**Issue by avalonx** [julia-vscode/julia-vscode#1588]
Inline evaluation results not showing to the right of the expression that just ran after successful execution of the code line via ctrl-enter or alt-enter (successful line execution verified in terminal output). 

VS Code
Version: 1.47.3
Commit: 91899dcef7b8110878ea59626991a18c8a6a1b3e
Date: 2020-07-23T13:08:29.692Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

I also attempted a clean reinstall of VS Code with no other extensions other than Julia and the result is the same.

What I ran was the VSCode Demo from JuliaCon2020.

**Comment by pfitzseb** [comment]
Did you set the "Result Type" setting to "inline" or "both"?

**Comment by avalonx** [comment]
I see the problem now. 
1) I didn't realize the feature was available as a setting in the preferences that needed to be switched to "inline" or "both". The Demo seemed to indicate it was a standard/default behavior.
2) After setting the preference Execution: Result Type to "both", the inline result does NOT work with Ctrl+Enter. It just advances to the next line. It will still output to REPL though. Shift+Enter works, also Alt+Enter (Option+Enter on my Mac). Only Ctrl+Enter (control + enter on my Mac) does NOT work.

**Comment by pfitzseb** [comment]
1. Fair. We should probably mention that in the docs or somewhere.
2. That's by design. Ctrl-Enter explicitly pastes the current line or selection into the REPL. You can use Alt-Enter instead.

**Comment by casasgomezuribarri** [comment]
Hi, 

I had the same problem and solved it as explained in this thread. 
However, although Alt+Enter shows the execution both inline and in the REPL, the console doesn't show what the executed line was (i.e. it I type `1+1`, both the bubble and the REPL will return simply  `2`). Is there a way I can make the bubble with `2` appear while having in the REPL something like the following?
```
>julia 1+1
2
```
