### ISSUE TITLE
Epsilon in editor is different in REPL

### ISSUE THREAD

**Issue by cojua8** [julia-vscode/julia-vscode#1589]
Hi,

I have noticed that ` \epsilon` in editor is different than the one in the REPL.

The `\epsilon` in editor matches `\varepsilon` in the REPL (and vice versa)

**Comment by pfitzseb** [comment]
I can't repro this. Are you maybe using different fonts in the editor and the terminal?
![image](https://user-images.githubusercontent.com/6735977/90026645-df32dd80-dcb7-11ea-88aa-1c9532f653d6.png)

**Comment by cojua8** [comment]
I was using a unicode extension!! 🤦‍♂️🤦‍♂️🤦‍♂️🤦‍♂️ sorry!
