### ISSUE TITLE
VS Code does not recognise code before a semicolon

### ISSUE THREAD

**Issue by pb866** [julia-vscode/julia-vscode#1591]
When Julia code is written on a single line separated by a semicolon (`;`), only the last statement is evaluated.
Typing the following line and pressing `alt+enter` in VS Code gives an error:

```julia
x = 1; x

ERROR: UndefVarError: x not defined
```

I am using VS Code version `1.0.3` together with `Julia 1.5.0` on `MacOS 10.15.6`.

**Comment by pfitzseb** [comment]
Hm, so we're actually evaluating the current expression, not the current line (so things work fine if you just select the whole line and then press Alt-Enter). Not sure if we should actually change the behaviour or just document it.

**Comment by pb866** [comment]
I don't know, how much hassle it is to change this behaviour and I guess it could be seen as a breaking change, but for me it would definitely be more convenient, if the whole line was evaluated. If I have a script or code, I often want to run it line be line to see what it does or to debug during development. Then I just have to continuously press `alt+enter` and can look at the inline results. It would be annoying to first have to select the whole line for every line that has several statements combined with a semicolon in it.

**Comment by pfitzseb** [comment]
You can do that already:
![vscode2](https://user-images.githubusercontent.com/6735977/90336270-f97ffa80-dfda-11ea-8115-d5d0619d4c33.gif)

Alt-Enter moves the cursor to the next block, *not* to the next line.

**Comment by pb866** [comment]
Ah, cool. I wasn't aware of that. I previously got an error message, but my cursor was placed at the end of the line. So this is fine, too, probably even better as every step gets evaluated separately. I just have to be more careful, where to place the cursor, when I start evaluating the code.  
However, something doesn't seem to work on my mac: when I run through the same code, I am shown `3` as a result twice when I evaluate the second line for the first time. If I go back to that line and re-evaluate it, I am shown `5` for the first expression and `3` for the second expression. (I attached a zip from a screen record, didn't know how to get the animated gif).

[Screen Recording 2020-08-16 at 16.48.56.zip](https://github.com/julia-vscode/julia-vscode/files/5080841/Screen.Recording.2020-08-16.at.16.48.56.zip)

**Comment by pfitzseb** [comment]
Fixed nowadays.
