### ISSUE TITLE
Please keep the ChangeLog up to date

### ISSUE THREAD

**Issue by zor-el** [julia-vscode/julia-vscode#1597]
Hi guys, I'm sorry for bringing this up coz' I'm sure there are more pressing matters on your plate, but I'm one of those users who generally likes to know what has changed before updating to the newest version (bad experience with braking changes, sigh), and I've noticed between 0.16.something and 1.0.3 there's _only a single entry in the changelog_ (that for 0.17).

Can we please have some proper maintenance information in there?

Thank you so much for all your work!

**Comment by pfitzseb** [comment]
Fair point, although there hasn't happened anything feature-wise between 0.17 and 1.0 -- they are the same release modulo some bug fixes.
Also take a look at the release announcements ([0.16](https://discourse.julialang.org/t/julia-vs-code-extension-version-v0-16-released/41692), [0.17](https://discourse.julialang.org/t/julia-vs-code-extension-version-v0-17-released/42865)).

**Comment by zor-el** [comment]
@pfitzseb thanks for your very quick response.

> there hasn't happened anything feature-wise between 0.17 and 1.0 -- they are the same release modulo some bug fixes.

Oh, that's unexpected given the big jump in the version number. But now I saw the extension follows the Julia version. I find that a little confusing though. Just as a hint in the Python ecosystem, packages that are bound to Python versions follow a versioning scheme along the lines of `1.0.3-Py3.7.3`. Would a scheme like that be something you guys would be open to adopt?

I'm not meaning to take the discussion off topic. I can gladly create a separate ticket for this, if that's something that you'd consider and is not completely out of question.

**Comment by pfitzseb** [comment]
We're not following Julia's versioning here -- the extension should be compatible with all 1.x Julia versions. It's just that with 0.17 we had most features in place we wanted for a "proper" release _and_ had a couple weeks of bugfixes with no new features, so we decided to re-release 0.17 as 1.0 during JuliaCon.
