### ISSUE TITLE
Julia Language Server crashed: "Connection to server got closed. Server will not be restarted."

### ISSUE THREAD

**Issue by dasayan05** [julia-vscode/julia-vscode#1598]
I am aware of the fact that this problem has been reported multiple times (e.g. #861, #650 ) in the past but none of them could provide me with any solid fix. So I am opening an issue again.

So, I have the following setup:
```
VS-Code version: 1.47.3 (Installed from Snap)
Julia version: 1.5.0
Julia-VSCode extention: 1.0.3
System: Ubuntu 18.04
```
And julia executable is in right place and exposed via ${PATH}.

Whenever I start the julia-vscode extension, I get

```
The Julia Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.
```
and in the output panel I get
```
[Info  - 2:28:12 PM] Connection to server got closed. Server will restart.
[Info  - 2:28:12 PM] Connection to server got closed. Server will restart.
[Info  - 2:28:12 PM] Connection to server got closed. Server will restart.
[Info  - 2:28:12 PM] Connection to server got closed. Server will restart.
[Error - 2:28:12 PM] Connection to server got closed. Server will not be restarted.
```

I tried tinkering with a lots of things. No positive results :disappointed:

**Comment by pfitzseb** [comment]
Have you by chance compiled a custom sysimg for Julia?

**Comment by dasayan05** [comment]
Well, I am very new to Julia. I am not very aware of what that is. But I didn't do anything like that.
BTW, I compiled Julia from source in the standard way.

**Comment by aviatesk** [comment]
LanguageServer is now not compatible with julia v1.6, watch on https://github.com/julia-vscode/SymbolServer.jl/pull/186

**Comment by dasayan05** [comment]
I am sorry, No. I am on Julia 1.5.0.

**Comment by davidanthoff** [comment]
Did you get a prompt to send a crash report? That is by far the most useful information for us for any kind of language server problem.

**Comment by dasayan05** [comment]
@davidanthoff 
Alright, I'll send the crash report.
BTW, I tried installing the same versions of `julia`, `julia-vscode` and `vscode` on a Windows 10 machine of mine. It worked perfectly fine.
So, the problem seems to be only on linux.

**Comment by davidanthoff** [comment]
I'm going to close because this is so old. If this still happens for someone, please open a new issue.
