### ISSUE TITLE
Re-evaluating module leads to nested module

### ISSUE THREAD

**Issue by grahamgill** [julia-vscode/julia-vscode#1600]
module A
    x = 1
        module B
        y = 2
        end
    end

In the code above, I put the cursor on the first line (`module A`), then hit Alt-Enter. A Julia REPL opens and Main.A is reported.

I put the cursor on the first line again, and hit Alt-Enter again. Now Main.A.A is reported, and as you can see from the Julia workspace at left, there really is an A contained with the outer A.

I repeat the exercise a third time, but no third level of A appears. The workspace is no different from after the second Alt-Enter. See the screen shot.
![modA](https://user-images.githubusercontent.com/47540120/90181123-f2a87c00-dd7d-11ea-8ff0-472330c2b4c6.png)

I remember coming across a similar problem sometimes in Juno.

I'm using VSCode 1.47.1 and julia-vscode 1.0.3.

**Comment by NightMachinary** [comment]
Another problem is using `language-julia.executeFile`. When I call that on my file containing module X, it evaluates the module inside itself, creating X.X.

**Comment by NightMachinary** [comment]
A workaround is to choose the evaluating module manually from here (set it to `Main` like the screenshot):
![image](https://user-images.githubusercontent.com/36224762/90317238-2aa9ed80-df3d-11ea-86dd-6acce619e8b4.png)

This workaround nukes the whole benefit of automatic in-module eval though, so it's not that good.

**Comment by NightMachinary** [comment]
@davidanthoff I have a file named `sth.jl` where my definitions are and another file `tmp.jl` where I am playing with definitions from that file. `sth.jl` does not define a module. I want VSCode to recognize the definitions from `sth.jl` in `tmp.jl`. What is my best option? Adding `using .sth` to `tmp.jl` does not fix this.
