### ISSUE TITLE
Use an outline icon for the activity bar

### ISSUE THREAD

**Issue by shilangyu** [julia-vscode/julia-vscode#1601]
In [v1.37](https://code.visualstudio.com/updates/v1_37#_new-product-icons) vscode transitioned from filled to outline icons. Julia's Explorer looks out of place with a filled icon. Example:

![image](https://user-images.githubusercontent.com/29288116/90225656-030a3680-de12-11ea-9122-d5d25ca867d3.png)

If approved I can send a PR.

**Comment by pfitzseb** [comment]
Sounds good to me.
