### ISSUE TITLE
`read: Connection reset by peer` using Plots

### ISSUE THREAD

**Issue by JeffBezanson** [julia-vscode/julia-vscode#1606]
When I load Plots.jl and evaluate e.g. `plot(rand(5))` in the editor, I get this message in the REPL (followed by `send: Broken pipe`). Does not seem to happen if I run the plot command from the REPL.

**Comment by pfitzseb** [comment]
This is an issue with old(ish) GR version, IIRC. Can you try upgrading to the latest Plots and GR (plus `Pkg.build("GR"))?

**Comment by JeffBezanson** [comment]
Now on Plots 1.5.9 and GR 0.51.0 and it still happens.

**Comment by aviatesk** [comment]
![plot](https://user-images.githubusercontent.com/40514306/90283390-1b7a5f80-deab-11ea-965f-34b69ea3adff.gif)

hmm it seem to work with Plots@1.5.9 on macOS.

**Comment by pfitzseb** [comment]
Ping @jheinen. Do you know what could be going on here?

**Comment by jheinen** [comment]
Please try  `ENV["GRDIR"]=""; ] build GR` to ensure, that the latest GR runtime is loaded. `Plots.GR.version()` will then show `0.51.2.post25`.

**Comment by JeffBezanson** [comment]
I tried that and it doesn't seem to help. `Plots.GR.version()` gives `0.51.2.post27` for me.

Note I don't see a message for the first plot; it starts after the second plot, maybe due to output lag of some kind.

**Comment by bjonnh** [comment]
I've the same problem happening, I tried a serie of plot(rand(10)) then I tried the Lorenz demo from here: http://docs.juliaplots.org/latest/

**Comment by bjonnh** [comment]
Trying to run the next example, Julia just segfaults…

It is running on Wayland, maybe that's the issue. But it seems to fail during a LLVM pass… 
0x00007fff3877f11d in llvm::TargetPassConfig::addPass(llvm::Pass*, bool, bool) () from /usr/bin/../lib/libLLVM-11.so

**Comment by pfitzseb** [comment]
Are you using the official Julia binaries?

**Comment by bjonnh** [comment]
I just realized I posted that in the wrong issues window I had open and didn't mean to post it here on the vscode plugin. Sorry about that. I was using the ArchLinux binary under Wayland but not from VSCode. Sorry about that.

**Comment by pfitzseb** [comment]
I'd recommend switching to AURs julia-bin, FWIW (may or may not help with your specific problem).

Also closing this issue since it should've been fixed in GR.
