### ISSUE TITLE
Could not start the julia language server

### ISSUE THREAD

**Issue by PedroPizarro** [julia-vscode/julia-vscode#1612]
I was looking forward to use VSCode to run Julia but I'm struggling to find peace.
I've looked for others similar issues here, but none of the solutions worked for me.
Currently I'm using Julia 1.5.0 in Fedora  31. I have Julia's bin file in the `env_path` in the `.bashrc` like this:
`export PATH="$PATH:~/julia-1.5.0/bin"`

I've already tried to put in the Julia: Executable Path in Code the path to the bin, but didn't work... I just don't know how to do this and I've searched a lot for a tutorial/explanation on this topic. If somebody help me I would be very happy :). By the way this is my first issue post and a post in general in Git Hub, so if I'm doing something wrong, please tell me.

**Comment by PedroPizarro** [comment]
So apparently I made it, but don't know how and why. 
Although I can run Julia in the cmd because of the path in  `.bashrc`, I needed to put the executable path in Code too. 
However, this one (in Code) is not the same `bib` as the one in the path. When I use `which julia` I get another destination, and if I use this destination, the  problem is solved. 

But, the stories continues; another problem appeared: "Couldn't start client Julia Language Server". Searching for this particular problem I could find #1135, which in this comment:


> I'm surprised that it works at all for some cases ;)

It's kinda magical, and I don't know how, but the Remote-SSH extension works seamlessly with the Julia extension, including remote plotting.

The issue here doesn't seem to have anything to do with Remote-SSH, though - maybe I should have been more specific, the problem also occurs in purely local operation.

> I think for the remote stuff, aren't there some remote specific settings somewhere that you might also be able to use?

Sadly, no - I'd like to be able to configure target host specific settings (env vars, etc.), but that doesn't seem possible. Hence my plan to use host-specific  Julia startup scripts. Besides, env vars are not enough, on some HPC systems I need to run stuff like "module load julia" first, etc.

_Originally posted by @oschulz in https://github.com/julia-vscode/julia-vscode/issues/1135#issuecomment-618556920_

The extension Remote-SSH was mentioned, than I installed and, magic?, worked :). 

I would love to see VSCode being similar to Juno, if somebody get to know something about, please reach me.

**Comment by mmattocks** [comment]
Same problem (language server recently started failing, complaining about a `nothing` being passed to `push!(server.workspaceFolders, uri2filepath(wksp.uri))` at init.jl:134- bypassing the if not defined as nothing check? Strange... Installing remote-ssh does the trick and I have my language server back.

**Comment by michael-irvin** [comment]
I am having the first issue in julia-v1.6. I repeated everything PedroPizarro tried including setting the path to the destination I get when I use `which julia`. I also unistalled and reinstalled vscode, julia and the vscode-julia extension v.1.5.4, and re-tried the instructions in the tutorials.

**Comment by PedroPizarro** [comment]
@davidanthoff  I've almost forgotten about this issue, and nowadays there is the `juliaup` installer that sets all the configuration in `.bashrc` automatically. May I close this issue?

**Comment by davidanthoff** [comment]
Yes!
