### ISSUE TITLE
Language Server has massive delay/not responding for up to 100000ms

### ISSUE THREAD

**Issue by spcogg** [julia-vscode/julia-vscode#1613]
Hi All,

Running in to an issue on my setup (Julia v1.5, Extension version 1.0.3, MacOSX Catalina 10.15.6) where the language server would hang for up to 100000ms and does not respond during this period.

Screenshot of the trace output where this occurs : (trace log of the duration of the event also attached)
![image](https://user-images.githubusercontent.com/8016236/90588524-27ee1780-e21f-11ea-880f-630d106cf243.png)
[julia-vscode-trace.txt](https://github.com/julia-vscode/julia-vscode/files/5093846/julia-vscode-trace.txt)

Any one else seeing this occuring? It seems to occur randomnly but most frequently when I try to use the F12 'go to definition' functionality when it hangs.

During this time, all the actions are still being sent to the language server but not processed, they get actioned all at once when the LS is responding again. (You can  see in the logs where a whole bunch of actions are queued with no response, and then they all come back after ~100000ms)

You can still manually type commands into the REPL during this time, so Julia is definitely responding, just not the LS for some reason.

Funnily enough on my home windows machine this does not happen, but I have someone in my team reporting that this also does affect windows environments. What's the best way to further diagnose if there's something that's causing this delay?

Thanks in advance for any help on this!

**Comment by captchanjack** [comment]
Same issue here, vscode intellisense for Julia works well when it does, but often it would hang and not respond with cmd + mouse hover.

**Comment by spcogg** [comment]
Hi Team,

Another update when this happened again - I've noticed the large delay usually ends with the error message: 'Request failed: version mismatch in getCurrentBlockRange request for LanguageServer.URI2('<path to file>'): JLS 4, client: 3 (-32099). 
![image](https://user-images.githubusercontent.com/8016236/91240709-114b4180-e786-11ea-9d45-d34febbe18cb.png)

Full logs attached
[julia_trace_2.txt](https://github.com/julia-vscode/julia-vscode/files/5126894/julia_trace_2.txt)

**Comment by spcogg** [comment]
![image](https://user-images.githubusercontent.com/8016236/103842374-e84e9c00-50e9-11eb-9a8f-c20bfd98e2a0.png)
Bump on this one, still getting this in Jan 2021. 
It looks like it's to do with a particular getCurrentBlockRange() function in the Language Server, which is blocking other functions until it times out with the error that comes back.

If someone can point in the right direction of where this might be, happy to try putting in a fix of either reducing the timeout or adding proper error handling.

**Comment by davidanthoff** [comment]
We fixed a fairly large number of bugs in this area, so I'm hoping that this is fixed and am closing this issue for now. Please ping or reopen if this is still a problem.

**Comment by pfitzseb** [comment]
There's an issue here where we're linting a bunch of non-workspace files, which causes the LS to lock up (when e.g. going to the definition of a Base method). We might want to make our LSP notification handling async to work around that (not sure that won't break anything else though) or jjust analyse fewer files.

**Comment by davidanthoff** [comment]
I think we should simply limit linting to files in the workspace folder and files that are opened. I think our crawling and following of `include`s outside of the workspace is something we should maybe reconsider.

**Comment by pfitzseb** [comment]
I've been trying to debug this (and similar) issues today, and it *might* not actually be the linting that's the issue (or if it is then I don't know where it's triggered). Will need to take a more systematic approach to profiling the LS though...

**Comment by davidanthoff** [comment]
Yes!! We should for example add telemetry diagnostics that simply send back how long different operations take. That kind of message type exists in the application insights stuff we use, and I think the infrastructure to send these messages from the LS is (almost) there already.
