### ISSUE TITLE
random array generation is massively slower when run in debugger.

### ISSUE THREAD

**Issue by jiifon** [julia-vscode/julia-vscode#1614]
I am new to Julia and just started to learn it, found this issue when trying rewriting some python scripts in Julia. I am not sure if this is a bug, or due to improper configuration on my machine. (How should I fix it if not a bug?) 

A simple script to show the problem is as follows
```
# test.jl
function main()
    @time A = rand(20,20)
end

main()
```
When I "Run Julia File", the output is 
```
  0.000325 seconds (20 allocations: 23.438 KiB)

Julia debuggee finished. Press ENTER to close this terminal.
```
which is similar with the performance in REPL.
But when I "Debug Julia File" (setting no breakpoints), the output is
```
  3.104844 seconds (2.36 M allocations: 110.596 MiB, 0.89% gc time)

Julia debuggee finished. Press ENTER to close this terminal.
```

**relevant platform info**
Julia installation info:
```
julia> versioninfo()
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i3-3120M CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, ivybridge)
```
VSCode info:
```
Version: 1.48.0
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T07:40:55.768Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-42-generic
```
VSCode Julia extension version is **1.0.3**

**Comment by pfitzseb** [comment]
It's neither a bug nor misconfiguration, unfortunately. 
This is expected behaviour until we improve the [interpreter](https://github.com/JuliaDebug/JuliaInterpreter.jl) or implement a bunch of heuristics.
