### ISSUE TITLE
Add configuration files for code highlighting

### ISSUE THREAD

**Issue by jlperla** [julia-vscode/julia-vscode#1620]
Jupyter notebook support is coming along well since they fixed https://github.com/microsoft/vscode-python/issues/12760#issuecomment-654995857.  I haven't had other bugs since.

But syntax highlighting is not functional.  According to microsoft, this is a vscode setup issue (and not specific to jupyter).  See https://github.com/microsoft/vscode-python/issues/5078#issuecomment-668126575  for example.

For example, in C:\Users\MYUSERNAME\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions I see a list of a whole bunch of languages, but not julia.  Should the configuration files there (or perhaps copying them over?)

If you do the following:
- add a `C:\Users\MYUSERNAME\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\julia` folder
- copy from the `C:\Users\MYUSERNAME\.vscode\extensions\julialang.language-julia-1.0.4` the following into that folder
  - package.json
  - julia.configuration.json
  - syntaxes folder

Then syntax highlighting in jupyter seems to work great.  Can those files be copied over easily in the installation process?

**Comment by pfitzseb** [comment]
From the comment linked above:
> Since VS code doesn't ship one, you'd have to add one manually to that location or change our code to look elsewhere for it.

The latter options seems much cleaner to me. They could just iterate over all active extensions and figure out the paths to the language configuration files from there.

**Comment by jlperla** [comment]
Just a gentle reminder that microsoft agreed to add this in on microsoft/vscode#105229 , and was asking for some help.  It might make sense to start to process to keep up the momentum.  I think it is a big marketing win for julia for vscode to ship with the basic highlighting/etc. out of the box.

I think this is out of my paygrade or I would try to help out more directly.

**Comment by davidanthoff** [comment]
I'll look into this once I've got the semester start under control.

**Comment by jlperla** [comment]
Sounds good.  When the time is right, if I can help with testing/etc., please let me know.

... and good luck with getting things under control.

**Comment by javieryu** [comment]
For posterity this fix also works in Ubuntu 20.04.

Copying the same files from `~/.vscode/extensions/julialang.language-julia-X.X.X/`

- `package.json`
- `julia.configuration.json`
- `syntaxes/`

to `/usr/share/code/resources/app/extensions/julia/`.

**Comment by coxackie** [comment]
gentle nudge here, to see if this feature is coming. With the new Jupyter VS code extension, this will be beautiful!

**Comment by jlperla** [comment]
I think this might already be in the released vscode and this issue able to he closed?

**Comment by pfitzseb** [comment]
I don't think so :) https://github.com/microsoft/vscode/issues/105229 is still open.

**Comment by jlperla** [comment]
I vividly remember the Julia config files being merged into the released version of vscode! More evidence why human memory should never be trusted, and github a thousand years from will contain all human knowledge at a sequence of commits...sorry to distract!

**Comment by coxackie** [comment]
@pfitzseb Thanks for the update. Are you going to ping microsoft/vscode#105229 to see if it possible to move things?

**Comment by mchitre** [comment]
Any idea what the equivalent folder is on OS X for this temporary fix?

**Comment by xukai92** [comment]
> Any idea what the equivalent folder is on OS X for this temporary fix?

Similar to https://github.com/julia-vscode/julia-vscode/issues/1620#issuecomment-714675654, but you just moving stuff to `/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/extensions/`.

**Comment by mchitre** [comment]
@xukai92 thanks

**Comment by Christian-Git01** [comment]
> For posterity this fix also works in Ubuntu 20.04.
> 
> Copying the same files from `~/.vscode/extensions/julialang.language-julia-X.X.X/`
> 
>     * `package.json`
> 
>     * `julia.configuration.json`
> 
>     * `syntaxes/`
> 
> 
> to `/usr/share/code/resources/app/extensions/julia/`.

Does somebody know the path for Linux Arch?

**Comment by coxackie** [comment]
@Christian-Git01 I guess do the same but copy to `/usr/lib/code/extensions/julia/`. Try and let us know if it works.

 The problem of course is that you would have to do this every time after an update of `code`.

**Comment by Christian-Git01** [comment]
> @Christian-Git01 I guess do the same but copy to `/usr/lib/code/extensions/julia/`. Try and let us know if it works.
> 
> The problem of course is that you would have to do this every time after an update of `code`.

Thanks! Unfortunately not, I also had to create the directory julia. Should it be there already?

**Comment by coxackie** [comment]
> 
> Thanks! Unfortunately not, I also had to create the directory julia. Should it be there already?

You should create the directory, it will not be there in the first place. When you say "unfortunately not" what do you mean? It is not working?

**Comment by xukai92** [comment]
Anyone know how this trick works for remote Linux? Specifically I don't have root access so it's impossible to edit anything like `/usr/lib` or `/usr/share`.

**Comment by irojkov-ph** [comment]
> @Christian-Git01 I guess do the same but copy to `/usr/lib/code/extensions/julia/`. Try and let us know if it works.
> 
> The problem of course is that you would have to do this every time after an update of `code`.

@coxackie This doesn't work for me unfortunately :( 

(I am under Manjaro Gnome, so I've created as you've said a `/usr/lib/code/extensions/julia/` folder and copied the files in there, then restarted vs code but nothing changed)

**Comment by Christian-Git01** [comment]
> > Thanks! Unfortunately not, I also had to create the directory julia. Should it be there already?
> 
> You should create the directory, it will not be there in the first place. When you say "unfortunately not" what do you mean? It is not working?

Unfortunately, it is not working. My setup is similar to @irojkov-ph. Open source code of vs code and Manjaro.

**Comment by jlperla** [comment]
Alas, it seems like the workarounds aren't working.  I think this may need to be built into vscode to be usable across platforms.  @pfitzseb  any ideas on the path forward here?  Microsoft said that they would merge julia support directly into vscode, which I think is a big win for the community.  Is there anything other people can do to help here?

**Comment by coxackie** [comment]
I just tried this with vscodium 1.52.1; made a julia folder at /usr/share/..., copy `package.json`, `julia.configuration.json` and `syntaxes/` there, and I get syntax highlighting.

**Comment by coxackie** [comment]
ok, so now I think that in the `code - oss` package in Arch the problem may be more general. I open a notebook with `R` kernel, and I am not getting highlighting also for that one, even though `r` has built-in grammar. Can anyone confirm? @Christian-Git01 @jlperla (not sure if the latter is using arch linux)?

**Comment by jlperla** [comment]
@coxackie It may be easiest to just wait a month or two. See https://github.com/microsoft/vscode/pull/115309 which @pfitzseb provided to them for built in support

**Comment by Christian-Git01** [comment]
> @coxackie It may be easiest to just wait a month or two. See [microsoft/vscode#115309](https://github.com/microsoft/vscode/pull/115309) which @pfitzseb provided to them for built in support

Thanks for that information!

@coxackie I am gonna wait for that and stop spending time on trying to get it work.

**Comment by coxackie** [comment]
@jlperla @Christian-Git01 maybe I did not explain very well.

 I am talking about a specific issue with the build of code - oss in arch linux. I do not think that julia highlighting will work even after it receives built-in support, the way things are right now. My evidence comes from the fact that highlighting does *not* work also for the R kernel, and R has built-in support already.

 Note that it *does* work for `vs-codium`. But as far as arch `code - oss` does, there is a deeper problem. @Christian-Git01 do you work with kernels other than python and julia? It may be that only python has highlighting for arch `code - oss`.

**Comment by alsaibie** [comment]
> Jupyter notebook support is coming along well since they fixed https://github.com/microsoft/vscode-python/issues/12760#issuecomment-654995857. I haven't had other bugs since.
> 
> But syntax highlighting is not functional. According to microsoft, this is a vscode setup issue (and not specific to jupyter). See https://github.com/microsoft/vscode-python/issues/5078#issuecomment-668126575 for example.
> 
> For example, in C:\Users\MYUSERNAME\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions I see a list of a whole bunch of languages, but not julia. Should the configuration files there (or perhaps copying them over?)
> 
> If you do the following:
> 
> * add a `C:\Users\MYUSERNAME\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\julia` folder
> * copy from the `C:\Users\MYUSERNAME\.vscode\extensions\julialang.language-julia-1.0.4` the following into that folder
>   
>   * package.json
>   * julia.configuration.json
>   * syntaxes folder
> 
> Then syntax highlighting in jupyter seems to work great. Can those files be copied over easily in the installation process?

I can do these steps just fine and it works in VSCode on Windows 10. But every time there is an update, the folder I created is removed. What's the best way to keep this configuration persistent?
