### ISSUE TITLE
Linter no longer runs on my machine

### ISSUE THREAD

**Issue by CameronBieganek** [julia-vscode/julia-vscode#1621]
I had the linter turned off for a while, but I just turned it back on and nothing will lint.

I created a test file with these contents:

```
x = asdf + 1
```

No linting happens. I tried toggling the linter, restarting VS Code, etc, but the linter won't run.

### System Info

```
Julia Version 1.4.0
Commit b8e9a9ecc6 (2020-03-21 16:36 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 6
  JULIA_EDITOR = vim
```

VS Code:

```
Version: 1.48.1
Commit: 3dd905126b34dcd4de81fa624eb3a8cbe7485f13
Date: 2020-08-19T17:09:41.484Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```

Julia Extension: v1.0.4

**Comment by pfitzseb** [comment]
We recently turned off the `Julia > Lint: Missingrefs` linter pass by default. You might want to re-enable that if you want the linter to catch the case you described.
