### ISSUE TITLE
Current package get "Missing reference" in subfolder other than test

### ISSUE THREAD

**Issue by josePereiro** [julia-vscode/julia-vscode#1623]
Hi, Im having some `Missing reference` warnings when I try to `import/using' the current project package.

I'm doing the following experiment
```
git clone https://github.com/JuliaLang/Example.jl Example
code Example
```
NOTE: `Example.jl` is not present in my global environment
```
(v1.1) pkg> status Example
ERROR: The following package names could not be resolved:
 * Example (not found in project or manifest)
Please specify by known `name=uuid`.
```

I have no warnings inside `test/runtests.jl` file,
![image](https://user-images.githubusercontent.com/44244693/90982856-2763c280-e538-11ea-812f-268e51660707.png)

ISSUE: if I include `scripts/myscripts.jl`
![image](https://user-images.githubusercontent.com/44244693/90982951-b07af980-e538-11ea-9e06-2b6c30c0b005.png)

But if I move `scripts/myscripts.jl` to `tests/myscripts.jl`
![image](https://user-images.githubusercontent.com/44244693/90983230-92ae9400-e53a-11ea-892c-b257e0d87745.png)

Although a (Shift + Enter) works perfectly in both cases
```
# Hello, Jose
# 8.0
```

my workspace `Example/.vscode/settings.json` only have
```
{
    "julia.environmentPath": "/Users/Pereiro/Documents/Test/Example",
    "julia.executablePath": "/Applications/Julia-1.1.app/Contents/Resources/julia/bin/julia",
}
```
my user `settings.json` have nothing related with julia

versioninfo:
```
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
  JULIA_EDITOR = code
```
I'm using the extension version `0.17.1`

Did I miss some further configuration?

Thanks!!!

**Comment by pfitzseb** [comment]
We don't handle this case at all at the moment and have turned off the relevant linter passes in certain subdirectories (`/docs` and `/test`, specifically).

**Comment by josePereiro** [comment]
Thanks for the reply, any possible work around?

**Comment by aviatesk** [comment]
no, no workaroud users can do, LS itself needs to be fixed.

**Comment by davidanthoff** [comment]
I'm going to close this issue because we already have issues that track the work we need to do to fix this.
