### ISSUE TITLE
Formatting indentation when forgetting a block end statement doesn't work correctly for function declarations in modules.

### ISSUE THREAD

**Issue by TommyXR** [julia-vscode/julia-vscode#1625]
Hey guys, so here's an issue I stumbled on earlier today.

![vscode_indent](https://user-images.githubusercontent.com/42289375/90986825-b500db80-e553-11ea-9185-006d0a4cb36e.gif)

To reproduce:

* in a module, declare a function.
```julia
module Foo

function g()
    x^2
end

function h()
    println()
end

end # module
```

* Now declare a new function before that function, but forget the `end` keyword.

```julia
module Foo

function f()

function g(x)
    x^2
end

function h()
    println()
end

end # module
```

* Format your code, all blocks under that function will be indented (as expected)

```julia
module Foo

function f()

    function g(x)
        x^2
    end

    function h()
        println()
    end

end # module
```

* Realize your mistake, add the end block, and reformat. Unfortunately, the `function` lines don't get reindented correctly!

```julia
module Foo

function f()
end

    function g(x)
    x^2
end

    function h()
    println()
end

end # module
```

I suspect the `function` lines don't realize that the block they're in is a `module` block, thus they don't get reindented back,
as they think their indentation depth is 1. (This is my guess because it doesn't happen outside of modules)

**Comment by pfitzseb** [comment]
Should be fixed in the next version of the extension.
