### ISSUE TITLE
Indentation in strings

### ISSUE THREAD

**Issue by atbug** [julia-vscode/julia-vscode#1626]
With the cursor at the end of the sentence

```julia
"""
This function calculates eigenvectors of a Hermitian matrix.
"""
```

press enter, and the next line will be automatically indented. It seems the function keyword is detected in the string.

**Comment by pfitzseb** [comment]
Fixed.

**Comment by atbug** [comment]
Is this really fixed? I can still reproduce the original behavior.

**Comment by atbug** [comment]
Bump. This is a pretty annoying behavior.

**Comment by pfitzseb** [comment]
Unfortunately, there is no easy fix for this. VS Code uses a [`increaseIndentPattern` regex](https://code.visualstudio.com/api/language-extensions/language-configuration-guide#indentation-rules) for indentation of the next line, but that is a local pattern and only looks at the current line. AFAICT there's no way to get it to look at the current scope (i.e. the fact that we're currently inside of a string).
