### ISSUE TITLE
Suggestion: Syntax highlighting closer to Juno

### ISSUE THREAD

**Issue by hdavid16** [julia-vscode/julia-vscode#1627]
It would be great to have the syntax highlighting to be more like Juno. The highlighting in VS Code is good, but the one in Atom is superior (i.e `=`, `in`, `:` have a different color). Just a thought...

**Comment by davidanthoff** [comment]
I don't know what we would do here. We use the same grammar file that Juno used, and beyond that I don't think there is anything we can do. So I think I'm going to close this issue for now, unless someone has some concrete ideas what we could do :)

**Comment by hdavid16** [comment]
In case any body wants a richer experience with the syntax coloring, there's a great extension for this: https://github.com/CameronBieganek/julia-color-themes
