### ISSUE TITLE
Order of auto-completion items

### ISSUE THREAD

**Issue by xgdgsc** [julia-vscode/julia-vscode#1628]
I noticed when I type `Fl` it always shows `Float16` on top which I rarely use (I select Float64 almost always) . Is it possible to order the items based on last usage frequency. Even only in current window session would help a lot.

**Comment by pfitzseb** [comment]
That should be the default already:
![image](https://user-images.githubusercontent.com/6735977/91293892-fb934780-e798-11ea-9a33-490b1cc726f2.png)

**Comment by xgdgsc** [comment]
Thanks. Don' t know when I changed that to `first`.
