### ISSUE TITLE
Log messages not being shown in REPL

### ISSUE THREAD

**Issue by adamlichtl** [julia-vscode/julia-vscode#1631]
When I run the following (based on https://docs.julialang.org/en/v1/stdlib/Logging/) in the Julia REPL, nothing is shown:
```
julia> foo() = @debug "foo";
julia> ENV["JULIA_DEBUG"] = Main;
julia> foo()
```
I'm running VS Code 1.48.2 on Linux, with Julia extension version 1.0.4.

**Comment by adamlichtl** [comment]
Also, it looks like @info and @warn both work, but @debug does not.

**VS Code Julia REPL session:**
```
julia> ENV["JULIA_DEBUG"] = Main
Main

julia> @info "Test 1"
[ Info: Test 1

julia> @warn "Test 2"
┌ Warning: Test 2
└ @ Main REPL[23]:1

julia> @debug "Test 3"

julia>
```

**Terminal (Zsh) Julia REPL:**
```
julia> ENV["JULIA_DEBUG"] = Main
Main

julia> @info "Test 1"
[ Info: Test 1

julia> @warn "Test 2"
┌ Warning: Test 2
└ @ Main REPL[3]:1

julia> @debug "Test 3"
┌ Debug: Test 3
└ @ Main REPL[4]:1
```

So it looks like the issue may be with the way VS Code interacts with the "JULIA_DEBUG" variable. Is there a different way to set it such that it will be picked up by the REPL? I'm happy to provide any other info that might be useful. Thanks!

**Comment by pfitzseb** [comment]
I can't repro this:
![image](https://user-images.githubusercontent.com/6735977/91412989-cc3d1300-e84a-11ea-8c0d-89a260fafa48.png)

**Comment by adamlichtl** [comment]
Hi @pfitzseb - thank you for trying to reproduce. Trying again this morning, I'm no longer seeing the issue either. Checking versions, I'm still running VS Code 1.48.2 on Linux, with v1.0.4 of the Julia plugin, so I have no idea what changed. I even went back into the REPL history and reran the commands from yesterday, and they're working now too. Everything seems to be working now-- thanks again, and sorry for the noise!

**Comment by pfitzseb** [comment]
No worries. It's possible you replaced the global logger at some point prior or something like that.
