### ISSUE TITLE
Debugger connecting to embedded process on demand

### ISSUE THREAD

**Issue by wasabinza** [julia-vscode/julia-vscode#1633]
We are keen to migrate a workflow from Juno to VSCode but I don't see how it can work for us.
We are using the remote debugging where our embedded Julia process connects out with Juno.connect(PORT) when we want to trigger debugging.
This works nicely as we can trigger on demand from a long running process.

I have read the bug about the main workflow: https://github.com/julia-vscode/julia-vscode/issues/509 and the quoted documentation: https://code.visualstudio.com/blogs/2019/05/02/remote-development but I don't really see how to adapt that to our workflow where our entry point is not a julia binary.
I could try to implement some julia like entrypoint to our embedded application but that wouldn't be as flexible as deciding to debug a running process and just connecting to the external debugger at that point as we currently enjoy.

Anyone have any suggestions?

**Comment by wasabinza** [comment]
Could I intercept the call to launch the debuggee somehow and record the pipes and then run the equivalent Julia in my embedded process to connect to the pipe/sockets?  This is analogous to what I do with Juno but I guess in the current situation the control is then intended to come down the pipes to the debuggee rather than the debuggee telling the debugger what is going on.

**Comment by pfitzseb** [comment]
We could "just" implement an equivalent to `Juno.connect` here. Has the added benefit of making multi-screen setups nicer by running Julia in an external terminal.

**Comment by wasabinza** [comment]
Hi,  Is this something I could help contribute to?  Would porting some code from the Juno be possible?  Are the code bases at all similar?

**Comment by pfitzseb** [comment]
https://github.com/julia-vscode/julia-vscode/pull/1893 allows attaching to an arbitrary Julia process, which should be all that's needed for this.

**Comment by wasabinza** [comment]
Awesome, I'll try it out in our scenario.
So I think I can just call VSCodeServer.serve("${pipename}") from my embedded Julia with the correct pipename and it can connect?
I'll try to get the tmux version working on linux first to reproduce that and then I will try and mimic the persistent behaviour in my embedded Julia.

**Comment by pfitzseb** [comment]
Not quite. You'll also need to "spoof" the way the extension starts Julia, because otherwise you'll connect to the autostarted Julia instead of the one you intended to use. I'll prepare a PR to make that easier though :)

**Comment by pfitzseb** [comment]
This has been implemented as `Julia: Connect to external REPL`.
