### ISSUE TITLE
Execution: Result Type set to both leads to double printing sometimes

### ISSUE THREAD

**Issue by raphaelsaavedra** [julia-vscode/julia-vscode#1634]
See https://github.com/LAMPSPUC/ScoreDrivenModels.jl/issues/110. Looks like Having `Julia > Execution: Code in REPL` set to `both` leads to double printing in some cases. I've been using this setting for a while without any issues, but for this particular function it prints the output twice. Maybe it is because it overloads `Base.show`. Changing the setting to just `REPL` fixed the issue.

**Comment by pfitzseb** [comment]
This isn't an issue with VSCode. Your `show` method is incorrect in the sense that it *always* prints to `stdout`, instead of the provided `IO`. E.g. [this](https://github.com/LAMPSPUC/ScoreDrivenModels.jl/blob/73d44f168bdee136e09e1b51ed7a2d4a867ef7aa/src/prints.jl#L1-L11) should be
```
function Base.show(io::IO, est::EstimationStats{D, T}) where {D, T}
    println(io, "--------------------------------------------------------")
    println(io, "Distribution:                 ", D)
    ....
```
instead.

**Comment by raphaelsaavedra** [comment]
Thanks for pointing that out!
