### ISSUE TITLE
"run without debugging" still runs in a terminal labeled "julia debugger"

### ISSUE THREAD

**Issue by JeffBezanson** [julia-vscode/julia-vscode#1640]
This is a very superficial issue, but I just found it a bit confusing that the terminal is called this even if I'm not using the debugger. If the debugger is not in use, the terminal should be named e.g. "Julia execution", or it could be called that all the time.

**Comment by davidanthoff** [comment]
[Here](https://github.com/julia-vscode/julia-vscode/blob/2f7bfa11ef1ccfaa5ae7ad1b28713542aca95972/src/debugger/juliaDebug.ts#L226) is the line where this would need to be changed, depending on the value of `args.noDebug`, if someone wants to open a PR :)

**Comment by PetrKryslUCSD** [comment]
Has anything happened? "Julia: Run in new process" still opens a window named Julia debugger.
