### ISSUE TITLE
About GitHub codespaces

### ISSUE THREAD

**Issue by fonsp** [julia-vscode/julia-vscode#1647]
Hi,

I read that you don't have access to GitHub codespaces (https://github.com/microsoft/vscode/issues/104199) - boo!

I got access today, you are more than welcome to use my session via Live Share to experiment. I guess I need to be online to prevent the 30 minute idle time, but I am happy to help.

fonsvdplas@gmail.com

I did not get the Julia extension working - I can download & run Julia binaries, add `/bin` to my PATH in `~/.bashrc` and run the `julia` command, but the Julia extension cannot find `julia`:

Here's a screenshot, but I will happily do the Live Share thing if you want to debug:

![image](https://user-images.githubusercontent.com/6933510/92286452-623a0300-ef07-11ea-87c7-86f31a1b4ea6.png)

**Comment by fonsp** [comment]
Oh the issue was fixed after restarting my browser... It works now!

The offer still stands!

**Comment by davidanthoff** [comment]
I just got in! They announced that VS Codespaces will go away, and anyone with an account there apparently is now automatically in the github beta :)

When I start Codespaces for the davidanthoff/StringBuilders.jl repo, everything works?

**Comment by fonsp** [comment]
Good to hear!

Was Julia available straight away? Wat that because of https://github.com/davidanthoff/StringBuilders.jl/blob/master/.devcontainer/devcontainer.json ?

**Comment by davidanthoff** [comment]
Yes and yes :)

I'll look into creating a docker image that is specifically useful for this kind of scenario, that should make this even easier, hopefully.

**Comment by fonsp** [comment]
Awesome! Very cool stuff.

What would be great is a MWE repository that works straight away if you open it in Codespaces. So `/.devcontainer/devcontainer.json` to get Julia, and `/.vscode/extensions.json` to make `julia-vscode` a "recommended" extension.

I could also look into this myself next week

**Comment by davidanthoff** [comment]
Yes, that is the plan, and then we'll add that as a template to the official VS Code list of templates.
