### ISSUE TITLE
No indexing on insiders

### ISSUE THREAD

**Issue by timholy** [julia-vscode/julia-vscode#1648]
I'm running the insiders track, and within the last 24hrs (I think) F12 has stopped working for me. I never see a "Language Server indexing..." message (or whatever it was precisely, I don't remember for sure).

**Comment by timholy** [comment]
Tab completion also seems busted.

**Comment by davidanthoff** [comment]
Do you have the released and insider version installed at the same time? We added a check that detects that situation and then disables the extension, because installing both at the same time is not supported. But there should have been an error message alerting you to that.

**Comment by timholy** [comment]
I didn't see such an error message. But the problem has gone away. I think a reboot might have fixed it; perhaps I updated my vscode package via Ubuntu or something? Sorry for the noise.
