### ISSUE TITLE
Interpolated variable inside `Cmd` not detected - sometimes?

### ISSUE THREAD

**Issue by fonsp** [julia-vscode/julia-vscode#1654]
Only the first cell shows this linter warning:

![image](https://user-images.githubusercontent.com/6933510/92635281-d7c21c80-f2d5-11ea-9561-072f2fae74c5.png)

**Comment by mmiller-max** [comment]
I also get this when a command is assigned to a variable:
```Julia
function fn(a)
   cmd = `a`
end
```
<img width="791" alt="image" src="https://user-images.githubusercontent.com/59854849/106667875-9cfeaf00-65fd-11eb-8faa-b9b89b4050ed.png">

**Comment by fonsp** [comment]
@mmiller-max That looks like the expected behavior, because you did not interpolate with `$`.

**Comment by ZacLN** [comment]
Yep, agreed. The original one issue is a bug though

**Comment by mmiller-max** [comment]
@fonsp Apologies, I missed the `$` in my MWE. I've edited it now.
