### ISSUE TITLE
executing a block of code 

### ISSUE THREAD

**Issue by xiaodaigh** [julia-vscode/julia-vscode#1657]
In R 

```
x = 1

a = function() {
...
} # cursor is here |

y=2
```

and I press control-enter at the cursor location then `a = function() {...}` will get run but neither of `x=1` nor `y=1` will get run.

RStudio seems to have the ability to detect a complete code code by analysing the syntax. This is so nice.

Currently, vscode Julia can only execute the whole file (shift enter) or one line or selected region (ctrl enter). But there is no short-cut to select the immediate code block unit.

**Comment by pfitzseb** [comment]
Use Alt-Enter (by default; the command is called `language-julia.executeCodeBlockOrSelection`) for that.

**Comment by xiaodaigh** [comment]
```
model = fit(EconometricModel,
            @formula(target ~ x1+x2+x3+x4+x5+x6+x7
            ),
            df,
            contrasts = Dict(:target => DummyCoding(base = 0)))
```

It's not complete. IT's doesn't work in the above case for example

**Comment by pfitzseb** [comment]
You sure you're using the right command?
![vscode-block](https://user-images.githubusercontent.com/6735977/92991393-c8182300-f4e3-11ea-9260-f1e913b03011.gif)
