### ISSUE TITLE
julia-vscode doesn't handle multiprocessing correctly

### ISSUE THREAD

**Issue by k4rt33k** [julia-vscode/julia-vscode#1659]
I am trying to start Julia interpreter in VSCode with additional arguments `-p 4` and getting this error.
```
ERROR: LoadError: On worker 2:
ArgumentError: Package VSCodeServer [9f5989ce-84fe-42d4-91ec-6a7a8d53ed0f] is required but does not seem to be installed:
 - Run `Pkg.instantiate()` to install all recorded dependencies.

_require at ./loading.jl:993
require at ./loading.jl:922
#1 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Distributed/src/Distributed.jl:78
#105 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Distributed/src/process_messages.jl:290
run_work_thunk at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Distributed/src/process_messages.jl:79
run_work_thunk at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.3/Distributed/src/process_messages.jl:88
#98 at ./task.jl:333
```
The issue is with terminalserver.jl as it doesn't use `@everywhere` for changing the `LOAD_PATH` and for `using VSCodeServer`. I'll make a PR with my fixes that I tested on Julia 1.3 and 1.5.

**Comment by davidanthoff** [comment]
Can you explain a bit more what you are trying to do? I think in general we don’t want to load `VSCodeServer` in worker processes and we also don’t want users to directly use the stuff that is in there, it is really an implementation detail.

If the goal is to use the debugger for multi process situation, then that will require quite a lot of extra design...

**Comment by k4rt33k** [comment]
As a part of my research workflow, I regularly use `pmap` to parallelize some time consuming tasks. I just want to be able to run these functions from within vscode. I'm only loading `VSCodeServer` `@everywhere` because VSCode REPL was throwing an error and not starting up when I used `-p 4` as additional arguments in the extension settings.

It is very likely that I might be going about it the wrong way.

**Comment by chelate** [comment]
This may be redundant for you, but I found this information hard to find, so I might as well post it here. To get pmap working I set In **Settings Julia: Num Threads: 8.**

Then you just have to making sure all the workers know about all the functions they need to run your simulations.  Typically I'm running code from inside a package-like folder.  I then run in my VS-code terminal
```
using Distributed
addprocs(7)
@everywhere using Pkg
@everywhere Pkg.activate(".")
@everywhere using <packageName>

pmap(x->simulation_function(), 1:1000)
```

Then simulation_function is available from the package that I need to run simulations with are available to all workers. I dunno if this is the best way, as I am also ``new" to Julia, but that's how I do it. It works in VSCode with julia 1.4.

**Comment by pfitzseb** [comment]
FWIW, I can't repro the original issue. Are you certain you're on the latest version of the Julia plugin? Can you try with Julia 1.5 (on the off chance that changes anything)?

**Comment by rustyconover** [comment]
I can repro the issue as I too want to have worker processes in my repl.

```
ArgumentError: Package VSCodeServer [9f5989ce-84fe-42d4-91ec-6a7a8d53ed0f] is required but does not seem to be installed:
 - Run `Pkg.instantiate()` to install all recorded dependencies.

_require at /Users/rusty/Development/electricity-modelling/JuliaSysimage.dylib:?
require at /Users/rusty/Development/electricity-modelling/JuliaSysimage.dylib:?
#1 at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Distributed/src/Distributed.jl:78
#103 at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Distributed/src/process_messages.jl:290
run_work_thunk at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Distributed/src/process_messages.jl:79
run_work_thunk at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Distributed/src/process_messages.jl:88
#96 at ./task.jl:356

...and 15 more exception(s).

Stacktrace:
 [1] sync_end(::Channel{Any}) at /Users/rusty/Development/electricity-modelling/JuliaSysimage.dylib:?
 [2] macro expansion at ./task.jl:333 [inlined]
 [3] _require_callback(::Base.PkgId) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.5/Distributed/src/Distributed.jl:75
 [4] require(::Base.PkgId) at /Users/rusty/Development/electricity-modelling/JuliaSysimage.dylib:? (repeats 2 times)
 [5] include(::Function, ::Module, ::String) at /Users/rusty/Development/electricity-modelling/JuliaSysimage.dylib:? (repeats 2 times)
 [6] exec_options(::Base.JLOptions) at /Users/rusty/Development/electricity-modelling/JuliaSysimage.dylib:?
 [7] _start() at /Users/rusty/Development/electricity-modelling/JuliaSysimage.dylib:?
in expression starting at /Users/rusty/.vscode/extensions/julialang.language-julia-1.0.8/scripts/terminalserver/terminalserver.jl:5
```

**Comment by pfitzseb** [comment]
But what are you doing to get that error? If I add `-p 4` to the additional args and then start a process everything works fine, `nprocs()` returns 4 and I can e.g. `pmap` just fine.

**Comment by rustyconover** [comment]
Are you using start repl?

**Comment by pfitzseb** [comment]
Yes, of course.

**Comment by rustyconover** [comment]
On Mac OS X?

**Comment by pfitzseb** [comment]
Linux, but that really shouldn't matter.
Quick demo:
![Peek 2020-10-26 16-17](https://user-images.githubusercontent.com/6735977/97191106-d45ff300-17a6-11eb-9b46-ba1d8bb34172.gif)

**Comment by rustyconover** [comment]
I'm not using an insiders build of VScode.

**Comment by pfitzseb** [comment]
That really shouldn't matter. What version of the Julia extension are you running?

**Comment by rustyconover** [comment]
I haven't installed the extension specifically, how can I list the version
for you?

**Comment by pfitzseb** [comment]
Click on the Extensions button in the toolbar on the left (the four squares thing) and look for Julia. There should be a small version number next to it (e.g. "1.0.8").

**Comment by gwd999** [comment]
Can confirm the same issue ... 
I have a startup.jl that contains the following 
```
## Update all packages, but do so in a worker process
import Distributed
let
    pkg_worker = Distributed.addprocs(1)[end]
    Distributed.remotecall(pkg_worker) do
        redirect_stdout() # silence everything, only on this worker
        Pkg.update()
        # now remove this worker and say we are done
        remotecall(1) do
        eval(quote
              Distributed.rmprocs($(pkg_worker))
              printstyled("\nPkg.update() completed!\n", color=:light_black)
             end
        )
        end
    end
end
```
Which makes the VS Code julia extension "break" - throws a "VSCodeServer is missing"type of error and is not able to execute any julia Code in the REPL.

**Comment by garibarba** [comment]
I think there is a new variation of this issue.

If I set:
```json
    "julia.additionalArgs": [
        "-p 1",
    ]
```

I get on the REPL:
```
ERROR: LoadError: UndefVarError: VSCodeServer not defined
Stacktrace:
 [1] top-level scope
   @ ~/.vscode/extensions/julialang.language-julia-1.6.17/scripts/terminalserver/terminalserver.jl:45
in expression starting at /Users/tho1en/.vscode/extensions/julialang.language-julia-1.6.17/scripts/terminalserver/terminalserver.jl:24
UndefVarError: VSCodeServer not defined
```
and the REPL will not work.
