### ISSUE TITLE
Cant start Julia 1.5 in vs code on mac

### ISSUE THREAD

**Issue by kirgush** [julia-vscode/julia-vscode#1661]
I decide to try vs code instead of atom on mac for julia, but cant start julia running in vs code.

I reinstalled julia and vs code few times but with no results.
I try manually specify julia.executablePath": "/Applications/Julia-1.5.app/Contents/Resources/julia/bin/julia"

But still cant run the debugger.

**Comment by davidanthoff** [comment]
Can you start the REPL with the `Julia: Start REPL` command?

What exactly are you doing to start the debugger?

**Comment by kirgush** [comment]
After latest reinstallation I managed to start Julia `Julia: Start REPL`. 
And Vs-Code managed to find installation itself.
Have no idea of what it was.
Thanks!
