### ISSUE TITLE
Provide an easy to way to switch between compiled sysimages?

### ISSUE THREAD

**Issue by xiaodaigh** [julia-vscode/julia-vscode#1663]
Like how there is a drop-down to change the environment but for compile images.

**Comment by davidanthoff** [comment]
We will automatically pick-up a sysimage that is compiled with the VS Code built-in sysimage compile support for a specific environment. I don't think we want a separate option to then also switch through sysimages, right?

**Comment by xiaodaigh** [comment]
> VS Code built-in sysimage compile

Didn't know about this. Let me check this out then get back.

**Comment by xiaodaigh** [comment]
I think using that feature is fine.
