### ISSUE TITLE
Insert linebreak when pressing enter on suggested word

### ISSUE THREAD

**Issue by jakobnissen** [julia-vscode/julia-vscode#1670]
Whenever you write something, VSCode gives you suggestions. For example, I might write `MyStr`, and it suggests [`MyStruct`, `MyString`]. Pressing enter will autocomplete the topmost suggestion.
However, this autocompletion also happens when you've typed out the full name, e.g. `MyStruct`. In that case, pressing enter only removes the suggestion box, whereas presumably, the user know they already typed the full struct and pressed enter for a linebreak. This is particularly annoying when typing `end`, since it leads you to have to type `E-N-D-enter-enter`.

It would be nicer if, when the word selected from the list exactly matched the current word, a newline was inserted when pressing enter.

**Comment by pfitzseb** [comment]
There's this handy setting:
![image](https://user-images.githubusercontent.com/6735977/93436859-a0ea9880-f8cb-11ea-8eae-6fe59efb535d.png)
I recommend setting it to `off` :)

**Comment by jakobnissen** [comment]
Thank you, Sebastian Pfitzner!

For anyone reading this down the line, besides "on" and "off", there is a "smart" setting which does exactly what I wanted.
