### ISSUE TITLE
How to go to source code in a package?

### ISSUE THREAD

**Issue by RafailFridman** [julia-vscode/julia-vscode#1675]
Hello, is there a way to go to the definition of functions inside packages?
For example, I tried to go to the definition of function `hello` in the `Example` package after writing 
```julia
using Example
hello("Rafail")
```
but no definition was found.

**Comment by pfitzseb** [comment]
You might need to re-index your current environment if you only just added Example.jl. The easiest way to do that is by clicking the `Julia env: ...` selector in VSCode's status bar and re-select the current environment (e.g. `v1.5`).

**Comment by RafailFridman** [comment]
@pfitzseb Thanks, that worked!
