### ISSUE TITLE
VSCode REPL crash whenever using revise and running cell

### ISSUE THREAD

**Issue by Cvikli** [julia-vscode/julia-vscode#1677]
Hey Masters!
I just faced with an issue:
```
#%%
using Revise
#%%
"after including revise, this cell crash the whole REPL"
#%%
```
I could make a picture before it crashed:
![image](https://user-images.githubusercontent.com/11393096/94261925-ebef5600-ff32-11ea-96e7-3ab295fdc3d9.png)

I tried with:
Revise#3.1.2 - julia 1.5.2
Revise#2.7.5 - julia 1.5.1  # and many other
julia-vscode#1.0.8
julia-vscode#1.0.7
There is an issue opened here about it too: [Revise issue](https://github.com/timholy/Revise.jl/issues/544)

I don't see what do I do wrong.

It this issue with the Revise or vscode, I just can't figure it out!

**Comment by davidanthoff** [comment]
Best strategy is probably to just get https://github.com/julia-vscode/julia-vscode/pull/1283 into the product...

**Comment by Cvikli** [comment]
I think the problem is solved. I hope it solve the problem for anyone facing with this issue. :+1: 
https://github.com/timholy/Revise.jl/issues/544#issuecomment-699843627
