### ISSUE TITLE
Weave preview does not work

### ISSUE THREAD

**Issue by mlg556** [julia-vscode/julia-vscode#1683]
When I try to `Julia Weave: Open Preview to the Side` on a `.jmd` file, nothing happens. The output console shows:
```
Weaving preview of /var/folders/13/bsdhjx652b7d4fsyh79c22hr0000gn/T/julia-vscode-weave12092-3475-1445ysu.hvgh/source-file.jmd
[ Info: Ignore
┌ Info: Weaved all chunks
└   progress = 1
[ Info: Weaved to /var/folders/13/bsdhjx652b7d4fsyh79c22hr0000gn/T/julia-vscode-weave12092-3475-1445ysu.hvgh/source-file.html
```
so I'm guessing Weave itself works. However, when I toggle the developer console in VSCode, I see:
```
 ERR ENOENT: no such file or directory, open '/var/folders/13/bsdhjx652b7d4fsyh79c22hr0000gn/T/julia-vscode-weave12092-3475-dlacc5.mqyhw/output-file.html': Error: ENOENT: no such file or directory, open '/var/folders/13/bsdhjx652b7d4fsyh79c22hr0000gn/T/julia-vscode-weave12092-3475-dlacc5.mqyhw/output-file.html'
```
so it is trying to open `output-file.html`, while the correct file should be `source-file.html`. Surely enough, I can open the `source-file.html` file manually and it is correct.

![image](https://user-images.githubusercontent.com/26349315/94968632-f2b93280-0509-11eb-9df0-c30975655d54.png)

```
code --version
1.49.3

julia --version
julia version 1.5.1
```

**Comment by gileoo** [comment]
Having the same issue.

**Comment by pgunnink** [comment]
I had the same problem, and I traced it back to this [Weave.jl bug](https://github.com/JunoLab/Weave.jl/issues/383) that Weave.jl does not properly support the `out_path` option, which is what run_weave.jl relies on: https://github.com/julia-vscode/julia-vscode/blob/25e0ea50f322f5fa472c0d2a38edec1acc3972c0/scripts/weave/run_weave.jl#L20 

An easy solution for now would be to just remove the `out_path` option in run_weave.jl and just assume that that output file is the same as the input file, with the extension changed to `.html`. This is a workaround I guess, but I could make a PR. If that's not preferred I will go and bother the Weave.jl team or file a PR there :)
