### ISSUE TITLE
REPL actively clears LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by tbenst** [julia-vscode/julia-vscode#1684]
Currently, the Julia REPL seems to actively clear environmental variables like `LD_LIBRARY_PATH`. This is disastrous for my setup as julia cannot find many key libraries without this. Setting inside of julia with `ENV["LD_LIBRARY_PATH"] = [...]` does not work for `LD_LIBRARY_PATH`. Related to https://github.com/julia-vscode/julia-vscode/issues/1142, but opened an issue as actively clearing is a distinct issue.

Note that the environmental variables appear as expected in VScode shell, however I see the same behavior in the `Python` extension. Thus, is this unavoidable VScode behavior? In any case, the workaround seems to be using a `.env` file: https://code.visualstudio.com/docs/python/environments#_environment-variable-definitions-file

Also related: https://github.com/julia-vscode/julia-vscode/issues/1679, https://github.com/julia-vscode/julia-vscode/issues/1135

**Comment by pfitzseb** [comment]
This shouldn't happen, I think.
How are you setting `LD_LIBRARY_PATH`? Did you play around with the `terminal.integrated.inheritEnv` setting?

**Comment by Gnimuc** [comment]
In the case of #1679, Julia REPL clears `DYLD_LIBRARY_PATH` even with `terminal.integrated.inheritEnv=true`.

**Comment by pfitzseb** [comment]
That's different -- Julia isn't started via your shell, so env variables set in your zshrc or bashrc or whatever aren't present *unless* you start VSCode from the shell.

**Comment by Gnimuc** [comment]
Starting VSCode from shell does fix the problem. I was starting VSCode from Github Desktop App and all of the env variables were inherited from my .zshrc except `DYLD_LIBRARY_PATH`. Anyway, the ultimate seems to be #1142.
