### ISSUE TITLE
UI/UX: unclear if succeeded when last message is an error

### ISSUE THREAD

**Issue by tbenst** [julia-vscode/julia-vscode#1685]
Imagine I have the following code:
```julia
##
x = [1, 2, 3, 4]
puush!(x,4);
##
```

I run the cell three times and get an expected error. The entire console is now filled with the error message. I then correct `puush` to `push` and rerun the cell. There is no visual indication that the last run succeeded without an error.

**Comment by pfitzseb** [comment]
I'd recommend enabling inline results for this.

**Comment by davidanthoff** [comment]
I don't remember whether we have an option to toggle echoing of the code that is to be executed? That would give another visual indication that something ran.

**Comment by pfitzseb** [comment]
We do have an option for that.

**Comment by davidanthoff** [comment]
Ok, then I think we can close this?
