### ISSUE TITLE
"Send Current line or selection to REPL" do not have inline results shown

### ISSUE THREAD

**Issue by singularitti** [julia-vscode/julia-vscode#1686]
Command "Send Current line or selection to REPL" (shortcut: ctrl + enter) does not show results in inline mode, it only shows that in REPL.

```julia
julia> versioninfo()
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake-avx512)
```

Extension: Julia Insider 1.0.8

VSCode Version: 1.49.3
Commit: 2af051012b66169dde0c4dfae3f5ef48f787ff69
Date: 2020-10-02T17:54:06.165Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.1.0

Settings:
```json
{
  "julia.execution.codeInREPL": true,
  "julia.execution.resultType": "both",
}
```

**Comment by singularitti** [comment]
Just found "Exec file" do not show each result in inline mode either. I hope this can be unified.

**Comment by pfitzseb** [comment]
I can't repro that:
![Peek 2020-10-05 11-16](https://user-images.githubusercontent.com/6735977/95061728-44291380-06fc-11eb-8684-77e9954740da.gif)

`Execute File` will never show inline results -- it's basically `include`.

**Comment by singularitti** [comment]
You are right, "Exec Code Cell And Move" works. My mistake. But "Send Current line or selection to REPL" still does not work for me.

**Comment by pfitzseb** [comment]
That's by design. The command really just copy-pastes the current line into the REPL. For any serious usage I'd recommend `Execute Code` instead.
