### ISSUE TITLE
`eval(expr)` will get a possible method call error

### ISSUE THREAD

**Issue by singularitti** [julia-vscode/julia-vscode#1688]
When I am going to `eval` a quoted expression, Julia-VSCode warns me that it is a "Possible method call error". It seems to treat that as `Core.eval` which request a `Module` as the 1st argument. However, I am using `Base.MainInclude.eval(expr)` so it is a legal Julia statement. Is this a bug and can it be fixed if so?

![image](https://user-images.githubusercontent.com/25192197/95008820-1e601980-05eb-11eb-81ec-5b792b247262.png)

**Comment by singularitti** [comment]
```julia
julia> versioninfo()
Julia Version 1.5.2
Commit 539f3ce943 (2020-09-23 23:17 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake-avx512)
```

Extension: Julia Insider 1.0.8

VSCode Version: 1.49.3
Commit: 2af051012b66169dde0c4dfae3f5ef48f787ff69
Date: 2020-10-02T17:54:06.165Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.1.0

**Comment by JeffBezanson** [comment]
Just ran into this as well. I would say this is a bug.

**Comment by pfitzseb** [comment]
For sure. We're erroneously resolving this to `Core.eval` instead of the `eval` defined in whatever module you're in. The whole method resolution story needs a bit of an overhaul...

**Comment by ZacLN** [comment]
https://github.com/julia-vscode/StaticLint.jl/pull/237
