### ISSUE TITLE
Plots pane options only appear when clicked on

### ISSUE THREAD

**Issue by ElectronicTeaCup** [julia-vscode/julia-vscode#1691]
Sometimes you can miss the plots pane options (since they disappear) if you have recently clicked on the editor. Would it be possible for the options to permanently appear, without having to click on the pane?

![plotpane](https://user-images.githubusercontent.com/31346583/95129861-ed532680-075b-11eb-9591-806709feeaa8.gif)

**Comment by pfitzseb** [comment]
Not easily. This needs custom UI, afaict.

**Comment by davidanthoff** [comment]
I'm inclined to close this because this just seems a generic VS Code UI decision beyond our control... The situation might also generally be solved once we have the plot thumbnail view added.
