### ISSUE TITLE
Avoid terminal instance to close when Server crash

### ISSUE THREAD

**Issue by josePereiro** [julia-vscode/julia-vscode#1697]
Hi, sorry for the lack of details, but it is part of the issue. Sometimes when I'm using the `Shift + enter` workflow I run some code that crash the Server, but almost instantly the terminal instance that I was using also terminate so I can't read the error messages to know what happened. 

Is it any configuration that I can set to avoid that?

Thanks

**Comment by davidanthoff** [comment]
I think the only way we could achieve this is to have a wrapper process around our Julia instance, but that is kind of annoying. OR hope that upstream they at some point give us an option to not terminate a terminal if it crashes :)

**Comment by pfitzseb** [comment]
https://github.com/julia-vscode/julia-vscode/pull/1893 also fixes this issue (if running under tmux, that is). :)

**Comment by pfitzseb** [comment]
Dup of https://github.com/julia-vscode/julia-vscode/issues/1560.
