### ISSUE TITLE
Julia: run file runs the debugger 

### ISSUE THREAD

**Issue by BenCzaczkes** [julia-vscode/julia-vscode#1698]
I am a new user so might be doing something wrong but I tried to follow 
"https://www.julia-vscode.org/docs/stable/gettingstarted/#Installation-and-Configuration-1"
specifically 
"To run the Hello World program, click Run: Julia File in Terminal play button in the top-right side of the editor."
This ran the debugger
CTRL-F5 does the same

the extension is version 1.08
Julia is 1.52
vscode info:
"Version: 1.50.0 (user setup)
Commit: 93c2f0fbf16c5a4b10e4d5f89737d9c2c25488a3
Date: 2020-10-07T06:10:52.432Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
"
thanks very much

Having looked through similar postings it seems that the problem came up a few times on discourse and as git issues.
Maybe for now just change the basic introduction in the documentation so it works?
Sorry if I am barging into open doors but the experience was quite disconcerting for a newbie :(

**Comment by R366Y** [comment]
You are not alone, I'm having the same issue with **julia-vscode 1.0.8**.
Before this version it was possible to launch a julia file without debugger with command _Julia: Execute code_, now regardless what I choose it launches the debugger every time. Even if I try suggested command **Run: Start without debugging CTRL+F5**

**Comment by FHell** [comment]
Seeing this too.

**Comment by clintonTE** [comment]
Theres a lot to like about VSCode, but I'm finding this and the inability to exclude directories from indexing #1085  a real experience killer.

**Comment by pfitzseb** [comment]
`Execute File` really is the recommended way to run a file, especially if you're used to Juno's behaviour. The next release will make that command more discoverable.

**Comment by FHell** [comment]
> `Execute File` really is the recommended way to run a file, especially if you're used to Juno's behaviour. The next release will make that command more discoverable.

@pfitzseb that doesn't change the bug that Run File, accessible through the button at the very top of the screen, has the wrong behaviour right now (namely, the same as the Debug File Button next to it). That's really a major usability bug that will hit every single person that first uses Julia in VSC.

**Comment by pfitzseb** [comment]
Right. It's also not something we can fix because it's a VSCode bug. And that button will default to `Execute File` on insiders and the next release.

**Comment by FHell** [comment]
@pfitzseb Great to hear!

**Comment by ThomasChaffey** [comment]
> Right. It's also not something we can fix because it's a VSCode bug. And that button will default to `Execute File` on insiders and the next release.

This is great to hear!  When I first started using VScode I was tearing my hair out because of the behaviour of the "play" button with plots.  

In the mean time, is there a quick way to change the binding of the play button from "run file" to "execute file"?

(Sorry if this is a basic question in the wrong place).

**Comment by pfitzseb** [comment]
No, unfortunately there isn't. You could however add a convenient keybinding to `Run File` (like [here](https://github.com/julia-vscode/julia-vscode/wiki/Keyboard-shortcuts#replicating-juno-shortcuts)).

**Comment by davidanthoff** [comment]
Is there still anything left to do for us? I don't think so, right? I'm going to close for now.
