### ISSUE TITLE
Valid multiline-comments can lead to Parsing Error

### ISSUE THREAD

**Issue by erik-f** [julia-vscode/julia-vscode#1701]
This (admittedly weirdly formatted) valid multiline-comment produces a parsing error when linting is enabled:
```julia
#=# example with spaces
next line=#
```
This only happens if one places the second `#` in `#=#` and the first line contains multiple words.

**Comment by ZacLN** [comment]
https://github.com/JuliaLang/Tokenize.jl/pull/159
