### ISSUE TITLE
Function call doesn't work in VS code

### ISSUE THREAD

**Issue by RonBarakBackal** [julia-vscode/julia-vscode#1702]
Hello! and thank you very much in advance
I think the Julia language is awesome and you help to spread it

However, in VS code the language seems to work not so well, for example:

function gaxpy(y,x,a)
    y = y+a*x
end

saxpy([4;6;8],[4;4],[5 5; 6 6 ; 7 8])

in Julia shell you will get the matrix
[44 ; 54 ; 68]

in VS code I get two problems when debugging:
Parsing error Julia(Julia) [1,1]
Parsing error Julia(Julia) [3,1]
So the code doesn't know how to debug the function call and how to debug end

Thanks!

**Comment by pfitzseb** [comment]
I can't reproduce any error (after fixing the `saxpy` -> `gaxpy` typo). How are you running the code?

**Comment by RonBarakBackal** [comment]
Thqnk you very much!
i open VS code 2019, I installed the extension, opened a folder and tried
to  opened q file I saved as julia, then typed thr code and Run-->starr
debugging
