### ISSUE TITLE
support new syntax "import ... as ..." in Julia 1.6?

### ISSUE THREAD

**Issue by Roger-luo** [julia-vscode/julia-vscode#1703]
https://github.com/JuliaLang/julia/pull/37396 implements `import ... as ...` syntax which will appear in Julia 1.6, would be nice that vscode-julia supports it, or at least don't treat that as an invalid syntax error in the linter first. 

This should also close #1237

**Comment by ZacLN** [comment]
https://github.com/julia-vscode/CSTParser.jl/pull/220
