### ISSUE TITLE
PATH not set when launching the language server

### ISSUE THREAD

**Issue by fredrikekre** [julia-vscode/julia-vscode#1704]
It seems that `PATH` does not have the expected value, and is not exported when VSCode launches the language server.

I set the `Julia Executable Path` setting to the following wrappers script:
```bash
$ cat julia-wrapper 
#!/bin/bash

{
echo "---- START SCRIPT ----"
echo "PATH=$(declare -p PATH)"
echo "ARGS=$@"
} >> /home/fredrik/vscode-test/test.log

exec julia "$@"
```
and I see the following output
```
$ cat test.log 
---- START SCRIPT ----
PATH=declare -x PATH="/home/fredrik/bin:/home/fredrik/.local/bin:/home/fredrik/bin:/home/fredrik/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
ARGS=--version

---- START SCRIPT ----
PATH=declare -- PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
ARGS=--startup-file=no --history-file=no --depwarn=no --project=/home/fredrik/.vscode/extensions/julialang.language-julia-1.0.8/scripts/environments/languageserver main.jl /home/fredrik/vscode-test --debug=no /tmp/vsc-jl-cr-19815  /home/fredrik/.config/Code/User/globalStorage/julialang.language-julia
```

Why is this happening?

For reference, here is the output from `Julia: Start REPL`:
```
---- START SCRIPT ----
PATH=declare -x PATH="/home/fredrik/bin:/home/fredrik/.local/bin:/home/fredrik/bin:/home/fredrik/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
ARGS=-i --banner=no --project=/home/fredrik/vscode-test /home/fredrik/.vscode/extensions/julialang.language-julia-1.0.8/scripts/terminalserver/terminalserver.jl /tmp/vsc-julia-repl-19815 /tmp/vsc-jl-cr-19815 USE_REVISE=true USE_PLOTPANE=true DEBUG_MODE=undefined
```

cc @staticfloat

**Comment by davidanthoff** [comment]
We generally try to run the LS in an as controlled way as possible and try to disable any user config settings being passed on to it. We essentially consider it an internal implementation detail that users should not change anything about. In fact, we hope to at some point just ship a compiled binary version of it, at which point it would be entirely disconnected from any user installed Julia version.

The code that does this is [here](https://github.com/julia-vscode/julia-vscode/blob/d3f98a00f498d1e3765a342dc65f316d1ab4064a/src/extension.ts#L145), and I believe the way it is coded right now it won't pass any env variables on.

Can you say a bit more what you are trying to do in this scenario?

**Comment by fredrikekre** [comment]
Thanks, I was under the impression that VSCode launched the language server so I did not look closely here after those settings.

> Can you say a bit more what you are trying to do in this scenario?

I am hooking up [`direnv`](https://github.com/direnv/direnv) to work correctly with this plugin. I need the wrapper script in order to call `direnv` to set up `PATH`, and then the script finds `julia` in this new modified `PATH` and `exec julia`.

However, even without `direnv` I think it is useful to pass `PATH` since then you can use `julia` as `Julia: Executable PATH`. This is what I have always had before, I just happened to have `julia` found in the default path (`/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`) so I never noticed this before. For example, you might not have admin rights and put julia in `/home/fredrik/.local/bin` or something, and as it is not the extension would not find julia.

> We generally try to run the LS in an as controlled way as possible and try to disable any user config settings being passed on to it.

Yea, that makes sense, but is there something in the code that interacts with `PATH`?

> In fact, we hope to at some point just ship a compiled binary version of it, at which point it would be entirely disconnected from any user installed Julia version.

Interesting, so it doesn't have to be the same julia binary (e.g. same version) that you use to launch the builtin REPL?

**Comment by pfitzseb** [comment]
Yeah, I missed that yesterday. If we explicitly pass `PATH` into the LS process things should work fine. You can use `julia` or whatever other command even with the current solution, because we resolve that beforehand.

> Interesting, so it doesn't have to be the same julia binary (e.g. same version) that you use to launch the builtin REPL?

No (in theory). In practice it makes everything much easier if the versions match at least.

**Comment by fredrikekre** [comment]
> If we explicitly pass PATH into the LS process things should work fine.

Right, so is there any downside? If the language server does not spawn any external processes it shouldn't, right?

**Comment by pfitzseb** [comment]
It spawns more Julia processes, but yes, I think it should be fine to pass `PATH` along ;)

**Comment by fredrikekre** [comment]
I believe this is issue is a red herring -- the real "problem" is that `$PWD` was not what I expected, for the smoke-test `--version` call it is `/home/fredrik` (on launch of VSCode altogether), when starting the language server it is `/home/fredrik/.vscode/extensions/julialang.language-julia-1.0.8/scripts/languageserver` and only when starting the REPL it is what I thought all processes had; the project root path.

**Comment by fredrikekre** [comment]
https://github.com/julia-vscode/julia-vscode/pull/1707 is good enough for me. What are the plans for a new release if I may ask?

**Comment by pfitzseb** [comment]
Hopefully this week.
