### ISSUE TITLE
add-ing a package from remote console  results in permission denied

### ISSUE THREAD

**Issue by drozzy** [julia-vscode/julia-vscode#1706]
If I connect to remote machine using remote extension, and then try to install a package:

```
] add Flux
```
I get this error:
```
ERROR: IOError: mkdir: permission denied (EACCES)
```

**Comment by pfitzseb** [comment]
This isn't an issue with `julia-vscode`. Did you make sure that the you're logging in as the same user that created the package dir and have permissions to change that?

**Comment by drozzy** [comment]
Yes, this was an issue of me not activating the right julia environment from vscode.
It works now. Thanks.
