### ISSUE TITLE
Surface plot not working in plotly or plotlyjs backend

### ISSUE THREAD

**Issue by crlaugh** [julia-vscode/julia-vscode#1716]
When I use the following code to generate surface data in VSCode, I get a plot that doesn't show anything.  This behavior was also referenced in https://github.com/JuliaPlots/Plots.jl/issues/3052.

```
using Plots

xTest = collect(Float16, range(-2,length=100,stop=2));
yTest = collect(Float16, range(sqrt(2),length=100, stop=2));
fEval = zeros(length(xTest), length(yTest))
for (ix, xVal) in enumerate(xTest)
    for (iy, yVal) in enumerate(yTest) 
        fEval[ix, iy] = xVal*yVal-xVal-yVal+1
    end
end

plotly()
surface(fEval)
plot(xTest, yTest, fEval, st=:surface)
```

![image](https://user-images.githubusercontent.com/9616147/97066286-27a52c00-1582-11eb-8d4e-97518450db81.png)

This problematic behavior is only demonstrated in VSCode; if I do the same thing in either Atom or a Julia terminal (all examples in Windows), the plot is correct.  

My VSCode information is: 
Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

and Julia terminal in VSCode: 
  [c52e3926] Atom v0.12.21
  [aae01518] BandedMatrices v0.15.20
  [336ed68f] CSV v0.7.7
  [5ae59095] Colors v0.12.4
  [8f4d0f93] Conda v1.4.1
  [a93c6f00] DataFrames v0.21.7
  [5789e2e9] FileIO v1.4.3
  [033835bb] JLD2 v0.2.3
  [e5e0dc1b] Juno v0.8.3
  [47be7bcc] ORCA v0.5.0
  [14b8a8f1] PkgTemplates v0.7.10
  [a03496cd] PlotlyBase v0.4.1
  [f0f68f2c] PlotlyJS v0.14.0
  [91a5bcdd] Plots v1.6.4
  [438e738f] PyCall v1.91.4
  [295af30f] Revise v2.7.6 ⚲
  [44cfe95a] Pkg

I am using Julia 1.5.1 in Win10.

**Comment by pfitzseb** [comment]
What happens with a significantly smaller data set, e.g. `surface(rand(2,2))`?

**Comment by crlaugh** [comment]
Exactly the same behavior; 

```
using Plots

xTest = collect(Float16, range(-2,length=2,stop=2))
yTest = collect(Float16, range(sqrt(2),length=2, stop=2))
fEval = zeros(length(xTest), length(yTest))
for (ix, xVal) in enumerate(xTest)
    for (iy, yVal) in enumerate(yTest) 
        fEval[ix, iy] = xVal*yVal-xVal-yVal+1
    end
end

plotly()
plot(xTest, yTest, fEval, st=:surface)
```

![image](https://user-images.githubusercontent.com/9616147/97087540-ed2aa600-15f8-11eb-932b-edfa138cfb74.png)

**Comment by crlaugh** [comment]
`surface(rand(2,2))`

![image](https://user-images.githubusercontent.com/9616147/97087558-0b90a180-15f9-11eb-8bab-7b7dc9e3449c.png)

**Comment by BoundaryValueProblems** [comment]
@pfitzseb ; I am wondering whether this serious problem is fixed soon. This issue prevents me and my students to move from Atom/Juno to VSCode since interactive 3D plots are quite important for us. Thanks!

**Comment by pfitzseb** [comment]
Thanks for bumping this, had completely forgotten about it. Will look into it soon.

**Comment by BoundaryValueProblems** [comment]
Thank you very much! I just tried this new version, i.e., julia-vscode v1.1.14 under VSCode, and the surface plot under the plotlyjs backend of Plots.jl now works beautifully!

**Comment by christineymshen** [comment]
I encountered the same issue today, using julia v1.8 and julia-vscode v1.41.1
