### ISSUE TITLE
formatting never completes

### ISSUE THREAD

**Issue by baggepinnen** [julia-vscode/julia-vscode#1717]
When I execute the formatter in vscode, it appears to think forever and never format the document. In the bottom bar, there appears three instances of "Formatting..."

```
JuliaFormatter v0.10.8

vscode:
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:44:48.716Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-48-generic
```

**Comment by baggepinnen** [comment]
Hmm, restarting vscode and trying again did the trick. Feel free to close this issue if it's deemed to be a fluke.

**Comment by pfitzseb** [comment]
That sounds wrong. Are you in an exceptionally large file or something? Formatting is basically instant for me.

**Comment by baggepinnen** [comment]
The following file takes more or less the same 8 seconds to format each time I try
```julia
using CSV, DataFrames
file = CSV.File("/home/fredrikb/Documents/j1_a30_5conf.csv"; header = 7, datarow = 26)
```

**Comment by pfitzseb** [comment]
Should be fixed in the next version of the extension.
