### ISSUE TITLE
Tab complete does not work on remote

### ISSUE THREAD

**Issue by jgslazzaro** [julia-vscode/julia-vscode#1722]
Hi,

I use Julia VScode in my local computer and also in a remote server using Remote SSH development.

The extension works great in my local machine. In the remote one, I am able to use all functionalities of the Julia extension except the autocompletion. 
For example: 

\alpha+[tab] does not do anything. 
I write for+[tab] nothing happens while in the local one I get in and end of the for loop statement automatically.  

I just noticed that the auto formatting feature is also not working in the remote machine.

Does anyone know what can be causing this issue in the remote server?

Thanks!

**Comment by davidanthoff** [comment]
Can you start a Julia REPL on the remote machine in VS Code?

**Comment by jgslazzaro** [comment]
The REPL works great on the remote machine. ctrl+enter and other commands
to execute code also work. But none of the auto-complete features are
working as they do in my local machine.

**Comment by pfitzseb** [comment]
Then the language server doesn't start up for you. Can you check the corresponding output tab for any messages?

**Comment by jgslazzaro** [comment]
I am sorry, but how do I do that?

**Comment by davidanthoff** [comment]
The UI for this is here:

![image](https://user-images.githubusercontent.com/1036561/110985362-3cac0d00-8321-11eb-8da8-220ed694af17.png)

**Comment by jgslazzaro** [comment]
Thanks!
I need to use a script to run julia on the remote server, so I guess it is
not loading the language server as well...
Here is the output:
[Error - 2:22:04 PM] Connection to server is erroring. Shutting down server.
/path_to_sh_file/.load_modules/load_julia.sh: line 1: module: command not found
path_to_sh_file/load_julia.sh: line 3: julia: command not found
[Error - 2:22:04 PM] Connection to server is erroring. Shutting down server.

**Comment by davidanthoff** [comment]
Ah, I'm pretty positive this won't work, i.e. we need to find the actual Julia binary, not a script that launches the Julia binary...

I think our medium term plan to solve this is to ship a precompiled version of the language server, so that that part works independently of any installed Julia version.

**Comment by jgslazzaro** [comment]
Thanks for your help!
In the meantime I will keep using the extension Fast Unicode Math
Characters, which is not ideal but works. I am anxiously waiting for the
precompiled version.
I really like Julia-vscode, Thanks for the good work!

**Comment by pfitzseb** [comment]
No, having an intermediary script is fine as long as it forwards all arguments properly. Seems like you need to hard code the path to `julia` instead of relying on your .bashrc (presumably)  being loaded.

**Comment by jgslazzaro** [comment]
This was so simple, it is working now! I just changed the commands of my
script to the path to julia as you said.
Having access to the functions descriptions and autocomplete once again
will be very helpful.

Thanks!
