### ISSUE TITLE
Plot pane captures plots despite being deactivated

### ISSUE THREAD

**Issue by baggepinnen** [julia-vscode/julia-vscode#1723]
I find that vscode often captures plots in  the plot pane even though I've deactivated this option and restarted vscode, but it only appears to happen if I inline eval code, not from the REPL. If I issue a plot command from the repl, the plot shows in a standalone gui, but if I inline eval, the gui pops up for a split second but then goes away and the plot is captured in the plot pane.
I also have an issue where for instance evaluating the following as a block
```julia
plot(...)
plot!(...)
plot!(...)
plot!(...)
```
shows 4 plots instead of only the last one like in Juno. This is mostly a problem with plotly, which opens a crazy amount of browser tabs when using vscode.

**Comment by davidanthoff** [comment]
Is this still the case? I think there were some updates to this stuff?

**Comment by pfitzseb** [comment]
Yes, pretty sure I fixed that.
