### ISSUE TITLE
Julia VS code extension crashes

### ISSUE THREAD

**Issue by ampbj** [julia-vscode/julia-vscode#1726]
Hi,
Julia extension has been crashing constantly with the message:

┌ Warning: Some Julia code in the VS Code extension crashed with
│   e = Endpoint is not running, the current state is closed.
└ @ VSCodeDebugger ~/.vscode/extensions/julialang.language-julia-1.0.8/scripts/error_handler.jl:5

**Comment by mw8** [comment]
I have run into a similar issue. Here is a minimal working example.

`using Plots
display(plot(rand(5, 5)))`

When I run this code from the REPL, it creates a plot in the plots pane correctly. When I paste this code into a Julia script and then select "Run without Debugging" from the Run menu, it creates a plot in a new window and then it crashes and I get the same error shown above.

Julia Extension Version: v1.0.8

VS Code version:
Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:53:05.704Z (2 wks ago)
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.4.0

**Comment by mdmilgrom** [comment]
I'm also having this issue with a very basic file when I enable a breakpoint and try to debug.
Name: Julia
Id: julialang.language-julia
Description: Julia Language Support
Version: 1.0.10
Publisher: julialang
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=julialang.language-julia
VS Code Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:30:02.420Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
`s0 = [0;0]
Wss = [-1. 0;0 1]
Wsx = [1. 0;0 1]
x1 = [[1.;0],[1.;0]]
x2 = [[1.;0],[0.;1],[0;1]]
x3 = [[0.;1],[1.;0],[1;0]]

f1(z::Float64) = max(0,z)
f2(z::Float64) = z >= 1. ? 1 : 0

function S_T(X::Array{Array{Float64,1},1}, Ws::Matrix{Float64}, Wx::Matrix{Float64})
    global s0
    local s
    T = length(X)
    #@assert(T == size(Wss,2))
    #breakpoint on line below
    s = s0
    for x in X
       s = f1.(Ws * s + Wx * x)
    end
    println(s)
    return s
end

for X in (x1, x2, x3)
    #println(S_T(X,Wss,Wsx))
end
#4.4
s = [[1;1],[0;0]]
IV = [1. 0; 0 1]
Wss = IV
Wsx = [IV, -1 .* IV]
global s0
for s0 in s
    println("s0: ",s0)
    for w in Wsx
        println("Wsx: ",w)
        for X in (x1, x2, x3)
            println(S_T(X,Wss,w))
        end
    end
end`

**Comment by pfitzseb** [comment]
Are you sure this is a genuine crash? IIRC we're just erroneously reporting a crash when the debugger finishes running your code. You could also try running your code with the in-process debugger (`@run`/`@enter`).

**Comment by mdmilgrom** [comment]
It never reaches my breakpoint so *something* goes wrong.
It appears to fail due to ```global s0``` in that code. Without that line the program runs, albeit incorrectly, as ```s0``` has the wrong value. I just refactored it to pass a parameter, which I guess is better general style, but this was only to solve a specific problem, not be production code.

**Comment by diatomicDisaster** [comment]
I am also experiencing this issue on an incredibly simple piece of code when trying to add a breakpoint.

````
   using Dierckx

   x = [1., 2., 3., 4.]
> y = x.^2
   spl = Spline1D(x, y)

   x = spl(1.5)
```
It runs fine without the breakpoint.

**Comment by pfitzseb** [comment]
That code works fine for me when debugging in a new process. 
The original issue seems to be fixed as well.

**Comment by amrit-poudel** [comment]
Julia (v1.6.4) debugger does not quite  work for me in vscode (1.63). 

> Connecting to debugger... Done!

┌ Error: Some Julia code in the VS Code extension crashed
└ @ VSCodeDebugger ~/.vscode/extensions/julialang.language-julia-1.5.6/scripts/error_handler.jl:15
ERROR: ArgumentError: lowering did not return a `:thunk` expression, got $(Expr(:toplevel, :(#= /Users/

**Comment by DavidSagan** [comment]
I have run into this too. For me the problem was an error in the file being run that prevented the compiler from compiling the code prior to running.
