### ISSUE TITLE
Add option to resize plots in the plot pane

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/julia-vscode#173]
This is going to be tricky, more a long term goal... Ideally the plots would fill the whole plot pane area.

**Comment by ZacLN** [comment]
I was thinking about this (in relation to having a pane to display `@profile` output). I know we can't run arbitrary javascript in html/svg panes but can we embed it in the typescript side of the vscode extension somehow?

**Comment by davidanthoff** [comment]
I actually think we can run arbitrary javascript in the pane, I don't think it is sandboxed. I'm more worried how the scaling would work. If we use an html or svg representation of the plot for viewing I assume we could scale it, but the plots might not look good, i.e. one might need to get a new svg for a different solution from the plotting library, which would be really tricky to achieve. But maybe I'm wrong, not sure. When we get things as PNG from julia, we really can't scale it, I guess.

**Comment by tbenst** [comment]
Right now, my hack workaround is to ctrl +/- to rescale the entire VSCode GUI. Would love to be able to scale Julia Plots

**Comment by davidanthoff** [comment]
We have a new plot pane coming soon (TM), and I think that will support some level of zooming.

**Comment by ElectronicTeaCup** [comment]
PlotlyJS manages to scale to the size of the pane---could it at least offer a hint to manage this with plots.jl using plotly backend (which currently does not scale)?

**Comment by zerefwayne** [comment]
> We have a new plot pane coming soon (TM), and I think that will support some level of zooming.

@davidanthoff Any updates on this?

**Comment by pfitzseb** [comment]
This is implemented now.
