### ISSUE TITLE
Clear inline results

### ISSUE THREAD

**Issue by phlavenk** [julia-vscode/julia-vscode#1746]
Clear inline results when connected Julia session is terminated (or new session is started).

Current behavior is that all the in-line results stay displayed until the expression is re-run. I know that the inline-results do not represent the program state - that's the task for JuliaExplorer tab - but I personally use the in-line result view to track which part of my scripts has been already run, heavily relying on code sections ( ##). 

However, I'd argue that the reason a REPL session is restarted is to throw away the mess one has caused in the previous session and all the in-line results are just invalid. And, with having a fresh REPL one expects to also have fresh view on the code with cleared in-line results.

**Comment by pfitzseb** [comment]
This is already implemented on master and insiders :)

**Comment by phlavenk** [comment]
Thank you.
