### ISSUE TITLE
typo in recent commit that breaks table view / vscodedisplay 

### ISSUE THREAD

**Issue by kragol** [julia-vscode/julia-vscode#1748]
There seems to have been an unfortunate typo in caf3cf32e5e4cb5f1441ac71f64a1c4c00a7f4a3.
Line 38 of `julia-vscode/scripts/packages/VSCodeServer/src/display.jl` currently reads
```julia
payload = stringmime(MIME("application/vnd.datareso urce+json"), x)
```
notice the space in "vnd.datareso urce+json".

Removing the space makes table view working again in the latest insider build (1.0.9).

**Comment by pfitzseb** [comment]
Thanks, good catch!
