### ISSUE TITLE
Alt+Enter doesn't send input to REPL

### ISSUE THREAD

**Issue by JeffBezanson** [julia-vscode/julia-vscode#1752]
I have Ctrl+Enter set to paste the input line in the REPL, where it also then gets added to the history. However, Alt+Enter doesn't do that. Is there a separate setting for that, or does this need to be added?

**Comment by aviatesk** [comment]
<kbd>alt-enter</kbd> doesn't send code to REPL, but evaluates it via `include_string`. 
Appending the evaluated code to REPL history would still be possible.
