### ISSUE TITLE
Debugger gives no ouput when using imports

### ISSUE THREAD

**Issue by adomasbaliuka** [julia-vscode/julia-vscode#1763]
Issue Type: <b>Bug</b>

I'm using the standard debugger with no launch.json file (I haven't tried solving the problem by making a launch file but certainly not using any launch file is allowed by the extension). When the code I'm debugging includes files and imports modules from them, the debugger does not break on breakpoints and produces no output at all, except "Julia debuggee finished. Press ENTER to close this terminal."

# Code example:
```julia
# # mymodule.jl
# module MyModule
# export num

function num(x)
    return 42
end
# end
```

```julia
# # main.jl (the file I am debugging)
include("mymodule.jl"); # using .MyModule

a = 2
println("Hello world")
println(num(a))
println(a)
```

# Instructions to reproduce bug
Copy the two codefiles into the same folder, which is opened in VS code with Julia extension. Run `main.jl` to see that the code works. Run `main.jl` in the debugger, with breakpoints on a few lines in `main.jl`, to see that debugging works.

Remove the first occurence of the `#` character in each line of code, thus introducing the use of modules. I believe this way of importing modules from files in the same project is standard in Julia v1.5.2 (see, e.g., [stackoverflow](https://stackoverflow.com/q/37200025/9988487)). Run `main.jl` again to see that it does the same thing as before. Now run `main.jl` in the debugger,  with breakpoints on a few lines in `main.jl`. My result when doing this: All breakpoints are ignored and the program ends with no output whatsoever, except "Julia debuggee finished. Press ENTER to close this terminal.".
 
# System information
Extension version: 1.0.8
VS Code version: Code 1.51.0 (fcac248b077b55bae4ba5bab613fd6e9156c2f0c, 2020-11-05T18:18:23.642Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (6.01GB free)|
|Process Argv|--crash-reporter-id bd45eb4e-4b1a-4088-9e9c-fc7825d22b47|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by pfitzseb** [comment]
This seems to be fixed now (on master and/or insiders).
