### ISSUE TITLE
How to set the environmental variable DEPOT_PATH in this extension

### ISSUE THREAD

**Issue by PyDataBlog** [julia-vscode/julia-vscode#1764]
Currently, I ran julia aliased from `JULIA_DEPOT_PATH=/data/julia /data/julia-1.5.3/bin/julia` on my Ubuntu system as I prefer this julia depot path.

I want to pass JULIA_DEPOT_PATH=/data/julia as an environmental variable in the settings JSON but I can't seem to find any place to place this variable.

How do I tell the Julia extension to set this DEPOT_PATH permanently before running Julia?

**Comment by pfitzseb** [comment]
I don't think you can do that in the settings, but I'd recommend setting the env var before starting VSCode.
