### ISSUE TITLE
Feature request: Run cells etc

### ISSUE THREAD

**Issue by xgb1206** [julia-vscode/julia-vscode#177]
It would be great if we could have the ability to run cells etc like in Juno and Jupyter.

**Comment by davidanthoff** [comment]
Yep, that is certainly high on my list as well!

**Comment by ZacLN** [comment]
How do you mean? Evaluate the block/toplevel expression that the cursor is in?

**Comment by alha02** [comment]
Well yes that, but also the possibility to run cells of code like in e.g. [Jupyter](https://github.com/DonJayamanne/pythonVSCode/wiki/Jupyter-Examples). Basically all running functionality available in [Juno](http://junolab.org/) would be very useful.

**Comment by ZacLN** [comment]
I'm not sure this can be done at the moment. I don't think there's any way for the server to request an arbitrary command call on the client side (which you'd need to send selected text to the terminal).

**Comment by davidanthoff** [comment]
Yeah, this requires a different mechanism in how we send code to the REPL. I have a plan, but it is blocked by #105.

**Comment by ZacLN** [comment]
For when it becomes possible see [here](https://github.com/ZacLN/LanguageServer.jl/blob/eval-cell/src/provider_action.jl#L52) for cell/region selection code

**Comment by DNF2** [comment]
This feature is one of the main things I miss from Matlab. Organizing top-level scripts in cells that can quickly be run multiple times is very convenient.

One of the python plugins for VS Code also has this: https://donjayamanne.github.io/pythonVSCodeDocs/docs/jupyter_getting-started/#Running-a-cell-in-a-kernel  (though I would prefer a keyboard shortcut.)

**Comment by StevenLi-DS** [comment]
I really like how the Python extension works in vscode and hopefully, we can have something similar for Julia

**Comment by davidanthoff** [comment]
Has been shipping for a while.
