### ISSUE TITLE
Tab completion works outside but not inside code blocks

### ISSUE THREAD

**Issue by kapple19** [julia-vscode/julia-vscode#1776]
Inside .jmd files, tab completion doesn't work inside Julia code blocks, as such.

![2020-11-18 (7)](https://user-images.githubusercontent.com/48305293/99523697-875cee80-29eb-11eb-9198-bf23da4de1e5.png)

However, the tab completion works outside the code block.

![2020-11-18 (8)](https://user-images.githubusercontent.com/48305293/99523812-ace9f800-29eb-11eb-9094-82f51868b1f9.png)

Is this a bug?

**Comment by ZacLN** [comment]
Yes it is, addressed https://github.com/julia-vscode/LanguageServer.jl/pull/856/commits/9c20068f008d489eac6afeb76c8d62a87ee99792. Will work it's way into the next julia-vscode release
