### ISSUE TITLE
Feature request: Inline results and output pane

### ISSUE THREAD

**Issue by ghost** [julia-vscode/julia-vscode#178]
In Juno, the results of evaluations are displayed inline, with the ability to expand and so on. All errors or other messages are instead sent to a separate output pane

**Comment by davidanthoff** [comment]
We won't be able to do inline displays unless VS Code enables that in some form for extensions. In the meantime I think we'll have the *.jmd support (that I plan to greatly expand), and the plot pane.

But I agree, it would be great to have this feature!

**Comment by davidanthoff** [comment]
There has been some progress on the VS Code side of things. The two relevant issues are https://github.com/microsoft/vscode/issues/3220 and https://github.com/microsoft/vscode/issues/85682.

But until VS Code ships an API for this, we are blocked on this feature.

**Comment by pfitzseb** [comment]
https://marketplace.visualstudio.com/items?itemName=betterthantomorrow.calva has an interesting approach to inline results that we could maybe go with in the meantime.

**Comment by davidanthoff** [comment]
The thing that appears to the right? I.e. just a little bit of info restricted to that line of code, right?

**Comment by pfitzseb** [comment]
Yes. I think it's implemented the same way as that git extension that shows when you last modified a line. We potentially could show additional info on hover (but I'm not sure how easily that's possible with the VSCode API).
