### ISSUE TITLE
stuck on "julia language server starting..."

### ISSUE THREAD

**Issue by kgeusens** [julia-vscode/julia-vscode#1780]
Setup:
windows 10 vscode client connecting to WSL2 with VSCode remote extenstion
julia version 1.15 running in WSL2 ubuntu 20.04 (server side)

Starting version 1.10, the language server fails to initialize. The vscode status bar keeps displaying the "Starting Julia language server" message, but never succeeds.
The process for the language server does not show up on the server in "ps -ef"

Installing the previous version of the julia vscode extension solves the problem.

**Comment by charlesbrodhead3** [comment]
Not sure if this is helpful, but after deleting .julia directory, then installing Julia 1.5.3 on Windows 10, I also got stuck on "Julia Language Server Starting..." for 30+ minutes.  I uninstalled/reinstalled Julia Language Support 1.0.10 and it immediately starting indexing and behaved normally.

**Comment by PatrickGoettsch** [comment]
It helped for me too. I had this issue under Ubuntu 20 with vs-code and vs-code insider and julia 1.5.3.
After reinstalling the julia vscode extension it worked for me. Thanks for the tipp.

**Comment by dpdannemiller** [comment]
I have the same issue on Mac, but the error came back after reinstalling.

Details:

Hardware: 13-inch, 2020, Four Thunderbolt 3 ports
OS: MacOS Catalina 10.15.7

Completely deleted VS Code and Julia, including the following folders:
/Applications/Visual\ Studio\ Code.app
/Applications/Julia-1.5.app
~/Library/Application Support/Code/
~/.julia
~/.vscode

Clean install Julia 1.5.3 and VS Code 1.51.1 using the directions here:
https://github.com/julia-vscode/julia-vscode#installing-juliavs-codevs-code-julia-extension

Only julia extension 1.0.10 is installed.

==========
Open folder that has only 1 file named "hello.jl" with contents:
print("Hello world!")

The message at the bottom status line of VS Code says "Starting Julia Language Server ...", and that message does not go away.

==========
Click the triangle "Julia: Execute File" produces the following in the TERMINAL pane:

[ Info: Precompiling VSCodeServer [9f5989ce-84fe-42d4-91ec-6a7a8d53ed0f]
Hello world!
julia> 

Output pane is blank.

"Starting Julia Language Server ..." is still present on the status line.

==========
Place cursor in line 1 of the editor, and option-return. Expect that line of code to execute. Instead:

Lower left of the VS Code window (above status line):
"Error: Julia Language server is not running. Please wait a few seco..."

"Starting Julia Language Server ..." is still present on the status line.

No additional output is produced in the TERMINAL.

==========
Restart VS Code. "Starting Julia Language Server ..." is still present on the status line.

**Comment by kgeusens** [comment]
I tried all flavors of uninstalling, clearing cache and config directories, and reinstallation on both windows 10 (client) and WSL2 Ubuntu (server), but the problem is persistent! I not only uninstalled the plugin, but even my full VSCode installation (and corresponding config caches). Nothing seems to help.

The only way for me that works, is to force install a previous version of the VSCode plugin (which fortunately is easy in VSCode). This leads me to believe there is either a bug in the latest version, or some undocumented cache location that needs to be cleared.

**Comment by dpdannemiller** [comment]
Update:

I uninstalled julia extension 1.0.10, and installed language-julia-insider-1.0.9.vsix, restarted VS Code. Problem disappeared.

I updated to 1.0.10, restarted VS Code. Problem is back.

There seems to be a problem with 1.0.10.

**Comment by cmichelenstrofer** [comment]
Same problem with insider-1.0.10

**Comment by ericgreveson** [comment]
Another "me too" comment: using Julia 1.5.3, Visual Studio Code 1.51.1, julia-vscode 1.0.10 on Windows 10. The suggestion above to install language-julia-insider-1.0.9.vsix solved it for me too.

**Comment by tbenst** [comment]
Same issue on Julia 1.5.3, VSCode 1.51.1, julia-vscode 1.0.10 on Ubuntu 18.04. Downgrading to `julia-vscode 1.0.8 resolves the issue. click gear next to julia extension to downgrade.

cc https://github.com/julia-vscode/julia-vscode/issues/1800

**Comment by FedericoV** [comment]
Same here here on windows.  Julia 1.5.3, Visual Studio Code Insiders.

**Comment by chelseas** [comment]
Hallelujah! Thank you @tbenst ! Downgrading to julia-vscode 1.0.8 solves the problem.  (I'm on macOS so it might be a different version of the code but your solution worked for me too)

**Comment by origamist** [comment]
Downgrading to 1.0.8 worked for me too. Happy to run bisect if a maintainer is interested in fixing this.

**Comment by bhatiaabhinav** [comment]
Same here. Julia 1.5.3, VS Code, Windows 10. Downgrading to 1.0.8 works.

**Comment by fedenolasco** [comment]
Could this relate to similar issue under Atom https://github.com/JunoLab/Juno.jl/issues/178#issuecomment-660625757?
I basically have Ubuntu 20.04 and VScode and Julia through snaps and as I followed the suggestion above Julia code compiles under Vscode extension 1.0.10 and Julia Server Starts. I use path /snap/julia/current/bin/julia under Executable Path for this extension.

`"julia.executablePath": "/snap/julia/current/bin/julia"`

**Comment by tpoisot** [comment]
Just to add a datapoint: Ubuntu 20.10, VS Code through snaps, Julia 1.5.3, the latest version of the extension gives the bug described here, but reverting to 1.0.8 makes it work as expected.

**Comment by Sixzero** [comment]
For me 1.0.10 gets stuck, so I built 1.0.11 and it is also stuck. 
Hope we find a fix. 
Here ubuntu20.04.
Also reading over the posts I also downgraded to 1.0.8 and now I see caches building and indexing progresses, previously I think it also didn't start.

**Comment by gguyver** [comment]
Just to add another datapoint, MacOS 10.14.6 with VSCode 1.52.1, also stuck on initializing the language server for 1.0.10, Downgrading to 1.0.8 also fixed the issue for me.

**Comment by GDX64** [comment]
I'm also with this problem using the newer versions. The version 1.0.9 is working though.

**Comment by RaulDurand** [comment]
> Downgrading to `julia-vscode 1.0.8 resolves the issue

How do you downgrade?

**Comment by davidanthoff** [comment]
I believe this should be fixed on `master`, and we'll hopefully ship this in a few days.

**Comment by krynju** [comment]
fixed on 1.1.25 on linux

**Comment by davidanthoff** [comment]
I'm closing this for now, let us know if this is still a problem in recent versions.

**Comment by haberdashPI** [comment]
I seem to be having the same issue with version 1.1.38. There is no output for "Julia Language Server trace". I will try the workaround proposed above: if it doesn't work, I'll report back here.

**Comment by pfitzseb** [comment]
FWIW, we did get a bunch of reports of the LS failing to precompile (and deleting the extension-specific precompile cache helped), but you should see something in the LS trace then.

**Comment by haberdashPI** [comment]
Oh, I see what's happening, nothing to do with the above issue, some problematic interaction between using [`asdf`](https://github.com/asdf-vm/asdf) and the assumptions julia-vscode is making about the files present where the julia binary is.

**Comment by logankilpatrick** [comment]
I am still having this issue with VS Code version Version: 1.59.1.

**Comment by HumpyBlumpy** [comment]
Also having issues with VS Code 1.59.1. Downgrading to the Julia extension does not help

**Comment by Nimava** [comment]
Same problem with VS Code 1.64.2 and Julia 1.7.1

**Comment by eacabbi** [comment]
Unable to start it, I tried everything. Running Julia 1.7.3, VS Code 1.70.2, Julia extension 1.6.31. I tried everything, clean install, nothing seems to work.

**Comment by vacuously-false** [comment]
> Same problem with VS Code 1.64.2 and Julia 1.7.1

Same problem with VS Code 1.94.2 and Julia 1.11.1
