### ISSUE TITLE
PyPlot does not show plot window after updating to julia-vscode v1.0.10 (Windows)

### ISSUE THREAD

**Issue by zhopan77** [julia-vscode/julia-vscode#1782]
On julia-vscode v1.0.8 and earlier, as long as I uncheck "Use Plot Pane" in configuration, julia-vscode works well with PyPlot. The plot window will show up as an independent window, just like when running Julia from a command line window.

After upgrading to julia-vscode v1.0.10, PyPlot cannot show its window anymore, and there is no error or warning message (everything else works as before). Downgrading to julia-vscode v1.0.08 and PyPlot works again.

This is on Julia v1.5.3, Windows 10 64-bit. Repeatable on 2 separate PCs. 

Not sure if it's relevant or not, but on all my PCs I have added MKL.jl so Julia is running MKL instead of OpenBLAS. I did make sure the Python version PyCall uses has standard numpy and matplotlib (i.e. not linked with MKL) so matplotlib does not crash due to MKL conflict.

**Comment by grayed** [comment]
A bit of more information: the matplotlib tells it uses the `agg` backend. When telling it to use `Qt5Agg` backend instead, the whole thing crashes.

**Comment by zhopan77** [comment]
Just tried Julia Insider 1.0.11 on VSCode. This issue is still there.
