### ISSUE TITLE
Format Document indentation and Format Selection missing

### ISSUE THREAD

**Issue by albheim** [julia-vscode/julia-vscode#1784]
Is there a reason why Format Document does not fix indentation? There is Reindent Lines which seems to work, but to me this seems like something that should be included in a formatting step?

Format Selection (see https://code.visualstudio.com/docs/editor/codebasics#_formatting) seems to not be supported.

**Comment by davidanthoff** [comment]
I think in theory it should fix indentation, but medium term we're going to swap in JuliaFormatter.jl I'm going to close this issue because once we do that it should hopefully all work better.

**Comment by ericphanson** [comment]
Can this be reopened? Format selection does not seem to work with the new JuliaFormatter integration

**Comment by pfitzseb** [comment]
Works fine for me.

**Comment by ericphanson** [comment]
Interesting, it works for me if I select a small part of a large file, but it doesn't work if I select say 70% of a large file. For an open source example, if I add `style = "yas"` in a `.JuliaFormatter.toml` file to Convex.jl, then select this part: https://github.com/jump-dev/Convex.jl/blob/e8304a5279e90d9f1f0c1ac743e29a22c7f7a182/src/solution.jl#L62-L360, what happens is the first two `add_terms!` methods are formatted too. However, if I select just one `add_terms!` method and do format selection, then just that method gets formatted.

**Comment by pfitzseb** [comment]
Hm, interesting. That *also* works fine for me...

**Comment by pfitzseb** [comment]
https://github.com/julia-vscode/julia-vscode/issues/2623
