### ISSUE TITLE
Update JuliaInterpreter to v0.8.4

### ISSUE THREAD

**Issue by simonbyrne** [julia-vscode/julia-vscode#1793]
It includes an important fix: https://github.com/JuliaDebug/JuliaInterpreter.jl/pull/442

**Comment by pfitzseb** [comment]
This is blocked on https://github.com/julia-vscode/DebugAdapter.jl/pull/24. I'll try to fix that this week.

**Comment by valeriabarra** [comment]
Thanks @pfitzseb, I have seen that  [julia-vscode/DebugAdapter.jl#24](https://github.com/julia-vscode/DebugAdapter.jl/pull/24) has been merged. Does that close this issue?

**Comment by pfitzseb** [comment]
Not quite. DebugAdapter now works with JuliaInterpreter 0.8.5, but we still need to update the vendored dependency in this repo here and tag a release.

**Comment by valeriabarra** [comment]
Thanks! Do you have any rough idea of the timeline for a new release? Just to have an idea

**Comment by pfitzseb** [comment]
I'd like to get an insiders release out tomorrow and the stable release maybe a day or two later, if we don't find any big issues.

**Comment by valeriabarra** [comment]
Thanks! That helps!

**Comment by valeriabarra** [comment]
@pfitzseb , I was wondering if there was a release (and I missed that) or if you have an updated timeline for that. Thank you

**Comment by pfitzseb** [comment]
Sorry this took so long, but the new insiders release is out at last.
