### ISSUE TITLE
Add exception inspector/view for debugger

### ISSUE THREAD

**Issue by jolars** [julia-vscode/julia-vscode#1796]
There doesn't seem to be an exception view for the debugger. The [documentation](https://www.julia-vscode.org/docs/dev/userguide/debugging/) seems to suggest that there is one, but the (supposed) screenshot in the documentation is missing.

As far as I can tell there doesn't appear to be any other way to see what exception is thrown when the debugger hits one. The debugger just breaks on the line of the exception but doesn't return the error message.

**Comment by pfitzseb** [comment]
Yeah... I've already spent a bunch of time trying to figure out what's going on with that, but it's starting to look like a VSCode issue.

**Comment by davidanthoff** [comment]
This definitely used to work at some point, but I also have vague memories that it was really quite brittle, i.e. if there was something slightly off in the way that message was sent to VS Code, it didn't display. Unfortunately I don't remember the details...

**Comment by pfitzseb** [comment]
This will be fixed once a VSCode version with https://github.com/microsoft/vscode/issues/113921 is released (you can already use the latest insiders build).
