### ISSUE TITLE
Starting language server forever ver:1.0.10

### ISSUE THREAD

**Issue by dillir07** [julia-vscode/julia-vscode#1800]
I installed vscode extension version 1.0.10 and the language server loads forever.
But if I downgraded to version 1.0.8, it is working fine.

info:
Julia version: 1.5.3 (2020-11-09), Installed via Manjaro repository
In extension's JSON config file, I have "julia.executablePath": "julia"

I tried manually downloading the tarball and extracting to different folder and updated the path, but the issue is same.
version 1.0.8 loads properly, but version 1.0.10 says 'Starting language server' and it never completes.

**Comment by gnangnan15** [comment]
Hello @dillir07,
I had the same issue today when upgrading from 1.0.8 to 1.0.10. I needed to change the _Environment Path_ in the settings of the extension (julia.environmentPath in the file settings.json). The default one that was pointing to an "empty" environment (which seemed to be ok with 1.0.8). When changing to the default for Julia 1.5 the server started again.

**Comment by krynju** [comment]
Hit the same issue on Win10, Julia1.5.3 and 1.0.10 version of the extension.
Downgrade to 1.0.8 fixed the issue.

However, the workaround proposed by @gnangnan15 didn't work for me. I had the same issue after populating the environment with the path to the default one.

**Comment by krynju** [comment]
fixed in 1.1.25 on linux
