### ISSUE TITLE
/bin/bash: [command]: command not found

### ISSUE THREAD

**Issue by MLackner** [julia-vscode/julia-vscode#1803]
If I use `PyPlot` from the integrated **REPL** in VSCode I get an error saying
```
"No such file or directory: 'kpsewhich'"
```
If I try to run this command from the integrated VSCode **terminal** it does find the command.
If I try to run
```julia
julia> ;
shell> kpsewhich
```
in the integrated **REPL** I get
```
/bin/bash: kpsewhich: command not found
```
Providing the full path to `kspewhich` does work but I can't figure out a workaround. Is there a way to manually point to the executable?

**Comment by pfitzseb** [comment]
Did you set that as an alias in `.bashrc`? If so, try starting VSCode from within bash instead.

**Comment by MLackner** [comment]
I had not set that as an alias. However, doing so and starting from within bash gives the same error.

**Comment by MLackner** [comment]
I am still having this issue and it seems to be related to VS Code rather than the Julia plugin. Several other plugins also have problems finding executables that should be available.

**Comment by davidanthoff** [comment]
It seems there really isn't anything we could do about this, so I'm going to close this issue.
