### ISSUE TITLE
Execute Code: output in REPL is not suppressed with semicolon

### ISSUE THREAD

**Issue by ChrHorn** [julia-vscode/julia-vscode#1813]
Semicolons at the end should suppress the output. Currently they have no effect when using Alt + Enter to execute code in the REPL.

Extension Version: 1.0.10
Julia 1.5.3

**Comment by charlesbrodhead3** [comment]
This is especially useful for suppressing multi-stage plot display popups (e.g. when adding multiple series lines via loops) until the plot is fully rendered.

**Comment by guyvdbroeck** [comment]
This bug makes ALT-ENTER kind of useless for me, I cannot afford to print all that output.

**Comment by pfitzseb** [comment]
Will be fixed by https://github.com/julia-vscode/julia-vscode/pull/2098. I'd also recommend using inline results instead of printing to the REPL, as is the default.
