### ISSUE TITLE
Code in docstring not formatted

### ISSUE THREAD

**Issue by fonsp** [julia-vscode/julia-vscode#1816]
![image](https://user-images.githubusercontent.com/6933510/101948382-37d89f80-3bf2-11eb-8b09-c8263ac13df4.png)

extension version 1.0.10

**Comment by pfitzseb** [comment]
Works fine with a multi-line docstrings:
![image](https://user-images.githubusercontent.com/6735977/102074444-18659080-3e05-11eb-8af1-019446c2815b.png)

**Comment by ZacLN** [comment]
https://github.com/julia-vscode/LanguageServer.jl/pull/856/commits/725dfe3cc0eba31437a002711a91f80146458a81
