### ISSUE TITLE
When pasting certain strings into VS Code Julia REPL, random characters appended

### ISSUE THREAD

**Issue by BioTurboNick** [julia-vscode/julia-vscode#1824]
I'm not sure how to track this one down. Recently when I paste into the Julia REPL (only the one running inside VS Code), it appends text to certain strings. The REPL session has been live for quite some time, after running a 2-day analysis. Possible something corrupted?

Pasting the same thing in the Windows Julia REPL doesn't do it, nor does pasting it into a browser. Also doesn't impact a PowerShell session running in VSCode.

Weirdly, it is sensitive to length.

"combinednormalizedmontecarlomeasurem" => correct
"combinednormalizedmontecarlomeasureme" => correct
"combinednormalizedmontecarlomeasuremen" => correct
"combinednormalizedmontecarlomeasurement" => "combinednormalizedmontecarlomeasurement~"
"combinednormalizedmontecarlomeasurements" => "combinednormalizedmontecarlomeasurements1~"
"combinednormalizedmontecarlomeasurementsc" => "combinednormalizedmontecarlomeasurementsc01~"
"combinednormalizedmontecarlomeasurementsco" => "combinednormalizedmontecarlomeasurementsco~"
"combinednormalizedmontecarlomeasurementscom" => "combinednormalizedmontecarlomeasurementscom~"
"combinednormalizedmontecarlomeasurementscomb" => correct
"combinednormalizedmontecarlomeasurementscombi" => correct
"combinednormalizedmontecarlomeasurementscombin" => correct

Any information I can collect while the session is still live?

**Comment by pfitzseb** [comment]
Weird. I don't really have an idea on how to debug this, unfortunately.

**Comment by BioTurboNick** [comment]
I'll probe a bit more

If I start a new PowerShell terminal in VSCode and execute Julia 1.5.3, the behavior remains (so presumably wouldn't be affected by the other long-running REPL).

It does not occur if I open PowerShell in Windows Terminal and then execute the same copy of Julia. So it seems to be specific to VS Code, or at least this session of it.

It also occurs on a brand new install of both VS Code, the Julia extension, and Julia 1.5.3 on another computer.

**Comment by BioTurboNick** [comment]
It also occurs if I uninstall the Julia extension, so that suggests it's either the REPL itself or VSCode. In which case I'll close this and move the issue.
