### ISSUE TITLE
Autocomplete and latex symbols

### ISSUE THREAD

**Issue by valeriabarra** [julia-vscode/julia-vscode#1826]
Hello, 
 I am using the insider version v1.0.11 in this VSCode:
 
 ```
 Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:32:10.090Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-58-generic snap
 ```
 
and it seems like the autocompletion and rendering of LaTeX symbols with <tab> does not work anymore. It used to work just fine.
 
 (I disabled the Julia language interpreter extension `julialang.language-julia` when I started testing the `julialang.language-julia-insider` )

**Comment by pfitzseb** [comment]
This probably means the language server isn't starting up correctly. Do you have telemetry enabled? I'll see if we got any new error messages on the insiders channel.

**Comment by valeriabarra** [comment]
It does work for me now. I will close the issue. Thanks

**Comment by stanleesocca** [comment]
Hi Julia devs, 

I still have this issue in my machine even after removing and reinstalling vscode-julia. @valeriabarra can you please share how you made your work again.

**Comment by valeriabarra** [comment]
@stanleesocca I actually didn't do anything to solve the issue. It might have been solved by the fact that, in the meantime, JuliaInsider `v1.0.12` was released and my extension was auto-upgraded?
