### ISSUE TITLE
"Debug File in New Process" doesn't work in multi-root workspaces

### ISSUE THREAD

**Issue by erik-f** [julia-vscode/julia-vscode#1827]
I am using a multi-root workspace. When I click on "Debug File in New Process", I get the error message "Variable $(workspaceFolder) can not be resolved in a multi folder workspace. Scope this variable using ':' and a workspace folder name."

I suppose this error is caused by this code here in `debugFeature.ts`:
```ts
const folder = vscode.workspace.getWorkspaceFolder(resource)
if (folder === undefined) {
    vscode.window.showInformationMessage('File not found in workspace.')
    return
}
vscode.debug.startDebugging(folder, {
     type: 'julia',
     name: 'Debug Editor Contents',
     request: 'launch',
     program,

})
```

I'd suggest making this hard-coded launch configuration customizable in a `launch.json` file.

**Comment by pfitzseb** [comment]
Can you try the insiders release? That should work there.

**Comment by erik-f** [comment]
Yes, it works. Thanks!
