### ISSUE TITLE
Remote development leads to tiny plots

### ISSUE THREAD

**Issue by Byrth** [julia-vscode/julia-vscode#1829]
I use a combination of Docker and Remote - Containers to develop [in a container on a remote docker host](https://code.visualstudio.com/docs/remote/containers-advanced#_developing-inside-a-container-on-a-remote-docker-host).

The Julia extension is installed inside the container and works as expected. Plots from the REPL pop up in the Julia Plots tab.

However, maybe a month ago at this point, the plots started popping up at about 1/4 the expected size, as detailed in [this post](https://discourse.julialang.org/t/plots-are-tiny/52184). I can save PNGs to the remote container and load them just fine through VS Code (correct size), but the Julia Plots tab either misinterprets my screen resolution or is stuck at preview size.

VS Code Julia extension 1.0.10
VS Code 1.52.1
Julia 1.5.3

**Comment by pfitzseb** [comment]
This kinda sounds like https://github.com/JuliaPlots/Plots.jl/issues/3133. Could you try updating GR to the latest version?

**Comment by Byrth** [comment]
I confirmed that GR 0.53.0 fixed it.
