### ISSUE TITLE
Julia should respect global telemetry setting instead of using its own telemetry option. 

### ISSUE THREAD

**Issue by musm** [julia-vscode/julia-vscode#1830]
For example the Python extension simply respects the global telemetry setting instead of creating it's own option to set/unset telemetry collection.

**Comment by pfitzseb** [comment]
Not sure I agree with that. People might only want to trust Microsoft with their data but not us (or vice versa).

**Comment by davidanthoff** [comment]
Yeah, I agree, that won't work. The global setting controls whether you want to submit your telemetry to Microsoft, so that works for all the MS extensions, but we can't re-use that.
