### ISSUE TITLE
not recognizing `by` keyword in `sort`

### ISSUE THREAD

**Issue by chkwon** [julia-vscode/julia-vscode#1832]
The following code shows `Possible method call error`.
```julia
a = rand(10)
sort!(a, by= x->x^2)
```

<img width="392" alt="Screen Shot 2020-12-23 at 11 17 52 AM" src="https://user-images.githubusercontent.com/7596204/103016726-83ebe400-4510-11eb-8040-ec2943241caa.png">

**Comment by ZacLN** [comment]
https://github.com/julia-vscode/SymbolServer.jl/pull/195
