### ISSUE TITLE
how to turn on the Useable real-time feedback ?

### ISSUE THREAD

**Issue by bigdataman2015** [julia-vscode/julia-vscode#1833]
the utility of Useable real-time feedback is really good as in atom. but how to turn on the Useable real-time feedback ? thanks!

**Comment by pfitzseb** [comment]
Check out the Result Type setting and set it to `inline`:
![inline results](https://user-images.githubusercontent.com/6735977/103133717-4754ef80-46ac-11eb-97c6-86fa1e183e51.png)

**Comment by bigdataman2015** [comment]
I set it to `both`, Thanks!
