### ISSUE TITLE
When executing the code with Alt+Enter, detect changes in the above code and re-evaluate

### ISSUE THREAD

**Issue by leventov** [julia-vscode/julia-vscode#1834]
Example code:
```
x = 1
y = x + 1
```
I evaluate both lines with Alt+Enter. Result is y = 2. Then I edit the code to the following:
```
x = 2
y = x + 2
```
And hit Alt+Enter on the second line again. The result is 3 rather than 4, which is very confusing.

**Comment by ZacLN** [comment]
This is expected behaviour - Alt + Enter evaluates the current block (which in this case is the second line). I think the `Julia: Execute File` command may be what you intend to use? 

Closing

**Comment by pfitzseb** [comment]
Also take a look at Pluto for a fully reactive experience. We don't have any plans to recreate that in VSCode (although I've played around with integrating Pluto into VSCodes notebook interface for a couple of hours).
