### ISSUE TITLE
[FR] Lint error for illegal `const` usage

### ISSUE THREAD

**Issue by fonsp** [julia-vscode/julia-vscode#1835]
The linter could warn me about these errors:

<img width="703" alt="image" src="https://user-images.githubusercontent.com/6933510/103169663-1dcbcd80-483e-11eb-8c68-8f325bfdb918.png">

Result:

<img width="703" alt="image" src="https://user-images.githubusercontent.com/6933510/103169660-15739280-483e-11eb-9cbf-bdf40e6e9ac8.png">

**Comment by ZacLN** [comment]
Addressed here: https://github.com/julia-vscode/StaticLint.jl/commits/cst-compat, which will make it's way onto master in due course.
