### ISSUE TITLE
abnormal warning: "Invalid redefinition of constant"

### ISSUE THREAD

**Issue by AIxer** [julia-vscode/julia-vscode#1836]
### If you define a `structure` or `abstract type` that is not at the end of the file, then you will get this warning. The code is correct, but the blue wavy line is redundant. 

![image](https://user-images.githubusercontent.com/19511727/103172790-ee927c00-4890-11eb-8533-85d6287534dd.png)

**Comment by aviatesk** [comment]
I guess you're actually defining them in another file or somewhere ?

**Comment by pfitzseb** [comment]
Yeah, the snippet you have there isn't enough to repro the issue.

**Comment by AIxer** [comment]
I'll try this again in a new project.

**Comment by AIxer** [comment]
> I guess you're actually defining them in another file or somewhere ?

No, `MyConstant` and `MyType` are just defined for this issue

**Comment by AIxer** [comment]
## How to explain this?
![image](https://user-images.githubusercontent.com/19511727/103173113-9c068f00-4893-11eb-8a2f-df249de076f0.png)

![image](https://user-images.githubusercontent.com/19511727/103173138-cfe1b480-4893-11eb-96a1-0318a1d7065a.png)

**Comment by pfitzseb** [comment]
The linter not working properly without a trailing new line is a bug, but I still can't repro the "Invalid redefenition of constant" warning.

**Comment by AIxer** [comment]
> The linter not working properly without a trailing new line is a bug, but I still can't repro the "Invalid redefenition of constant" warning.

my project isn't wrapped in a module, I think it's too much `include()` in my project  causes this warning.

**Comment by AIxer** [comment]
> The linter not working properly without a trailing new line is a bug, but I still can't repro the "Invalid redefenition of constant" warning.

yes, may be it should be closed, I can't repo this warning in some lines either.
