### ISSUE TITLE
In debug mode the exception don't show up

### ISSUE THREAD

**Issue by honoreeronoh** [julia-vscode/julia-vscode#1838]
for example, if i run hello.jl which has a problem
![Snipaste_2020-12-29_11-10-36](https://user-images.githubusercontent.com/50764350/103255996-83e35c80-49c6-11eb-85df-dfd1ec2e5453.png)

In the debug mode,the programme stop but i can't see the ERROR 

![Snipaste_2020-12-29_11-11-22](https://user-images.githubusercontent.com/50764350/103256024-9cec0d80-49c6-11eb-92e7-c3e9407fe69a.png)

is there some setting that i should check?

**Comment by honoreeronoh** [comment]
![Snipaste_2020-12-29_11-10-36](https://user-images.githubusercontent.com/50764350/103257124-e63e5c00-49ca-11eb-8e47-7f6cc3cfc955.png)
![Snipaste_2020-12-29_11-11-22](https://user-images.githubusercontent.com/50764350/103257127-e76f8900-49ca-11eb-815d-3fc145e6c783.png)

**Comment by pfitzseb** [comment]
This will be fixed once a VSCode version with https://github.com/microsoft/vscode/issues/113921 is released (you can already use the latest insiders build).

**Comment by pfitzseb** [comment]
Also, closing this in favour of https://github.com/julia-vscode/julia-vscode/issues/1796.
