### ISSUE TITLE
No plots shown with VegaLite.jl

### ISSUE THREAD

**Issue by weidenka** [julia-vscode/julia-vscode#1840]
I was trying to run this simple example from the [VegaLite docs](https://www.queryverse.org/VegaLite.jl/stable/):

```Julia
using VegaLite, VegaDatasets
dataset("cars") |>
@vlplot(
    :point,
    x=:Horsepower,
    y=:Miles_per_Gallon,
    color=:Origin,
    width=400,
    height=400,
    tooltip=:Origin
)
```
To my understanding I should see a plot in a separate pane. That pane opens but is empty. In the screenshot I also show which Vega-related plugins are installed (disabling them did not help). Running the exact same code in the Julia REPL outside of VSCode shows the plot in a browser. Any idea?
(Julia v1.5, VSCode plugin Julia Language Support 1.0.10)

<img width="1292" alt="Screenshot 2021-01-02 at 22 40 44" src="https://user-images.githubusercontent.com/2812521/103467083-8f7aae80-4d4b-11eb-8c10-4cc7c3949390.png">

**Comment by davidanthoff** [comment]
Hm, I can't replicate this on my machine, the plot shows just fine when I run that code...

Are you sure that you assigned the correct plot to `p`, sometimes it shows empty plots when there is some error in the spec.

**Comment by noahrhodes** [comment]
I tried to plot some things today, and suddenly plots aren't showing up in VScode for either VegaLite or Plots.  (the `Use Plot Plane` setting is checked), but they show up externally (in browser/GKS window respectively).

Not exactly new info to debug it, but it seems to be more general than just VegaLite.

**Comment by davidanthoff** [comment]
Hm, maybe you are loading some package that is messing with the display stack...

**Comment by pfitzseb** [comment]
That shouldn't be possible anymore -- we're always pushing our `InlineDisplay` to the top of the display stack before each evaluation now. FWIW, I can't repro this either.

**Comment by noahrhodes** [comment]
In a clean environment, I had no issues. Not sure what the problem was because I can't replicate it again in the environment I was working in either.

**Comment by weidenka** [comment]
Thanks for testing. Any suggestion how to debug this? Otherwise feel free to close this issue.
