### ISSUE TITLE
Option for progress bar logging

### ISSUE THREAD

**Issue by mileslucas** [julia-vscode/julia-vscode#1845]
Recently progress bars produced by ProgressLogging.jl have stopped using the TerminalLogger I have set in my `startup.jl` and have been eagerly grabbed by vscode. I currently do not prefer the vscode progress bar styling (too out of the way, have to click to see the bar, no timing info or extra log messages).

It would be nice to add an option to disable this behavior- currently there is *no way* for me to set up a logger that works for me since vscode seems to intercept it no matter what.

**Comment by pfitzseb** [comment]
You can  wrap your long running statement in a `withlogger(TerminalLogger) do ...` call; that should be early enough for us to not be able to grab the log messages.

**Comment by alexriss** [comment]
just a note in case anyone stumbles upon this, it should be: `with_logger(TerminalLogger()) do ...` and it uses the packages `Logging` and `TerminalLoggers`.

**Comment by pfitzseb** [comment]
We do also have a setting to disable progress bars in VSCode, FWIW.
