### ISSUE TITLE
plot in panel too big

### ISSUE THREAD

**Issue by bigdataman2015** [julia-vscode/julia-vscode#1847]
![QQ图片20210107131111](https://user-images.githubusercontent.com/13653216/103853828-ee447d00-50e9-11eb-8ce7-722cd4f26879.png)

plot in panel too big, how to tune it.

**Comment by tpoisot** [comment]
You can use the `size` argument if using *Plots.jl*.

**Comment by davidanthoff** [comment]
This is way too little info to do anything :) What plot package, what plot command, how can we reproduce this?

**Comment by bigdataman2015** [comment]
the problem may be due to the separate external display, which is much larger than the laptop one ? it shows normal when only use the laptop display.

**Comment by pfitzseb** [comment]
Probably fixed. Please open a new issue if not.
