### ISSUE TITLE
Inspector support in vscode

### ISSUE THREAD

**Issue by jlperla** [julia-vscode/julia-vscode#1851]
From https://github.com/microsoft/vscode-jupyter/issues/1536

This is the setting we need to update (although the name of the extension has chagned):
```json
                "python.dataScience.variableQueries": {
                    "type": "array",
                    "description": "Language to query mapping for returning the list of active variables in a Jupyter kernel. Used by the Variable Explorer in both the Interactive Window and Notebooks. Example: \n'[\n{\n   \"language\": \"python\",\n   \"query\": \"%who_ls\",\n  \"parseExpr\": \"'(\\\\w+)'\"\n}\n]'",
                    "scope": "machine",
                    "examples": [
                        [
                            {
                                "language": "python",
                                "query": "_rwho_ls = %who_ls\\nprint(_rwho_ls)",
                                "parseExpr": "'(\\w+)'"
                            },
                            {
                                "language": "julia",
                                "query": "whos",
                                "parseExpr": "'(\\w+)'"
                            }
                        ]
                    ]
                },
```
- Basically, the old `whos` that previously was in Julia has been deprecated.  And the `varinfo()` gives a markdown table - which would be tough to parse.  Note that:
```julia
julia> Base.names(Main)
6-element Array{Symbol,1}:
 :Base
 :Core
 :InteractiveUtils
 :Main
 :ans
 :my_variable
```
So if so then would that potentially for the query?  As for the `parseExpr` is that executed in TypeScript?  What would be the regex to get the names and strip away the `:` from it being a symbol?

**Comment by davidanthoff** [comment]
Yes, to me it also looks like it might be enough to just replace the value for `query` and `parseExpr`. I never manage to handle regex well, so my strategy would probably be to change the query to return exactly the format that the Python version returns, then we don't have to change the regex :) I think
```julia
"[" * join(map(i->"'$i'", String.(Base.names(Main))), ", ") * "]" |> println
```
as the query string would do it. I think that change would have to be made in the Jupyter extension, right?

This whole solution, though, seems really, really brittle compared to how we implemented our workspace stuff in the Julia extension :)

**Comment by jlperla** [comment]
For sure.  I am just not sure how they can avoid some of this given the need to support different kernels.  But I suppose an intermediate JSON format would do it.

If you guys know how to call the https://github.com/JuliaLang/IJulia.jl/blob/9b10fa9b879574bbf720f5285029e07758e50a5e/src/handlers.jl#L229-L248  call to see how it might look, it might help them.

**Comment by pfitzseb** [comment]
Not happening. Upstream is talking about a proper unified variable viewer that all extensions (and notebooks) can use. For now our own variable viewer supports VS Code native Julia notebooks.
