### ISSUE TITLE
Add "Go to Definition" in `using PackageName` clause.

### ISSUE THREAD

**Issue by heetbeet** [julia-vscode/julia-vscode#1853]
Allow the usual "Go to Definition" in VSCode to work with `using PackageName` in order to go to where `PackageName` is defined.

Current workarounds include typing `pathof(PackageName)` in REPL and then clicking on that, or typing `PackageName.eval` and clicking on that.

**Comment by ZacLN** [comment]
https://github.com/julia-vscode/LanguageServer.jl/pull/856/commits/64b2c750b82866f63093f2ac7a85a9820dd1e074
This should work it's way into julia-vscode-insiders quite quickly
