### ISSUE TITLE
Double click `push!` selects `push`

### ISSUE THREAD

**Issue by fonsp** [julia-vscode/julia-vscode#1860]
It would be _Julian_ if double clicking function names like `asdf!` would select the whole name, and not just `asdf`, but perhaps this is not something that the extension can control.

**Comment by pfitzseb** [comment]
The easiest way to do that is to put
```
    "[julia]": {
        "editor.wordSeparators": "`~#$%^&*()-=+[{]}\\|;:'\",.<>/?"
    }
```
into your settings.json. #1861 will provide a better default experience.

**Comment by fonsp** [comment]
That was fast, thank youu!
