### ISSUE TITLE
Formatter: Named tuple comment gets deleted

### ISSUE THREAD

**Issue by fonsp** [julia-vscode/julia-vscode#1862]
Before formatting:

![Schermafbeelding 2021-01-15 om 23 01 41](https://user-images.githubusercontent.com/6933510/104783170-c1493780-5785-11eb-9456-5965a38ccae2.png)

After formatting:

![Schermafbeelding 2021-01-15 om 23 01 49](https://user-images.githubusercontent.com/6933510/104783192-c73f1880-5785-11eb-9ebb-62cf5ad30f1f.png)

---

Code:

```julia
(
    # i will get deleted
    a = 1,
    # i wont
    b = 2,
)
```

**Comment by pfitzseb** [comment]
Not sure if we should spend time fixing this considering we plan to switch to JuliaFormatter anyhow.

**Comment by davidanthoff** [comment]
I do think we should fix bugs like this that actually remove user data, that is actually pretty bad :) And who knows how long the integration of the new stuff will take.
