### ISSUE TITLE
pluto support

### ISSUE THREAD

**Issue by Xinyu-Wu-0000** [julia-vscode/julia-vscode#1864]
Hoping to run pluto in vscode with highlight and autocomplete.

**Comment by davidanthoff** [comment]
Our general strategy for that is that we would love to see Pluto support on VS Code, but ideally in a separate extension that interacts with our core extension, similar to the design that we're heading for with the Jupyter extension, where support for Jupyter notebooks is in its own extension, but the Julia extension features then light up in those notebooks.

I believe @pfitzseb has started playing with that already.

**Comment by pfitzseb** [comment]
See https://github.com/JuliaComputing/pluto-vscode for a superficial implementation. A proper notebook UI integration is probably out of scope of this extension.
