### ISSUE TITLE
How to disable "Keyword argument not assigned "

### ISSUE THREAD

**Issue by ShuhuaGao** [julia-vscode/julia-vscode#1871]
Is there an option to remove the following warning?
![Snipaste_2021-01-22_12-44-37](https://user-images.githubusercontent.com/20141984/105447688-a60f8800-5caf-11eb-94cb-a39763f63441.png)

It is totally legal to not assign a keyword argument, and there are many examples in the base library of Julia, e.g., `sort`.

**Comment by pfitzseb** [comment]
This warning has been removed.
