### ISSUE TITLE
Add `Julia: Delete All Plots` to main command list

### ISSUE THREAD

**Issue by dpsanders** [julia-vscode/julia-vscode#1877]
Doing `Shift-Command-P` and searching for `julia plot` does not show the `Julia: Delete All Plots` command.

**Comment by Janssena** [comment]
Is this supposed to be intentional? The plotpane commands (except for show) are all hidden from the command palette. I could make a PR enabling Delete All Plots, since using it from the command palette does seem to work fine for me locally.

**Comment by pfitzseb** [comment]
Fixed.
