### ISSUE TITLE
CSTParser do not respect files.exclude setting

### ISSUE THREAD

**Issue by innerlee** [julia-vscode/julia-vscode#189]
In a project, the setting `files.exclude` is ignored by the `CSTParser`. Then a lot of stuff would fill the PROBLEMS tab.

**Comment by davidanthoff** [comment]
Good point, we'll have to investigate that.

**Comment by sbromberger** [comment]
x-ref https://github.com/JuliaEditorSupport/LanguageServer.jl/issues/173
