### ISSUE TITLE
Benchmark task MethodError

### ISSUE THREAD

**Issue by Oliver-Leete** [julia-vscode/julia-vscode#1895]
When trying to run the benchmark task I get the following error:
`ERROR: MethodError: no method matching benchmarkpkg(::String, ::BenchmarkConfig; promptsave=false, promptoverwrite=false)`

It looks like the `promptsave` and `promptoverwrite` keywords were replaced with `overwrite` in JuliaCI/PkgBenchmark.jl#40 and then removed completely for v0.1.0  in JuliaCI/PkgBenchmark.jl#57.  

From [their documentation](https://juliaci.github.io/PkgBenchmark.jl/stable/run_benchmarks/) It looks like it now takes the keyword argument `resultfile` instead:

```
resultfile - If set, saves the output to resultfile
```

I think removing the `promptsave` and `promptoverwrite` arguments in 67 of src/tasks.ts
https://github.com/julia-vscode/julia-vscode/blob/2d38dd17ea4e711cfd2898cabfaab48d350ca373/src/tasks.ts#L67
by changing it to this should fix the error. 
```julia
let benchmarkTask = new vscode.Task({ type: 'julia', command: 'benchmark' }, folder, `Run benchmark`, 'julia', new vscode.ProcessExecution(jlexepath, ['--color=yes', '-e', 'using PkgBenchmark; benchmarkpkg(Base.ARGS[1], resultfile=" ")', package_name]), "");
```
I've left the `resultfile` string empty as I don't know what the previous naming convention was, but once that is filled out it should have the same behavior as before.

**Comment by davidanthoff** [comment]
Cool, thanks for digging into this! Do you think you might be able to open a PR with a fix?
