### ISSUE TITLE
conda command tries to run inside julia REPL when both python and julia extensions are installed

### ISSUE THREAD

**Issue by yha** [julia-vscode/julia-vscode#1901]
Not sure if this is a bug here or in the python extension (https://github.com/Microsoft/vscode-python). 
When both are installed, running the first julia command results in the following output in the Julia REPL:
```
julia> conda activate base
ERROR: syntax: extra token "activate" after end of expression
Stacktrace:
 [1] top-level scope at REPL[1]:1
```

**Comment by pfitzseb** [comment]
See https://code.visualstudio.com/docs/python/environments#_select-and-activate-an-environment -- imho that's an issue with the python extension trying to activate the conda env in all terminals, even extension contributed ones.

> Tip: To prevent automatic activation of a selected environment, add "python.terminal.activateEnvironment": false to your settings.json file (it can be placed anywhere as a sibling to the existing settings).

**Comment by davidanthoff** [comment]
Wait, they are just randomly sending strings to terminal windows?!? Gee, I have to say, they are doing some really weird stuff in the Python extension...

**Comment by Rapsodia86** [comment]
Do you have  "python.terminal.activateEnvironment": false in settings.json?
