### ISSUE TITLE
Argument incorrectly labelled as unused when broadcasting inside a for loop

### ISSUE THREAD

**Issue by mmiller-max** [julia-vscode/julia-vscode#1909]
In the top example below, `a` is greyed out.
![image](https://user-images.githubusercontent.com/59854849/106692895-78203100-6629-11eb-8f76-031c23f668eb.png)

This also seems to "block" other uses of `a`  that are detected when by themselves:
![image](https://user-images.githubusercontent.com/59854849/106693012-b61d5500-6629-11eb-80d9-7cfe767700a1.png)

**Comment by ZacLN** [comment]
Which version of the extension are you using? I can't replicate this behaviour on the `insiders` release suggesting this may already be fixed

**Comment by mmiller-max** [comment]
I'm using v1.0.10.

With the `insiders` release I can't replicate it either, but I don't even get the unused variable message when it is unused

<img width="325" alt="image" src="https://user-images.githubusercontent.com/59854849/107187250-d1c59880-6a39-11eb-9da5-819574971f68.png">

And now after switching back to the normal release I also don't get unused variable messages.. is something being cached somewhere?

**Comment by ZacLN** [comment]
We have a special case where a function returns a constant to allow simple functions like `isanumber(f::Number) = true`

**Comment by pfitzseb** [comment]
Although maybe we should require people to write `isanumber(::Number) = true` instead?

**Comment by ZacLN** [comment]
I didn't know that's what that was shorthand for, sounds like a good idea

**Comment by mmiller-max** [comment]
OK I realised I wasn't waiting for the Language Server to finish indexing packages when I thought that the `insider` (and then the normal release after switching back to it) was not showing any unused variable messages, my bad.

I can confirm that this issue is fixed on the `insider` version, thanks!
