### ISSUE TITLE
String parentheses parser bug

### ISSUE THREAD

**Issue by akosuas** [julia-vscode/julia-vscode#1913]
`"$(findfirst(==(a), b))"` seems to get parsed incorrectly. The final `)` is colored red/"string color", when it should be colored black/"code colour".

**Comment by davidanthoff** [comment]
@pfitzseb assigning this to you as the only person on earth that I know who understands our grammar file ;)

**Comment by pfitzseb** [comment]
Should be fixed once VS Code picks up the new grammar.
