### ISSUE TITLE
How to switch of warning on expr=expr (equaton based language)

### ISSUE THREAD

**Issue by MartinOtter** [julia-vscode/julia-vscode#1916]
How to disable warnings of the following kind:

![grafik](https://user-images.githubusercontent.com/7248038/107143620-47484080-6936-11eb-8bab-08993d5175ec.png)

Note, equations (such as "T*der(x) + x = u") are defined in a quoted expression and then further processed. There are MANY of such equations in the future and it would then be important to not flag such correct statements in the editor.

**Comment by pfitzseb** [comment]
There's no warning there, is there? Only the "Expand function definition" thingy, which I guess should be disabled in quoted expressions.

**Comment by MartinOtter** [comment]
> There's no warning there, is there? Only the "Expand function definition" thingy, which I guess should be disabled in quoted expressions.

Yes, you are right. Just the "thingy" is displayed.
