### ISSUE TITLE
"Julia sysimage for this environment is out-of-date and not used for REPL."

### ISSUE THREAD

**Issue by itchingpixels** [julia-vscode/julia-vscode#1936]
Hi!
I'm trying to speed up the time it takes to get my environment up and running (with the Build task provided by the extension) and it looks like the second time I open the environment, it incorrectly detects the sysimage file as expired. I can reproduce this every time.
Is there anything I can do to prevent this from happening?
Thanks!

**Comment by itchingpixels** [comment]
I'm on Mac OS 11.1, with VSCode 1.53.2 and Extension v1.1.17

**Comment by f-ij** [comment]
I'm having the same problem. At first sys image using the Run Build Task option, would work, but now they seem iffy as well.

**Comment by f-ij** [comment]
Making a sysimage myself with the PackageCompiler pkg, VScode will immediately say that the image is out of date. Touching does indeed work for the sys image made using vscode, though. So thanks for that suggestion. It's still cumbersome to have keep doing this though.
