### ISSUE TITLE
Plots panel shows missing image

### ISSUE THREAD

**Issue by ancher1912** [julia-vscode/julia-vscode#1937]
Hi,

I haven't been using VSCode for Julia development in a few month. I decided to updated everything and run some old applications. However my plots show a missing image icon:

![image](https://user-images.githubusercontent.com/12416095/107863155-21e59600-6e52-11eb-980a-6c426c91f118.png)

Plotting is done with Gadfly. Using Plots does show the actual plots.

if I add a popdisplay(), my plots appear in my browser.

I'm running VSCode on my Mac running macOSX Big Sur 11.2.1. It might also be that something changed with the update to Big Sur.

Any clue what might cause this?

**Comment by stefanjwojcik** [comment]
I'm having the same issue. I'm on Pop!_OS 20.10. I tried installing a slightly older version of VSCode julia extension, restarting my machine, etc. In plain julia in terminal, Gadfly plots show up as expected in a browser, so it seems like VSCode is the issue.
