### ISSUE TITLE
Parsing error for (A)'

### ISSUE THREAD

**Issue by atbug** [julia-vscode/julia-vscode#1942]
julia-vscode reports parsing error for `(A)'` in, for example,
```julia
A = rand(5, 5) + im * rand(5, 5)
B = (A)'
```

`(A)'` is equivalent to `A'` and should not be an error.

**Comment by pfitzseb** [comment]
Dup of https://github.com/julia-vscode/julia-vscode/issues/1931 and fixed by https://github.com/julia-vscode/CSTParser.jl/pull/258, which will be in the next release.
