### ISSUE TITLE
Quitting VSCode does not stop Julia(LanguageServer)

### ISSUE THREAD

**Issue by coxackie** [julia-vscode/julia-vscode#1951]
Exactly what the title says. arch linux, code(oss) 1.53.1, julia extension 1.1.23. Here is memory after I have open and closed code 4 times:
![Screenshot from 2021-02-17 19-54-58](https://user-images.githubusercontent.com/22049642/108260514-51e6af00-715a-11eb-9fca-f5b7858dc552.png)
Given that every time it costs > 650MB ram, it is a concern...

**Comment by pfitzseb** [comment]
Can you check the PPIDs for those processes?

**Comment by coxackie** [comment]
@pfitzseb sorry for not including the legend - the IDs are in the 4th column - before the memory (5th)

**Comment by pfitzseb** [comment]
4th column is process ID, though, right? I'm interested in the parent's process ID (note the extra P in PPID) :)

**Comment by coxackie** [comment]
ok, so I run `top`, add ppid, sort by memory:
![Screenshot from 2021-02-18 09-32-19](https://user-images.githubusercontent.com/22049642/108336821-5e0b5480-71cc-11eb-93a4-001445a2a676.png)
the 1177 are leftover from previous instances, 19971 is the current one running. 1177 is `systemd`, 19971 is `electron`.

**Comment by pfitzseb** [comment]
Alright. Can you give me the command those processes were started with? `htop` shows those by default, not sure how to get `top` to do that.

**Comment by coxackie** [comment]
here:
![Screenshot from 2021-02-18 11-34-55](https://user-images.githubusercontent.com/22049642/108351398-615b0c00-71dd-11eb-91b9-2b0bfbbe6506.png)

**Comment by serenity4** [comment]
I had the same problem on Ubuntu 20.10, julia-vscode version 1.1.29, VS Code version 1.53.2. Ran out of RAM when 8 julia instances didn't get stopped after switching several times between projects.

**Comment by coxackie** [comment]
Why this is in the backlog and not being addressed is beyond me.

**Comment by davidanthoff** [comment]
> Why this is in the backlog and not being addressed is beyond me.

We are all volunteers, and so everything ends up on the backlog by default. That just means "hey, would be great if someone wants to tackle this". If someone does start to work on an issue, they move it away from the backlog to indicate that they are working on it.

**Comment by pfitzseb** [comment]
Closing this in favour of https://github.com/julia-vscode/julia-vscode/issues/1850.
