### ISSUE TITLE
Error creating CuArrays in the integrated REPL : EXCEPTION_ILLEGAL_INSTRUCTION

### ISSUE THREAD

**Issue by ozmaden** [julia-vscode/julia-vscode#1954]
I am experiencing a weird error in the versions 1.1.20 -- 1.1.25. This works fine up until version 1.1.17.

**To reproduce**:
```julia
using CUDA
N = 2500
arr = CUDA.zeros(N)
```
The array creation fails using all other commands as well be it `cu(...)` or `CuArray{Float32}(undef, N)`
The integrated REPL quickly flashes the following error message before crashing and reverting to terminal:
```
Unreachable reached at 000000002840ea76

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.

Exception: EXCEPTION_ILLEGAL_INSTRUCTION at 0x2840ea76 -- Wrapper at c:\Users\cozma\.vscode\extensions\julialang.language-julia-1.1.25\scripts\packages\VSCodeServer\src\eval.jl:6
in expression starting at none:1
Wrapper at c:\Users\cozma\.vscode\extensions\julialang.language-julia-1.1.25\scripts\packages\VSCodeServer\src\eval.jl:6
Wrapper at c:\Users\cozma\.vscode\extensions\julialang.language-julia-1.1.25\scripts\packages\VSCodeServer\src\eval.jl:6
wrap at c:\Users\cozma\.vscode\extensions\julialang.language-julia-1.1.25\scripts\packages\VSCodeServer\src\eval.jl:8
macro expansion at c:\Users\cozma\.vscode\extensions\julialang.language-julia-1.1.25\scripts\packages\VSCodeServer\src\eval.jl:40 [inlined]
#56 at .\task.jl:356
unknown function (ip: 0000000028345433)
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
start_task at /cygdrive/c/buildbot/worker/package_win64/build/src\task.c:705
Allocations: 34931476 (Pool: 34920843; Big: 10633); GC: 29
```
Error does not appeas in external terminals or in vscode integrated terminals calling julia executable via CLI.

I am using Windows 10, tested vscode verison 1.51.1 and 1.53.2.
CUDA.jl version 2.4.0

Would appreciate any help. In the meantime I rolled back to version 1.1.17.

**Comment by pfitzseb** [comment]
Basically the same as https://github.com/julia-vscode/julia-vscode/issues/1940. I'll try to repro this and figure out why this is happening.

In the meantime, can you try the following code in a non-VSCode REPL:
```
using CUDA
N = 2500
arr = CUDA.zeros(N)

struct Wrapper{T}
    content::T
end
wrap(x) = Wrapper(x)
c = Channel(0)
put!(c, arr)
```
I'd expect that to error in some way.

**Comment by ozmaden** [comment]
@pfitzseb Yeah I executed your script in the Julia windows app and it just freezes and becomes unresponsive

**Comment by pfitzseb** [comment]
Nah, that's expected (changed the code above so that doesn't happen).

**Comment by ozmaden** [comment]
> Nah, that's expected (changed the code above so that doesn't happen).

The changed code works and does not error in the same way. This is its result:

```julia 
Wrapper{CuArray{Float32,1}}(Float32[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
```
Am I misunderstanding you? The provided code snippet was to simulate the same error in a non-vscode terminal, right?
