### ISSUE TITLE
Notebook Editor not displaying DataFrames.jl output correctly

### ISSUE THREAD

**Issue by JontySinai** [julia-vscode/julia-vscode#1955]
Output previewer is displaying the raw mathjax for DataFrames.jl output instead of the rendered table in VS Code (not Insiders).

Steps to reproduce (matrix from [Julia Academy DataFrames course](https://github.com/JuliaAcademy/DataFrames))

<img width="566" alt="VS Code not displaying dataframes jl output" src="https://user-images.githubusercontent.com/10547901/108381079-5f09a980-71ff-11eb-84c5-5f41412977b9.png">

Meanwhile the output renders perfectly in Jupyter:

<img width="392" alt="but Jupyter displays output correctly" src="https://user-images.githubusercontent.com/10547901/108381345-9f692780-71ff-11eb-98f5-64feb4ef11ea.png">

**Comment by davidanthoff** [comment]
I believe our extension is not involved in this scenario at all, so I don't think there is anything we can do here, these are things that presumably need to be fixed in whatever package provides this notebook implementation.
