### ISSUE TITLE
Introspect on Julia side of extension

### ISSUE THREAD

**Issue by goretkin** [julia-vscode/julia-vscode#1961]
If this question is better to be asked on Discourse, please let me know.

In Julia for VSCode, there are two Julia environments corresponding to commands "Julia: Start REPL"  "Julia: Restart Language Server".

The "Julia side" of the extension runs in [this environment](https://github.com/julia-vscode/julia-vscode/tree/e96e9425dd8e9d120177d5e8635b5048c0d48b9b/scripts/environments/languageserver) with [this entrypoint](https://github.com/julia-vscode/julia-vscode/blob/e96e9425dd8e9d120177d5e8635b5048c0d48b9b/scripts/languageserver/main.jl).

Can I get a REPL where I can access the `LanguageServerInstance` and  something like, I don't know, access the currently focused [`Document`](https://github.com/julia-vscode/LanguageServer.jl/blob/dacc5bf12d97ff44b65af1547d8c36d5e9895641/src/document.jl#L1)?

It looks like [`run(::LanguageServerInstance)`](https://github.com/julia-vscode/LanguageServer.jl/blob/da7eb2347e864d7407c52dfc5aebac0a184293bd/src/languageserverinstance.jl#L236) isn't designed to enable that, and  `scripts/languageserver/main.jl` is not supposed to terminate.

**Comment by pfitzseb** [comment]
Not easily, no.

You should be able to change the startup code to open a terminal and start Julia in that (plus wrap that main loop you pointed out in an `@async`).

**Comment by davidanthoff** [comment]
I think there is nothing to do here, right? I'm closing for now.

**Comment by pfitzseb** [comment]
Yes, although we might want to think about making this easier (even if only for our own ease of development).

**Comment by davidanthoff** [comment]
I actually was thinking for some time whether we can just start the LS in the debugger, which would be neat :) I did look into that at some point, and I could swear that there was in the past a way to start a LS manually, and then connect the LS client to a running instance, which would have enabled that scenario fairly easily, but I can't find _any_ trace of info on how to do that anymore. So either I made that up, it was removed, or it is just tricky to find at the moment.
