### ISSUE TITLE
Error when starting julia REPL

### ISSUE THREAD

**Issue by myrddin89** [julia-vscode/julia-vscode#1969]
With version 1.1.26 of VSCode Julia extension, I get this error when starting the REPL:

```
ERROR: UndefVarError: active_repl_backend not defined
Stacktrace:
julia> ) at …/.vscode-server/extensions/julialang.language-julia-1.1.26/scripts/packages/VSCodeServer/src/repl.jl:70
 [2] (::VSCodeServer.var"#2#4"{REPL.LineEditREPL})() at ./task.jl:356
```

If I need to check something else to resolve this, please let me know.

**Comment by pfitzseb** [comment]
Should be fixed with https://github.com/julia-vscode/julia-vscode/pull/1968.

**Comment by myrddin89** [comment]
Thank you, I didn’t know this was already reported.
