### ISSUE TITLE
Feature Request: Add options to load startup file

### ISSUE THREAD

**Issue by AStupidBear** [julia-vscode/julia-vscode#197]
My .juliarc.jl file contains a lot of user module load paths and preloaded packages. Now I have to add include("~/.juliarc.jl") to `main.jl` in the language server folder.

**Comment by ZacLN** [comment]
I'm not sure what's going wrong here, my `.julia.rc` is being loaded

**Comment by AStupidBear** [comment]
@ZacLN  Strange. Loading .juliarc.jl is disabled [here](https://github.com/JuliaEditorSupport/julia-vscode/blob/master/src/extension.ts#L223)

**Comment by ZacLN** [comment]
Those settings are for the language server not the REPL/terminal

**Comment by davidanthoff** [comment]
Yeah, this should certainly not effect the REPL. I don't think we should run ``.julia.rc`` in the LS process, we really want to control that process tightly. @AStupidBear what is the scenario that is not working? The REPL? Some Intellisense?

**Comment by ZacLN** [comment]
Ah sorry I see what you meant now

**Comment by AStupidBear** [comment]
@davidanthoff Intellisense. Not REPL.
