### ISSUE TITLE
Data grid column width for wide tables

### ISSUE THREAD

**Issue by jtrakk** [julia-vscode/julia-vscode#1971]
I work with tables that have hundreds of columns. In the data grid, these tables aren't readable without manually dragging each column to be wider.

![image](https://user-images.githubusercontent.com/43392409/108757480-bdd06b00-74fe-11eb-8a9f-bb55ada1b056.png)

Some ideas, inspired by Excel

- set a larger default width
- allow the user to set the default width for all columns numerically
- add a button to automatically fit a column to the width of its contents
- add a button to automatically fit all columns to the width of their contents

**Comment by pfitzseb** [comment]
Fixed in the next release.
