### ISSUE TITLE
MethodError: no method matching wait(::Float64) in v1.1.28

### ISSUE THREAD

**Issue by BoundaryValueProblems** [julia-vscode/julia-vscode#1972]
Since both v1.1.26 and v1.1.27 complained `ERROR: UndefVarError: active_repl_backend not defined`, I tried v1.1.28. Then, that error was gone, but instead, I got `MethodError: no method matching wait(::Float64)`. So, at this point, I have to revert back to v.1.1.25, which doesn't generate any error messages.  With those errors (v1.1.26-28), I cannot plot graphics on Julia Plots pane. Thanks for your help!

**Comment by pfitzseb** [comment]
Sorry about that. Will be fixed with #1973.

**Comment by BoundaryValueProblems** [comment]
Thanks a lot! v1.1.29 now works well!
