### ISSUE TITLE
 IOError: could not spawn 'cmd' : no such file or directory <ENOENT> #ISSUE

### ISSUE THREAD

**Issue by abbasn110** [julia-vscode/julia-vscode#1974]
hi
Im kinda new on Julia. While working on REPL, when I want to switch to cmd and type it on Shell I get this error.

 IOError: could not spawn 'cmd' : no such file or directory <ENOENT>

 I also added installation directory to environment variables but it didnt help. Is there any way I can solve it? 
![ERROR](https://user-images.githubusercontent.com/79546488/108916281-47895100-7643-11eb-996f-e497cf5e4936.png)

**Comment by davidanthoff** [comment]
This repo here is for the Julia extension for VS Code, not Julia itself. I would suggest you ask this question over at the general Julia forum at https://discourse.julialang.org/.

**Comment by abbasn110** [comment]
I did as you suggestion. Thanks for the frequent reply.
