### ISSUE TITLE
Julia table displays sorted data in wrong order for negative values

### ISSUE THREAD

**Issue by azev77** [julia-vscode/julia-vscode#1976]
The order is correct for positive values of X2, until X2 becomes negative...

![image](https://user-images.githubusercontent.com/7883904/109354618-1891fb80-784c-11eb-96dd-11d774a3e2c8.png)

**Comment by pfitzseb** [comment]
Just for future reference -- looks like the column isn't marked as numeric, so it's just sorting strings instead.

**Comment by azev77** [comment]
@pfitzseb 
when I call a dataframe in REPL it automatically lists the variable types at the top (float, string etc)
 
<img width="657" alt="image" src="https://user-images.githubusercontent.com/7883904/109531423-dbb14900-7a85-11eb-9bae-00e5bb37a204.png">

why don't Julia Tables in VS code automatically show column types?
If they showed it was marked as a string I would convert to numeric

In RStudio datatables automatically show variable types etc
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/7883904/109531626-25019880-7a86-11eb-9b71-deee764c554c.png">

**Comment by azev77** [comment]
@pfitzseb 
The Dataframe column is float
<img width="299" alt="image" src="https://user-images.githubusercontent.com/7883904/109532422-1b2c6500-7a87-11eb-84d0-2affd730a40f.png">

But I still have the same problem

**Comment by pfitzseb** [comment]
Should be fixed in the next release.
