### ISSUE TITLE
VS code insists on opening the plot pane

### ISSUE THREAD

**Issue by PetrKryslUCSD** [julia-vscode/julia-vscode#1979]
I use Gnuplot. Yet,  VS code insists on opening a plot pane. I think  this is a bug. I know that I can turn off this behavior in the settings, but I think the extension is being overzealous here.

**Comment by pfitzseb** [comment]
We're just using Julia's normal display machinery here -- if you try to display an object that has a `show` method for e.g. `image/png` then we'll try to display that in the plot pane. It's not clear to me what we could be doing different here.

**Comment by PetrKryslUCSD** [comment]
That is a good point.

**Comment by davidanthoff** [comment]
Ok to close? If not, please reopen.
