### ISSUE TITLE
Julia table makes inefficient use of space

### ISSUE THREAD

**Issue by azev77** [julia-vscode/julia-vscode#1983]
Often columns are too wide:
<img width="1368" alt="image" src="https://user-images.githubusercontent.com/7883904/109533487-4a8fa180-7a88-11eb-9812-55fdbfbdd8d4.png">

Or too thin:
<img width="738" alt="image" src="https://user-images.githubusercontent.com/7883904/109533881-b5d97380-7a88-11eb-9dce-3b15ba5e5e07.png">

In other IDEs the spacing is better. For example:
![image](https://user-images.githubusercontent.com/7883904/109538240-dbb54700-7a8d-11eb-90aa-26402bdc1479.png)

@pfitzseb has this been brought up elsewhere?

**Comment by pfitzseb** [comment]
Should be fixed in the next release.
