### ISSUE TITLE
Is there a way to make autocomplete use smart case?

### ISSUE THREAD

**Issue by NightMachinary** [julia-vscode/julia-vscode#1988]
I want the autocomplete to use smart case, i.e., be case insensitive if all I have typed is lower case, otherwise be case sensitive. If this is not possible, just making everything case insensitive is good enough, too. I don't like typing upper-case letters.

**Comment by pfitzseb** [comment]
There's no option for that atm, no. Shouldn't be too hard to add one though, I think.

**Comment by NightMachinary** [comment]
@ZacLN Thanks!
