### ISSUE TITLE
Language Server crashing on v1.6.0-rc1

### ISSUE THREAD

**Issue by mihalybaci** [julia-vscode/julia-vscode#1990]
For the last week or so (maybe longer?), the Julia Language Server crashes when I start VS Code and is never able to run. I have attempted various ways to fix the problem, going so far as to completely remove VS Code, the `.vscode` config files, and the Julia `.compiled` folders for the extension to no avail. This issue seems to be specific to v1.6.0-rc1 because if I simply edit the settings to point the `Julia Executable Path` to the v1.5.3 binary, then it compiles and runs just fine. It is possible this is specific to my setup, but I don't know what else to try to get it working. Here is my system info:

```
Julia:
------
Julia Version 1.6.0-rc1
Commit a58bdd9010 (2021-02-06 15:49 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, haswell)
Environment:
  JULIA_NUM_THREADS = 8

VS Code:
----------
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:44.518Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 4.19.0-14-amd64

Julia Extension:
-----------------
v1.1.31
```

**Comment by pfitzseb** [comment]
You could give deleting the symbol server cache in `~/.config/Code/User/globalStorage/julialang.language-julia/symbolstorev4/` a go. Also, do you have crash reporting enabled?

**Comment by mihalybaci** [comment]
I deleted that folder and still got crashes. So I one-by-one I started deleting folders in `globalStorage/julialang.language-julia/` until I had removed the whole directory. I didn't know that folder existed, so I just tried another complete removal and reinstall of VS code and am still getting the crashes. Is it possible that it is something else within my personal Julia setup that is causing the issue?

I do have both crash reporting and telemetry enabled.

**Comment by mihalybaci** [comment]
Well, I never pinpointed the issue, but I completely removed my `~/.julia` folder and that seems to have fixed it. I don't know how I could have corrupted anything, but it's working now.

**Comment by mihalybaci** [comment]
I do not think this issue needs to be reopened, but I discovered the source of the crash. I attempted a workaround to get MKL.jl
to build properly with v1.6.0, which worked. But the sysimage that MKL.jl creates using the workaround appears to cause the VS code server to crash for some reason. 

It is this issue:  https://github.com/JuliaLinearAlgebra/MKL.jl/issues/60

**Comment by pfitzseb** [comment]
FWIW, we basically don't support Julia versions with a custom sysimg. Whenever possible you should explicitly give the `-J` option for the REPL process.

**Comment by mihalybaci** [comment]
Okay, good to know. Someone else on the MKL issue isn't having any trouble, so apparently this is still just something about my setup.
