### ISSUE TITLE
Linter warning associated with collect function

### ISSUE THREAD

**Issue by Yujie-W** [julia-vscode/julia-vscode#1991]
The linter somehow displays warning when using `collect` function. Here is an example
```
struct TestStruct{FT<:AbstractFloat}
    sa::FT
    sb::FT
end

function test(a::FT) where {FT<:AbstractFloat}
    return collect(FT, 0:1:a);
end

function test(st::TestStruct{FT}) where {FT<:AbstractFloat}
    return collect(FT, 0:1:st.sa)
end
```
Here is the warning
![warning](https://user-images.githubusercontent.com/16584422/110013878-ffb79900-7cd6-11eb-816e-d8502b119e3c.png)

P.S. both test functions work, but it is anoying to see the warning.

**Comment by ZacLN** [comment]
I think this has been fixed by https://github.com/julia-vscode/StaticLint.jl/pull/268
