### ISSUE TITLE
Remote Development

### ISSUE THREAD

**Issue by ohmsweetohm1** [julia-vscode/julia-vscode#1996]
I'm using this VSCode extension for Julia and the remote [Development Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack).
However, I have the problem that that the Julia process that is started by the extension is still running.
I have many processes like:
```
/<folder>/julia-1.5.0/bin/julia --startup-file=no --history-file=no --depwarn=no --project=/<folder>/.vscode-server/extensions/julialang.language-juli
```
that are days old, still runnning.

**Comment by pfitzseb** [comment]
Dup of https://github.com/julia-vscode/julia-vscode/issues/1951, I think.
