### ISSUE TITLE
"Start debugging" does not work anymore in 1.1.33 / Ubuntu

### ISSUE THREAD

**Issue by graidl** [julia-vscode/julia-vscode#2004]
"Start debugging" does not do anything anymore in version 1.1.32+33 under my Ubuntu 20.04 with the most recent VSCode. 
I tried it with and without launch configuration. Going back to ~~1.1.32~~1.1.31, it works again.
Also run as separate process doesn't work anymore. 
Starting the debugger from the REPL with @run, however, works.
Also tested it on different projects.

**Comment by davidanthoff** [comment]
I'm not sure whether this here and https://github.com/julia-vscode/julia-vscode/issues/2003 are the same thing. They sound similar, but refer to different extension versions...

**Comment by graidl** [comment]
I am sorry, I mixed the versions. I can confirm that the problem I am referring to also started with version 1.1.32 and only 1.1.31 still worked. I corrected my report correspondingly. And yes, #2003 seems to refer to the same.

**Comment by pfitzseb** [comment]
Alright, let's close this in favour of #2003 then.
