### ISSUE TITLE
Julia REPL turns black after switching to another window

### ISSUE THREAD

**Issue by dfdx** [julia-vscode/julia-vscode#2005]
VS Code version: 1.54.1
Julia extension version: 1.1.32
Julia version: 1.5.0
OS: Linux Mint 19.1 Tessa (Cinnamon)

### Steps to reproduce

1. Open Julia REPL.
2. Start a long-running process.
3. Switch to another OS window (e.g. Chrome) for a few minutes.
4. Go back to VS Code.

### Expected result

REPL shows the progress of the process.

### Actual result

In ~30% of cases REPL pane becomes mostly black and doesn't respond to keystrokes:

![image](https://user-images.githubusercontent.com/428171/110243989-be8ce680-7f6d-11eb-96ea-8dc5a030281b.png)

Some control sequences (e.g. Ctrl+C Ctrl+C) result in error messages like if REPL was alive, but normal input doesn't show up:

![image](https://user-images.githubusercontent.com/428171/110244111-4ffc5880-7f6e-11eb-8d51-303341824fca.png)

System monitor shows that calculations continue, so it should be an issue with display. 

### Notes

* same thing happens after screen lock
* I'm not sure it's related to Julia extension or VS Code itself, but so far I wasn't able to reproduce the issue with Python or bash

**Comment by davidanthoff** [comment]
My best guess is that this is actually an upstream issue?

**Comment by dfdx** [comment]
By upstream you mean VS Code itself, right?

**Comment by davidanthoff** [comment]
Yes.

**Comment by dfdx** [comment]
I will repost this issue to VS Code's repo then. 
Thanks!
