### ISSUE TITLE
Wrong linter warnings "A DataType parameter has been specified but not used"

### ISSUE THREAD

**Issue by graidl** [julia-vscode/julia-vscode#2006]
I get the linter warning "A DataType parameter has been specified but not used" in a lot of cases where this is not deserved such as in the following function:
`function Base.copy!(s1::S, s2::S) where {S <: MAXSATSolution}
...
end
`
Unlike other linter warnings, these warnings disappear once I click on them to jump to the respective code.

**Comment by pfitzseb** [comment]
I can't repro this in the latest version.
