### ISSUE TITLE
debugging does not start

### ISSUE THREAD

**Issue by ericqu** [julia-vscode/julia-vscode#2009]
Using version 1.1.33 on Linux and Windows.
the test code is:
```julia
a = 5
b = 2a
println(b)
```
I put a breakpoint on the second line and then pressed F5 to launch the debugger. And then nothing happens.

on Linux and windows, there are many warnings of the type in the "Julia Language Server":
```
┌ Warning: DiffEqSensitivity not stored on disc
└ @ SymbolServer ~/.vscode/extensions/julialang.language-julia-1.1.33/scripts/packages/SymbolServer/src/SymbolServer.jl:197
```

Let me know if any other information is needed.

If it is possible to roll back to a previous version that is working please let me know how, and which version is the most stable.

**Comment by pfitzseb** [comment]
Dup of https://github.com/julia-vscode/julia-vscode/issues/2003 and fixed by https://github.com/julia-vscode/julia-vscode/pull/2008.
