### ISSUE TITLE
What is the lifetime of kernels in Notebooks

### ISSUE THREAD

**Issue by DonJayamanne** [julia-vscode/julia-vscode#2018]
Based on the initial work in the Notebook PR, the kernel dies when VS Code closes.
It seems that the same kernel is used for all notebooks.

**Options:**
* Use single kernel for all documents? Is this the desired effect?
* Separate kernel for each document
	* In Jupyter Notebooks (lab) each notebook gets its own instance of a kernel.
	* In Jupyter extension for VS Code, each notebook gets its own instance of a kernel.

I'd suggest going with the latter option.
But we need a way to manage these kernels. What if a user opens 10 documents, now we have 10 kernels.
10 processes now running, if the user doesn't close VS Code these stay running. Is this ok?

**Comment by pfitzseb** [comment]
I'm not particularly happy with having a Julia process for each notebook (Julia needs a *lot* of memory compared to e.g. Python), but don't see any way around that. We could reduce the memory overhead a bit with using Distributed (much like Pluto does), but that'd open a whole new can of worms.

**Comment by davidanthoff** [comment]
Yeah, I definitely think we need to have one kernel per notebook!

I think in terms of UI I would want to get rid of the terminal for the kernel that I have right now, and instead show a list of running kernels somewhere else, with options to kill and restart them. Jupyter Lab for example has a dedicated UI for that. My current thinking is that we can add this to our existing Workspace view. That view currently shows all the variables in the Julia REPL:

![image](https://user-images.githubusercontent.com/1036561/110973707-6f023e00-8312-11eb-9e05-e1da4b147de8.png)

What I think we should do is add another top level layer in that hierarchy that corresponds to "kernel". So we might have the following nodes as the top level nodes:
```
Julia REPL
Notebook kernel (FILENAME)
Notebook kernel (FILENAME)
```
etc. And then one can expand each of these kernel nodes and see all the variables in that specific kernel, as one can do today for the REPL. To the right of each top level node we could add action buttons for "Stop kernel", "restart kernel" etc.

In terms of lifetime, I'm not entirely sure... In Jupyter Lab kerneles outlive the notebook open/close cycle. So if you open a notebook, run something, then close the notebook in the UI, the kernel is _not_ killed. You either have to kill the kernel manually in the UI, or it gets killed when Jupyter Lab is closed entirely. So my gut feeling is to just go with that for starters to keep things compatible?

**Comment by DonJayamanne** [comment]
> unning kernels somewhere else, with options to kill and restart them. Jupyter Lab for example has a dedicated UI 

In the Jupyter extension we are looking at creating a Jupyter Panel with the ability to display runnign kernels, and ability to manage them (stop, interrupt, etc).
Not sure whether we'd expose that to non-jupyter kernels (like vs code kernels), but happy to look into that extensiblity, then Julia can just contribute to that.

However, the complication is the panels would sit under `Jupyter` instead of `Julia` panel.

But thats just an idea.

> I'm not particularly happy with having a Julia process for each notebook
> Yeah, I definitely think we need to have one kernel per notebook!

Feels like there are two schools of thought here. 
When i start working on the kernel, as mentioend in another issue, i'll factor our the real kernel implemnentation into another file, this way, if we want to have separate kernels per notebook or vice versa, its a simple change. But i'd like to remove that assumption/link from the notebook code.

**Comment by pfitzseb** [comment]
> Feels like there are two schools of thought here.

David and I are basically agreed on having one process per notebook, I think. I don't like it, but the alternatives are even worse ;)

**Comment by davidanthoff** [comment]
One more observation: I do believe we are using separate kernels already for each notebook. One just needs to make sure to select our kernel for each notebook separately.

**Comment by DonJayamanne** [comment]
Thaks for clarification.
I just want to ensure i have everything right.

> David and I are basically agreed on having one process per notebook, I think

This means we're sharing the same underlying process/kernel for each notebook.
You delcare a variable in one notebook and run it , then you can access the same informaiton from another different notebook. is that right.

**Comment by davidanthoff** [comment]
> This means we're sharing the same underlying process/kernel for each notebook.
You delcare a variable in one notebook and run it , then you can access the same informaiton from another different notebook. is that right.

No, just the other way around :) We start a separate Julia process for each notebook, nothing is shared between notebooks.

**Comment by davidanthoff** [comment]
I think this is also resolved: we have a separate kernel per notebook, and we have a notebook lifecycle UI in the Julia Workspace.
