### ISSUE TITLE
When should we start a kernel for notebooks

### ISSUE THREAD

**Issue by DonJayamanne** [julia-vscode/julia-vscode#2019]
Today we seem to start the Julia kernel as soon as the user selects the kernel.
I don't think this is the desired effect.
If user doesn't have any kernel installed at all, then just opening a notbook results in a kernel being started, even if the user didn't mean for this to happen. Its possible they opened a notebook just to view it.

Instead we can start the kernel when the user attempts to run a cell.
THoughts?

**Comment by pfitzseb** [comment]
100% agreed.

**Comment by davidanthoff** [comment]
Yes, I had the same thought yesterday!

**Comment by DonJayamanne** [comment]
Dinner
