### ISSUE TITLE
Use same kernel used by Notebook and Repl

### ISSUE THREAD

**Issue by DonJayamanne** [julia-vscode/julia-vscode#2021]
This is just to get a better understanding of the current codebase and API.
Apologies for creating an issue to ask such issues.

Why do we have two types of kernels, one for REPL and one for the Notebook?
I'm referring to the underlying comms in repl.ts & notebookkernel.ts in the notebook branch.

Is it not possibel to use the same underlying kernel & same communication mechanism.
If we were to share the code, then if tomorrow we wanted to add debugging for Notebook kernels, it wouldn't require too much (additional) effort, as we'd be re-using most of the existing infrastructure.

**Comment by pfitzseb** [comment]
We should probably try to factor out common parts needed for both REPL and notebook kernels, yes.

**Comment by davidanthoff** [comment]
Yes, that was also on my roadmap. I primarily kept it separate because I didn't want to run into huge merge conflicts while the `notebook` branch stays separate. But we should definitely just use the same code here, also to reuse things like the variables tree inspector etc.

**Comment by DonJayamanne** [comment]
I'll try to look into that, at least i'll try to factor out the kernel code (comms) from notebooks, then when we re-use the code from repl.ts, it'll be a matter of just using common code & changing underlying implementation, without any changes to the notebook stuff.

**Comment by DonJayamanne** [comment]
@davidanthoff I'd like to add support for interrupt, hence going to try to work on this, with little refactoring as possible, you can see the PR.

**Comment by davidanthoff** [comment]
Give me a few minutes, and I'll add support for the interrupt notification in the server!

**Comment by davidanthoff** [comment]
Actually, I'm realizing that is a bit more difficult than I thought :) Right now we are running code on the same task on which we are processing messages, and so we will only ever start to process the next message from the client when a given code block is finished executing. That won't work for interrupting things :)

So we'll need to change that on the Julia side of things. I'll have to think a bit how we would best do that...

**Comment by DonJayamanne** [comment]
Never mind, I'll work on this, based on what I can tell we're still going to want to have some common code (share code between repl.ts and notebooks).
I'll work on that, moving starting terminal and the like into a common file.

**Comment by davidanthoff** [comment]
Yeah, that is what I am thinking right now, but I think we might want to wait for feedback from @pfitzseb before we move ahead, he kind of owns that part of the code at the moment. He is on European time.

**Comment by DonJayamanne** [comment]
>  he kind of owns that part of the code at the moment. He is on European time.

Absolutely no problem.

**Comment by davidanthoff** [comment]
We now have a shared codebase on the Julia side of things for the notebook kernels and the REPL.
