### ISSUE TITLE
Kernel selection for Jupyter notebooks

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/julia-vscode#2023]
@DonJayamanne So my biggest question right now is around kernel selection. So [here](https://github.com/julia-vscode/julia-vscode/blob/7b395fc6a0a087bb9dcc85bf158cc048ad6c7234/src/notebook/notebookFeature.ts#L32) we are now saying "Hey, we might be able to help for ipynb files/jupyter-notebook views", and then [here](https://github.com/julia-vscode/julia-vscode/blob/7b395fc6a0a087bb9dcc85bf158cc048ad6c7234/src/notebook/notebookFeature.ts#L10) I'm currently saying we can handle anything that has the `julia` language.

But isn't the Jupyter extension going to claim exactly the same thing also? And how does VS Code then decide which kernel to use by default?

**Comment by DonJayamanne** [comment]
> But isn't the Jupyter extension going to claim exactly the same thing also? And how does VS Code then decide which kernel to use by default?

Already on that, thanks for creating this issue so we can track it.
Here's the upstream issue, please feel free to upvote that issue https://github.com/microsoft/vscode-jupyter/issues/5126

I'm certain we'll be able to address that. We had a solution for .NET extension, but that might not work here.
