### ISSUE TITLE
Add support for Notebook Kernel Interrupt on Windows

### ISSUE THREAD

**Issue by DonJayamanne** [julia-vscode/julia-vscode#2025]
The solution could be one of the following:
* Either add interrupt to the kernel code in notebooks (see here https://github.com/julia-vscode/julia-vscode/pull/980#discussion_r592949474)
* Or just use the existing interrupt in repl.ts         g_connection.sendNotification('repl/interrupt')
	* I.e. use the same code for both repl and notebook.
	* See here https://github.com/julia-vscode/julia-vscode/issues/2021

This issue is used to track the need for interrupt in notebooks as this doesn't exist today.

**Comment by davidanthoff** [comment]
Closing this in favor of https://github.com/julia-vscode/julia-vscode/issues/2039.
