### ISSUE TITLE
Everytime we reload VS Code, our connection with the kernel is lost, but VS Code keeps the terminal alive

### ISSUE THREAD

**Issue by DonJayamanne** [julia-vscode/julia-vscode#2033]
* With Notebooks, we start the julia process in a terminal
* If you re-load VS Code, the process doesn't die and the terminal is still alive
* Unfortunately the extnsion doens't know this, it re-launches Julia kernels in the terminal.
I.e. if you reload VS Code 10 times, and run a notebook each time, we'll have 10 terminals with (assuming) 10 julia processes.

Will need to check if we can stop this, or kill the processes.
Just adding this issue to ensure we don't forget this.

**Comment by davidanthoff** [comment]
The implementation has changed in that we no longer use terminals. We still have ghost processes, though, tracking that at https://github.com/julia-vscode/julia-vscode/issues/2254.
