### ISSUE TITLE
How do we open/create notebooks

### ISSUE THREAD

**Issue by DonJayamanne** [julia-vscode/julia-vscode#2037]
Today Jupyter extension has support for opening/creating Ipynb files.
Julia extension is working on working with he notebook that's created by Jupyter extension.

How do users get started with Julia and notebooks?:
* Do they install Julia extension & also Jupyter (how do they know they need this?)
* Do we want Julia extension to ship with Jupyter
	* Bascially all we need to do is add an entry in the package.json in the julia extension.
	* Thus when users install Julia they get Jupyter extension as well, and users will not have to install Python or any other dependecies just because they install Jupyter extension

thought i'd start this conversation before submitting a PR that added the dependency.

**Comment by pfitzseb** [comment]
I think I'd prefer not "depending" on the Jupyter extension here. Instead we should imho take the user to the marketplace to install the Jupyter extension when they try to use a feature that needs it.

**Comment by DonJayamanne** [comment]
I agree, 

> nstall the Jupyter extension when they try to use a feature that needs it.

I would expect VS Code to do the necessary recommendations for ipynb files, just as they would recommend julia extension today for julia files. I.e. I think we can close this issue and things should work out fine.

**Comment by davidanthoff** [comment]
https://github.com/microsoft/vscode/issues/118442 might also turn into something that could help us here, not sure though.
