### ISSUE TITLE
Support Julia in Jupyter Interactive Window

### ISSUE THREAD

**Issue by DonJayamanne** [julia-vscode/julia-vscode#2042]
A picture speaks a 1000 words, please have a look at the gif in the issue https://github.com/microsoft/vscode-jupyter/issues/273
Basically this is a feature we support today and widely used in Python community using VS Code.
Would such a feature be useful for Julia (FYI the screenshots are workign prototypes, using the Julia kernel that is used by Jupyter).

There are some places where the Julia extension can contribute if this is deemed a useful feature.

**Comment by RoyiAvital** [comment]
How can one enable this?
