### ISSUE TITLE
Variable Viewer for Notebooks

### ISSUE THREAD

**Issue by DonJayamanne** [julia-vscode/julia-vscode#2044]
Add existig repl variable viewer in notebooks as well.
I'd like to work on this @davidanthoff

**Comment by davidanthoff** [comment]
I think the first step for this would be to enhance our workspace tree to support a new node type, namely these top level nodes for connections to either the REPL or a notebook kernel. I think ideally we would actually make that change on `master` first, i.e. on `master` add support for a new abstract type `ConnectionToJuliaInstance`, with a sub type `JuliaREPLConnection`, that would essentially correspond to the top level node that corresponds to our REPL. I think that would also imply moving a whole bunch of global state that we have right now in the extension (and that assumes that there is only ever a singleton instance of a Julia REPL) into such a data structure.

And then, as a second step, we could add another sub type of `ConnectionToJuliaInstance` named say `JuliaKernelConnction` on the `notebook` branch.

And I think (hope) that it would then be relatively straightforward to support the variable viewer for the notebook kernels.

But with all of this, I think we need input from @pfitzseb, he is much more familiar with that part of the codebase than I am, and I think he should actually decide how we best phase this in and how we should move code that corresponds to the REPL around.

**Comment by pfitzseb** [comment]
Yep, that sounds about right. I'll spend some time on getting the workspace to work with multiple providers (REPL and kernels), although maybe we should do that in a more structured way.

**Comment by davidanthoff** [comment]
Our existing Julia Workspace variable viewer now works with notebook kernels.
