### ISSUE TITLE
Support multiple Julia version kernels

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/julia-vscode#2045]
For the Jupyter kernel story, we need to support multiple Julia version kernels.

At the moment we just return one kernel [here](https://github.com/julia-vscode/julia-vscode/blob/334a1334189f1dfe28d77c14b879b4ac59cc0e5b/src/notebook/notebookFeature.ts#L12), but really we should return a list of kernels there where each kernel corresponds to a different Julia version that is installed.

I think essentially we need to change things as follows:
- Detect _all_ Julia versions that are currently installed, not just the newest one. Potentially we might need something like an array for manually configured Julia paths, but I think for beginners we could just go with the auto-detected versions.
- In general then return a list of kernels we can offer, one for each Julia version we have.
- For existing notebooks that are opened, where the notebook was created with a Julia version that is not installed, we then need some smart fallback options that we probably still have to figure out...

**Comment by davidanthoff** [comment]
CC @DonJayamanne Should I tag you on all issues that are related to notebooks that I create you? That way you would get notified without having to subscribe to all notifications from this repo (where there are probably _a lot_ that are of zero interest to you). Or do you just want to look up issues with the `area-notebook` label yourself?

**Comment by DonJayamanne** [comment]
> do you just want to look up issues with the area-notebook label yours

Latter is fine. I'll be checking the issues.

**Comment by davidanthoff** [comment]
This is implemented on our end now.
