### ISSUE TITLE
How does a user restart the kernel

### ISSUE THREAD

**Issue by DonJayamanne** [julia-vscode/julia-vscode#2054]
We have a `restart`, but theres no UI affordance for this.
Hopefully we'll get something from VS Code (as 3 extensions need this today).
https://github.com/microsoft/vscode/issues/118783

**Comment by davidanthoff** [comment]
So I think once we have the variable viewer story as outlined in https://github.com/julia-vscode/julia-vscode/issues/2044, that might be a pretty natural place in the UI to also show a restart option.

But then, I also see the value of a central VS Code wide UI for kernels.

**Comment by davidanthoff** [comment]
For now we have a restart UI in the Julia Workspace.
