### ISSUE TITLE
Could not start language server

### ISSUE THREAD

**Issue by Ifihan** [julia-vscode/julia-vscode#2058]
After updating my Julia version to 1.5.3, I've tried changing the `julia.executablePath` to the current version but it gives me an error saying " is not recognized as an internal or external command, operable program or batch file", and the server doesn't start. I have even uninstalled and reinstalled the extension but it didn't work.

**Comment by davidanthoff** [comment]
Can you start a REPL?

**Comment by Ifihan** [comment]
No, I can't.

**Comment by pfitzseb** [comment]
Did you make sure the path to the Julia binary is correctly set? The settings UI is sometimes a bit finnicky with applying changes, so do check the JSON file directly.

**Comment by Ifihan** [comment]
Yes, I did. Still the same error.

**Comment by pfitzseb** [comment]
What exactly did you set the path to? Also, do you have a workspace/folder specific Julia path set (check the different tabs at the top of the settings UI).

**Comment by Ifihan** [comment]
I set the path to the \bin folder. Yes, I do have a specific Julai Path set.

**Comment by pfitzseb** [comment]
Pretty sure the path needs to point to the binary, not the directory containing the binary.

**Comment by Ifihan** [comment]
Attached is how I set my Path in the `settings.json` file

![julie](https://user-images.githubusercontent.com/49107589/111437829-d1d54a00-8703-11eb-9e43-71b228600f1d.png)

**Comment by pfitzseb** [comment]
Right, please change `julia.executablePath` to `"C:\\Users\Ifihan\\AppData\\Local\\Programs\\Julia 1.5.3\\bin\\julia.exe"`.

**Comment by Ifihan** [comment]
It works now. Thanks a lot!

**Comment by pfitzseb** [comment]
Great, glad it's working for you now. Will close this in favor of https://github.com/julia-vscode/julia-vscode/issues/1854 because we really should throw a more informative error.
