### ISSUE TITLE
1.1.35 breaks something

### ISSUE THREAD

**Issue by BPMinaker** [julia-vscode/julia-vscode#2060]
After upgrading extension from 1.1.34 to 1.1.35, all my syntax highlighting is gone, and Command Palette actions, in particular, "Execute File in REPL" don't work.  The REPL will start, and is responsive to command line input.  Running Julia 1.5.4 on fully updated Arch Linux.  Downgrade to 1.1.34 from the VS Code Marketplace and manual install restores proper functionality.

**Comment by pfitzseb** [comment]
What version of VSCode are you using?

**Comment by BPMinaker** [comment]
Version: 1.54.0
Commit: 81ae94a9dc82197829717915db783e3b934db46a
Date: 2021-01-31T04:24:40.227Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.11.6-arch1-1

**Comment by pfitzseb** [comment]
Hm, that version should ship syntax highlighting for Julia out of the box. Do you see any error messages for commands that stopped working? Does the Outputs > Julia Language Server view show anything alarming?

**Comment by BPMinaker** [comment]
The output is below, lots of warnings, but no errors.  It doesn't start the server until I use the command palette to open a REPL.

[ Info: Starting the Julia Language Server
[ Info: Symbol server store is at '/home/bpminaker/.config/Code - OSS/User/globalStorage/julialang.language-julia/symbolstorev4'.
┌ Warning: Artifacts not stored on disc
└ @ SymbolServer ~/.vscode-oss/extensions/julialang.language-julia-1.1.35/scripts/packages/SymbolServer/src/SymbolServer.jl:197
┌ Warning: Grisu not stored on disc
└ @ SymbolServer ~/.vscode-oss/extensions/julialang.language-julia-1.1.35/scripts/packages/SymbolServer/src/SymbolServer.jl:197
┌ Warning: GR_jll not stored on disc
└ @ SymbolServer ~/.vscode-oss/extensions/julialang.language-julia-1.1.35/scripts/packages/SymbolServer/src/SymbolServer.jl:197
┌ Warning: ColorTypes not stored on disc
└ @ SymbolServer ~/.vscode-oss/extensions/julialang.language-julia-1.1.35/scripts/packages/SymbolServer/src/SymbolServer.jl:197
┌ Warning: Latexify not stored on disc
└ @ SymbolServer ~/.vscode-oss/extensions/julialang.language-julia-1.1.35/scripts/packages/SymbolServer/src/SymbolServer.jl:197
┌ Warning: GeometryBasics not stored on disc
└ @ SymbolServer ~/.vscode-oss/extensions/julialang.language-julia-1.1.35/scripts/packages/SymbolServer/src/SymbolServer.jl:197
┌ Warning: LibVPX_jll not stored on disc
└ @ SymbolServer ~/.vscode-oss/extensions/julialang.language-julia-1.1.35/scripts/packages/SymbolServer/src/SymbolServer.jl:197
┌ Warning: Contour not stored on disc
└ @ SymbolServer ~/.vscode-oss/extensions/julialang.language-julia-1.1.35/scripts/packages/SymbolServer/src/SymbolServer.jl:197
┌ Warning: LaTeXStrings not stored on disc
└ @ SymbolServer ~/.vscode-oss/extensions/julialang.language-julia-1.1.35/scripts/packages/SymbolServer/src/SymbolServer.jl:197
┌ Warning: EzXML not stored on disc
└ @ SymbolServer ~/.vscode-oss/extensions/julialang.language-julia-1.1.35/scripts/packages/SymbolServer/src/SymbolServer.jl:197
[ Info: Received new data from Julia Symbol Server.

**Comment by BPMinaker** [comment]
Updated to:

Version: 1.54.2
Commit: fd6f3bce6709b121a895d042d343d71f317d74e7
Date: 2021-03-12T19:27:39.374Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.11.6-arch1-1

and problem is gone.
