### ISSUE TITLE
problems with VScode 1.54.x?

### ISSUE THREAD

**Issue by rryi** [julia-vscode/julia-vscode#2061]
I did upgrade to VScode 1.54.1 about 5 days ago (fresh install, portable version) and installed julia-vscode. Debugger and git did not work, I went back to VSCode 1.53.2. I retried with 1.54.2. Lots of errors:

Steps to reproduce:

 * OS Windows 10 professional 20H2, 64 bit
 * download VSCode 1.54.2 (Win portable installation, ZIP archive)
 * unpack in target dir
 * create data dir in VSCode dir (to avoid storing in win user profile)
 * start VSCode
 * install julia-vscode 1.1.35
 * set path to julia.exe (julia 1.5.3)
 * start a REPL

very short, this display pops up:
![image](https://user-images.githubusercontent.com/26365322/111348840-e0c6e880-8680-11eb-94f8-06f86420a59d.png)

waiting a minute, this is displayed:
![image](https://user-images.githubusercontent.com/26365322/111348935-f9370300-8680-11eb-822b-1abc23af4e8f.png)

REPL is working, I can call some julia functions. (the JULIAVERSION shown on next screenshot is a windows environment variable I have many julia versions installed in parallel).
![image](https://user-images.githubusercontent.com/26365322/111349260-43b87f80-8681-11eb-86c9-9bbcf348f457.png)

run&debug button in left panel has changed behavior: asks for an environment
![image](https://user-images.githubusercontent.com/26365322/111349839-c5a8a880-8681-11eb-9b6c-ff71d5fd74d4.png)
I select julia :-)

A strange message pops up:
![image](https://user-images.githubusercontent.com/26365322/111349980-ee30a280-8681-11eb-8744-f11a59d211da.png)

I open a folder with a julia project. Language server crashes again.
![image](https://user-images.githubusercontent.com/26365322/111350200-289a3f80-8682-11eb-9039-610b25b31ff7.png)

IDE & extension seem to work, but those crash messages are annoying, and I fear it could have negative effects on my work. You should have a lot of crash reports from me ...

With vscode 1.54.3, error messages are less, but still there:

![image](https://user-images.githubusercontent.com/26365322/111352328-57b1b080-8684-11eb-8fc7-6c103a015458.png)

![image](https://user-images.githubusercontent.com/26365322/111352583-9e9fa600-8684-11eb-9dcc-e407efed0fec.png)

**Comment by pfitzseb** [comment]
Crash reporting tells me that we fail to precompile LanguageServer.jl on your system. Can you check whether you have write access to `c:\RRtool\vscode\data\user-data\User\globalStorage\julialang.language-julia\lsdepot\v1\compiled\v1.5\LanguageServer\` (just follow that path as far as it goes if directories don't exist after some point)?

**Comment by rryi** [comment]
Folder exists, authenticated users have write access:
![2021-03-18 12_17_27-C__RRtool_VScode_data_user-data_User_globalStorage_julialang language-julia_lsde](https://user-images.githubusercontent.com/26365322/111618099-41bb0180-87e4-11eb-9d5a-c3445ac3b368.png)

It contains 2 files, same access rights:
![2021-03-18 12_16_31-C__RRtool_VScode_data_user-data_User_globalStorage_julialang language-julia_lsde](https://user-images.githubusercontent.com/26365322/111618228-67480b00-87e4-11eb-9bc3-d8516ac33a2b.png)

**BUT** despite that, your suggestion maybe correct in some sense. Access rights are o.k, but the files in the folder are marked write-protected:
![image](https://user-images.githubusercontent.com/26365322/111619040-5e0b6e00-87e5-11eb-85d6-ee7dcf141373.png)

I checked it upwards the directory chain. **ALL** folders in C:\ are marked write-protected. Same holds for volume S:\ on a separate harddisk and volume R:\, a ramdisk which is created on every boot. This was never done intentionally by me, I cross-checked with a machine having a newer setup - same picture. Seems to be a a windows property.

Hmm. I have absolutely no problems with unexpected write protection in everyday use. Create files, folders, copying, deleting writing ... everything works as expected. I am aware of only one exception: my portable installation of Irfanview (same base folder C:\RRtool) complains sometimes its config file is write protected.

I tried to remove that write protection mark recursively in a ramdisk installation:
![image](https://user-images.githubusercontent.com/26365322/111622315-4fbf5100-87e9-11eb-9539-1933717cb7b8.png)
Windows shows it is doing something recursively in a loop, but afterwards, all write protection marks are still there.

Seems to be a "feature" of some windows installations, see  [folders write-protected by windows](https://answers.microsoft.com/en-us/windows/forum/windows_10-files-winpc/how-do-you-remove-write-protection-on-a-folder/76373111-c71e-41e6-9b47-7451bdc9f9bf).

I just tested again with VSCode, opening the ramdisk installation - no error messages, and a new file was written to the language server folder:
![image](https://user-images.githubusercontent.com/26365322/111622927-0c191700-87ea-11eb-9c80-b36c81ca4e9a.png)

Test again with the installation in C:\RRtool: no errors shown, everything works smoothly.

Hmm.
I did a fresh install to ramdisk as described (unpack zip, create data dir, start VSCode, install julia extension, start repl) and got errors again;
![image](https://user-images.githubusercontent.com/26365322/111625774-89925680-87ed-11eb-8813-6b717f4efa7c.png)

Languageserver folder is empty (installed julia v1.6 RC meanwhile, VSCode seems to detect it, so a slightly changed folder chain)
![image](https://user-images.githubusercontent.com/26365322/111626175-fdccfa00-87ed-11eb-9c33-84abda6baa3e.png)

So the bug is still reproducible, but seems to vanish after a couple of VSCode restarts.

If I am the only one having such problems, you can close this issue. Bug is reproducible, but I can work around it.

If you want to do further investigation, I will support it with further experiments (just tell me what to do)

**Comment by rryi** [comment]
Here my install script. It uses 7zip command line version to unpack. Could that have any impact on folder attributes?! I never heard of such a thing. Following steps are done manually. The install in r:\VScodeRetry was done manually, unpacking with 7zip GUI.

rd /S /Q c:\rrtool\VSCodeAlt
ren c:\rrtool\VSCode VSCodeAlt
bin\7za x -o%RRtool%\VSCode dev\VSCode-win32-x64-1.54.3.zip
md %RRtool%\VSCode\data

**Comment by pfitzseb** [comment]
The read-only thing is a red herring, I think. Can you check whether your current user account is the owner of the directory/the files in it (click on Advanced in the Securitcy tab)?

I'll try reproing with the portable install.

**Comment by rryi** [comment]
I did a machine reboot - always good for windows ;-)

After unpacking VSCode, My user account is owner:
![image](https://user-images.githubusercontent.com/26365322/111629884-0cb5ab80-87f2-11eb-8b48-3d7527e18adc.png)

After start of VSCode and installation of extension, folder chain is only partly created:
![image](https://user-images.githubusercontent.com/26365322/111630533-c01ea000-87f2-11eb-9e58-e1dfbc2235bd.png)

After opening a REPL, folders are created. After a while, julia prompt appears.
No errors, this time. Folder content: 
![image](https://user-images.githubusercontent.com/26365322/111630953-2a374500-87f3-11eb-9ab1-e4de702100d6.png)

Sorry, I cannot reproduce the bug any more. Windows too tired after a week without reboot?

**Comment by pfitzseb** [comment]
Huh, weird. So let's just chalk this up to some Windows permission weirdness, I guess (although there were other users who ran into similar issues).

**Comment by rryi** [comment]
agreed.
