### ISSUE TITLE
Feature request: A harder version of format document that also fixes indentation

### ISSUE THREAD

**Issue by xtalax** [julia-vscode/julia-vscode#2066]
Hi, I've found the extension excellent - Thanks! 
One thing I've noticed is that format document won't fix indentation when there are tabs to the left of a block of code, probably to avoid removing ones that the user has inserted for clarity. This is great, but leaves me manually removing these tabs when I remove an if statement (for example).

A version of format document that also removed tabs would be extremely useful, perhaps scoped to work only within selection to avoid clobbering manually inserted ones.

**Comment by pfitzseb** [comment]
Good idea, but unlikely to happen here since we're planning on [using JuliaFormatter](https://github.com/julia-vscode/LanguageServer.jl/pull/759).
