### ISSUE TITLE
performance issue at Plots panel ?

### ISSUE THREAD

**Issue by yeruoforever** [julia-vscode/julia-vscode#2070]
I use my laptop to connect to a remote server. When I draw a chart, my laptop becomes slow to respond.
I tried to find the reason, and found that when using the julia plots panel, the cpu occupancy rate increased significantly, and the memory approached 4GB. It seems that this puts a burden on my laptop that shouldn't be borne, especially when I switch charts.
I am interested in Plots planel in julia-vscode. Is the chart rendered by the client's vscode? Does it re-render every time I switch the chart? Is there a better solution to make the user experience smoother?
```julia
julia> using Plots
julia> scatter(rand(100),markershape=:xcross)
julia> scatter(rand(1000),markershape=:xcross)
julia> scatter(rand(10000),markershape=:xcross)
julia> scatter(rand(100000),markershape=:xcross)
julia> scatter(rand(1000000),markershape=:xcross)
```

**Comment by pfitzseb** [comment]
The issue here is that we default to outputting SVGs, which can indeed slow down or crash whatever application they're shown in. We could consider switching to PNG as the default.
In theory
```
scatter(rand(100),markershape=:xcross,html_output_format=:png)
``` 
should do the trick, but that code path isn't actually being hit here. In the meantime
```
julia> p = scatter(rand(100),markershape=:xcross);

julia> display("image/png", p)
```
should always work, even though it's a bit annoying.

**Comment by yeruoforever** [comment]
> The issue here is that we default to outputting SVGs, which can indeed slow down or crash whatever application they're shown in. We could consider switching to PNG as the default.
> In theory
> 
> ```
> scatter(rand(100),markershape=:xcross,html_output_format=:png)
> ```
> 
> should do the trick, but that code path isn't actually being hit here. In the meantime
> 
> ```
> julia> p = scatter(rand(100),markershape=:xcross);
> 
> julia> display("image/png", p)
> ```
> 
> should always work, even though it's a bit annoying.

Thanks for your reply and following your suggestions, I can work happily on my laptop.

**Comment by jcbritobr** [comment]
Im having a problem with svg plots in monte carlo simulations. Vscode plugins do not support that much large sizes and it will crash taking all memory of your system. I agree making png plots defaults, as we no need high resolutions for the most majority of plots. Or, we need to enhance plot panel performance in case to stay with svg.

![image](https://user-images.githubusercontent.com/6579862/137467797-2aaa521d-2157-4780-b92e-8f38418b1e96.png)
