### ISSUE TITLE
Render Latexify output in the plot pane?

### ISSUE THREAD

**Issue by tpoisot** [julia-vscode/julia-vscode#2071]
I'm not sure if this is possible but: when I use [`Catalyst`](https://github.com/SciML/Catalyst.jl) with students, we tend to look at the output of `Graph` (which shows in the plot pane), and also the `latexify` output. This is where it gets less intuitive, since we usually end up copying and pasting into quicklatex.com or something to that effect.

My _feature request_ would be to **render the output of latexify calls**, maybe in the plot pane, possibly using [katex](https://katex.org/). I don't know how the `mchem` environment would be handled, but there is apparently [a plugin for katex](https://mhchem.github.io/MathJax-mhchem/).

Is this a feature that would be useful? I have no idea about the architecture of the package, but with some guidance I would be game to try a submit a PR to do this. I genuinely think that looking at the equations within VScode would be a good feature, especially with the emergent CAS.

**Comment by pfitzseb** [comment]
Doesn't this already work since [this PR got merged](https://github.com/korsbo/Latexify.jl/pull/137)?

cc @korsbo

**Comment by korsbo** [comment]
Yes but I did not want to pirate LaTeXStrings so it's not automatic - you have to call `render`.

```
latexify(:(x/y)) |> render
```

this works with latexify v0.14.8+. It uses html+mathjax in VSCode or a bunch of other things to generate an image and open it up if you're in a different environment.

**Comment by korsbo** [comment]
It would feel rather wrong to overload `Base.show(::IO, ::MIME"juliavscode/html", ::LaTeXString)` from within Latexify since I own neither the MIME nor the LaTeXString. I also sense a great deal of reluctance from LaTeXStrings.jl to implement any form of rendering at all. Would it make sense/be desirable to have such an overload here instead?

**Comment by korsbo** [comment]
I'll just ask in LaTeXStrings.jl again. This added support is much lighter than the proposed and rejected rendering https://github.com/stevengj/LaTeXStrings.jl/issues/43

**Comment by tpoisot** [comment]
> Doesn't this already work since [this PR got merged](https://github.com/korsbo/Latexify.jl/pull/137)?
> 
> cc @korsbo

Drats. I looked for relevant issues and missed this one.

**Comment by tpoisot** [comment]
I think that the solution using `render` is fine, so I'm happy to close unless the devs think there's value in adding a show method.
