### ISSUE TITLE
The llvmcall string will break syntax highlights.

### ISSUE THREAD

**Issue by SeniorCtrlPlayer** [julia-vscode/julia-vscode#2072]
![screenshot](https://user-images.githubusercontent.com/38762187/111909636-114fbd80-8a99-11eb-9ffd-669d999252a0.PNG)

After `"""` of `llvmcall` string, codes will be regarded as comments, syntax highlights can't work, but it can run without errors.

**Comment by pfitzseb** [comment]
Workaround for now is to use `$("""blah""")` instead of `$"""blah"""`.
