### ISSUE TITLE
Interpolation into command should count as variable usage

### ISSUE THREAD

**Issue by KristofferC** [julia-vscode/julia-vscode#2074]
![bild](https://user-images.githubusercontent.com/1282691/112130929-452a0080-8bc9-11eb-9307-dfb282ed8047.png)

`tarball_path` is claimed to be unused in the body.

**Comment by zerefwayne** [comment]
@pfitzseb I would like to take a look into this issue.

**Comment by zerefwayne** [comment]
I think this issue is a redundant one, #1654 is already open with the same problem.

**Comment by zerefwayne** [comment]
On inspection, I think the issue needs to be fixed in this function:

https://github.com/zerefwayne/StaticLint.jl/blob/e49b0908d8021ef5c72013e3b0fbe05f2ffed684/src/linting/checks.jl#L495-L513
