### ISSUE TITLE
Module with docstring doesn't allow in-module eval

### ISSUE THREAD

**Issue by baggepinnen** [julia-vscode/julia-vscode#2078]
From slack:

Lately, vscode evaluates the whole module if I have my cursor on a line inside the module definition. Has it always been like that? It causes the module to be replaced and all code using it breaks and I have to restart.

 I have configured my keymap and used the same for six months so I'm confident that when I pres ctrl-enter it should evaluate the current line/block. It appears as if a module is treated as a single block now

**Comment by pfitzseb** [comment]
I can't repro this on 1.1.37. Can you share a screenshot/gif of what's going on?

**Comment by baggepinnen** [comment]
If I place the cursor anywhere inside the module defined in https://github.com/baggepinnen/Robotlib.jl/blob/master/src/Frames.jl and hit *execute code in repl` it evaluates the whole module instead of the line/block the cursor is at. 
If I try to simplify the example down to
```julia
module Mod
a = sin(1)
end
```
in a new file and evaluate the line `a = sin(1)` it does what I expect, only evaluates that particular line.

**Comment by pfitzseb** [comment]
Seems like the docstring is the issue.
