### ISSUE TITLE
Improved code jumping and auto-completion

### ISSUE THREAD

**Issue by zerefwayne** [julia-vscode/julia-vscode#2084]
Coming from a background of TypeScript and Golang where the <kbd>Ctrl+Enter</kbd> works so flawlessly, I noticed we don't have similar code jumping available in Julia. Also, the auto-completion is unavailable when module is not directly imported in a Julia file.

![image](https://user-images.githubusercontent.com/28949397/112744142-f27e8900-8fba-11eb-80b6-e49579abe077.png)

In the above scenario, since we are already `using` the `models.jl` in the module, we don't need to add it to the `methods.jl` file since it will be available at the runtime. Now the problem arises during code jumping because VS Code doesn't know where the `Car` comes from.

The main problem arises here because of a different style of code import than other languages. Since we don't use explicit `export` and `import` like TS, it can be quite difficult to track the source of a variable.

I think this can be a pretty handy feature because I needed frequent code jumping, eg. while working on Geometry related Projects.

**Comment by zerefwayne** [comment]
A possible solution:

1. Create an entire tree of the project from the `include`, `import`, `using` statements.
2. In each node of the tree, list out all the variables and functions available for exporting.
3. To look at the definition of a variable, we just search the tree in the direction of the root to find the required definition.

This process might also help us in [tree-shaking](https://github.com/julia-vscode/julia-vscode/issues/2081) the project.

**Comment by pfitzseb** [comment]
This is what we're doing already. Do you have a specific failure case?

Also note that it should be `include("models.jl")` etc, not `using("models.jl")`.

**Comment by zerefwayne** [comment]
It seems to be working correctly now. Maybe there were some issues while I was working with Makie. Closing this issue.
