### ISSUE TITLE
Variable declaration in @testset causes function of same name to be highlighted as invalid.

### ISSUE THREAD

**Issue by lassepe** [julia-vscode/julia-vscode#2085]
The language server does not seem to recognize that variables defined in a `@testset` are local to the test set scope.
In the example blow, the function definition `foo` is shown as erroneous with the error message
```
Cannot define function ; it already has a value.Julia(Julia)
```
```julia
using Test: @test, @testset

@testset begin
    foo = 1
    @test foo == 1
end

function foo()
    println("asdf")
end
```

**Comment by dpinol** [comment]
@lassepe did you do anything special to enable vscode linting in your test folder?
I get linting under src, but not under test

**Comment by lassepe** [comment]
@dpinol that just works for me. I just tried again and linting in the `test` folder never caused any issues.

That said, I cannot reproduce the original issue anymore, it now does what it should so. Thus I'll close this one.
