### ISSUE TITLE
problem in getting input

### ISSUE THREAD

**Issue by rahmani-hossein** [julia-vscode/julia-vscode#2088]
hi,
I am a freshman in Julia. after installing Julia and vs code, I cant get inputs from the terminal of vs code.
but surprisingly after I print sth I can get inputs and all my lines run. (the difference is shown in the picture ).
I use Julia 1.05.
I really need your help.
thanks
![Screenshot (21)](https://user-images.githubusercontent.com/61795938/112974568-dcfa9200-9167-11eb-8ab7-629a71d57f12.png)
![Screenshot (22)](https://user-images.githubusercontent.com/61795938/112974596-e3890980-9167-11eb-89c4-ca803fd3da1e.png)

**Comment by pfitzseb** [comment]
This is a known issue: https://github.com/julia-vscode/julia-vscode/issues/1529

Don't run `readline` via inline evaluation or the debugger. Only run it in the REPL.
