### ISSUE TITLE
Problems calling PyPlot objects from Julia under REPL

### ISSUE THREAD

**Issue by Mars2026** [julia-vscode/julia-vscode#2092]
I wanted to create a simple x-y axis plot from Julia's REPL interface, as demonstrated in the textbook 'The Julia Handbook'. My coding:

using IJulia, PyPlot
...
display(Plot(xaxis,yaxis))  # 2 arrays with11 elements

Julias answer:  
1-element Vector(PyCall.PyObject):
PyObject <matplotlib.lines.Line2D object at 0x0000000045524|>

Julia does not specify an error, it looks like the objects are known. 
Is it a missing path or environment variable ?
P.S.: I read on the web about some similar problems but without helpful solutions.

**Comment by Mars2026** [comment]
Additional info:
The error occurs only within "Visual Studio Code".
If I call the Julia program with include("main.jl") directly from the REPL terminal, the plot appears as desired. But of course this is not a solution.

**Comment by pfitzseb** [comment]
Only `Figure`s are showable, so something like `scatter(1:3, rand(3)); gcf()` should work fine.
