### ISSUE TITLE
Inline evaluation of a line ending with a semicolon displays output

### ISSUE THREAD

**Issue by dpsanders** [julia-vscode/julia-vscode#2093]
Inline evaluation of a line ending with a semicolon displays output both inline and on the terminal.
I would expect both outputs to be suppressed by the semicolon.

Julia extension 1.1.38; MacOS; Julia 1.6

**Comment by pfitzseb** [comment]
This got fixed in https://github.com/julia-vscode/julia-vscode/pull/2409.
