### ISSUE TITLE
is there a way to force "ctrl enter" to ensure I'm not in a non-julia REPL 

### ISSUE THREAD

**Issue by anandijain** [julia-vscode/julia-vscode#2099]
```
{
  "key": "ctrl+enter",
  "command": "language-julia.executeJuliaCodeInREPL",
  "when": "editorTextFocus && editorLangId == 'julia'"
}
```
I often execute some code to find im in `Pkg>`, and it's awkward to escape.

**Comment by pfitzseb** [comment]
Use Alt-Enter instead. The current Ctrl-Enter command is a relict of the past and basically just a workaround for the slow LS startup, which causes Alt-Enter to be unresponsive initially.
