### ISSUE TITLE
No intellisense for stdlib

### ISSUE THREAD

**Issue by lucidfrontier45** [julia-vscode/julia-vscode#2100]
Problem
------

No autocompletion for stdlib package.

Environment
-------

OS : Windows 10, Ubuntu 20.04
Julia : 1.6.0
VSCode : 1.55.0
Plugin : 1.1.38

How to reproduce
---------

1. create a black Project.toml
2. In the bottom bar of VSCode, choose Julia env of the current directory 
3. create a black file such as test.jl
4. Type `using LinearAlgebra`
5. Type `det`

I expected that candidates will be suggested In the section of 4 and 5 of the above procedure but they weren't.

Note
-------

After adding `LinearAlgebra` to the Project.toml by pkg mode, the intellisense worked correctly.

**Comment by pfitzseb** [comment]
This is by design. You won't be able to load `LinearAlgebra` in your project if it's not in Project.toml, although there is an exception for interactive use.
