### ISSUE TITLE
Language Server not starting on Linux after Julia v1.6 update

### ISSUE THREAD

**Issue by twfroelich** [julia-vscode/julia-vscode#2103]
Hello, I've recently tried to update from Julia v1.5.3 to v1.6 but ran into issues trying to load the Language Server with the error message included below. I can change the executable path back to julia v1.5.3 and it will compile and run without issue but switching back causes it to crash. I can still run Julia v1.6 from the command line so I believe that my installation is not corrupted. 

System Info
vscode v1.50.1
CentOS 7
Julia v1.6

[ Info: Starting the Julia Language Server
ERROR: LoadError: KeyError: key :_apply_latest not found
Stacktrace:
  [1] getindex
    @ ./dict.jl:482 [inlined]
  [2] getindex
    @ ~/.vscode/extensions/julialang.language-julia-1.0.10/scripts/packages/SymbolServer/src/symbols.jl:20 [inlined]
  [3] load_core()
    @ SymbolServer ~/.vscode/extensions/julialang.language-julia-1.0.10/scripts/packages/SymbolServer/src/symbols.jl:467
  [4] top-level scope
    @ ~/.vscode/extensions/julialang.language-julia-1.0.10/scripts/packages/SymbolServer/src/SymbolServer.jl:203
  [5] include
    @ ./Base.jl:386 [inlined]
  [6] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
    @ Base ./loading.jl:1213
  [7] top-level scope
    @ none:1
  [8] eval
    @ ./boot.jl:360 [inlined]
  [9] eval(x::Expr)
    @ Base.MainInclude ./client.jl:446
 [10] top-level scope
    @ none:1
in expression starting at /home/twfroelich/.vscode/extensions/julialang.language-julia-1.0.10/scripts/packages/SymbolServer/src/SymbolServer.jl:1
ERROR: LoadError: Failed to precompile SymbolServer [cf896787-08d5-524d-9de7-132aaa0cb996] to /home/twfroelich/.vscode/extensions/julialang.language-julia-1.0.10/scripts/languageserver/julia_pkgdir/compiled/v1.6/SymbolServer/jl_iYJPXZ.
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:33
  [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::Base.PipeEndpoint, internal_stdout::Base.PipeEndpoint)
    @ Base ./loading.jl:1360
  [3] compilecache(pkg::Base.PkgId, path::String)
    @ Base ./loading.jl:1306
  [4] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:1021
  [5] require(uuidkey::Base.PkgId)
    @ Base ./loading.jl:914
  [6] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:901
  [7] include
    @ ./Base.jl:386 [inlined]
  [8] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
    @ Base ./loading.jl:1213
  [9] top-level scope
    @ none:1
 [10] eval
    @ ./boot.jl:360 [inlined]
 [11] eval(x::Expr)
    @ Base.MainInclude ./client.jl:446
 [12] top-level scope
    @ none:1
in expression starting at /home/twfroelich/.vscode/extensions/julialang.language-julia-1.0.10/scripts/packages/LanguageServer/src/LanguageServer.jl:1
\u250c Warning: Some Julia code in the VS Code extension crashed with
\u2502   e = Failed to precompile LanguageServer [2b0e0bc5-e4fd-59b4-8912-456d1b03d8d7] to /home/twfroelich/.vscode/extensions/julialang.language-julia-1.0.10/scripts/languageserver/julia_pkgdir/compiled/v1.6/LanguageServer/jl_YWxNB1.
\u2514 @ Main ~/.vscode/extensions/julialang.language-julia-1.0.10/scripts/error_handler.jl:5
ERROR: Failed to precompile LanguageServer [2b0e0bc5-e4fd-59b4-8912-456d1b03d8d7] to /home/twfroelich/.vscode/extensions/julialang.language-julia-1.0.10/scripts/languageserver/julia_pkgdir/compiled/v1.6/LanguageServer/jl_YWxNB1.
Stacktrace:
 [1] top-level scope
   @ ~/.vscode/extensions/julialang.language-julia-1.0.10/scripts/languageserver/main.jl:37
[Info  - 10:22:22 AM] Connection to server got closed. Server will restart.

**Comment by pfitzseb** [comment]
That version of the extension isn't compatible with Julia 1.6. You'll need to update your version of VSCode to get the newest extension.
