### ISSUE TITLE
@__DIR__ differs for ctrl-enter and shift-enter

### ISSUE THREAD

**Issue by tbenst** [julia-vscode/julia-vscode#2104]
When in a project where a script is in a subdirectory, the value of `@__DIR__` changes based on if you execute the cell, or copy line to REPL. I find this very confusing, as it's the only example I've come across where shift-enter and ctrl-enter give a different value.

I believe the REPL (and ctrl-enter) is "correct" by giving the path to project directory. shift-enter instead gives path to parent folder of script.

**Comment by pfitzseb** [comment]
Well, `@__DIR__` in the REPL just gives you `pwd()`, so it's completely unrelated to the currently open file. The behaviour of Shift-Enter (and Alt-Enter)  is consistent with what you'd get when e.g. `include`ing the file, where `@__DIR__` is the parent of the current `@__FILE__`.

As an aside, I'd heavily recommend using Alt-Enter in place of Ctrl-Enter to execute a single line/block of code. The current Ctrl-Enter implementation is bad and will hopefully be deprecated soon.

**Comment by fbanning** [comment]
> I believe the REPL (and ctrl-enter) is "correct" by giving the path to project directory. shift-enter instead gives path to parent folder of script.

I agree with this sentiment.

**Comment by tbenst** [comment]
Thanks for the explanation. Alt-Enter and Shift-Enter still have different values for `@__DIR__`, though. I often step through a cell line-by-line when debugging, and it's confusing for values to change. IMHO running line-by-line in a cell or running the whole cell should have the same output--this is the experience for VScode Python as well as predecessors like Atom's Hydrogen.

**Comment by pfitzseb** [comment]
Hm, executing a code block and a cell produces the same result for me:
![Peek 2021-04-15 21-27](https://user-images.githubusercontent.com/6735977/114927166-7b0d7e00-9e31-11eb-86fc-c8f21d1eca26.gif)

**Comment by tbenst** [comment]
Ah, you're correct. I missed this due to a different subtle bug with `Execute Code in Cell and Move` (I think that's default for `alt-Enter` unless I had already changed) and `@__DIR__`
![Peek 2021-04-15 16-30](https://user-images.githubusercontent.com/863327/114950558-33bec780-9e08-11eb-8eeb-25b551f9bb9c.gif)

**Comment by pfitzseb** [comment]
Yeah, that's why I used `@__DIR__()` in the example above.

**Comment by sboukortt** [comment]
On Windows, it seems that the macro is replaced with a string containing unescaped backslashes, resulting in invalid escape sequences (`"D:\Pictures\Photos\..."` instead of `"D:\\Pictures\\Photos\\..."` or `"D:/Pictures/Photos/..."`).

**Comment by sboukortt** [comment]
(Sorry, I previously left a comment but it was a manipulation error on my part, please disregard this.)
