### ISSUE TITLE
Inconsistency when including files

### ISSUE THREAD

**Issue by fbanning** [julia-vscode/julia-vscode#2105]
```julia
# path/to/test/test.jl

cd("path/to/file") do
    include("file.jl")
end
```

Works as expected by sending it to the REPL via `Ctrl + Enter` but fails when executing it via `Shift + Enter`.
Why is that the case?

**Comment by pfitzseb** [comment]
Dup of https://github.com/julia-vscode/julia-vscode/issues/2104.
