### ISSUE TITLE
Linter does not recognize use of variable called "type" in interpolation

### ISSUE THREAD

**Issue by yha** [julia-vscode/julia-vscode#2112]
Here
```
f(type) = "$type"
```
`type` is marked by the linter as unused. This does not happen with other variable names (but does happen with a variable called `abstract`).

**Comment by racinmat** [comment]
The same thing happens to me even with different variable names.
![image](https://user-images.githubusercontent.com/5525771/115844904-97587e80-a420-11eb-95da-e76147ab9b91.png)

**Comment by pfitzseb** [comment]
The second one is fixed by https://github.com/julia-vscode/CSTParser.jl/pull/267. I also can't repro the original issue on master, so I suspect it's gotten fixed since the last release.
