### ISSUE TITLE
julia.executablePath as a workspace setting

### ISSUE THREAD

**Issue by ettersi** [julia-vscode/julia-vscode#2113]
The VS Code Julia extension currently does not allow to use  `julia.executablePath` as a workspace setting. Any chance this can be changed?

Being able to specify the Julia executable on a per-project level would be helpful to work with old, rarely used projects which might need an outdated Julia version, and it would also be helpful for developing Julia itself where we want to use the most recent, potentially unstable build.

**Comment by pfitzseb** [comment]
No, unfortunately we can't because of security issues.

**Comment by jtrakk** [comment]
> No, unfortunately we can't because of security issues.

Could you expand on that?

**Comment by davidanthoff** [comment]
@jtrakk take a look at https://github.com/microsoft/vscode/issues/106488, the scenarios that are addressed by that work are essentially the reason we disabled this in our extension for now. Once VS Code has trusted workspaces we can most likely reenable this feature in a secure way.
