### ISSUE TITLE
Function with optional keyword arguments complained about by linter as possible method call error

### ISSUE THREAD

**Issue by kapple19** [julia-vscode/julia-vscode#2115]
![call_error_issue](https://user-images.githubusercontent.com/48305293/115671397-ce318480-a38d-11eb-9ceb-2c3e40faca1d.png)

Adding to the list of issues on the false positives of "possible method call error." I've checked the others and I don't think this one falls into any of the other categories of reported issues. If I'm wrong, please correct me.

**Comment by pfitzseb** [comment]
This got fixed by https://github.com/julia-vscode/StaticLint.jl/pull/272. The fix will be in the next release.
