### ISSUE TITLE
Julia kernel not respecting environment selection

### ISSUE THREAD

**Issue by deoradh** [julia-vscode/julia-vscode#2127]
Brief: This is a problematic bit of UI interaction with VSCode's Jupyter support, and probably *also* involves IJulia.  See initial discussion at https://github.com/microsoft/vscode-jupyter/issues/5666. The TLDR is that the environment selector is not respected by the notebook interface.  It should either be disabled in that environment and guidance created for users to make use of environments, or the kernelspec adapted to make use of it by maybe passing the -e flag (but not destructively -- consider different notebooks opened to different environments).

Really, I just want the 2-3 groups here to coordinate :)

## Environment data

-   VS Code version: 1.56.0-insider (also non-insider build)
-   Jupyter Extension version (available under the Extensions sidebar): 2021.6.790799743
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: Win10 21H1 (19043.962)
-   Python and/or Anaconda version: (Conda pkg from Julia)
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A?
-   Jupyter server running: Local

## Expected behaviour

When using a Julia notebook, having selected a Julia environment, available packages should reflect that environment, and adding/removing packages should affect only that environment.

## Actual behaviour

Only the default (eg, "v1.6") environment is used.  The selected environment is indexed, but commands are not run against it.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Install Julia
2. In Julia: `import Pkg`
3. `Pkg.add("IJulia")`
4. `Pkg.add("Conda")`
3. `import Conda; Conda.add("ipython")`
4. `]` to get to Pkg mode, prompt should reflect v1.6 environment
5. `build`
6. (At this point, I believe Jupyter kernel should now be available for connection)
7. still in Pkg mode: `activate cas`
8. (At this point a new environment folder has been created)
9. `add SymPy`
10. (At this point, cas environment, not the v1.6 environment, should have SymPy installed.  Verify with st command.)
11. In VSCode, add new notebook, set for Julia.  
12. `1+1` (should return `2`)
13. `using SymPy` (returns LoadError -- this is expected)
14. select cas environment via UI in status bar .. probably located under user folder 
15. `using SymPy` (returns LoadError -- this is the problem)
16. Open new Julia shell. Type `]` for Pkg mode. Prompt should show v1.6 environment.
17. `st` to confirm SymPy not present
18. `add SymPy`; verify with `st`
19. Repeat starting at (11). Lines 13 and 15 should both succeed.  `@vars x y` should return `(x, y)`
20. while in the cas environment in VSCode, `import Pkg; Pkg.remove("SymPy")` 
21. In Julia shell's Pkg mode, `st` should now show SymPy removed from v1.6 environment, yet remains in cas environement.  This is the problem, again.

## Logs

<details>

<p>

```
> ~\AppData\Local\Programs\Julia-1.6.1\bin\julia.exe -i --color=yes --project=@. ~\.julia\packages\IJulia\e8kqU\src\kernel.jl ~\AppData\Local\Temp\tmp-26076Hwwked5aynhv.json
cwd: ~\AppData\Local\Programs\Microsoft VS Code Insiders
```

</p>
</details>

**Comment by davidanthoff** [comment]
Yeah, I'm going to close this for now, I have a list of things to fix for the notebook integration and this is part of that. I also should have a bit more time to finish this now, my semester is over.
