### ISSUE TITLE
Linter not detecting errors

### ISSUE THREAD

**Issue by otobrzo** [julia-vscode/julia-vscode#2132]
I really like VScode julia extension, but I am not able to get behaviour from your example [here](https://www.julia-vscode.org/)

particularly:

![screenshot_error](https://user-images.githubusercontent.com/16555995/116666228-02fb9800-a99b-11eb-8506-e470408adc79.png)

For me the missing definition of variables is not working

<img width="1136" alt="Snímek obrazovky 2021-04-30 v 9 55 17" src="https://user-images.githubusercontent.com/16555995/116666316-1ad31c00-a99b-11eb-9863-7f9d22c274a6.png">

Julia extension version 1.1.38
Julia 1.6
VS Code 1.55.2

**Comment by pfitzseb** [comment]
Your example works fine for me:
![image](https://user-images.githubusercontent.com/6735977/116667521-9386a800-a99c-11eb-8da4-c080b972b60d.png)
Can you check whether you have the `julia.lint.missingrefs` setting set to `none`?

**Comment by otobrzo** [comment]
Yes it is set to `none`

**Comment by pfitzseb** [comment]
Then I'd suggest trying `all` and restarting VSCode.

**Comment by otobrzo** [comment]
Thank you very much for solving this problem.
