### ISSUE TITLE
Plot in VSC differs from Plot in Julia REPL

### ISSUE THREAD

**Issue by ptoche** [julia-vscode/julia-vscode#2133]
Plot in VSC differs from Plot in Julia REPL

    using Plots

    function f(x,y) :: Float64
        (x^(1-y)-1)/(1-y)
    end

    default(xlims = (0,1), ylims = (-10, 1))

    plot()
    plot!(x -> f(x, 2), 0, 1) 
    plot!(x -> f(x, 5), 0, 1) 

**REPL:**

<img width="671" alt="c" src="https://user-images.githubusercontent.com/6339274/116666992-7f1cbe00-a950-11eb-8415-eb4b6982800f.png">

**VSC:**

<img width="1145" alt="d" src="https://user-images.githubusercontent.com/6339274/116666999-817f1800-a950-11eb-907b-45c32dbc0f2a.png">

<img width="241" alt="a" src="https://user-images.githubusercontent.com/6339274/116667176-bc814b80-a950-11eb-89aa-094dda1b660f.png">

<img width="261" alt="b" src="https://user-images.githubusercontent.com/6339274/116667351-ef2b4400-a950-11eb-8cad-9afb9c9481c0.png">

Plots v1.13.2

**Comment by pfitzseb** [comment]
I can't repro the issue:
![image](https://user-images.githubusercontent.com/6735977/116668763-0cd2ca80-a99e-11eb-971e-ed44ba201e3f.png)

Generally seems like more of a Plots/GR issue than an issue with the extension -- we're just displaying an image exported by the plotting library after all.

**Comment by ptoche** [comment]
Oh. How could I debug this? Any suggestion? Thanks.

**Comment by ptoche** [comment]
For completeness, here's the output `Atom`:

<img width="571" alt="a" src="https://user-images.githubusercontent.com/6339274/116687589-4984ce80-a96a-11eb-9d06-9e3946bdab48.png">

I also tried with `IntelliJ`, but it invokes `GKS QtTerm` so the output is the same as the Julia REPL.

**Comment by pfitzseb** [comment]
Is it possible that VSCode calls a different version of GR/Plots than the other environments?

**Comment by ptoche** [comment]
Something like that must be going on. Is there a way for me to check that? `Pkg.status("GR")` gives the same answer in both the REPL and VSCode. Any way I can track what's happening? Thanks! (will be offline for a few hours now).

**Comment by pfitzseb** [comment]
Sorry, no idea what's going on here then. You might have better luck asking on Slack/Discourse or the Plots/GR repos.

**Comment by ptoche** [comment]
The issue is specific to vscode, as it doesn't happen with the Julia REPL or atom. Is there a way to debug which image exported by the plotting library you are exporting? Do you have a debugging tool that you'd recommend? Thanks.

**Comment by pfitzseb** [comment]
All that VSCode is doing is calling `stringmime` on the plot, so you can check what:
```
using Plots, Base64
function f(x,y) :: Float64
    (x^(1-y)-1)/(1-y)
end

default(xlims = (0,1), ylims = (-10, 1))

p = plot()
plot!(x -> f(x, 2), 0, 1) 
plot!(x -> f(x, 5), 0, 1) 

stringmime(MIME"image/svg+xml"(), p)
stringmime(MIME"image/png"(), p) # base64 representation
```
produces for you and whether it reproduces the issue you see.

**Comment by ptoche** [comment]
I did not understand what to do with `stringmime`, but with 

    using Debugger
    Debugger.@enter plot, etc.

I was able to track the version of `Plots` used: 

    name = "Plots"
    uuid = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
    author = ["Tom Breloff (@tbreloff)"]
    version = "1.13.2"

**Comment by pfitzseb** [comment]
Ok, just run 
```
using Plots, Base64
function f(x,y) :: Float64
    (x^(1-y)-1)/(1-y)
end

default(xlims = (0,1), ylims = (-10, 1))

p = plot()
plot!(x -> f(x, 2), 0, 1) 
plot!(x -> f(x, 5), 0, 1) 

file = tempname()*".html"
open(file, "w") do io
    write(io, stringmime(MIME"image/svg+xml"(), p))
end
println("Open `$(file)` in a browser to check the plot!")
```
and follow the instructions printed in your terminal.

**Comment by ptoche** [comment]
Thanks a lot Sebastian!

https://pastebin.com/gxw1ZMuf

<img width="607" alt="a" src="https://user-images.githubusercontent.com/6339274/117655482-fd950f00-b14b-11eb-92a5-b9e721c93976.png">

**Comment by pfitzseb** [comment]
Right, so it definitely isn't an issue with the VSCode extension. Probably best to open an issue over at Plots.jl (feel free to ping me there as well).

**Comment by ptoche** [comment]
Got it, thanks Sebastian!
