### ISSUE TITLE
reading txt file

### ISSUE THREAD

**Issue by rahmani-hossein** [julia-vscode/julia-vscode#2140]
i faced something strange when I create a file and writing sth(by hand) in it I can read it with readdlm and there isn't any problem .but when i want to read a txt file on my desktop it says to me there isn't anything inside the file (with readdlm an error "LoadError: at row 0, column 0 : ArgumentError("number of rows in dims must be > 0, got 0")")
it's my file 
[blobs.txt](https://github.com/julia-vscode/julia-vscode/files/6413635/blobs.txt)

thanks for your helping.

**Comment by pfitzseb** [comment]
This doesn't seem to be related to the VSCode extension. Please ask general Julia usage question on Slack or Discourse instead.
