### ISSUE TITLE
condition breakpoints might not be working

### ISSUE THREAD

**Issue by lewisl** [julia-vscode/julia-vscode#2145]
I have a variable that is incremented I a loop: ```overall count += 1```

At this line I create a breakpoint and then edit it to have the expression: ```overallcount >= 10```

I am pretty sure that this condition will be met because I can step through a simple breakpoint until it is met.

I think the problem is that the debugger gets corrupted. It doesn't start properly and NO breakpoint works.  The Julia Evaluating spinner in the status line is going but no breakpoint is reached.  SEE NEXT POST: hard to reproduce problems associated with compiled mode and the Julia server still processing whatever it processes.

The only way to cleanse the debugger is to quit VS Code, restart it and then run the debugger.  AFTER DOING THIS SEVERAL TIMES, things settled down.

It seems that the debugger auto-creates configs and these configs may be wrong. Rather than auto creating anything (which could be nice--then I don't have to), the user should be notified and given the chance to confirm the config.

It is also a bit mysterious how to get rid of them so that the debugger starts cleanly./

I was really liking the experience until I created an expression breakpoint. Since then, it plain doesn't work.

**Comment by lewisl** [comment]
It's too flaky to reproduce.  If I restart the debugger and not in compiled mode with an ordinary breakpoint, it works. I can then edit that breakpoint to be an expression.  

I think the problem was since I wanted the code to run a while before stopping I used compiled mode.  I'd guess that compiled mode doesn't like expression breakpoints and that compiled mode can leave the debugger in some weird state.

So, I won't use compiled mode for a while and will go through the code in smaller chunks. Still useful.

**Comment by lewisl** [comment]
Well, I spoke to soon.  After the breakpoint was reached at ```overall count >= 20``` I tried to edit it (while stopped) to ```overall count >= 200```. 

I got ```[invokeFunction] unknown service 'privateBreakpointWidgetService'```

Not clear what that could mean.  Apparently once set, expression breakpoints can't be changed within a given debugging session.  Time to restart again.

**Comment by pfitzseb** [comment]
- Compiled mode disables any and all breakpoints.
-  `[invokeFunction] unknown service 'privateBreakpointWidgetService'` very much sounds like a VSCode issue which I can't repro. What VSCode version are you on?
- Changing the breakpoint condition in fact does not seem to work atm. Will fix.

**Comment by lewisl** [comment]
Thanks for taking a look.

Guess I should read the doc about compiled mode. Pretty useless w/o any breakpoints. Can’t see watches or stop and look at variables. I thought it used to honor simple breakpoints.

My version of VS Code is:
Version: 1.56.0
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:06:21.189Z (2 days ago)
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.3.0

Changing breakpoint condition working or not is inconsistent. I am glad you could find the conditions where you could repro it.

Generally, I like the debugger. I rarely use it, generally struggling to understand what-the-heck my good is doing. I used to avoid the debugger because from old Atom days it seemed hard to set up usefully.  Now it is easy. Just set a breakpoint so it stops once. Run it. Move breakpoints to more useful places. Continue. The condition breakpoints are useful when the error I am looking for is dependent on input data conditions—I can zero in on when and where the “bad stuff” happens.

From: Sebastian Pfitzner ***@***.***>
Reply-To: julia-vscode/julia-vscode ***@***.***>
Date: Friday, May 7, 2021 at 12:50 AM
To: julia-vscode/julia-vscode ***@***.***>
Cc: Lewis Levin ***@***.***>, State change ***@***.***>
Subject: Re: [julia-vscode/julia-vscode] condition breakpoints might not be working (#2145)


  *   Compiled mode disables any and all breakpoints.
  *   [invokeFunction] unknown service 'privateBreakpointWidgetService' very much sounds like a VSCode issue which I can't repro. What VSCode version are you on?
  *   Changing the breakpoint condition in fact does not seem to work atm. Will fix.

**Comment by davidanthoff** [comment]
So I think there is nothing todo here at the moment, right? Closing for now.
