### ISSUE TITLE
shift+enter

### ISSUE THREAD

**Issue by aloispichler** [julia-vscode/julia-vscode#2151]
Starting code executing with
`shift+enter` immediately moves the cursor to the end of the file, even if the program did not terminate and irrespective, if errors occurred or not.
However, most certainly the user just wants to continue working at the line where code execution was started from with `shift+enter`; so not to move the cursor is the most preferred option. Is that possible?

Thank you :-)

**Comment by pfitzseb** [comment]
Yes, just use the `language-julia.executeCell` command (or re-bind Shift-Enter to that command).

**Comment by aloispichler** [comment]
Awesome, I did not know that. It works.
Thank you!

**Comment by xgdgsc** [comment]
Can' t fix the default moving to file end behavior?
like 
```
##
a = 1




## 123
## 234
```
it would go to the end.
