### ISSUE TITLE
Different behavior depending on how code is excecuted

### ISSUE THREAD

**Issue by KronosTheLate** [julia-vscode/julia-vscode#2152]
I want to include a local file in my script, and I do this with the `include` function:
`include("../D_funcs.jl")`

When I execute this line with hotkey A assigned to `language-julia.executeCodeBlockOrSelection`, the file is included no problem.

When I send the same line to the REPL with hotkey B assinged to `language-julia.executeJuliaCodeInREPL`, I get the following error:
`ERROR: SystemError: opening file "PathToFile\\D_funcs.jl": No such file or directory`. From the path, it is clear that the file is being looked for 1 level up from where it is.

Pressing hotkey B when selecting `include("./D_funcs.jl")`, with one less `.`, works fine. But exceuting `include("./D_funcs.jl")` , with one less `.` and with hotkey A, results in looking for `D_funcs.jl` at one level too deep.

This difference only occurs when the file I am working from is inside a folder, and the folder is located on the same level as `D_funcs.jl`. When the file I am working from is in the same level as `D_funcs.jl`, `include("./D_funcs.jl")` work with both hotkeys. 

This means that depending on how I want to excecute the code, I have to use different code. This is inconvenient, and I am guessing that this behavior is not intentional. Can be be fixed, to behave in the same way with the different ways of excecuting code?

**Comment by pfitzseb** [comment]
This absolutely is intentional. 
The REPL expands the path relative to `pwd()`, while in an editor it is expanded relative to the file's path. 

I'd recommend not using `executeJuliaCodeInREPL` at all, fwiw.

**Comment by KronosTheLate** [comment]
If it is intentional, then case closed. But why would one want different behaviour for two different ways of executing code?

The only reason I use `executeJuliaCodeInREPL` is because the other way of evaluating can take something like a minute the first time, and occasionally stops working. I am not able to reproduce the second issue, and the first issue is occasionally not an issue. So I don't know what could be done about it.

**Comment by pfitzseb** [comment]
`executeJuliaCodeInREPL` literally copy-pastes the code into the REPL. So that just needs to be consistent with what the REPL does.
