### ISSUE TITLE
Incorrect indentation

### ISSUE THREAD

**Issue by laborg** [julia-vscode/julia-vscode#2158]
When formatting following piece of code with the vscode Julia extension 1.1.40 the last `ref` doesn't get indented.
```
"""
    ^[a-z0-9_]{3,30}\\\$
    ["^[a-z0-9_]{3,30}\\\$"],
"""
struct A
    x
end

struct Anomaly
    ref
end
```
formats to 
```
"""
    ^[a-z0-9_]{3,30}\\\$
    ["^[a-z0-9_]{3,30}\\\$"],
"""
struct A
    x
end

struct Anomaly
ref
end
```

(If I remove the first line of the comment, the `x` isn't indented...)

**Comment by pfitzseb** [comment]
Should be fixed in the next version.
