### ISSUE TITLE
no auto completion when in template

### ISSUE THREAD

**Issue by xgdgsc** [julia-vscode/julia-vscode#2162]
When in the template mode generated by keywords like when you enter 

```
if 

end
```
by `if` `enter`, where you can press `tab` to jump through locations , the following type doesn' t trigger auto competion. You have to exit this mode with `esc` and type to trigger following auto completion.

**Comment by davidanthoff** [comment]
I'm not sure we can actually do something about this, it might be an upstream issue?

**Comment by pfitzseb** [comment]
You can hit `Ctrl-Space` to force the autocompletion popup to show, even in that context. So yeah, don't think there's anything wrong here on either side.

**Comment by xgdgsc** [comment]
But the cpptools extension works in this case. There must be someway to do it ?
