### ISSUE TITLE
Variable unused wrong for variables that shadow keywords / other variables

### ISSUE THREAD

**Issue by akosuas** [julia-vscode/julia-vscode#2165]
```
function foo(xs)
    a = 1
    for i in 1:10
        exponent = xs[i]
        a *= exponent
    end
    return a
end
```

In this example, the first instance of `exponent` is highlighted by the linter as "assigned but not used". 
It also happens for other built-in names. It seems to have something to do with the loop - removing the loop removes the warning.

**Comment by pfitzseb** [comment]
This seems to be fixed on master.
