### ISSUE TITLE
Plotting shifts focus on insider

### ISSUE THREAD

**Issue by korsbo** [julia-vscode/julia-vscode#2172]
Hi, when I plot something on the current insider (1.2) the focus shifts to the plot pane and I must mouse my way back to the buffer. 

Cheers!

**Comment by korsbo** [comment]
It seems to also open the "Plot navigator" in the sidebar. I did not notice on my big screen but it eats up valuable screen real-estate on my laptop.

**Comment by pfitzseb** [comment]
That part is intentional. Probably makes sense to add a setting for the navigator though.
