### ISSUE TITLE
[DOC] How to enable "latex completion in Julia VS Code"

### ISSUE THREAD

**Issue by Datseris** [julia-vscode/julia-vscode#2181]
Latex completions are an integral part of julia and should be accessible from the get-go in Julia VSCode, like they were in Atom. But even if they aren't available from the get-go, the docs should definitely state how to add them:

![image](https://user-images.githubusercontent.com/19669089/120172804-b4445680-c203-11eb-90f7-c5a5bed9ba48.png)

**Comment by pfitzseb** [comment]
They are available from the get-go though, at least in Julia files. If you don't get them then that's a bug.

**Comment by Datseris** [comment]
I do not :( 

![image](https://user-images.githubusercontent.com/19669089/120173119-008f9680-c204-11eb-863e-ffadfb16b6ea.png)

**Comment by Datseris** [comment]
What should I report to help solve this?

**Comment by pfitzseb** [comment]
Well, it looks like you're not getting *any* (of our) completions at all.
Can you open the the terminal pane (Ctrl-J), navigate to "Output" and select "Julia Language Server" form the dropdown? That should have a bunch of info. Also, do you get a "Language Server: Indexing..." message in the status bar? If so, then wait for that to finish.

**Comment by Datseris** [comment]
After downloading 1.2, restart VSCode, and letting the indexing do its work. It now works. However, it is unfortunate that I do not get to see the symbols before pressing tab:

![image](https://user-images.githubusercontent.com/19669089/120174413-5a449080-c205-11eb-8e26-b8f503c3097c.png)

In Atom this was a useful way to find "appropriate" unicode characters for a scenario.

**Comment by pfitzseb** [comment]
The latex symbol should be shown on the right:
![image](https://user-images.githubusercontent.com/6735977/120174639-98da4b00-c205-11eb-928f-987a089a9f5e.png)

or in the expanded auto-complete dropdown (which you can get by pressing Ctrl-Space);
![image](https://user-images.githubusercontent.com/6735977/120174699-ac85b180-c205-11eb-86bb-4df55d05e5a7.png)

**Comment by Datseris** [comment]
Thanks a lot, when using the arrow keys to go down, I can see each symbol on the right. Would be nice to autmatically display all of the though. Not sure why I'd have to scroll through then to see how the look. At the moment only the topmost unicode is displayed.

**Comment by davidanthoff** [comment]
Is there something we can improve here? Not clear to me...

**Comment by Datseris** [comment]
(only improvement would be that all latex completions show their rendering on the right side of the panel, not only the one selected. but this is unrelated with the original issue)
