### ISSUE TITLE
Follow-link on Julia stack traces in the terminal not working

### ISSUE THREAD

**Issue by marius311** [julia-vscode/julia-vscode#2184]
![image](https://user-images.githubusercontent.com/1510968/120232986-9843b380-c209-11eb-948d-2df18e2aac35.png)

Clicking the follow-link above doesn't work in the stack trace, but it does work if e.g. I type out `~/scratch.jl` in another terminal and click it.

**Comment by baggepinnen** [comment]
I have the same issue,
of these two links
``` 
 [5] top-level scope
   @ ~/repos/vibdamp-21/VibdampAnalysis/vibdamp_jet.jl:36
in expression starting at /home/fredrikb/repos/vibdamp-21/VibdampAnalysis/vibdamp_jet.jl:36
```
the second can be followed but not the first. The first has a `~`, and is also colored darker than the second, if that helps debug the issue
