### ISSUE TITLE
Julia window opening on every plot

### ISSUE THREAD

**Issue by NathanMagnan** [julia-vscode/julia-vscode#2189]
Hi !

I'm working with VS Code and its Julia extension (I'm quite new).

Since yesterday, I notice a strange behavior that also happens to be annoying: whenever I plot something, the JULIA window on the left of the IDE opens. I don't know what is the proper way to call these windows -- the following picture should explain what I mean:
![image](https://user-images.githubusercontent.com/57399545/120364711-dcb87780-c30d-11eb-8b06-072b423d347f.png)

My points is, yesterday this window did not pop up everytime I ploted something, and I liked it much better. I have no use for it and it takes a lot of space on my screen.

I don't remember making any change to my settings, so I really don't understand what causes this new behavior. So far I have tried (unsuccesfully) :
- To close and restart VS Code
- To desinstall - reinstall all packages linked to Plots.jl (Plots, GR, PlotlyJS, Colors)
- To desinstall - reinstall the Julia extension to VS Code
- To desintall - reinstall all of VS Code
- To shutdown and restart my computer

I'm on Windows 10 with VS Code 1.56.2, the Julia extension 1.2.1, Plots 1.15.2, PlotlyJS 0.14.1. Here is a minimal working example:
`using Plots`
`plot([1 2], [1 2])`

If you have an idea what I could do to solve this, I'd be very glad !

Thank you !

**Comment by NathanMagnan** [comment]
Hi again !

On my roommate suggestion, I tried to downgrade the Julia extension from version 1.2.1 (from yesterday) to version 1.1.40 (from 21 days ago). It works, the window doesn't pop up anymore.
I don't know if this observation helps ?

**Comment by pfitzseb** [comment]
Version 1.2.2 should be out in a few hours and introduces a setting for this.
