### ISSUE TITLE
Incorrect parser error marking in `for j in 1`

### ISSUE THREAD

**Issue by Datseris** [julia-vscode/julia-vscode#2193]
![image](https://user-images.githubusercontent.com/19669089/120637929-c75b5e80-c46f-11eb-9ff8-48946c93c123.png)

Even though the loop syntax `for j in 1` is perfectly valid for Julia this is highlighted as potential error.

**Comment by pfitzseb** [comment]
I'd argue that it's a good idea to draw attention to iterating over numbers, tbh.

**Comment by Datseris** [comment]
It is valid syntax though. I thought these annotations were supposed to point out to incorrect syntaxes, not be a style guide. (E.g. there aren't any annotations regarding spacing etc.)

From my perspective the syntax `j in 1` is extremely useful. It allows me to run a data analysis loop only for a specific field instead of all of them. The alternative is to comment out the `for` and then `end`, and put a `j = 1` above it. I'd much rather the first approach!

**Comment by Datseris** [comment]
EDIT: oh well, I see your point on how someone might write this by mistake.

**Comment by pfitzseb** [comment]
Blue underlines indicate a hint, as opposed to a warning (orange) or error (red). So this is basically a call to attention and not the linter saying "you did something wrong!".
