### ISSUE TITLE
Option to display documentation in documentation pane when clicking on function/item (like hover but doesn't disappear on move)

### ISSUE THREAD

**Issue by FishAres** [julia-vscode/julia-vscode#2194]
It would be great!

**Comment by pfitzseb** [comment]
The default short cut is `Alt-J Alt-D`, but you can get the same by right clicking and selecting `Julia: Show Documentation`.
AFAICT it's impossible to hook into VSCode's mouse event handling, so we can't change to e.g. Ctrl-Click or something like that (and I don't think it'd be a good idea either).
