### ISSUE TITLE
Debug does not stop at breakpoint

### ISSUE THREAD

**Issue by cirobr** [julia-vscode/julia-vscode#2197]
Hello,
Running with latest (as of June 2021) releases of Julia and VScode for Ubuntu Mate 20.04, when selecting a certain break point for debug and hitting F5, program runs and executes at once. Have also tried configuring "stopOnEntry": true on launch.json file: program stops at first line. However, when hitting the command to go to the next line, the debug simply breaks and exits
![Screenshot at 2021-06-06 17-13-52](https://user-images.githubusercontent.com/37887021/120938752-e1ed3c00-c6ea-11eb-8530-a812e6b4cce1.png)
![Screenshot at 2021-06-06 17-14-55](https://user-images.githubusercontent.com/37887021/120938754-e580c300-c6ea-11eb-8ef6-dfe189d90f87.png)

. Any fix for these isues? Thanks.

**Comment by pfitzseb** [comment]
Can't repro this. Is your file in the workspace? What happens when click the play button in the upper right and select "Julia: Debug File in New Process"?
