### ISSUE TITLE
external REPL executeJuliaCodeInREPL doesn't work, but executeCodeBlockOrSelection does

### ISSUE THREAD

**Issue by akosuas** [julia-vscode/julia-vscode#2203]
Hi, I'm trying the beta "connect to external REPL" feature. Sending code to the REPL with Alt+Enter works, but sending code with Ctrl+Enter doesn't. Both commands work when using the integrated REPL.

**Comment by pfitzseb** [comment]
That's by design.

**Comment by akosuas** [comment]
What's the rationale behind the design please?

**Comment by pfitzseb** [comment]
We have absolutely no control over the process/terminal you're using, so it's very difficult to send text to it. I'd recommend using `executeCodeBlockOrSelection` whenever possible; `executeJuliaCodeInREPL` is strictly less powerful once the language server is running.

**Comment by akosuas** [comment]
Thanks, got it. The main reason I use `executeJuliaCodeInREPL` is because it allows you to send the single line under the cursor, without having to explicitly highlight it. Perhaps there is a way to get that behavior using `executeCodeBlockOrSelection` that I'm missing?

**Comment by lrnv** [comment]
Same problem, same comprehension of the design choice, but same question here: Is there a way to execute line by line that we are missing ? I.e. get the same behavior regarding which lines are interpreted and cursor movements in the editor as we did with Ctrl+Enter ?
