### ISSUE TITLE
Feature request: switch between multiple persistent tmux sessions

### ISSUE THREAD

**Issue by palmtree2013** [julia-vscode/julia-vscode#2207]
I really appreciate the experimental persistent tmux session feature in the new update. However, sometimes I have to switch between different projects while the persistent tmux session always bring me to the same old session. If one uses `include("")` in the code,  the path in the newly opened project is not adapted in the old session and it gives error message.  Is there a way to start another tmux session and select which one to use at the beginning?

**Comment by pfitzseb** [comment]
Yes, just set `julia.persistentSession.tmuxSessionName` to something else. 

I thought about adding a dropdown that lets you select from all running sessions (`tmux ls`, maybe filtered by some criterion) or start a new one.

**Comment by palmtree2013** [comment]
Thanks, it worked perfectly! But if a dropdown feature is added it will be even better!

**Comment by xgdgsc** [comment]
It seems to support variables like `julia_vscode_${workspaceFolder}`

**Comment by pfitzseb** [comment]
Yep. I think this is the "correct" UX -- each tmux session can (optionally) be attached to e.g. a workspace.
