### ISSUE TITLE
Compiled Mode red button not turned off after a debug session

### ISSUE THREAD

**Issue by w-hc** [julia-vscode/julia-vscode#2219]
My VSCode environment
```
Version: 1.57.0
Commit: b4c1bd0a9b03c749ea011b06c6d2676c8091a70c
Date: 2021-06-09T17:22:31.215Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.4.0
```
and my julia-vscode version v1.2.3

When the compiled mode button is turned on, and after a debug session, I notice that
the debug button stays red, instead of being automatically turned off. 

At a subsequent debug session, the debugger enters in the normal `interpreted` mode, while the button is 
still red. This is incorrect?

I need to manually click the compiled mode button twice to re-enable it. 

The right behavior should be that the compiled button automatically goes off after a debug session ends.

**Comment by pfitzseb** [comment]
Red button does mean interpreted mode, yes. 

> The right behavior should be that the compiled button automatically goes off after a debug session ends.

Why is that? Imho nothing about this should be changed automatically ever.

**Comment by w-hc** [comment]
Hi @pfitzseb I wasn't clear in my language

debug session starts
T1 -- red button -- interpreted mode
T2 -- click, white button -- compiled mode
debug session ends
new debug session starts
T3 -- white button -- interpreted mode

At T3 there is an inconsistency. white button should mean compiled mode, but the debugger enters in interpreted mode. I know T3 is in interpreted mode cuz all inner breakpoints are active and speed is noticeably slow on an intensive loop.

**Comment by pfitzseb** [comment]
Ah, I see. I can't reproduce this, unfortunately.

Does this happen when debugging in a separate process or in the REPL (with `@enter`/`@run`)? If you can repro this in the latter case, try setting `ENV["JULIA_DEBUG"] = "all"` and paste the output of those two sessions here.

**Comment by w-hc** [comment]
This happens with using the `F5` button inside vscode itself.

**Comment by pfitzseb** [comment]
Ok, I see why this happens. Will fix. In the meantime, try the `language-julia.debugEditorContents` command instead.

**Comment by w-hc** [comment]
Thanks!
May I know how to use this button? I tried typing this into the command palette but nothing happens.

**Comment by pfitzseb** [comment]
I'd recommend opening the file you want to debug and then click the "play" button in the upper right. That should allow you to select the `Julia: Debug File in New Process` command.
