### ISSUE TITLE
Plot navigator gets focused every time when running display() and plot commands fail if Plot Navigator is disabled

### ISSUE THREAD

**Issue by NikEyX** [julia-vscode/julia-vscode#2220]
I understand that some people enjoy the plot navigator, but I'd rather want to keep it in the background. However, in the current version it pops into the sidebar every single time you plot something with display(). This is very annoying, as I prefer to have my sidebar focused on other tools.

I also tried "hiding" the Julia tab completely, but any time you plot, the whole thing comes automatically into view again, despite the caption still indicating that it's supposed to be hidden.

Disabling the Plot Navigator via checkmark in the Julia tab results in plots not being generated anymore, and old plots cannot be deleted anymore, showing this error: `Running the contributed command: 'language-julia.plotpane-delete' failed.`

This happens with all Julia VS Code plugin versions from 1.2.0 and up. Versions below that are unaffected and work as expected.

**Comment by pfitzseb** [comment]
There's a setting for disabling the navigator-autofocusing in 1.2.2 and up.

**Comment by anandijain** [comment]
<kbd>CTRL</kbd>+<kbd>,</kbd> and searching navigator-autofocusing didn't bring anything up, how do I find it?

**Comment by pfitzseb** [comment]
Should be `julia.usePlotNavigator` or similar.
