### ISSUE TITLE
Plots.jl: plots do not pop up if "Julia: Use Plot Pane" is disabled in the extension for VSCode

### ISSUE THREAD

**Issue by VivaldoMendes** [julia-vscode/julia-vscode#2234]
Hi,

I am on a Windows 10 machine, Julia v1.6.1, Julia for VSCode v1.2.5, Plots v1,6.8, and GR v0.52.0. I have these installed on two computers, and in both, I disabled the "Julia: Use Plot Pane" facility in the Julia extension settings.  In one computer, if I use Plots, PlotlyJS or PGFPlotsX, the plots pop up in the external window without any problem.  However, I have a problem with Plots on the other computer because the plots are (apparently) produced, but I can not find them anywhere. If I enable the "Julia: Use Plot Pane", no problem, here they are in the Julia Plot Pane. 

I have already `up` my environment, `build Plots` and `build GR`, but the problem persists. The only difference that I can spot between the two computers is that on the one that the problem above persists, when Plots is precompiled it appears a Glib_Gio_Warning stating that:

```
(process:5424): GLib-GIO-WARNING **: 22:19:40.951: Unexpectedly, UWP app `Evernote.Evernote_10.15.6.0_x86__q4d96b2w5wcc2' (AUMId `Evernote.Evernote_q4d96b2w5wcc2!Evernote') supports 1 extensions but has no verbs
```

Nevertheless, when I enable the "Julia: Use PLot Pane", and the plots pop up, the same Warning also comes up. I do not recall having installed any package related to the EverNote corporation.

Help will be very much appreciated. Thanks.

**Comment by davidanthoff** [comment]
Do plots properly work from a standard Julia REPL on that machine?

**Comment by VivaldoMendes** [comment]
The problem existed on a new computer (it's a Windows 10 machine). There are more computers in the house (all with the same OS), all with Julia installed, but I have never seen this kind of problem before, with different Julia versions and different Plots versions.

I re-installed the Julia installation (including VSCode and Julia for VSCode) on that computer. Now, using Plots, the plots pop up in the external window, both with VScode and the Julia REPL. Nevertheless, the mysterious "Warning" still comes up:

```
(process:14856): GLib-GIO-WARNING **: 14:33:24.710: Unexpectedly, UWP app `Evernote.Evernote_10.16.7.0_x86__q4d96b2w5wcc2' (AUMId `Evernote.Evernote_q4d96b2w5wcc2!Evernote') supports 1 extensions but has no verbs
```

Please see the example below. It is not a big deal now that the plots can be seen. It is now clear that the problem is not related to Julia for VSCode. Maybe something related to Plots or GR in their new versions when installed on a new computer. 

Thanks for giving me some feedback.

![a1](https://user-images.githubusercontent.com/48516539/125166719-c9ae8800-e194-11eb-8bb3-db50d2d7bbd6.png)
![a2](https://user-images.githubusercontent.com/48516539/125166721-ce733c00-e194-11eb-9d78-7bf75e2eae90.png)

**Comment by davidanthoff** [comment]
That is weird, probably best to ask over on the GR repo!
