### ISSUE TITLE
How to cut and paste a plot from Plot Navigator to clipboard

### ISSUE THREAD

**Issue by Peter-Jolly** [julia-vscode/julia-vscode#2235]
I really like the new plot navigator feature in the latest release of the Julia extension for Vscode BUT it would be much better if you could copy a plot to the clipboard for use in other documents such as MS Word. Is there a way to do this or could it be included in a future release? Thanks Peter

**Comment by davidanthoff** [comment]
Duplicate of https://github.com/julia-vscode/julia-vscode/issues/172.
