### ISSUE TITLE
long lines and ctrl enter cause excessive printing to stdout. text wrapping

### ISSUE THREAD

**Issue by anandijain** [julia-vscode/julia-vscode#2236]
1 select a bunch of lines of code 
2 ctrl enter
3 one of the lines happens to be long
4 50000 copies of the code block are endlessly printed to stdout, forcing me to close repl session

is there a solution to this? it happens to me all the time

#443 is related but is closed

**Comment by pfitzseb** [comment]
Can't do anything about this. Use Alt-Enter instead.
