### ISSUE TITLE
stderror not shown in notebooks

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/julia-vscode#2250]

**Comment by davidanthoff** [comment]
It does seem to show it now, logging also works, but for example `Pkg.status()` still doesn't show in the notebook, but instead in the Output channel that we attach to the notebook kernel...

**Comment by davidanthoff** [comment]
@pfitzseb I'm a bit lost why
```julia
using Pkg
Pkg.status()
```
output ends up in the Output panel for the Julia Notebook Kernels rather than being sent to the notebook... As far as I can tell we are capturing the stderr properly, but apparently not? In IJulia this seems to work...

**Comment by pfitzseb** [comment]
Upstream issue is https://github.com/JuliaLang/Pkg.jl/issues/2542 and got fixed by https://github.com/JuliaLang/Pkg.jl/pull/2543.
