### ISSUE TITLE
Automatic kernel selection for existing notebook doesn't work

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/julia-vscode#2255]
When I open a notebook that was created in JupyterLab and had a specific Julia kernel set there, and then open the same notebook in VS Code, it does not automatically select our kernel to run things.

It is not clear to me whether we need to add functionality in say `onDidOpenNotebookDocument` to handle that (by calling `updateNotebookAffinity`) or whether the Jupyter extension will handle that?

@DonJayamanne do you know how this is supposed to work?

**Comment by DonJayamanne** [comment]
I'll work on this.
