### ISSUE TITLE
Kernel choice is not saved in notebook file

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/julia-vscode#2256]
It seems that the kernelspec/metadata fields in notebooks are not populated properly when saving a Jupyter notebook.

@DonJayamanne this is also something that needs to be fixed in the Jupyter extension, right?

**Comment by DonJayamanne** [comment]
Yes, sorry, was on holidays, today. Will work on this.

**Comment by davidanthoff** [comment]
@DonJayamanne so this will essentially go https://github.com/julia-vscode/julia-vscode/blob/2bbf02bfec80f84992a3bf61b3a60d3ae2357fad/src/notebook/notebookFeature.ts#L161, right?

Do you know when the relevant upstream code will ship, i.e. when we can implement that? Is there an issue/PR upstream that I can follow?

**Comment by davidanthoff** [comment]
@DonJayamanne and @claudiaregio, so I think this issue is the one I'm most worried about at the moment. My understanding from an email from Don is that we can't do anything about this, because some more APIs in VS Code itself would be needed?

I'm really almost torn whether we should release the whole notebook functionality before this is resolved at all (that is why this was one of our "must be done before release" items). The problem here is that users will actually save in some way faulty files if this is not resolved, and such faulty files can have a long lifetime... Say someone uses this to write some replication code for a paper and then deposits such files in zenodo.org or something like that (this happens all the time with scientific code). If they create that notebook file with VS Code without this being fixed, those files will miss really crucial information.

Is there a timeline for this? I.e. will be able to fix this with the July VS Code release? I am much less worried about rough edges around user experience, but when it comes to file formats, I think we really need to get it right from the start because those files will stay around even after we've updated the extension to a new version that might fix this...

**Comment by mjbvz** [comment]
I have a PR out on the VS Code side that would allow setting the kernelspec on ipynb files:

https://github.com/microsoft/vscode/pull/131219

You would use this api through the built-in `ipynb` extension

Please let me know if this PR adds what you need for Julia
