### ISSUE TITLE
When using debugger program does not sop at breakpoints

### ISSUE THREAD

**Issue by Peter-Jolly** [julia-vscode/julia-vscode#2262]
I have recently tried running the debugger (on a fairly large program with lots of macros) and found that the program does not stop at set breakpoints. As a work around, is there anyway to stop the program at a defined point but inserting a command (I am not sure what command that would be?), inspect the variables and then hit a command (key) to proceed (I am not sure what key that would be)? I know this is how the debugger is supposed to work, but unfortunately it does not. Look forward to some feedback. Thanks Peter

**Comment by pfitzseb** [comment]
You can try [Infiltrator.jl](https://github.com/JuliaDebug/Infiltrator.jl) instead.

Also try clearing the compiled functions/modules in VSCode:
![image](https://user-images.githubusercontent.com/6735977/123913357-6778aa80-d97e-11eb-88db-6eeff31de17a.png)

It's possible we overlooked some higher order function in Base that you ended up calling.

**Comment by Peter-Jolly** [comment]
Ok thanks for response. I will give Infiltrator.jl a try.
