### ISSUE TITLE
Julia-insider causes git settings to "disappear" in recent vscode build

### ISSUE THREAD

**Issue by asampal** [julia-vscode/julia-vscode#2265]
Uninstalling this extension brought back git functionality.

Please see https://github.com/microsoft/vscode/issues/127736

**Comment by davidanthoff** [comment]
Thanks for reporting! I know what the problem is, working on getting out a new build ASAP.

**Comment by davidanthoff** [comment]
I think this should be fixed now, if not please let me know.
