### ISSUE TITLE
Is there a profiler available?

### ISSUE THREAD

**Issue by tomchor** [julia-vscode/julia-vscode#2269]
Hello, I'm trying to get a profiler working for Julia that can profile remote code. Juno for Atom was my first choice but I couldn't get it to work. I went to post an issue there but apparently the project is no longer maintained.

Does `julia-vscode` have that capability? If not, could you point me in the right direction for this feature?

Thanks!

**Comment by pfitzseb** [comment]
Yes, simply use the `@profview` macro (same as you would with ProfileView.jl).
