### ISSUE TITLE
Final variable assignment of a function shouldn't be grayed out

### ISSUE THREAD

**Issue by Datseris** [julia-vscode/julia-vscode#2270]
Julia has the arguably nice feature that the final evaluation of a function is automatically returned. Consider the following:

![image](https://user-images.githubusercontent.com/19669089/124671584-fe30f400-deb5-11eb-8134-0bd08ba30f8d.png)

As you can see, in the first function the `zⱼ₊₁` is grayed-out. I appreciate tremendously the "graying out of unused variables". In 99% of the cases it makes me spot some typo in my functions. But if the last operation of a function is an assignment, this assignment shouldn't be grayed out if possible. Otherwise it forces me to write the somewhat ugly duplicate `return` statement.

**Comment by pfitzseb** [comment]
Is `zⱼ₊₁` a global? If not, why do you even have that assignment? Just for

**Comment by Datseris** [comment]
Yes for clarity. It is not global, but the last line implements an exact equation from a paper/algorithm document (thank unicode for that!)

**Comment by Datseris** [comment]
Hm, I see your point, that in a sense it is not possible to tell whether this is a global or not, so the graying out can still serve as warning sign...?
