### ISSUE TITLE
Hide View Container

### ISSUE THREAD

**Issue by sclel016** [julia-vscode/julia-vscode#2274]
Hi,

The Julia vscode extension seems to always show the view container. I would expect the extension to hide unless there was any Julia files in the current workspace. The screenshot was taken without any files in the workspace. All of my language specific extensions are hidden except for Julia (i.e. cmake, latex, etc).

![image](https://user-images.githubusercontent.com/11709587/124847428-d8b0f280-df68-11eb-8ded-619bfeb065c1.png)

**Comment by davidanthoff** [comment]
I think this might be a duplicate, but I can't find it right now. It would be good to see whether VS Code has some guidance on what "best practices" are here, not clear to me.

**Comment by sclel016** [comment]
Agreed, issue #2247 seems to be a report of the same problem. I'm happy to close mine if you want to consolidated. I think taking a look at existing extensions like [cmake-tools](https://github.com/microsoft/vscode-cmake-tools) might help. They seem to have one of the more polished extensions I've had the pleasure of using.
