### ISSUE TITLE
Feature Request: Add Refactoring (Method, Variable, Parameter)

### ISSUE THREAD

**Issue by j-hayes** [julia-vscode/julia-vscode#2279]
One of my most used features in any IDE are:

Extract Method
Introduce/Extract Variable (create a variable from highlighted value),
Introduce parameter (for a variable that is not defined in the code above in a function 
Move to selection (function/struct/etc.) to a separate file 

I'd love to see this in this extension. I imagine it be very similar to the way the native VS code python functionality:
https://github.com/microsoft/vscode-python
which uses:
https://github.com/python-rope/rope

Thanks for all the great work on this package so far!

**Comment by davidanthoff** [comment]
Duplicate of https://github.com/julia-vscode/julia-vscode/issues/2237.
