### ISSUE TITLE
backward compatibility mode

### ISSUE THREAD

**Issue by phgmacedo** [julia-vscode/julia-vscode#2281]
Newer vscode versions seem to be getting slower, and extremely buggier (especially the terminal), without any meaningful features that improve my workflow. 
One way I have found effective was to turn off updates with ` "update.mode": "none",` in my config, so that vscode would not update itself to newer buggier versions after 1.55.2.

In recent releases of this extension, the [minimum vscode api is 1.57](https://github.com/julia-vscode/julia-vscode/blob/master/package.json#L9), meaning that users on 2 months older vscode versions will not be able to install julia. 

Would it be feasible to provide support for older vscode versions (mayber 6 months or more, at least), so that all julia users are not forced to be on the bleeding edge always?

**Comment by davidanthoff** [comment]
I don't think we can do that, for example we plan to ship support for the integrated notebook stuff very soon, and that requires the latest version of VS Code. Ditto for things like workspace trust, that is really important for us to have from a security point of view, but that also just shipped super recently. I think your best bet is to report these bugs upstream, the VS Code team is typically _super_ responsive and fast with fixing things. If you have specific things that don't work for Julia (but are upstream problems), you can also let us know here and we can ping the VS Code team about that.

**Comment by pfitzseb** [comment]
You could also remove the `engines.vscode` entry from package.json and see what happens; I'd expect many things to work fine and a few of them to break, but who knows.
