### ISSUE TITLE
Julia 1.7 compat

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/julia-vscode#2284]
We should start making everything compatible with Julia 1.7...

**Comment by pfitzseb** [comment]
AFAICT we only need https://github.com/julia-vscode/julia-vscode/pull/2302 for this by now.

**Comment by mmiller-max** [comment]
I'm currently in the process of updating [TestReports.jl](https://github.com/JuliaTesting/TestReports.jl) for 1.7 and I think similar changes will be required in `live_unit_testing`, specifically [this](https://github.com/JuliaTesting/TestReports.jl/blob/8620bcfe8024d88ced8426d0850a3fb069abb0fd/src/TestReports.jl#L27-L29), [this](https://github.com/JuliaTesting/TestReports.jl/blob/8620bcfe8024d88ced8426d0850a3fb069abb0fd/src/runner.jl#L193-L202), [this](https://github.com/JuliaTesting/TestReports.jl/blob/8620bcfe8024d88ced8426d0850a3fb069abb0fd/src/runner.jl#L216-L231) and [this](https://github.com/JuliaTesting/TestReports.jl/blob/8620bcfe8024d88ced8426d0850a3fb069abb0fd/src/runner.jl#L374-L378). I can make these changes in a PR here once I've got them fully tested ([TestReports PR](https://github.com/JuliaTesting/TestReports.jl/pull/74) can be used to track).

Thinking more longer term, this may have to happen for each new version of Julia, and doing it in two places suggests it should be somewhere else. I think either an API package that provides the sandbox environment and installation checking, or adding to `Pkg` itself. I'll raise an issue in `Pkg` to see what they think over there.

**Comment by davidanthoff** [comment]
@mmiller-max the live unit testing is disabled at the moment, we never got it to properly work. So that won't be a blocker for 1.7. But totally agreed, if we could move some of that code somewhere else, it would be great! Even better if we could actually try to fix live unit testing :)

**Comment by mmiller-max** [comment]
Ok cool! I'll look at moving it to another package for now. I'd also be interested in looking at the live unit test stuff. Suspect it's over my head but will check out the issues..

**Comment by pfitzseb** [comment]
We should be fully 1.7 compatible nowadays.
