### ISSUE TITLE
Missing reference on Julia 1.6.2 but not 1.6.1

### ISSUE THREAD

**Issue by singularitti** [julia-vscode/julia-vscode#2287]
After updated to Julia 1.6.2, I met a lot of "Missing reference"s which work fine on Julia 1.6.1. This problem occurs on extension versions 1.3.13, 1.2.5, and 1.2.7.
![image](https://user-images.githubusercontent.com/25192197/125729794-13a81641-9daf-4fa5-9bb9-3078171c8ce5.png)

```julia
julia> versioninfo()
Julia Version 1.6.2
Commit 1b93d53fc4 (2021-07-14 15:36 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake-avx512)
```

**Comment by davidanthoff** [comment]
We had a bug on Julia 1.6.2 that crashed the language server. I just pushed a new build that hopefully fixes that. If not, please reopen.

**Comment by singularitti** [comment]
It seems to be fixed, thanks!
