### ISSUE TITLE
Improper syntax highlighting for end keyword inside vectors

### ISSUE THREAD

**Issue by Octogonapus** [julia-vscode/julia-vscode#2293]
This is colored properly:
```julia
foo(
    quote
        push!(foo, (x,y))
    end
)
```

But when you put it inside a vect expr, the highlighting breaks:
```julia
[
    foo(
        quote
            push!(foo, (x,y))
        end
    )
]
```

Screenshot so it's clear:
![image](https://user-images.githubusercontent.com/4064722/126047804-728ff602-a64a-447e-a760-585acadbfd65.png)

Interestingly, this happens on GitHub's syntax highlighting, too.

Using Julia v1.6.1, julia-vscode v1.2.8, vscode 1.58.0.

**Comment by pfitzseb** [comment]
That's https://github.com/JuliaEditorSupport/atom-language-julia/issues/140. Unlikely to be fixed soon.
