### ISSUE TITLE
Add a documentation pane

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/julia-vscode#230]
Juno is getting it, see https://files.gitter.im/JunoLab/Juno/DXhk/image.png.

**Comment by waldyrious** [comment]
Embedded image for convenience:

![screenshot](https://files.gitter.im/JunoLab/Juno/DXhk/image.png)

**Comment by davidanthoff** [comment]
I think we would want this to show up in the side bar, and as of right now we can't host arbitrary HTML there. I think there is work going on in the core VS Code product to enable extensions to add arbitrary webviews to the side bar, at which point we could implement this. If someone finds the issue for that on the VS Code repo, please link it here :)

**Comment by davidanthoff** [comment]
Here is the relevant upstream issue: https://github.com/microsoft/vscode/issues/83911. I think they plan to start working on this in the May 2020 iteration.

**Comment by pfitzseb** [comment]
As a first iteration this could also just live in a normal pane (like plots). The implementation wouldn't change much anyways once that feature is in.

**Comment by davidanthoff** [comment]
My best guess is that the lifecycle story will be quite different, but who knows. From what I've read I don't think they will finish this in May, but maybe they will make enough progress so that one can get a good sense how similar the implementation will be to the regular webview.

**Comment by aviatesk** [comment]
Whichever their API will be based on direct HTML or markdown strings, implementation in Julia side won't change much. I would like to work on this weekend.

**Comment by davidanthoff** [comment]
I believe @ZacLN started a bit with this in https://github.com/julia-vscode/julia-vscode/pull/818, but never got to the UI part. We might have removed the request handler on the LS side in the meantime, but it probably is still somewhere in either the git history or some non-merged PR :)

**Comment by aviatesk** [comment]
Okay, now I'm having a basic working implementation of this.
As a first iteration, currently I'm using our REPL session to retrieve a documentation as in Juno since [@ZacLN 's initial approach](https://github.com/julia-vscode/LanguageServer.jl/pull/377) won't work for user package code (i.e. documentation that can't be accessed directly from `Main` module)
Do you guys agree on using the interactive session instead of LS for the first try ?
I think LS _does_ retrieve documentations for e.g. on-hover feature etc, while it doesn't work for all cases I tried, e.g.:
- documentation for bindings (`const my_sin = sin` and get documentation for `my_sin`)
- documentation for variables

/cc @pfitzseb @davidanthoff

**Comment by zhaouv** [comment]
> I think we would want this to show up in the side bar, and as of right now we can't host arbitrary HTML there. I think there is work going on in the core VS Code product to enable extensions to add arbitrary webviews to the side bar, at which point we could implement this. If someone finds the issue for that on the VS Code repo, please link it here :)

recently i am working on highlighting and previewing embeded markdown in any languages, and the typical application is julia markdown doc. so i find this issue. I haven't read your work carefully. but for the question. it is easy to put any html except script to the side bar

i put the iframe by this [function](https://github.com/zhaouv/vscode-markdown-everywhere/blob/ea28afdc0cb091fb2ac8761206181bbb8c4606a1/build/extension.js#L54)

![image](https://user-images.githubusercontent.com/26158289/90370569-3104aa80-e0a0-11ea-91d7-811fdf0b0bc5.png)
![image](https://user-images.githubusercontent.com/26158289/90370747-7923cd00-e0a0-11ea-9d19-65566468e908.png)
