### ISSUE TITLE
Click to Go to Definition Not Workin

### ISSUE THREAD

**Issue by chelseas** [julia-vscode/julia-vscode#2300]
I am running v1.2.8 on Ubuntu 20 and nothing happens when I ```Ctrl + Click``` on a function call to try to jump to the definition. :/// This is one of my favorite features of the julia-vscode extension so it's disappointing that it's not working.

**Comment by chelseas** [comment]
Actually no features are working ://
Autocompletion of unicode is not working either
And I get the error: Couldn't start client Julia Language Server

**Comment by davidanthoff** [comment]
Can you start a Julia REPL via the command?
