### ISSUE TITLE
Function object (functor) not parsed correctly

### ISSUE THREAD

**Issue by melonedo** [julia-vscode/julia-vscode#2303]
![Screenshot_20210723_140216](https://user-images.githubusercontent.com/44501064/126743013-f7acfba2-4e7e-4123-9539-7edbf57d9797.png)
The file is https://github.com/JuliaInterop/Clang.jl/blob/master/src/generator/passes.jl.
As can be seen on the screenshot, `function (x::EpiloguePrinter)(dag::ExprDAG, options::Dict)` is not parsed as a function, and its local variables appear to leak to global scope in the tree.

**Comment by pfitzseb** [comment]
AFAICT scope analysis is correct for this case, but the outline display is indeed broken. Will fix.
