### ISSUE TITLE
The Julia Language Server Failed to start

### ISSUE THREAD

**Issue by Xinyu-Wu-0000** [julia-vscode/julia-vscode#2311]
Issue Type: <b>Bug</b>

[ Info: Starting the Julia Language Server
[ Info: Symbol server store is at '/home/wuxinyu/.config/Code - Insiders/User/globalStorage/julialang.language-julia-insider/symbolstorev5'.
┌ Error: CST does not match input string length.
└ @ LanguageServer ~/.vscode-insiders/extensions/julialang.language-julia-insider-1.3.21/scripts/packages/LanguageServer/src/requests/textdocument.jl:141
┌ Error: Error parsing file file:///home/wuxinyu/Documents/drafts/draft_julia/python_tcp_serial_test.jl
└ @ LanguageServer ~/.vscode-insiders/extensions/julialang.language-julia-insider-1.3.21/scripts/packages/LanguageServer/src/requests/init.jl:119
┌ Error: Some Julia code in the VS Code extension crashed
└ @ Main ~/.vscode-insiders/extensions/julialang.language-julia-insider-1.3.21/scripts/error_handler.jl:15
ERROR: indexing error for global expression at 3. args: [:IDENTIFIER, :IDENTIFIER] trivia: [:GLOBAL]
Stacktrace:[ Info: Couldn't find package on disc.
[ Info: Couldn't find package on disc.

[ Info: Couldn't find package on disc.
[ Info: Couldn't find package on disc.
 [ Info: Couldn't find package on disc.
[ Info: Couldn't find package on disc.
[ Info: Couldn't find package on disc.
[ Info: Couldn't find package on disc.
[ Info: Couldn't find package on disc.
 [1] error(s::String)
    @ Base ./error.jl:33
  [2] getindex(x::CSTParser.EXPR, i::Int64)
    @ CSTParser.Iterating ~/.vscode-insiders/extensions/julialang.language-julia-insider-1.3.21/scripts/packages/CSTParser/src/iterate.jl:12
  [3] collect_hints(x::CSTParser.EXPR, env::StaticLint.ExternalEnv, missingrefs::Symbol, isquoted::Bool, errs::Vector{Tuple{Int64, CSTParser.EXPR}}, pos::Int64) (repeats 4 times)
    @ StaticLint ~/.vscode-insiders/extensions/julialang.language-julia-insider-1.3.21/scripts/packages/StaticLint/src/linting/checks.jl:569
  [4] collect_hints(x::CSTParser.EXPR, env::StaticLint.ExternalEnv, missingrefs::Symbol)
    @ StaticLint ~/.vscode-insiders/extensions/julialang.language-julia-insider-1.3.21/scripts/packages/StaticLint/src/linting/checks.jl:546
  [5] mark_errors(doc::LanguageServer.Document, out::Vector{LanguageServer.Diagnostic})
    @ LanguageServer ~/.vscode-insiders/extensions/julialang.language-julia-insider-1.3.21/scripts/packages/LanguageServer/src/requests/textdocument.jl:152
  [6] lint!(doc::LanguageServer.Document, server::LanguageServerInstance)
    @ LanguageServer ~/.vscode-insiders/extensions/julialang.language-julia-insider-1.3.21/scripts/packages/LanguageServer/src/staticlint.jl:77
  [7] parse_all(doc::LanguageServer.Document, server::LanguageServerInstance)
    @ LanguageServer ~/.vscode-insiders/extensions/julialang.language-julia-insider-1.3.21/scripts/packages/LanguageServer/src/requests/textdocument.jl:147
  [8] load_folder(path::String, server::LanguageServerInstance)
    @ LanguageServer ~/.vscode-insiders/extensions/julialang.language-julia-insider-1.3.21/scripts/packages/LanguageServer/src/requests/init.jl:117
  [9] initialized_notification(params::LanguageServer.InitializedParams, server::LanguageServerInstance, conn::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint})
    @ LanguageServer ~/.vscode-insiders/extensions/julialang.language-julia-insider-1.3.21/scripts/packages/LanguageServer/src/requests/init.jl:192
 [10] (::LanguageServer.var"#96#97"{typeof(LanguageServer.initialized_notification), LanguageServerInstance})(conn::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, params::LanguageServer.InitializedParams)
    @ LanguageServer ~/.vscode-insiders/extensions/julialang.language-julia-insider-1.3.21/scripts/packages/LanguageServer/src/languageserverinstance.jl:252
 [11] dispatch_msg(x::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, dispatcher::JSONRPC.MsgDispatcher, msg::Dict{String, Any})
    @ JSONRPC ~/.vscode-insiders/extensions/julialang.language-julia-insider-1.3.21/scripts/packages/JSONRPC/src/typed.jl:67
 [12] run(server::LanguageServerInstance)
    @ LanguageServer ~/.vscode-insiders/extensions/julialang.language-julia-insider-1.3.21/scripts/packages/LanguageServer/src/languageserverinstance.jl:361
 [13] top-level scope
    @ ~/.vscode-insiders/extensions/julialang.language-julia-insider-1.3.21/scripts/languageserver/main.jl:63
[ Info: Couldn't find package on disc.
[ Info: Couldn't find package on disc.
[ Info: Couldn't find package on disc.
[ Info: Couldn't find package on disc.
[ Info: Couldn't find package on disc.
[ Info: Couldn't find package on disc.
[ Info: Couldn't find package on disc.
[ Info: Couldn't find package on disc.
[ Info: Couldn't find package on disc.
[ Info: Couldn't find package on disc.
[Info  - 4:20:21 PM] Connection to server got closed. Server will restart.

Extension version: 1.3.21
VS Code version: Code - Insiders 1.59.0-insider (04485223ebc6a075f39966bf9b3e261359ac7818, 2021-07-23T19:20:06.533Z)
OS version: Linux x64 5.11.0-25-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.41GB (7.04GB free)|
|Process Argv|--unity-launch /home/wuxinyu/Desktop/Julia Notes.code-workspace --crash-reporter-id 43d31d55-f7ab-4c13-ac5c-382630e82534|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551:30291412
vspre833:30321513
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
00j7a122:30294756
vscod805cf:30301675
pythonvspyt200:30323110
vscextlangct:30310089
vsccppwtct:30312693
pythonvssor306:30340298
bridge0708:30335490

```

</details>

**Comment by davidanthoff** [comment]
Now tracking at https://github.com/julia-vscode/CSTParser.jl/issues/293.
