### ISSUE TITLE
Julia kernel doesn't have Image mimetype

### ISSUE THREAD

**Issue by merckxiaan** [julia-vscode/julia-vscode#2317]
Using the `Julia VS Code extension` kernel option (as opposed to IJulia) doesn't display an image as I'd expect it to. I also can't change the mimetype to anything else.
![vs-code image mimetype](https://user-images.githubusercontent.com/31353884/127054071-c8acccbd-a32a-4183-a4df-ef5430bc44e5.png)
These are the mimetypes IJulia's kernel offers:
![mimetypes IJulia](https://user-images.githubusercontent.com/31353884/127054534-27b5430f-c416-4a3a-8f98-e0793d917989.png)
Both the `image/png`-options show the image with a very subtle difference in whitespace.

**Comment by davidanthoff** [comment]
Hm, that is strange, in theory the built-in MIME type renderers should kick in and handle all image displaying... Could you let us know which version of VS Code, the Julia extension and the Jupyter extension you are using? And is there maybe a chance you could share the notebook?

**Comment by merckxiaan** [comment]
Sure!

**Comment by merckxiaan** [comment]
Sure!
I'm on:
```
VS Code 1.58.2
Julia Insider 1.3.25
Jupyter 2021.8.1054968649
```
Here's a gist containing the notebook:
https://gist.github.com/merckxiaan/3910c1bcbe2fdd16106f3f1ef7592b1e
Thanks for looking at this and please let me know if you need further information!

**Comment by davidanthoff** [comment]
Great, thanks for the super useful bug report! I fixed it on `master`, we'll push out a new build very soon.
