### ISSUE TITLE
Use soft scope for notebook

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/julia-vscode#2320]
We should do the same thing as IJulia.jl here.

**Comment by pfitzseb** [comment]
https://github.com/julia-vscode/julia-vscode/blob/28ebc28d0b0cf3a9d5df280de658904827cedb88/scripts/packages/VSCodeServer/src/eval.jl#L201-L205

**Comment by davidanthoff** [comment]
Stupid question: don't we need https://github.com/stevengj/SoftGlobalScope.jl to get this working properly? I don't understand any of this, TBH.

**Comment by pfitzseb** [comment]
Only for old Julia versions:
https://github.com/stevengj/SoftGlobalScope.jl/blob/68195b7ed749832c1f54ccb3dcbfce0d317c8f66/src/SoftGlobalScope.jl#L64-L66

And imho we should always try to be consistent with the currently running Julia version, so no soft-scoping pre 1.6.

**Comment by davidanthoff** [comment]
> And imho we should always try to be consistent with the currently running Julia version, so no soft-scoping pre 1.6.

I guess the question is how compatible we want to be with IJulia.jl... At the end of the day, if someone is using the notebook stuff with an old Julia version, then probably almost certainly because they have an old notebook lying around, and then that was almost certainly created using IJulia.jl and the assumptions in there... But maybe we just ignore, I think the user base on old Julia versions is exceedingly small in any case.
