### ISSUE TITLE
LaTeXing in Markdown cells (julia.notebookController)

### ISSUE THREAD

**Issue by PaulSoderlind** [julia-vscode/julia-vscode#2323]
Thanks for the notebook support. Looks very interesting.

Trying some of my (teaching) notebooks, most things work great. However, there are some issues with LaTeX in the Markdown cells. In particular, environments do not render. Example:
```
$
\begin{equation}
y = \cos x
\end{equation}
$
```
According to the KaTeX documentation, this should work, but it does not.

Info: Julia 1.6.2, WIndows10 (64)
Vs code 1.58.2
Julia extension 1.3.26 

Edit: added $$ to avoid confusion about that.

**Comment by PaulSoderlind** [comment]
Update: I _might_ have to retract this issue. After more testing, it seems vs code shows _some_ environments. There is a chance that my environments were a bit too fancy (and not as simple as I initially claimed). Let me test a bit more - and then I'll report back. Sorry for the noise.

**Comment by PaulSoderlind** [comment]
I hereby retract this issue. Yes, the TeX rendering in vs code is different (it's based on KaTeX) from jupyter. Still, it works for most things. Fancy environments and delimiters around arrays are not pretty, but that is not a julia-vscode bug. Just KaTeX, I believe. Again, sorry for the noise.

**Comment by davidanthoff** [comment]
Hm, I almost feel though that we (or maybe the VS Code team) needs to make sure that something that displays properly in Jupyter Lab should also show properly on our end...

CC @claudiaregio and @DonJayamanne

**Comment by DonJayamanne** [comment]
@davidanthoff I'm trying this at my end and looks like it works well.
Plase could you check this in VS Code insiders, as there have been a few changes to latext rendering in notebooks,
Here's the markdown view I get for the same latext

![Screen Shot 2021-07-29 at 10 15 33](https://user-images.githubusercontent.com/1948812/127536011-279ceaf5-0d98-40b8-8d3d-428de8f8a3d7.png)

**Comment by PaulSoderlind** [comment]
I am no expert on this (although I claim to know my LaTeX well...), but vs code seems to use KaTeX whereas jupyter uses MathJax. If so, it is no surprise that there are some differences. To my eyes, MathJax is a more precise LaTeX interpreter, but KaTeX claims to be much faster.

In simple cases like $y = \cos x$, I would expect no differences. Rather, they show up when you try more complicated things., for instance, to have delimiters around an array.

**Comment by PaulSoderlind** [comment]
@DonJayamanne 

Here is an illustration of what jupyter and vscode show (same notebook, does not matter if it's a python or Julia notebook). Please notice the difference for the matrix.

in jupyter:
<img width="207" alt="py_ipynb_in_jupyter" src="https://user-images.githubusercontent.com/9378261/127644741-7c8d741e-5c6b-4219-a681-8e77b754a1fd.png">

in vs code:
<img width="445" alt="py_ipynb_in_vscode" src="https://user-images.githubusercontent.com/9378261/127644777-16cc1344-7492-4307-b5ec-3f71e3ed9e1c.png">

**Comment by PaulSoderlind** [comment]
This seems to be fixed in the latest VS code 1.60.0. I therefore close this issue.

**Comment by pfitzseb** [comment]
Great, thanks for reporting back!
