### ISSUE TITLE
Error message not displayed in notebook UI

### ISSUE THREAD

**Issue by pfitzseb** [julia-vscode/julia-vscode#2326]
with the "Jupyter Error Handler" for the `application/vnd.code.notebook.error` MIME type. Everything looks fine with the built-in renderer.

This makes a lot of sense since the renderer does indeed not look at any field except for `stack`:
https://github.com/microsoft/vscode-jupyter/blob/c13fe7f10ec6b82369c2a16727819be6339178ea/src/datascience-ui/error-renderer/index.ts#L31-L78

Imho this should be fixed in the Jupyter extension. Thoughts, @DonJayamanne?

**Comment by DonJayamanne** [comment]
I agree, will get on that ASAP.

**Comment by rebornix** [comment]
@pfitzseb can you share a sample code with the error for me to troubleshoot? For error properties, the error renderer should do the same as the builtin one, I might miss some properties but not sure what.

**Comment by pfitzseb** [comment]
Just `0//0` in a Julia notebook will trigger it. We're sending a 
```
Object
message: "LoadError: ArgumentError: invalid rational: zero(Int64)//zero(Int64)\nin expression starting at Untitled-1.ipynb:1"
name: "ArgumentError"
stack: "\nStacktrace:\n  [1] __throw_rational_argerror_zero(T::Type)\n    @ Base ./rational.jl:32\n  [2] Rational{Int64}(num::Int64, den::Int64)\n    @ Base ./rational.jl:34\n  [3] ..."
```
object to the UI, which is displayed fine by the built-in error renderer. The one in the Jupyter extension drops all fields except for `stack`.
