### ISSUE TITLE
JuliaFormatter configuration/defaults

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/julia-vscode#2337]
I thought we could use this issue to sort out how we handle configuration and defaults for JuliaFormatter integration.

One idea is that we just move all configuration out of the VS Code configuration system. JuliaFormatter already has an option to have local configuration files (which correspond to workspace level VS Code configuration settings in principle). If JuliaFormatter _also_ had a native user level configuration settings story (say a file in the Julia depot, maybe `~/.julia/.JuliaFormatter` or something like that) then we could just say "all JuliaFormatter configuration is handled by JuliaFormatter", which I think would greatly simplify things on some level. A drawback of this approach is that we would lose the relatively simple UI for editing settings that VS Code provides, the remote scenario loses the UI, and we lose settings sync in VS Code... So I'm not 100% sure this is a good idea.

Another idea is that (like in the past) we have VS Code configuration settings, and they can be specified both at the user and workspace level. The drawback of this is that we have two ways to specify folder level settings (VS Code and `.JuliaFormatter`), plus exposing the full richness of `.JuliaFormatter` via VS configuration might be tricky.

Third option is to have user level configuration in VS Code, but use `.JuliaFormatter` as the folder level setting. I think this is what @pfitzseb has implemented in his draft PR. The weird thing about this is that one can presumably only configure a subset of things at the user level, right? Also feels kind of weird to use two different configuration systems for these, but maybe that is ok?

I guess there are some other permutations as well?

The other tricky questions is defaults, i.e. what happens if nothing is configured? I think when we last chatted about this we felt that JuliaFormatter by default is too opinionated to be our default as is. So I think the plan was that something like https://github.com/domluna/JuliaFormatter.jl/pull/256 would be our default, i.e. something that does a lot fewer things by default. I think I could then easily adjust the whole package butler ecosystem to use the same default, so that would all be ok. The one thing that is _not_ nice with this is that if someone then installs JuliaFormatter.jl directly and formats something that was previously formatted with VS Code (and that user is just using defaults), formatting will jump back and forth between the defaults of VS Code and JuliaFormatter... I don't really see a way out of that, though...

CC @domluna, @pfitzseb and @ZacLN

**Comment by pfitzseb** [comment]
The current state of the PR is that no config options are used, except for the `tabSize` sent along with the `textDocument/formatting` request. A `.JuliaFormatter.toml` is imho enough in all cases; global configuration isn't super important imho.

Re defaults: I'd be totally happy with just using JuliaFormatter's defaults as is; it works well enough that I don't mind opinionated formatting.

**Comment by domluna** [comment]
If `.JuliaFormatter.toml` can be leveraged that would be best. I know this is VSCode specific but if VScode options are specific to it only and it ignores .`JuliaFormatter.toml` then it could be iffy when collaborating with someone not using VScode

**Comment by pfitzseb** [comment]
Right, the only question is whether we can/want to do something about global configuration.

**Comment by davidanthoff** [comment]
The more I think about it, the more I agree with @pfitzseb on the global configuration. Or maybe I'm getting even more extreme: I think we should actually probably just not have global configuration at all. In many ways that is really not a good concept for a formatter in any case, given that it essentially completely breaks any collaborative workflow. So I'd say we just force folks to use local configuration, and don't offer any other options.

@pfitzseb, the `tabSize` is just the global VS Code config value, not something Julia specific?

> I'd be totally happy with just using JuliaFormatter's defaults as is; it works well enough that I don't mind opinionated formatting.

So I'm pretty opposed to that :) I just had a long Rust phase, and their (default) opinionated formatter that constantly messed with my line breaks drove me absolutely nuts. I think our default really should be something that only does indentation and whitespaces, nothing else. But I think we're converging on that in any case, with the `MinimalStyle`, right?

**Comment by pfitzseb** [comment]
> the tabSize is just the global VS Code config value, not something Julia specific?

No, that's the per-file thing in the lower right.

> But I think we're converging on that in any case, with the MinimalStyle, right?

Yup.
