### ISSUE TITLE
Use variables in tmux session name

### ISSUE THREAD

**Issue by haberdashPI** [julia-vscode/julia-vscode#2349]
I'd love to be able to name my tmux sessions for persistent sessions something like `vscode-julia-${workspace}-${git.branch}` and have the values inside `${}` be replaced by appropriate strings.

**Comment by pfitzseb** [comment]
I kinda want upstream support (https://github.com/microsoft/vscode/issues/2809, https://github.com/microsoft/vscode/issues/46471) for this instead of implementing our own version of variable substitution. There already is an npm package that handles a few cases, but... meh.

**Comment by haberdashPI** [comment]
I do see the advantage of supporting the built-in form of this, when it exists. That makes sense.

Given that it doesn't exist and that this is easy to implement, I am happy to submit a PR, if your only resistance is the additional workload. The disadvantage I guess is that this *might* break someone's config once you did move to using the official API extension for this (if the names change).

**Comment by pfitzseb** [comment]
My bigger concern is that this might subtly break if upstream changes their implementation of how these variables are defined/resolved.

**Comment by ssfrr** [comment]
This seems to have regressed at some point. Now setting the tmux name to `julia_vscode_$[workspace]` ends up creating a tmux session with that literal name, rather than substituting the workspace name.

**Comment by ssfrr** [comment]
I just confirmed that this works fine on v1.38.2, so it does seem to be a regression.
