### ISSUE TITLE
Function with optional keyword arguments complained about by linter as possible method call error

### ISSUE THREAD

**Issue by touchft** [julia-vscode/julia-vscode#2351]
The issue still there, no matter I add package `LanguageServer.jl` or not.

**Comment by davidanthoff** [comment]
Can you provide a bit more information what you are actually trying to do? You should never have to interact or install LanguageServer.jl at all when you use the extension, so at the moment it is not clear to me what you are actually doing, or trying to do.

**Comment by pfitzseb** [comment]
The case in #2115 is actually fixed:
![grafik](https://user-images.githubusercontent.com/6735977/128625484-fe93ef89-9362-4a1f-8902-f357a36fd88b.png)

**Comment by touchft** [comment]
With the following code: 
```julia
f(s::Int, p::Int) = s + p
f(s::Int; k::Int) = f(s, k)
f(1, k=2)
1
```

I get:
![123](https://user-images.githubusercontent.com/12428354/130360358-c1dbde10-3380-4d09-8656-c217dc097981.png)
