### ISSUE TITLE
Dismissing executable error now always goes to settings

### ISSUE THREAD

**Issue by maleadt** [julia-vscode/julia-vscode#2353]
I only want to use the highlighting capabilities of this plugin (the language server doesn't play nicely with compiler-y packages), so I've set the `julia.executablePath` to `/bin/false`. That works fine, even though I always get to click away a popup complaining that the language server doesn't work:

![image](https://user-images.githubusercontent.com/383068/128861945-7c96515e-4e2a-4c6a-aee7-174cd6e89de7.png)

Since a couple of days (?), even if I dismiss the pop-up by clicking the x, I get redirected to the Settings page:

![image](https://user-images.githubusercontent.com/383068/128862069-4051f827-7fd1-4a0b-b4f5-901e0c83d509.png)

That's annoying, as I don't want to set the executable path to something valid.

Usnig vscode 1.59.0 (on Arch Linux, but using the binary package), plugin v1.3.27.

**Comment by pfitzseb** [comment]
> I only want to use the highlighting capabilities of this plugin (the language server doesn't play nicely with compiler-y packages)

FWIW, Julia syntax highlighting now ships with VSCode, so you might not even need this extension at all ;)

**Comment by maleadt** [comment]
Ah, good to know, thanks!

**Comment by pfitzseb** [comment]
That said, I'm always happy to try and improve the LS so that it can handle a wider range of use cases (just in case you have any specific complaints/errors when working on compiler-y projects).
