### ISSUE TITLE
Switch back to local REPL

### ISSUE THREAD

**Issue by hdavid16** [julia-vscode/julia-vscode#2355]
I'm not sure if there is a command for this, but I have connected to an external REPL and would now like to connect back to the VSCode REPL. Is there a way to do this?

I tried `Julia: Start REPL`, but I can't `Alt + Enter` code into the REPL I already had open in VS Code before connecting to an external REPL. I can `Ctrl + Enter` though...

Thanks!

**Comment by pfitzseb** [comment]
You can use `Julia: Stop REPL` for that. I'll add a dedicated command for that (probably `Julia: Disconnect from REPL`), which should be a bit easier to find.
