### ISSUE TITLE
language server fails to start when using "~" alias for home directory

### ISSUE THREAD

**Issue by gszep** [julia-vscode/julia-vscode#2363]
~I'm using the [Remote SSH extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh) to open a workspace on an ubuntu 18 server~. I've added julia to the remote environment
Edit: this problem has nothing to do with SSH
```bash
export PATH=$PATH:$HOME/.local/lib/julia/bin
```
and the `settings.json` reads
```json
{
    "julia.executablePath": "~/.local/lib/julia/bin/julia"
}
```
When I type `julia` into the remote terminal it opens a julia session with no problems. The language server however is stuck on the message `Starting Julia Language Server...` and whenever I try to execute an extension command --- for example Shift+Enter in a code block --- the log outputs the following javascript related error
```log
[2021-08-14 13:40:51.048] [exthost] [error] TypeError: Cannot read property 'file' of undefined
	at /home/gszep/.vscode-server/extensions/julialang.language-julia-1.3.28/dist/extension.js:2:679850
	at Generator.next (<anonymous>)
	at s (/home/gszep/.vscode-server/extensions/julialang.language-julia-1.3.28/dist/extension.js:2:677077) language-julia.executeCodeBlockOrSelectionAndMove
```
I have used these two extensions together before and it worked without issues. ~I suspect there is either some package version missing on this server, or that a recent update broke something.~ Would be great to track this down 🙏🏼

**Comment by gszep** [comment]
Solved it. You are not allowed to use `~` as an alias for the home directory. Should this be made more clear in the docs?

**Comment by pfitzseb** [comment]
We did resolve that before. Must've fallen under the table in a recent refactor.
