### ISSUE TITLE
1.3.28 breaks Executable Path

### ISSUE THREAD

**Issue by tbenst** [julia-vscode/julia-vscode#2366]
Last night, julia-vscode worked perfectly. This morning, it did not, and I got errors related to problems with the julia executable. It seems that 1.3.28 update hit 12 hours ago, and a path of `julia` no longer works. If I instead specify `/opt/julia/latest/bin/julia`, the extension works again

**Comment by davidanthoff** [comment]
Yes, we're working on fixing it, but haven't pinned down why exactly it is not working (we did rewrite those code parts, so no surprise that something broke, at some level).

Any more info you could provide would be helpful. What OS, how is julia on your `PATH`? Via a manipulation of `PATH` or via symlinks?

**Comment by ZacLN** [comment]
Another datapoint - linux, symlink in `/usr/bin/`

**Comment by davidanthoff** [comment]
I'm setting up my Ubuntu virtual machine right now :)

**Comment by davidanthoff** [comment]
I can reproduce it now, so no need for more info, now I just need to debug it.

**Comment by tbenst** [comment]
sorry for my delay, I'm on Ubuntu where I use `zsh` as my login shell. zsh in turn gets its path from `~/.zshrc`, where I have a line that says `export PATH="/opt/julia/latest/bin:$PATH"`

**Comment by davidanthoff** [comment]
New insider build 1.3.29 out, could you give it a try whether that fixes it?

**Comment by wherrera10** [comment]
It works, fixing the broken Julia extension issue with executablePath (windows 10) just now here.

**Comment by RoyiAvital** [comment]
Version `1.3.29` seems to solve the issue on my system (Windows 10 + [JuliaWin](https://github.com/heetbeet/juliawin)).
Thank you for the prompt response.

By the way, could you please update `CHANGELOG.md`?
It will be great to have release notes for each new version.
