### ISSUE TITLE
Test support

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/julia-vscode#2367]
I looked into the new test API, played around a bit with it [here](https://github.com/julia-vscode/julia-vscode/pull/2350) and generally started to think how we might best integrate. Here are my current thoughts.

# Overview

There are a bunch of things that need to happen:
1. Tests detection. This populates the test explorer view and enables the in-editor controls to run tests.
2. Running tests. Well, what it says ;)
3. Potentially down the road detection of updates in the tested code so that we can trigger automatic reruns.

## Test detection

I think for this one we should go with a LS based solution, i.e. static source code analysis test detection. We want the list of tests to be up-to-date as one types, plus the annotations in the currently open editor should also be correct as one types, and so I think realistically this is the only way to achieve that. I think we also want these things to update without a file save, which again essentially means a LS based solution is our only option. Also, I think this could be _very_ simple. We could essentially just have some custom messages that are analog to diagnostic messages that are sent from the LS to the client that return the ranges of each individual test item in a given file.

## Running tests

We want to run tests quickly, so I think what is out of the question is to start a new Julia process for every small test item one wants to run. I think we probably want to have a "test server", which would just be a Julia process that is connected to our extension via JSON-RPC, and then we can trigger specific test runs via messages to that test server. We'll also want the debugger integration, so we'll need JSON-RPC in that process in any case.

Generally I'm thinking that we would auto-load Revise in that test server, so that it can pick up changes in the package that is being tested via that and without a restart of the process. If there is a change that Revise can't handle, the test server could send a message to the client a la "You need to restart me", and then the client could restart the test server.

## Detection of updates to the code that is being tested

Not really sure, haven't thought too much about it :) Revised based as well, maybe?

# Proposal A

Here is one concrete proposal how we could do all of this. I think we should iterate on this, so this is just a starting point really.

We introduce a new macro called `@testitem`. A test item is the smallest unit of tests that can be run individually and correspond to a test item in the VS Code API. A typical `@testitem` would have various calls to the existing `@test` macros in it. In some way a `@testitem` is similar to a `@testset`, but we would have some very strict rules about execution of those. And they can also not be nested, for example.

A `@testitem` can have a "hierarchical" name. Say `@testitem "Foo.Bar.Something else" begin`. That hierarchy would appear in the tree view of VS Code when test items are surfaced in the UI.

A `@testitem` can appear _anywhere_, like in ReTest.jl or Rust. So it can also appear inside the package code itself, or in the `test` folder. The macro itself _always_ returns nothing, i.e. when someone uses the package, none of the test code is in the package. How can the code then ever run? The design here is that any test runner will extract/detect that test code by parsing source files, not by running them. NOTE TO SELF: take a closer look how ReTest.jl does this, and whether that is a better design.

Whenever a `@testitem` is run (for example by our test server), the code from within the test item block is put into an enclosing `module`, and then the entire module is evaluated. Those modules will always use the test environment of a project.

# Next steps

I think at this point we should collect some feedback and brainstorm about all of this. We obviously don't want to create something that only works in VS Code, while at the same time my sense at the moment is that we probably need something new in general because the VS Code scenario does have requirements and capabilities that probably aren't really covered by the existing stuff. But maybe I'm wrong, and we could just reuse something that already exists :) I think another goal here should be that ideally what we create here (if we created something new) will become the "new" standard lib test system.

CC @rfourquet.

**Comment by johnnychen94** [comment]
How does this proposal handling test-only dependencies if the test items live in `src/`?

**Comment by davidanthoff** [comment]
I think we would just always run tests in the test env of the project, right? So both tests in `test` and inline tests.

**Comment by johnnychen94** [comment]
If inline tests require a test-only dependency, where should the `using XXX` code be put?

For instance, how would you make this [Query test on DataFrame](https://github.com/queryverse/Query.jl/blob/e36d8af8aaec4673846a24ffb9bf68fbf5edf02c/test/runtests.jl#L44-L54) and inline test? Where should we put `using DataFrames`?

**Comment by davidanthoff** [comment]
I had been thinking inside the `@testitem` macro. So it might look like this:
```
@testitem "Foo.Bar" begin
  using DataFrames

  # Rest of the test code here
end
```
Essentially a `@testitem` would just be very similar to being a module (in fact, under the hood it would be a module).

**Comment by johnnychen94** [comment]
Thanks for the clarification. I get your points now. But I have to admit that this is a bit strange to have some test-only dependencies and `using DataFrames` in `src/`. It can be very confusing when this `using DataFrames` is actually a no-op.

> The design here is that any test runner will extract/detect that test code by parsing source files, not by running them.

Instead of parsing, how about having a global testitem stack per package, and let `@testitem` macro to push the test codes to the global stack. I'm not macro expert so the codes won't run, but I hope you get the ideas:

```julia
function _testitem(expr)
    on_test_mode() || return nothing
    push!(TESTITEM_STACK[get_current_pkg_uuid()], expr)
end

function run_testitem(pkg_uuid)
    foreach(generate_test_modules, TESTITEM_STACK[pkg_uuid])
end
```

**Comment by davidanthoff** [comment]
Yeah, I have to admit I'm also not yet fully sold or clear how these inline tests would work in detail :)

At least for test detection inside VS Code I think we'll want to use parsing no matter what, I don't think any other solution would a) be as instant and allow us to detect changes to the set of test items as users type, and b) for example also allow us to reliably detect test items if there is a typo say in one source file. With the parsing story we can just ignore that and still detect everything else, but if we were to rely on running Julia code to detect tests that wouldn't work.

But your idea for how these `@testitem` macros should be implemented when they are run outside of VS Code might be good. I'm not sure at the moment.

**Comment by dpinol** [comment]
hi,
is there currently any workaound to activate vscode linter within tests?
This is highlighted as an error
`"as"=3`
but this isn't

```
 rr()=2
 rr(3)
```
thanks

**Comment by adolgert** [comment]
I love the "feedback and support" issue. I looked through testing libraries and note that many of them redefine the @testset macro for other purposes: to save a test for later running (Jute, XUnit, and ReTest), to change test display, or to change metadata about tests. I'll list them here:

- https://github.com/fjarri/Jute.jl
- https://github.com/RelationalAI-oss/XUnit.jl
- https://tkf.github.io/LiterateTest.jl/dev/
- https://github.com/apieum/Maracas.jl
- https://github.com/YingboMa/SafeTestsets.jl
- https://github.com/mlhetland/DotTestSets.jl
- https://github.com/ssfrr/TestSetExtensions.jl
- https://github.com/JuliaTesting/ReTest.jl
- https://github.com/JuliaTesting/TestReports.jl
- https://github.com/Jutho/TestExtras.jl

There are two packages that change test discovery.
- https://github.com/IainNZ/Pukeko.jl, by using modules that are specifically for testing.
- https://github.com/pengwyn/EyeOfRa.jl, using Revise in a way similar to your suggestions above.

Lastly, loading packages within the testitem could have problems similar to what SafeTestsets experiences. You can see in this issue (closed as "won't fix"), that there is a package loading problem that prevents test from using macros in imported packages.
- https://github.com/YingboMa/SafeTestsets.jl/issues/3

You have a challenge for designing this test support because the Julia testing ecosystem is young. If there's a way to focus the test support on discovering tests using the Language Server (LS), and to leave room for test definitions to change, that might support some of these other inventive testing extensions.

**Comment by davidanthoff** [comment]
> Lastly, loading packages within the testitem could have problems similar to what SafeTestsets experiences. You can see in this issue (closed as "won't fix"), that there is a package loading problem that prevents test from using macros in imported packages.

Ah, very interesting! I think, actually, that my proposal where tests are discovered via syntactic analysis and then just run completely separately would get around that. The actual `@testitem` macro would just expand to nothing, and then the test code would be discovered by parsing the file separately, and then the code inside the `@testitem` macro would essentially be `eval`ed in some form, and I think that should take care of this macro presence thing.

Thanks a lot for all these pointers, super helpful!

**Comment by fonsp** [comment]
[Deno](https://deno.land/)'s VS Code extension is a great example of close integration between the testing stdlib and the LSP, which gives awesome features like [inline buttons to run a specific test set](https://user-images.githubusercontent.com/6933510/164501398-fade2d37-0431-4c09-8864-bd65366757ff.png) and the [Testing API GUI](https://deno.com/v1.21/deno-lsp-testing.mp4). 😍

**Comment by davidanthoff** [comment]
Yeah, I like these inline buttons a lot, Rust also has them. For some reason the native test VS Code UI doesn't provide that, though, so we would have to put that into the LSP and then hook events there up manually with the test execution API in VS Code... My thinking is that we would do that as a second phase. The integration with the rest of the test UI is fairly complete in the PR where I'm working on this.

**Comment by davidanthoff** [comment]
This is implemented now.
