### ISSUE TITLE
native notebook - cannot execute cells

### ISSUE THREAD

**Issue by phlavenk** [julia-vscode/julia-vscode#2383]
Hi,
when using the native (experimental) support of notebook in julia extension and VSCode (no Jupyter extension installed), I cannot execute cell and I get a warning with ?probably? miss-spelled path to the notebook (its c:\Users\ ...):
![image](https://user-images.githubusercontent.com/12131440/130029855-406af1a4-1a75-4fec-9c05-165b437711a5.png)

windows 10 64b
vscode 1.60-0-insider
julia-insider 1.3.30
julia 1.6.2 (oficial build)

**Comment by Telcrome** [comment]
I'm not a maintainer of this repo, but it might be interesting for you that it works well in WSL2 for me:

![image](https://user-images.githubusercontent.com/4445277/130315993-260a9552-5b12-4c9c-a77b-f298f74a06ba.png)

**Comment by davidanthoff** [comment]
That to me looks like an upstream bug, that error message is emitted in VS Code itself... CC @DonJayamanne.

**Comment by DonJayamanne** [comment]
@davidanthoff I'll check this out tomorrow. Please could you give me permissions to transfer this issue to the VS Code repo. Or @phlavenk please could you file a bug on the VS Code repo here https://github.com/microsoft/vscode/issues/new?assignees=&labels=&template=bug_report.md

**Comment by phlavenk** [comment]
Quick update: 
Somehow, it looks like some old ipynb files refuse to get connected with the notebook infrastructure  - cannot execute cells with this weird error message about the non-existing path. Any newly created notebook, regardless of the filename length or complexity, just work...
So I'm not able to give a clear way how to reproduce the problem. So I'm thinking of closing the issue and will reopen it if I have a better understanding of what is going on.

**Comment by pfitzseb** [comment]
Maybe something problematic in the metadata?

**Comment by phlavenk** [comment]
I didn't observe the reported issue for quite a while, so closing.
