### ISSUE TITLE
completion in notebook stucked in one cell

### ISSUE THREAD

**Issue by Xinyu-Wu-0000** [julia-vscode/julia-vscode#2385]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/57612792/130251983-9723bd79-1ca3-49f3-8403-7cefe8e3a28c.png)
![image](https://user-images.githubusercontent.com/57612792/130252101-446f794e-1859-4364-a9df-1552e460fd45.png)

In the second cell, completion failed.

Extension version: 1.3.30
VS Code version: Code - Insiders 1.60.0-insider (c08913337cb8b95493be8e99d62e0b3241563f6b, 2021-08-19T05:15:56.182Z)
OS version: Linux x64 5.11.0-31-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.41GB (1.51GB free)|
|Process Argv|--unity-launch --crash-reporter-id 43d31d55-f7ab-4c13-ac5c-382630e82534|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
pythonvspyt639:30291487
pythontb:30258533
pythonvspyt551:30291412
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
pythonvsuse255:30319630
00j7a122:30294756
vscod805cf:30301675
pythonvspyt200:30323110
vsccppwtct:30312693
pythonvssor306:30340298
bridge0708:30335490
pygetstartedt2:30353727
dockerwalkthrucf:30348714
bridge0723:30353136
pythonrunftest32cf:30353182
pythonf5test824cf:30353184
javagetstartedt:30350119

...

</details>

<!-- generated by issue reporter -->

**Comment by pfitzseb** [comment]
Yeah, right now cells aren't connected for the LS, so objects defined or imported in another cell aren't available.

**Comment by tfiers** [comment]
What needs to be done to fix this?

(I just opened a notebook in vscode by accident.. and was _very_ pleasantly surprised.
It has gotten so much better than a year or two back.
So much so that I decided to switch from the browser/Jupyter to vscode.
Popup documentation and completions are a necessity though).

**Comment by pfitzseb** [comment]
Dup of https://github.com/julia-vscode/julia-vscode/issues/2016.
