### ISSUE TITLE
Formatting fails even though JuliaFormatter can format it

### ISSUE THREAD

**Issue by Volker-Weissmann** [julia-vscode/julia-vscode#2418]
Take a look at the following, wrongly formatted code
```
function weird()
    begin
        if true
        end
        print("abc")
    end
end

    print("wrong_ident")
```
`JuliaFormatter.jl` can fix this code, but if I run F1 `Format Document`, it does not fix this code, and it does not log anything.

**Comment by pfitzseb** [comment]
We don't currently use JuliaFormatter, but will with the next minor release (which should be out next week or so).
