### ISSUE TITLE
kernel remains open after I close Vscode

### ISSUE THREAD

**Issue by puerco-errante** [julia-vscode/julia-vscode#2429]
Issue Type: <b>Bug</b>

If I open a Julia Jupyter notebook and then close VSCode, I can run `top` and see that the Julia process is still there, consuming a significan amount of Ram. If I reopen VSCode, it doesn't seem that it re-connects to it, but instead opens a new one.

It also seems to me that even previewing a notebook causes a kernel to launch, and this then remains open even if I don't fully open said notebook.

Extension version: 1.3.33
VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:43:02.136Z)
OS version: Linux x64 5.4.0-81-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8 x 1401)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|5.75GB (0.22GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id f8631473-5e30-4634-9d72-b9d9409c1bc2|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspyt653:30270858
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805cf:30301675
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
vsccppwtct:30329789
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonf5test824cf:30361778
vsdyn321cf:30356811
pythonvspyt187cf:30362783
pydsgsc2:30361791
vscus224:30358039
vssid140cf:30362081

```

</details>

**Comment by pfitzseb** [comment]
Can you show the top/htop output for these processes? I'm particularly interested in the startup arguments and PPIDs.

**Comment by puerco-errante** [comment]
Yes!
```
top - 12:09:01 up  2:01,  1 user,  load average: 1,16, 0,66, 0,49
Tasks: 356 total,   1 running, 353 sleeping,   0 stopped,   2 zombie
%Cpu(s):  3,0 us,  0,7 sy,  0,0 ni, 95,6 id,  0,7 wa,  0,0 hi,  0,0 si,  0,0 st
MiB Mem :   5885,1 total,    814,8 free,   3589,0 used,   1481,4 buff/cache
MiB Swap:   3918,5 total,   2230,8 free,   1687,7 used.   1927,4 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
-----
  10669 puercoe+  20   0 1801996   7996   1344 S   0,0   0,1   0:18.49 julia
  11837 puercoe+  20   0 4763416 930552   1688 S   0,0  15,4   1:48.38 julia
```
I had opened just one notebook, ran some cells, and then closed Vscode.

**Comment by davidanthoff** [comment]
What kernel are you using? I.e. do you have the native Julia notebook controller enabled in the settings and are using that?

I'm asking because I'm pretty positive that there is no way that we will start our kernel if you just look at a notebook, maybe you are actually using the IJulia kernel via the Jupyter extension?

**Comment by puerco-errante** [comment]
You're totally right!
I checked the Julia extension settings and indeed the native Julia notebook controller was inactive :(
Sorry for the false alarm and thanks for the help.
Cheers!
