### ISSUE TITLE
REPL 

### ISSUE THREAD

**Issue by emergentharmony** [julia-vscode/julia-vscode#2436]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

If I open VScode and then start a julia file I can press a keyboard shortcut to get the REPL going. But if I close the REPL and the use the same keyboard shortcut, no REPL.

I have to close VScode and start all over again.

Am I missing something?

Thanks

Extension version: 1.3.34
VS Code version: Code 1.60.0 (Universal) (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:54:53.442Z)
OS version: Darwin arm64 20.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|8.00GB (0.12GB free)|
|Process Argv|--crash-reporter-id 73aef55e-a00b-4d13-b898-439eea66fc9d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30358480
pythondataviewer:30285071
pythonvsuse255:30340121
vscod805:30301674
pythonvspyt200:30340761
vscextlangct:30333562
binariesv615:30325510
pythonvssor306:30344512
bridge0708:30335490
pygetstartedt2:30360495
bridge0723:30353136
pythonrunftest32:30361774
pythonf5test824:30361777
vsdyn420:30356812
pythonvspyt187:30362782
pydsgsc2:30361791
vscus224:30358039
vssid140cf:30362081

```

</details>

**Comment by pfitzseb** [comment]
You can use the `View: Toggle Panel` to unhide the bottom panel (assuming you just clicked the x to hide the REPL and not the trashcan to actually close it). #2437 will also make sure that repeated invocations of `Julia: Start REPL` will move focus as expected.
