### ISSUE TITLE
Docstrings are not attached to functions when pasting into terminal

### ISSUE THREAD

**Issue by tkoolen** [julia-vscode/julia-vscode#244]
Minor thing.

Copy the following code:
```julia
"""
bla
"""
function f(x)
    x
end
```
and paste it into the VSCode Julia terminal. The docstring will be evaluated separately, so `?f` won't return the expected documentation. This behavior is different from the Julia REPL.

**Comment by ZacLN** [comment]
Maybe addressed by https://github.com/JuliaEditorSupport/julia-vscode/issues/494
