### ISSUE TITLE
How to disable zoom in/out features in the plot pane?

### ISSUE THREAD

**Issue by ChenZhao44** [julia-vscode/julia-vscode#2449]
I'm using Vega.jl as an interactive plot backend. In the previous version of julia-vscode, it works well.
However, the latest version support zoom in/out in the plot pane. And the zoom in/out gestures are not compatible with the interacting gestures (like drag and drop) in Vega.jl.
So I'm wondering whether there are any methods to disable the zoom in/out features in the plot pane.

**Comment by pfitzseb** [comment]
There isn't. I would've expected event propagation to handle this case fine, but obviously it doesn't. Can you give me a small MWE for creating an interactive Vega plot so I can fix this?

**Comment by ChenZhao44** [comment]
https://gist.github.com/ChenZhao44/3182660c09efaced17d4df2507197940
Here is an example for plotting an interactive graph with Vega.jl.

**Comment by pfitzseb** [comment]
Thanks. The best solution I can come up with for now is to require pressing Alt/Option to get panning/zooming.
