### ISSUE TITLE
Investigate TraceCalls.jl

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/julia-vscode#245]
https://github.com/cstjean/TraceCalls.jl

I believe it has Atom integration, so we should check whether we can also integrate it with our extension.

**Comment by ZacLN** [comment]
Yep this would be great

I was thinking of a simulated debugger along the same lines where we use the scope/namespace info to allow running to a single breakpoint (implemented as an inserted macro) where upon we error out returning all those  variables

**Comment by lassepe** [comment]
TraceCalls.jl seems to be dead. So I guess this can be closed.
