### ISSUE TITLE
Pkg.update() issue in Jupyter notebook

### ISSUE THREAD

**Issue by daler6** [julia-vscode/julia-vscode#2452]
I am working with the experimental native Jupyter notebook integration, without installing the Jupyter extension for VSCode. after running a code block to start using the Pkg package (code is simply **using Pkg**), I create and run a code block to update any packages currently installed in the environment (code is simply **Pkg.update()**) I quickly get messages indicating that the registry has been updated and of and changes to the Project.toml and Manifest.toml files. It then indicates that it is Precompiling the project. At this point, it just keeps going without end, and proceeds to consume all the application memory until the computer reboots.

**Comment by pfitzseb** [comment]
I don't see how that would be related to VS Code. Do you not see the same issue with a Julia REPL?

**Comment by pfitzseb** [comment]
No, but there should be no difference between these two ways of calling Pkg.

**Comment by daler6** [comment]
OK, I have explored further. Obviously, there is a problem with how I have set up this environment. I'll try to redo.

Thanks for your help
