### ISSUE TITLE
No row numbers inside Julia Table

### ISSUE THREAD

**Issue by Julpro21** [julia-vscode/julia-vscode#2458]
Please add row numbers inside Julia Table, similar to column numbers, without adding/installing any external packages. It would be so convenient. Thank you for your hard work. Please see the attached screenshot.

<img width="1742" alt="row_numbers" src="https://user-images.githubusercontent.com/90942844/133867409-f4088bfb-66d6-4c28-a163-757bce4bdfb2.png">

**Comment by pfitzseb** [comment]
This got implemented in https://github.com/julia-vscode/julia-vscode/pull/2415.
