### ISSUE TITLE
[Q] How does this extension make the REPL "enter" a module?

### ISSUE THREAD

**Issue by NightMachinery** [julia-vscode/julia-vscode#2464]
I have seen some attempts on this, but none of them work with latest Julia version:
-- @2019 [JuliaLang/julia-33872 {WIP} REPL: allow switching contextual module by rfourquet](https://github.com/JuliaLang/julia/pull/33872)

-- @unmaintained/2020 [GitHub - sglyon/REPLMods.jl: Mod your REPL](https://github.com/sglyon/REPLMods.jl)

-- @unmaintained/2017 [GitHub - tshort/REPLinModule.jl: REPL mode to evaluate in a module](https://github.com/tshort/REPLinModule.jl)

But I think this extension will probably be the most used code to implement this functionality. So it would be good to refactor this functionality to a new, standalone package.

(I need this functionality for the emacs Julia REPL.)

**Comment by pfitzseb** [comment]
There's nothing here that switches the context/module REPL evaluation works in.
Something like https://gist.github.com/pfitzseb/8fab21f09d6c15246d4a0960af3c65b1 should do the trick though.
