### ISSUE TITLE
Red line (previous error) can not be deleted

### ISSUE THREAD

**Issue by KronosTheLate** [julia-vscode/julia-vscode#2466]
Tiny annoyance:

So when a line errors, it is highlighted red. Great. But sometimes, I can not make the red highlight go away. Below is a GIF showing the behavior:
![MjqeVMCxng](https://user-images.githubusercontent.com/61620837/134513997-4923f8ad-4e74-4583-926e-80dfff5333cb.gif)

Anyone else experiencing this?
Do anyone know what may cause it, and how to make it go away?

**Comment by pfitzseb** [comment]
Does the `Julia: Clear All Inline Results` command do anything?

**Comment by KronosTheLate** [comment]
It does indeed fix it, thanks! I did not know about that function, but I think I will be using it a lot, as I have been missing something like it.

So that is a workaround. But I find the bug itself quite curious...

**Comment by xgdgsc** [comment]
I still see this occasionally. Is it possible to run `Clear All Inline Results` after successful eval on the same line?

**Comment by pfitzseb** [comment]
That's already happening, but apparently some of the char-range logic is broken in certain edge cases.
