### ISSUE TITLE
Interrupt (Ctrl+C) often crashes the REPL

### ISSUE THREAD

**Issue by BioTurboNick** [julia-vscode/julia-vscode#2469]
I don't think it used to be this sensitive. Lately, it seems like interrupting long-running processes ends up killing the REPL. Is there an error log being kept somewhere? I just noticed, and turned on, crash reporting, in case that helps.

Here's a simple trial:
```
using StaticArrays
hcat(map(x -> SA[1, 2, 3], 1:8000)...)
# hit Ctrl+C
```

**Comment by pfitzseb** [comment]
Nothing changed about this recently and I can interrupt your example just fine.

**Comment by BioTurboNick** [comment]
```
The terminal process "julia '-i', '--banner=no', '--project=C:\Users\ncb20\.julia\environments\v1.6', 'c:\Users\ncb20\.vscode\extensions\julialang.language-julia-1.4.3\scripts\terminalserver\terminalserver.jl', '\\.\pipe\vsc-jl-repl-81d62ca8-8258-4bab-865d-90e276a6cf5f', '\\.\pipe\vsc-jl-cr-8a35fa9e-c390-4433-91ec-a3a41549679c', 'USE_REVISE=true', 'USE_PLOTPANE=true', 'USE_PROGRESS=true', 'DEBUG_MODE=false'" terminated with exit code: 3221225786.
```

**Comment by pfitzseb** [comment]
Ah, Windows. No wonder :P
It might be possible to improve the situation (generally, and on Windows specifically), but I don't know how...

**Comment by BioTurboNick** [comment]
This may be the cause:

https://stackoverflow.com/questions/25444765/why-does-a-non-interactive-batch-script-think-ive-pressed-control-c#:~:text=The%20magic%20here%20is%20in%20exit%20code%203221225786%2C,so%20as%20expected%2C%20it%20was%20aborted%20with%20STATUS_CONTROL_C_EXIT.

That exit code indicates that the process was terminated with CTRL+C. So is it not marking the interrupt as handled, or something?

**Comment by BioTurboNick** [comment]
Where would such a thing be handled within VSCode/Julia? I might poke around if I can find it.

**Comment by BioTurboNick** [comment]
I'm going to close this as I haven't encountered this in a while.
