### ISSUE TITLE
Plotting pane slow at rendering SVG (the default MIME-type)

### ISSUE THREAD

**Issue by ma-laforge** [julia-vscode/julia-vscode#2474]
It appears that the SVG rendering facilities for VSCode's integrated plot pane is noticeably slow --- even when comparing to the inline plots rendered from the Jupyter extension.

The difference is obvious when using Plots.jl (for example) to plot over 1k points using markers (ex: scatterplot).

More details & sample code on discourse:
--> https://discourse.julialang.org/t/why-is-julias-graphics-system-so-slow/68750

**Comment by axsk** [comment]
Same as https://github.com/julia-vscode/julia-vscode/issues/2070
