### ISSUE TITLE
No plot output

### ISSUE THREAD

**Issue by Peter-Jolly** [julia-vscode/julia-vscode#2479]
For some months one of my programs is now not able to output any plots (Windows 10, Julia 1.6.3 latest version of Vscode). However, a small trivial program, shown below, does work with the plot navigator window correctly displaying the plot. However, if I insert this trivial program into my main program, the plot is not made! As a check, when I reach the plot command in my program, I print out the data before plotting, to ensure the data is fully defined. It just seems to me that the plot command is being ignored in my main program, for some unknown reasons and this problem has been created by recent updates to Vscode. Is anyone else experiencing the same issues? Any ideas how to fix or is this a bug now being addressed? Thanks
```
# test plot package
using Plots
y=rand(300)
plot(y)
#print(y)
```

**Comment by Peter-Jolly** [comment]
Many thanks - putting display around the plot command solved the problem. The question remains why is the display(plot()) NOT required for small trivial programs? Anyway, I am very pleased I now have a solution.

**Comment by Peter-Jolly** [comment]
Solved but not sure why!

**Comment by pfitzseb** [comment]
So when you use the REPL or inline evaluation, the `plot` function returns an object that will be `display`ed by the REPL/VS Code automatically. If you just plot inside a function the returned object is internal, so you need to call `display` yourself.

**Comment by Peter-Jolly** [comment]
Ok. Many thanks
