### ISSUE TITLE
Grey plotpane on remote server

### ISSUE THREAD

**Issue by theogf** [julia-vscode/julia-vscode#2487]
When plotting heavy plots with Plots.jl + GR, the plot pane turns grey (see screenshot) after a few seconds. Closing it and reopening it solves the problem.

![image](https://user-images.githubusercontent.com/11480067/135451114-977d463b-d6a8-4dca-ba74-c2a1ccb2891e.png)

Here is a MWE:
```julia
using Plots
scatter(rand(20000), rand(20000)) |> display
```

**Comment by Sov-trotter** [comment]
I can't seem to reproduce this. I wonder why you use `display` since in-memory plots are automatically displayed.

**Comment by pfitzseb** [comment]
We've recently switched to using png instead of svg for plots by default, which should make this bug harder to hit.

**Comment by theogf** [comment]
How hard would it be to be able to chose the default output as an user option?

**Comment by pfitzseb** [comment]
Not particularly hard, but imho this should be handled in user code instead. Just call `display` with the right MIME type manually or define `showable` to exclude certain types.
