### ISSUE TITLE
startup.jl ignored with new native notebook support

### ISSUE THREAD

**Issue by favba** [julia-vscode/julia-vscode#2495]
I have my own Plots configuration on my `~/.julia/config/startup.jl` file
Example:
```julia
const PLOTS_DEFAULTS = Dict{Symbol,Any}(:legend=>:outertopright,
				        :palette=>:tab10,
				        :linewidth=>1.5,
				        :markershape=>:auto,
				        :markersize=>3.0)
```

When I open an notebook using Jupyter directly on my web browser the startup.jl file is read and the configuration used.
When I open the same notebook on VS Code with the Julia extension the startup.jl file is ignored.

**Comment by pfitzseb** [comment]
Fixed by https://github.com/julia-vscode/julia-vscode/pull/2536.
