### ISSUE TITLE
Extra characters appended when pasting text of certain size into Julia REPL

### ISSUE THREAD

**Issue by BioTurboNick** [julia-vscode/julia-vscode#2501]
https://github.com/microsoft/vscode/issues/112831

Reproduction:

Paste "combinednormalizedmontecarlomeasurementsc" at prompt (right click, excluding quote marks)

The VSCode team looked into it and they believe it's specific to the extension:

> It looks like the Julia REPL is not handling bracketed paste mode correctly and sending it back to print 01~. \x1b[200~ and \x1b[201~ wrap pasted text only when requested by the REPL, these are meant to be stripped out by Julia after accepting them.

The logs they looked at:
```
xterm.js: sending data "�[200~combinednormalizedmontecarlomeasurementsc�[201~" (53) [27, 91, 50, 48, 48, 126, 99, 111, 109, 98, 105, 110, 101, 100, 110, 111, 114, 109, 97, 108, 105, 122, 101, 100, 109, 111, 110, 116, 101, 99, 97, 114, 108, 111, 109, 101, 97, 115, 117, 114, 101, 109, 101, 110, 116, 115, 99, 27, 91, 50, 48, 49, 126]
LogService.ts:62 xterm.js: parsing data c
LogService.ts:62 xterm.js: parsing data ombinednormalizedmontecarlomeasurementsc01~
```

**Comment by pfitzseb** [comment]
Hm, this is weird. It's definitely not an issue with the Julia extension, but something in the Julia REPL fails to handle the escape sequences properly (maybe they're just disabled on Windows and other terminals don't send them or something).

**Comment by BioTurboNick** [comment]
But I can't get it to happen in the normal Julia terminal, only the one inside VSCode.

**Comment by BioTurboNick** [comment]
This code could be the offender? but I'm not sure how to debug an extension right now to check:
```
async function executeCodeCopyPaste(text: string, individualLine: boolean) {
    if (!text.endsWith('\n')) {
        text = text + '\n'
    }

    await startREPL(true, true)

    let lines = text.split(/\r?\n/)
    lines = lines.filter(line => line !== '')
    text = lines.join('\n')
    if (individualLine || process.platform === 'win32') {
        g_terminal.sendText(text + '\n', false)
    }
    else {
        g_terminal.sendText('\u001B[200~' + text + '\n' + '\u001B[201~', false)
    }
}
```

**Comment by pfitzseb** [comment]
I also get this for a normal VS Code terminal in which I start a normal Julia REPL.
That function doesn't run when pasting code into the REPL, so I don't think it'd be related.

**Comment by BioTurboNick** [comment]
Hmm... I'll try poking around at some point.

**Comment by BioTurboNick** [comment]
Over on the VSCode issue, it was suggested that there could be something going on with ConPTY and xTerm? Because the issue only occurs inside VSCode. As far as I can tell, the initial bracketed character never makes it to the REPL for processing in VSCode.

![image](https://user-images.githubusercontent.com/1438610/143317138-861d54a2-d991-4d65-997c-8fa930aa66b4.png)
![image](https://user-images.githubusercontent.com/1438610/143317175-6ad09a0d-5cb6-431e-a3d2-64d555c19739.png)

**Comment by BioTurboNick** [comment]
I've confirmed that the issue is not in this extension or Julia proper. It's somewhere in VSCode parts or the Windows console code, as the issue also appears in WSL alone running inside VSCode. Thus, I'm closing this.

**Comment by BioTurboNick** [comment]
It sounds like we may be blocked by https://github.com/microsoft/terminal/issues/395. Would it be possible to disable bracketed paste mode on Windows until this is fixed? Perhaps by overriding the `Terminals.enable_bracketed_paste` and `Terminals.disable_bracketed_paste` functions.
