### ISSUE TITLE
Error message not displayed in notebook UI with built-in renderer

### ISSUE THREAD

**Issue by ChrHorn** [julia-vscode/julia-vscode#2502]
Error messages in notebooks (`application/vnd.code.notebook.error` MIME with built-in renderer), are no longer displayed. Issue was introduced in the newest VS-Code version 1.61.1, works fine with older version 1.60.2.

![image](https://user-images.githubusercontent.com/17070041/137740632-1d503887-4d36-4eab-a038-be85b1e4f7a0.png)

This issue is about the built-in implementation without using the Juypter extension. There is a similar issue https://github.com/julia-vscode/julia-vscode/issues/2326 when using the Jupyter extension. 

VS-Code: 1.61.1
Julia: 1.6.3
OS: Windows 10

**Comment by jebej** [comment]
I am having the same problem. Is the problem with a redirected io stream? Why does the stacktrace show up but not the error message?

**Comment by pfitzseb** [comment]
Nah, the renderer just is Jupyter compatible now. This will be fixed by https://github.com/julia-vscode/julia-vscode/pull/2509.
