### ISSUE TITLE
Suggestion: Show table row numbers with vscodedisplay

### ISSUE THREAD

**Issue by einarpersson** [julia-vscode/julia-vscode#2505]
When printing a `TypedTable` in the REPL I can see row numbers like this
````julia
julia> mytable
Table with 8 columns and 3 rows:
     Brand      Tier      Quantity  Price  Cost  Revenue  Profit  Margin
   ┌────────────────────────────────────────────────────────────────────
 1 │ Company A  Premium   10        100    30    1000     700     0.7
 2 │ Company A  Economy   100       10     7     1000     300     0.3
 3 │ Company A  Standard  50        50     25    2500     1250    0.5
````

However, when I run `vscodedisplay(mytable)` I do not see any row numbers.

![image](https://user-images.githubusercontent.com/6043691/138395682-16f78946-9401-4e2a-9e71-d50837ab9eff.png)

Is that something you have considered adding, either as a default or as an option?

**Comment by pfitzseb** [comment]
This got implemented in https://github.com/julia-vscode/julia-vscode/pull/2415.
