### ISSUE TITLE
Julia: Stop REPL doesn' t stop julia in tmux mode

### ISSUE THREAD

**Issue by xgdgsc** [julia-vscode/julia-vscode#2506]
Currently the command `Julia: Stop REPL` doesn' t stop julia in tmux mode for me. And `Julia: Restart Kernel` fails for me. Now when I want to kill julia and restart to test some program I have to ctrl-D which leaves a dead tmux pane and kill it with `ctrl-b x` and rerun `Julia: Start REPL`. Is there a better way?

**Comment by pfitzseb** [comment]
Fixed in the next release.
