### ISSUE TITLE
NumThreads setting not used in persistent tmux mode

### ISSUE THREAD

**Issue by xgdgsc** [julia-vscode/julia-vscode#2510]
`NumThreads` setting not used in persistent tmux mode.

**Comment by pfitzseb** [comment]
Can't reproduce this.

**Comment by xgdgsc** [comment]
Have you tried on a remote server or local machine? Remote server doesn' t work for me.

**Comment by pfitzseb** [comment]
Both. Make sure you change the `Julia: Num Threads` setting on the remote though:
![image](https://user-images.githubusercontent.com/6735977/140481695-d85d9f4c-461b-46a2-ad8d-66f46d7a3a13.png)

**Comment by xgdgsc** [comment]
Oh. Seems it' s because I used https://github.com/gpakosz/.tmux . Removing that works.

**Comment by xgdgsc** [comment]
Nope. It' s not that config. If I start another tmux session with `tmux new -s  sync` first. Then run `Start REPL`,  `Threads.nthreads()` returns 1. If there is no other tmux session running and I run `Start REPL` ,  `Threads.nthreads()` returns what I configured.

**Comment by pfitzseb** [comment]
Right, the number of threads is set before starting the tmux session. So if you start it yourself then you're also responsible for setting up your environment as you want it to be.

**Comment by xgdgsc** [comment]
Maybe a workaround: https://stackoverflow.com/a/66531282/1136027

**Comment by pfitzseb** [comment]
Ah, I misunderstood your comment. Will fix.
