### ISSUE TITLE
Invalid formatting when combining function one-liners and ternary operators 

### ISSUE THREAD

**Issue by agucova** [julia-vscode/julia-vscode#2511]
I'm really lost here, I've gone through my code trying to find a minimally reproducible example, but I can't seem to reduce it further than this (it's working, valid code):

```julia
f(x, y) = x == 1 ? x : string(x) * y

function h(s)
    c = 'a'
    for x in s
        if x == c
            println(x)
        end
    end
end
```

Gets formatted to:
```julia
f(x, y) = x == 1 ? x : string(x) * y
    
function h(s)
    c = 'a'
        for x in s
        if x == c
        println(x)
        end
    end
end
```

Somehow the presence of the ternary operator, the one-liner function and the for loop all seem to matter. Maybe I'm missing something obvious.

This is with v1.4.3 of the extension on VSCode Insider v1.61.0.

**Comment by pfitzseb** [comment]
Closing this since the next version will use JuliaFormatter for formatting.
