### ISSUE TITLE
local variable used but hint shows it is not used

### ISSUE THREAD

**Issue by johnnychen94** [julia-vscode/julia-vscode#2514]
Julia-Insider v1.4.3

```julia
function f!(X, Y)
    @. X = Y
    return X
end
```

![image](https://user-images.githubusercontent.com/8684355/139470773-4e17aa46-fbc6-4486-a3aa-108ba033f784.png)

**Comment by pfitzseb** [comment]
Needs some special handling to tell the linter that `@. X = Y` doesn't introduce a new binding.
