### ISSUE TITLE
Feature proposal: debuggerDefaultInterpreted, everything else is compiled

### ISSUE THREAD

**Issue by MariusDrulea** [julia-vscode/julia-vscode#2516]
Currently there is a `debuggerDefaultCompiled` list of modules stored in the settings.json file. Everything not in this list is treated as interpreted by default.
Most of the time we only want to debug the code we write, not the julia code or the code of various installed packages. I think this defaults to most users. As a consequence, the list in `debuggerDefaultCompiled` get's pretty long and it's annoying to update it every time new packages and their dependencies are installed.

Therefore I think it is better to have a `debuggerDefaultInterpred` list and everything not in this list shall be treated as compiled by default. For instance, the only thing I will have in this list is the "Main" module and "MyOwnPackage".

(Maybe this is not the right place to post this, as it might lead to discussions... my apologizes. Please indicate the right place eventually. )

```
"julia.debuggerDefaultCompiled": [
        "Base.",
        "Base",
        "Core",
        "Core.Compiler.",
        "Core.IR",
        "A LONG LIST OF OTHER PACKAGES"
]
```

Proposed:
```
"julia.debuggerDefaultInterpreted": [
        "Main",
        "Main.",
        "MyOwnPackage",
        "MyOwnPackage."
]
```

**Comment by MariusDrulea** [comment]
To further motivate my proposal: I have just configured settings.json yesterday. Today I run a script using the GLMakie plotting library. And obviously, a lot of extra packages appeared as interpreted. In such conditions it's hard to maintain settings.json. I would have to do it every few days. Now imagine multiple people have to do this.

Anyway, until this feature proposal is hopefully implemented, I will try to do this programmatically, inside `launch_wrapper.jl". This is a reference page in this regard: https://discourse.julialang.org/t/debugging-in-juno-extremely-slow/53801/14. 

![image](https://user-images.githubusercontent.com/27725572/139720225-8eba2fe7-5859-415f-946a-12ced3459509.png)

**Comment by pfitzseb** [comment]
The issue with this is that higher order functions are very widely used and will break the expected debugging behaviour (of breakpoints working). 
I can definitely see why specifying a list of interpreted functions would be useful, especially since that what we have for Base already.

**Comment by pfitzseb** [comment]
Btw, did you consider enabling compiled mode? Or do you actually use breakpoints in your code and no higher order functions from packages at all?

**Comment by MariusDrulea** [comment]
Hi, I set breakpoints strictly in my code, nothing else. I have set everything else to "compile". So far I haven't use the compiled mode of the debugger. I just tried it out and it's interesting I can manually step inside a bar() function from foo(), but I cannot reach the bar() breakpoints while I am in foo() and press continue. But once I get inside the bar() (manually), then I can run until the next breakpoint. I'm curious why the compile mode does not take the breakpoints inside sub-functions, why are breakpoints related to compilation, cause they seem to be un-related.
`foo() calls bar()`

**Comment by pfitzseb** [comment]
Breakpoints don't work in compiled code, no matter whether that's because you toggled compiled mode or because you set a function as compiled.

**Comment by MariusDrulea** [comment]
So what's happening inside the compiled mode debug? Is my code compiled with -O1 option and without inline? I mean minimally compiled to avoid the interpreter?

**Comment by MariusDrulea** [comment]
> Compiled mode debugging is basically native execution. Anything that's not in compiled mode is run by JuliaInterpreter, which can be orders of magnitude slower.

Ok, than I will also use this from now on. Two options:
1. Compile mode + sys image for GLMakie
2. Interpreted mode for my code + everything else set as compiled (hopefully the default in the future) + sys image.

**Comment by MariusDrulea** [comment]
Question1:
If I set a package MyPackage to be compiled in the user_settings.json, and this package depends on other packages like Dep1, Dep2 which are not specified at all in the user_settings.json ----- does it means that MyPackage will always be compiled?

Question 2: MyPackage is set to compile and Dep1 and Dep2 are set explicitly to be interpreted. Does this affect the running of MyPackage calls (they shall still run in compiled mode, right?)

**Comment by pfitzseb** [comment]
Functions in MyPackage should always be compiled (in both cases). Functions in dependencies may or may not be compiled, depending on where they are called from (i.e. directly calling `Dep1.foo(MyPackage.MyStruct())` means it's interpreted, but everything that goes through `MyPackage` first will be compiled). Generally, there's no way to go from compiled code to interpreted code.

**Comment by MariusDrulea** [comment]
Ok,
Now I want to implement the compile everythin ```*``` **_option_**. This option tells us to scan all the packages and set them to be compiled. The exceptions to be interpreted are set with ```-``` as usual. Here I have set the code in my Main to be interpreted. This is the only package I want to debug.
```
"julia.debuggerDefaultCompiled": [
        "*", # this means all installed packages and their dependencies are compiled; except the ones specified bellow
        "-Main.Core.Main"        
    ],
```

Yes, I understand map(my_fun...) would no long call my_fun in debugger, but I can leave with this or I can specify map as interpretted. At the end this ```*``` is only an option, everyone shall be free to choose or not.

code to list all packages: 
```
using Pkg
all_packages = [last(p).name for p in Pkg.dependencies()]
```
@pfitzseb is ok if I proceed with a PR with the above proposal?

**Comment by pfitzseb** [comment]
https://github.com/julia-vscode/DebugAdapter.jl/pull/61 does that. I've called the option `ALL_MODULES_EXCEPT_MAIN`, since `*` conflicts with multiplication and it's very likely Main should be interpreted (you can always add it separately if not).

**Comment by MariusDrulea** [comment]
The ALL_MODULES_EXCEPT_MAIN is present in the 1.6.30 version so I did a test. It's super easy to use. 
There is however one problem left: _it does not seem to except "MAIN"_. The debugger does not step inside the `my_fun` function, in the example bellow. 

![image](https://user-images.githubusercontent.com/27725572/184123841-f2048686-810e-4505-a029-80db86c529d6.png)

**The code:**
```
function my_fun(N)
    x = N * rand(1000, 1000)
    y = N * rand(1000, 1000)

    s = sum(x .+ y)
    return s
end

N = 10
s = my_fun(N)
println(s)
```

Inside `settings.json` file:
```
"julia.debuggerDefaultCompiled": [
        "ALL_MODULES_EXCEPT_MAIN",
    ]
```

**Comment by pfitzseb** [comment]
Good catch. Should be fixed by https://github.com/julia-vscode/DebugAdapter.jl/pull/63.

**Comment by MariusDrulea** [comment]
I did an additional test to check if we can step inside the modules we specify as interpreted. This does not work, I _cannot step inside the `save` function of `FileIO`_. I have set the `FIleIO` as interpreted and made sure this settings is loaded into the UI.

**in settings.json:**
```
"julia.debuggerDefaultCompiled": [
        "ALL_MODULES_EXCEPT_MAIN",
        "-FileIO",               
        "-FileIO.",               
    ], 
```

**The code:**
```
using FileIO

function f()
    x = rand(100, 100)
    save("test.jpg", x)
end

f()
```

![image](https://user-images.githubusercontent.com/27725572/184162948-841ab7db-c30e-4628-944e-bc074a8afa3d.png)

**Comment by pfitzseb** [comment]
Will be fixed by https://github.com/julia-vscode/DebugAdapter.jl/pull/64.

**Comment by MariusDrulea** [comment]
Ok, I merged these two fixing branches together locally. Still the step into `save` does not work.
I have checked the log messages of the debugger and filtered by the `FileIO` text. `FileIO` is set to compiled in all such messages. 

```
	Line 22: │   params = VSCodeDebugger.DebugAdapter.DebugArguments(false, "debug_test.jl", ["ALL_MODULES_EXCEPT_MAIN", "-FileIO", "-FileIO."], false)
	Line 22: │   params = VSCodeDebugger.DebugAdapter.DebugArguments(false, "debug_test.jl", ["ALL_MODULES_EXCEPT_MAIN", "-FileIO", "-FileIO."], false)
	Line 36: │     "-FileIO"
	Line 37: │     "-FileIO."
	Line 133: │     "FileIO"
	Line 134: │     "FileIO"
	Line 141: │      1 1  1 ─     using FileIO
	Line 151: │     "FileIO"
	Line 152: │     "FileIO"
	Line 242: ┌ Debug: setting FileIO and submodules as compiled via ALL_MODULES_EXCEPT_MAIN
	Line 362: ┌ Debug: setting FileIO and submodules as compiled via ALL_MODULES_EXCEPT_MAIN
	Line 477: ┌ Debug: setting FileIO and submodules as compiled via ALL_MODULES_EXCEPT_MAIN
```

**Comment by pfitzseb** [comment]
Your exact case works fine for me with that PR.

**Comment by MariusDrulea** [comment]
Interesting. 
I have added some logs. It can be seen the function `function set_compiled_functions_modules!(items::Vector{String})` is called twice. Once for `["ALL_MODULES_EXCEPT_MAIN", "-FileIO", "-FileIO."]` and once for `["ALL_MODULES_EXCEPT_MAIN", "FileIO", "FileIO."]` Is this the expected behavior?

Note I'm using the julia extension 1.6.30 and I just updated the DebugAdapter (via git merges). @pfitzseb are you using JuliaInsider version?

```
Line 131: ┌ Debug: [yo] oacc=-FileIO, items=["ALL_MODULES_EXCEPT_MAIN", "-FileIO", "-FileIO."]
Line 160: ┌ Debug: [yo] oacc=-FileIO., items=["ALL_MODULES_EXCEPT_MAIN", "-FileIO", "-FileIO."]
Line 308: ┌ Debug: [yo] oacc=FileIO, items=["ALL_MODULES_EXCEPT_MAIN", "FileIO", "FileIO"]
Line 337: ┌ Debug: [yo] oacc=FileIO, items=["ALL_MODULES_EXCEPT_MAIN", "FileIO", "FileIO"]
```

I have also printed the stack-trace to see which calls what. Sorry for these very long traces.
To summarize the stack traces:
- the call to "-FileIO" is via _debug_notification(conn::VSCodeDebugger.JSONRPC.JSONRPCEndpoint_
- the call to "FileIO" is via a call to _run_debugger.jl:10_

### So the full chain of calls to "-FileIO" is this way:
```
│        @ d:\z_installed_programs\VSCode-win32-x64-1.70.1\data\extensions\julialang.language-julia-1.6.30\scripts\packages\VSCodeDebugger\src\VSCodeDebugger.jl:27 [inlined]
│      [4] set_compiled_functions_modules!(items::Vector{String})
│        @ VSCodeDebugger.DebugAdapter d:\z_installed_programs\VSCode-win32-x64-1.70.1\data\extensions\julialang.language-julia-1.6.30\scripts\packages\DebugAdapter\src\debugger_requests.jl:145
│      [5] set_compiled_functions_modules!(params::NamedTuple{(:compiledModulesOrFunctions,), Tuple{Vector{String}}})
│        @ VSCodeDebugger.DebugAdapter d:\z_installed_programs\VSCode-win32-x64-1.70.1\data\extensions\julialang.language-julia-1.6.30\scripts\packages\DebugAdapter\src\debugger_requests.jl:205
│      [6] set_compiled_items_request(conn::VSCodeDebugger.JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, state::VSCodeDebugger.DebugAdapter.DebuggerState, params::NamedTuple{(:compiledModulesOrFunctions,), Tuple{Vector{String}}})
│        @ VSCodeDebugger.DebugAdapter d:\z_installed_programs\VSCode-win32-x64-1.70.1\data\extensions\julialang.language-julia-1.6.30\scripts\packages\DebugAdapter\src\debugger_requests.jl:107
│      [7] debug_notification(conn::VSCodeDebugger.JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, state::VSCodeDebugger.DebugAdapter.DebuggerState, params::VSCodeDebugger.DebugAdapter.DebugArguments)
│        @ VSCodeDebugger.DebugAdapter d:\z_installed_programs\VSCode-win32-x64-1.70.1\data\extensions\julialang.language-julia-1.6.30\scripts\packages\DebugAdapter\src\debugger_requests.jl:41
│      [8] (::VSCodeDebugger.DebugAdapter.var"#121#147"{VSCodeDebugger.DebugAdapter.DebuggerState})(conn::VSCodeDebugger.JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, params::VSCodeDebugger.DebugAdapter.DebugArguments)
│        @ VSCodeDebugger.DebugAdapter d:\z_installed_programs\VSCode-win32-x64-1.70.1\data\extensions\julialang.language-julia-1.6.30\scripts\packages\DebugAdapter\src\packagedef.jl:49
│      [9] dispatch_msg(x::VSCodeDebugger.JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, dispatcher::VSCodeDebugger.JSONRPC.MsgDispatcher, msg::Dict{String, Any})
│        @ VSCodeDebugger.JSONRPC d:\z_installed_programs\VSCode-win32-x64-1.70.1\data\extensions\julialang.language-julia-1.6.30\scripts\packages\JSONRPC\src\typed.jl:67
│     [10] macro expansion
│        @ d:\z_installed_programs\VSCode-win32-x64-1.70.1\data\extensions\julialang.language-julia-1.6.30\scripts\packages\DebugAdapter\src\packagedef.jl:76 [inlined]
│     [11] (::VSCodeDebugger.DebugAdapter.var"#144#170"{VSCodeDebugger.var"#3#4"{Tuple{String, String}}, VSCodeDebugger.JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, VSCodeDebugger.JSONRPC.MsgDispatcher})()
│        @ VSCodeDebugger.DebugAdapter .\task.jl:423
```

### The call to "FileIO" is this way:
```
[3] eval
│        @ d:\z_installed_programs\VSCode-win32-x64-1.70.1\data\extensions\julialang.language-julia-1.6.30\scripts\packages\VSCodeDebugger\src\VSCodeDebugger.jl:27 [inlined]
│      [4] set_compiled_functions_modules!(items::Vector{String})
│        @ VSCodeDebugger.DebugAdapter d:\z_installed_programs\VSCode-win32-x64-1.70.1\data\extensions\julialang.language-julia-1.6.30\scripts\packages\DebugAdapter\src\debugger_requests.jl:145
│      [5] our_debug_command(cmd::Symbol, state::VSCodeDebugger.DebugAdapter.DebuggerState)
│        @ VSCodeDebugger.DebugAdapter d:\z_installed_programs\VSCode-win32-x64-1.70.1\data\extensions\julialang.language-julia-1.6.30\scripts\packages\DebugAdapter\src\debugger_core.jl:69
│      [6] startdebug(socket::Base.PipeEndpoint, error_handler::VSCodeDebugger.var"#3#4"{Tuple{String, String}})
│        @ VSCodeDebugger.DebugAdapter d:\z_installed_programs\VSCode-win32-x64-1.70.1\data\extensions\julialang.language-julia-1.6.30\scripts\packages\DebugAdapter\src\packagedef.jl:106
│      [7] startdebugger()
│        @ VSCodeDebugger d:\z_installed_programs\VSCode-win32-x64-1.70.1\data\extensions\julialang.language-julia-1.6.30\scripts\packages\VSCodeDebugger\src\VSCodeDebugger.jl:43
│      [8] top-level scope
│      @ d:\z_installed_programs\VSCode-win32-x64-1.70.1\data\extensions\julialang.language-julia-1.6.30\scripts\debugger\run_debugger.jl:10
│      [9] include(mod::Module, _path::String)
│        @ Base .\Base.jl:418
│     [10] exec_options(opts::Base.JLOptions)
│        @ Base .\client.jl:292
│     [11] _start()
│        @ Base .\client.jl:495
```

**Comment by pfitzseb** [comment]
Ah, whether this works depends on whether you attach to an existing process or not. Pushed a commit that makes it work in all cases.

**Comment by pfitzseb** [comment]
Unrelated, but you should never need both of `-FileIO` and `-FileIO.` -- the latter is a strict superset of the former.

**Comment by MariusDrulea** [comment]
@pfitzseb it works now, thanks for the fix

**Comment by MariusDrulea** [comment]
after more intensive debugs: this feature is a life saver!

**Comment by graidl** [comment]
`ALL_MODULES_EXCEPT_MAIN` is really much appreciated! But:

When using 
````
"julia.debuggerDefaultCompiled": [
        "ALL_MODULES_EXCEPT_MAIN",
        "-MyModule.",
    ]
````
any submodules from MyModule seem to stay compiled. Shouldn't they also be interpreted? To achieve this it currently seems necessary to list them all explicitly with a preceding '-', which again may lead to a long list of exceptions.

**Comment by pfitzseb** [comment]
Should be fixed with https://github.com/julia-vscode/DebugAdapter.jl/pull/67.

**Comment by MariusDrulea** [comment]
https://www.julia-vscode.org/docs/dev/userguide/debugging/#Settings-to-speed-up-the-debugger
