### ISSUE TITLE
Show sidebar icon only when Julia is actively used?

### ISSUE THREAD

**Issue by cbrnr** [julia-vscode/julia-vscode#2517]
I use VS Code for Python, R, and Julia (among others). When I work on a Python project, I don't need the Julia extension to clutter the sidebar. Is it possible to show the icon only when working on a Julia project? I know that this works for the R extension, which is not shown in the sidebar unless at least one R file is open (or at least I thing that is the trigger). Manually disabling the extension is a bit of a cumbersome workaround.

**Comment by pfitzseb** [comment]
Will be fixed in the next version.
