### ISSUE TITLE
debugger hangs with large variables

### ISSUE THREAD

**Issue by MariusDrulea** [julia-vscode/julia-vscode#2520]
I have created a very large variable (1024 MB) with the following code. I tried to debug like in the picture bellow, and tried to expand the Local variables tab.  After this, the debugger hangs.

```
module debug_tests
function create_very_large_object()
    # x = rand((512, 512, 512))
    x = rand(512*512*512)
    println(sizeof(x)/2^20, "MB")
    println("done")
end
end

debug_tests.create_very_large_object()
```

![image](https://user-images.githubusercontent.com/27725572/139602490-bb7de3a0-a44c-46a1-9459-ba44422184f2.png)

If I run a similar code to have variable x in the workspace (no debugging), everything works just fine, I can inspect this variable, so I'm surprised the debugger does not work similarly.
![image](https://user-images.githubusercontent.com/27725572/139602317-5f1c54fd-a2b2-44f8-b6af-c8b88d7cca4c.png)

**Comment by pfitzseb** [comment]
We unfortunately use two different implementations of what's basically the same functionality...

**Comment by MariusDrulea** [comment]
I have enabled the "compile mode" for debugging, and the debugging is really fast, unless I expand the "Variables". When I do this the debugging is noticeably laggy. The variables I have there are plotting figures plus the data I display, so usual stuff we do when prototyping algos. There are no big variables here. To me this is currently the most "blocking" issue as I cannot change it via some configurations. For compile vs interpret, I was able to find various configurations and workarounds. The laggy variables issue is an implementation issue. 

![image](https://user-images.githubusercontent.com/27725572/139940885-3cf1e2c4-301b-435a-94bd-bfe8b5861561.png)

**Comment by RGerzaguet** [comment]
Hello, 
I get the same issue with Julia insider 1.5.9. 
Any workaround ?

**Comment by MariusDrulea** [comment]
@pfitzseb I have just tested julia vscode 1.5.10 and the issue still persists. I think this issue was accidently closed. Reopen?

**Comment by pfitzseb** [comment]
No, the issue is fixed but no version with the fix has been released in the meantime.
