### ISSUE TITLE
entering new line clears the in-line evaluation popup cell

### ISSUE THREAD

**Issue by Datseris** [julia-vscode/julia-vscode#2521]
MWE.
type
```
rand()
```
press ALT+ENTER. A popup appears.

Then press ENTER to start a new line and write whatever other command. The popup to the right of `rand` has dissapeared. 

This isn't nice for interactively writing scripts.

**Comment by pfitzseb** [comment]
Can't repro this:
![Peek 2021-11-02 13-28](https://user-images.githubusercontent.com/6735977/139846322-a281e225-8c6d-44e6-b3a2-fb17a9cae56b.gif)

**Comment by Datseris** [comment]
Well, I'm extremely confused because this isn't what happens to me. The pop ups are all deteled :( How can I help further identifying the problem?

**Comment by Datseris** [comment]
(Windows 10)
