### ISSUE TITLE
Can't turn off autocomplete in comments

### ISSUE THREAD

**Issue by Gregliest** [julia-vscode/julia-vscode#2523]
I have 
```
"editor.quickSuggestions": {
    "comments": false
}
```
in my settings.json. But, when I type in a Julia comment, I still get suggestions, like:

![Autocomplete](https://user-images.githubusercontent.com/4493287/140005635-20085b83-bd61-443f-8e49-6821bc6538bc.png)

Am I doing something wrong, or is this a bug? I'm running Linux Mint 20.2, and VSCode version 1.61.2.

**Comment by pfitzseb** [comment]
Kinda looks like a bug, but is unrelated to the Julia extension.

**Comment by Gregliest** [comment]
Where should I post the issue then? I checked in a Python file, the setting is working properly for a Python comment.

**Comment by Gregliest** [comment]
@pfitzseb Do you have any additional advice on where I can look for a solution?

**Comment by fvanmaele** [comment]
I'm also having this issue. The `editor.quickSuggestions` setting does not apply to the Julia mode. A workaround is duplicating the settings for `[julia]` in settings.json:
```json
    "[julia]": {
        "editor.quickSuggestions": {
            "other": "off",
            "comments": "off",
            "strings": "off"
        }
```
