### ISSUE TITLE
Improper display of prompt messages in output of Julia program in the TERMINAL

### ISSUE THREAD

**Issue by shubh-b** [julia-vscode/julia-vscode#2529]
This issue has been raised [here](https://discourse.julialang.org/t/vs-code-terminal-julia-repl-is-not-showing-prompt-messages-for-inputs-properly/70282) before.

When this simple Julia program

```
print("Enter the first number: ")
a = parse(Float64, readline())
println("First number is $a")

print("Enter the second number: ")
b = parse(Float64, readline())
println("Second number is $b")

println("Hence the sum of $a and $b is $(a+b)")
```

is run in VS Code, the first prompt message appears weirdly. In TERMINAL, final output looks like

![Weird Output in VS Code](https://user-images.githubusercontent.com/28826994/140329656-d8539e90-01d8-4117-aef2-63e324e1d934.png)

Is it possible to make this output look more appropriate something like below?

```
julia> Enter the first number: 23
First number is 23.0     
Enter the second number: 58.9
Second number is 58.9
Hence the sum of 23.0 and 58.9 is 81.9
```

**Comment by pfitzseb** [comment]
`readline` and all other functions that take input via stdin are broken in VS Code.
Dup of #785.

**Comment by shubh-b** [comment]
Thank you for letting me know this. Hope issue [#785](https://github.com/julia-vscode/julia-vscode/issues/785) will be resolved soon.
