### ISSUE TITLE
Error message is masked

### ISSUE THREAD

**Issue by uluviano** [julia-vscode/julia-vscode#2538]
Issue Type: <b>Bug</b>

I find error messages in the notebook extension are masked beyond comprehension. For example, if I type
```julia
>sin("A")
#I get:
ERROR: MethodError: no method matching sin(::String)
Closest candidates are:
  sin(::Float16) at math.jl:1159
  sin(::ComplexF16) at math.jl:1160
  sin(::Complex{T}) where T at complex.jl:831
  ...
Stacktrace:
 [1] top-level scope
   @ REPL[1]:1
```

With the same input in a notebook cell, instead, the error output is
```
Stacktrace:
  [1] top-level scope
    @ ~/fortranmc/dataAnalysisNotebooks/actvsDstar.ipynb:1
  [2] eval
    @ ./boot.jl:360 [inlined]
  [3] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
    @ Base ./loading.jl:1094
  [4] #invokelatest#2
    @ ./essentials.jl:708 [inlined]
  [5] invokelatest
    @ ./essentials.jl:706 [inlined]
  [6] (::VSCodeServer.var"#98#99"{VSCodeServer.NotebookRunCellArguments, String})()
    @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-1.4.3/scripts/packages/VSCodeServer/src/serve_notebook.jl:18
  [7] withpath(f::VSCodeServer.var"#98#99"{VSCodeServer.NotebookRunCellArguments, String}, path::String)
    @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-1.4.3/scripts/packages/VSCodeServer/src/repl.jl:185
  [8] notebook_runcell_request(conn::VSCodeServer.JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, params::VSCodeServer.NotebookRunCellArguments)
    @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-1.4.3/scripts/packages/VSCodeServer/src/serve_notebook.jl:14
  [9] dispatch_msg(x::VSCodeServer.JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, dispatcher::VSCodeServer.JSONRPC.MsgDispatcher, msg::Dict{String, Any})
    @ VSCodeServer.JSONRPC ~/.vscode/extensions/julialang.language-julia-1.4.3/scripts/packages/JSONRPC/src/typed.jl:67
 [10] serve_notebook(pipename::String; crashreporting_pipename::String)
    @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-1.4.3/scripts/packages/VSCodeServer/src/serve_notebook.jl:94
 [11] top-level scope
    @ ~/.vscode/extensions/julialang.language-julia-1.4.3/scripts/notebook/notebook.jl:10
 [12] include(mod::Module, _path::String)
    @ Base ./Base.jl:386
 [13] exec_options(opts::Base.JLOptions)
    @ Base ./client.jl:285
 [14] _start()
    @ Base ./client.jl:485
```
I found issue [1837](https://github.com/julia-vscode/julia-vscode/issues/1837) marked as closed but I think it was regarding the repl.

I appreciate any help.

Extension version: 1.4.3
VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:18:44.904Z)
OS version: Linux x64 5.4.0-89-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8 x 2231)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 1|
|Memory (System)|5.75GB (0.12GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id f8631473-5e30-4634-9d72-b9d9409c1bc2|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwt:30382697
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593cf:30376535
vssld246cf:30386378

```

</details>

**Comment by pfitzseb** [comment]
This will be fixed with 1.5. Feel free to give the insiders release a go and report back.

**Comment by uluviano** [comment]
Great to know! :)
This might be a noob question but I tried googling around and found no way to install the insiders version. Do I have to check the other branches of the repository and try to build it from there?

**Comment by pfitzseb** [comment]
Just install https://marketplace.visualstudio.com/items?itemName=julialang.language-julia-insider and disable the normal Julia extension temporarily.

**Comment by uluviano** [comment]
It does work indeed :)!
<img width="457" alt="Screen Shot 2021-11-06 at 5 24 57 PM" src="https://user-images.githubusercontent.com/43607358/140616670-cc1d4c9d-b160-45ee-b0ea-233ce9eeb061.png">
Thanks a lot :) I'll wait for the 1.5 release.
