### ISSUE TITLE
StackOverflowError when taking matrix exp with big matrix

### ISSUE THREAD

**Issue by daviehh** [julia-vscode/julia-vscode#2543]
Reduced to a minimum example: 
```
using LinearAlgebra

t = 2.1
hx = rand(125, 125)
u = exp(-1im * hx * t)

println(u[1, 1])
```

running this script in julia repl (outside of vscode) is ok, but when run in vscode it errors with just

```
ERROR: LoadError: StackOverflowError:
in expression starting at /test/sof.jl:5
```

with no more info...

my julia versioninfo():

> julia> versioninfo()
> Julia Version 1.7.0-rc2
> Commit f23fc0d27a (2021-10-20 12:45 UTC)
> Platform Info:
>   OS: macOS (x86_64-apple-darwin21.1.0)
>   CPU: Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
>   WORD_SIZE: 64
>   LIBM: libopenlibm
>   LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
> Environment:
>   JULIA_MATHLINK = /Applications/Mathematica.app/Contents/Frameworks/mathlink.framework
>   JULIA_MATHKERNEL = /Applications/Mathematica.app/Contents/MacOS/MathKernel

julia-vscode: this issue is present in both the normal (v1.4.3) and insider version (v1.5.2)

Most likely not related to io or variable names, since the calculation above was originally inside a function with no prints, etc.

**Comment by daviehh** [comment]
A bit more digging: the error info above was observed with julia 1.7 rc2 compiled from source; using the 1.7 rc2 binary downloaded from julia gives
```
ERROR: LoadError: ReadOnlyMemoryError()
```

No errors with julia 1.6.3.

**Comment by pfitzseb** [comment]
Very weird. Unfortunately I can't repro this on my machine (with 16GB RAM as well). MacOS stackoverflows are notorious for not being particularly informative, but I'm not sure I can be of much help debugging this. Couple of pointers:
- Are you running the same sysimg in both cases?
- Did you load any packages in either case? It's possible something interacts weirdly with the modules loaded into the VS Code REPL.

**Comment by daviehh** [comment]
Thanks for getting back! No custom sysimg, no other package other than LinearAlgebra; also tried with the connect external REPL by pasting the code provided, with fresh julia with no startup file, still `StackOverflowError`; notice no error with smaller matrix below:

<img width="1059" alt="Screen Shot 2021-11-08 at 12 31 00 PM" src="https://user-images.githubusercontent.com/25255906/140790321-945b0300-a0e7-45bb-8688-43899821d244.png">


FWIW, also noticing this with ijulia/jupyter notebooks, but not Pluto.jl if it helps troubleshooting

**Comment by daviehh** [comment]
Closing, since it appears to be a julia issue and not related to vscode: without vscode stuff, the vanilla julia repl just has StackOverflowError with a higher n:

```
julia> using LinearAlgebra

julia> n = 300
300

julia> m = rand(ComplexF64, n, n);

julia> mex = exp(m);
ERROR: StackOverflowError:
```

**Comment by daviehh** [comment]
link: https://github.com/JuliaLang/julia/issues/43008
