### ISSUE TITLE
LaTeX bindings for emojis don't work

### ISSUE THREAD

**Issue by akriegman** [julia-vscode/julia-vscode#2549]
Hi, I'm a big fan of this extension, especially how seamlessly the Latex bindings work in the VScode editor just like in the REPL. I just noticed a missing feature that I wanted to make you aware of.

Among the many Latex bindings in julia are several emojis, for which the bindings are nested in colons, e.g. `\:scream:`. These work just like all the other bindings in the REPL with pressing `<tab>` entering the character. In VScode these do not work.

Expected behavior:
Typing `\ne<tab>` enters a ≠. Works in REPL, works in VScode.
Typing `\:scream:<tab>` enters a 😱. Works in REPL, does not work in VScode.

**Comment by pfitzseb** [comment]
That's just a font issue, `\tau\bar` looks fine for me (with JuliaMono):
![image](https://user-images.githubusercontent.com/6735977/141462868-d79f3638-fdb0-4fcf-b4a8-f0d1c54ded90.png)

**Comment by akriegman** [comment]
Thanks, I installed JuliaMono and it works now. Also I was wrong, Unicode combines characters in the same order as Julia, which is probably why Julia uses a different order than Latex.
