### ISSUE TITLE
alt + enter code executes entire script

### ISSUE THREAD

**Issue by itsdfish** [julia-vscode/julia-vscode#2556]
In the newest version of Julia-VSCode, the command `alt + enter` executes the entire active file rather than the highlighted code. Please let me know if you need more information. 

**Version**

Julia: 1.6.3
VSCode: 1.62.2
Julia-VSCode: 1.5.4
OS: Ubuntu 20.04

**Comment by krynju** [comment]
`ctrl+enter` as well, same extension version

**Comment by itsdfish** [comment]
Interesting. On my system, `ctrl + enter` executes highlighted code for me.

**Comment by krynju** [comment]
Ah yes, highlighted code works as expected 

What I meant was the case where you have your cursor on the specific line and nothing highlighted and hit ctrl enter. That used to execute just the specific line, but now it executes the full file

Forgot there's two behaviors of ctrl enter

**Comment by pfitzseb** [comment]
The default keybindings changed in this release. Check [this](https://discourse.julialang.org/t/ann-julia-for-vs-code-1-5-released/71365/24?u=pfitzseb) for info on how to revert that change locally.

Also, just to be accurate:
1. Alt-Enter evaluates the current cell. If you don't have any cells in your file, it'll evaluate the whole file.
2. Ctrl-Enter will evaluate the largest non-module code block, which could be equivalent to the whole file if you only have one function for example.

**Comment by itsdfish** [comment]
My apologies for the false alarm. I must have missed the change in the change log.
