### ISSUE TITLE
Add support for VS Code for the Web

### ISSUE THREAD

**Issue by benz0li** [julia-vscode/julia-vscode#2557]
See [Visual Studio Code for the Web](https://code.visualstudio.com/docs/editor/vscode-web#_extensions) and [Web Extensions | Visual Studio Code Extension API](https://code.visualstudio.com/api/extension-guides/web-extensions) for more information.

**Comment by pfitzseb** [comment]
None of the LS-powered features (or interactive features, for that matter) will work in web extensions, because we can't spin up a Julia process. So I don't quite see what we'd gain from adding web extension support.

**Comment by benz0li** [comment]
@pfitzseb Thanks for the feedback and clarification.
