### ISSUE TITLE
Runtime REPL completion suggestions are occurring in local scope

### ISSUE THREAD

**Issue by CameronBieganek** [julia-vscode/julia-vscode#2560]
According to [this comment](https://discourse.julialang.org/t/ann-julia-for-vs-code-1-5-released/71365/24?u=cameronbieganek) on Discourse, runtime REPL completions should only occur in global scope:

> Runtime completions should always look very distinct though and only pop up for `getproperty`/`getindex` calls in global scope

However, I'm also getting runtime REPL suggestions in local scope:

![image](https://user-images.githubusercontent.com/8310743/141689841-51695cd0-0630-446e-8075-b8d905403155.png)

**Comment by pfitzseb** [comment]
Let's call this "by design". Technically the completions are valid, so I'm not sure we should prevent this.
