### ISSUE TITLE
Interactive plot pane plot resolution when zooming has become lower resolution than before

### ISSUE THREAD

**Issue by NikoBiele** [julia-vscode/julia-vscode#2561]
Hi,

I noticed that the zoomed quality of plots is now not as high resolution as it was before.
I only know this because I made a few plots a few days ago, and to get good resolution I zoomed max, before taking the screenshot.
Before it seemed more 'vector-graphics'-like where the resolution would follow the zoom.
This no longer seems to be the case.

Two identical screenshots (click the plots too see full size and compare):

The new plot window, zoomed max:
![JuliaVSCodeNewPlot](https://user-images.githubusercontent.com/71772461/141694475-8429954c-07dc-4545-95b1-59b7bb6f5c51.PNG)
The old plot window, zoomed max:  (Until a few days ago. It's actually a screenshot of a pdf with an inserted screenshot, still it appears more clear than the new max zoomed plot pane.), 
![JuliaVSCodeOldPlot](https://user-images.githubusercontent.com/71772461/141694483-6fd8bdd9-1122-4109-b726-93dc379f9b77.PNG)

Would be nice if this could be fixed, other than that, nice with new features!

Regards Nikolaj

**Comment by pfitzseb** [comment]
The default plot mime type changed to png in the latest release. I'd like to switch back to svg, but performance seems pretty bad atm.

**Comment by NikoBiele** [comment]
Hmm ok, plotting is quite important to me. I would definitely prefer the old format, even if slow. But now you know. Should I just close this then?

**Comment by NikoBiele** [comment]
Or maybe the user could be given the choice of format? Maybe some prefer performance while others prefer high quality zoomable plots.

**Comment by pfitzseb** [comment]
Well, you can always explicitly call `display(VSCodeServer.InlineDisplay(), "image/svg+xml", your_plot)` for now. But hopefully this gets a more satisfying resolution :)

**Comment by NikoBiele** [comment]
Nice, thanks for the tip! I'll use this option for now then :)

**Comment by NikoBiele** [comment]
Wow now, I can even export as .svg, this is a serious improvement as compared to screenshot .png's! :D Thank you!

**Comment by luboshanus** [comment]
However, while using Jupyter notebook in VScode, the display works with SVG. https://discourse.julialang.org/t/plot-blurred-again-in-vs-code-with-gr/71546/3 
Wouldn't be possible to have some setting/preference/property for normal plot pane? Or to do some kind of implementation into https://github.com/JuliaPlots/Plots.jl/blob/master/src/output.jl where is also a specification display/output for `Juno` and `IJulia`.

**Comment by JianghuiDu** [comment]
I can't use `display(VSCodeServer.InlineDisplay(), "image/svg+xml", your_plot) `
```julia
ERROR: LoadError: UndefVarError: VSCodeServer not defined
```

**Comment by pfitzseb** [comment]
Then you're obviously not in the Julia REPL process and don't need the workaround.

**Comment by JianghuiDu** [comment]
But I also got this low resolution image. I'm using `display` inside a function. How can change to svg?

**Comment by JianghuiDu** [comment]
I can just do `display("image/svg+xml", your_plot)` and that works, both inside a module and in REPL. Why the need to add `VSCodeServer.InlineDisplay()` ?

**Comment by pfitzseb** [comment]
Ah, cool. No need for that then.
