### ISSUE TITLE
LaTeX autocompletes both `\epsilon` & `\varepsilon` to `ε`, while the first one should return `ϵ`

### ISSUE THREAD

**Issue by singularitti** [julia-vscode/julia-vscode#2562]
![image](https://user-images.githubusercontent.com/25192197/141751149-b62e8451-2390-400e-aca8-678a2cd084c3.png)
![image](https://user-images.githubusercontent.com/25192197/141751203-1443f603-1ac0-46be-bed7-1b6344a630fc.png)

Version: 1.62.2
Commit: 3a6960b964327f0e3882ce18fcebd07ed191b316
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0

Plugin version: 1.5.4

**Comment by pfitzseb** [comment]
This is a font issue.

**Comment by singularitti** [comment]
Sorry to bother you, I just want to ask what is a font issue? Do you mean I do not have the character for `ϵ`? I am using [the Iosevka font](https://typeof.net/Iosevka/), which can print both characters:
![ϵ](https://user-images.githubusercontent.com/25192197/141842274-725149a2-0ebb-4585-a758-d0bbb38424e2.png)

**Comment by pfitzseb** [comment]
Ok, this most likely is an issue with `yellpika.latex-input` (or another latex input extension, but that's the one I had active). The completions provided by the LS are correct:
![image](https://user-images.githubusercontent.com/6735977/141850544-677573e3-bb52-48a8-9316-b6e46b17df8c.png)

**Comment by singularitti** [comment]
> Ok, this most likely is an issue with `yellpika.latex-input` (or another latex input extension, but that's the one I had active). The completions provided by the LS are correct: ![image](https://user-images.githubusercontent.com/6735977/141850544-677573e3-bb52-48a8-9316-b6e46b17df8c.png)

Oh, I am sorry. I also had this extension active. Thank you for your reply!
