### ISSUE TITLE
Linter misses `sort` method definition in `DataFrames`

### ISSUE THREAD

**Issue by nilshg** [julia-vscode/julia-vscode#2565]
As discussed on Slack, I currently see the following issue:

![image](https://user-images.githubusercontent.com/7264491/141968963-10b02601-73f9-441b-9ed8-bd998b6ec806.png)

This is on Julia extention v1.5.4. My VSCode is the latest version of the Insiders build (1.63.0-insider)

**Comment by Betristor** [comment]
I encountered this problem either. Using sort! to sort a dataframe according to a column will report this error.
