### ISSUE TITLE
VS Code extension crashes in debug mode

### ISSUE THREAD

**Issue by johannaklahold** [julia-vscode/julia-vscode#2571]
I am new to Julia and so far I've had a very good experience with the VS Code Julia extension. However, with my new project the extension crashes immediately when I try to debug my code. The code runs perfectly when I am not in debug mode. 

I am attaching the error message and information on my setup below. If you need any further info, let me know!

Do you have any advice about what might cause the crash and how I could possibly fix it? I am afraid the problem could as well sit in front of the screen - I am not a computer scientist nor do I have huge coding experience...

Many thanks!
Johanna

(I found this related issue, but unfortunately it didn't help much... https://github.com/julia-vscode/julia-vscode/issues/2343)

------------------------
┌ Error: Some Julia code in the VS Code extension crashed
└ @ VSCodeDebugger ~/.vscode/extensions/julialang.language-julia-1.5.4/scripts/error_handler.jl:15
ERROR: ArgumentError: lowering did not return a `:thunk` expression, got $(Expr(:toplevel, :(#= ...

... followed by a dump of the source text and this stacktrace: 

 [1] VSCodeDebugger.JuliaInterpreter.Frame(mod::Module, ex::Expr)
   @ VSCodeDebugger.JuliaInterpreter ~/.vscode/extensions/julialang.language-julia-1.5.4/scripts/packages/JuliaInterpreter/src/types.jl:275
 [2] get_next_top_level_frame(state::VSCodeDebugger.DebugAdapter.DebuggerState)
   @ VSCodeDebugger.DebugAdapter ~/.vscode/extensions/julialang.language-julia-1.5.4/scripts/packages/DebugAdapter/src/debugger_core.jl:60
 [3] debug_notification(conn::VSCodeDebugger.JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, state::VSCodeDebugger.DebugAdapter.DebuggerState, params::VSCodeDebugger.DebugAdapter.DebugArguments)
   @ VSCodeDebugger.DebugAdapter ~/.vscode/extensions/julialang.language-julia-1.5.4/scripts/packages/DebugAdapter/src/debugger_requests.jl:45
 [4] (::VSCodeDebugger.DebugAdapter.var"#120#146"{VSCodeDebugger.DebugAdapter.DebuggerState})(conn::VSCodeDebugger.JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, params::VSCodeDebugger.DebugAdapter.DebugArguments)
   @ VSCodeDebugger.DebugAdapter ~/.vscode/extensions/julialang.language-julia-1.5.4/scripts/packages/DebugAdapter/src/packagedef.jl:49
 [5] dispatch_msg(x::VSCodeDebugger.JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, dispatcher::VSCodeDebugger.JSONRPC.MsgDispatcher, msg::Dict{String, Any})
   @ VSCodeDebugger.JSONRPC ~/.vscode/extensions/julialang.language-julia-1.5.4/scripts/packages/JSONRPC/src/typed.jl:67
 [6] macro expansion
   @ ~/.vscode/extensions/julialang.language-julia-1.5.4/scripts/packages/DebugAdapter/src/packagedef.jl:76 [inlined]
 [7] (::VSCodeDebugger.DebugAdapter.var"#143#169"{VSCodeDebugger.var"#3#4"{Tuple{String, String}}, VSCodeDebugger.JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, VSCodeDebugger.JSONRPC.MsgDispatcher})()
   @ VSCodeDebugger.DebugAdapter ./task.jl:411

My working environment:
OS: macOS (x86_64-apple-darwin18.7.0)
CPU: Apple M1
Julia Version 1.6.2
Julia VS Code extension Version 1.5.4

Packages:
  [fbb218c0] BSON v0.3.4
  [a134a8b2] BlackBoxOptim v0.5.0
  [717857b8] DSP v0.6.10
  [a93c6f00] DataFrames v1.2.2
  [7a1cc6ca] FFTW v1.4.5
  [38e38edf] GLM v1.5.1
  [f67ccb44] HDF5 v0.13.7
  [a98d9a8b] Interpolations v0.13.4
  [429524aa] Optim v1.5.0
  [91a5bcdd] Plots v1.23.5
  [b372bb87] SeisIO v1.2.1
  [ade2ca70] Dates
  [8ba89e20] Distributed
  [1a1011a3] SharedArrays
  [10745b16] Statistics

**Comment by pfitzseb** [comment]
This is a bit weird. Normally I would've expected a syntax error to be the cause of this, but that can't be it because your code runs fine outside of the debugger. Is the file saved? IIRC the debugger uses the actual file, while inline evaluation uses the buffer content, so that would explain the different behaviour.

If that isn't it: Any chance you can share your code (ideally, the minimal subset that still exhibits the bug)?

**Comment by johannaklahold** [comment]
Thanks for your quick reply! The file is saved.

Unfortunately, I cannot share the code because it's part of an ongoing unpublished research project and therefore confidential.

I understand that this limits your possibilities to help me, but still: Any other idea what I could try and have a look at?

**Comment by pfitzseb** [comment]
Try
```
# pkg> add JuliaInterpreter 
using JuliaInterpreter
expr = Base.parse_input_line(read("/path/to/your/file", String))
for (mod, ex) in JuliaInterpreter.ExprSplitter(Main, expr)
    println("\n\nExpr:\n-----")
    println(ex)
    println("\nFrame:\n------")
    println(Frame(mod, ex))
    println("--------------------------\n")
end
```
with the file the debugger errors on. I'd expect one of those `Frame(mod, ex)` calls to produce the same error you reported originally -- would be great if you could share as much as possible about the expression for which the subsequent `Frame` call errors.

**Comment by sozkcn** [comment]
Hi, I had the same problem and managed to reproduce the error with this code:
```
global i = 0
function increment_global()
    global i += 1
end

increment_global()
```

**Comment by amrit-poudel** [comment]
I keep getting the same error as OP whenever I try to use the Julia debugger in VS Code. [I click the "Start Debugging" option under the "Run" tab the VS Code toolbar]: 

> Connecting to debugger... Done!

┌ Error: Some Julia code in the VS Code extension crashed
└ @ VSCodeDebugger ~/.vscode/extensions/julialang.language-julia-1.5.8/scripts/error_handler.jl:15
ERROR: ArgumentError: lowering did not return a `:thunk` expression, got $(



Has this issue been resolved? Thanks!

**Comment by johannaklahold** [comment]
Hi, in my case the error was caused by declaring a local variable `local myvariable`. Now I don't need this line anymore and the error has disappeared.

**Comment by pfitzseb** [comment]
Yeah, we'll have a fix for that soonish (both the `global` and `local` case).

**Comment by amrit-poudel** [comment]
@pfitzseb Thanks a lot! Looks like I have "global" defined in my code. I overlooked one of the messages above and kept wondering why I was getting the error :(.

**Comment by pfitzseb** [comment]
FWIW, I don't think it ever makes sense to annotate a variable in a top-level scope as either `local` or `global`.

**Comment by amrit-poudel** [comment]
Without annotating a variable global, how would you use that variable in the for loop in Julia?

**Comment by pfitzseb** [comment]
You annotate it as `global` in the local scope, like so:
```
julia> foo = 2
2

julia> for i in 1:10
         global foo
         foo += 1
       end

julia> foo
12
```
This doesn't cause the issue reported here.
