### ISSUE TITLE
ALT+ENTER has changed behaviour

### ISSUE THREAD

**Issue by casasgomezuribarri** [julia-vscode/julia-vscode#2578]
I have been using `Alt` + `Enter` to run my code for a year and a bit now, I love being able to access the block code outputs on the editor by hovering over them. Suddenly, today the shortcut has changed behaviour, it now runs the entire file on the REPL (only reporting the output of the last code block on the editor).

`Shift` + `Enter` sends the current line to the REPL, but doesn't show the output on the editor

`Ctrl` + `Enter` does what I want `Alt` + `Enter` to do (run the current code block and show its output) but doesn't move - i.e. runs the block but the cursor remains at the beginning of it instead of moving to its last line (this is kind of important for me because my code is organised in long `begin` blocks). 

Has there been a recent update on `julialang` that I can undo? Or is there a new shortcut that does what `Alt` + `Enter` used to do? Or can I assign a shortcut to do what `Ctrl` + `Enter` now does but also move the cursor to the end of the block?

**Version info**
Julia v1.6
VSCode 1.62.3 (user setup)
julialang v1.5.6

**Comment by pfitzseb** [comment]
`Shift-Enter` is the new `Alt-Enter`.

Also feel free to search through the `Open Keyboard Shortcuts` -- that will list all Julia keybindings.

**Comment by casasgomezuribarri** [comment]
Ah, I see. Two actions were bound to `Shift` + `Enter`, and changing the keybinding of the other one solved the problem of the cursor not moving to the end of the block.

Was this change notified to the users and did I miss that?
