### ISSUE TITLE
Add profiler result UI

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/julia-vscode#258]
https://github.com/tkluck/StatProfilerHTML.jl

**Comment by KristofferC** [comment]
Is there any problem with that code being GPL?

**Comment by sheegl** [comment]
What do you think about adding profiling results per line? I really like the way PyCharm displays the profiler results besides the line numbers (unfortunately I can't find a screenshot). Spotting slow lines of code is really nice that way.

This would work similarly to how git changes are highlighted. The more time is spent on a line the more red the highlighting becomes. It probably also makes sense to use a threshold so not all lines are highlighted e.g. >1%.

I had something like this in mind:
![git changes](https://code.visualstudio.com/assets/docs/editor/editingevolved/gutter.png)

I've quickly created a function which aggregates the profiling results for all files in the current project.

```julia
using Profile

function show_statistics()
    data = Profile.fetch()
    stackframes = Profile.getdict(data)
    project_dir = pwd()
    total = Dict()
    total_samples = 0

    # count samples for lines in project files
    for (addr, stackframe) in stackframes
        for s in stackframe
            file_name = String(s.file)
            if startswith(file_name, project_dir)
                rel_file_name = file_name[(length(project_dir)+2):end]
                n_samples = count(a -> a == addr, data)
                total_samples += n_samples
                if !haskey(total, rel_file_name)
                    total[rel_file_name] = Dict()
                end
                if !haskey(total[rel_file_name], s.line)
                    total[rel_file_name][s.line] = 0
                end
                total[rel_file_name][s.line] += n_samples
            end
        end
    end

    # print statistics
    for (file_name, d) in total
        println("$(file_name):")
        for (line_num, samples) in sort(collect(d), by=x -> x[2], rev=true)
            println("\tLine:$(line_num) = $(round(100 * samples / total_samples, digits=1))%")
        end
    end

end

macro lineprofile(ex)
    quote
        Profile.clear()
        @profile $(esc(ex))
        show_statistics()
    end
end

function f(n)
    A = rand(n, n)
    A .+= 1
    maximum(A)
end

@lineprofile f(5000)
```

**Output**
```
LineProfiler.jl:
        Line:49 = 56.2%
        Line:50 = 43.8%
```

**Comment by davidanthoff** [comment]
Yes, that wouldn't work. That package I think also needs perl? That would also be a non-starter. So I think we'll probably just need to roll our own...

**Comment by cdsousa** [comment]
What about https://github.com/timholy/ProfileView.jl or https://docs.junolab.org/latest/man/juno_frontend/#Juno.@profiler?

**Comment by davidanthoff** [comment]
I think it would be very nice if the stuff in ProfileView.jl that is not related to a specific display front-end (GTK or SVG) could be moved into its own package. Right now ProfileView.jl pulls in Gtk.jl, which is a non-starter for us here.

I don't know what Juno is using there, certainly worth exploring that! @pfitzseb.

Right now I'm thinking that maybe a combination of moving the generic stuff out of ProfileView.jl and then a vega spec for displaying things might be the best option?

**Comment by davidanthoff** [comment]
This should be super easy now, see [here](https://discourse.julialang.org/t/ann-more-flexible-user-friendly-profile-visualization-profileview-0-6/33648/8) for a strategy that uses vega-lite to display the flame graph. I have a plan how we can do this in a very robust way where we can ship everything we need in the extension, so that it should always work.

**Comment by zhopan77** [comment]
Glad to see this feature is already being developed! This is one of the top 3 in my wish list to get our colleague to adopt Julia + VSCode as standard development environment. 

FY the other two being intellisense for local module on LOAD_PATH and loaded with "using" or "import"; and workspace view. All these 3 features are currently supported by Juno, but we prefer VSCode's overall performance.

**Comment by davidanthoff** [comment]
My plan for this has actually changed a bit: as far as I can tell, MS is working on a profiling visualization extension itself, and from what I've seen so far it is probably going to be quite comprehensive (including frame graphs, a query language etc.). If that turns out to be the case, we should just plug into that instead of doing our own UI.

**Comment by zhopan77** [comment]
Interesting! Plugging into a MS developed framework is certainly a more sustainable approach.

GUI profiler is actually not the main pain point in our daily work as profiling happens infrequently, for which we can use Juno for now, which is also quite nice albeit a little heavier and slower. The more important are intellisense that "just works" even for local modules on LOAD_PATH, and the workspace view. I have either commented on existing issue or opened new one for those two.

Thanks again for the wonderful plugin!

**Comment by davidanthoff** [comment]
Short update on this: MS is now shipping the profile visualization extension in the marketplace for the released VS Code, and the insiders version ships it out of the box. I believe that it will ship out of the box for everyone whenever the new JavaScript debugger will ship. Hopefully soon.

On our end we have https://github.com/julia-vscode/ChromeProfileFormat.jl, which exports Julia profiles into the right format. We just need to integrate that into the extension and ship by default, and then we are done with this feature.

**Comment by pfitzseb** [comment]
Juno also adds [inline info](https://junolab.org/img/newscreen2.png), which makes it very easy to figure out how lines compare in  execution cost.

**Comment by davidanthoff** [comment]
I think I don't get what `inline info` refers to :) Is it the light blue color background in the code lines?

I think the VS Code profile UI will show numeric results inline.

**Comment by vchuravy** [comment]
>I think I don't get what inline info refers to :) Is it the light blue color background in the code lines?

Yeah it is basically the percent of ticks per line.

**Comment by davidanthoff** [comment]
I think we can close this? There might be things to tweak, but we are shipping a profiler UI now.
