### ISSUE TITLE
Plots no Longer resize

### ISSUE THREAD

**Issue by Abel-Github** [julia-vscode/julia-vscode#2580]
After updating my julia-vscode extension, I am no longer able to increase the size of the plots for viewing. It just remains static.

Before now, i was able to use Ctrl+Mouse Scroll to increase the size of the plot in the view panel for my plots.

I am on windowsOS.

**Comment by pfitzseb** [comment]
You should be able to use Alt + scroll to resize plots.

**Comment by Abel-Github** [comment]
Working. It seems some of the key bindings were changed. I normally use Crtl+scroll

Thanks
