### ISSUE TITLE
Code Block Execution in Julia Markdown Broken

### ISSUE THREAD

**Issue by Firionus** [julia-vscode/julia-vscode#2583]
REPL code execution of Julia Codeblocks in Julia Markdown Files doesn't work for me. 

### Steps to Reproduce

- Create a new Julia Markdown File `test.jmd`:
````markdown
```julia
println("Hello")
```
````

### Observations

1. Place cursor anywhere on the code line except for the beginning
    1. Pressing `Alt + Enter` only prints an empty line
    2. Pressing `Ctrl + Enter` only prints an empty line
2. Place the cursor at the beginning of a code line
    1. Pressing `Alt + Enter` does nothing
    2. Pressing `Ctrl + Enter` executes the line, as expected
3. Place the cursor anywhere but on a Julia code line
    1. Pressing `Ctrl + Enter` executes the next line of code. If no code line follows, it prints an empty line to the REPL. This is as expected.
    2. Pressing `Alt + Enter` does nothing, as expected.

### Expected Behavior

The [docs](https://www.julia-vscode.org/docs/stable/userguide/weave/#Julia-Markdown-Documents) suggest that Julia Markdown files should work like cells in normal `.jl` files. Therefore I expected:

1. Place cursor anywhere on a code line
    1. Pressing `Alt + Enter` executes the whole cell
    2. Pressing `Ctrl + Enter` executes the next code line

### Test Environment

julia-vscode:
```
julialang.language-julia@1.5.6
```

Julia:
```
julia> versioninfo()
Julia Version 1.6.4
Commit 35f0c911f4 (2021-11-19 03:54 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
```

VS Code:
```
Version: 1.62.3
Commit: ccbaa2d27e38e5afa3e5c21c1c7bef4657064247
Date: 2021-11-17T08:00:36.721Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.11.0-40-generic
```

**Comment by pfitzseb** [comment]
Fixed by https://github.com/julia-vscode/julia-vscode/commit/3bb8890b85cbb698313f0e193fb4fc54932f1144.

**Comment by Firionus** [comment]
Wow, that was quick :rocket: :smile: 

`Alt + Enter` seems to work fine now. 

But when I place the cursor on the lines with fences or at the beginning of the code line and press `Ctrl + Enter`, I get this error:


![image](https://user-images.githubusercontent.com/32422182/143238500-62348f9b-075b-4d7e-a9a8-cce622d83b96.png)

**Comment by pfitzseb** [comment]
Yeah, that's a separate issue though.

**Comment by Firionus** [comment]
Shall I open a new issue for it?

**Comment by pfitzseb** [comment]
Please do.
