### ISSUE TITLE
Integrated terminal losses communication to REPL 

### ISSUE THREAD

**Issue by andreasvarga** [julia-vscode/julia-vscode#2585]
I am using VSCODE for testing and development purposes. Since a few days I am facing the problem that after executing some selected lines in a script files, the computed quatities can not be visualized in the terminal. A typical error message obtained after executing the following highlighted command using `Ctrl+Enter`

`Q2, Rf2, info2 = ammsyn(sysf, sysr2, atol = 1.e-7, sdeg =-5, reltol = 1.e-5)`

is 

```
julia> Q2
ERROR: UndefVarError: Q2 not defined
```

When I am starting a new terminal, VSCODE behaves, for a while, as expected. 

I am using Julia v1.6.0 with Julia Language Support v1.5.6. 

I would like to add that I am using Revise within VSCODE.

**Comment by pfitzseb** [comment]
Check the module selected in the lower right corner -- that's the context in which your code is executed. The REPL always uses Main.

**Comment by andreasvarga** [comment]
The current module was my test module `Test_ammsyn`. After changing it to `main`, things work again. Thanks. 

Is any way to prevent switching to another module?

**Comment by pfitzseb** [comment]
No. You can [revert the changed keybinding though](https://discourse.julialang.org/t/ann-julia-for-vs-code-1-5-released/71365/24?u=pfitzseb).
