### ISSUE TITLE
JavaCall gives error only in a VSCode Terminal 

### ISSUE THREAD

**Issue by IgnacioRubioScola** [julia-vscode/julia-vscode#2587]
In VSCode running the following command
```using JavaCall; JavaCall.init()```
gives
```
┌ Warning: JavaCall needs the environment variable `JULIA_COPY_STACKS` to be `1` or `yes`.
│ Calling the JVM may result in undefined behavior.
└ @ JavaCall ~/.julia/packages/JavaCall/tjlYt/src/JavaCall.jl:53
ERROR: LoadError: JavaCall.JavaCallError("Either the environmental variable JULIA_COPY_STACKS must be 1 OR JavaCall must be used on the root Task.")
```
but in a linux terminal it works well (without setting JULIA_COPY_STACKS=1).

How I can set the environment variable JULIA_COPY_STACKS=1 in VSCode before running Julia?

Thank you.

**Comment by pfitzseb** [comment]
You should be able to use the `terminal.integrated.env.linux` setting for that. As to why you're getting that warning -- it's possible that it's threading related and the VS Code terminal starts Julia multithreaded by default.

**Comment by IgnacioRubioScola** [comment]
Adding in `settings.json` the following
```
"terminal.integrated.env.linux":{
        "JULIA_COPY_STACKS": "1"
    },
```
solves the problem! 
Thank you!
