### ISSUE TITLE
`.JuliaFormatter.toml` gets ignored

### ISSUE THREAD

**Issue by hbarthels** [julia-vscode/julia-vscode#2589]
According to the documentation ([here](https://www.julia-vscode.org/docs/v1.5/userguide/formatter/)), it should be possible to configure the formatter with a `.JuliaFormatter.toml` file. For me, this doesn't seem to work, regardless of where I put this file (for example in the home directory, or the same directory as the file that should be formatted).

While searching for existing issues, I found this one: https://github.com/julia-vscode/julia-vscode/issues/2337 Based on this discussion, I'm not sure anymore if using `.JuliaFormatter.toml` should work.

So should it work? And if yes, any idea why it doesn't work for me?

I'm using
- VS Code 1.62.3
- macOS 11.6.1
- julia-vscode version v1.5.6
- Julia 1.6.4

**Edit:** After trying a few more things, I found out that it does work, but only if `.JuliaFormatter.toml` is in the current VS Code workspace. I would recommend that you point this out in the documentation, since the JuliaFormatter documentation ([here](https://domluna.github.io/JuliaFormatter.jl/stable/config/)) says that it searches up the file tree until a config file is (or isn't) found.

**Comment by pfitzseb** [comment]
https://github.com/julia-vscode/docs/commit/6b4a69df0d68fc8de4d7b1819db8c47ccde2728b

**Comment by findmyway** [comment]
It seems the `.JuliaFormatter.toml` file still gets ignored with the latest version `v1.65.2`.

I just put it under the root dir of the opened folder in VSCode.
