### ISSUE TITLE
New pixelated plot rendering mode is too pixelated

### ISSUE THREAD

**Issue by jkrumbiegel** [julia-vscode/julia-vscode#2597]
Here's an example of a CairoMakie png plot since https://github.com/julia-vscode/julia-vscode/pull/2570 was merged:

![grafik](https://user-images.githubusercontent.com/22495855/144256576-73fdd7d2-f136-455d-be66-05916305d000.png)

The text is not really readable, the 'f's lose their bars for example. Axis lines appear at different widths.
@pfitzseb said on Slack 
>  I think a good compromise here is to switch rendering mode when zooming in

So the pixelated mode would be activated whenever zoom level was at 100% or higher I assume?

**Comment by jkrumbiegel** [comment]
This link https://developer.mozilla.org/de/docs/Web/CSS/image-rendering says:

> pixelated
>    When scaling the image up, the "nearest neighbor" or similar algorithm must be used, so that the image appears to be composed of large pixels. When scaling down, this is the same as 'auto'.

It's interesting that here, the behavior is that of upsampling while it should be downsampling. I assume this is because the `transform` css logic is not correctly interpreted as upsampling, and the image is interpreted to be at 100% the whole time, therefore falling under the "nearest neighbor" rule.

**Comment by pfitzseb** [comment]
At this point I'm fairly convinced that `image-rendering` isn't implemented according to that spec. `transform` seems to play by its own rules as well...

**Comment by pfitzseb** [comment]
Fixed by https://github.com/julia-vscode/julia-vscode/pull/2602.
