### ISSUE TITLE
Julia does not use plot pane

### ISSUE THREAD

**Issue by RnoldR** [julia-vscode/julia-vscode#2599]
I am using Julia for two days. The preferred IDE seems to be vscode so I use the Julia language support extension. To be able to plot is my own HelloWorld experience and uptill now I have been busy for two days trying to get plotting up and running. I am not succeeding. Using ubuntu=21.10, vscode=1.62.3, julia=1.7.0.

The Julia extension documentation gives an [example on plotting](https://www.julia-vscode.org/docs/stable/userguide/plotgallery/). It ends with "You will get something like the following graph as a output in a **new tab** in VS Code". No such tab. In the settings plotting, plot pane, etc. are enabled. I get a pane, but with 0/0 plots, regardless of how often I try to plot. The code is the example code:

        using Plots
        x = 1:10; y = rand(10) 
        plot(x, y, label="my label")

The above code works in the julia REPL when I run that in a vscode terminal as well directly from an Ubuntu terminal. I found a workaround:
        
        using Plots
        x = 1:10; y = rand(10) 
        p = plot(x, y, label="my label")
        display(p)
        gui()

The display(p) shows the plot and removes it immediately. So that's why the gui() statement is needed, it shows the plot for some longer time: sometimes 5 seconds, sometimes much longer. 

I removed vscode and julia totally from my machine, deleting any directory, file or link on my system. After that I reinstalled just julia, vscode and the julia language support extension. No improvement. I experimented in a virtual machine with a clean setup: ubuntu=20.04, vscode=1.56, julia=1.7.0: same behavior.

I am aware of issues #819 and #1487 but I do not really understand their conclusion. In my setup the plot pane works for python and I find it a good solution when having many plots because of the plot navigator. So that brings me to my question:
- can I expect to see the plots in the plot pane when trying to plot?
- if so what should I do to see them?
- if not, is the current workaround the best or is there a beter one?

Thank you for your time.

**Comment by mbaz** [comment]
Make sure to start Julia with the `Julia: Start REPL` command, and not by invoking Julia manually in a regular terminal.

**Comment by RnoldR** [comment]
Could you explain that? I must be understanding it wrong, got julia: not found, Start not found or extra token REPL after end of expression.

**Comment by mbaz** [comment]
Open the command palette with `ctrl-shift-p`. There, type `Julia: Start REPL`.

**Comment by davidstreader** [comment]
Also just starting with Julia. (MacOS 11.5.2 ) and failing to see plots from VScode.  In the Julia REPL your code works and i see the plot in a stand alone window.
using Plots
```
    x = 1:10; y = rand(10) 
    p = plot(x, y, label="my label")
    display(p)
    gui()
```
 But from VScode I can not see any plot.
Then , in desperation and based on little or no understanding, I tried something simpler
```
using Plots 
    x = 1:10; y = rand(10) 
    print("l1\n")
    plot(x, y, label="my label")
    print("l2\n")
```
the only output I had was from the two print statements. Whereas in the repl I saw 
```
julia> x = 1:10; y = rand(10)
10-element Vector{Float64}:
 0.19698096438178236
 0.8777879239222209
 0.44640545250681674
 0.004885313280340253
...
```
any help much appreciated.

**Comment by davidstreader** [comment]
I uninstalled VSCode (looking up how to do this on stackoverflow) Then reinstalled VSCode afresh and only added the extension for Julia.  Then  after a lot of experimentation I found that
```
using DifferentialEquations
print("Line-1\n")
f(u,p,t) = 1.01*u
u0 = 1/2 
print("Line-2\n")
tspan = (0.0,1.0)
print("Line-3\n")
prob = ODEProblem(f,u0,tspan)
print("Line-4\n")
sol = solve(prob, Tsit5(), reltol=1e-8, abstol=1e-8)
print("Line-5\n")
using Plots
plot(sol,linewidth=5,title="Solution to the linear ODE with a thick line",
     xaxis="Time (t)",yaxis="u(t) (in μm)",label="My Thick Line!") # legend=false
plot!(sol.t, t->0.5*exp(1.01t),lw=3,ls=:dash,label="True Solution!")
#display(p)
gui()
print("Line-6\n")
```
takes time but between Line-5 and Line-6 appearing the gui for the plot dose appear but only for a fraction of a second. With simpler plots I was unable to see the plot flash on and off the screen.

**Comment by davidstreader** [comment]
Last comment:  A poor workaround is to save the plot.
```
using Plots
    gr()
    x = 1:10; y = rand(10) 
    print("l-1\n")
    plot(x, y, label="VSCode label", show=true)
    print("l-2\n")
    savefig("myVSplot.pdf")
    print("l-3\n")
```

The plot dose flash on and off the screen but I can not find how to stop this.
Sorry for multiple comments  david

**Comment by JipKim** [comment]
I'm experiencing the same issue: https://discourse.julialang.org/t/vscode-plot-pane-is-not-working-for-pgfplotsx/68171/2

<video src="https://wp.nyu.edu/jipkim/wp-content/uploads/sites/7641/2021/11/pgfplot.mp4" controls ></video>

<video controls="" autoplay="" muted="">
<source src="https://wp.nyu.edu/jipkim/wp-content/uploads/sites/7641/2021/11/pgfplot.mp4" type="video/mp4">
</video>

**Comment by davidstreader** [comment]
My problem was not setting up VSCode for Julia correctly. But when I followed the excellent tutorial in "JuliaCon 2020 | Using VS Code for Julia development | David Anthoff "
https://www.youtube.com/watch?v=IdhnP00Y1Ks   then plots did appear as expected.  (But alas - my fault- I could not get get his first function foo() to execute and had to  write a simple scatter plot function.) So if you are having problems not seeing plots it might be  you need to us workspaces, construct environments - link your editor to them etc. etc. as explained in tutorial.
