### ISSUE TITLE
Debugging does not work with csv command

### ISSUE THREAD

**Issue by pguerron** [julia-vscode/julia-vscode#2607]
Hi,

The debugger gets stuck at this line 

Firm_data_raw = CSV.read(dataDir * "myfile.csv", DataFrame, header = true);

Any clues? Thanks

**Comment by pfitzseb** [comment]
Put CSV into the list of compiled modules; that should make sure that call is close to native speed.

**Comment by pguerron** [comment]
Thanks for the reply. Where is the list of compiled modules?
