### ISSUE TITLE
Plots.jl figure resolution is low in VS Code in Julia 1.7

### ISSUE THREAD

**Issue by cristophermoen** [julia-vscode/julia-vscode#2610]
Plots.jl plotting resolution is weirdly low in the VS Code window after I switched to Julia 1.7.

I'm using the default GR backend, and running on a Macbook Pro 2020 Quad-Core Intel Core i5.

![image](https://user-images.githubusercontent.com/54078289/145264287-bd7faf17-c7a5-43eb-891e-705f72f59880.png)

**Comment by pfitzseb** [comment]
This got fixed in https://github.com/julia-vscode/julia-vscode/pull/2602.
