### ISSUE TITLE
Plot pane not staying in vsplit

### ISSUE THREAD

**Issue by tpgillam** [julia-vscode/julia-vscode#2612]
As of today (having just upgraded to vscode 1.63.0), I'm finding that the plot pane does not stay in a vsplit.

Steps to reproduce:

1. Start a fresh vscode, and open the usual julia repl
2. call `plot([1,2,3])` - the plot pane appears
3. Drag the plot pane into a vsplit
4. call `plot([4,5,6])` the new plot appears in the plot pane, and the plot pane moves out of the split to occupy the full width of the editor again (*)

(*) More precisely, if there are multiple splits open, the plot pane will move to occupy the same split as the file in which code is being run with `Execute Code in REPL and Move`.

Previously, on step 4, the re-organisation wouldn't occur (and this would evidently be preferable for workflow). Not sure if this is a Julia extension bug, or VSCode bug though.

This discourse thread describes the issue too: https://discourse.julialang.org/t/vs-code-plot-pane-wont-stay-splitted/72051/3

**Comment by pfitzseb** [comment]
Fixed by https://github.com/julia-vscode/julia-vscode/pull/2611.
