### ISSUE TITLE
Evaluate in module

### ISSUE THREAD

**Issue by jtrakk** [julia-vscode/julia-vscode#2627]
```jl
module M
x = 1

slow_computation()
end
```

If I start vscode, put the cursor on `x = 1` and press ctrl+enter, it will define `x=1` in `Main`, not `Main.M`. If I first evaluate the module then run `x=1` `x` will be defined in `Main.M`, but I don't want to do that because I'd have to wait for `slow_computation()`. I would like a way to run `x = 1` in the enclosing module without running `slow_computation()`. 

One solution would be for ctrl+enter on `x=1` to define any enclosing modules first automatically.

Alternatively, maybe there is another way I can organize my code so that `slow_computation()` isn't in that location.

**Comment by pfitzseb** [comment]
Mh, I don't think we should try to be smart here and evaluate a minimal `M` without top-level statements or anything like that.

In general, I'd recommend not doing any substantial work in a module's top-level scope.

**Comment by jtrakk** [comment]
In an example like

```jl
module M
loaded = load_data()
cleaned = clean(loaded)
calculated = calculate(cleaned)
visualize(calculated)
end
```

I want to run one line at a time within the module so I can look at each result before moving on to the next. Is that possible or are you suggesting that is a bad workflow?
