### ISSUE TITLE
SVG has blank space above it

### ISSUE THREAD

**Issue by jtrakk** [julia-vscode/julia-vscode#2628]
I'm not sure if this is an "issue" or if I'm just calling `display` incorrectly. I render an svg with `display(MIME("image/svg+xml"), read(io, String))`, the plot pane shows `data:image/svg+xml` at the top, and then there's blank space, then the image doesn't actually start until halfway down the plot pane, and it runs off the end so I have to scroll down to make it all visible. I don't need the `data:image/svg+xml`, and I would like the image to start at the top. 

![image](https://user-images.githubusercontent.com/43392409/146261818-af38c638-d9c2-434f-8241-51b00ab447b3.png)

**Comment by pfitzseb** [comment]
That should've gotten fixed in https://github.com/julia-vscode/julia-vscode/pull/2611, so please try julia-insiders.
