### ISSUE TITLE
"assigned but not used" when used in string interpolation

### ISSUE THREAD

**Issue by jtrakk** [julia-vscode/julia-vscode#2633]
It says variable "assigned but not used" when the variable is used in string interpolation.

**Comment by pfitzseb** [comment]
Can you share a code-snippet or screenshot of this happening?

**Comment by jtrakk** [comment]
![image](https://user-images.githubusercontent.com/43392409/146340616-fef80f81-2a19-475c-878a-fc1a4e82f49a.png)

**Comment by jtrakk** [comment]
![image](https://user-images.githubusercontent.com/43392409/146340856-f5af0c41-bd2f-4464-b649-2efc9f7a9f13.png)

**Comment by pfitzseb** [comment]
Can't repro that on the latest version of the extension:
![image](https://user-images.githubusercontent.com/6735977/146340988-aea568f2-53ec-4eea-873f-09f040dc2fc5.png)

**Comment by jtrakk** [comment]
Updated screenshot

**Comment by pfitzseb** [comment]
![image](https://user-images.githubusercontent.com/6735977/146341275-95a8b506-1ad7-4e81-bdf5-77d782a9d467.png)

**Comment by jtrakk** [comment]
Hover on the `i` in `for i`

**Comment by pfitzseb** [comment]
![image](https://user-images.githubusercontent.com/6735977/146341675-a4115d06-a75b-4c59-a4a7-f5c0fc3cf847.png)

**Comment by jtrakk** [comment]
Ok I'll reopen if it still happens next release.

**Comment by pfitzseb** [comment]
It shouldn't be happening on the current release either. What version of the extension are you on?

**Comment by jtrakk** [comment]
1.5.6

**Comment by pfitzseb** [comment]
Hm, I'd assume the linter is stuck on your system for some reason. Try restarting the language server.

**Comment by jtrakk** [comment]
Restarted language server. No change.
