### ISSUE TITLE
Failed to close tmux session 

### ISSUE THREAD

**Issue by xgdgsc** [julia-vscode/julia-vscode#2645]
Failed to close tmux session when using `stop REPL `.

v1.5.8

Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:39:46.686Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.0-92-generic

**Comment by pfitzseb** [comment]
Can you give some more info on this?

**Comment by xgdgsc** [comment]
Is there any log? I didn' t find any log message when triggering this.

**Comment by pfitzseb** [comment]
It would be helpful if you described what you did and how to reproduce the issue. 

Also, are you sure you have an active tmux session with the same name as the `persistentSession.tmuxSessionName` setting? All that command does is call `tmux kill-session -t ${sessionName}`.

**Comment by xgdgsc** [comment]
I just run `start REPL` and `stop REPL`, and click "yes" at right corner. I' m sure there's  an active tmux session  with the same name. `tmux kill-session -t ${sessionName}` works but through this extension it shows: 
![Peek 2021-12-23 17-26](https://user-images.githubusercontent.com/1189869/147219332-59070f13-859c-4ab1-83f1-a73ab6362953.gif)

**Comment by pfitzseb** [comment]
Hm. What's the session's name? Any special chars or something like that?

**Comment by xgdgsc** [comment]
julia_vscode_ex with setting `julia_vscode_${workspaceFolderBasename}`

**Comment by xgdgsc** [comment]
Works for me now. Don' t know what happened
