### ISSUE TITLE
Plotly backend for plots not working with 1.5.8

### ISSUE THREAD

**Issue by sebastianpech** [julia-vscode/julia-vscode#2651]
Running this
```
using Plots
plotly()
plot(1:10)
```
in the REPL in vscode, doesn't open the plot pane and just shows an empty plot in the plot navigator:
![image](https://user-images.githubusercontent.com/13043943/147215854-39e85aba-14b7-4c67-97b3-bdad9914acdb.png)
On 1.5.6 everything worked.

VSCODE INFO:
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Datum: 2021-12-15T09:37:28.172Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
Betriebssystem: Darwin x64 21.1.0

**Comment by AI-economist** [comment]
Hi. I have the same issue. I am not able to view any plots  using the "Plots" package and "Plotly()". 
`
import Pkg; Pkg.add("Plots")
begin
    using Plots 
    plotly()
end

#Let's create a scatter plot
begin
    scatter([1.5,2,-1],[1,5,-2], title="Points", label="Points")
end
`

julia> versioninfo()
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS =


Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by davidanthoff** [comment]
Same here, the plot pane just doesn't open at all for me now. @pfitzseb maybe something went wrong with the recent PR that was meant to fix the column layout things re the plot pane?

The way I can reproduce is to just try this in the REPL:
```
julia> using VegaLite

julia> @vlplot(:point, rand(10), rand(10))
```

**Comment by AI-economist** [comment]
Hi. Any update to this issue? My VSCode is still not displaying the plots? It goes from displaying it next to the editor , then sometimes opens a new tab on VSCode and then sometimes doesn't open a plot at all.

**Comment by Fizmath** [comment]
Just installed the latest VScode with Julia then the same , no plot pane with the back-ends ``plotly()  ,  plotlyjs() `` . Did this  temporary bypass until getting the bug fixed 

```julia
using Plots 
plotlyjs()

function show_html(p)
     filenmae = "myplot.html"
     savefig(p, filenmae)
     run(`google-chrome $filenmae`)
 end

p = plot(Plots.fakedata(50, 5), w = 3)

show_html(p)
```
or , just first comment the backend ` # plotly() ` then run the code , the pane appears  , now uncomment the back-end and re-run , the plot refreshed to the backend mode

**Comment by Fizmath** [comment]
For other backends the same bug ;  `using PlotlyJS `  returns no plots .  A trick until getting this bad bug fixed :

comment the backend  
```
using Plots
#plotlyjs()
plot(Plots.fakedata(50, 5), w = 3)
```
run the VScode ,  you see the plot , then uncoment the backend ``plotlyjs() `` and re-run , the plot refreshed to the backend mode
