### ISSUE TITLE
Workspace in Julia is blank

### ISSUE THREAD

**Issue by alexqo27** [julia-vscode/julia-vscode#2655]
Hi, I am having some issues with my workspace inside Julia on VS code. It turns out no matter what code I run on the REPL, I can not see anything on the workspace, it is always blank. Does anyone have any idea of why this might be happening? 

So far, I tried installing the Julia extension again and reinstalling VScode, but nothing has worked. Here there is a  typical  screenshot of my workspace layout:
![image](https://user-images.githubusercontent.com/67404686/147394935-c5aaa377-8e0e-4fd8-92bd-3e97b4791da0.png)

Thanks!

**Comment by chenuanc** [comment]
Have you solved this problem so far？

**Comment by chenuanc** [comment]
I have the same problem.

**Comment by pfitzseb** [comment]
The workspace only works with the special REPL started by `Julia: Start REPL`.

**Comment by chenuanc** [comment]
> 工作区仅适用于由`Julia: Start REPL`.

Thank you for your reply. Well, I thought it was the same as pychram.

**Comment by chenuanc** [comment]
Viewing array elements is not so convenient.

**Comment by pfitzseb** [comment]
Did you try the integrated table viewer for those?

**Comment by chenuanc** [comment]
Not yet. I'm a beginner, but I really want to learn to use it.
