### ISSUE TITLE
Plot Pane ceases to work after reconnecting to remote host

### ISSUE THREAD

**Issue by hdavid16** [julia-vscode/julia-vscode#2664]
Hi,

I see this behavior occasionally. I am working on a remote host with the persistent tmux option enabled. Occasionally, when I interrupt my connection and reconnect, the extension does not respond to plot commands from StatsPlots and my previous plots in the plot pane are gone. Any thoughts here?

Thanks!

**Comment by pfitzseb** [comment]
I think this is fixed now.
