### ISSUE TITLE
Typing `exit()` in integrated Julia REPL doesn't work properly

### ISSUE THREAD

**Issue by CameronBieganek** [julia-vscode/julia-vscode#2665]
VS Code attempts to restart the Julia REPL when I run `exit()`. And then when I run `exit()` a second time, it hangs.

![image](https://user-images.githubusercontent.com/8310743/147953745-aa480f93-4404-43fb-9aba-2e61dcae5f93.png)

```julia
julia> versioninfo()
Julia Version 1.7.0
Commit 3bf9d17731 (2021-11-30 12:12 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, tigerlake)
Environment:
  JULIA_EDITOR = vim
  JULIA_NUM_THREADS = 6
```

v1.5.8 of the Julia extension.

**Comment by pfitzseb** [comment]
For now you'll have to disable the `terminal.integrated.enablePersistentSessions` setting.

**Comment by pfitzseb** [comment]
I can't repro that on any machine I have access to. Is it possible that the "open REPL" command is being called somehow? Did you try without OhMyREPL?
