### ISSUE TITLE
Incorrect highlighting of interval notation `..` with leading 0

### ISSUE THREAD

**Issue by Datseris** [julia-vscode/julia-vscode#2669]
Now that the interval Julia packages have become quite a large part of the ecosystem, the interval notation `a..b` is used much more frequently. It is not correctly highlight when used with numeral literals:
![image](https://user-images.githubusercontent.com/19669089/148210143-fab1b2c5-23fd-47d1-ad88-f4463a661733.png)

0 should have been yellow above

**Comment by Datseris** [comment]
Notice that it is correctly highlighted with real number literals, e.g., `0.0..90.0` is all orange.

**Comment by Datseris** [comment]
Hm, oddly this seems to happen only for zero:

![image](https://user-images.githubusercontent.com/19669089/148210417-582e7d9d-c6d7-4d97-92d5-200cdbd385f4.png)

**Comment by pfitzseb** [comment]
Fixed by https://github.com/JuliaEditorSupport/atom-language-julia/pull/255.

Btw, you can almost always just check the highlighting here on GitHub:
```julia
0..90
0.0..0.0
10..10
```
