### ISSUE TITLE
Many false positive warnings in neovim LSP

### ISSUE THREAD

**Issue by simonmandlik** [julia-vscode/julia-vscode#2670]
Hi, I have set up [julials](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/julials.lua) language server in neovim and it looks quite impressive, but many times I get false positive warnings. Some examples from the current Flux.jl master:

<details>

<img width="798" alt="image" src="https://user-images.githubusercontent.com/16707112/148296388-e3918af3-bed1-4bef-ab98-9be30c1576a9.png">

<img width="1329" alt="image" src="https://user-images.githubusercontent.com/16707112/148296428-b8b58395-7eff-4481-a35c-cc4b75186ee3.png">

<img width="739" alt="image" src="https://user-images.githubusercontent.com/16707112/148296625-c751f3e1-7021-436e-aa20-aa7d65e66655.png">

<img width="656" alt="image" src="https://user-images.githubusercontent.com/16707112/148296660-68d38d24-26a5-44fe-8766-f2b7b1a7c3d9.png">

<img width="751" alt="image" src="https://user-images.githubusercontent.com/16707112/148296711-9613bc40-2703-4769-8bc7-4b71a87c93e9.png">

</details>

And from DataFrames.jl:

<details>

<img width="860" alt="image" src="https://user-images.githubusercontent.com/16707112/148297196-bc7b4c78-f94a-40b9-aa17-6b30d7054067.png">

<img width="612" alt="image" src="https://user-images.githubusercontent.com/16707112/148297354-aec48214-8761-4e23-976d-e0eb249512b1.png">

<img width="926" alt="image" src="https://user-images.githubusercontent.com/16707112/148297413-ade160aa-a48a-4b67-9474-6a189b112e49.png">

<img width="1262" alt="image" src="https://user-images.githubusercontent.com/16707112/148297449-ec9a4723-a0d8-40db-941f-63878fe5a350.png">

<img width="770" alt="image" src="https://user-images.githubusercontent.com/16707112/148297518-00754c52-c99b-448c-b786-913054a48271.png">

</details>

It is of course possible to disable the warnings, but I was wondering whether reports like this are useful and we can further improve the server. Thanks!

**Comment by davidanthoff** [comment]
Duplicate :)
