### ISSUE TITLE
Plot pane not opened with plotlyjs() backend

### ISSUE THREAD

**Issue by JakobAsslaender** [julia-vscode/julia-vscode#2671]
Hi,
I am not sure if I should file this issue here or in the plots repository, so please redirect me in case the problem lies on their end. Since about mid-December (did a major update take place at that time?), the following call on a fresh session does not open the plots pane:
```
using Plots
plotlyjs()
plot(rand(10))
```
The same is true with the `plotly` backend:
```
using Plots
plotly()
plot(rand(10))
```
With the `gr` backend, everything works fine:
```
using Plots
gr()
plot(rand(10))
```
And if I first plot with `gr`, I can switch the backend and everything also works as expected:
```
using Plots
gr()
plot(rand(10))
plotlyjs()
plot(rand(10))
```

I am on this system:
```
julia> versioninfo()
Julia Version 1.6.5
Commit 9058264a69 (2021-12-19 12:30 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.6.0)
  CPU: Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, westmere)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 4
```

with this VSCode version
```
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:38:17.605Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.2.0
```

using the `Julia v1.5.8` extension. 

Any idea what is going wrong here? Thanks a ton for looking into this, much appreciated!

**Comment by trigaut** [comment]
It is a problem with julia-vscode v1.5.8.
Apparently the issue is fixed by #2662 but is not yet released.

You can set the julia-vscode extension version to v1.5.6 in vscode to temporarily fix the problem.

**Comment by pfitzseb** [comment]
You can however try 1.5.9 on the julia-insiders channel.

**Comment by JakobAsslaender** [comment]
Sorry, I was somehow not capable of finding the existing issue report and PR. Thanks for fixing it, v1.5.9 works like a charm!
