### ISSUE TITLE
Plot pane is moved to the split of the current focused window

### ISSUE THREAD

**Issue by sebastianpech** [julia-vscode/julia-vscode#2672]
This is possibly a duplicate of #179 but I'm not sure because this definitely worked 2 months ago.

Focus always switched to the plot pane, but it stayed where I moved it. Now the plot pane is always moved to the currently active window group which is annoying because it always appears on top of the currently opened file. I tried julia plugin versions until 1.4.0 but the pane is always moved.

```
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Datum: 2021-12-15T09:37:28.172Z (Vor 3 Woche(n))
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
Betriebssystem: Darwin x64 21.1.0
```

**Comment by pfitzseb** [comment]
Something in VS Code's pane handling changed recently, but I couldn't quite track it down yet.

Can you try 1.5.9-insiders and see whether that fixes things for you?

**Comment by sebastianpech** [comment]
Still the same. First plot opens in a split to the right, second one moves the window over the opened file on the left.

**Comment by bgroenks96** [comment]
Can also confirm, I have this bug since updating. What was the last working version?

**Comment by pfitzseb** [comment]
VS Code 1.62, from the looks of it.

**Comment by sebastianpech** [comment]
@pfitzseb Works! Thanks

**Comment by pfitzseb** [comment]
Thanks for the feedback. Glad we got that fixed, finally...
