### ISSUE TITLE
Reload environment variables from direnv 

### ISSUE THREAD

**Issue by jtrakk** [julia-vscode/julia-vscode#2678]
The [direnv](https://marketplace.visualstudio.com/items?itemName=Rubymaniac.vscode-direnv) extension loads changes to the `.envrc`  file while vscode is running. These changes to the environment are applied, for example, in a Python environment so I can add an environment variable to the `.envrc` and start a new Python interpreter which can read the new variable from `os.environ`. 

However, starting a new Julia repl after applying a new .envrc, Julia is not able to see the new values. I have to restart vscode. I would like to have the new environment variables available in a new Julia repl.

**Comment by pfitzseb** [comment]
I'd recommend just writing a small shim script that starts your shell, loads your env, and then starts Julia.

We're currently (intentionally) not involving any shell when starting Julia.
