### ISSUE TITLE
Feature: show methods applicable to object (`methodswith`)

### ISSUE THREAD

**Issue by tfiers** [julia-vscode/julia-vscode#2679]
Idle feature idea (sparked by [these tweets](https://twitter.com/alexisgallagher/status/1483487864843214853) on "the power of the dot: what I envy about OOP").

I want to mimic the `obj.<tab>` behaviour of OOP editors (like vscode-python or IPython), as it is extremely useful for exploring APIs and writing code:

<img src="https://user-images.githubusercontent.com/3773558/150037847-b5824e64-20db-4614-8f39-b928b21cc55d.png" width=330>

For Julia, by example:
```julia
using FilePaths
dir = p"~/subdir"
dir|
```
, and then pressing some **shortcut key** would show:
```
absolute
chown
cp
exists
⋮
```
i.e. we call
```julia
methodswith(typeof(dir), supertypes=true)
```
, and suitably present the results, and make them iteratively filterable.
The `methodswith` call should probably be cached, as it's often rather slow.

[Same idea could be done in IJulia](https://github.com/JuliaLang/IJulia.jl/issues/1033).

**Comment by tfiers** [comment]
Just learned something quite similar is coming to the language itself: https://github.com/JuliaLang/julia/pull/38791
So closing for now.

**Comment by tfiers** [comment]
Also see https://github.com/julia-vscode/LanguageServer.jl/issues/979 and the linked discourse

**Comment by pfitzseb** [comment]
https://github.com/julia-vscode/LanguageServer.jl/pull/980
