### ISSUE TITLE
ReadOnlyMemoryError() in VS Code

### ISSUE THREAD

**Issue by vikram-s-narayan** [julia-vscode/julia-vscode#2680]
**Description:**
Running the following code produces a 'ReadOnlyMemory()' error in VS Code but works fine if I run the code from a Terminal (Command Line) on my Mac.

**To Reproduce:**
Run the following code. 

```
using Surrogates
f = x -> exp(x)*x^2+x^3
lb = 0.0
ub = 10.0
x = sample(100,lb,ub,UniformSample())
y = f.(x)
p = 1.9
my_krig = Kriging(x,y,lb,ub,p=p)
```

**Device information:**
MacBook Air (M1, 2020)
Chip Apple M1

**Comment by davidanthoff** [comment]
If this is still an issue, please reopen.
