### ISSUE TITLE
Numeric x axis labels are clipped

### ISSUE THREAD

**Issue by oscarrutt** [julia-vscode/julia-vscode#2687]
We have written the needed data into your clipbo
Issue Type: <b>Bug</b>

Execute the following Julia code.

plot(sin, size = (1200, 150))

The lower parts of the numbers labeling the x axis are clipped. Screen shot attached.

The problem appears in Visual Studio Code Jupyter notebook, VSC plot pane w/o Jupyter, in GKSTerm when run from a terminal session, and in a saved png. All macOS
[Clipped.numbers.pdf](https://github.com/julia-vscode/julia-vscode/files/7910912/Clipped.numbers.pdf)

Extension version: 1.5.10
VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:15:48.091Z)
OS version: Darwin x64 15.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz (2 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 2, 3|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710cf:30416617
vsccppwtstudy:30421978

```

</details>

ard because it was too large to send. Please paste.

**Comment by pfitzseb** [comment]
> The problem appears in Visual Studio Code Jupyter notebook, VSC plot pane w/o Jupyter, in GKSTerm when run from a terminal session, and in a saved png. All macOS

That doesn't sound like an issue with the Julia extension. Please open an issue at whatever plotting package you use.
