### ISSUE TITLE
Attach to external process

### ISSUE THREAD

**Issue by phlavenk** [julia-vscode/julia-vscode#269]
Would be great to :

* support the workflow [https://github.com/JunoLab/atom-julia-client/blob/master/manual/workflow.md]() where code can be evaluated within loaded module namespace.
* implement the Atom's: `Julia client: Attach to external process` command. I use this to attach to running IJulia notebook.

This two features are the main reason I'm still staying in Atom. 
Is there any convergence between the glue layer between julia to Atom and VS Code? Is it possible to reuse the same code or protocols?

**Comment by davidanthoff** [comment]
Eval into modules should be possible with the next version.

Attach to an external process is not something we've considered yet, I'll put it down as a feature suggestion.

In general, best to open two separate issues for two distinct ideas like this.

**Comment by davidanthoff** [comment]
I'm renaming this issue to track the attach to remote process feature. The eval into module feature is being tracked over at https://github.com/julia-vscode/julia-vscode/issues/982.

While I'm not generally opposed to implementing this feature here, I feel that the recent VS Code Remote capabilities might make this less urgent and actually give a much richer experience?

**Comment by phlavenk** [comment]
Great that eval to module IS implemented, though with revise workflow that is less used feature.
As i said, attach to external process is mainly usefull for attaching to running ijulia kernels. 
Can you explain how VS Remote can be used for this?

**Comment by davidanthoff** [comment]
Ah, sorry, I didn't catch the Jupyter part there, that is clearly a scenario that wouldn't be solved by the remote stuff in VS Code.

We are getting a native notebook implementation in the extension (see https://github.com/julia-vscode/julia-vscode/pull/980), so maybe we'll find some way to address your notebook scenario as part of that.

I'll leave this issue open for tracking the generic scenario for a REPL in VS Code that is attached to some Julia process that is not managed by the extension itself.

**Comment by pfitzseb** [comment]
Implemented nowadays.
