### ISSUE TITLE
Julia plotter chooses dumb minor grids

### ISSUE THREAD

**Issue by oscarrutt** [julia-vscode/julia-vscode#2691]
Issue Type: <b>Bug</b>

using Plots;
plot(sinc)

The plotter has choosen really awkward minor grids for both x and y axes. The x-axis has five increments between 0 and 2, making the ticks 0.4, 0.8, 1.2, 1.6, 2.0. This makes it difficult for the user to actually read values from these ticks.

Similarly, the y axis has chosen five increments between 0.0 and 0.3, making the ticks, well, you figure it out.

The plotter should be better at choosing the tick or grid values to be human-friendly. As it stands, this is not only hard to use but not publication quality.

Extension version: 1.5.10
VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:15:48.091Z)
OS version: Darwin x64 15.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz (2 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|3, 2, 3|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710cf:30416617
vsccppwtstudy:30421978

```

</details>

**Comment by davidanthoff** [comment]
That is an issue with the plotting package, not with the Julia extension for VS Code, please open an issue in their repository :)
