### ISSUE TITLE
Default major and minor grid lines on plots are too dim

### ISSUE THREAD

**Issue by oscarrutt** [julia-vscode/julia-vscode#2692]
Issue Type: <b>Bug</b>

The default coloring of grid lines for plots is much too dim. Major grid lines are dim and minor grid lines are almost invisible. See attached plot.
[Bad Plot.pdf](https://github.com/julia-vscode/julia-vscode/files/7917036/Bad.Plot.pdf)

Setting alpha values for major grid lines to 0.8 and  minor grid lines to 0.3 makes the plots much easier to read while still remaining unobtrusive.

Yes the user can set these values in his or her startup.jl file but why should this be necessary. And most users won't even learn about this possibility.

Also, the default line colors are not well-saturated and unnecessarily hard to see. Maybe this concept was copied from Mathematica which loves its pastel plots. A saturated color is much easier to see. The second attachment shows both improved grid lines and plot color.
[Good Plot.pdf](https://github.com/julia-vscode/julia-vscode/files/7916990/Good.Plot.pdf)

The default alpha values should be made darker and default colors more saturated.

Extension version: 1.5.10
VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:15:48.091Z)
OS version: Darwin x64 15.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz (2 x 2400)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>metal: disabled_off<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|5, 4, 3|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vs360:30404995
vsrem710cf:30416617
vsccppwtstudy:30421978

```

</details>

**Comment by davidanthoff** [comment]
Same thing, this has nothing to do with the Julia extension, but are all choices made in the plotting package you are using, please open issues there.
