### ISSUE TITLE
basic "Plots" Julia library

### ISSUE THREAD

**Issue by VespulaGermanica** [julia-vscode/julia-vscode#2694]
Issue Type: <b>Feature Request</b>

Hello, I have an issue when installing one of the most basic libraries for the Julia language, all the others are working finr but for some reason I get errors with this one, no matter what I do. 
Thanks

Extension version: 1.5.10
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by pfitzseb** [comment]
This is unlikely to be an issue with the extension. Please post a thread on https://discourse.julialang.org/ instead and make sure to include the error message you're seeing.
