### ISSUE TITLE
Julia REPL hangs when typing certain (somewhat obscure) Unicode characters

### ISSUE THREAD

**Issue by tmthyln** [julia-vscode/julia-vscode#2697]
When the input to the Julia REPL contains certain characters, the REPL hangs indefinitely.

## What I've tested
Just doing something like the following examples makes the Julia REPL within vscode hang indefinitely:

```julia-repl
julia> '🀀'
# hangs

julia> '♡'
# also hangs
```

(this also happens even if they're not in strings/chars (e.g. variables names like those used in [PlayingCards.jl](https://github.com/charleskawczynski/PlayingCards.jl)).

But, this works fine in a julia REPL through my normal terminal or using the vscode terminal.
```julia-repl
julia> '♣'
'♣': Unicode U+2663 (category So: Symbol, other)

julia> '🀀'
'🀀': Unicode U+1F000 (category So: Symbol, other)

julia> ♡
ERROR: UndefVarError: ♡ not defined
```

**Comment by pfitzseb** [comment]
Can't repro this. Are you on the latest version of the extension?

**Comment by tmthyln** [comment]
Going back to it a day later...I also can't reproduce this issue. (I was on the latest version of the extension and latest version of vscode.)

Digging into it further, I think there was some extra complication with a corrupt Project.toml that was fixed in the middle of the REPL session, so it seems like it seems it's actually probably not a vscode-extension issue/very particular edge case from a specific combination of actions. Will update if this changes.
