### ISSUE TITLE
Debug line mismatch when ${file} in launch.json is specified

### ISSUE THREAD

**Issue by jandaa** [julia-vscode/julia-vscode#2698]
The debugger fails to indicate where it is when it stopped in the case where you replace `"program": "${file}"`in `launch.json` with an actual file you want to debug (e.g.  `"program": "test.jl"`). It seems to jump to another read only file with just the function in it. This does not happen when you use `${file}` and run from the active file you want to debug

### Steps to Reproduce
1. Create a file called `test.jl` and with the following text
```julia
# Leave these two lines here
# to show the mismatch
function test()
    put_breakpoint_here = 1
end

test()
```

2. Put a breakpoint on the variable `put_breakpoint_here`
3. Create the following `launch.json` file under the '.vscode` folder

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "julia",
            "request": "launch",
            "name": "Run active Julia file",
            "program": "test.jl",
            "stopOnEntry": false,
            "cwd": "${workspaceFolder}",
            "juliaEnv": "${command:activeJuliaEnvironment}"
        }
    ]
}
```
4. Run the above debug configuration

### Expected behaviour
Breakpoint stops and highlights the correct line

### Actual behaviour
Stops, but in a new read-only file with the function test() at the very top and with no indication of where it has stopped. If you remove the two comments, you'll see it actually does stop on the correct line, which suggests that the line it is jumping to is the one in the compiled code which extracted the function to a separate read only file.

**Comment by pfitzseb** [comment]
This is technically working as intended -- the hover help for `program` tells you that it needs to be an absolute path (e.g. `"program": "${workspaceFolder}/test.jl"`). 

That said, https://github.com/julia-vscode/DebugAdapter.jl/pull/49 will allow for relative program paths.
