### ISSUE TITLE
Timeout after 2000 ms for 'terminate'

### ISSUE THREAD

**Issue by Saltsmart** [julia-vscode/julia-vscode#2702]
a weird problem happens when I restart debugger. VSCode displays an error and just stop debugging:
![1](https://user-images.githubusercontent.com/40828952/151489281-b8a1d65c-72d9-4f2f-bc52-7f4d33f8bf56.png)
(displays in VSCode Simplified Chinese plugin. This plugin has nothing to do with the problem and "Timeout after 2000 ms for 'terminate'" always shows when I toggle VSCode in English)

**Comment by Saltsmart** [comment]
I have no idea whether this could be reproduce on other machine. This error message was also displayed for AL plugin (see [this](https://github.com/microsoft/AL/issues/6230))

If config or os information is needed please let me know.

**Comment by pfitzseb** [comment]
Dup of https://github.com/julia-vscode/julia-vscode/issues/2283.

This message should be harmless.
