### ISSUE TITLE
Creates duplicate Julia REPL terminals on relaunch of vscode

### ISSUE THREAD

**Issue by xgdgsc** [julia-vscode/julia-vscode#2703]
![image](https://user-images.githubusercontent.com/1189869/151501311-f522e9d6-02ea-4d7a-82a3-37377ce42396.png)

I' m using tmux persistent mode. It seems everytime I relauch vscode there is a new terminal attached to the tmux session.

**Comment by pfitzseb** [comment]
Try disabling `terminal.integrated.enablePersistentSessions`, that doesn't play well with the Julia terminal.

**Comment by xgdgsc** [comment]
Thanks.

**Comment by pfitzseb** [comment]
Dup of https://github.com/julia-vscode/julia-vscode/issues/2621.
