### ISSUE TITLE
Is it possible to run code in jupyter/IJulia other than custom REPL?

### ISSUE THREAD

**Issue by clouds56** [julia-vscode/julia-vscode#2707]
Like what https://github.com/microsoft/vscode-jupyter/issues/273 and https://code.visualstudio.com/docs/python/jupyter-support-py does.

I think We could benefit from this:
* have one window show both text result and plot result
* know which code the result (text/plot) are coming from
* seamlessly connect to remote jupyter kernel
* integrate with other jupyter features like restart/variables

**Comment by pfitzseb** [comment]
Isn't that just what the jupyter extension with an IJulia kernel allows you to do?

**Comment by clouds56** [comment]
No, there's a little bit different.
Now we have 2 options with current julia and jupyter extention
1. write code in a `.jl` file, type Shift+Enter to run code in REPL (all done in julia extension)
2. write code and run code in jupyter, and optional save as ipynb. (all done in jupyter extension)

This issue requests a *new* feature that
Write code in a `.jl` file, and when type Shift+Enter, it send code to IJulia kernel.
So that we could take advantage of both 2 extensions just like what happens in a `.py` file.

**Comment by pfitzseb** [comment]
No, we won't hook up normal code execution to IJulia.
