### ISSUE TITLE
Stopped showing inline results while hovering

### ISSUE THREAD

**Issue by shubh-b** [julia-vscode/julia-vscode#2726]
Julia Extension in VS Code has been working great. But suddenly I am facing an issue just after VS Code got updated automatically. It has stopped showing the inline results while hovering on it. Hope attached snap below could be helpful to diagnose:

![VS Code Issue 0 - Copy](https://user-images.githubusercontent.com/28826994/152947151-93d762bf-83c8-46b5-96db-01404894c2c5.png)

Previously, I was getting a copy of output in REPL and it was providing inline results as well on which I could hover to see. Now only REPL output I am getting, not showing that array while hovering as it shows in snap. Can it be resolved?

**Comment by jeffreyesun** [comment]
I am experiencing the same problem. Updated Julia, VSCode, the Julia extension for VSCode, and all Julia packages to latest version and the problem persists.

**Comment by xgdgsc** [comment]
dup https://github.com/julia-vscode/julia-vscode/issues/2715
