### ISSUE TITLE
Incorrect highlighting for types with many nested braces

### ISSUE THREAD

**Issue by jaemolihm** [julia-vscode/julia-vscode#2738]
![image](https://user-images.githubusercontent.com/32537613/154011621-d8a56db2-77f5-4deb-83b2-31f9189ff7cd.png)

When there are many nested braces, the syntax highlighting does not apply to the full type.

**Comment by pfitzseb** [comment]
Dup of https://github.com/JuliaEditorSupport/atom-language-julia/issues/131.
