### ISSUE TITLE
Julia REPL giving different result from plain Julia

### ISSUE THREAD

**Issue by bradcarman** [julia-vscode/julia-vscode#2761]
Recently the Julia REPL has been ignoring changes I apply to my package. For example, I was able to delete my Manifest.toml file, restart the REPL and activate and successfully use my environment, even with the Manifest file missing. It seems the REPL is persistant, and not really starting a new session.

I checked my settings, persistence is disabled, and I disabled Revise. I even uninstalled the Julia extension and  installed the insiders extension. Restarting VS code, restarting the REPL, none of that will load the new code I added to my package or realize the Manifest file is
missing. The REPL seems stuck in an older state.

If I start plain Julia in the same VS Code session, everything works as expected.

Using version 1.8.0-beta1 and confirmed both the REPL and plain julia are the same version.

**Comment by bradcarman** [comment]
Note: this persistence issue seems to be related to the folder VS Code is open in.  If I open VS Code in another folder, start the Julia REPL, cd() to my package folder, activate the environment, then all my code execution works as expected. But if I simply start VS Code in my package folder, and start the REPL, I get the "old" Julia session or code I should say, compilation is still happening, and I can't seem to get new changes to my package recognized and loaded, such as changes I made to a struct for example.  It’s as if VS Code is using an old copy of the code it keeps somewhere.

**Comment by pfitzseb** [comment]
Did you double check that both Julia REPLs have the same environment active? It's possible that the VS Code REPL is started in an environment that has a static copy of your code.

**Comment by bradcarman** [comment]
I'm very sure that both plain Julia and extension Julia REPL are activating the same path and environment. I can get the extension Julia REPL to work if I open VS Code in a different folder and then ‘cd(project path)’

Btw, the package I'm working on is in develop mode, so I can see from ‘Pkg.status()’ that I have the correct and same path to the package.

**Comment by bradcarman** [comment]
Here is a screen shot showing the 2 cases...

From a fresh start of VS Code, on the left is the extension Julia REPL, on the right is plain Julia.  The following can be seen:

1. They are both in the same directory
2. They are both loading the same exact Project.toml
3. They are both the same Julia version

But as can be seen, the extension Julia REPL is stuck in the past with older versions in the Manifest.  How is this possible?!?! 

![image](https://user-images.githubusercontent.com/40798837/156588722-b22673f9-3ae6-4b24-8daa-8aa0364d0cbf.png)

**Comment by pfitzseb** [comment]
What's `Base.active_project()` in both sessions?

**Comment by bradcarman** [comment]
They are both the same (and matching `Pkg.status()`)...

```
julia> Base.active_project()
"d:\\Work\\IST\\Projects\\JuliaPackages\\CatView.jl\\scripts\\Project.toml"
```

**Comment by pfitzseb** [comment]
Do you have the `julia.useCustomSysimage` setting active? Anything in `julia.additionalArgs`?

**Comment by bradcarman** [comment]
No not using custom sysimage.  I checked, both instances give the same `Base.julia_cmd()`, and no additional args are given...

```
julia> Base.julia_cmd()
`'C:\Programs\julia-1.8.0\bin\julia.exe' -Cnative '-JC:\Programs\julia-1.8.0\lib\julia\sys.dll' -g1`
```

**Comment by pfitzseb** [comment]
Not on Windows, apparently. You can try the dev instructions [here](https://github.com/julia-vscode/julia-vscode/blob/master/CONTRIBUTING.md) and then set a breakpoint [here](https://github.com/julia-vscode/julia-vscode/blob/4ef98597aea5c9c7876f85e54e814c8003ad6973/src/interactive/repl.ts#L219).

**Comment by bradcarman** [comment]
I haven't had a chance to check that out yet, but I did discover the solution.  If I delete the ".vscode" folder with the setting...

```
{
    "julia.environmentPath": "c:\\Work\\IST\\Projects\\JuliaPackages\\CatView.jl\\scripts"
}
```

then finally, starting the extension Julia REPL was able to see the latest code changes and Manifest.  

It seems that somewhere somehow the `julia.environmentPath` setting is causing VS Code or the extension to cache code or memory.

**Comment by pfitzseb** [comment]
There's definitely nothing being cached, but glad you figured out the solution.
