### ISSUE TITLE
julia vscode extension memory usage

### ISSUE THREAD

**Issue by ngam** [julia-vscode/julia-vscode#2766]
Hi, I have noticed that while idling in another project (non-julia project), julia vscode extension ends up using ~0.5--1.0 GB of memory just for being there. Is this expected? It seems like it's triggering julia in the background waiting for some input (despite not using or intending to use julia for that particular session). 

Would it make sense to limit this behavior to cases where it is very clear that the user is trying to use julia? That is, would it be possible to forbid julia vscode extension from triggering a julia process in the background waiting for input? As far as I know, julia vscode extension is the only extension causing this sort of behavior. A situation when it is "very clear" that the user wants to use julia would be for example launching the REPL.

Notes: 
- One could try to force-quit that process, but it will immediately come back on. 
- Disabling the extension does indeed kill that process for good.

Details: 
```
Name: Julia
Id: julialang.language-julia
Description: Julia Language Support
Version: 1.5.11
Publisher: julialang
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=julialang.language-julia
```
```
julia> versioninfo()
Julia Version 1.9.0-DEV.108
Commit 3a5dc09ce4 (2022-03-01 15:17 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.3.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 1 on 4 virtual cores
```

<img width="728" alt="Screen Shot 2022-03-04 at 15 31 55" src="https://user-images.githubusercontent.com/67342040/156837331-1976cc84-33e8-4cd2-976f-f40666157913.png">

Thanks, and let me know if you'd like any additional information.

**Comment by pfitzseb** [comment]
The extension is only activated in [these cases](https://github.com/julia-vscode/julia-vscode/blob/master/package.json#L31-L76); the language server process you're seeing is always started when the extension is active. I think that's fairly standard across the ecosystem.

So I suspect your workspace contains a `.jl` file or Jupyter notebook.

**Comment by ngam** [comment]
> Jupyter notebook

Most likely it had a Jupyter notebook. Would it be technically possible to limit this to the case when the Julia kernel is selected in the Jupyter notebook? Just wondering.



> I think that's fairly standard across the ecosystem

Hmmm. What do you mean here? The VSCode ecosystem? 

Maybe, yes, it is standard (I do see other extensions active) but they tend to happen only when they are being used. I guess the biggest difference is that this Julia process takes a significant portion of memory and so it is not noticeable?

**Comment by ngam** [comment]
> The extension is only activated in [these cases](https://github.com/julia-vscode/julia-vscode/blob/master/package.json#L31-L76)

Thanks for this; I suppose I can edit it for my use case. Just checking, is this also available in settings or could be added to settings.json?

**Comment by pfitzseb** [comment]
> Most likely it had a Jupyter notebook. Would it be technically possible to limit this to the case when the Julia kernel is selected in the Jupyter notebook? Just wondering.

Actually, the extension should only activate when you open a notebook. And no, I don't think so.

> Maybe, yes, it is standard; I do see other extensions active, but they tend to happen only when they are being used. I guess the biggest difference is that this Julia process takes a significant portion of memory and so it is more noticeable?

Maybe so, but I think all language servers start when you have the relevant files in the workspace.

> Thanks for this; I suppose I can edit it for my use case. Just checking, is this also available in settings or could be added to settings.json?

No, I don't think so.

**Comment by ngam** [comment]
Okay, here is how it seems to work. Yes, you're correct that it only happens when one opens a notebook. However, it doesn't stop after closing the notebook. Only stops after closing the whole project/window of that vscode session.

On editing package.json, one could edit on disk and it works fine: ~/.vscode/extensions/julialang.language-julia-1.5.11/package.json

Thanks a lot for your help! I am going to close this for now since the issue has been addressed, but feel free to reopen it if you think otherwise.

**Comment by xgdgsc** [comment]
I ' d like to remove ` "workspaceContains:**/*.jl"` from activation events, which alone would save a few GB of memory for me. https://github.com/microsoft/vscode-python/blob/f7d7354832fcc3b4db4b527b9579c7295892c69f/package.json#L63 Python extension doesn' t include something like this.

**Comment by pfitzseb** [comment]
We can probably do that and only auto-activate when a `Project.toml` is present in the workspace folder root. Open a PR for further discussion?
