### ISSUE TITLE
Plots terminate on Windows without showing a plot

### ISSUE THREAD

**Issue by epogrebnyak** [julia-vscode/julia-vscode#2767]
I'm failing to make a plot in VS Code by clicking Julia: Ececute Active File in REPL:

```
using Plots
x = 1:10 
y = rand(10)
plot(x, y, label="my label")
```

The error message is:

```
The terminal process "julia.exe '-i', '--banner=no', '--project=C:\Users\Евгений\.julia\environments\v1.7', 'c:\Users\Евгений\.vscode\extensions\julialang.language-julia-1.5.11\scripts\terminalserver\terminalserver.jl', '\\.\pipe\vsc-jl-repl-4937e752-2e1c-405c-82e4-e2b6dc2cd528', '\\.\pipe\vsc-jl-cr-82604b85-ec17-4cc9-a588-469057d4c34a', 'USE_REVISE=true', 'USE_PLOTPANE=true', 'USE_PROGRESS=true', 'DEBUG_MODE=false'" terminated with exit code: 1.
```

**Comment by epogrebnyak** [comment]
Perhaps similar to #2599

**Comment by pfitzseb** [comment]
What happens if you run that code in a non-VS Code terminal?

**Comment by epogrebnyak** [comment]
@pfitzseb - what I run ths code in command line without VS Code nothing happens - that code runs for a while, then finishes, no pop-up.

I have an alternative code that shows a plot in VS Code:

```
using VegaLite, DataFrames, Query, VegaDatasets

cars = dataset("cars")

p = cars |>
@vlplot(
    :point,
    x=:Horsepower,
    y=:Miles_per_Gallon,
    color=:Origin,
    width=400,
    height=400
)
```

but code with Plots.jl (original post above) crashes the REPL and does nothing on  command line.

Wonder what would be needed to debug this. I suspect folders like `C:\Users\Евгений\` may have an effect, but not sure. Tried `set JULIA_DEPOT_PATH=d:\julia_depot` to isolate direcotory names effects.

**Comment by pfitzseb** [comment]
Try putting the plotting code into a file and run that with `Julia: Run File in New Process`. That way you shouldn't lose the output and might get an idea of why Julia crashed.

**Comment by epogrebnyak** [comment]
Thanks, trying now! Can you please hint where I can set JULIA_DEPOT_PATH
for the new process?

пн, 7 мар. 2022 г. в 14:49, Sebastian Pfitzner ***@***.***>:

**Comment by epogrebnyak** [comment]
Running in new process helped a bit, thanks again for the clue!

Here is the result I get

1) Nothing happens if I just use Plots.plot() - no graph, no crash

> Executing task: C:\tools\Julia-1.7.2\bin\julia.exe --color=yes
--project=C:\Users\Евгений\.julia\environments\v1.7
c:\Users\Евгений\Desktop\julia_excercise\plots.jl <

Terminal will be reused by tasks, press any key to close it.

2) If I add Plots.gui() - I get an error - possibly due to non-latin
letters in a location of .julia directory:


GKS: file open error
(C:\Users\???????\.julia\artifacts\bc436b9b4f04cc9b6f773cb544ba67fb739121a3\bin\..\FONTS\GKSFONT.DAT)
open: Invalid argument
connect: Invalid argument
GKS: can't connect to GKS socket application

GKS: Open failed in routine OPEN_WS
GKS: GKS not in proper state. GKS must be either in the state WSOP or WSAC
in routine ACTIVATE_WS
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP
in routine FILLAREA
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP
in routine FILLAREA
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP
in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP
in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP
in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP
in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP
in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP
in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP
in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP
in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP
in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP
in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP
in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP
in routine TEXT
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP
in routine TEXT
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP
in routine TEXT
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP
in routine TEXT
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP
in routine TEXT
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP
in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP
in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP
in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP
in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP
in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP
in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP
in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP
in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP
in routine POLYLINE
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP
in routine TEXT
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP
in routine TEXT
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP
in routine TEXT
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP
in routine TEXT
GKS: GKS not in proper state. GKS must be either in the state WSAC or SGOP
in routine POLYLINE












пн, 7 мар. 2022 г. в 15:14, Evgeny Pogrebnyak ***@***.***>:

**Comment by epogrebnyak** [comment]
I will also look for way to add custom .julia location for VS Code - setting the JULIA_DEPOT_PATH with non-latin characters. 

I think I should close this issue here, as it is not related to extenstion. 

Thanks for walking me through diagnostics, @pfitzseb!

**Comment by epogrebnyak** [comment]
> > setting the JULIA_DEPOT_PATH with non-latin characters
> 
> That really shouldn't be necessary -- pretty sure we have a bunch of users with non-ascii home dirs and they don't have problems.

Oh, good to know! non-ascii dirs were a problem for a while in Python, that is why I thought this direction.
