### ISSUE TITLE
White background in plot panel for transparent plots

### ISSUE THREAD

**Issue by wujinq** [julia-vscode/julia-vscode#2768]
I'm using [PGFPlots](https://nbviewer.org/github/JuliaTeX/PGFPlots.jl/blob/master/doc/PGFPlots.ipynb), and its outputs are SVGs with transparent backgrounds. When shown in julia-vscode in a dark theme, I can't see clearly the x and y axes and ticks. It may be a good idea to give a white background to such plots.

**Comment by pfitzseb** [comment]
No, that's the plotting package's responsibility.
