### ISSUE TITLE
format jumps to file end 

### ISSUE THREAD

**Issue by xgdgsc** [julia-vscode/julia-vscode#2771]
Suddenly when I save to format the cursor jumps to the file end.

Version: 1.65.0
Commit: b5205cc8eb4fbaa726835538cd82372cc0222d43
Date: 2022-03-02T11:12:36.248Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.0-100-generic

julia-vscode  version 1.5.11

**Comment by pfitzseb** [comment]
Can't repro this. Does this happen on any file?

**Comment by xgdgsc** [comment]
No. Even in the same window not restarted the same file once occured and not now. And copying same content to another file, this doesn' t occur. And since I use a persistent tmux session. Window reloading doesn't fix this. I will report if I find a robust reproducible example.

**Comment by xgdgsc** [comment]
I triggered once of this when I add white lines at end of file and save. But not on a copy paste file.

**Comment by pfitzseb** [comment]
> And since I use a persistent tmux session. Window reloading doesn't fix this.

That's unrelated -- formatting is powered by a different process.

**Comment by xgdgsc** [comment]
Also happens to Go ,json files. Maybe not a julia extension issue. It sometimes stops happening while I switch files. I' ll look elsewhere.
