### ISSUE TITLE
Add keyboard shortcut to run single line of code regardless of scope.

### ISSUE THREAD

**Issue by nathanrboyer** [julia-vscode/julia-vscode#2816]
I am trying to write a function within another function and am finding it quite difficult to test as I go. I have to highlight a line with the mouse, then press Shift+Enter to "Execute Code in REPL", then highlight the next line with the mouse... I searched for a keyboard shortcut to highlight the current line and save me from reaching for the mouse, but the VSCode default of Ctrl+L is overwritten by the Julia extension to clear the REPL. What is the suggested way to do this?

**Comment by nathanrboyer** [comment]
Shift+Alt+Cursor-Right is working for me but Ctrl+L clears the REPL rather than highlighting the current line even if my cursor is in the editor.

![image](https://user-images.githubusercontent.com/65452054/160623965-63bd6868-2b87-423f-aa20-f049b4dcc6cd.png)
It looks like maybe I added the terminal clear shortcut and forgot 😅. However, I do also want that functionality, and Ctrl+L seems to be the suggested shortcut ([thread1](https://discourse.julialang.org/t/clear-terminal-window/17046), [thread2](https://discourse.julialang.org/t/commands-in-julia/22067)).

**Comment by nathanrboyer** [comment]
I am having another related issue.

```julia
julia> using ASME_Section8_Division3_Edition2021 # My local package
[ Info: Precompiling ASME_Section8_Division3_Edition2021 [d29f79e6-4313-439e-a1e0-c6c95527bf41]

julia> file_location = joinpath(@__DIR__,"test","testdata","verification")
"C:\\Users\\nboyer.AIP\\.julia\\dev\\ASME_Section8_Division3_Edition2021\\test\\testdata\\verification"

julia>     df = DataFrame(CSV.File(file_location))
ERROR: UndefVarError: file_location not defined
```

The first two lines were typed. The last line was evaluated by highlighting a line inside a function (`function read_principal_stresses(file_location)`) and pressing Ctrl+Enter. I don't understand why `file_location` is not defined since I manually defined it in the line above.

**Comment by pfitzseb** [comment]
Ctrl-Enter et al run your code in a specific module (indicated in the lower right), which usually is not Main.

**Comment by nathanrboyer** [comment]
![image](https://user-images.githubusercontent.com/65452054/160633581-e5b95a2e-0670-4275-a6d0-8edfe344f8f9.png)

**Comment by pfitzseb** [comment]
So the REPL always executes code in Main, whereas in-editor evaluation follows the module. Mixing the two usually doesn't work, but you can click the module selector and select Main manually.

**Comment by nathanrboyer** [comment]
Okay, now my dependencies are not loaded.
![image](https://user-images.githubusercontent.com/65452054/160636036-4c9e419a-84fe-4221-bf36-a429b45d1b67.png)

I think I should be in the package Module so I have the correct package versions loaded?

**Comment by nathanrboyer** [comment]
Partially answered [here](https://discourse.julialang.org/t/how-to-use-vscode-and-repl-to-write-and-test-a-package/78818).
