### ISSUE TITLE
[Question] Julia Language server cannot start.

### ISSUE THREAD

**Issue by zhiyuanzhai** [julia-vscode/julia-vscode#2819]
With Julia v1.6.5(LTS), I have got this problem:
```
The Julia Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.
```
Problem is that I don't know how to get more information of this error. I need some help for that.

**Comment by pfitzseb** [comment]
Go to Output > Julia Language Server, where you should hopefully find the error message.

**Comment by zhiyuanzhai** [comment]
> Go to Output > Julia Language Server, where you should hopefully find the error message.

@pfitzseb Thanks! I have found the error message and it's the same as in #2124. So I'm closing this issue.
