### ISSUE TITLE
Disable vscode blue wave warning “The included file can not be found.” 

### ISSUE THREAD

**Issue by Himbeersternchen** [julia-vscode/julia-vscode#2837]
Hi Guys,

i have in a julia scripts main.jl the code line
@everywhere include(“test/test_functions.jl”)

and i ran it in REPL or terminal, it’s no problem (this project must be ran in the project folder not in the test folder). But in the vscode editor there is always a blue wave warning under this line and if i move my cursor to it, it shows me “The included file can not be found.”
How should i change the vscode settings in order to disable this warning?

I tried:
I ran test/main.jl in the project folder:
tmp/project$ julia -p 3 test/main.jl
as the warning requested i have changed test/main.jl to have the following codes:
using Distributed
@everywhere include(“test_functions.jl”)

But I get the error:
ERROR: LoadError: On worker 2:
could not open file /tmp/project/test_functions.jl

The file structure of my project is like:

project:
- -test:
 ---main.jl
 ---test_functions.jl

**Comment by pfitzseb** [comment]
Ref https://discourse.julialang.org/t/disable-vscode-blue-wave-warning-the-included-file-can-not-be-found/79087.

This warning cannot be disabled atm. I also still maintain that it's actually correct (and am very confused as to why you're getting that error).

**Comment by Himbeersternchen** [comment]
@pfitzseb Thanks for your answer. I found out that, this error only occures on subworkers (worker 2,3,4), but not on worker 1. If i don't use the macro everywhere, this error does not occure. But i don't get it why.

**Comment by Himbeersternchen** [comment]
The issue about include() relative paths are different on worker processes does exist, ref: https://github.com/JuliaLang/julia/issues/27429. But why the error only shows by me and not by everyone. Is there something wrong in my settings?

**Comment by pfitzseb** [comment]
What Julia version are you using?

**Comment by Himbeersternchen** [comment]
Version 1.5.3 (2020-11-09)

**Comment by pfitzseb** [comment]
That version isn't really supported anymore. I'd heavily recommend upgrading to 1.6 at least.

**Comment by Himbeersternchen** [comment]
Okay i ll update to julia 1.6 and try it again.

**Comment by pfitzseb** [comment]
Great, glad you got it working.
