### ISSUE TITLE
No workspace data on in VS CODE.

### ISSUE THREAD

**Issue by inse0918** [julia-vscode/julia-vscode#2840]
![image](https://user-images.githubusercontent.com/93040154/162584498-34c16bb3-dd0a-46b7-bf85-347eee0f5c1f.png)

I installed JULIA with VSCODE.

As i know, When the codes is running, variables are create in workspace blcok.

But there is no variables data in workspace block...

**Comment by davidanthoff** [comment]
I believe you executed the entire file? That mode of running code is not integrated with the Workspace, you need to run your code in the Julia REPL.

**Comment by inse0918** [comment]
![image](https://user-images.githubusercontent.com/93040154/162623371-d7083887-0e4f-4847-9f51-30ba8254e94d.png)
Thank you very much ! ! ! ^^
