### ISSUE TITLE
Print versioninfo() on startREPL

### ISSUE THREAD

**Issue by xgdgsc** [julia-vscode/julia-vscode#2849]
Everytime I run start REPL I would wonder if I' m using the correct version or whether I updated julia successfully. And it seems to be common practice when starting such REPL in other language IDEs from my memory.

**Comment by pfitzseb** [comment]
You can add `--banner=yes` to the `julia.additionalArgs` setting. We may end up changing the default in https://github.com/julia-vscode/julia-vscode/pull/2855.
