### ISSUE TITLE
Failed to close tmux session: can't find session: julia_vscode_

### ISSUE THREAD

**Issue by xgdgsc** [julia-vscode/julia-vscode#2851]
I have `"julia.persistentSession.tmuxSessionName": "julia_vscode_${workspaceFolderBasename}",`

set.
Only on one of my machines it happens to when I do `stop REPL` the error of 
`Failed to close tmux session: can't find session: julia_vscode_` shows. While `start REPL ` works correctly with the `${workspaceFolderBasename}` resolved on the same machine ( its a remote session). On all other machines with the same version of vscode(1.66.2) and julia-vscode(v1.6.17) there' s no this issue. I' ve tried remove `.vscode-server/bin` and killing all code processes on this machine and reinstall but with same results. 

It' s a minor issue that affects only one machine. But it' s really weird.

**Comment by pfitzseb** [comment]
So `${workspaceFolderBasename}` is correctly resolved when starting a REPL, but not when stopping it? I.e. you end up with a `julia_vscode_foo` session, but we try to kill `julia_vscode_` when you try to stop that REPL?

**Comment by xgdgsc** [comment]
Yes

**Comment by pfitzseb** [comment]
Ok, this kinda sounds like an upstream error then, since we're not doing anything special to resolve `workspaceFolderBasename`.

**Comment by xgdgsc** [comment]
It started occuring on another remote machine
```
Failed to close tmux session: more than one session: julia_vscode_
```
I didn' t find anything on vscode issues.

**Comment by xgdgsc** [comment]
Not happening recently.
