### ISSUE TITLE
VSCode+Julia now changing style throughout my files

### ISSUE THREAD

**Issue by dlfivefifty** [julia-vscode/julia-vscode#2852]
Now when I try to modify a file it is changing style, e.g., `(λ,μ) = f(...)` becomes `(λ, μ) = f(...)`, `where T = ....` becoming `where {T} = ...`. I don't want this as it ruins Github diff!

How do I turn this off? I don't think this should have been enabled by default as it is doing this silently.

It seems to happen whenever I paste something.

**Comment by pfitzseb** [comment]
Disable auto-formatting?

**Comment by dlfivefifty** [comment]
Ah, guess this was a VSCode default that somehow got turned on 🤦‍♂️

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/1229737/164231458-000b97e7-f595-4c36-986e-76b97a34141d.png">
