### ISSUE TITLE
Go to Definition (F12) for import/using statements

### ISSUE THREAD

**Issue by guidorice** [julia-vscode/julia-vscode#2860]
In julia-vscode extension, there seems to be no way to Go to Definition to see the toplevel source code of an imported package. I found I can do it from the REPL like this:

```
julia> import Package
julia> edit(Package)
```

It would be nice if just hitting F12 over an `import` or `using` statement in Julia code would accomplish the same thing as those 2 lines of code in the REPL.

Thanks so much for your efforts making Julia awesome in VScode. 👍🏽

**Comment by pfitzseb** [comment]
That already works, at least if the package is in the currently active environment.

**Comment by pfitzseb** [comment]
Ah, I see what's going on here. We're downloading cache files for packages (which contain all info we need for navigation, completion, docs, etc), but for GeoInterface specifically (well, probably for more packages) we can't automatically resolve and insert the package path in place of our placeholders.

I should have a fix for that in a bit.

**Comment by guidorice** [comment]
Cool, thanks much 👍🏽
