### ISSUE TITLE
ERROR: cannot assign a value to variable IJulia.ans from module Main when using connect to external REPL

### ISSUE THREAD

**Issue by xgdgsc** [julia-vscode/julia-vscode#2861]
With  v1.6.17 and jupyter lab 3.3.4
```
ERROR: cannot assign a value to variable IJulia.ans from module Main
```
shows when connected to external REPL and run code inside vscode.

**Comment by pfitzseb** [comment]
I don't understand your setup -- why's IJulia loaded and what does Jupyter Lab have to do with anything?

**Comment by xgdgsc** [comment]
Connected to a jupyuter lab kernel, is it supported?

**Comment by pfitzseb** [comment]
Hm, certainly not officially :) Do you have a stacktrace for the error?

**Comment by xgdgsc** [comment]
That ERROR line is the only stacktrace printed. I just remembered using atom-juno with a jupyter notebook concurrently a few years ago which was nice. Considering vscode-jupyter has many issues I don' t like, might be useful if this is supported.

**Comment by pfitzseb** [comment]
I'm happy to merge a PR for this, but don't think I'll have the time to dig into this myself.

**Comment by xgdgsc** [comment]
It seems the code is evaluated (like using Modules adds Modules in WORKSPACE and takes time to precompile) . But there 's problem displaying result in notebook and vscode. I searched `ans` inside VSCodeServer and IJulia.jl but not sure where it is that tries to set `IJulia.ans`. Any clues?

**Comment by pfitzseb** [comment]
Might be related to
https://github.com/julia-vscode/julia-vscode/blob/f578fee2a56e3a3855f6900299bec340a88d303f/scripts/packages/VSCodeServer/src/eval.jl#L157-L158
Try getting rid of the `ans` handling code there.

**Comment by xgdgsc** [comment]
Thanks. Commenting out `@eval` line works. Would it cause trouble in other conditions?

**Comment by pfitzseb** [comment]
It shouldn't, no. Can you give https://github.com/julia-vscode/julia-vscode/pull/2867 a go and report back as to whether it works?

**Comment by pfitzseb** [comment]
https://github.com/julia-vscode/julia-vscode/pull/2869 will speed plot navigation up by a lot.
