### ISSUE TITLE
Reproducible hang when restarting language server

### ISSUE THREAD

**Issue by jakobnissen** [julia-vscode/julia-vscode#2873]
I've been able to reproduce this problem on two different systems. Here's how
* Create a new environment in a directory
* Open VSCode in that environment. Make sure the language server uses the same environment
* Use the REPL to add a new package to the environment
* Restart language server
* It will now hang indefinitely, and won't work until VSCode is restarted

This is on extension version 1.6.17, VSCode 1.66.2, Julia 1.7.2, on linux

**Comment by pfitzseb** [comment]
Fixed by https://github.com/julia-vscode/julia-vscode/pull/2859.
