### ISSUE TITLE
Add ExcelReaders integration

### ISSUE THREAD

**Issue by ZacLN** [julia-vscode/julia-vscode#288]
Add to REPL
- Right click on excel file in explorer
- check whether it's installed
- select sheet from pop down menu
- load to excel
- option to copy the code that has just been run to the copy/paste buffer or into current file

**Comment by davidanthoff** [comment]
Yep, this would be nice. I think we should go straight to the FileIO.jl integration that I created for lots of tabular file formats, though. That way we'll get support for not just Excel, but also CSV, Feather, all the ReadStat.jl files and soon Parquet.jl. Happy to provide more points on how to get started once we tackle this for real.
