### ISSUE TITLE
Autocomplete for table columns

### ISSUE THREAD

**Issue by jariji** [julia-vscode/julia-vscode#2882]
I would like to have autocomplete on `t.` for Tables.jl columns such as for DataFrames.jl and TypedTables.jl

**Comment by pfitzseb** [comment]
You should be getting these kinds of completions for "live" objects (at least if `julia.runtimeCompletions` is enabled):
![image](https://user-images.githubusercontent.com/6735977/167100845-6ab1cce8-bca2-42f2-bb80-9bfffce388bc.png)

**Comment by charlesbrodhead3** [comment]
This is fantastic, thanks!  I waited for many years for Pycharm (paid version) to implement this for Python Pandas data frames but it is *still* unavailable...
