### ISSUE TITLE
Profiling colors not very bright

### ISSUE THREAD

**Issue by gdalle** [julia-vscode/julia-vscode#2883]
Hi there, and thank you for the awesome revamp of the VSCode Julia profiler!
Is it possible to manually tweak the colors of the bars shown next to source code? I don't know if it is related to my VSCode color theme ([this one](https://marketplace.visualstudio.com/items?itemName=cameronbieganek.julia-color-themes)), my blue light filter or my color blindness, but these bars appear very pale and I often struggle to see them correctly.

**Comment by pfitzseb** [comment]
Can you post a screenshot?

**Comment by gdalle** [comment]
![Screenshot from 2022-05-07 13-46-32](https://user-images.githubusercontent.com/22795598/167260117-c13877a7-6b48-431e-9bbe-731747736c37.png)

**Comment by gdalle** [comment]
@pfitzseb you will have a statue in my living room
