### ISSUE TITLE
Add a way of passing environment variables to Julia REPL

### ISSUE THREAD

**Issue by frankier** [julia-vscode/julia-vscode#2889]
It would be great if there was a way to pass environment variables to Julia REPL.

Use cases:

 * This workaround: https://github.com/JuliaGL/GLFW.jl/issues/198
 * `JULIA_REVISE_INCLUDE=1`

So far, I've tried doing this:
```
julia.persistentSession.shellExecutionArgument": "-c LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libstdc++.so.6 "
```

**Comment by pfitzseb** [comment]
Just use the `terminal.integrated.env.linux` setting (or the equivalent for whatever other OS).
