### ISSUE TITLE
showing a type crashes 

### ISSUE THREAD

**Issue by cscherrer** [julia-vscode/julia-vscode#2896]
This works fine in a terminal REPL:
```julia
julia> struct Binomial{N,T}
           par::NamedTuple{N,T}
       end

julia> T = Binomial{(:n, :p)}
Binomial{(:n, :p)}

julia> T.body
Binomial{(:n, :p), T}
```

But trying this in VSCode crashes the extension. The error flashes on the screen too quickly to read, but I'm left with this popup:
> The terminal process "/home/chad/.local/bin/julia '-i', '--banner=no', '--project=/home/chad/git/MeasureTheory.jl', '/home/chad/.vscode/extensions/julialang.language-julia-1.6.17/scripts/terminalserver/terminalserver.jl', '/tmp/vsc-jl-repl-384283cc-df7f-4d32-bd97-4d94547597e8', '/tmp/vsc-jl-cr-8780e9da-e1ff-461c-8ce9-d0f8cfc24b87', 'USE_REVISE=true', 'USE_PLOTPANE=true', 'USE_PROGRESS=true', 'DEBUG_MODE=false'" terminated with exit code: 1.

**Comment by pfitzseb** [comment]
Should be fixed by https://github.com/julia-vscode/julia-vscode/pull/2892.

**Comment by cscherrer** [comment]
Ah, great. Sorry for the duplicate
