### ISSUE TITLE
is there a way to disable the debugger?

### ISSUE THREAD

**Issue by aldopareja** [julia-vscode/julia-vscode#2902]
I want to use the [full command palette of Debugger.jl](https://github.com/JuliaDebug/Debugger.jl#debugger-commands), which allows for many more options than the graphical debugger in the extension.

Is there any way I can stop the extension from shadowing @enter and @run so I can use the CLI debugger from the REPL?

![image](https://user-images.githubusercontent.com/7622817/170236382-12852d70-eb46-43d3-871a-579d67e2e5c1.png)

**Comment by pfitzseb** [comment]
No. You can of course use `Debugger.@enter`, as suggested by that warning.

As far as I'm aware, the only functionality the VS Code debugger doesn't provide is support for generated functions. Is there anything else you're missing?

**Comment by pfitzseb** [comment]
Sure, just open the file and click next to the line number to add a breakpoint. There are some (slightly outdated) docs [here](https://www.julia-vscode.org/docs/dev/userguide/debugging/).

**Comment by aldopareja** [comment]
thank you!
