### ISSUE TITLE
package symbols not suggested for autocomplete in test folder (or outside of `src/`)

### ISSUE THREAD

**Issue by anandijain** [julia-vscode/julia-vscode#2904]
I mentioned this to Sebastian in slack a while ago and there was a reason this doesn't work, but I forget what it was and it keeps frustrating me. I couldn't find an open issue for this. 

But basically when developing a package and editing the tests, julia-vscode will not have the current environment packages' symbols available. 

For example, in src/Foo.jl, I have `module foo; greet(x) = ...; end`, then when I go to test/runtests.jl, the Symbol `Foo` is not suggested, nor is `greet`. 

I'm just wondering if my workflow is wrong and there is a way to get around this. 

Thanks

**Comment by lvignoli** [comment]
As a fresh Julia user, I experience the same issue.
In fact,  it seems all symbols outside Base are not recognized for suggestions nor intellisense, nor jump to definition and so on.
