### ISSUE TITLE
Regarding Revise.jl Load on Startup

### ISSUE THREAD

**Issue by Matthew-Whisenant** [julia-vscode/julia-vscode#2906]
I am a little confused on the extension option to load Revise.jl on startup. What does this effect? Are files automatically watched for changes? I looked through the documentation and could not find anything about this feature.

I believe others are interesting in learning this too. See my post from Reddit: [Regarding Revise.jl Built into VScode Extension](https://www.reddit.com/r/Julia/comments/uynf6o/regarding_revisejl_built_in_to_vscode/?utm_source=share&utm_medium=web2x&context=3)

**Comment by davidanthoff** [comment]
You need to have Revise available in your env, and if it is there, and you selected the option to load it, we will load it when we start a new REPL.

**Comment by carpetdev** [comment]
Still a bit confused by this. Is it meant to automatically be revising the file you run with "Julia: Execute active file in REPL", or do we have to still do an includet()?
