### ISSUE TITLE
Debugger gets stuck - with Timeout after 2000 ms for 'terminate'

### ISSUE THREAD

**Issue by anna-parker** [julia-vscode/julia-vscode#2908]
Hi! I'm trying to debug a Julia package I'm maintaining (see test script: `https://github.com/PierreBarrat/TreeKnit.jl/blob/master/test/splitgraph/3solutions/test.jl`)

When I run the debugger, it always gets stuck at the same function (`SplitGraph.sa_opt`), I also get the error `Timeout after 2000 ms for 'terminate'`.

The function I'm running completes without errors and really fast, in around 300 milliseconds when not using a debugger (timed using the `TickTock` package in Jupyter notebook). So I don't understand why it times out in the debugger. 

I'm using the default Julia extension for VS code, and everything is still set to default. I wanted to extend the timeout time in the debugger settings (e.g. in the launch.json file) but do not seem to be able to do so. Is there a way to do this, or could it be added as an extension?

**Comment by pfitzseb** [comment]
The debugger can very well be orders of magnitude slower than compiled Julia code, especially if the code contains many function calls. 

We don't really have a good solution to this at the moment; I'd usually recommend reducing your input data as much as possible. Another option would be to use https://github.com/JuliaDebug/Infiltrator.jl (although that's not integrated into VS Code at all).

`Timeout after 2000 ms for 'terminate'` is harmless -- it just indicates that we couldn't stop the debugger process gracefully withing 2s, which makes sense -- it's very busy running your code afterall.
