### ISSUE TITLE
Can't restart Julia REPL after moving from panel to editor

### ISSUE THREAD

**Issue by TomRottier** [julia-vscode/julia-vscode#2913]
If I drag the Julia REPL from the terminal into the editor then close it using "ctrl + d" or calling `exit()` I then cannot open the REPL again. 

You can restart it again if you close the REPL how you would close a file e.g. clicking the "x" though.

**Comment by pfitzseb** [comment]
This is blocked on https://github.com/microsoft/vscode/issues/152302 (or at least I don't see a robust solution for this atm).

**Comment by TomRottier** [comment]
Closing as this seems to be fixed now
