### ISSUE TITLE
Improve vs-code plot display quality

### ISSUE THREAD

**Issue by HiramTheHero** [julia-vscode/julia-vscode#2918]
Hello all. Thank you for the hard work on this package.

I've noticed that vs-code displays pixelated plots in comparison to plotting in an external REPL.

Is there a way to change this? It would be nice to have the "crisp" looking plots within the plot viewer.
The screenshot shows the difference in the quality between the two.

<img width="1440" alt="Screen Shot 2022-06-12 at 10 21 30 PM" src="https://user-images.githubusercontent.com/22198719/173280753-a309a20e-5ddd-47c4-9a2b-78c295e834f2.png">

Thank you all, again, for your hard work on this software.

**Comment by pfitzseb** [comment]
This will be fixed in the next release (you can try the [insiders channel](https://marketplace.visualstudio.com/items?itemName=julialang.language-julia-insider) if you want).
