### ISSUE TITLE
Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

### ISSUE THREAD

**Issue by HerClau** [julia-vscode/julia-vscode#2919]
Issue Type: <b>Bug</b>

using Plots
pyplot()
using Random

Random.seed!(1234)

#ys = Vector[rand(10), rand(20)]
#plot(ys, color=[:black :orange], line=(:dot, 4), marker=([:hex :d], 12, 0.8, Plots.stroke(3, :gray)))

function batch(n)
    x = sort(rand(-1.1:0.01:1.1, n))
    y = sin.(10x) .+ rand(n)
    return x, y
end
x, y = batch(100);
p1 = scatter(x, y, marker_z=(+), color=:blues, legend=false,
    label="data",
    markersize=3, alpha=0.3);
plot(p1)

Extension version: 1.6.17
VS Code version: Code 1.68.0 (4af164ea3a06f701fe3e89a2bcbb421d2026b68f, 2022-06-08T11:44:16.822Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700X 8-Core Processor              (16 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (6.71GB free)|
|Process Argv|--crash-reporter-id 6584f5c6-f1d4-4fc9-9d27-36e9d92bbd5d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by pfitzseb** [comment]
Unlikely to be an issue with this extension. Something broke your VS Code window, but extensions shouldn't be able to do that.

**Comment by HerClau** [comment]
What would be the procedure to follow to resolve this alert? Sent from Mail for Windows From: Sebastian PfitznerSent: Monday, 13 June 2022 11:49To: julia-vscode/julia-vscodeCc: HerClau; AuthorSubject: Re: [julia-vscode/julia-vscode] Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state.. (Issue #2919) Unlikely to be an issue with this extension. Something broke your VS Code window, but extensions shouldn't be able to do that.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
