### ISSUE TITLE
Clicking error message links to source doesn't use already open file.

### ISSUE THREAD

**Issue by Datseris** [julia-vscode/julia-vscode#2925]
MWE: I have an VSCode editor open, with 2 panels of julia source open, and one panel the REPL. As below:

![image](https://user-images.githubusercontent.com/19669089/174266111-6d604caf-0f1d-4c96-a6c1-8932f61d22df.png)

I get an error message. I click the error message, which points to one of the two open files in the editors. If the last active panel, before the REPL was the source file that also contains the line the REPL points at, everything is ok. The focus switches to said window as expected.

If however the last active panel was the other source file, that doesn't contain the line the error points at, and then I Ctrl+Click the error, a **new file will open up at the previously focused panel** opening the same file as in the other panel, even though the file already exists and is open.

I think it would make for a much cleaner experience if when Cltr+Clicking an error message there was first a check to see if there is an existing panel that already has the source file **irrespectively of what was the last panel that was focused**

**Comment by pfitzseb** [comment]
I'm pretty sure you want to enable the `workbench.editor.revealIfOpen` setting and there's nothing we actually need to change in the extension.
