### ISSUE TITLE
Disable auto formatting

### ISSUE THREAD

**Issue by tlienart** [julia-vscode/julia-vscode#2928]
Hello,

Is there a toggle to completely switch off JuliaFormatter when using Julia-vscode? (ideally not via setting a set of options manually in a TOML file as I guess is suggested implicitly [here](https://discourse.julialang.org/t/how-to-disable-automatic-formatting-options-in-vscode/75157) unless there is a way to write a global toggle in that file).

I couldn't find this in the docs, will gladly add a PR to [this part of the docs](https://domluna.github.io/JuliaFormatter.jl/stable/config/) to indicate how to switch it off globally.

thanks!

**Comment by davidanthoff** [comment]
My best guess is that there is a generic VS Code setting for this. I think the default at the moment is that the formatter is only ever run on demand in any case? I might be wrong, though...
