### ISSUE TITLE
Display plot in the same pane rather than opening a new pane? 

### ISSUE THREAD

**Issue by xiaoweiz** [julia-vscode/julia-vscode#294]
I drag the plot pane so that the plots can be displayed side by side with the codes.  
<img width="1316" alt="screen shot 2017-10-11 at 11 23 35 am" src="https://user-images.githubusercontent.com/4540215/31420872-b5122d66-ae76-11e7-8a7d-58a8fd73cd2b.png">

However, if I make another plot, then a new plot pane is opened, covering the editor pane, which makes the layout become "two plot panes side by side". 
<img width="1321" alt="screen shot 2017-10-11 at 11 29 12 am" src="https://user-images.githubusercontent.com/4540215/31420999-6fdbdaa2-ae77-11e7-9520-eb5f1333696c.png">
The two plot panes are obviously synced, both displaying the new plot. But I need to close the new plot pane in order to restore to the desired layout of "codes and plots displayed side by side". It becomes quite annoying after several iterations...

**Comment by ZacLN** [comment]
@davidanthoff any idea on this?

**Comment by davidanthoff** [comment]
I have vague memories that I tried to get this right originally, but that it wasn't trivial. I'll have another look.

**Comment by ZacLN** [comment]
As a start maybe we open plots in column 2? 
(change `undefined` to `2` in https://github.com/JuliaEditorSupport/julia-vscode/blob/master/src/repl.ts#L206)

**Comment by davidanthoff** [comment]
Yeah, that would be an option. I think I had that originally but then for some reason reverted it, but I don't remember why... But seems reasonable that there are more folks that want this in column 2.

**Comment by davidanthoff** [comment]
Alright, we now show this always in the second column. I don't think we can do more for this release, but I'll leave this open on the backlog, it would be nice to have the plot pane be a true singelton tab that just can't be opened multiple times. Probably requires something in VS Code itself, though.

**Comment by pfitzseb** [comment]
Should be fixed nowadays.

**Comment by putianyi889** [comment]
After the latest (auto)update the new plots always show in the same pane with the code...
Version: 1.63.0 (user setup)
Commit: 7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e
Date: 2021-12-07T06:26:56.179Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by pfitzseb** [comment]
Will be fixed once https://github.com/julia-vscode/julia-vscode/pull/2611 is in a release.
