### ISSUE TITLE
[UI Improvement] Why not let hover and CTRL+hover produce different content on variable ?

### ISSUE THREAD

**Issue by touchft** [julia-vscode/julia-vscode#2943]
Currently, both `hover` and `CTRL+hover` produce the definition on a variable. Why not let `CTRL+hover` or `hover` show values of the variable and make the pop-up show similar as JUNO do.

It is really convenient to explore the value when `hover` or `CTRL+hover` on a variable in Atom with JUNO !

**Comment by davidanthoff** [comment]
We are limited by the options VS Code provides
