### ISSUE TITLE
[Multithreading] NumThreads not having effect in Jupyter Notebook

### ISSUE THREAD

**Issue by kilacoda** [julia-vscode/julia-vscode#2944]
I was looking to use multithreading in my Jupyter Notebook, and found that the `julia.NumThreads` setting should allow me to do that.

However, When I set the value for this setting to something like 4, the value of `Threads.nthreads()` in the notebook still remains 1, no matter how many times I restart the kernel or reload the editor:

![image](https://user-images.githubusercontent.com/14952412/176924662-97919fad-fc37-4f49-9a41-33be62a1f6bb.png)

Moreover, when I open a new REPL with `Julia: Start REPL` it appears to start with 4 threads:

![image](https://user-images.githubusercontent.com/14952412/176925515-b6d557a3-5f3c-4e90-a497-a02b561d1d26.png)

Do the settings for the Julia extension not apply for notebooks or something? My first thought was that the REPL and IJulia kernel are managed by the Julia and Jupyter extensions, respectively, don't know if that's the case though.

**Comment by pfitzseb** [comment]
AFAICT, the integrated kernels do respect that setting. Can you check what notebook kernel you're using? It should mention the Julia extension explicitly.

**Comment by kilacoda** [comment]
Ah my bad, I was using one I made with IJulia myself, now it correctly shows 4 threads. Thanks!

![image](https://user-images.githubusercontent.com/14952412/176935635-62d29d32-f6a6-47e8-ab3d-2d18fa36d001.png)
