### ISSUE TITLE
VScode Jupyter Notebook only shows documentation and autocomplete in cells where you load packages [Bug]

### ISSUE THREAD

**Issue by Dekermanjian** [julia-vscode/julia-vscode#2945]
I only get autocomplete and function documentation when hovering over a function if it is in the same cell where I load the packages via `using package`. If I type the same function in another subsequent cell no autocomplete or documentation is available except for base functions.

**Comment by orbitoo** [comment]
I ran into this problem as well, and variables already defined cannot be detected too.

**Comment by davidanthoff** [comment]
Yeah, the whole LS story for notebooks is pretty incomplete at the moment. We know what we need to do to fix it, but it is not trivial and will take some time.

**Comment by pfitzseb** [comment]
Dup of https://github.com/julia-vscode/julia-vscode/issues/2016.
