### ISSUE TITLE
α is highlighted for some strange reason

### ISSUE THREAD

**Issue by v715** [julia-vscode/julia-vscode#2947]
The α character is always highlighted with a weird yellow box. Doesn't happen to any other of the special unicode characters.

Also not a problem with my theme, I've disabled it and the highlighting persists.

<img width="571" alt="Screen Shot 2022-07-02 at 10 59 21 AM" src="https://user-images.githubusercontent.com/29757116/177005826-f4a11b7c-d775-49a0-bb80-1b4115ca8142.png">

**Comment by pfitzseb** [comment]
Not an extension issue. Check the `editor.unicodeHighlight` settings and disable them as appropriate.
