### ISSUE TITLE
Multithread kernel on Jupyter notebook

### ISSUE THREAD

**Issue by galshkolnik** [julia-vscode/julia-vscode#2949]
Hello,
The Jupyter notebooks in VSCode combined with the SSH extension and the basic IDE provide me with a complete application for my Julia programming needs. However, I have had trouble using multithread kernels on the notebooks.
Can I expect VSCode to support multithreading on notebooks in the near future?
Thanks,
Gal

**Comment by pfitzseb** [comment]
The kernels provided by this extension already support multi-threading via the `julia.NumThreads` setting. Also see https://github.com/julia-vscode/julia-vscode/issues/2944.
