### ISSUE TITLE
debugger slows down linearly with array size

### ISSUE THREAD

**Issue by mind6** [julia-vscode/julia-vscode#2951]
Julia extension: 1.6.24
vscode: 1.68.1
Julia runtime: 1.7.3
platform: Windows

All you need is to try this minimal example:
```julia
function run(size::Int)
    @time begin 
        a = fill(999, (size,))::Vector{Int}
        a .*= 2
        # println(a[1],':',a[end])
    end
    nothing
end

run(1)
run(100)
run(10000)
run(100000)

```

In the REPL, the output is
```
 0.000001 seconds (1 allocation: 64 bytes)
  0.000001 seconds (1 allocation: 896 bytes)
  0.000012 seconds (2 allocations: 78.172 KiB)
  0.000153 seconds (2 allocations: 781.297 KiB)
```

When running it through the "Julia: Debug File in New Process" vscode command, I get this output:
```
0.173294 seconds (191.12 k allocations: 10.812 MiB, 84.41% compilation time)
  0.004221 seconds (34.42 k allocations: 1.166 MiB)
  0.512760 seconds (3.42 M allocations: 112.963 MiB, 2.13% gc time)
  4.476247 seconds (34.20 M allocations: 1.103 GiB, 2.00% gc time)
```
The debugger allocates more than 1.4 kilobytes of memory, *per element of the array*.
This means it's unusable for debugging any kind of data access. In my actual production code, it gets stuck on an array with just 2 million elements.

**Comment by pfitzseb** [comment]
That's expected.
You can probably get around that by removing all exceptions from `Base` in the `Julia: Compiled Code` pane.

**Comment by mind6** [comment]
> That's expected. You can probably get around that by removing all exceptions from `Base` in the `Julia: Compiled Code` pane.

I tried Debugger.jl it probably uses the same underlying debugger so it's the same behavior. 

I added everything under Base to "Compiled"; I think that helped my vector code not be interpreted which was causing the massive slow down. After running debugger for the first time, the interpreted modules show up under "All". I also added "Dates" in my case so I can used vectorized Dates.unix2datetime.(args).

This provides a great solution; I can now get the same performance with the debugger where breakpoints aren't necessary. The manual should probably emphasize you need to do this for large arrays. This is the section which mentions "compiled mode":

https://www.julia-vscode.org/docs/stable/userguide/debugging/#Compile-mode
