### ISSUE TITLE
Julia: starting up stays until switching to a .jl file

### ISSUE THREAD

**Issue by barche** [julia-vscode/julia-vscode#296]
On julia-vscode 0.8 beta 4, it seems that opening a Julia package with a non-Julia file (QML in this case) active keeps showing the "Julia: starting up" message until actually switching to a Julia file. Appears to work fine after that.

**Comment by davidanthoff** [comment]
I'm moving this to the v0.9.0 milestone. While a bug, it doesn't seem critical, and I think we are better off getting v0.8.0 out at this point. If anyone feels strongly otherwise, please just let me know!

**Comment by davidanthoff** [comment]
I'm moving this to the backlog. I plan to tweak the message processing in LS at some point, and I think at that point it makes sense to revisit this.
