### ISSUE TITLE
Plot pane does subsampling for large images, even when zooming in

### ISSUE THREAD

**Issue by cdsousa** [julia-vscode/julia-vscode#2962]
(Following on an issue found in https://github.com/julia-vscode/julia-vscode/pull/2570)

For large images (>1000px side) the plot pane seems to be doing some pre-filtering/sub-sampling no matter the zoom level.

Example of a 2000x2000 random image (`rand(RGB,2000,2000)`) zoom-in, plot pane at the left versus image in a tab at the right:
![142430712-866b43b4-8baa-40f2-bbe5-877623addb15](https://user-images.githubusercontent.com/333519/179730984-5c23c5fa-0932-408b-9223-692183aef99b.png)

Example of a 1080x1920 image zoom-in, plot pane at the left versus image in a tab at the right:
![142426981-dcd6b370-9d52-499d-bad5-734f4d452147](https://user-images.githubusercontent.com/333519/179731899-d8cb4c78-eb93-42ed-87e9-a56df5933e46.png)

**Comment by pfitzseb** [comment]
This is an issue with ImageShow:
https://github.com/JuliaImages/ImageShow.jl/blob/245e0e4fa66001bd4d7b6f51b65b7d46844625cb/src/showmime.jl#L31

Try
```
julia> struct Foo end

julia> function Base.show(io::IO, mime::MIME"image/png", img::Foo)
         show(io, MIME"image/png"(), rand(RGB, 2000,2000), maxpixels=1e9)
       end

julia> Foo()
```
instead to force the full resolution.

**Comment by cdsousa** [comment]
Oh, all this tima and the issue was with ImageShow...
Thanks!
