### ISSUE TITLE
Ctrl-F5 wont work for new update 1.6.28

### ISSUE THREAD

**Issue by aidevnn** [julia-vscode/julia-vscode#2965]
Hello.
Since new update, i have issues with Ctrl-F5. When i downgrade to previous version 1.6.24, everything work.
Tx

**Comment by pfitzseb** [comment]
So what's the failure mode on the new release?

**Comment by aidevnn** [comment]
@pfitzseb 
When i do F5, the debugger works, the executing task start in the Terminal until the finish.
But when i do Ctrl-F5, the Terminal wont execute any task, and a popup "Could not run editor content in new process." is prompted.

**Comment by tongzhangqu** [comment]
I have similar issue with 1.6.28. VS code is not working properly.

**Comment by mongibellili** [comment]
sudo apt-get --purge remove code
sudo dpkg -i ......(earlier version)
settings: update:mode = none
everything works as usual.
thanks
