### ISSUE TITLE
"Escape" keybinding interferes with the vim extension for .jmd and .md files

### ISSUE THREAD

**Issue by twadleigh** [julia-vscode/julia-vscode#2970]
Trying to edit a .jmd file I noticed that vscode was ignoring `ESC` when trying to return to NORMAL mode from INSERT mode.

I'm pretty sure I've tracked the issue down to missing parentheses in a couple of the entries in the "keybindings" section of `package.json`.

I'll make a simple PR that I think should work, but I don't believe I have the setup in place to test it.

I can confirm, though, that the `language-julia.clearCurrentInlineResult` command is what is being triggered every time I press `ESC`.

**Comment by twadleigh** [comment]
BTW, when editing the change log for #2971, I ran into the same issue.

**Comment by twadleigh** [comment]
Let's reopen. #2971 doesn't fix it. Apparently parentheses are not yet supported in when clauses: https://github.com/microsoft/vscode/issues/91473

I'll have to rewrite those ugly boolean expressions in some way without using them.

**Comment by pfitzseb** [comment]
I can write a generator script for that. No-one should have to do that manually :)

**Comment by twadleigh** [comment]
I'll submit a hand-generated version as a PR meanwhile (at least for my own use). The required pattern is the same for all of them and easy to generate with some copy-paste.

**Comment by pfitzseb** [comment]
We can just use `editorLangId =~ /^julia|juliamarkdown|markdown$/`. I'll have a commit for that in a sec.

**Comment by pfitzseb** [comment]
Ok, can you give that PR a go, @twadleigh?
