### ISSUE TITLE
"Julia: Run File in New Process" does not open a terminal to display output 

### ISSUE THREAD

**Issue by tcae** [julia-vscode/julia-vscode#2976]
With julia-vscode version 1.6.28 "Julia: Run File in New Process" does not open a terminal to display output anymore. It works with julia-vscode version 1.6.24. Observed under OSX on Apple Mini M1.

Version: 1.69.2
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:12:57.074Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.5.0

**Comment by pfitzseb** [comment]
Should be fixed by https://github.com/julia-vscode/julia-vscode/pull/2966.

**Comment by mauerdev** [comment]
I have this issue also running same version. I also downloaded the latest, but it seems to not work with Insiders either.

**Comment by pfitzseb** [comment]
That PR isn't released on insiders yet.

**Comment by tcae** [comment]
Is now fixed with v1.6.30 - thanks!
