### ISSUE TITLE
Add an option to only scan and lint for open files?

### ISSUE THREAD

**Issue by colinfang** [julia-vscode/julia-vscode#2983]
Coud we add an option to only scan & lint for open files (and the `include(...)` from those open files) instead of scanning all `.jl` in the workspace.

It would save a lot of memory & process time for big repository.

**Comment by pfitzseb** [comment]
Not really. Linting (and more generally, statically analyzing) your code only makes sense with context.

What we could do is to only take files into consideration that are reachable from the current one, but in many cases that's still going to be everything (e.g. for every package ever).
