### ISSUE TITLE
Julia intercepting vsCodeVim keypresses while editing Markdown

### ISSUE THREAD

**Issue by bc0n** [julia-vscode/julia-vscode#2988]
Julia-vscode appears to be intercepting my vsCodeVim keypresses in Markdown documents.  When I open the markdown document I have the normal mode cursor, but on inserting a character I'm unable to Escape Insert mode to return to Normal.  Throughout this, vim editing continues to work in other files (julia, toml). 

I sometimes receive the error message "vscode command 'language-julia.clearCurrentInlineResult' not found markdown".

These extension logs may be relevant?
```
[2022-08-03 10:53:15.123] [exthost] [warning] TextEditor is closed/disposed
[2022-08-03 10:53:15.124] [exthost] [warning] TextEditor is closed/disposed
[2022-08-03 10:53:15.145] [exthost] [warning] ExtHostTextEditorOptions 'setCursorStyle' failed:'
[2022-08-03 10:53:15.145] [exthost] [warning] {"name":"DISPOSED","message":"TextEditor(vs.editor.ICodeEditor:1,$model16) has been disposed"}
```

Disabling the julia-vscode extension and restarting vscode allows regular vim editing of the markdown file.  If I then re-enable julia-vscode and run a script, I again lose the ability to escape insert mode.  This persists even if the julia session in the terminal is exit()ed.

This just started happening last week, 2022/07/25.

vsCode 1.69.2
julia extension v1.6.28
julia v1.7.2
vsCodeVim v1.23.1
on LinuxMint 20.3 Cinammon, kernel 5.4.0-122-generic

Thanks

**Comment by pfitzseb** [comment]
https://github.com/julia-vscode/julia-vscode/issues/2970

**Comment by bc0n** [comment]
@pfitzseb Seem like the same, sorry for the dup.
