### ISSUE TITLE
Terminal crash when examining types imported from packages

### ISSUE THREAD

**Issue by sjbreiner** [julia-vscode/julia-vscode#2996]
Issue Type: <b>Bug</b>

Environment: Ubuntu 20.04

When `using` an outside package, looking at a `UnionAll` type and its `body` attribute causes the language server to crash. Error message and transcript from MWE below. I've used the `Distributions` package as an example, but first ran into it using the `Catlab` package.

---

**Error message**

`The terminal process "/home/xxxx/.local/bin/julia '-i', '--banner=no', '--project=/home/xxxx/.julia/environments/v1.6', '/home/xxxx/.vscode/extensions/julialang.language-julia-1.6.24/scripts/terminalserver/terminalserver.jl', '/tmp/vsc-jl-repl-087b86c9-522b-4c8f-a142-071fc486b0df', '/tmp/vsc-jl-cr-14bc88b7-2b87-41af-a07d-b117d63fecf7', 'USE_REVISE=true', 'USE_PLOTPANE=true', 'USE_PROGRESS=true', 'DEBUG_MODE=false'" terminated with exit code: 1.`

---
**Transcript**

```julia
$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.2 (2021-07-14)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> pushfirst!(LOAD_PATH, raw"/home/spencer/.vscode/extensions/julialang.language-julia-1.6.24/scripts/packages");using VSCodeServer;popfirst!(LOAD_PATH);VSCodeServer.serve(raw"/tmp/vsc-jl-repl-93f2bfc8-3463-4c12-a4ba-a918a0219245"; is_dev = "DEBUG_MODE=true" in Base.ARGS, crashreporting_pipename = raw"/tmp/vsc-jl-cr-14bc88b7-2b87-41af-a07d-b117d63fecf7");nothing # re-establishing connection with VSCode

julia> using Distributions

julia> Normal.body
Normal{T<:Real}

julia> Normal
Normal

julia> ┌ Error: Some Julia code in the VS Code extension crashed
└ @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-1.6.24/scripts/error_handler.jl:15
ERROR: TypeError: in new, expected DataType, got Type{Normal}
Stacktrace:
  [1] Base.Fix2(f::typeof(isequal), x::Type{Normal{T<:Real}})
    @ Base ./operators.jl:998
  [2] isequal(x::Type)
    @ Base ./operators.jl:1013
  [3] getvariables()
    @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-1.6.24/scripts/packages/VSCodeServer/src/trees.jl:281
  [4] #invokelatest#2
    @ ./essentials.jl:708 [inlined]
  [5] invokelatest
    @ ./essentials.jl:706 [inlined]
  [6] repl_getvariables_request(conn::VSCodeServer.JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, params::Nothing)
    @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-1.6.24/scripts/packages/VSCodeServer/src/trees.jl:269
  [7] dispatch_msg(x::VSCodeServer.JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, dispatcher::VSCodeServer.JSONRPC.MsgDispatcher, msg::Dict{String, Any})
    @ VSCodeServer.JSONRPC ~/.vscode/extensions/julialang.language-julia-1.6.24/scripts/packages/JSONRPC/src/typed.jl:67
  [8] dispatch_msg(conn_endpoint::Base.RefValue{Union{Nothing, VSCodeServer.JSONRPC.JSONRPCEndpoint}}, msg_dispatcher::VSCodeServer.JSONRPC.MsgDispatcher, msg::Dict{String, Any}, is_dev::Bool)
    @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-1.6.24/scripts/packages/VSCodeServer/src/VSCodeServer.jl:100
  [9] macro expansion
    @ ~/.vscode/extensions/julialang.language-julia-1.6.24/scripts/packages/VSCodeServer/src/VSCodeServer.jl:148 [inlined]
 [10] macro expansion
    @ ./task.jl:387 [inlined]
 [11] macro expansion
    @ ~/.vscode/extensions/julialang.language-julia-1.6.24/scripts/packages/VSCodeServer/src/VSCodeServer.jl:142 [inlined]
 [12] (::VSCodeServer.var"#176#180"{Bool, String, Base.PipeEndpoint})()
    @ VSCodeServer ./task.jl:411
$
```
======================================================

Extension version: 1.6.24
VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:29.527Z)
OS version: Linux x64 5.4.0-124-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 3089)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.38GB (6.62GB free)|
|Process Argv|--unity-launch --crash-reporter-id 54aab0ed-ab22-4140-be20-540c12954568|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912cf:30529770
vsclangdc:30486549
c4g48928:30535728
d7fjc500:30543455
dsvsc012:30540252

```

</details>

**Comment by pfitzseb** [comment]
Please update to a more recent version of VS Code and the Julia extension, where this bug is fixed.
