### ISSUE TITLE
"Julia: New Julia File [⌥J ⌥N]" always shown in context menu

### ISSUE THREAD

**Issue by cbrnr** [julia-vscode/julia-vscode#2997]
Right-clicking in the Explorer side bar pops up a context menu, which always contains "Julia: New Julia File [⌥J ⌥N]". I have many non-Julia projects where I'd prefer to not see this entry (the context menu is crowded enough as it is), so is there a way to disable this? Alternatively, this could maybe also considered to be a bug since this entry could/should be shown only for projects that include Julia files (not sure if this is possible)?

**Comment by pfitzseb** [comment]
Thanks for the report. Should be fixed by https://github.com/julia-vscode/julia-vscode/pull/2998.

**Comment by cbrnr** [comment]
This is awesome! Thank you so much for this great extension!
