### ISSUE TITLE
CHANGELOG still shows [UNRELEASED]

### ISSUE THREAD

**Issue by cbrnr** [julia-vscode/julia-vscode#2999]
I think this should be v1.6.30 instead.

**Comment by RoyiAvital** [comment]
Guys, any chance to keep the changelog updated?
For users who gets their extension updated yet doesn't know what's going on.

**Comment by jmigual** [comment]
Why is this still an issue?

**Comment by pfitzseb** [comment]
Because no one updated the changelog :)

**Comment by RoyiAvital** [comment]
I see the current pre release is `1.45`, the last official version, form 6 months ago, is `1.38`.
At some point, hopefully, a new release will be materialized.
But for now, no way for the regular user to understand what has been going on in the last 6 months. What should one expect from the new version.
