### ISSUE TITLE
Crash and strange behaviour

### ISSUE THREAD

**Issue by Rratic** [julia-vscode/julia-vscode#3004]
This is *redirected* from [this issue](https://github.com/microsoft/vscode/issues/157731). I'm not exactly sure it's the extension's fault, but it has to be noted. Read the original issue for more information.

**Comment by pfitzseb** [comment]
This might be fixed by https://github.com/julia-vscode/LanguageServer.jl/pull/1137.

**Comment by davidanthoff** [comment]
If this is still an issue, please reopen.
