### ISSUE TITLE
Always copy code button does not work

### ISSUE THREAD

**Issue by LilithHafner** [julia-vscode/julia-vscode#3009]
When I click the "always copy code" button to connect to externel repl, it copies the code, but the next time I connect it presents the same popup and does not automatically copy the code. It used to work for me, but not anymore. Let me know if there are any particular details you would like to help reproduce this. I'm on Julia-VSCode v1.6.31 and my default Julia version is 1.8.0-rc3.

c.f. #2756, #2759; c.c. @pfitzseb

**Comment by pfitzseb** [comment]
Check the `julia.persistentSession.alwaysCopy` setting. Note that it might have different values for your workspace, machine, or globally (pretty sure your issue happens because we're sometimes querying from a different context than the one used when setting the value).

**Comment by LilithHafner** [comment]
`julia.persistentSession.alwaysCopy` does not appear in my user settings located at `/User/x/Library/Application Support/Code/User/settings.json`.

The box is unchecked in the user interface that comes up when I press command+, and search for `julia.persistentSession.alwaysCopy`.

I have 
```
	// Always copy the command for connecting to an external REPL to the clipboard.
	"julia.persistentSession.alwaysCopy": false,
```
in my defaultSettings.json

I'm not sure if I have other settings or where they are.

**Comment by LilithHafner** [comment]
Checking the box in the UI settings enables automatic copying for me and adds `"julia.persistentSession.alwaysCopy": true` to my user settings, which persists after VSCode restart.

**Comment by LilithHafner** [comment]
I'm still seeing this issue. I do not think #3011 fixed it.

**Comment by LilithHafner** [comment]
I've got this in my defaultSettings.json
```
	// Always copy the command for connecting to an external REPL to the clipboard.
	"julia.persistentSession.alwaysCopy": false,
```
It does not occur in User settings.
I do not think I have workspace or remote settings, but happy to check a specific path where they may be stored.
