### ISSUE TITLE
Debugger freezes in VSCode

### ISSUE THREAD

**Issue by Amuri44** [julia-vscode/julia-vscode#3016]
When I click on the debug, it takes long time to start and many times it freezes. It is similar to the problem here:
https://github.com/microsoft/debugpy/issues/108
Any way to solve it please?

**Comment by jake00100** [comment]
Same problem here, is there anything you have to do to install the debugger properly?

**Comment by davidanthoff** [comment]
The debugger is just very slow, it is essentially an interpreter, so if at the beginning of your Julia code there is any tight loop, it will take very long to run that. There is nothing we can do on the extension side of things, we just need a better Julia debugger...
