### ISSUE TITLE
crashed with a message that leads me here

### ISSUE THREAD

**Issue by thudjx** [julia-vscode/julia-vscode#3018]
My julia lsp crashed with a message:
![屏幕截图 2022-08-19 155801](https://user-images.githubusercontent.com/32637321/185576251-35e8f9c6-d096-4c6d-a851-870591744c15.png)

I don't how how can I help you guys. 
My system info:
```bash
NAME="openSUSE Leap"
VERSION="15.3"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.3"
PRETTY_NAME="openSUSE Leap 15.3"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.3"
```
and the lsp_log is linked [here](https://drive.google.com/file/d/1iVqSO33eGllvgK4ONbUth7-QhbQhlYkE/view?usp=sharing).
If any further infomation is required, don't hesitate to ask me. I am glad to answer any quesion you ask.

**Comment by kunzaatko** [comment]
[duplicate] The issue that is relevant is #2526. I had the same problem... In my case, I was trimming trailing white-space before saving and it made the inner LSP buffer and the actual buffer to go out of sync. Maybe you have something similar going on with some kind of formatting on save?

**Comment by kunzaatko** [comment]
I would check `BufWritePre` autocommands.

**Comment by thudjx** [comment]
Well, I don't remember what I had done to trigger this bug. So I don't know how to replicate it either. As this is the first time I encounter it in the long time I have been using julia lsp, it doesn't bother me so much actually.
Closing this issue.
