### ISSUE TITLE
Feature Request: Lock Module

### ISSUE THREAD

**Issue by nathanrboyer** [julia-vscode/julia-vscode#3024]
VSCode often gets confused about which module I want to run code in and thus errors when it shouldn't. Please add the ability to lock in a module so that all code is run in that module. Also open to any other ideas to fix this `Main` vs `MyPackage` module switching problem:
```julia
julia> using MyPackage

(MyPackage) pkg> status
     Project MyPackage v0.1.0
      Status `C:\Users\nboyer.AIP\.julia\dev\MyPackage\Project.toml`
  [37e2e46d] LinearAlgebra

julia> using DataFrames

(MyPackage) pkg> status
     Project MyPackage v0.1.0
      Status `C:\Users\nboyer.AIP\.julia\dev\MyPackage\Project.toml`
  [37e2e46d] LinearAlgebra

julia> df = DataFrame(x=[3,4]) # Typed
2×1 DataFrame
 Row │ x     
     │ Int64
─────┼───────
   1 │     3
   2 │     4

julia> df = DataFrame(x=[3,4]) # Ctrl + Enter
ERROR: UndefVarError: DataFrame not defined
```
More information [here](https://discourse.julialang.org/t/how-to-use-vscode-and-repl-to-write-and-test-a-package/78818/6?u=nathan_boyer).

**Comment by pfitzseb** [comment]
You can set the module for inline evaluation on a per-file basis with the module selector in the lower right corner.

**Comment by nathanrboyer** [comment]
Okay, thanks. But if I am in MyPackage environment, then I would want all REPL evaluation to use the MyPackage module regardless of what file it is sent from or if I type REPL code directly. I don't see the point of using the Main module at all in this environment.

**Comment by nathanrboyer** [comment]
A solution is provided by #3367. Once the VSCode module and REPL module are set to the same module, you can code interchangeably by both typing directly into the REPL or by running the VSCode command `Julia: Execute Code in REPL` .

Set the VSCode module from the GUI element in the bottom right corner.
![image](https://github.com/julia-vscode/julia-vscode/assets/65452054/a705c84a-42bf-4c3a-855c-dfb5e1337461)

Set the REPL module by typing a module name into the REPL and then pressing Alt+m.
https://github.com/JuliaLang/julia/pull/33872
![image](https://github.com/julia-vscode/julia-vscode/assets/65452054/e21e7593-d739-44a5-a905-4c3af983c7e2)
