### ISSUE TITLE
extension ignores Julia environment setting when running REPL

### ISSUE THREAD

**Issue by lewisl** [julia-vscode/julia-vscode#3036]
1. Run VS Code
2. open any Julia file
3. Change the environment using the Select Julia Environment control on the status bar at the bottom of the window. Say, change from Julia env v1.7 to Julia env v1.8
4. From the command palette, choose Julia: start repl.

This will start Julia 1.7 because the extension finds that executable first or it is the one in the PATH (latter is more likely).

I can change the path to the Julia executable and doubtless I'll get the whatever executable is on that path.

The extension seems to be able to find any Julia version reachable by the path, regardless of search order. So I can choose the version of Julia from the selector.

The problem appears to be that the version choice is simply ignored for many of the extension's functions.

**Comment by pfitzseb** [comment]
The environment is not tied to the Julia version, even if its name may correspond to the Julia version. Imho it'd be confusing for the environment selector to also change the actual Julia binary being used.

**Comment by davidanthoff** [comment]
We could probably start to integrate more closely with Juliaup now. In particular, we could have UI that shows all installed channels and lets users easily pick one.

**Comment by lewisl** [comment]
So, this is not solving my problem. In order to use many features like the profiler and debugger, it would appear that I need to run my Julia code in the REPL provided by the extension.

What I need is to get that REPL to run the right version of Julia. My original question was how can I do this? Even if the extension doesn't "sync up" right now (you'll get to it at some point) is there a way to choose manually?

**Comment by lewisl** [comment]
Actually, I found a workaround that is satisfactory for the moment. I start an external Julia environment with "my very favorite version of Julia."  Then, link it per the instructions.

Works like a champ (for now).  Couple of quick extra steps.
