### ISSUE TITLE
multi-threaded tests?

### ISSUE THREAD

**Issue by lmiq** [julia-vscode/julia-vscode#3045]
It seems that the julia launched by the runner is single-threaded. Is there a way to make it multi-threaded by default (or as an option)? 

(the current state of `] test` is to run multi-threaded since the julia repl launched by VSCode by default is multi-threaded. 

There are tests that require specifically multi-threading.

**Comment by davidanthoff** [comment]
I'm moving this to the extension repo as this is only an issue for the runner inside VS Code, the standalone runner should already pick up any multi-threading settings (it never launches a new process in any case).

**Comment by lmiq** [comment]
I think there is some overlap here with the other issue, as I had always `julia` set as the executable for launching Julia, but the REPL opened by "Juila: start REPL" was multi-threaded. So there is some disconnection between the two configurations, as I would expect that multithreading would be set with `julia -t auto` in the extension settings. 

If the executable path is left blank it becomes a black box to the user what exactly is the command used for launching julia. Maybe instead of `executable` path we should define the `flags`. Just a guess...

**Comment by davidanthoff** [comment]
I think we essentially need a way to configure a) the number of threads for the test processes, b) a way to specify additional args an c) maybe also a way to specify additional env vars for the test process.

a) and b) we already have as config settings for the REPL. One question then is whether we re-use those config settings for the test process, or whether we introduce new, test specific settings for those.

I think the best option would probably be that by default the test process just uses the settings we already have for the REPL, with an option to configure different settings for the test situation.

**Comment by lmiq** [comment]
I generally expect that what I test in the REPL can be converted as simpky as possible into a unit test, so I'm for having the same configuration, at least by default, in both.
