### ISSUE TITLE
more verbose output

### ISSUE THREAD

**Issue by lmiq** [julia-vscode/julia-vscode#3054]
Please let me know if you prefer this king of comment here or on Discourse.

I have some tests that should not take long (4 seconds). However, when I ran them for the first time, it took quite a while to get the response (would say 3 minutes). 

The issue is that there is no feedback on what is going on, which sort of triggers one to kill the tests:

![image](https://user-images.githubusercontent.com/31046348/187225325-bc233ebc-231f-42c6-afb5-45c2dc40f85e.png)

The test finally ended without errors:

![image](https://user-images.githubusercontent.com/31046348/187225613-d0abe1dc-726c-477f-8286-2fc80d0f31ca.png)

It seemed to report two runs of the tests, one taking 3 minutes, the other 4 seconds. 

Subsequent runs of the same test take 3-4 seconds.

The issue here is not knowing what is going on. If there was more data being output to the log we would feels assured that nothing is broken.

**Comment by davidanthoff** [comment]
Hm, this is a bit tricky, I don't really know what we could show? I think generally the various output windows now should show a little bit more details of what is going on, but of course those are not shown by default... But maybe that is good enough?

**Comment by lmiq** [comment]
The new output is good, previously I had the feeling of "nothing is happening" (it wasn't, but even now on the first run of a test it is nice to have an idea of what is going on).

At the same time, I miss the stack trace of the errors. They appear on top of the file, but rarely at the right point, and they are not control - clickable. Maybe I'll get used, but now I find harder to go to the error line than with standard errors.

**Comment by lmiq** [comment]
I was experimenting with the interface now again. The current output is fine, for me. 

The only thing I miss is that the stack traces generated (at the output window or at the red bar that points to the line of the error) are not control-clickable and lack some of the formatting of the standard stack traces*, which makes navigation on the error harder in some cases.

*stack trace one gets at the REPL when running `(Package) pkg> test`. 

But this is a different issue. I don't know if you can do anything about it. 

I'm closing this for now. Thanks for the outstanding support.
