### ISSUE TITLE
Julia REPL tries to execute to source python interpreter if one is configured

### ISSUE THREAD

**Issue by MateusRodolfo** [julia-vscode/julia-vscode#3064]
Happens if a python interpreter is selected in the VS Code environment .When initializing the REPL, julia tries to run the source command to activate the environment's python interpreter.

This raises an error and makes it longer to have the Julia REPL available and ready for input.

Here is the REPL after running the "Start REPL" command in VS Code:

```julia-repl
source /home/mrodolfo/venvs/venv_python_3_10_tpe/bin/activate
julia> source /home/mrodolfo/venvs/venv_python_3_10_tpe/bin/activate
ERROR: UndefVarError: source not defined
Stacktrace:
 [1] top-level scope
   @ REPL[1]:1

julia> 
```

**Comment by pfitzseb** [comment]
Not an issue with this extension. 

Disable `python.terminal.activateEnvironment` as per https://code.visualstudio.com/docs/python/environments#_work-with-python-interpreters and complain over at https://github.com/microsoft/vscode-python about injecting code into arbitrary non-shell terminals.
