### ISSUE TITLE
VSCodeServer.@run causes 2600x slowdown in CSV.write

### ISSUE THREAD

**Issue by adamlichtl** [julia-vscode/julia-vscode#3066]
**Setup:**
- Julia 1.8.1
  - No startup.jl
  - Installed packages: CSV, DataFrames, Dates
- MacBook Pro (Intel)
  - 2.5 GHz Intel Core i7
  - macOS High Sierra 

**Issue:**
The ability to interactively debug Julia code in VS Code using the `@run` macro is awesome. However, when writing a (20 column x 10k row) data frame to CSV, the slowdown is extreme. In the VS Code integrated REPL, running the test code below completes in ~44 ms. But when running in the same REPL using `@run`, it takes almost 2 minutes (2600x slower).

To help isolate the issue, I also replaced `CSV.write("test.csv", df)` with `mapcols(sum, df)` in the sample program below, and that gives a timing of `5 ms` when running with `@run`.  So this doesn't look like a DataFrames issue, but rather some kind of critical slowdown when @run encounters a CSV.write.

This makes debugging impractical with even moderately-sized data frames. Is there a way to fix this, or alternatively to annotate the CSV.write commands to be left untransformed by the @run macro?

**Test code:**
```
using CSV
using DataFrames
using Dates

function main()
    df = DataFrame(randn(10_000, 20), :auto)

    print("Starting..")
    timer_start = now()

    CSV.write("test.csv", df)
    
    elapsed = now() - timer_start
    println(". done. Elapsed: $(elapsed.value) ms.")
end
```

**Output in VS Code integrated Julia REPL:**
```
julia> include("test.jl"); main();
Starting... done. Elapsed: 44 ms.

julia> include("test.jl"); @run main();
Starting... done. Elapsed: 114821 ms.
```

**Comment by pfitzseb** [comment]
That's basically expected. Simply adding `CSV.write` (or all of CSV with `CSV.`) to the list of compiled functions:
![image](https://user-images.githubusercontent.com/6735977/189865229-07a3de59-273c-46db-92d6-6a0dcbd0a12c.png)

Alternatively, add the special `ALL_MODULES_EXCEPT_MAIN` token (which does exactly what it says on the tin).
