### ISSUE TITLE
A visual glitch in characters at REPL

### ISSUE THREAD

**Issue by suurj** [julia-vscode/julia-vscode#3075]
There has been a visual glitch for months now at Julia for VSCode's REPL session. Namely, some of the characters are either broken or even invisible. Now I am running on Julia 1.8.1 and the latest VSCode and its Julia extension, 1.71.2 and 1.7.12, but the issue plagued older versions as well.
In the attachment, the bug can be seen in letter _j_ in the beginning of REPL command line (_julia>_), and in the character _>_ (at _pkg>_). If the characters are selected by painting them with cursor, then the characters are shown correctly under the selection, but after removing the selection they appear as broken again. 
Occasionally, even the decimal separator is invisible, while nearly always some of the characters are broken like those in the attached screenshot. 

I use a fully up-to-date Xubuntu 22.04 as my operating system. The issue appears right after executing code or commands at REPL in restarted VSCode. The glitch seems not to show up at normal Julia REPL sessions strated from a command line instead of VSCode.

![Glitch](https://user-images.githubusercontent.com/40865346/190847990-b07a9415-9189-469a-93d3-b21a73ce2baf.png)

**Comment by davidanthoff** [comment]
Could you open a bug for this over at https://github.com/microsoft/vscode? We have no control over terminal rendering at all in the extension, that is all handled at the VS Code level, i.e. short version is that this is an upstream bug.
