### ISSUE TITLE
VSCodeServer (not found in project, manifest or registry)

### ISSUE THREAD

**Issue by StefanPofahl** [julia-vscode/julia-vscode#3076]
Following fails on my machine:
`import Pkg; Pkg.add("VSCodeServer")`

Version Info is:
```
Julia Version 1.6.7
Commit 3b76b25b64 (2022-07-19 15:11 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, haswell)
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 
```

Error message is:
```
ERROR: The following package names could not be resolved:
 * VSCodeServer (not found in project, manifest or registry)

Stacktrace:
  [1] pkgerror(msg::String)
    @ Pkg.Types /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:55
  [2] ensure_resolved(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; registry::Bool)
    @ Pkg.Types /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Types.jl:883
  [3] add(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; preserve::Pkg.Types.PreserveLevel, platform::Base.BinaryPlatforms.Platform, kwargs::Base.Iterators.Pairs{Symbol, Base.TTY, Tuple{Symbol}, NamedTuple{(:io,), Tuple{Base.TTY}}})
    @ Pkg.API /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:193
  [4] add(pkgs::Vector{Pkg.Types.PackageSpec}; io::Base.TTY, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:80
  [5] add(pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.API /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:78
  [6] #add#23
    @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:76 [inlined]
  [7] add
    @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:76 [inlined]
  [8] #add#22
    @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:75 [inlined]
  [9] add(pkg::String)
    @ Pkg.API /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:75
 [10] top-level scope
    @ REPL[6]:1
```

Any ideas how to solve this?

**Comment by davidanthoff** [comment]
That is by design, the `VSCodeServer` package is not registered in the Julia registry because we ship it as part of the extension itself.

**Comment by StefanPofahl** [comment]
Thanks for the fast response! :-)
The issue was, the script:
`/home/stefan/.vscode/extensions/julialang.language-julia-1.7.5/scripts/terminalserver/terminalserver.jl`
This script was not operational.
To enable the use the module `VSCodeServer` I gave the following command in Pkg mode:
`dev /home/stefan/.vscode/extensions/julialang.language-julia-1.7.12/scripts/packages/VSCodeServer`
I hope that this was not wrong.

**Comment by davidanthoff** [comment]
Hm, maybe you can explain a bit what you are trying to do? For example, the `terminalserver.jl` script is really a very internal implementation detail, and I would not expect you to have to ever deal with that directly, let alone run it.

There is definitely no need ever to do something like `dev` on the `VSCodeServer`.

**Comment by StefanPofahl** [comment]
Thanks David!
All started with this error message:
```
SystemError: opening file "/home/stefan/.vscode/extensions/julialang.language-julia-1.7.5/scripts/terminalserver/terminalserver.jl": No such file or directory
```
Then I began to search for this script and had tried to start it manually ...

**Comment by davidanthoff** [comment]
Hm, version 1.7.5 of the extension was never pushed to any marketplace. I think there is something wrong with how you installed the extension. Make sure you have the latest version of VS Code installed, and then just get it from the marketplace from within VS Code itself.

**Comment by StefanPofahl** [comment]
Again thanks David! - To be sure, I will re-install the Julia-Extention
