### ISSUE TITLE
support formatting julia code fence blocks in `qmd` files

### ISSUE THREAD

**Issue by haberdashPI** [julia-vscode/julia-vscode#3082]
There is support for this in JuliaFormatter (https://github.com/domluna/JuliaFormatter.jl/pull/570), so I think it would be easy to add. I haven't looked much into how formatting in VSCode works, so i'm a little uncertain how to implement. I have made quite a few small extensions for myself so am comfortable making a change if someone could give me a few quick pointers as to what files to change I'd be happy to tackle this.

**Comment by davidanthoff** [comment]
What are qmd files?

**Comment by haberdashPI** [comment]
They are a file format used by [Quarto](https://quarto.org/). They are a way of representing a notebook with a text file. Under the hood it uses Juypter and pandoc to generate html, ipython, pdf etc...

They key point is that it is a regular markdown file in syntax. The fenced code blocks can be written in R, julia or python. Quarto's extension already supports syntax highlighting, code completion, etc... but auto formatting does not yet work. It seems like it would be easy to adjust the the setup for formatting in `.jl` files to also apply to `.qmd` files since the underlying formatter (JuliaFormatter.jl) already can be applied to `.qmd` files.

**Comment by davidanthoff** [comment]
Ah, ok. I think this means that the Quarto extension should somehow implement this. We would have to extend our Julia language server to also handle quarto files, because file formatting happens in the language server, and I feel that is out-of-scope for the standard Julia LS.
