### ISSUE TITLE
Syntax highlight - textmate scopes

### ISSUE THREAD

**Issue by ravirathore** [julia-vscode/julia-vscode#3100]
Hi,

I want to add few new textmate scopes. Please let know if there's any documentation on how to recompile (, and reinstall) the extension after updating the 'syntaxes/julia_vscode.json' file. 

thanks and regards,

**Comment by davidanthoff** [comment]
Take a look at the [VS Code API](https://code.visualstudio.com/api) documentation, it explains those kinds of workflow questions quite thoroughly.

**Comment by pfitzseb** [comment]
Also note that the source of truth for the Julia grammar is at https://github.com/JuliaEditorSupport/atom-language-julia.

**Comment by ravirathore** [comment]
Thanks
