### ISSUE TITLE
Support for `Plots.plot(..., show=:inline) `

### ISSUE THREAD

**Issue by schlichtanders** [julia-vscode/julia-vscode#3109]
Hi there, I am regularly using `Plots.plot(x, y, show=:inline)` to update my plots automatically in a loop.

When doing this in vscode I get the error message, that this is only supported for `IJulia`.

![image](https://user-images.githubusercontent.com/4255480/194810088-df92fb92-cc72-482e-9ba9-1bae3c82dceb.png)

code:
```
julia> import Plots

julia> Plots.plot(1:10, 1:10, show = :inline)
inline() is IJulia-only

Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] inline(plt::Plots.Plot{Plots.GRBackend})
   @ Plots ~/.julia/packages/Plots/AAjgN/src/output.jl:157
 [3] _do_plot_show(plt::Plots.Plot{Plots.GRBackend}, showval::Symbol)
   @ Plots ~/.julia/packages/Plots/AAjgN/src/output.jl:170
 [4] _plot!(plt::Plots.Plot, plotattributes::Any, args::Any)
   @ Plots ~/.julia/packages/Plots/AAjgN/src/plot.jl:234
 [5] plot(::Any, ::Vararg{Any}; kw::Base.Pairs{Symbol, V, Tuple{Vararg{Symbol, N}}, NamedTuple{names, T}} where {V, N, names, T<:Tuple{Vararg{Any, N}}})
   @ Plots ~/.julia/packages/Plots/AAjgN/src/plot.jl:107
 [6] top-level scope
   @ ~/Projects/fall-in-love-with-julia/tmp/tmp.ipynb:1
```

using
- Julia 1.8.1
- vscode julia v1.37.2
- vscode 1.69.2

**Comment by davidanthoff** [comment]
That seems like an error message from Plots, I don't think there is anything we can do about this if they decide to special case things when run under IJulia...
