### ISSUE TITLE
Use diff UI feature for failed tests 

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/julia-vscode#3121]

**Comment by brychcy** [comment]
Hi!

We have tests where we compare the result of a complex algorithm that is written to a file and which has multiple lines with the expected value.

To figure out what went wrong in case of a failure is really hard by looking at the error message.
Being able to use the visual diff-tool is extremely helpful.

I've provided simple a pull request that gets the required information by parsing the data field of the Test.Fail instance, which is set by the @test macro when a failure occurs when comparing two strings like
```
@testitem "example" begin
  expected = """
         lots of lines
         some data
         more lines
         """

  result = """
         lots of lines
         changed data
         more lines
         """

  @test expected == result
end
```

I've tested it with other @test usages that don't compare strings or have a different form and made sure that this never can crash if anything is not as expected.
