### ISSUE TITLE
add 'raw' in their list of languages for the notebook cell type

### ISSUE THREAD

**Issue by oameye** [julia-vscode/julia-vscode#3131]
In [this issue](https://github.com/microsoft/vscode-jupyter/issues/1611) of the vscode-jupyter extention it asked to add a feature where one can mark a notebook cell as raw. The [last comment of the issue](https://github.com/microsoft/vscode-jupyter/issues/1611#issuecomment-1205644021) states that it is implemented but it is up to the vscode-julia extention to enable the feature. Could this be enabled please?

At the moment, the work around is to edit the specific cell type in the Json file behind the Ipynb file. However, it would be easier if this could be done via the vscode interface (GUI).
![image](https://user-images.githubusercontent.com/57623933/197172814-736e70e3-9faf-47b6-88ab-0cfc7c585f00.png)

Here I quote the last comment of [the relevant issue](https://github.com/microsoft/vscode-jupyter/issues/1611):
> It's a function of the [supportedLanguages](https://github.com/microsoft/vscode/blob/ede1cd6a388a52e08d2dd64c73e590f96436c480/src/vscode-dts/vscode.d.ts#L13543) that a kernel says it supports.
> 
> We give back 'raw' here:
> 
> https://github.com/microsoft/vscode-jupyter/blob/2adefe9614c3e95234573ddfdbff4689b09e5859/src/notebooks/controllers/vscodeNotebookController.ts#L187
> 
> Here's our list:
> 
> https://github.com/microsoft/vscode-jupyter/blob/2adefe9614c3e95234573ddfdbff4689b09e5859/src/platform/common/constants.ts#L132
> 
> So the Julia extension has to support 'raw' in their list of languages for the Julia kernel.

**Comment by oameye** [comment]
I would be happy to do it, but I have no idea where to start... If maybe someone can give me some guidance?

**Comment by yuyuan-lin** [comment]
Still waiting for this to be resolved... Quarto needs the raw cell for the notebook to be correctly rendered.
