### ISSUE TITLE
Better support for nightly Julia versions

### ISSUE THREAD

**Issue by pepijndevos** [julia-vscode/julia-vscode#3160]
As discussed in #3146 current master does not work with this extension.

To quote @pfitzseb out of context:
> we could potentially run against nightly with Pkg support

Currently the `fallback` environment is built with `+stable` while it might be more beneficial to build it with `+nightly` once that lands in https://github.com/JuliaLang/juliaup/pull/384

The other part of the problem is that on 1.9 there are packages that were removed from the standard library but not yet vendored. So in  such cases the `fallback` environment would still fail, unless it could support Pkg that are not vendored.

To approach the problem from the other side: it could be useful to add an extra option to set the executable path for the language server separately from the normal Julia path, so the language server could be set to run with a stable Julia release, and code can be ran with nightly Julia.

After much silly problems, this workaround seems to do the trick:
```
#!/usr/bin/env bash
set -e
if [ -z "$JULIA_LANGUAGESERVER" ]; then
	exec julia +dev "$@"
else
	exec julia +release "$@"
fi
```

**Comment by davidanthoff** [comment]
Ah, I wasn't aware that we would _also_ have to vendor more stuff. Ughh.... Do we have a list of former stdlib packages that now need to be vendored for 1.9?

**Comment by davidanthoff** [comment]
Is it just DelimitedFiles, actually?

**Comment by davidanthoff** [comment]
I've added 1.9 envs now, and I'm vendoring DelimitedFiles on Julia 1.9. If we need to vendor more, please comment here, otherwise I think this is now solved?

**Comment by pfitzseb** [comment]
This is still kinda relevant for nightly, because we don't want to vendor deps for that. Falling back to a Pkg-managed environment makes sense in that case imho.

**Comment by pepijndevos** [comment]
Also worth noting that the latest julia master already identifies as 1.10 so would use the fallback env based on +release rather than the 1.9 env.

It is probably unavoidable that nightly will break the extension at some point, so I think the Pkg solution could make sense, or support for running the language server on a different version than the repl.

**Comment by serenity4** [comment]
>  and/or support for running the language server on a different version than the repl.

I think this might be the easiest: letting the user choose to use a stable version for the language server, while using a beta or nightly build for the REPL. It seems also straightforward to implement, with no maintenance burden. This would be aimed for trying out development versions of Julia, not e.g. choosing two different stable versions, so we should probably make it clear in the documentation (next to the setting perhaps).

If we know that users could face potential issues in running different versions for the LS and the REPL, then we could just add a warning next to the relevant setting. After all, this is meant to be experimental, as there is never any guarantee that nightly will work smoothly.

**Comment by davidanthoff** [comment]
I think we can close this now. If Juliaup is present, the LS will always use the `release` channel version, and then one can use some other version for running code etc.
