### ISSUE TITLE
`vscodedisplay` not defined in a module

### ISSUE THREAD

**Issue by mrufsvold** [julia-vscode/julia-vscode#3169]
I can't seem to call `vscodedisplay()` from within a custom module.

I have a small utility module in my current project that is supposed to do some work in a database and then display the results using the Table Viewer, but even though `vscodedisplay` works when I call it from the toplevel in the REPL, I get `UndefVarError: vscodedisplay not defined` when it is called from inside a function. 

MWE:
```
module DisplayTables
    using DataFrames
    function display_a_table()
        df = DataFrame(a=[1,2,3])
        vscodedisplay(df)
    end
end

using .DisplayTables
DisplayTables.display_a_table()
# ERROR: UndefVarError: vscodedisplay not defined
```
Maybe it's just the nature of trying to integrate the REPL with VSCode utilities, but if there is a workaround/fix, I'd love to know!

**Comment by pfitzseb** [comment]
You can always reach for `Main.VSCodeServer.vscodedisplay` directly. Do put in a few checks for the existence of these fields :)

**Comment by mrufsvold** [comment]
Oh, perfect! Thank you!!
