### ISSUE TITLE
julia.executablePath & julia.NumThreads not taken into consideration

### ISSUE THREAD

**Issue by Patrikios** [julia-vscode/julia-vscode#3183]
`julia.executablePath` &` julia.NumThreads` are being ignored whereas the `julia.symbolCacheDownload` is being correctly communicated to the runtime.
Hence, having installed several Julia version (versions julia-1.6.5 up to julia-1.8.4), not the  latest julia version (1.8.4) is being found and the number of active session threads is 1.

The problem is aparent from the code-server setting as follows (dimmed out color, howeve ron says 'This setting cannot be applied in this window. It will be applied when you open a local window.'):

![image](https://user-images.githubusercontent.com/11005155/210246214-34bf1b53-3387-46fd-8828-624d3c026b9f.png)

How do I force it? I noticed the problem after donwloading and linking to the julia-1.8.4 version, before it was working fine.

I am on:
Debian GNU/Linux 10 (buster)
code-server: v4.9.1
Julia Ext v1.38.2

**Comment by pfitzseb** [comment]
What file is this in? Pretty sure you need to make those changes in the remote settings:
![image](https://user-images.githubusercontent.com/6735977/210248963-a4f1427d-6c1e-474d-a899-bb9947137426.png)

**Comment by Patrikios** [comment]
Hi @pfitzseb 
yes, that is it, in code.server there are several (user, remote, workspace) preferences, I was in user whereas I ought to be in remote. Thnx for the hint!
