### ISSUE TITLE
Julia-REPL started in wrong folder?

### ISSUE THREAD

**Issue by kellertuer** [julia-vscode/julia-vscode#3217]
This is a continuation of https://github.com/quarto-dev/quarto/issues/73 since it refers to running Quarto code cells in REPL.

I have a Quarto Markdown file with a cell like

```{julia}
#| echo: false
using Pkg;
Pkg.activate("."); # use the example environment,
```

and the Quarto extension displays (they say by you or then action passed on to this extension and use the `executeInREPL()` command) a “Run Cell” button above the cell.
Now the quarto file is in an `examples` subfolder of the package (and the package folder is of course the one I opened in VS Code). This cell should (and does when running Quarto) activate the environment in the `examples/` folder.

However the “Run Cell” command starts a Julia REPL (see link above, that should be handled by Julia-VSCode as far as I understand) but in the folder of the package and not the examples folder. Hence the wrong environment is activated. Is there a trick to use the current folder of a file for the Julia-REPL start? Or any other trick to make the run-cell to run in the `examples/` folder?
It would be great to have the “Run Cell” button to be consistent with running quarto on the file. 

For reference the quarto file is this one https://github.com/JuliaManifolds/ManoptExamples.jl/blob/main/examples/Riemannian-mean.qmd which might for now be a bit tricky to use, since the package is not yet registered and one has to also add `ManoptExamples.jl` in dev-mode in the environment in `examples` (sorry for that).

**Comment by mosullivan93** [comment]
I believe that the behaviour in Quarto can be made consistent for `@__DIR__` if they include the filename of the current document when executing the cell via `executeInREPL`. [Original](https://github.com/quarto-dev/quarto/issues/163#issuecomment-1534215026).

**Comment by kellertuer** [comment]
Thanks for the cross-ref :) looking forward to having this consistent.

**Comment by kellertuer** [comment]
I finally had the time to check again, for me the problem persists.
Running Code of a tile in `tutorials/myFile.qmd` in VS Code activates the project in `./`, even in the newest versions of extensions.

**Comment by mosullivan93** [comment]
I believe the extension will always launch in the same directory as the open folder. You should now be able to rely on `@__DIR__` to form a relative path for cases such as specifying the environment in the Pkg API.

**Comment by kellertuer** [comment]
That is even more complicated, since I am using a Workspace with 6 folders, but the `@__DIR__`, actually inspired by your post, works just fine :)

And along that way I even solved one of the issues that even came from times _before_ I used quarto and was the only one quarto was not able to fix until now: When developing a package and writing a tutorial for a new feature, that is not yet part of a registered version – then a similar trick `Pkg.dev("../")` even allows for these tutorials to run, which is super-nice – since the rest is still reproducible the environment specified for all other tutorials.

So – executing code is _still_ starting a REPL in a wrong folder – but the above is an easy fix
