### ISSUE TITLE
Cannot "go to definition" if I load .jl files with "includet" from Revise (it works with "include")

### ISSUE THREAD

**Issue by andresdrenik** [julia-vscode/julia-vscode#3229]
In the first attachement I include the file 1_setup.jl with

```include("1_setup.jl")```

and by hovering over the name of functions inside that file I get to see a description of them. Also, command+click takes me to that function. In the second attachment I include the file with

```includet("1_setup.jl")```

but then I lose all of these capabilities.  Is there a way to make the benefits I get in the first case available when using "includet"?
<img width="948" alt="Screenshot 2023-03-13 at 12 43 42 PM" src="https://user-images.githubusercontent.com/84545333/224785468-4afc0921-69e5-41cd-add8-748bec34a9e5.png">
<img width="948" alt="Screenshot 2023-03-13 at 12 44 08 PM" src="https://user-images.githubusercontent.com/84545333/224785476-789a23bf-980f-436c-ab53-bc9d7158f3e8.png">

**Comment by ma-sadeghi** [comment]
Is there an update on this issue? Thanks!

**Comment by andresdrenik** [comment]
Hi, this is marked as completed, but I'm still facing the same issue. Is there anything I need to do to activate this fix? Thank you!

**Comment by pfitzseb** [comment]
No, there shouldn't be anything you need to do besides update to the latest version of the extension. This still works for me.
