### ISSUE TITLE
PyPlot doesn't work with the plot pane

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/julia-vscode#325]

**Comment by davidanthoff** [comment]
@stevengj I'm trying to figure out why something like ``plot(randn(10), randn(10))`` doesn't just show up in the plot pane in VS Code when entered in the integrated REPL.

The plot does show up in the plot pane when I execute ``gcf()``, that returns an instance of ``PyPlot.Figure``. But the call to just ``plot`` seems to return
````julia
1-element Array{PyCall.PyObject,1}:
 PyObject <matplotlib.lines.Line2D object at 0x0000000024CCFBA8>
````
which doesn't hook into the standard multimedia display system, as far as I can tell.

Is that just how it is, or is there some way that we could get a simple call to ``plot`` to show something in the plot pane?

**Comment by davidanthoff** [comment]
I'm also moving this to v0.9.0 because there is a workaround for now: just call ``gcf()``.

**Comment by stevengj** [comment]
PyPlot doesn't return a displayable figure, it works by side effects.  If you want to return a displayable figure, you can do `withfig(figure()) do .... end` or you can return `gcf()`.

In IJulia, PyPlot [pushes some hooks to display plots after a cell executes](https://github.com/JuliaPy/PyPlot.jl/blob/693895e2cbbd0f08b6fb63fa0df2c516358d33ad/src/init.jl#L194-L197).   I don't know if it is possible to do something similar with vscode?

**Comment by davidanthoff** [comment]
We just run the normal julia REPL inside VS Code and push our display backend onto the multimedia stack, that is really all we do. So unless there is some generic solution for the basic julia REPL I think we shouldn't really add anything beyond that.

I think this sounds just like by design then. Thanks for clarifying!

**Comment by stevengj** [comment]
One alternative is to have PyPlot call `redisplay(fig)` as a side-effect of each plotting function, and have your display backend use `redisplay` to push the figure onto a queue to display.  PyPlot used to do this, in fact, but was really fragile because it involved monkey-patching matplotlib, and it was difficult to get it to work properly with Interact as well.

**Comment by davidanthoff** [comment]
Ah, I'll have to figure out ``redisplay`` and how that would map with the approach we are using, thanks for the pointer.

**Comment by MartinOtter** [comment]
The approach with gcf() displays the plot inside vscode without plot-toolbar. Therefore, important functionality is not available (zoom, save plot in different formats etc.).

Note, when starting a Julia REPL in a cmd window under Windows 7, plot opens a separate window with a toolbar. With figure(..) different windows can be opened.

**Comment by stevengj** [comment]
If you do `pygui(true)` it should open in a separate window, if that's what you want.  https://github.com/JuliaPy/PyPlot.jl#interactive-versus-julia-graphics

**Comment by MartinOtter** [comment]
> If you do `pygui(true)` it should open in a separate window, if that's what you want. https://github.com/JuliaPy/PyPlot.jl#interactive-versus-julia-graphics

Thanks very much. Yes this works!!!

**Comment by frankwswang** [comment]
I got the same problem and fixed it following the introductions in this issue page. Thank you very much! However, now if I want PyPlot to show the plot with a plot-toolbar, I have to add another line of code `pygui(true)`, yet I don't need to add it in a windows cmd based Julia REPL. It seems that I have to adjust my Julia code which uses PyPlot if I want to run it on vscode. I wonder do you consider this a temporary solution or a settled method?

**Comment by davidanthoff** [comment]
I think we'll add something at some point to configure the plot pane, i.e. whether it is active at all. At that point you could just disable it in the settings.

**Comment by jebej** [comment]
Does the plot pane actually work? Running `display(gcf())` does not seem to work.
