### ISSUE TITLE
Add process setting in extension like thread.

### ISSUE THREAD

**Issue by NeroBlackstone** [julia-vscode/julia-vscode#3255]
There is an existing option for threads:

Julia: Num Threads
Number of threads to use for Julia processes. A value of auto works on Julia versions that allow for --threads=auto.
`"julia.NumThreads": 1`

I think adding an option for the process is better, setting `Julia -p auto` automatically before running Julia via extension.
Setting json file like `"julia.NumProcess": "auto",`

**Comment by cjproud** [comment]
+1, I would like to see this as well as I'm running a Julia webserver with multiple threads and processes.

**Comment by pfitzseb** [comment]
You can use the `julia.additionalArgs` setting for this -- simply add 
```
    "julia.additionalArgs": [
        "-p",
        "auto",
    ]
```
to your settings.json.

I don't think we'll add this as a separate setting.

**Comment by cjproud** [comment]
Thanks @pfitzseb, didn't know about that setting!
