### ISSUE TITLE
Highlighting: `for` iterator in docstring interpolation

### ISSUE THREAD

**Issue by mortenpi** [julia-vscode/julia-vscode#3258]
```julia
"""
$(s for s in xs)
"""
foo(x::String) = x
```

![image](https://user-images.githubusercontent.com/147757/227135815-75649fff-b664-4c77-a4c9-5c1221cd11d5.png)

**Comment by pfitzseb** [comment]
Of course,
```julia
"""
$((x for x in x)...)
"""
foo(x::String) = x
```
_is_ valid and shows the same issue, so nvm.
