### ISSUE TITLE
"Always copy code" button for external REPLs doesn't seem to work on remote machines

### ISSUE THREAD

**Issue by ssfrr** [julia-vscode/julia-vscode#3262]
I'm using vscode's remote SSH integration. In a separate terminal I have a REPL running on the remote machine. From VScode I run "connect to external REPL" and the following pops up:

![image](https://user-images.githubusercontent.com/734386/228862731-6f1dfaf1-c439-4b48-b37b-0303ca414d9a.png)

After clicking "always copy code" it copies the code, but the window still pops up every time.

The "julia.persistentSession.alwaysCopy" option doesn't appear in my remote machine vscode settings, but does appear in my local settings. Manually enabling the local setting seems to work (from that point on the code is copied without the window popping up)

**Comment by sharanry** [comment]
A bump on this as I am consistently facing the same issue.
