### ISSUE TITLE
Do julia-vscode install a separate julia?

### ISSUE THREAD

**Issue by PhyX-Meow** [julia-vscode/julia-vscode#3264]
I found a julia installation in vscode storage, it was v1.8.2, installed by juliaup. And seems that this julia is the one used for language server. Is there an option to let julia-vscode use system julia, not install another one. I mean, it wastes disk space and it seems that it would not be updated automatically. (Now latest julia release is 1.8.5)
Thank you for any advise!

**Comment by pfitzseb** [comment]
The extension does not handle any Julia installation. You can set whatever path you want with the `julia.executablePath` setting.

**Comment by PhyX-Meow** [comment]
I removed the `julia.executablePath` setting then the extension recognizes my system julia. Anyway the problem is gone, thank you.
