### ISSUE TITLE
julia.additionalArgs missing in run & debug commands

### ISSUE THREAD

**Issue by mackrol** [julia-vscode/julia-vscode#3312]
Follow up to #2552 
Arguments configured in julia.additionalArgs are present only in REPL sessions but missing in run (Ctrl+F5) and debug (F5) commands

julia-vscode v1.47.2

**Comment by grahamgill** [comment]
This item is relevant for me because
1. `Pkg.test` sets `--check-bounds=yes` as a command line switch on the julia process that runs the tests
1. in `julia.additionalArgs` of `settings.json` I can set `--check-bounds=yes` so this switch is used when evaluating code in the julia REPL
1. but when I run a file with Run (^F5 on mac) or Debug (F5) there's no way to pass `--check-bounds=yes` via `launch.json`

I should be able to get consistent behaviour for testing.

**Comment by davidanthoff** [comment]
You _should_ be able to pass the command line args via `launch.json`? Is that not working for you?

**Comment by grahamgill** [comment]
@davidanthoff `args` in `launch.json` sets `Base.ARGS` but does not let you pass command line switches to julia itself.

E.g. with

`launch.json`:
```JSON
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "julia",
            "request": "launch",
            "name": "Run active Julia file",
            "program": "${file}",
            "stopOnEntry": false,
            "cwd": "${workspaceFolder}",
            "juliaEnv": "${command:activeJuliaEnvironment}",
            "args": ["--check-bounds=yes", "--", "arg1", "arg2"]
        }
    ]
}
```

`script.jl`:
```julia
@show ARGS
```

produces the output
```
ARGS = ["--check-bounds=yes", "--", "arg1", "arg2"]
```
when run with F5 or ^F5. So `--check-bounds=yes` is being passed as an argument to my script. It isn't being interpreted as a command line switch for julia.

**Comment by davidanthoff** [comment]
Ha, you are right of course!

Maybe it would make most sense to add a `juliaAdditionalArgs` to `launch.json`? That would be more flexible in the end than re-using the global setting we have for the REPL?

**Comment by grahamgill** [comment]
> it would make most sense to add a `juliaAdditionalArgs` to `launch.json`

I agree. That gives more flexibility in configurations.

I believe that's what #2552 was originally requesting (mentioned by the OP of this issue), except using the name `juliaArgs` .

**Comment by mind6** [comment]
I'm having this issue too, Julia v1.120.2, julia.additionalArgs not being passed to the process when invoking Julia: Run File In a New Process. The reason I don't use the REPL is it causes strange interactions with tensorflow (leaves all my cores at 100% CPU when idling).

**Comment by grahamgill** [comment]
Thanks for the quick turnaround on this! And for all the work on the
extension in general.

Works for me now in the latest preview build 1.123.1.
