### ISSUE TITLE
@profview first run shows empty tab

### ISSUE THREAD

**Issue by xgdgsc** [julia-vscode/julia-vscode#3316]
![image](https://github.com/julia-vscode/julia-vscode/assets/1189869/5d951520-fa50-4d04-b971-3f66b8ae35e0)

Everytime on first run of @profview  after start. It shows the empty Profiler tab. Following @profview  works.

**Comment by Zentrik** [comment]
I have also noticed this issue multiple times

**Comment by gdalle** [comment]
Same here

https://discourse.julialang.org/t/profiling-in-vscode-shows-blank-tab-on-first-run/100492

**Comment by BioTurboNick** [comment]
I've just started seeing this.
