### ISSUE TITLE
environment variables can't be reliably set in persistent (tmux) REPL

### ISSUE THREAD

**Issue by ssfrr** [julia-vscode/julia-vscode#3342]
I have a bunch of environment variables defined in `terminal.integrated.env.linux`. When launching a regular integrated REPL, they all show up as expected, but when using the experimental persistent REPL, they didn't show up.

In figuring out the issue, It was helpful to read this post:

 https://aj.codes/posts/be-careful-using-tmux-and-environment-variables/

The behavior I’m seeing is the combination of a couple factors:
* Tmux inherits its parent environment when the server starts, i.e. the host process that runs all your tmux sessions. In other words, when you launch the first tmux session
* My local ssh config directly launches tmux on the host (not from within a shell)

The sequence that led to this issue was:
1. First, I ssh’ed into the machine outside of vscode. This opened up a tmux session without any of my regular environment defined in my .zshrc file. It starts zsh within tmux, which pulls my regular environment variables in (but just to that session)
2. Then I started the julia REPL from vscode, it opened the integrated terminal shell, which included my `terminal.integrated.env.linux` environment, and then started a new tmux session. This second session didn’t start a new server though, so within tmux it didn’t end up inheriting the vscode environment, it got the empty global environment from my earlier session from SSH.

If I shut down tmux entirely and then launch the REPL, it starts a new tmux process within the integrated terminal environment, and then it does have all the expected environment.

So as it stands now, it doesn’t seem like there’s a clean way to control the environment of the REPL if its launched within tmux, unless you know there’s no other tmux sessions running. I can think of a couple possible solutions:

* when tmux is launched, use the `-L` argument to create a named pipe, which causes it to launch a brand new process rather than joining onto an existing one
* launch a shell within the tmux session, so the users's regular `.zshrc` etc. will get used
* set the environment variables in `terminal.integrated.env.linux` explicitly when launching julia within tmux

**Comment by pfitzseb** [comment]
With https://github.com/julia-vscode/julia-vscode/pull/3489, we're starting *a* shell inside of tmux (just not the shell you're expecting, unless you manually set `julia.persistentSession.shell`).
