### ISSUE TITLE
Just a typo: syntaxes/julia_vscode.json  line #209

### ISSUE THREAD

**Issue by gvanuxem** [julia-vscode/julia-vscode#3364]
function argumnets => function arguments

(sorry for the noise)

**Comment by xgdgsc** [comment]
This is reverted in https://github.com/julia-vscode/julia-vscode/commit/aa39f1384d1fe283f343b8900745e1e296fa5ad7#diff-a6955d32cfb915ce0d8178094e7e36f8308afa1e8706c9305c53954726e99c45

**Comment by pfitzseb** [comment]
-> https://github.com/JuliaEditorSupport/atom-language-julia/commit/85cf3ef2ddcb7bc9b2b17b2a5f1fc664e1f1e718
