### ISSUE TITLE
6 seconds to compile a simple function

### ISSUE THREAD

**Issue by ShalokShalom** [julia-vscode/julia-vscode#3404]
Hi there :)

The following only happens with the VSCode extension, both the Jupyter extension and normal mode. 

I define a function, evaluate it, and it takes an eternity to calculate. 

I tried that on the REPL in the Terminal, and it was blazing fast. 

![Screenshot_20230903_200639](https://github.com/julia-vscode/julia-vscode/assets/6344099/a542cf16-c989-4e8b-a7c1-c122a671e063)

![Screenshot_20230908_095834](https://github.com/julia-vscode/julia-vscode/assets/6344099/8b16300a-8bd2-4150-b34b-64bc8e64845c)

Garuda Linux KDE 
I am in VSCode 1.81.1 and Julia 1.9.3.
VSCode [binary](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=visual-studio-code-bin).

**Comment by pfitzseb** [comment]
Does this only happen for the first cell you evaluate?

**Comment by ShalokShalom** [comment]
No, it did evaluate the first time in 5.4 seconds.

**Comment by mrufsvold** [comment]
I've been curious, if you define a function in the second cell that's the same except call it `add2`, what timing do you get for the second function definition?

My hunch is that Jupiter is timing Julia startup and possibly the import and precompilation of the Jupiter package stuff in the first cell.  If that's the case, then any execution in that first cell will take a while, but then be comparable to REPL thereafter.

**Comment by ShalokShalom** [comment]
Yes, the second cell is much faster. 

I guess, I can close this issue?
Or is there anything we can do about this?

I feel like it would appear better, if the startup happens before the evaluation of the cell is displayed/calculated. 

Do you have any idea, if that's possible?

**Comment by mrufsvold** [comment]
I doubt it. This also happens with Python -- the first cell takes a second to start actually running because it's spinning up resources for the notebook. Just, in the case of Python, start up is optimized for and relatively fast. 

As we get more and more improvements to precompilation and code loading, this will speed things up, but I doubt there is much to be done from the Jupiter side of things.

**Comment by ShalokShalom** [comment]
Thanks a lot
