### ISSUE TITLE
Bug: on hover works, but go to definition does not?

### ISSUE THREAD

**Issue by MariusDrulea** [julia-vscode/julia-vscode#3418]
Here I do edit a fork of the https://github.com/FluxML/Tracker.jl package.
Hovering over `@grad` works but when I "Go to definition" the vscode complains there is no definition for it.

![Screenshot from 2023-09-25 22-49-59](https://github.com/julia-vscode/julia-vscode/assets/27725572/f9ad8615-c6ca-429a-bb06-5162d24c362d)

![image](https://github.com/julia-vscode/julia-vscode/assets/27725572/4aac4835-833d-4bde-ab82-c3a98b680cc1)

**Comment by pfitzseb** [comment]
Fixed by https://github.com/julia-vscode/StaticLint.jl/pull/374. Should be in the next release of the extension.
