### ISSUE TITLE
Ctrl+v doesn't work for paste in VSCode REPL

### ISSUE THREAD

**Issue by nathanrboyer** [julia-vscode/julia-vscode#3427]
I think this keyboard shortcut used to work, but it isn't working now. I have disabled all extensions except the Julia extension for testing. I can use Ctrl+v to paste in the VSCode PowerShell terminal and in the VSCode file editor, but that keyboard shortcut does not do anything in the VSCode Julia REPL. Ctrl+Shift+v and right click both work to paste in both the terminal and Julia REPL, but that is not the shortcut I want to use. I don't remember changing any default shortcuts related to paste.
![image](https://github.com/julia-vscode/julia-vscode/assets/65452054/2ad1c595-1be0-43df-b13f-4eadb930d2f3)

**Comment by pfitzseb** [comment]
What OS are you on? I can't repro this on Windows.

**Comment by nathanrboyer** [comment]
Windows 11

**Comment by nathanrboyer** [comment]
My issue was `workbench.action.terminal.sendSequence` was conflicting. I don't know what that is or where it came from, but deleting it fixed paste into the REPL.
![image](https://github.com/julia-vscode/julia-vscode/assets/65452054/13e40182-47f6-4d39-b90c-f5923361baea)

**Comment by pfitzseb** [comment]
It's unclear why this would conflict, given that `terminalShellType` definitely should not be powershell for julia.
