### ISSUE TITLE
Unable to execute active file in REPL with julia 1.9

### ISSUE THREAD

**Issue by hack-hard** [julia-vscode/julia-vscode#3429]
When running a julia file in REPL mode with julia 1.9, the process fails with exit 1.
This is the executed command:
```
/home/hacquard/.julia/juliaup/julia-1.9.3+0.x64.linux.gnu/bin/julia \
-i \
--banner=no \
--project=/home/hacquard/compute \
--precompiled=yes \
/home/hacquard/.vscode-server/extensions/julialang.language-julia-1.54.2/scripts/terminalserver/terminalserver.jl\
/tmp/vsc-jl-repl-6a47c512-38f0-485d-b834-303985da27bb', '/tmp/vsc-jl-cr-b3b455d0-f992-46e1-adbf-752784b2cf41 \
USE_REVISE=true \
USE_PLOTPANE=true \
 USE_PROGRESS=true \
 ENABLE_SHELL_INTEGRATION=true \
 DEBUG_MODE=false
```

I have the following error message:
```
ERROR: unknown option `--precompiled=yes
```

**Comment by pfitzseb** [comment]
You must have set that argument in the settings yourself, we're not starting Julia with `--precompiled=yes`. Note that you probably want `--compiled-modules=yes` instead.

**Comment by hack-hard** [comment]
Thank you for the response. It fixed my issue. I am still confused about why this parameter was set on my end.
