### ISSUE TITLE
Ctrl+I chord keybinding conflict with Copilot Chat

### ISSUE THREAD

**Issue by joyceerhl** [julia-vscode/julia-vscode#3452]
:wave: I work on VS Code, and we have a Ctrl+I keybinding to start a Copilot Chat session inline in the user's active editor. This keybinding doesn't work for Julia files when the Julia extension is installed: https://github.com/julia-vscode/julia-vscode/blob/main/package.json#L772

We'd love to get Ctrl+I working for Julia users out of the box. One possible approach is to tighten the keybinding when clause here, e.g. `"editorTextFocus && activeEditor != workbench.editor.notebook && editorLangId in julia.supportedLanguageIds && activeEditorHasInlineResults"` to avoid this conflict. Please let me know what you think. Thank you for your consideration!

**Comment by pfitzseb** [comment]
Shouldn't <kbd>Ctrl+I</kbd> still work, even though we define the <kbd>Ctrl+I Ctrl+C</kbd> chord?

Anyways, I'm happy to change this keybinding to something else.

**Comment by joyceerhl** [comment]
Sorry for the delayed followup here. I believe not because VS Code will wait for the second chord to be pressed (this is the behavior I see today when I have installed the Julia extension and try to use Ctrl+I):

<img width="519" alt="image" src="https://github.com/julia-vscode/julia-vscode/assets/30305945/ee3e64dc-d973-4016-b0f6-4374993ad980">
