### ISSUE TITLE
Debugging: Breakpoints are ignored when using pipelining ( |> )

### ISSUE THREAD

**Issue by Para7etamol** [julia-vscode/julia-vscode#3456]
After upgrading vscode, julia-vscode ignores breakpoints used in function pipeline.
Downgrading vscode does not help.
Please help/repair :-)

MWE:

```julia
function to_be_debugged(message::String)
    # set break point on next line
    println(message)
end

to_be_debugged("stopping")

"not stopping" |> to_be_debugged
```

julia 1.9.2
vscode 1.84.2
ubuntu 22.04

**Comment by pfitzseb** [comment]
I don't think this is a regression. `|>` needs to be interpreted by default, which #3459 will do. In the meantime you can add it to the list of interpreted functions manually.
