### ISSUE TITLE
The language client requires VS Code version ^1.82.0 but received version 1.78.2

### ISSUE THREAD

**Issue by jariji** [julia-vscode/julia-vscode#3457]
The language server isn't working right. Text doesn't send to the terminal, maybe the server is failing to start altogether. The Output says

```
The language client requires VS Code version ^1.82.0 but received version 1.78.2
```

Vscode Julia extension version v1.57.2.

```
julia> versioninfo()
Julia Version 1.9.3
Commit bed2cd540a1 (2023-08-24 14:43 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 24 × AMD Ryzen 9 3900XT 12-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, znver2)
  Threads: 24 on 24 virtual cores
Environment:
  JULIA_NUM_THREADS = 24
  JULIA_PKG_PRESERVE_TIERED_INSTALLED = true
  JULIA_EDITOR = code
```

I can downgrade the extension and it works fine, but should that be necessary?

**Comment by pfitzseb** [comment]
I assume you fixed this with a VS Code upgrade?

**Comment by jariji** [comment]
No I downgraded the extension to 1.56.2.

**Comment by pfitzseb** [comment]
Is there a reason not to update to a more recent VS Code version? If so, I think I can relax the VS Code version requirement as well.

**Comment by jariji** [comment]
VSCode 1.78.1 is [the version](https://search.nixos.org/packages?channel=23.05&show=vscode&from=0&size=50&sort=relevance&type=packages&query=vscode) in the stable release of my distro, NixOS 23.05. NixOS 23.11 will come out in a couple weeks with VSCode 1.83 or so.

**Comment by pfitzseb** [comment]
1.60 is now compatible with VS COde 1.78 again.

**Comment by jariji** [comment]
Thanks.
