### ISSUE TITLE
Persistent session does not work for systems with csh/tcsh shells

### ISSUE THREAD

**Issue by bgroenks96** [julia-vscode/julia-vscode#3461]
For systems with shells that do not support the syntax `VAR=value cmd`, the following command construction:

https://github.com/julia-vscode/julia-vscode/blob/a0a18162373832b3f58d514d6a7f9ae7dfa59b59/src/interactive/repl.ts#L190C28-L190C28

does not work and causes the persistent session to die immediately on startup.

Personally, I would prefer to always use `bash`, but I cannot control what the HPC system administrator installed as the default shell. I have tried setting the integrated shell to bash in VS Code settings but this does not seem to solve this issue. The REPL is still launched using the default system shell.

The ideal solution here would, I guess, be to detect the current shell and adjust the command appropriately. But is there a workaround to force either VS Code or vscode-julia to run these commands in bash?

EDIT: I should note also that setting the option `julia.persistentSession.shell` to `bash` does not solve this.

**Comment by pfitzseb** [comment]
Can you check that 
```
/bin/sh -c 'tmux new -d -s foo "FOO=bar julia"'
```
fails, but 
```
/bin/sh -c 'tmux new -d -s foo "/bin/sh -c '"'"'FOO=bar julia'"'"'"'
```
works?

**Comment by bgroenks96** [comment]
Ok, I found a workaround. You can add the following to `~/.tmux.conf`:

```
set -g default-shell /bin/bash
```

@pfitzseb Yes, that is the case, unless you update `.tmux.conf` with the above option, and then they both work.

**Comment by pfitzseb** [comment]
Imo it's best to use the configured shell inside of tmux as well, so I'll make that change in a future release.
