### ISSUE TITLE
Debugger does not launch

### ISSUE THREAD

**Issue by poldap** [julia-vscode/julia-vscode#3470]
Hello,

I'm in VSCode 1.85.0-insider (although the same happened in the last version) on Fedora on my laptop, and the extension Julia v1.60.2. Running the code, as well as everything else, works well. However, whenever I launch the debugger in any way, I will get the message 
```
 *  Executing task: julia --color=yes --startup-file=no --history-file=no --project=/home/poldap/.julia/environments/v1.9 /home/poldap/.vscode-insiders/extensions/julialang.language-julia-1.60.2/scripts/debugger/run_debugger.jl /tmp/vsc-jl-dbg-db19498a-4c4b-4e60-9589-1e2267af605b /tmp/vsc-jl-cr-f02c20f1-779a-4408-b9c1-7627a12afc93 

> Connecting to debugger... Done!
```
but "nothing" will happen. No stopping at breakpoints, the "pause" button won't do a thing, and the code does not appear to be running. Hitting the stop button will make the hovering panel with the buttons disappear. 

Let me know if I should provide any more details.

Thank you in advance for the help.

**Comment by pfitzseb** [comment]
Can you try with a *really* simple MWE? 
There are two possibilities for this happening -- either the debugger is really slow and your case and you didn't wait long enough for it to hit your breakpoint, or your breakpoint is in a function that's compiled (which by default is the case for all of Base except some higher order functions).

**Comment by poldap** [comment]
a _really_ simple MWE works wonderfully
```
str = "Hello, World!"
println(str)
str = str*" "*str
println(str)
```

My working file, however, doesn't. Running through `Ctrl + F5` does though. And it is definitely not a matter of waiting (I know the running time from `Ctrl + F5` and from running it manually, and I've let it there to see if something happened for 30 min or so). Could the involved libraries have an effect? I am using CUDA.jl, but the breakpoints are obviously not in the CUDA kernel.

Thanks in advance for your help.

**Comment by poldap** [comment]
oh! it was a bug  in my `launch.json`. Thank you! 

Before learning how to do it properly I had set 
`"juliaEnv": "${command:activeJuliaEnvironment} --threads=15"`, and that did not cause any problem except for messing up the debugger (did nothing though). 

Thanks for the help!
