### ISSUE TITLE
Pyimport crashes VSCode Julia REPL  

### ISSUE THREAD

**Issue by gaston-fernandez** [julia-vscode/julia-vscode#3482]
Importing the Python module `Scipy` instantly crashes and closes VSCode Julia REPL before I can see the error message.

For instance, the following code crashes my REPL every time:
```
julia> using PyCall
julia> mv = pyimport("scipy.stats.mvn") 
```
Interestingly, importing the module `Math` does not crash my REPL:
```
julia> using PyCall
julia> math= pyimport("math")
PyObject <module 'math' from '/Users/gaston/.julia/conda/3/lib/python3.10/lib-dynload/math.cpython-310-darwin.so'>
```
In VSCode, I am using:
```
Version: 1.84.2 (Universal)
Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
Date: 2023-11-09T10:52:33.687Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 20.6.0
```
And I have `v1.60.2` of the Julia language extension. This is all on MacOS Big Sur 11.6 (M1, 16GB)

**Comment by gaston-fernandez** [comment]
As an addendum, trying with the package [`PythonCall`](https://juliapy.github.io/PythonCall.jl/stable/) instead of `PyCall` does not crash nor close the Julia REPL. 

I am not sure why this is but I am using `PythonCall` for the moment.

**Comment by pfitzseb** [comment]
Doesn't seem to be related to the extension. Ref https://discourse.julialang.org/t/pyimport-crashes-vscode-julia-repl/107172.
