### ISSUE TITLE
Code is executed in builtin REPL after connecting to external REPL.

### ISSUE THREAD

**Issue by atemmo** [julia-vscode/julia-vscode#3498]
I developed a bug using external REPL after latest vscode/julia-vscode update (not sure which one caused it).

Usually:
1. execute "Connect external REPL" command in vscode
2. paste the command to the terminal, vscode server precompiles
3. code is executed in external REPL

Now:
1. and 2. are the same
3. upon executing code new builtin REPL opens and nothing happens in external one.

VSCodium - Version: 1.85.1 - Release: 23348
julia-vscode - v1.65.2
macos 14.2; m1

**Comment by JobJob** [comment]
Same issue. v1.61.2 works fine, so must be something recent.
