### ISSUE TITLE
REPL terminal can get stuck with some outputs/warnings

### ISSUE THREAD

**Issue by daviehh** [julia-vscode/julia-vscode#3511]
Normally, when running a script, the REPL would print out the result of the last line in the script.
It looks like, with certain outputs to the REPL, the REPL/terminalserver can get stuck with ~100% cpu for the terminalserver.jl process. Consider [this example](https://docs.sciml.ai/NeuralPDE/stable/tutorials/ode/) from the DifferentialEquation library:
```
using NeuralPDE, Flux, OptimizationOptimisers

linear(u, p, t) = cos(2pi * t)
tspan = (0.0f0, 1.0f0)
u0 = 0.0f0
prob = ODEProblem(linear, u0, tspan)

chain = Flux.Chain(Dense(1, 5, σ), Dense(5, 1))
opt = OptimizationOptimisers.Adam(0.1)
alg = NeuralPDE.NNODE(chain, opt)

@time sol = solve(prob, NeuralPDE.NNODE(chain, opt), verbose=true, abstol=1.0f-6,
    maxiters=200)
```
the REPL would stuck at the `@time` output (`14.586608 seconds (19.95 M allocations: 1.270 GiB, 1.38% gc time, 94.03% compilation time)`) for a very long time before finally printing out the array elements of `sol`. Running the script directly in julia REPL outside vscode is fine, and adding a dummy `println("")` to the end of the script also works fine.

---

On macos,
julia-vscode v1.65.2,
vscode: Version: 1.85.1 (Universal)
julia versioninfo
```
Julia Version 1.10.0
Commit 3120989f39b (2023-12-25 18:01 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 10 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores
Environment:
  JULIA_MATHLINK = /Applications/Mathematica.app/Contents/Frameworks/mathlink.framework
  JULIA_MATHKERNEL = /Applications/Mathematica.app/Contents/MacOS/MathKernel
  JULIA_MAX_NUM_PRECOMPILE_FILES = 5
  JULIA_PROJECT = @.
  JULIA_EDITOR = nvim
```

**Comment by pfitzseb** [comment]
I suspect that this happens due to introspection on the `sol`ution, which is done for the workspace viewer. I'll look intro repro'ing this.

**Comment by daviehh** [comment]
Thanks for the heads-up! Looks like it's a `display` thing, issue goes away with, e.g.
```
VSCodeServer.display(s::ODESolution) = VSCodeServer.display(s.retcode)
```
