### ISSUE TITLE
delete the Insider extension from OpenVSX

### ISSUE THREAD

**Issue by nsajko** [julia-vscode/julia-vscode#3536]
It seems the Julia Insider extension was deprecated in favor of giving the usual Julia extension prerelease versions. Would it be possible to delete the Julia Insider extension from OpenVSX to prevent confusion? This is the extension's page: https://open-vsx.org/extension/julialang/language-julia-insider

**Comment by davidanthoff** [comment]
https://github.com/EclipseFdn/open-vsx.org/issues/2341

I don't think I can do anything beyond that.
