### ISSUE TITLE
How to activate a Python environment before Julia: Start REPL

### ISSUE THREAD

**Issue by ShuhuaGao** [julia-vscode/julia-vscode#3553]
I am using the `PythonCall.jl` package and I want it to use my local Python environment _plot_ (managed by micromamba). In the terminal, I can do the following to start a Julia REPL with plot environment activated.
```powershell
PS C:\Users\lenovo> micromamba activate plot
(plot) PS C:\Users\lenovo> julia
```

How can I do the same when using the integrated Julia REPL in vs code? Can I type some kind of command to start it instead of the menu **Julia: Start REPL**?

**Comment by pfitzseb** [comment]
You can either use the "Julia: Connect external REPL` command to connect to a Julia process in the correct Python env. Alternatively, write a small script that switches to the correct env before starting Julia, which you can set in the `julia.executablePath` setting.

**Comment by ShuhuaGao** [comment]
Thank you! @pfitzseb  Regarding you second suggestion, could you provide more details? I have prepared a powershell script *C:\Users\lenovo\Downloads\wps\good\micromamba-julia.ps1* with the following content
```powershell
micromamba activate plot
julia
```

That script works well in my terminal. But after I set `julia.executablePath` to *C:\Users\lenovo\Downloads\wps\good\micromamba-julia.ps1*, nothing helped: `using PythonCall` throwed init error, which implies the micromamba environment *plot* is not properly activated.

**Comment by ShuhuaGao** [comment]
Another workaround is to start VS code within the activated Python environment by typing `code` in the terminal.  Please check [this dicussion on PythonCall.jl](https://github.com/JuliaPy/PythonCall.jl/discussions/466#discussioncomment-8663776).

**Comment by pfitzseb** [comment]
You'll probably need 
```
micromamba activate plot
julia @args
```
instead, so you pass all args through properly. No idea how python environments work though, so I can't really be of much help, especially if you don't provide any error output.

**Comment by ShuhuaGao** [comment]
Thanks, though adding `@args` still did not work. Anyway, we know that starting VS code from the activated Python environment indeed worked.
