### ISSUE TITLE
Handle `\r` in the notebook

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/julia-vscode#3561]
Running
```julia
print("Hello World")
print("\r")
print("1234")
```
with a Jupyter/IJulia kernel results in output
```
1234o World
```
but running it in the extension Julia kernel results in
```
Hello World
1234
```

If we just handled the `\r` like the Jupyter/IJulia kernel did, things like ProgressMeter would look a lot better, at least in some basic use-cases.

@DonJayamanne and @amunger any suggestion on how we might want to do that? Is there special handling in the Jupyter extension for this that we could just replicate somehow? The code that currently handles this in the extension is https://github.com/julia-vscode/julia-vscode/blob/696ce5099862668a242ba6bc0a3cd22de1401698/src/notebook/notebookKernel.ts#L255, presumably we would want to change that somehow?

**Comment by DonJayamanne** [comment]
I'll try to look into this some time during our debt week (approx 2 weeks from now). See here about our iteration plan and when we work on debt https://github.com/microsoft/vscode/wiki/Development-Process#inside-an-iteration

Please feel free to ping me if i do not get back.
Thanks for your patience and sorry this has been dragging on for a long time.
