### ISSUE TITLE
Support for the screen command in the Julia REPL

### ISSUE THREAD

**Issue by Atreyu-94** [julia-vscode/julia-vscode#3574]
When you're working on a cluster, it's often very useful to use the Linux screen command to be able to use multiple terminals without them depending on your connection.
However, when you run code with Julia's plugin, with Shift+Enter, it redirects to a new terminal that is not the screen that was previously open in VSCode.
Would this be possible?

**Comment by pfitzseb** [comment]
We have full tmux support, so I'd recommend using that instead of screen. Search for `julia persistent` in the remote settings.

You could also manually start a julia REPL in your screen session and then use the `Julia: Connect external REPL` command to connect to that.
