### ISSUE TITLE
stdin interaction is weird after "Execute code in REPL"

### ISSUE THREAD

**Issue by jariji** [julia-vscode/julia-vscode#3577]
If I evaluate `@descend foo()` with `Julia: Execute code in REPL` then the last line is either `julia>` or `↵` and the toggle keys only work when `julia>` is shown and I can toggle between `julia>` or `↵` by using `backspace`.

Sebastian said 

> This can happen if you run code that reads from stdin via inline evaluation, instead of from the REPL directly

I found this confusing before I understood it and now that I understand it it's still annoying I can't just run `@descend` from the editor. 

Why is this happening? Can it be fixed?

**Comment by pfitzseb** [comment]
Dup of https://github.com/julia-vscode/julia-vscode/issues/785.

> Can it be fixed?

Probably, but it's nontrivial.
