### ISSUE TITLE
VSCode Julia linter bug in Dict's

### ISSUE THREAD

**Issue by AhmedSalih3d** [julia-vscode/julia-vscode#3589]
Hello!

I call it a bug, might be an implementation decision. I noticed that my dict does not render properly, it should be coloured green-ish:

![image](https://github.com/julia-vscode/julia-vscode/assets/36305327/1c9a5316-f55a-4f94-ab90-3dbcd8260e05)

Kind regards

**Comment by pfitzseb** [comment]
That's basically https://github.com/JuliaEditorSupport/atom-language-julia/issues/131.

Closing as dup.
