### ISSUE TITLE
The latest pre-release version (v1.91.1-pre) exposes the exports of `Sockets`

### ISSUE THREAD

**Issue by SebastianM-C** [julia-vscode/julia-vscode#3640]
I'm seeing that `connect` is defined right after starting the REPL via the "Start REPL" command and this should not be usually available. This is breaking packages that might export functions that are also exported by `Sockets`, such as `ModelingToolkit`, which exports `connect`.

**Comment by sstroemer** [comment]
+1 (!)

This was extremely annoying to identify why a working code suddenly stopped working over night.

**Comment by davidanthoff** [comment]
Fixed on `main`.
