### ISSUE TITLE
unable show progressbar in the repl

### ISSUE THREAD

**Issue by kongdd** [julia-vscode/julia-vscode#3643]
> `julia-vscode`: v1.83.2

- When setting `julia.useProgressFrontend=false`, the progressbar disappear.
- While setting `julia.useProgressFrontend=true`, the progressbar shows in the status bar.

Any idea how to make progressbar show in the repl?

**Comment by pfitzseb** [comment]
Can you give some more context here? What packages generated the progress bars? What does "the progressbar disappears" mean?

**Comment by kongdd** [comment]
Sorry. My fault. It works after restart vscode.
