### ISSUE TITLE
Substitute `@__DIR__` by Directory on Execute Code in REPL

### ISSUE THREAD

**Issue by PatrickHaecker** [julia-vscode/julia-vscode#3653]
When a line in a file is selected containing `@__DIR__` and the shortcut for "Execute Code in REPL" is used, julia-vscode should replace `@__DIR__` with the actual directory of the file where the cursor is in before sending it to the Julia terminal.

**Comment by davidanthoff** [comment]
It doesn't substitute, but it should properly set the source path of the code, so that everything should just work as expected? Can you describe a bit more what is not working?

**Comment by pfitzseb** [comment]
This is already happening:
![image](https://github.com/user-attachments/assets/3bdbcd9a-6d23-452c-9d6f-229d6df0504d)

**Comment by PatrickHaecker** [comment]
Indeed, it does, thanks a lot!
I can't reproduce why it wasn't working when I tested it three days ago, but I am happy that it works and I will reopen if the problem happens again and I can reproduce it.
