### ISSUE TITLE
`@edit` not defined?

### ISSUE THREAD

**Issue by Datseris** [julia-vscode/julia-vscode#3655]
Oddly, VSCode tells me `@edit` not defined, when I do `@edit rand()`, in both a script inline evaluation and the integrated REPL.
```
ERROR: LoadError: UndefVarError: `@edit` not defined
```

If I open a Julia REPL without VSCode `@edit` works as expected.

Julia version: 1.10.4. OS: Windows 10. Julia VSCode extension v1.102.2.

**Comment by OndrejMarsalek** [comment]
I think this is related to an issue I also came across - `InteractiveUtils` are not loaded in the REPL in VSC, even though they should be by default, as it is, well, interactive. Things liked `@which` or `@code_*` are missing for the same reason. When I switch from the stable (v1.102.2) to the pre-release (v1.103.1) extension, it behaves as expected.

Try manually running `using InteractiveUtils` in the REPL launched by VSC to see if it's the same thing.

**Comment by Datseris** [comment]
exactly, I can confirm:
```
        
julia> @edit
ERROR: LoadError: UndefVarError: `@edit` not defined
in expression starting at REPL[2]:1

julia> using InteractiveUtils

julia> @edit
ERROR: LoadError: MethodError: no method matching var"@edit"(::LineNumberNode, ::Module)

Closest candidates are:
  var"@edit"(::LineNumberNode, ::Module, ::Any)
   @ InteractiveUtils C:\Users\gd419\.julia\juliaup\julia-1.10.4+0.x64.w64.mingw32\share\julia\stdlib\v1.10\InteractiveUtils\src\macros.jl:204

in expression starting at REPL[4]:1
```
in my VSCode repl.

**Comment by Datseris** [comment]
i can also confirm that in previous extension versions it worked as expected.

**Comment by OndrejMarsalek** [comment]
The macros I mentioned above definitely worked for me previously as well. Seems like a regression.

**Comment by davidanthoff** [comment]
Give the prerelease a try, hopefully we fixed it there.

**Comment by OndrejMarsalek** [comment]
For me, it works as expected in the pre-release.
