### ISSUE TITLE
Debuger cancellation no longer works

### ISSUE THREAD

**Issue by projekter** [julia-vscode/julia-vscode#3657]
Previously, when you were debugging a function, you could just hit "Disconnect" at any time when the debugger was currently stopped and it would cancel the execution and return to the REPL. This no longer works - now, "Disconnect" will in some way disconnect, i.e., the debugger controls go back to the state as if no debugger was attached, the run pane goes back to its default state and so on; but the REPL does not return from the `@run` command. However, it is also not the case that the rest of the function is then executed (compiled or interpreted), just nothing happens. CPU consumption is at 0%, Julia just seems to do nothing.
When then manually returning from the `@run` with Ctrl+C, the stacktrace is
```
ERROR: InterruptException:
Stacktrace:
 [1] try_yieldto(undo::typeof(Base.ensure_rescheduled))
   @ Base .\task.jl:931
 [2] wait()
   @ Base .\task.jl:995
 [3] wait(c::Base.GenericCondition{ReentrantLock}; first::Bool)
   @ Base .\condition.jl:130
 [4] wait
   @ .\condition.jl:125 [inlined]
 [5] take_buffered(c::Channel{Bool})
   @ Base .\channels.jl:477
 [6] take!
   @ .\channels.jl:471 [inlined]
 [7] 
   @ VSCodeServer.DebugAdapter c:\Users\...\.vscode\extensions\julialang.language-julia-1.96.1\scripts\packages\DebugAdapter\src\packagedef.jl:199
 [8] macro expansion
   @ c:\Users\...\.vscode\extensions\julialang.language-julia-1.96.1\scripts\packages\VSCodeServer\src\debugger.jl:108 [inlined]
 [9] top-level scope
   @ REPL[2]:1
```
which allow to return to the top-level. However, then, trying to debug something again will display the usual "waiting for process"-like progress bar and the debugger does not connect, as usually happens when some exception in Julia-VSCode was triggered (e.g., when trying to step into a generated function) and until Julia is restarted, no debugging is possible.
This error first appeared at least in 1.84.1; the last working version was at least 1.83.2.

Quick reproducer:
Put in an extra file (to avoid #3656):
```julia
function test()
    while true
        println("1")
    end
end
```
then open this file, put a breakpoint on the while line; in the REPL, include the file and `@run test()`. When the debugger stops at the loop, disconnect. No `1` will ever be shown and the behavior is as described.

**Comment by arvedjo** [comment]
Seems like I can disconnect with no error after the fix but not attach the debugger again with @run so it is a half fix unfortunatelly.

**Comment by projekter** [comment]
Yes, I can confirm this problem. 1.83.2 is still the last version with a repeatedly working debugger.
