### ISSUE TITLE
Ignore local environment project v. 0.103.2

### ISSUE THREAD

**Issue by lasotek** [julia-vscode/julia-vscode#3659]
Even though I select the local project for the catalog during live operation (ctrl+enter) it ignores the libraries from the configuration and uses those from the default version.
In the previous version it works as expeted.

**Comment by henrij22** [comment]
Can confirm, it always activate the default environment even though the local one is selected in the VS Code Gui

**Comment by mvanzulli** [comment]
Exactly the same, had to do it manually via `Pkg.activate`
