### ISSUE TITLE
The environment is not set

### ISSUE THREAD

**Issue by ValentinKaisermayer** [julia-vscode/julia-vscode#3661]
This should work according to here: https://www.julia-vscode.org/docs/stable/userguide/env/
But it does not:

![image](https://github.com/user-attachments/assets/fa74ee6d-1593-4a85-8093-1b103c61cf63)

On version **v1.103.2**

It works again on the pre-release version **1.104.1**.

**Comment by davidanthoff** [comment]
Yes, it is fixed in the dev version already, should ship to everyone soon.
