### ISSUE TITLE
Startup.jl runs (and fails) prior to Environment activating when opening REPL in VSCode

### ISSUE THREAD

**Issue by revolutionflourlake772** [julia-vscode/julia-vscode#3662]
This seems to be related to the recent issue where the specified environment didn't activate upon opening the REPL in VSCode (https://github.com/julia-vscode/julia-vscode/issues/3659). 

Basically, I see that I have the correct environment now after opening, but first there is an error in loading the packages from my startup.jl file: 
![image](https://github.com/user-attachments/assets/c27f5f71-4999-403e-8172-e0bad21d59ce)

This never happened prior to the recent issue with the default environment loading when opening a REPL in VSCode, so for whatever reason the startup.jl seems to be triggered before the environment loads.

In a normal shell window with this environment loading on open, the startup.jl loads normally:
![image](https://github.com/user-attachments/assets/2abc7b00-c791-4e29-8a1f-804da3eddd76)

**Comment by ValentinKaisermayer** [comment]
Seeing the same. I had it setup that my default environment would contain `Revise` and in the startup.jl I would load it. It seems that before, the startup.jl is run and then the local environment is activated, similar to performing `Pkg.activate(".")` at the end of the startup.jl. Now this changed?

**Comment by pfitzseb** [comment]
Currently, Julia is started in the default environment, your startup file gets loaded, and then the configured env is eventually activated. 

Can you describe your startup.jl and env setup in a bit more detail? I can't repro this with Revise in my global env and then setting a local env (that does not contain Revise) before starting the REPL.

**Comment by pfitzseb** [comment]
How are you setting `JULIA_LOAD_PATH`? Can you confirm that it's set to the expected value in the integrated REPL?

**Comment by revolutionflourlake772** [comment]
> How are you setting `JULIA_LOAD_PATH`? Can you confirm that it's set to the expected value in the integrated REPL?
> 
> > In any case, this seems to be a very recent change.
> 
> Yes, this is a consequence of #3629 I think.

I've always set depot path, load path, and num threads in the Windows global (system) environment variables, so no, it is not done in the REPL for me personally.

**Comment by pfitzseb** [comment]
Ok. What I meant with that second question is: can you confirm that `ENV["JULIA_LOAD_PATH"]`/`Base.LOAD_PATH` has the expected value in the integrated REPL?

**Comment by revolutionflourlake772** [comment]
> Ok. What I meant with that second question is: can you confirm that `ENV["JULIA_LOAD_PATH"]`/`Base.LOAD_PATH` has the expected value in the integrated REPL?

Ah, okay, I misunderstood the question before.

Yes, if I look at ENV["JULIA_LOAD_PATH"] (or DEPOT) in the VSCode Julia REPL, it's set correctly. Otherwise it would just instantiate the environment in the default location (which would take a long time and be very noticeable). I did verify it on both machines (Win 10 and 11) today.

**Comment by revolutionflourlake772** [comment]
thank you for the fix! 😍
