### ISSUE TITLE
juliaup "release" channel is required and default channel is not respected

### ISSUE THREAD

**Issue by coshz** [julia-vscode/julia-vscode#3684]
Environment: 
- OS: macOS 10.15.7
- VS Code: 1.92.2
- julia-vscode: >= 1.82

Issue summary:
The julia language server starts using julia from juliaup channel "release", not respecting the default channel set by `juliaup default`. If the "release" channel does not exist, a window pops up with the message 
`You must have the "release" channel in Juliaup installed for the best Julia experience in VS Code.`, and the language server won't work consequently.

Expected bahavior:
The julia-vscode extension should respect juliaup's default channel, as previous versions(e.g., 1.79.2) did.

**Comment by davidanthoff** [comment]
So this is on purpose, it makes it much easier for us to develop the LS. But note that it will still extract information from packages etc using the Julia version that is set as a default. 

There should be no visible impact on users from this choice, other than that the release version must be installed.
