### ISSUE TITLE
Cannor run @run more than once

### ISSUE THREAD

**Issue by joa-quim** [julia-vscode/julia-vscode#3714]
This has been discussed in the Forum too and on a quick look I haven't find an issue reporting it. Basically the second run of ``@run cmd...`` stalls. This brings the usability of the debugger to very close to zero.

**Comment by graidl** [comment]
I confirm this behavior. The Julia REPL always needs to be restarted to allow `@run cmd` to work again.

**Comment by arvedjo** [comment]
Same here

**Comment by ufechner7** [comment]
Seams to be fixed in the latest pre-relase version.

**Comment by joa-quim** [comment]
Yep, closing this.´Thanks again for this very important fix.
