### ISSUE TITLE
Add option for the number of threads the the julia REPL should use

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/julia-vscode#399]
That should end up setting the env var ``JULIA_NUM_THREADS``.

**Comment by ZacLN** [comment]
for ref. this is whats needed in the vscode settings, I'll add a gui menu to change it
```
"terminal.integrated.env.linux": {
        "JULIA_NUM_THREADS": "8"
    }
```

**Comment by ZacLN** [comment]
I'm slightly stumped, I've got a function: 
```
function changeThreads() {
    vscode.window.showInputBox().then((n) => {
        vscode.workspace.getConfiguration('terminal.integrated.env.linux').update('JULIA_NUM_THREADS', n, true)
    })
}
```
but it won't actually change the setting

**Comment by KristofferC** [comment]
It needs to be set before julia launches. Is that the case?

**Comment by ZacLN** [comment]
Yeh thats true, but this is a typescript issue where the command doesn't actually do anything (i.e. change `settings.json`

**Comment by davidanthoff** [comment]
Has been shipping for a while.

**Comment by EvaJanouskova** [comment]
> for ref. this is whats needed in the vscode settings, I'll add a gui menu to change it
> 
> ```
> "terminal.integrated.env.linux": {
>         "JULIA_NUM_THREADS": "8"
>     }
> ```

Btw, the above only changes the variable for use in the terminal, not in REPL. If you want this to be changed to have an effect in REPL, you need to add in the vscode settings the following:
```
"julia.NumThreads": "auto",
```
for Julia v1.7+ or a number instead of "auto" for earlier julia version.
