### ISSUE TITLE
∇' incorrectly highlighted

### ISSUE THREAD

**Issue by marius311** [julia-vscode/julia-vscode#404]
This is the same issue that Juno had here https://github.com/JuliaEditorSupport/atom-language-julia/issues/103, basically the `'` in `∇'` appears to be incorrectly interpreted as the beginning of a string rather than transpose. 

I'm seeing this with vscode 1.18.1 and julia-vscode 0.8.0.

**Comment by davidanthoff** [comment]
Hm, I think I copied the Atom grammar 14 days ago over, and this was fixed in Atom 20 days ago, so I'm slightly confused why this wouldn't be fixed already. But thanks for reporting, we'll look into it!
