### ISSUE TITLE
Unable to use REPL if terminal executes custom login using tmux

### ISSUE THREAD

**Issue by kdheepak** [julia-vscode/julia-vscode#426]
I have to following set to my code-shell. My settings.json has the following 

```json
{
  "terminal.integrated.shell.osx": "/Users/$USER/local/bin/code-shell",
}
```

with the `code-shell` script set as below:

```bash
#/bin/zsh
SESSION="vscode`pwd | md5`"
tmux $@ attach-session -d -t $SESSION || tmux $@ new-session -s $SESSION
```

This allows me to use tmux inside the terminal in vscode. 

However, `vscode.window.createWindow` [in this file](https://github.com/JuliaEditorSupport/julia-vscode/blob/6efc48a1c4ffc06e2c27d06f31301ada91af0303/src/repl.ts#L135) does not seem to run the `julia` command to start a REPL.

Does some command need to be added to be added to `code-shell` when it is starting or is there some other way to send a command to the terminal that should be used in this extension? I looked at the command line arguments passed to `code-shell` but did not find this `julia` command line to start the REPL.

**Comment by davidanthoff** [comment]
> However, vscode.window.createWindow in this file does not seem to run the julia command to start a REPL.

I don't follow. ``vscode.window.createTerminal("julia", g_settings.juliaExePath, ['-q', '-i', args, process.pid.toString()])`` runs the julia binary and links it to a new terminal window in VS Code.

What behavior would you like to see instead?

**Comment by kdheepak** [comment]
I see, I think I misunderstood what was going on. Please ignore the part where I linked to your code from this extension. 

Expected behavior:

Option 1:

CMD + SHIFT + P -> Start REPL -> Open Julia REPL in TMUX session

Option 2:

CMD + SHIFT + P -> Start REPL -> Open Julia REPL in new terminal 

Current behaviour:

CMD + SHIFT + P -> Start REPL -> Terminal restarts TMUX session.

**Comment by davidanthoff** [comment]
Hm, I'm not sure what to do about this... The whole shell integration in VS Code is a bit of a mystery to me...

**Comment by pfitzseb** [comment]
Probably fixed nowadays. You can use the integrated tmux support or `Julia: Connect to external REPL` if necessary.
