### ISSUE TITLE
Allow the user to produce clickable links

### ISSUE THREAD

**Issue by kafisatz** [julia-vscode/julia-vscode#428]
I have some Julia code which produces output files (say PDF, Excel, CSV …).
Is there any way I can produce a clickable link in the terminal in VSCode that will open said file with my default application (given the extension)? 
Personally, I am using Windows.
I can see that some of the built-ins (errors, stacktrace) do this, but I don’t know how to replicate it.

Right now I have ```println, @show, info``` and similar statements which simply show the file path (which I can then copy & past). A (CTRL) clickable link would be great…

**Comment by yongheekim-dev** [comment]
Currently full filepath automatically become clickable link. But It opens on vscode 
And ```run(`cmd /C start $(yourfile)`)``` open that file on windows default program.
```julia
julia> path = "C:/Windows/notepad.exe"
"C:/Windows/notepad.exe" #it's clickable if this file exist.

run(`cmd /C start $path`)
```
