### ISSUE TITLE
Disabling the plot pane

### ISSUE THREAD

**Issue by mcruas** [julia-vscode/julia-vscode#463]
Is it hard to implement an user option to choose if the plot will be displayed on the plot plane or not?

In my experiments, I often have big plots and having them in a pane is a real problem. Other possibility would be having a button to show the plot (which is in a pane) be displayed in a popup window, just like in RStudio.

**Comment by davidanthoff** [comment]
There are various options: we could add a config setting for this (i.e. to disable the plot pane entirely), we could add two function that folks can call from the REPL (``disable_vsc_plot_pane`` and ``enable_vsc_plot_pane`` or something like that) or we could go with the button option. I think the first two would be very straightforward, the button might be a bit more complicated.

A less convenient option that should work now already is to just remove the vscode display backend from the julia display stack. Take a look at https://docs.julialang.org/en/stable/stdlib/io-network/#Multimedia-I/O-1, it pretty much describes how the display infrastructure works.

**Comment by mcruas** [comment]
Thank you for your answer! 

Digging a bit on the documentation that you sent I could find the function named popdisplay(), which takes the vscodeserver.InlineDisplay out of the display stack, as desired.

**Comment by NightMachinary** [comment]
And `pushdisplay(Main._vscodeserver.InlineDisplay())` reenables it.

**Comment by pfitzseb** [comment]
There's a setting for this now.
