### ISSUE TITLE
Wrong execution with a transpose `'` with OhMyREPL

### ISSUE THREAD

**Issue by rawlik** [julia-vscode/julia-vscode#494]
Executing for example `x = collect(1:3)'` with `^ENTER` executes `x = collect(1:3)''` when OhMyREPL is used.

Similarily, but less harmfull, executing `2(` executes `2()`.

I guess this has to do with OhMyREPL's automatic closing of quotes and parenthesis.

**Comment by KristofferC** [comment]
This is when pasting into a Windows console?

**Comment by rawlik** [comment]
This is on macOS. When command `Julia: Execute Code` is invoked, the code appears to be pasted into the julia-vscode's REPL pane.

**Comment by KristofferC** [comment]
Sorry I didn't look what repo we were in. The code should be sent to the terminal with the "bracket paste" ansi codes.

**Comment by ZacLN** [comment]
Hi, I'm not quite sure what that means- could you give me a bit more info?

**Comment by KristofferC** [comment]
The code should be written to the REPL stream as

```
\e[200~code\e[201~
```

where `code` is the code to execute. This was the Julia REPL realizes this is a paste and not someone typing the code in by hand.

**Comment by KristofferC** [comment]
ref https://cirw.in/blog/bracketed-paste

**Comment by ZacLN** [comment]
ta
