### ISSUE TITLE
only parse `new` as a keyword when it is inside a struct

### ISSUE THREAD

**Issue by Roger-luo** [julia-vscode/julia-vscode#498]
new can be assigned outside a `struct` like

```julia
new = 2
``` 
It only has meanings when it is inside a `struct`. Will it be possible to parse it only in `struct`?

**Comment by ZacLN** [comment]
Do you mean in terms of the highlighter?

**Comment by Roger-luo** [comment]
currently, if you type new in a `struct` it will be hightlighted to blue, which is fine. But if you type if outside of `struct` it is highlighted to blue too, which should not. because you can use `new` as a variable name outside `struct`. The behavior of current highlighting strategy might be wrong.

**Comment by ZacLN** [comment]
We're dependent on  https://github.com/JuliaEditorSupport/atom-language-julia/blob/master/grammars/julia.cson for highlighting so I'd suggest opening an issue there. My suggestion would be to remove `new` from highlighting entirely: in use it is called so is highlighted as such and keyword highlighting is redundant.

```julia
new 
struct A
new()
end
```
