### ISSUE TITLE
cursor does not respond to arrow keys after plotting

### ISSUE THREAD

**Issue by IgorDouven** [julia-vscode/julia-vscode#523]
Downloaded the latest version of VSCode (1.25) and updated the julia extension. When I create a plot and place the plot pane next to the editor window, I seem unable to get back the control of the cursor in the latter via the arrow keys. That is, when I hold down the cmd or ctrl keys, the cursor does respond to the arrow keys, but only then. Am I overlooking something or is this a bug?

Also, is there a way to keep the plot pane fixed next to the editor? After I have placed it there, creating a new plot puts the pane back where it appeared at first (so not leaving the editor window visible).

**Comment by davidanthoff** [comment]
That looks like a bug, most likely in VS Code, hard to imagine how we could be messing that up...

We've reworked how the plot pane works on master and I think that will fix the issue about the placement.

**Comment by IgorDouven** [comment]
Thanks David. I noticed that if I don't reposition (and resize) the plot window and just go back and forth between the plot tab and the editor tab, all is fine. Nevertheless, would be nice to have the two side by side.

**Comment by IgorDouven** [comment]
This is not the problem I'm having. If I'm not repositioning the plots pane, everything is fine -- I can then go back to the tab with the code and the arrow keys work normally. But if I do reposition the plots pane -- so I can see code and plot side by side -- then I can still switch the focus back to the code, but now the arrow keys are no longer responding. What's worse, that remains the case if I close the plots pane, essentially meaning I have to restart VSCode.

**Comment by atranel** [comment]
I have also problem. I run my Julia script and suddenly I cannot use arrow keys or Del.

**Comment by davidanthoff** [comment]
@atranel Is this with the shipping version of the extension, or the beta? We have reworked the whole plotting pane for the beta, so hopefully this might just be solved there...

**Comment by atranel** [comment]
I have problem with new 0.11-beta2 + Julia 1.0.2. I don't have this issue with stable branch 0.10.3 + Julia 0.64. Interestingly, new 0.11-beta2 while using Gadfly will open plot in browser instead of Plot pane of VS Code, but same script in 0.10.3 will plot it in Plot pane.

**Comment by davidanthoff** [comment]
Interesting... I'll have to investigate.

The Gadfly issue is because Gadfly now [pushes](https://github.com/GiovineItalia/Gadfly.jl/blob/3483498410a44a11512f1587bc9d91333d887b69/src/Gadfly.jl#L58) its own display to the stack when you load it, thus giving that preference over the VS Code plot pane. I think that is essentially a bug in Gadfly...

**Comment by pfitzseb** [comment]
Fixed nowadays.
