### ISSUE TITLE
Add config to set number of threads used by julia process

### ISSUE THREAD

**Issue by kafisatz** [julia-vscode/julia-vscode#527]
I understand that I can do `set JULIA_NUM_THREADS=4` in cmd in the location of julia.exe.
This works as long as  I use cmd (notably it does not work with Powershell, why?)

However, if I invoke a julia process in vs-code I seem stuck with 1 thread. Any ideas?

**Comment by cstjean** [comment]
I have `export JULIA_NUM_THREADS=8` in my `.bashrc`, and interestingly, running "Julia: start REPL" has `ENV["JULIA_NUM_THREADS"]` of 1, but if instead I `Open New External Terminal` (cmd-shit-c) and launch julia from there, it's 8.

FWIW, I'm running over ssh

**Comment by davidanthoff** [comment]
We actually have a setting at this point for the extension called `NumThreads`, and that overrides anything you might have configured outside of VS Code. So you just need to set that setting.

Having said that, it would probably be nicer if the VS Code setting by default was empty, and in that case any externally set value for `JULIA_NUM_THREADS` would apply, and only if one actually configures a value in the extension would it override the env var.

**Comment by davidanthoff** [comment]
His is now implemented.

**Comment by NLaws** [comment]
Is there a way to set `JULIA_NUM_THREADS` for debugging Julia in VSCode? I have tried adding the following to my launch.json:
```
"env": {"JULIA_NUM_THREADS": 6}
```
```
"env": {"name": "JULIA_NUM_THREADS", "value": 6}
```
```
"environment": {"JULIA_NUM_THREADS": 6}
```
```
"environment": {"name": "JULIA_NUM_THREADS", "value": 6}
```

```
"osx": {
    "environment": [{"name": "JULIA_NUM_THREADS", "value": 6}]
}
```

**Comment by pfitzseb** [comment]
Yes, but you need to use the `julia.NumThreads` setting.

**Comment by petrposik** [comment]
Excuse me, could you elaborate?
My `julia.NumThreads` is set to 4.
When I run Julia REPL and execute `Threads.nthreads()`, I get 4.
But when I run a script that just prints `Threads.nthreads()` in debugger using F5 or Ctrl-F5, it prints `1`.
Any more detailed information appreciated. Thanks!

**Comment by pfitzseb** [comment]
Looks like that setting is not properly propagated to debugger processes then. Will fix.
