### ISSUE TITLE
String macros for multiline strings highlighting bug

### ISSUE THREAD

**Issue by rapus95** [julia-vscode/julia-vscode#530]
Seems that the highlighting of the string literal macros before multiline strings (`""" """`) doesn't work properly :/

**Comment by davidanthoff** [comment]
We routinely just copy the syntax highlighting from https://github.com/JuliaEditorSupport/atom-language-julia. So the next step here would be to figure out whether this also happens in Juno, and if it does, open an issue over there.

**Comment by pfitzseb** [comment]
This has been fixed sometime in the past two years.
