### ISSUE TITLE
Don't display a plot on plot pane

### ISSUE THREAD

**Issue by goropikari** [julia-vscode/julia-vscode#547]
Ubuntu 17.10
VSCode 1.28
julia-vscode latest master https://github.com/JuliaEditorSupport/julia-vscode/tree/0b06bb07d3f9b4e1f98bd23b0655f456169937c4
Julia 1.0.1
Plots.jl v0.20.5

When I plot with Plots.jl, the plot pane doesn't work.

After `using Plots`,  the topmost display-backend stack is `Plots.PlotsDisplay()` and second is `_vscodeserver.InlineDisplay()`.
So if I type `using Plots; popdisplay()` instead of `using  Plots`, it works correctly.

This problem doesn't occur on Julia 0.7.

**Comment by davidanthoff** [comment]
Alright, we've discussed this on Slack, and there is going to be a change in Plots.jl that will fix this eventually. I'll leave this issue open until things work again, but right now this is an upstream problem from our point of view.

**Comment by EricForgy** [comment]
Any news on this? Should we start looking for a workaround?

**Comment by davidanthoff** [comment]
I think Plots.jl has this fixed on ``master``. And then we just need to hope that the other plotting packages adopt the same fix :) I think that is the plan, so we probably just need to wait.

**Comment by duncanam** [comment]
@davidanthoff I have snagged the the Plots master version with Pkg, but I am still not seeing plots at all in VSCode. What are using in the meantime?

**Comment by davidanthoff** [comment]
@duncanam I think that must be a different issue, as far as I know the changes in Plots.jl have long been released. Can you provide more info what exactly you are doing, which backend, etc?

**Comment by duncanam** [comment]
> @duncanam I think that must be a different issue, as far as I know the changes in Plots.jl have long been released. Can you provide more info what exactly you are doing, which backend, etc?

As a simple example, this does not display anything in the plot pane:
```julia
using Plots
x = 1:10; y = rand(10); 
plot(x,y)
```
using both `gr()`, `pyplot()`, `plotly()` do not give me any plotting pane. I am executing via F5. If I execute this code in the REPL within VSCode, I get a plot pane in VSCode for `gr()` and `pyplot()`, and an empty (but existing pane) for `plotly()`. I am using Julia version 1.3.0, with `code` version 1.41.1, and `julia-vscode` version 0.13.1, on Arch Linux.

**Comment by davidanthoff** [comment]
If you execute via F5 the code runs as a script and you need to add `display` calls (e.g. `display(plot(...))`, that is just normal Julia behavior.

It does sound like there is a problem with plotly, could you open a new issue for that one?

**Comment by ataiya** [comment]
@davidanthoff what is the alternative to (F5) running as script?

**Comment by davidanthoff** [comment]
You can send individual lines via Ctrl+Enter to the REPL, and then the result of each line will be displayed in the REPL.

**Comment by micampbell** [comment]
> > @duncanam I think that must be a different issue, as far as I know the changes in Plots.jl have long been released. Can you provide more info what exactly you are doing, which backend, etc?
> 
> As a simple example, this does not display anything in the plot pane:
> 
> ```julia
> using Plots
> x = 1:10; y = rand(10); 
> plot(x,y)
> ```
> 
> using both `gr()`, `pyplot()`, `plotly()` do not give me any plotting pane. I am executing via F5. If I execute this code in the REPL within VSCode, I get a plot pane in VSCode for `gr()` and `pyplot()`, and an empty (but existing pane) for `plotly()`. I am using Julia version 1.3.0, with `code` version 1.41.1, and `julia-vscode` version 0.13.1, on Arch Linux.

did this ever work for you? I still can't figure out how to plot from scripts, but I can plot from the REPL

**Comment by davidanthoff** [comment]
Oh, things changed again a bit. If you run a file with F5 or Ctrl+F5 now there is simply no integration with the VS Code plot pane. That integration only exists in the REPL.

**Comment by micampbell** [comment]
good to know it's not just me. Thanks, David. You're doing great and important work!

**Comment by micampbell** [comment]
by the way, I do see an external "GKS Qt Term" window appear with the following script...
`using Plots`
`p=plot(rand(10))`
`display(p)`
`gui()`
`sleep(10)`
but it only last those 10 seconds, then closes (actually, it lasts a bit longer, but that's just the extra time it takes for the terminal to update after the debugger session

**Comment by davidanthoff** [comment]
So that extra window you see there is something that I think GR creates, or Plots? I believe that is unrelated to VS Code.

**Comment by cortinah** [comment]
Hello, any updates regarding being able to view plots when running a full Julia script via CTRL-F5 ?   Thank you very much.

**Comment by davidanthoff** [comment]
I don't expect us to do anything about this. I don't think we should load our VS Code integrations into Julia processes if someone starts an entire script externally.

The solution is to run your script inside the Julia REPL in VS Code, then all the integrations are there.
