### ISSUE TITLE
Handle environments

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/julia-vscode#552]
I have started working on that. The plan would be that one can pick an active environment per VS Code window. That environment then will be used for 1) new REPLs that are started, 2) test, build, doc runs etc. and 3) ideally the LS will pick it up as well.

I'm pretty much done with the UI work for selecting an environment, and have 1) almost done. I'll try to open a PR later today.

Just wanted to ping @ZacLN on this, so that you are aware that I have some code for this and we don't duplicate effort :)

**Comment by ZacLN** [comment]
Nope nothing done yet. I was just pondering how to handle this for the package cache

**Comment by davidanthoff** [comment]
I think we'll have to use something like [this](https://github.com/JuliaLang/Pkg.jl/blob/8bcfcbf094233c43489fc74426659219ecd9f8d9/src/Operations.jl#L807), maybe we can even reuse that function...

The problem is this: say we open a folder ``.julia\dev\Foo``, i.e. the dev folder for package ``Foo``. And say that folder is deved in the default environment. Say ``Foo`` has a dependency on ``Bar``, so that appears in its REQUIRE file (or its Project.toml, going forward). But ``Bar`` does *not* appear in the default environment. Then we can't just say ``using Bar`` to load the symbols from that, because ``Bar`` is not in the default environment. So what we need to do is actually run our symbol server process in a new, temporary environment where all the dependencies that ``Foo`` has are top level deps in this new, temporary environment. At that point we can run ``using Bar`` in the symbol server and load the stuff inside it... I think that is what the code I linked above to does for the testing case, but I'll need to look into that a little bit more...

**Comment by ZacLN** [comment]
Shouldn't the above case just give an error? 

I've a few other questions:
1 - I assume weare  planning to only handle environments installed in the default depot (i.e. load manifests from `.julia/environments/...`?
2 - are you saying we launch SymbolServer on demand, load modules if they're not cached, transfer across a pipe to LS, then close it?

**Comment by davidanthoff** [comment]
> Shouldn't the above case just give an error?

I would think it is the most common workflow for folks working on packages? Say I have a pristine julia install, I do ``]dev Foo`` and then open ``.julia/dev/Foo`` in VS Code. That should definitely work, right? And now say ``Foo`` has a dep on ``Bar``, and I do ``]add Bar#master``, then we would want the LS to pick up the symbols from ``Bar#master`` when we edit ``Foo``, right?

>  I assume weare planning to only handle environments installed in the default depot (i.e. load manifests from .julia/environments/...

Right now the UI gives access to the environments in the default location in the drop down, but also offers an option to open any arbitrary environment via a file open dialog. I was thinking that we might also want to add an option to automatically find any ``Project.toml`` file inside the workspace and show those as another option in the list of environments. But that can come later, I think.

> are you saying we launch SymbolServer on demand, load modules if they're not cached, transfer across a pipe to LS, then close it?

Yes, that is kind of what is happening right now. LS starts, then right now is starts a symbol server process, loads any package that is not yet cached into that symbol server, then kills the symbol server process. The transfer between the symbol server and LS is happening via STDOUT. I think we can tweak the lifetime of the symbol server as we go along, in particular it should be possible to not ever start a symbol server process if everything is already cached. The current API of SymbolServer.jl should make it possible to change that without any of the clients having to do anything.

**Comment by ZacLN** [comment]
Sorry I was confused by your first comment where you say `Bar` doesn't appear in the default environment, the above makes sense. Will we need a file watch within `StaticLint` to know when the `Project.toml` files have been changed?  (I don't think we want to spin up/communicate with it each time there's an attempt to `import` something not already available on the LS side)

**Comment by davidanthoff** [comment]
I'm also moving this to the backlog. There is still a lot we can do to improve things, but lets ship a version for now :)
