### ISSUE TITLE
Execute code cell

### ISSUE THREAD

**Issue by sdewaele** [julia-vscode/julia-vscode#560]
A feature that would allow execution of a code cell would be great to have. The feature is available in Matlab and Spyder. It means that the code block starting with a certain marker, e.g. `#%%` would be executed in the REPL. BTW - I am rather new to VS code, so perhaps this feature is already available.

**Comment by dgleich** [comment]
Just a quick note on this -- I use this feature extensively in the atom editor. Would love to see it in julia-vscode too so I can better evaluate a potential move. Here's one of the initial issues on the atom-julia-client for it. 

https://github.com/JunoLab/atom-julia-client/issues/63

If I get an itch to do something new at some point, I may take a closer look. 

Standard cell delimiters are: 

##
#%%

If I run into any others, I'll post them.

**Comment by davidanthoff** [comment]
Yes, very much on my radar! There are some changes in the pipeline over in VS Code itself that will make this scenario a heck of a lot more powerful, I think once that lands (hopefully soon) I'll take a stab at this.

**Comment by sdewaele** [comment]
Thanks for implementing this! (same as #777)
