### ISSUE TITLE
Autocompletion for the field names of a struct?

### ISSUE THREAD

**Issue by x-ji** [julia-vscode/julia-vscode#601]
This would greatly enhance productivity and reduce errors IMO. The linter doesn't catch errors of trying to access nonexistent fields either.

In this issue: https://github.com/JunoLab/atom-julia-client/issues/310 it's suggested that the language server might be able to provide field name autocompletions, but it doesn't seem to be there at the moment?

**Comment by ZacLN** [comment]
This is dependent on extensive type inference, which I'm working on
