### ISSUE TITLE
Hover help issue

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/julia-vscode#604]
From discourse, on v0.11.0-beta.2:

> Once loaded, it is still not showing doc string from my own functions or functions from my own modules. It does not show PyPlot’s “plot” as undefined symbol anymore, but it only shows something like "PyPlot.LazyHelp[LazyHelp(PyObject(Ptr{PyObject_struct} @0x00000000224e23a8), (“plot”,))] for PyPlot functions.

**Comment by pfitzseb** [comment]
This is fixed.
