### ISSUE TITLE
Re-opening Go to symbol in file... is broken

### ISSUE THREAD

**Issue by lewisl** [julia-vscode/julia-vscode#640]
It doesn't work.  Sorry guys. Don't know what you are doing special.  I have Julia 1.0.3 installed and on my path.  I choose the command and only get "No symbol information  for the file".  

Julia Env in the status bar shows v1.0.  
By the way, this is a drop down that allows a choice of installed Julia environments.  v0.7 does in fact work.

But, never mind. Go to Symbol in file has not worked for me ever since v 0.6.

**Comment by lewisl** [comment]
So, the problem was that I had to create the Julia path executable explicitly--installation of the extension did not find it.  Julia IS in my $PATH environment variable.  Once I added: 
```
"julia.executablePath": "/Applications/Julia-1.0.app/Contents/Resources/julia/bin/Julia",
```
then it worked.  So, I suspect that it would actually have worked in 0.7, too.

So, maybe there is a problem with path parsing.

Also, VS Code's prettified settings editor doesn't allow editing of julia.executablePath  unless a value is already present.  If it has not been set, you must edit the json file to add this field.  Then, it appears.  I don't know if the extension has any control over it, but if so--it is not showing up.  

Generally, every conceivable customization field should have an entry even if the current entry is null valued.  Also, probably all of them should be editable in the prettified view--or the link to open the json file should appear as:
```
Edit in settings.json
```

Here is my $PATH variable:
```
/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/bin:/Applications/Julia-1.0.app/Contents/Resources/julia/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
```

Don't know that there is anything wrong with this?  It certainly lets me type julia in the Terminal and launch Julia v1.0.3 successfully.

**Comment by davidanthoff** [comment]
I'm not sure what is going on here... We do automatically search in that location (see [here](https://github.com/JuliaEditorSupport/julia-vscode/blob/d28bfe4c43e03a6c9340fc2187ac885eac4a2925/src/juliaexepath.ts#L31)), so my only explanation is that maybe just starting ``julia`` by itself (which we also try automatically, and that has higher priority than the hard coded path) might resolve to an older version of julia?
