### ISSUE TITLE
Ctrl-enter does not finish after encountering a multi-line code block

### ISSUE THREAD

**Issue by tk3369** [julia-vscode/julia-vscode#651]
Please see video at https://youtu.be/JGxSXr4lRfI

My environment:
```
julia> versioninfo()
Julia Version 1.0.1
Commit 0d713926f8 (2018-09-29 19:05 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, haswell)
Environment:
  JULIA_NUM_THREADS = 4
  JULIA_EDITOR = /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper
```

**Comment by davidanthoff** [comment]
I just tried to replicate this with the latest `master` version but can't, it executes the code after each block. Is this still an issue with the latest shipping version?

**Comment by davidanthoff** [comment]
Actually, I can replicate this on Mac, just not on Windows.

**Comment by davidanthoff** [comment]
I suspect this is related to the use of the escape sequences that @KristofferC introduced in https://github.com/julia-vscode/julia-vscode/pull/596. I'm not sure what to do about this.. @KristofferC, any idea?

**Comment by KristofferC** [comment]
Ctrl+Enter in vscode is bound to just paste the current line into the REPL (in contrast to all other interactive execution environments where ctrl+enter executes a block) So what is the expected behavior here?

**Comment by davidanthoff** [comment]
Actually, I have a solution: we just don't send the bracket stuff when we execute a single line, that fixes it.
