### ISSUE TITLE
Leave terminal window open (or at least capture the stacktrace) when julia has a fatal error.

### ISSUE THREAD

**Issue by twadleigh** [julia-vscode/julia-vscode#653]
The julia terminal closes when the julia process crashes. It would be useful to be able to see the stacktrace that gets dumped when this happens.

**Comment by twadleigh** [comment]
Cf. https://github.com/Microsoft/vscode/issues/70444

**Comment by davidanthoff** [comment]
Ah, cool! So if I understand that correctly they will add support for that in the next VS Code iteration in a month or so? In that case we should probably just wait, right?

**Comment by twadleigh** [comment]
It appears so. Analogous functionality already exists upstream but has been commented out.

**Comment by twadleigh** [comment]
Well, microsoft/vscode#70444 has been shelved, so it's back to the drawing board. That issue refers to Tasks as a potential way to satisfy one of the stated use cases. Don't know if that would help here...

**Comment by davidanthoff** [comment]
No, I don't think we can use tasks for our use case at all... And I don't really think there is anything we can do on our end, I think that just needs to be resolved on the VS Code side of things. Or at least I can't think of anything we could do...

**Comment by pfitzseb** [comment]
Closing in favor of https://github.com/julia-vscode/julia-vscode/issues/1788.
