### ISSUE TITLE
undeclared variable for macro declaration

### ISSUE THREAD

**Issue by Roger-luo** [julia-vscode/julia-vscode#664]
![image](https://user-images.githubusercontent.com/8445510/51232510-f3124280-19a1-11e9-97df-606f77b4331a.png)

**Comment by Roger-luo** [comment]
Update, this part is already registered as package. If you need it for debugging you can find it here:

https://github.com/QuantumBFS/BitBasis.jl/blob/master/src/bit_str.jl

**Comment by ZacLN** [comment]
fixed on master
