### ISSUE TITLE
intellisense for modules

### ISSUE THREAD

**Issue by sdewaele** [julia-vscode/julia-vscode#672]
Is it possible to enable intellisense for content of modules that are in the current path, but not in a package? Suppose I have created a module `MyModule` that defines a function  `myfunction`. When I use this module in a script, it would be great if I could get autocompletion/help/code navigation for it. I have added it to LOAD_PATH, even in `startup.jl`, but it is not detected by the plugin.

**Comment by davidanthoff** [comment]
I think it used to work for modules, so I would think that it should work again once we fix the julia 1.1 compat issues. But not sure, @ZacLN knows much more about that part of the extension than I :)

**Comment by sdewaele** [comment]
FYI - I encountered this issue using Julia 1.0.2.

**Comment by ZacLN** [comment]
Hi, if the module is not part of a package known by `Pkg` then you'll have to explicitly `include`the containing file, as you would when running a script. 

Using `startup.jl` files is another issue that does need to be addressed

**Comment by sdewaele** [comment]
Thanks! Unfortunately IntelliSense is still spotty. I have taken the following steps in Julia 1.0.1.1: 1) `generate` a package in the package manager, see code below; 2) create a git repo in the root dir of this package. 3) Registering it in package mode with `dev StijnPackage`. 4) Made some small changes (`export greet`, add a comment.  The package manager is aware of the package, see output below. In the console, I can use the package.

After this, I occasionally get IntelliSense for the package, oftentimes none. When I do, I get an old version. For example, the documentation I added below for `greet` does not show up, even when I commit the change to the repo. Do I perhaps need to trigger the plugin somehow to become aware of the change? 

```
module StijnPackage

export greet

"greet user"
greet() = print("Hello World!")

end # module
```
In package mode:
```
(v1.0) pkg> status
    Status `C:\Users\marionstijn\.julia\environments\v1.0\Project.toml`
  [f2e7f880] MatrixExponential v0.1.0 [`..\..\..\source\MatrixExponential`]
  [295af30f] Revise v1.0.2
  [697ea9e2] StijnPackage v0.1.0 [`..\..\..\source\StijnPackage`]
  [fce5fe82] Turing v0.6.8
```

**Comment by sdewaele** [comment]
Any thoughts on this? Perhaps Am I missing a step here?

**Comment by sdewaele** [comment]
I am glad to say that after upgrading to v0.11.5 and using the latest VScode release (1.33.0-1554390824), I am now getting reliable IntelliSense when using the `dev MyModule` approach. This is great progress and and a workable method for me. Unless you still plan the enable IntelliSense for modules in the `LOAD_PATH`, I am fine with closing this issue.

**Comment by davidanthoff** [comment]
Great! I think lets close it for now, and if we revisit the `LOAD_PATH` situation we'll just have to make it work there as well.

**Comment by sdewaele** [comment]
I actually continue to have issues with this. Sorry to come back to it. The reason is that I think good intellisense really improves productivity. Could you perhaps briefly explain how the plug-in finds the packages for intellisense? E.g. is it related to the Julia env that is mentioned in the status bar (BTW - is there a way to set it automatically, I have to reset it manually at every start up). Do the packages have to reside in a specific directory?, etcetera.

Any insight in this would be appreciated!

**Comment by davidanthoff** [comment]
Try out the new beta we have for v0.12.0, [here](https://github.com/julia-vscode/julia-vscode/releases)! I think it greatly improves the story on this front. In particular, IntelliSense will now use the active Julia environment, which you can set in the status bar. The active environment also gets stored between sessions, so no annoying resetting it. Any feedback on whether this new version solves your main issues would be especially appreciated.

I'm going to close this issue for now. Ideally, if you come across problems with the beta, just open a new issue!

**Comment by sdewaele** [comment]
Thanks, looking forward to it!

I've tried to test using the linked VSIX, but for some reason intellisense is not working at all (i.e., it won't autocomplete `println` etc, only shows text-based completions (abc), no linting. The plug-in is showing as installed, and I can start the console. I am using VS code v.1.35.1. May just be that I have not properly installed it. I'll wait for the official v0.12.0 to come out.

**Comment by sdewaele** [comment]
Unfortunately, I have to come back to this once more... I am seeing exactly the same issue as I described above, where the intellisense is based on the code in the package at the time when I do `dev` for the very first time. It does not change after that. So, I can only conclude that the IntelliSense uses some __cached version of the package__ somewhere. It would be great if someone could explain where the IntelliSense keeps the code that it uses. Is there a way to debug this?

**Comment by sdewaele** [comment]
I declared victory too early. I continue to have the issue, on multiple computers, both Linux and Windows, with the latest version of Julia (1.1.1), VS Code (1.37) , and plugin (0.12.0). Based on my experience, it must be the case that the plugin keeps a separate version of my package from which it gets the IntelliSense info. Therefore, I repeat my question:

What steps do I need to take to trigger the plugin to use the latest, current version of my package for IntelliSense?

Or, put in another way:
It would be great if you could give a step-by-step description of how to create a package, get IntelliSense on it, the -importantly - make a change, and get intellisense on the change. I think I follow the recommendations in my quoted reply below (`dev` trick), but that does not work.

Does it have to do with using Revise in a certain way? Commits to git? Location of the code (I prefer to use a location of my own choice...)?

> Thanks! Unfortunately IntelliSense is still spotty. I have taken the following steps in Julia 1.0.1.1: 1) `generate` a package in the package manager, see code below; 2) create a git repo in the root dir of this package. 3) Registering it in package mode with `dev StijnPackage`. 4) Made some small changes (`export greet`, add a comment. The package manager is aware of the package, see output below. In the console, I can use the package.
> 
> After this, I occasionally get IntelliSense for the package, oftentimes none. When I do, I get an old version. For example, the documentation I added below for `greet` does not show up, even when I commit the change to the repo. Do I perhaps need to trigger the plugin somehow to become aware of the change?
> 
> ```
> module StijnPackage
> 
> export greet
> 
> "greet user"
> greet() = print("Hello World!")
> 
> end # module
> ```
> 
> In package mode:
> 
> ```
> (v1.0) pkg> status
>     Status `C:\Users\marionstijn\.julia\environments\v1.0\Project.toml`
>   [f2e7f880] MatrixExponential v0.1.0 [`..\..\..\source\MatrixExponential`]
>   [295af30f] Revise v1.0.2
>   [697ea9e2] StijnPackage v0.1.0 [`..\..\..\source\StijnPackage`]
>   [fce5fe82] Turing v0.6.8
> ```

**Comment by sdewaele** [comment]
I changed the location of my test package. What happens is that IntelliSense continues to refer to the old, no longer existing, file location of the package. To me this seems to be further evidence that the plugin keeps its own, outdated, database of packages. Or is there another reason?

Any insight is much appreciated!
