### ISSUE TITLE
Use of possibly undeclared variable in test folder

### ISSUE THREAD

**Issue by cedeerwe** [julia-vscode/julia-vscode#680]
Hey,

since I started using the Julia extension in vscode, the `test` folder in my package is full of `Use of possibly undeclared variable`. All the `using` statements have underlined packages, e.g.,
 
![selection_001](https://user-images.githubusercontent.com/11530208/53486327-b3527680-3a88-11e9-9641-839964913a92.png)
This leads to all the exported function names to be marked as undeclared as well. In total I have 600+ such errors and it's starting to be kinda annoying.

My issue seems to be similar to this https://github.com/JuliaEditorSupport/LanguageServer.jl/issues/172, but it happens before the includes (which are not even programmatic in my case). I am running 
`Ubuntu 18.04` with code `1.31.1`, julia extension `0.11.4` and julia `1.1`, although I am encountering the same issues since `julia 1.0` and whatever version of `vscode` & its extension was around in December.

**Comment by cedeerwe** [comment]
As a side note, one possibly fix this using https://github.com/JuliaEditorSupport/julia-vscode/issues/552 - the code in the `test` folder does not seem to be aware that it is in the environment defined by `src`

**Comment by ZacLN** [comment]
I believe this was due to SymbolServer not making those (stdlib) packages available correctly, this should be fixed on master - could you check?

**Comment by cedeerwe** [comment]
Looks good!

**Comment by davidanthoff** [comment]
Great, then I can close this?
