### ISSUE TITLE
alt-click to jump to file fails if there is a space in the path

### ISSUE THREAD

**Issue by dlfivefifty** [julia-vscode/julia-vscode#684]
If I have a file path (say due to a stack trace or `@which`) with a space in the name, I can't alt-click to jump to the location.

**Comment by davidanthoff** [comment]
Unclear to me whether we can do anything about this, the whole clicking on filenames in the REPL is handled by VS Code.

Would be great if someone could research whether there are some options in VS Code to solve this!

**Comment by ChrHorn** [comment]
Seems to be a known issue upstream, https://github.com/microsoft/vscode/issues/21125 for reference.
