### ISSUE TITLE
Use of possibly undeclared variable in nested comprehensions

### ISSUE THREAD

**Issue by cedeerwe** [julia-vscode/julia-vscode#685]
Hey,
it seems that the linter is not able to recognize variables defined in nested comprehensions, MWE: 
![selection_003](https://user-images.githubusercontent.com/11530208/53940580-51ac9080-40b6-11e9-8aac-53cf5322292c.png).
gives `Use of possibly undeclared variable: i`. It's not a big problem, appears just a few times across our codebase, but would be nice to have it fixed.

**Comment by ZacLN** [comment]
Should be fixed by https://github.com/julia-vscode/StaticLint.jl/commit/f01ea000739c3c7d308b78da128f9b3c3b77399d
