### ISSUE TITLE
Function names are not shown with Shift+Ctrl+O

### ISSUE THREAD

**Issue by joa-quim** [julia-vscode/julia-vscode#703]
The ``Shift+Ctrl+O`` combination shows the symbols in a file, but it now doesn't show the function names. Just the variable names + the function names where they are declared.

**Comment by ZacLN** [comment]
Hi, could you elaborate on this a bit? You say it both does and doesn't show the function names for the file

**Comment by joa-quim** [comment]
Well, if you try you'll see what I mean. It does show the function names but do not distinguish them from variable names, so what we see is a long list of symbols and it's hard (very) to identify which of those correspond to functions.

**Comment by ZacLN** [comment]
Correct-ish symbols for bindings of different kinds (e.g. functions, strings, etc.) have been added
