### ISSUE TITLE
Undefined Variable for closure 

### ISSUE THREAD

**Issue by Roger-luo** [julia-vscode/julia-vscode#707]
found this when defining Zygote adjoints

```julia
Zygote.@adjoint function LinearAlgebra.tr(x)
    tr(x), function (Δ)
         # blabla
    end
end
```

`Δ` is undefined here

version: 0.11.5

**Comment by ZacLN** [comment]
In this instance it's a failure to bind arguments of nameless functions, unrelated to the macro (though we don't expand macros).

**Comment by ZacLN** [comment]
Fixed on master (specifically by https://github.com/julia-vscode/CSTParser.jl/commit/8f031559558b9118f28270a3bbb72e44b15b2d4e)
