### ISSUE TITLE
Use of possibly undeclared variables using JuMP

### ISSUE THREAD

**Issue by Dx-Wang** [julia-vscode/julia-vscode#708]
Hello,

I get lots of "Use of possibly undeclared variable" warnings in VS code when using `@constraint` and `@variable` provided by JuMP.

![image](https://user-images.githubusercontent.com/6644934/55828639-b8600800-5ac1-11e9-87f5-244489de9df9.png)

OS: Windows 10
Julia: v1.1.0
VS Code Julia extension v0.11.5

**Comment by KristofferC** [comment]
https://github.com/JuliaEditorSupport/julia-vscode/issues/694
https://github.com/JuliaEditorSupport/julia-vscode/issues/657

**Comment by ufechner7** [comment]
Bump.

**Comment by davidanthoff** [comment]
This will take a while, we don't yet know how to solve this.

**Comment by ZacLN** [comment]
https://github.com/julia-vscode/StaticLint.jl/pull/72, let me know if there are cases I've missed
