### ISSUE TITLE
undefined variable for operators

### ISSUE THREAD

**Issue by Roger-luo** [julia-vscode/julia-vscode#714]
operators can be overloaded as

```julia
function(a::AbstractVecOrMat * b::AbstractVecOrMat)
    # blabla
end
```

which is not correctly parsed in vscode, thus `a` and `b` is undefined

**Comment by davidanthoff** [comment]
Wow, I didn't even know that this is valid syntax! Is that described in the docs somewhere?

**Comment by Roger-luo** [comment]
I'm not sure where's it in docs. And I don't like to use it very much either (since I usually follow YASGuide and add the module name to anything I overload).

But I believe @MikeInnes use them a lot in his packages... like Zygote.

**Comment by ZacLN** [comment]
I think this is due to the surrounding parentheses, should be straightforward to fix

**Comment by ZacLN** [comment]
fixed here: https://github.com/julia-vscode/CSTParser.jl/commit/1ff493227a28c5aa5210d9eff0b2634959a05fa3
