### ISSUE TITLE
The reformatter swallows escaped \ characters

### ISSUE THREAD

**Issue by PeterLuschny** [julia-vscode/julia-vscode#715]
[Julia 1.1, Windows]

Original:
"""
``\\sum_{m=1}^{n-k+1} \\binom{n-1}{m-1}`` 
"""

After formatting:
"""
``\sum_{m=1}^{n-k+1} \binom{n-1}{m-1}`` 
"""

Result:
ERROR: LoadError: syntax: invalid escape sequence

The docs say:
The \ character should be escaped appropriately if the text is embedded in a Julia source code, for example,  "``\\LaTeX`` syntax in a docstring."

**Comment by ZacLN** [comment]
Closing this in favour of https://github.com/julia-vscode/DocumentFormat.jl/issues/32
