### ISSUE TITLE
Renaming a struct property with (F2) does not work

### ISSUE THREAD

**Issue by mahdizakizadeh** [julia-vscode/julia-vscode#717]
When I'm trying to change a struct property name it does not work properly 

Here is an example
```julia
struct Foo
    property_a::Int64
    property_b::Int64
end

function bar(f::Foo)
    f.property_a == 0 && dosomething()
end
```
If you try to change name of `property_a` (to something like `property_c`) it does not change the name in function `bar`, in my case cursor is in middle of `property_a` name in struct `Foo`

Also, if you try to change the name in function `bar` it does not change anything at all

**Comment by ZacLN** [comment]
This will now (though only where all instances of `Foo` are inferred)
