### ISSUE TITLE
Tab completion sequence 

### ISSUE THREAD

**Issue by kotorana** [julia-vscode/julia-vscode#753]
Issue Type: <b>Bug</b>

d\^2 doesn't work "Superscript numbers" in VS code also emojis like (\:turtle: TAB) in VS code

Extension version: 0.11.6
VS Code version: Code 1.35.0 (553cfb2c2205db5f15f3ee8395bbd5cf066d357d, 2019-06-04T01:16:40.241Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_off<br>flash_stage3d: unavailable_off<br>flash_stage3d_baseline: unavailable_off<br>gpu_compositing: unavailable_off<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ZacLN** [comment]
https://github.com/julia-vscode/LanguageServer.jl/commit/686d5881b568d6c6172fb347194b28c3eda9f734
