### ISSUE TITLE
Warn on writing loop header as `for i in length(x)`

### ISSUE THREAD

**Issue by KristofferC** [julia-vscode/julia-vscode#760]
A loop that looks like

```
for i in length(x)
    ...
end
```

is almost always a bug where the user meant to write `1:length(x)`. Perhaps it can be linted?

**Comment by ZacLN** [comment]
Yep that's a sensible check, I'll check against Number literals as well

**Comment by ZacLN** [comment]
Added https://github.com/julia-vscode/StaticLint.jl/commit/f9fae1342a00dc613bde16557680a78806bb7dce and 
https://github.com/julia-vscode/LanguageServer.jl/commit/eed6f2fc1f2ea67a8da838443d1a89f84a44138e
