### ISSUE TITLE
Add send to terminal feature

### ISSUE THREAD

**Issue by musm** [julia-vscode/julia-vscode#764]
I'd like to  ‘send to terminal’ the current file or lines from the file instead of it using the integrated terminal.  There are still a lot of cases where I find an external terminal more useful.

**Comment by davidanthoff** [comment]
Is there maybe already a VS Code built in command for that? I'm not sure, but worth looking around.

**Comment by tshort** [comment]
`Terminal: Run selected text in active terminal`. I've used it a lot when ssh'ing elsewhere (and may not need that anymore with the remote capabilities that just came out).

**Comment by musm** [comment]
But that always ends up sending it to the integrated terminal.

I was hoping it would be possible to have a shortcut that sends the code to an external terminal.

**Comment by musm** [comment]
I guess I would also be happy with https://github.com/microsoft/vscode/issues/34442

**Comment by davidanthoff** [comment]
Alright, I think this looks more like something that should be solved in VS Code itself, and not in the Julia extension? So I'm going to close this here.

**Comment by musm** [comment]
yep sorry for the noise
