### ISSUE TITLE
Ctrl-C doesn't interrupt Alt-Enter code

### ISSUE THREAD

**Issue by cchderrick** [julia-vscode/julia-vscode#767]
When code are executed with `Alt-Enter`, `Ctrl-C` is unresponsive.

To test it:
```julia
N = 20_000

# Alt-Enter busy loop
begin
    M = zeros(Float64,16,16)
    for k = 1:N
        M[:] = rand(Float64,16*16) 
        inv(M)
        println(k)
    end
end
```
If you `Ctrl-C` while the code block is running, you will occasionally see `^C` and the Julia prompt, but the process will continues.

```julia-repl
...
19873
19874
19875
julia> 
^C

julia> 
19878
19879
19880
...
```

**Comment by cchderrick** [comment]
Got thinking from [this discussion](https://discourse.julialang.org/t/vs-code-extension-v0-12-0-beta-release/25420/44`)

It turns out, when you <kbd>F5</kbd> a script or `include("script.jl")`, <kbd>Ctrl</kbd> + <kbd>C</kbd> also does not interrupt the process.

| Action | Behavior when <kbd>Ctrl</kbd> + <kbd>C</kbd>|
|--------|----------|
| <kbd>Alt</kbd> + <kbd>Enter</kbd>| occasionally see `^C`|
|<kbd>F5</kbd>| occasionally see `^C`|
|`include("script.jl")`| Don't see `^C` at all|

**Comment by jespermartinsson** [comment]
This issue has kept me from updating and I am still running 0.11.6. If possible I would like to bump this issue to get higher priority if possible? I'm often in a situation where I'm printing results within a loop to REPL and I would like to break the loop by ctrl+c and look at the printouts.

**Comment by davidanthoff** [comment]
@jespermartinsson You can always execute code with Ctrl+Enter and interrupt that with Ctrl+C, even in the latest versions of the extension, I don't think anything has changed there. If you you need interrupt, just don't use Alt+Enter.

I hear you on wanting a solution for this, but I don't have an idea how we might be able to implement this...

**Comment by jespermartinsson** [comment]
@davidanthoff Thank you for your efforts and for a fast reply. I'm most likely doing something wrong or perhaps this is an Ubuntu 18.04 problem? I just upgraded to latest vscode 1.43.1 and I upgrade to Julia Language Support v0.15.18 to see if anything changed. If I execute the `Julia: Execute File` command in vscode I'm not able to interrupt a loop or able to get keyboard input to work, e.g., using `chomp(readline())`. This works perfectly in v0.11.6 but nothing happens after v0.12.0.

**Comment by davidanthoff** [comment]
Ah, yes, `Julia: Execute File` runs the code in a background task, not in the REPL task... Not clear to me right now how we can resolve that... As a workaround you could `include` the file at the REPL for now.

**Comment by jespermartinsson** [comment]
Thanks for the record quick reply. Do you know if there is a possibility to make a keyboard shortcut similar to `Julia: Execute File` but using something like `include(@__FILE__)` in vscodeish?

**Comment by davidanthoff** [comment]
I guess we could add something like that, but I think I'd first like to dig in a bit whether we can solve this properly.

**Comment by JamesKCS** [comment]
Any progress on this or possibility of increasing its priority?  This is a significant issue with my workflow, and the "just press ctrl+enter" solution doesn't work well because:

1. When I want to run a file (which is most of the time I want to run something), I need to select all before pressing ctrl+enter, (can be solved with a macro, but that should not be necessary), and 
2. The code itself changes depending on whether pressing ctrl+enter or alt+enter, since the include statements are different.

Does anyone have any tips on how to get around these issues for someone who needs to be able to interrupt often and wants to "run file", rather than executing specific bits of code or typing commands in the REPL?  Thank you!

**Comment by jespermartinsson** [comment]
I have the same workflow as you and the only option I have for now is to
downgrade to julia language server v0.11.6 (i.e. click on extensions ->
julia gear -> Install Another Version).

Den ons 9 sep. 2020 kl 05:40 skrev JamesKCS <notifications@github.com>:

**Comment by caseykneale** [comment]
Control-C doesn't work for me, can anyone share their Ctrl+C key binding so I can double check?

**Comment by pfitzseb** [comment]
This isn't expected to work until https://github.com/julia-vscode/julia-vscode/pull/1690 is merged.

**Comment by pfitzseb** [comment]
This works now.
