### ISSUE TITLE
`abc` word suggestion blocks Unicode completion

### ISSUE THREAD

**Issue by kapple19** [julia-vscode/julia-vscode#768]
In the image below, I am trying to get script T, and the annoying autosuggestion is stopping me.

It stops me from time to time from using Unicode symbols and is so annoying.

If I add `"editor.wordBasedSuggestions": false,` to `settings.json` then I can't have tab-completion at all.

Help please! In addition, sometimes Unicode tab-completion just stops working.

![image](https://user-images.githubusercontent.com/48305293/59820208-45e79000-936e-11e9-9cd0-f96e4ed36a8e.png)

**Comment by ZacLN** [comment]
Could you try the latest beta release to check if this is resolved? Ta

**Comment by kapple19** [comment]
Been a while... seems to be mostly fixed now, every now and then tab-completion disappears but returns soon after.
