### ISSUE TITLE
Spurious "Incorrect number of arguments" warnings

### ISSUE THREAD

**Issue by tkoolen** [julia-vscode/julia-vscode#769]
For example,

```julia
range(1, 10; length=5)
```

results in the warning. I've also seen this on my own functions, though I haven't been able to produce a minimal standalone code example.

**Comment by tkoolen** [comment]
Another case, where it's more obvious what's going wrong, is `typeof(3)`, which most likely fails because `typeof` is not a generic function.

**Comment by pjssilva** [comment]
Same here. The minimal example is
```julia
println(1, 2, 3)
```
Any `println` with more than two arguments triggers the warning.

**Comment by ZacLN** [comment]
Yep noted. I've disabled this temporarily on StaticLint,

**Comment by davidanthoff** [comment]
@ZacLN does this mean we can take it off the the v0.12.0 milestone because we have a temporary fix? I guess then it should go to the backlog?

**Comment by singularitti** [comment]
Same here. Example:
```julia
julia> x = "12231/2131"
"12231/2131"

julia> split(x, '/'; keepempty=false)
2-element Array{SubString{String},1}:
 "12231"
 "2131" 
```
<img width="277" alt="warning" src="https://user-images.githubusercontent.com/25192197/60933523-9298f980-a290-11e9-9532-f7d6b41550f8.png">

Using VSCode 1.36.1, extension 0.12.0-beta, Julia 1.1.1, and macOS 10.14.5.

**Comment by stakaz** [comment]
I have this for `DataFrame(a = a, b = b)` in julia 1.1 and version 0.13.1.

**Comment by ZacLN** [comment]
This is definitely fixed on LanguageServer#master so will be addressed in the next release

**Comment by davidanthoff** [comment]
Ok, then I'm closing this issue :)

**Comment by scimas** [comment]
This still seems to be a problem for some functions. Not sure if I should open another issue. Example:
```julia
using DelimitedFiles

readdlm("my_file.txt", ',', String, '\n', header=true)

readdlm("my_file.txt", ',', String, '\n'; header=true)
```
Both of these show the warning.

Here's a [link](https://docs.julialang.org/en/v1/stdlib/DelimitedFiles/#DelimitedFiles.readdlm-Tuple{Any,AbstractChar,Type,AbstractChar}) to the documentation of the function.

And a [link](https://github.com/JuliaLang/julia/blob/2d5741174ce3e6a394010d2e470e4269ca54607f/stdlib/DelimitedFiles/src/DelimitedFiles.jl#L175-L224) to the source code.

**Comment by davidanthoff** [comment]
Are you seeing these problems on `master` or in the currently shipping version?

**Comment by scimas** [comment]
Currently shipping version, 0.13.1.

**Comment by ZacLN** [comment]
@davidanthoff should we add a 'fixed pending release' tag to things like this and only close the actual issues on julia-vsxode releases?

**Comment by davidanthoff** [comment]
Yeah, that might be a good idea!

**Comment by norru** [comment]
Still open as of 2020-02-06?
