### ISSUE TITLE
alt+enter on last line crashes language server

### ISSUE THREAD

**Issue by merckxiaan** [julia-vscode/julia-vscode#772]
I just installed the beta release (v0.12.0-beta.1) and everything works great except using alt+enter on the last line of a file, this causes the language server to crash: `Connection got disposed.`

When there's a a blank line after the last line of code, `alt`+`enter` does actually work.

Here's my versioninfo:
```
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "C:\Users\username\AppData\Local\Programs\Microsoft VS Code\Code.exe"
```

**Comment by ZacLN** [comment]
I've pushed a [commit](https://github.com/julia-vscode/LanguageServer.jl/commit/d0b918c977c014f78457f2ad0aed5bac549b82a5) that should fix this. If it continues to error could you post some example code?
