### ISSUE TITLE
weird behavoir with block execution and semi-colon

### ISSUE THREAD

**Issue by cchderrick** [julia-vscode/julia-vscode#776]
Version: v0.12.0 beta

Observed behavior: 
<kbd>Alt</kbd>-<kbd>Enter</kbd> a line (or any code block) end with semi-colon `;`, it will also execute the next block of code too.

```julia
println("1");

begin
    println("2")
end
```
 This will print
```julia-repl
julia> 
1
2
```
Expected behavior?

In fact, if I <kbd>Alt</kbd>-<kbd>Enter</kbd> `println(3)` in the example below, it will print 1 and 2 too.
```julia
println("1");

begin
    println("2")
end;

println("3")
```

**Comment by ZacLN** [comment]
fixed: https://github.com/julia-vscode/LanguageServer.jl/commit/10c21ede278c4fe5928e064106d5b33dc814be11
