### ISSUE TITLE
No definition found for Array

### ISSUE THREAD

**Issue by kindlychung** [julia-vscode/julia-vscode#782]
I tried go-to-def on the following:

```jl
Array{Int, 3}(undef, 1, 2,3 )
Array{Int}(undef, 1, 2,3 )
```

**Comment by ZacLN** [comment]
fixed by https://github.com/julia-vscode/SymbolServer.jl/commit/23b4cd8f697449b2249e197df42f0455fa5c4aa1 and https://github.com/julia-vscode/LanguageServer.jl/commit/945bb4bb35544b117b935cefb6b2d1acca27403a
