### ISSUE TITLE
formatter deletes code

### ISSUE THREAD

**Issue by ChrHorn** [julia-vscode/julia-vscode#783]
Formatting the test case
```julia
function f(t::T) where {T}
    x = 123
end
```
results in
```julia
function f(t::T) where {T}
    x = 23
end
```
Version: 0.12.0-beta.2

**Comment by KristofferC** [comment]
Perhaps the formatter should do nothing if the AST after formatting changes?

**Comment by ZacLN** [comment]
fixed: https://github.com/julia-vscode/DocumentFormat.jl/commit/a5b7c976d43ad2136f80e89820de6ad1ff16db56

@KristofferC, perhaps but things would be less likely to be fixed as well

**Comment by KristofferC** [comment]
> @KristofferC, perhaps but things would be less likely to be fixed as well

I mean throw an error but not do the transformation. Silently corrupting code to get to maybe get some bug reports doesn't seem like a good idea.

**Comment by davidanthoff** [comment]
I think if we throw an error but don't make an edit in that case, it would come through our crash reporting, right? If it is just another LS crash, it should. That seems ideal: we hear about it, but nothing gets corrupted.

**Comment by ZacLN** [comment]
Yep that seems like a good idea
