### ISSUE TITLE
Issues with renaming

### ISSUE THREAD

**Issue by ChrHorn** [julia-vscode/julia-vscode#784]
Renaming mostly does not work for me. Sometimes it does the right thing, sometimes it does the wrong thing and sometimes it does nothing.

Test case:
```julia
struct S
    a
    b
    c
end
```
Renaming c will change b, renaming b will change a and renaming a will change S. There seems to be an off-by-one error in the code.

Version: 0.12.0-beta.2

**Comment by ZacLN** [comment]
fixed: https://github.com/julia-vscode/LanguageServer.jl/commit/8aa72648f9d169add19c25b5e5a304d70f5dd207
