### ISSUE TITLE
Using Julia in VS code

### ISSUE THREAD

**Issue by 00koeffers** [julia-vscode/julia-vscode#791]
I found this site by looking for the Q&As here (https://marketplace.visualstudio.com/items?itemName=julialang.language-julia&ssr=false#qna), so I hope this is the right place to ask my question.

Today I installed VS Code Version 1.36.1 for Windows 10. After that, I used this programm to install Julia 0.11.6. However, I cannot select Julia in the terminal, the only available option is "powershell".

Both, Julia and VS Code are installed in the folder C:\Program Files.

I tried changing the Julia path in the settings to the following values, all without an effect (even after restarting VS Code):
C:\Program Files\Julia\bin\julia.exe
C:\\Program Files\\Julia\\bin\\julia.exe
C:/Program Files/Julia/bin/julia.exe

When I use Atom, C:/Program Files/Julia/bin/julia.exe works. What is going wrong?

**Comment by josephmarturano** [comment]
Could you please try the following:

1. File -> New file
2. File -> Save -> "testfile.jl"
(make sure you include the .jl extension so VSCode recognizes the file as Julia code)
3. In the editor, type `print("hello world")`
4. Press Shift+Enter

What happens?

By the way, on my Windows machine I use the following Julia path: C:\Julia-1.1.0\bin\julia.exe

**Comment by perdigao1** [comment]
Hi,
I am having a similar problem.
I installed the Julia extension, but I can't see how to run the code, without debugging, it keeps asking for the debugger.
Joseph's suggestion worked. But what does Shift+Enter does? It seems that it runs a single line of code but documentation of VSCode has no information.
I found later that in File->Preferences->Keyboard Shortcuts there are some Julia specific bindings
Shift+Enter - Execute code cell
Ctrl+Enter - Execute code, but all code needs to be selected, and it will display code lines one by one while executing. Avoid it as it may be difficult to stop the slow execution.
F5 - Execute code. This seems to override the Menu option Debug -> Start Debugging. Which makes it confusing

So, to run code in Julia terminal (without debugging), press F5.

**Comment by 00koeffers** [comment]
@josephmarturano 
After saving the .jl file, the following Pop-up shows: "Could not start the julia language server. Make sure the configuration setting julia.executablePath points to the julia binary". However, this message is strange, since I know the path I type in is correct. If I copy it into the Windows Explorer and press Enter, Julia starts.
Also, the settings are correctly used in the file settings.json (I did not edit this file myself, it gets updated automatically if I change the path in the settings of the extension):
{
    "editor.renderControlCharacters": false,
    "julia.executablePath": "C:\\Program Files\\Julia\\bin\\julia.exe"
}

Shift+Enter does the same as just Enter: It starts a new line in the editor.
Ctrl+Enter does nothing.
When copying print("hello world") into the console (which still shows the "1:powershell" on the top right) and pressing enter, the message "Gerät PRN konnte nicht initialisiert werden." ("Device PRN could not be initialized.") shows.

EDIT: As I was writing this answer, I restarted VS Studio Code several times and suddenly it started working. The entry in the settings.json is now:
{
    "editor.renderControlCharacters": false,
    "julia.executablePath": "C:\\\\Program Files\\\\Julia\\\\bin\\\\julia.exe"
}
I cannot explain why here are so many backslashes, since I only put the double backslash (C:\\Program Files\\Julia\\bin\\julia.exe) in the extension settings (as I did before), but now it seems to work.

Thank you very much for your help!

**Comment by jake-diga** [comment]
I am running a somewhat similar issue on Julia VS code Extension. When I add it to docker and check it in vscode it is grayed out and can not be selected. 

Here is the command :

sudo apt-get update 
sudo apt-get install -y bsdtar 

mkdir -p /home/ubuntu/.local/share/code-server/extensions/julialang.language-julia-0.17.1 

cd /home/ubuntu/.local/share/code-server/extensions/julialang.language-julia-0.17.1 

curl -JL https://marketplace.visualstudio.com/_apis/public/gallery/publishers/julialang/vsextensions/language-julia/0.17.7/vspackage | bsdtar -xvf - extension

cd /home/ubuntu/.local/share/code-server/extensions/julialang.language-julia-0.17.1/extension/

mv * ../ 
chown ubuntu:ubuntu /home/ubuntu/.local/share/code-server/
