### ISSUE TITLE
Avoid printing code when running with ctrl+enter

### ISSUE THREAD

**Issue by ErwanPiR** [julia-vscode/julia-vscode#805]
Hi,

I wonder if there is a way to launch a code block with Ctrl+Enter without printing in the REPL all the lines of the code ?

When you run a large number of lines, it's quite annoying to have all the lines printed in the REPL.
For example the default rule in Atom is to just print the output of the run.

I search in the parameters but I didn't find anything to change this but maybe I miss something...

Thanks for your answer.

**Comment by davidanthoff** [comment]
That won't work with Ctrl+Enter because it literally sends the code to the REPL, but try Alt+Enter, which (at this moment) is not echoing code back, I believe.

**Comment by ErwanPiR** [comment]
Hi @davidanthoff,

Thanks for your answer. I already try _Alt+Enter_ but the behavior is the same... Is there something we can add in the options of the _Keyboard Shortcuts_ panel to change this ? Or maybe it's an option of the REPL that has to be change ?

Thanks for your help.

**Comment by davidanthoff** [comment]
Wait, Alt+Enter is echoing back code? That shouldn't be the case and I can't replicate that. Can you give a bit more info how you can trigger that?

**Comment by ErwanPiR** [comment]
Hi @davidanthoff,

So now _Alt+Enter_ is not echoing back anymore with the new version of VS Code/Extension.

However, the behaviour is still not the same that _Ctrl+Enter_. You can if the cursor is at the beginning of a line tape _Alt+Enter_ it will run the line (without echoing back). But if the line is not in the global scope (in a function or in a loop) it runs all the lines in the same scope...

Maybe it's the correct behaviour but I think It should be possible to run just the line. For example by selecting the line. Actually if you select a line or a piece of code in a line, and you tape _Alt+Enter_ nothing happens. So yo need to use _Ctrl+Enter_ to do so which by the way isn't working anymore...

I mean you still can place the cursor at the beginning of the line and run the line with _Ctrl+Enter_ but you can't anymore select couple lines or piece of code in a line and run it with _Ctrl+Enter_ because it add a weird 200~ in the repl... See the picture attached. 

Is there a incompatibility with the 1.37.1 version of VS Code ?

Again the idea behind all this is to be able to run a lot of lines without writing all the lines in the REPL, by selecting them.

Thanks for your answer (and your work :))
![ctrlenter](https://user-images.githubusercontent.com/44569180/63326876-6a8bc400-c32d-11e9-8909-fb034f8782f1.PNG)

**Comment by KristofferC** [comment]
>  run it with Ctrl+Enter because it add a weird 200~ in the repl... See the picture attached.

Seems the bracket pasting is indeed bugged :/. I don't really have access to Windows right now to figure out why though.

**Comment by ErwanPiR** [comment]
Yes I am on v0.12.1 of the extension. 
The fix on v0.12.2 is working fine with CTRL+ENTER, thanks.

**Comment by davidanthoff** [comment]
I'm going to close this because I haven't seen any problem along these lines for quite a while.
