### ISSUE TITLE
Displaying DataFrame

### ISSUE THREAD

**Issue by ErwanPiR** [julia-vscode/julia-vscode#808]
Hi,

I have a surprising behaviour with the displaying of dataframes in the REPL. It's something I didn't have previously and I have no idea what changed in between.

Let me explain. When I have a dataframe of 1 to 3 lines, no problem ! But if my dataframe has more than 3 lines, I can't anymore show the preview of the dataframe as before.

If I do :
`df = DataFrame(A = 1:4, B = ["M", "F", "F", "M"])`
I get in the REPL
`4x2 DataFrame`
while if I do:
`df2 = DataFrame(A = 1:3, B = ["M", "F", "F"])`
I get the classic preview of the DataFrame...

I also get the behaviour when using first :
`first(df,3)`
gives me a preview of the 3 first lines of the dataframe when
`first(df,4)`
gives me
`4x2 DataFrame`

The only way I have to get more than 3 lines is to use showall which is fine for a small dataframe but impossible for a large one. The classic preview is necessary in that case !

This happens only in the REPL in VS Code. When I open a Julia terminal outside, I have the classic behaviour.

Does someone is able to explain me what the problem is and how can I fix it ?

Thanks a lot.

**Comment by davidanthoff** [comment]
Hm, I can't replicate that. What versions of packages and julia and extension are you using?

**Comment by ErwanPiR** [comment]
Hi @davidanthoff,

I'm using the following versions :
DataFrames => 0.19.0
julia Language Support => 0.11.6 (the only extension installed :) )
Julia => 1.1.1
VS Code => 1.36

Thanks for your answer.

**Comment by davidanthoff** [comment]
Can you update the extension to v0.12.0 and see whether it still happens?

**Comment by ErwanPiR** [comment]
Hi,

Yes I still have the same behaviour. I don't undestand because on another computer with the same versions of the packages and extensions (and Julia) I don't have it.

Could it be a weird option in VS Code that I have activated by mistake ?

**Comment by ErwanPiR** [comment]
Hi,

I come back with the printing problem of dataframes in the REPL. I still have the curious behavious for dataframe with more than 3 lines. I have everything up to date... Is someone has a clue about how to correct the problem ?

Thanks

**Comment by davidanthoff** [comment]
What packages do you have loaded besides DataFrames?

**Comment by ErwanPiR** [comment]
Hi,

I close this subject since the solution can be found here : [https://discourse.julialang.org/t/dataframe-no-longer-is-displayed-in-console/32717/3](url) 

For the record, it's a problem of REPL size in vscode and can be solved adjusting the height of the REPL (and by restarting if necessary). 

Thanks @davidanthoff for the help anyway
