### ISSUE TITLE
Parsing error for x.^B[length(A)+1] 

### ISSUE THREAD

**Issue by stakaz** [julia-vscode/julia-vscode#812]
Hello, why do I get a parsing error for this code:

```julia
x.^B[length(A)+1] 
```
The error is indicated at `+1` and is removed once I add a space befor `+`, like:
```julia
x.^B[length(A) +1] 
```

**Comment by ZacLN** [comment]
Thanks for the bug report, fixed here: https://github.com/julia-vscode/CSTParser.jl/commit/f9dcdbf0467c0764fc0c3c4d73a1923ab1977e4d
