### ISSUE TITLE
Disable the linter in settings does not work

### ISSUE THREAD

**Issue by stakaz** [julia-vscode/julia-vscode#813]
Hello, I cannot disable the linter. Even if I uncheck the `Run linter on active files` option, I still get all the warnings. Additionally, now I get then for all files and not only for opened once. Combined with the `Missing Reference` bug described in #811 I get 2K warnings in my project and the complete tree view is colored with warnings. Could you please have a look into it? Thanks.

**Comment by jasonsun0310** [comment]
agreed... this is really annoying... I don't think the linter is mature enough...

**Comment by crstnbr** [comment]
Shouldn't this be easy to fix? It indeed is quite annoying (in particular given https://github.com/julia-vscode/julia-vscode/issues/307).

**Comment by davidanthoff** [comment]
https://github.com/julia-vscode/LanguageServer.jl/pull/423 Will fix this.
