### ISSUE TITLE
runtests.jl does no longer work with 0.12.0

### ISSUE THREAD

**Issue by MartinOtter** [julia-vscode/julia-vscode#814]
When selecting file <modulName>/test/runtests.jl in a module and clicking F5, the file is executed, but includes inside the runtests.jl file are no longer relative to the directory of runtests.jl but relative to pwd(). This means, all the runtests.jl can no longer be executed in a simple way from vscode. In 0.11.6 this was not the case.

This might be related to another missing feature: In 0.11.6, clicking F5 showed the command that is executed:
```
include(raw"<path>test\runtests.jl")
```
However, in 0.12.0, this command is no longer shown and is therefore also no longer stored in the REPL memory (and can no longer be inquired).

Due to the above issues, I am temporarily going back to 0.11.6

**Comment by cojua8** [comment]
This also happens to any other file, Execute file command is not working
