### ISSUE TITLE
Linter highlights objects in the workspace

### ISSUE THREAD

**Issue by neoabs** [julia-vscode/julia-vscode#815]
1. I cannot turn off linter - it shuts down only highlighting iterators
2... so I noticed linter highlights that are in the memory but are not defined in current script. Since I work on many scripts simultaneously and that breaks the visuals. 

Desired outcome: a switch for linter to also check if object is in the memory before highlighting

![image](https://user-images.githubusercontent.com/53402602/62008974-afbb3c80-b159-11e9-8707-15a6e8222dee.png)

**Comment by neoabs** [comment]
![image](https://user-images.githubusercontent.com/53402602/62009130-f90c8b80-b15b-11e9-879a-db602607d295.png)
It also failes to actually select proper set of symbols for checking. Above it says missing reference tm, where there is no m in the whole line. 

Linter is a great tool and much apprecieted but it seems it was too soon to release it. Especially since you cannot turn it off

**Comment by neoabs** [comment]
Furthermore after typing ANY variable name _not at the beginning of the line_ linter starts freaking out (something like  picture above). Only saving file calms it down.

**Comment by CameronBieganek** [comment]
I wouldn't want this to be the default setting. When I'm developing a package, all that matters is lexical scope, i.e. what's in the file. I shouldn't get different linting behavior if I happen to have an object called, e.g., `df` in memory.

**Comment by ZacLN** [comment]
We've added options to disable lint hints so I'm going to close this. 

The linter is not going to react to what's been run in the REPL for the reasons @CameronBieganek gives.
