### ISSUE TITLE
Tests Pane

### ISSUE THREAD

**Issue by mileslucas** [julia-vscode/julia-vscode#817]
Hello, I tried looking through issues and pull requests and I don't seem to see anything about this- a test pane that matches python language's test pane. Something that can be used to run tests (without having to open repl), shows testsets and nested testsets, visualizes failures, and has debug support for testsets.

The workflow I have with vscode for python library development is very nice and I'd like to have a similar workflow with julia. This feature isn't prevalent in Juno, either, so it would be a good selling point.

**Comment by Eggiverse** [comment]
I am also looking forward to this. I having been working with Julia for months but no debugger is as easy to use as those in python. I hope Microsoft can participate in future development in this as well since they have done a great job in Python.

**Comment by zhangliye** [comment]
Also waiting for this feature. Thanks!

**Comment by mileslucas** [comment]
I wanted to bump this-

Could we start with something like a test icon for the sidebar that executes tests and outputs to the output pane? To ease compilation pains, maybe this can start a julia instance s.t. multiple runs all run within basically the same REPL, with some button or something that can restart the instance (for when we inevitably change a struct definition)? I'm sorry if this is not explanatory; I'm very unfamiliar with how vscode works.

**Comment by davidanthoff** [comment]
There is already a command to run tests `Tasks: Run Test Task`. That is a VS Code UI piece and we hook into that to run Julia tests.

**Comment by xgdgsc** [comment]
Any plan to support [Test Explorer UI ](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer)?

**Comment by davidanthoff** [comment]
I think there isn’t really any official support in Julia for running a subset of tests, right? That kind of limits what we could do on that front...

**Comment by xgdgsc** [comment]
Thanks. Haven' t used tests in julia...

**Comment by davidanthoff** [comment]
I'm renaming this issue to track the pure test pane feature. Running tests in the debugger is tracked at https://github.com/julia-vscode/julia-vscode/issues/1049.

**Comment by pfitzseb** [comment]
Pretty sure we have this nowadays.
