### ISSUE TITLE
Exclude/Include paths for problems pane

### ISSUE THREAD

**Issue by rapus95** [julia-vscode/julia-vscode#829]
In accordance to https://github.com/microsoft/vscode/issues/22289 it'd be cool if there was a config to exclude/include some paths from checking. That way I could ignore outdated Julia packages/folders from problems view.

**Comment by ZacLN** [comment]
#797

**Comment by rapus95** [comment]
Direct reference to the solution: https://github.com/julia-vscode/julia-vscode/issues/797#issuecomment-578037867
(Rather than to an entirely unrelated problem)
