### ISSUE TITLE
Launching 100% CPU Julia processes. 

### ISSUE THREAD

**Issue by vomout** [julia-vscode/julia-vscode#830]
The most recent 0.12.1 update seems to have a) completely disabled the language server (the package complains that it is not running, even immediately after restart, if one tries to turn on the logs), and b) to be starting Julia processes that take 100% CPU: without even using the Julia REPL. (Yes, I verified, and Code is the parent process of those Julia processes.)

Also, possibly related to the language server being gone, the flaky LaTeX-unicode completion has finally completely disappeared. Not a trace anymore. 

OS: MacOS.

**Comment by xukai92** [comment]
@davidanthoff Thanks for the reply. A little bit more patience does solve the problem. 

BTW what is LS short for?

**Comment by davidanthoff** [comment]
Language Server, it is the backend process that does all the code analysis etc.
