### ISSUE TITLE
Spurious undef variable warning

### ISSUE THREAD

**Issue by KristofferC** [julia-vscode/julia-vscode#836]
```
const BroadcastedChunkableOp{Style<:Union{Nothing,BroadcastStyle}, Axes, F<:ChunkableOp, Args<:Tuple} = Broadcasted{Style,Axes,F,Args}
```

Gives a warning that `F` and `Args` both on the LHS and RHS of the equal sign are undefined.

**Comment by ZacLN** [comment]
Thanks, this is fixed on master (https://github.com/julia-vscode/CSTParser.jl/commit/07b663d9ad5fb136bc7a79044dbd3f8488c89770)
