### ISSUE TITLE
Having JULIA_LOAD_PATH environmental variable prevents Julia language server from starting

### ISSUE THREAD

**Issue by zhopan77** [julia-vscode/julia-vscode#848]
I have the stable VS Code version 1.37.1 with julia-vscode extension version 0.12.2, and Julia v1.2.0, running on Windows 10 64-bit.

After julia-vscode loaded the symbols from installed packages, the linter still complained about variables and functions imported from my user-defined modules as "Missing reference". I learned from online discussions that julia-vscode won't load user-defined modules at paths dynamically appended to LOAD_PATH yet.

Therefore, I added the module paths to the JULIA_LOAD_PATH environmental variable. However, this action led to the error message "Could not start the Julia language server. Make sure the configuration ...", and the "Julia env: " on the status bar was showing "[loading]" indefinitely (it should have shown "v1.2"). I tried using double back slashes `\\` for the paths in JULIA_LOAD_PATH, tried configuring file names instead of paths, and even tried using just one space (Windows does not allow totally empty environmental variable). All of them led to the same problem. Only after I removed the JULIA_LOAD_PATH environmental variable did I get the Julia language server back.

VS Code Help | About information:

Version: 1.37.1 (user setup)
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:17:55.855Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by HFriberg** [comment]
I can replicate the issue on Linux if I overwrite the defaults:
`JULIA_LOAD_PATH="/home/hfriberg/foobar" code`

but including the defaults (i.e., by adding a colon) loads as normally:
`JULIA_LOAD_PATH="/home/hfriberg/foobar:" code`

I still get `Missing reference` for the code `using mymod` even though module `mymod` exists at `/home/hfriberg/foobar/mymod.jl`, so the language server is definitely not respecting the environment variable. I agree with @zhopan77 that there should be some way (alternatively in settings.json of VS CODE) to modify the load path. This is a feature request though, not a bug report.
