### ISSUE TITLE
Renaming a struct (F2) doesn't work

### ISSUE THREAD

**Issue by BrianGun** [julia-vscode/julia-vscode#852]
When renaming a struct all references to fields in the struct get turned into the new struct name.

simplest example:

Before struct rename

struct Graph
 children:: Array{Int64,1}
end

function test()
    g = Graph()
    f = g.children
end

After struct rename

struct WRONG
 children:: Array{Int64,1}
end

function test()
    g = WRONG()
    f = g.WRONG
end

**Comment by ZacLN** [comment]
Thanks, fix is https://github.com/julia-vscode/StaticLint.jl/commit/9f803aae755bdb8ee987080eb985dd3e05c74ce0 but will take a little while to creep into a vscode release
