### ISSUE TITLE
Support progress logging as implemented in Juno

### ISSUE THREAD

**Issue by phlavenk** [julia-vscode/julia-vscode#854]
A fantastic feature from the usability standpoint.
See JunoLab/Atom.jl#122 , the `JunoProgressLogger` functionality. 
Just add anywhere in the code `@info "foo-bar" progress=i/length(arr)` and you"ll be presented with a nice (nested if needed) progress bar that does not pollute your REPL. In Juno they make their logger the default - might be good idea do the same here.
Have no idea how to implement it within VSCode. With e.g. floating window or a widget? I personally have no JS programming skills.

**Comment by davidanthoff** [comment]
Yes, that would be nice! Maybe in the status bar?

**Comment by aterenin** [comment]
Possibly, related to this, it would be useful to have the `@progress` macro from Juno be able to display in VS Code. This shows a progress bar for how long some loop is expected to take.

**Comment by davidanthoff** [comment]
There are various progress UI things in the VS Code API, so we would really just need to figure out how we do the plumbing with Julia.

**Comment by pfitzseb** [comment]
Should use https://github.com/JunoLab/ProgressLogging.jl on the Julia side for this and there's a progress API at https://code.visualstudio.com/api/references/vscode-api#window.

**Comment by davidanthoff** [comment]
I think this is something we should discuss tomorrow: we've had this pretty strict policy so far in the extension here to not rely on any packages in the user controlled processes...

**Comment by phlavenk** [comment]
i love the @info, @debug, and other mechanism defined by Logging stdlib where activating a progress bar in Juno can be as simple as
```julia
@info "progress message" progress = 0.5
```
I have no idea what is the best way to hook into this mechanism directly, without having to force use of `VSCodeLogger :> Logging.AbstractLogger` that annoys me a lot in Atom. In Atom, I've to use the default logger injected by Atom under the hood.  In that case, progress logging is simple, effective and visually nice. But once I use my own logger, Juno's progress meter UI element is broken (diconnected). I'd prefer a different way for IDEs to hook into the Logging stdlib interface.

**Comment by pfitzseb** [comment]
https://github.com/julia-vscode/julia-vscode/pull/1579/ will implement this. I don't think there's a way to do this without a custom logger though; the best way for a user to use a custom logger is to change the global logger.

**Comment by goretkin** [comment]
Is this implemented now?

I was surprised to see that this example https://c42f.github.io/TerminalLoggers.jl/stable/#Progress-bars-1 (reproduced below) did not produce progress bars in the VS Code REPL. 

```julia
using Logging: Logging, global_logger
using TerminalLoggers: TerminalLoggers, TerminalLogger

global_logger(TerminalLogger(right_justify=120))
using ProgressLogging

@progress for i=1:100
    if i == 50
        @info "Middle of computation" i
    elseif i == 70
        println("Normal output does not interfere with progress bars")
    end
    sleep(0.01)
end
@info "Done"
```

**Comment by garibarba** [comment]
> i love the @info, @debug, and other mechanism defined by Logging stdlib where activating a progress bar in Juno can be as simple as
> 
> ```julia
> @info "progress message" progress = 0.5
> ```
> 
> I have no idea what is the best way to hook into this mechanism directly, without having to force use of `VSCodeLogger :> Logging.AbstractLogger` that annoys me a lot in Atom. In Atom, I've to use the default logger injected by Atom under the hood. In that case, progress logging is simple, effective and visually nice. But once I use my own logger, Juno's progress meter UI element is broken (diconnected). I'd prefer a different way for IDEs to hook into the Logging stdlib interface.
> 
> For more fancy progress bar call options (`@progress for ...`) I'm happy to use a separate package, e.g. `ProgressMeter` that would also just use the `@logmsg...` interface.

This `@info` works great 🤗 , but it is totally missing from the documentation.
