### ISSUE TITLE
Execute Code Cell : Add delimiter ## in docs

### ISSUE THREAD

**Issue by LodrikMtl** [julia-vscode/julia-vscode#857]
I was trying to use the Julia: Execute Code Cell Command, but I didn't know what was the delimiter for a cell. Finally, I found it, but It would be nice to have a comment about it :).

**Comment by NightMachinary** [comment]
@davidanthoff This feature seems to have regressed? `language-julia.executeCellAndMove` now executes all of my file (`###`s do not act as delimiters).

**Comment by pfitzseb** [comment]
The current cell delimiter is `^##(?!#)`, so only exactly two `##`s will work now.

**Comment by NightMachinary** [comment]
@pfitzseb Thanks, that works. It will be much better if the API keeps backward-compatibility in mind. Today I updated VSCode and without warning, some command IDs of the Julia extension were changed (on which I had custom hotkeys defined), and `###` no longer worked as a cell boundary. Tools need stability.

**Comment by davidanthoff** [comment]
We hope to reach a 1.0 soonish and then we'll be more careful about not breaking stuff.

**Comment by bmaslam11** [comment]
It would be nice if julia vscode shows some cell boundary line after adding ## (similar to matlab or spyder IDE)
