### ISSUE TITLE
Execute code block: shuffling command orders

### ISSUE THREAD

**Issue by phlavenk** [julia-vscode/julia-vscode#862]
Sometime when I quicky pres several times alt-enter (execute code-block) the order of code-blocks in the FIFO gets shuffled. If done slowly, it does not happen. And often shuffling appears if one emits several alt-enter and ctrl-enter keypresses - then it happens even more often. Seems like some racing-condition.

**Comment by ZacLN** [comment]
Does this happen when the editor has just been launched or a REPL is not yet opened ?

**Comment by phlavenk** [comment]
In the case you mentioned, this is a rule - therefore i don't use it for the start of a session. But occasionally  it happens also in the middle of running session - hard to debug, though.

**Comment by phlavenk** [comment]
The bug in the wrong ordering is still present and makes me crazy as I have longer (cca 1min) execution times per command. So I try to serialize more block-execute commands and ofter get them executed in wrong order
(latest vscode, 0.15.32, julia 1.4.0, win10-x64)

Today, I've found a similar issue discussed on SO
https://stackoverflow.com/questions/61781887/javascript-appends-writes-strings-in-the-wrong-order
and I think we should rewrite the 
```ts
async function executeCode(text, individualLine) { ...
```
in a similar sense our `executeCode` to be just something that synchonously serializes the REPL commands into FIFO and let another function do the julia-crunching in the right order.

**Comment by pfitzseb** [comment]
Can you check whether this is still happening on 0.17?

**Comment by phlavenk** [comment]
So far I didn't observed this issue on 0.17 
I think I can close it now and reopen in case it shows-up in long-term use.
