### ISSUE TITLE
Show a useful error message if Alt+Enter is pressed and the LS is not yet up and running

### ISSUE THREAD

**Issue by phgmacedo** [julia-vscode/julia-vscode#864]
Execute code block only works once the Julia Language Server is ready.

Source: Julia (Extension)

**Comment by davidanthoff** [comment]
Yes, and I don't see how we could change that, the language server is used to detect the code block.

We should try to get the language server to be ready faster :) I'm going to close this here because I don't see anything we can do to change that.

**Comment by pedrogarcia** [comment]
@davidanthoff I didn't even know that the language server was not loaded yet. 

I get no feedback from the editor that the language server is starting, if it is working or not, if there is some problem loading something, if I'm using something wrong, or if its just the general julia newbie unfriendliness.

**Comment by davidanthoff** [comment]
Yes, good point, we should improve the UI here! I updated the issue title.

**Comment by leventov** [comment]
Related to https://github.com/julia-vscode/julia-vscode/issues/830

**Comment by zerefwayne** [comment]
@davidanthoff @pfitzseb  Since this issue still persists, can I look into it?

**Comment by pfitzseb** [comment]
This should basically be fixed now, no?

**Comment by zerefwayne** [comment]
@pfitzseb I still didn't get any notification telling me that LS hasn't started yet. Tried it just now
