### ISSUE TITLE
plotting crashes

### ISSUE THREAD

**Issue by JianghuiDu** [julia-vscode/julia-vscode#868]
simply calling `PyPlot.figure()` crashes `julia`. Any idea? v1.2.

**Comment by JianghuiDu** [comment]
This is the return message:
`The terminal process terminated with exit code: 3221226505`

**Comment by davidanthoff** [comment]
Are you sure this is related to VS Code?

**Comment by JianghuiDu** [comment]
Just found that it also crashed `Juno`. Probably a ` PyPlot` issue then.
