### ISSUE TITLE
renaming unicode variable eats extra space

### ISSUE THREAD

**Issue by yongheekim-dev** [julia-vscode/julia-vscode#871]
renaming variable with `F2`which endswith unicode 

here is MWE
```julia
    aÂ = ["a"]
    aÂ[1]
```
And when I change `aÂ` to `bb` with `F2` results is

```julia
    bb = ["a"]
    bb1]
```

Maybe it's bug from vscode? rather than julia-vscode

**Comment by ZacLN** [comment]
Should be addressed by: https://github.com/julia-vscode/LanguageServer.jl/pull/427
