### ISSUE TITLE
ccall keyword is not recognized

### ISSUE THREAD

**Issue by radioflash** [julia-vscode/julia-vscode#872]
AFAIK, `ccall` is a keyword in Julia since v0.6.

The vscode extension does not respect it, though, and complains about "missing reference to ccall" wherever it is used.

Maybe this is just a matter of adding "ccall" to syntaxes/julia.json?
I will submit a pull request if someonce can confirm that the required change is simple (I lack insight into the codebase).

**Comment by davidanthoff** [comment]
We just regularly copy over the syntax file from https://github.com/JuliaEditorSupport/atom-language-julia, so ideally you would make a PR against that repo, and then we would copy things over to here once that is done.

**Comment by radioflash** [comment]
Some simple experiments led me to believe that the problem is with StaticLinter (not the syntax json file): Because the problem only shows after the file is open for some time (delay from linter?), while the syntax highlighting (powered by the syntax json?) kicks in immediately.

After looking into everything some more, it seems to me that both this issue and also the block enum one (#873) is already fixed in the newest StaticLinter version.

But from what I can tell the StaticLinter master branch only works with the SymbolServer master branch (that combination passes all of their respective tests).

The julia-vscode project is using an older StaticLinter and SymbolServer commits (SymbolServer also seems to have forked off?).

I've cloned the repo, changed both StaticLinter and SymbolServer to master branch and built the plugin file. This fixes this issue and also #873.

**Comment by radioflash** [comment]
I think only these two commits would be lost by changing SymbolServer to master (everything else was just version bumping):

julia-vscode/SymbolServer.jl@5e403f5
julia-vscode/SymbolServer.jl@ae81128

Maybe the master branch makes these obsolete, anyway.

**Comment by ZacLN** [comment]
Fixed https://github.com/julia-vscode/SymbolServer.jl/commit/d517c0c77edb3dd26325dbdc94afd912f05bc92d, will be in the next release
