### ISSUE TITLE
enum blockdeclaration (begin ... end) gives errors when no defaults are specified

### ISSUE THREAD

**Issue by radioflash** [julia-vscode/julia-vscode#873]
This gives "missing reference" errors (both inside the declaration and wherever the literals are used):

```
@enum MyEnum begin
    ZERO
    ONE
end
```

When default values are specified, everything works as expected:
```
@enum MyEnum begin
    ZERO = 0
    ONE = 1
end
```

**Comment by ZacLN** [comment]
Appears to be fixed by StaticLint updates
