### ISSUE TITLE
Runaway Julia process

### ISSUE THREAD

**Issue by tro3** [julia-vscode/julia-vscode#880]
Using julia-vscode on Windows and love(d) it.  But now I can't use it.  While doing some benchmarking in the console, I hit ctrl-C at one point and got a slew of error messages that seemed uncorrelated.  Had to restart Code.

But now, whenever the Julia extension is loaded, at full-CPU runaway Julia process launches that can't be stopped.  Things I have tried:

- Ending process in task manager (restarts the process if extension is still active)
- Reinstalling extension
- Combinations of the above and machine restart
- Turning off linting
- Turning off the sysimage setting

I don't know if it is because of the Ctrl-C leaving an image somewhere that the extension relaunches, or if it is an interaction with the recently-installed BechmarkTools.  (I find the latter hard to believe.)  Nothing else has changed in my environment.

Did an issues search here and did not turn up anything.  Apologies if this is redundant.  Any help appreciated.

**Comment by tro3** [comment]
Update - after a couple hours, the process ended for reasons unknown.  So I'm back up, but I still don't understand how this behavior was possible.

**Comment by davidanthoff** [comment]
That is almost certainly the initial indexing of all the packages by the language server. Essentially what happens is that the extension loads every package you have in your environment once, extracts all the information about types, doc strings etc. and stores that internally so that we have quick access to it later.

We have plans to make that process less intrusive, but for now there is nothing one can do about it, I'm afraid.

**Comment by tro3** [comment]
Fair enough, but wouldn't that have implied the same behavior if a non-VS-code Julia instance was running?  That was not the case.

**Comment by davidanthoff** [comment]
No, this is a VS Code extension thing.

**Comment by tro3** [comment]
@davidanthoff - Thanks for the help.  Still loving Julia, and hoping to take things to the next level and contribute when time allows.  I'll sign up for Discourse, and if there is something here you want to offload, let me know.
