### ISSUE TITLE
"Execute Code" command uses current prompt

### ISSUE THREAD

**Issue by BioTurboNick** [julia-vscode/julia-vscode#881]
If e.g. the Pkg prompt is active in the REPL, code lines executed with Ctrl+Enter are executed in the context of the Pkg prompt, which doesn't work.

**Comment by davidanthoff** [comment]
Yes, Ctrl+Enter just sends whatever you have selected to the REPL, copy-paste style. I don't think there is anything we can do about that, we don't really know what state the REPL is in when we do that.

 Alt+Enter should be more robust, it executes the code independently of the REPL state.
