### ISSUE TITLE
[BUG] Clicking on path that contains spaces in REPL plane does not open corresponding file in editor plane

### ISSUE THREAD

**Issue by KestutisMa** [julia-vscode/julia-vscode#885]
Clicking on path that contains spaces in REPL plane after some error does not open corresponding file in editor plane, vscode 1.39.2, julia extension 0.12.3, Windows 10, (for example:
[1] top-level scope at C:\Users\Kestutis\OneDrive - Lietuvos sveikatos mokslu universitetas\is Dropbox\Programming\gjJulia\fentonOptimizer.jl:68).
But clicking on path that does not contain spaces opens file in editor plane.

**Comment by davidanthoff** [comment]
I don't think there is anything we can do here, this is really functionality that is part of VS Code itself.

**Comment by cdsousa** [comment]
Would the "link provider" API to extensions (https://github.com/microsoft/vscode/issues/91290) work?
