### ISSUE TITLE
OS X Catalina and error `command 'language-julia.startREPL' not found`

### ISSUE THREAD

**Issue by torkar** [julia-vscode/julia-vscode#886]
OS X Catalina 10.15.1
VS Code 1.40.0
julia-vscode 0.12.3

When I open a `Julia` file and select `> Julia: Start REPL` in the `Command Palette` I get this at the bottom right corner:
<img width="512" alt="Skärmavbild 2019-11-10 kl  16 33 38" src="https://user-images.githubusercontent.com/22315/68546561-eac74000-03d7-11ea-9625-a7e2b3bcd7ba.png">

I have `"julia.executablePath": "/Applications/Julia-1.2.app/Contents/Resources/julia/bin/julia"` in my `settings.json`. If I execute `/Applications/Julia-1.2.app/Contents/Resources/julia/bin/julia` in the terminal I get a `Julia` interpreter running...

**Comment by davidanthoff** [comment]
I believe this should be fixed on `master`.
