### ISSUE TITLE
Code that crashes things

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/julia-vscode#896]
```
ENV["JUPYTER"] = "/home/gsc/anaconda3/bin/jupyter"`

Pkg.add("IJulia")
```
the extra `\`` at the end of first line crashes it every time for me.

_Originally posted by @xgdgsc in https://github.com/julia-vscode/julia-vscode/issues/801#issuecomment-557886076_

**Comment by davidanthoff** [comment]
@xgdgsc, could you provide more context for this comment? What version of Julia, what version of the extension are you using? Where do you have this piece of code?

**Comment by xgdgsc** [comment]
Working for me now. You can close this.
