### ISSUE TITLE
Syntax highlighting for function arguments

### ISSUE THREAD

**Issue by CameronBieganek** [julia-vscode/julia-vscode#898]
I noticed recently that the MATLAB extension for VS Code is able to change the color of arguments in function definitions, like this:

![image](https://user-images.githubusercontent.com/8310743/70562171-81ab2780-1b51-11ea-8df7-07fcbefcbf12.png)

The example shown in the screen capture uses the Monokai theme. It would be cool if we could also get syntax highlighting of arguments in function definitions for the Julia VS Code extension. Of course it's not urgent, but I'm always in favor of more colors when it comes to syntax highlighting.

Note that the function arguments are highlighted only in the declaration of the function signature, not within the function body. PyCharm, on the other hand, highlights arguments both within the signature and within the body:

![image](https://user-images.githubusercontent.com/8310743/70562725-950ac280-1b52-11ea-9b1b-ab269d4715a7.png)

Highlighting argument use within function bodies seems desirable, though I don't know if it's possible in VS Code.

**Comment by davidanthoff** [comment]
Do they do something differently in the grammar definition they use?

**Comment by CameronBieganek** [comment]
I'm not sure what they do differently with their grammar. I've never worked with TextMate grammars, but it looks interesting. I might play around with the Julia grammar if I have some time.

**Comment by davidanthoff** [comment]
We just routinely copy the grammar file from https://github.com/JuliaEditorSupport/atom-language-julia, so ideally make changes over there, and then they will flow into the VS Code extension eventually.
