### ISSUE TITLE
Julia Language Server Crashes like nuts.

### ISSUE THREAD

**Issue by JustBKen** [julia-vscode/julia-vscode#900]
I have no idea how to reproduce this.
None of the features of the linter work. Completion fails to display anything except things referenced in the active file. Latex completion doesnt display anything and tab enters a larger space.

The only indication that ist is the LanguageServer, is the message, that it has crashed 5 times in the last 3 minutes, and that it will not be restarted.

Version 12.3, 
Vscode official binary version on Manjaro linux, version 1.40.2-1
Julia 1.3

Settings.json:

{
    "julia.executablePath": "/usr/bin/julia",
    "julia.enableCrashReporter": true
}

**Comment by dfioravanti** [comment]
Same for me with standard setting and with this environment 
```
version 12.3
Julia 1.3
Ubuntu 18.04 
Vscode version 1.41.0 installed from snap
```
attached you can find the stacktrace of the server. Let me know if you need anything else.

[stacktrace.log](https://github.com/julia-vscode/julia-vscode/files/3960025/stacktrace.log)

**Comment by SyxP** [comment]
I believe version 12.3 does not support Julia 1.3.
You need to try it with https://github.com/julia-vscode/julia-vscode/releases/tag/v0.13.0-alpha.1

I'm not sure if there are other problems with 0.13.0-alpha that I'm not aware of, but I've tried it and it works so far.

**Comment by davidanthoff** [comment]
Yes, the shipping version doesn't work with Julia 1.3 yet, try the alpha in the meantime. We are trying to get a new version out ASAP.
