### ISSUE TITLE
Missing reference error for `local` var

### ISSUE THREAD

**Issue by tk3369** [julia-vscode/julia-vscode#903]
Variables declared with `local` ends up with a missing reference warning.  Note that `global` works fine.

![image](https://user-images.githubusercontent.com/1159782/70855641-15972f00-1e83-11ea-999d-8cc99c7dd0be.png)

![image](https://user-images.githubusercontent.com/1159782/70855650-44150a00-1e83-11ea-9151-48ead6d4fe9a.png)

https://github.com/julia-vscode/julia-vscode/releases/tag/v0.13.0-alpha.1

VSCode version:
```
Version: 1.40.2
Commit: f359dd69833dd8800b54d458f6d37ab7c78df520
Date: 2019-11-25T14:52:45.129Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0
```

**Comment by ZacLN** [comment]
https://github.com/julia-vscode/StaticLint.jl/pull/43
