### ISSUE TITLE
Code folding does not hide `end`

### ISSUE THREAD

**Issue by SyxP** [julia-vscode/julia-vscode#905]
For instance on a function
```
function f()
    1 + 2
end
```

Folding `f` does not hide the `end` keyword at the end. I am using version 0.13-alpha with Julia 1.3 on Linux x86_64.

**Comment by bilderbuchi** [comment]
One could argue that then `end` should remain visible, as it is needed to complete the`function` which also stays visible.

For a slightly more involved example, consider
```
if bla
  xxx
else
  yyy
end
```
if you collapse on the "if", you get
```
if bla ...
else
  yyy
end
```
If you collapse on the `else`, you get
```
if bla
  xxx
else ...
end
```
, both of which i find intuitive. Do you agree?

**Comment by davidanthoff** [comment]
Yeah, I think what we are doing here is also consistent with folding for other languages. For example in JSON, the closing `}` also stays visible if one folds.

**Comment by SyxP** [comment]
Also related (and duplicate I think), #865 .

**Comment by ZacLN** [comment]
I think this ought to stay as is so am closing this
