### ISSUE TITLE
Hmm... 13.1 is already published, but the issues in milestone v0.13.1 are not yet fixed...

### ISSUE THREAD

**Issue by ufechner7** [julia-vscode/julia-vscode#911]
???

**Comment by davidanthoff** [comment]
I forgot to update the CHANGELOG for 0.13.0, so I pushed 0.13.1 with just an update for the CHANGELOG a few minutes after I published 0.13.0. I make that same mistake _every_ time I publish a new release. I updated the milestone name to 0.13.2.
