### ISSUE TITLE
code completion and linter doesn't seem to work on new release v0.13.1

### ISSUE THREAD

**Issue by reactgary** [julia-vscode/julia-vscode#912]
Hi,

I am using v0.13.0-alpha.1 in Linux, with Julia 1.3 and vscode 1.41.0. The code completion and linter seems to be working fine despite custom module in other files doesn't seem to be loading.

Then I tried julia-vscode v0.13.1 and all the rc for v0.13.1, and the code completion and linter doesn't seem to work on any of these version.

Just a report for the issue, thanks for the great work David, and is there anything I can help except for reporting bugs?

**Comment by ufechner7** [comment]
julia-vscode 0.13.1 is not working for me. But no error message, no crash. Any idea how to debug?

**Comment by ufechner7** [comment]
Just verified: going back to julia-vscode 0.12.3 fixes the problem.

**Comment by ufechner7** [comment]
Works for me now also on 13.1; just had to wait longer. To see the progress look at #

**Comment by ufechner7** [comment]
@reactgary What do you see if you look at the output of the Language Server (see #915)?

**Comment by reactgary** [comment]
@ufechner7 
I only see 2 lines in that windwos
`[ Info: Started symbol server
[ Info: CSV not stored on disc`

**Comment by reactgary** [comment]
@ufechner7 

When using 0.13.alpha-1, here is the log

[ Info: Started symbol server
[ Info: loading dependency PooledArrays
[ Info: loading dependency DataAPI
[ Info: loading dependency WeakRefStrings
[ Info: loading dependency Test
[ Info: loading dependency InteractiveUtils
[ Info: loading dependency Markdown
[ Info: loading dependency Base64
[ Info: loading dependency Random
[ Info: loading dependency Serialization
[ Info: loading dependency Logging
[ Info: loading dependency Distributed
[ Info: loading dependency Sockets
[ Info: loading dependency LazyArrays
[ Info: loading dependency ArrayLayouts
[ Info: loading dependency LinearAlgebra
[ Info: loading dependency Libdl
[ Info: loading dependency FillArrays
[ Info: loading dependency SparseArrays
[ Info: loading dependency StaticArrays
[ Info: loading dependency Statistics
[ Info: loading dependency MacroTools
[ Info: loading dependency DataStructures
[ Info: loading dependency OrderedCollections
[ Info: loading dependency Tables
[ Info: loading dependency IteratorInterfaceExtensions
[ Info: loading dependency DataValueInterfaces
[ Info: loading dependency TableTraits
[ Info: loading dependency CategoricalArrays
[ Info: loading dependency JSON
[ Info: loading dependency Dates
[ Info: loading dependency Printf
[ Info: loading dependency Unicode
[ Info: loading dependency Mmap
[ Info: loading dependency Compat
[ Info: loading dependency Pkg
[ Info: loading dependency SHA
[ Info: loading dependency LibGit2
[ Info: loading dependency REPL
[ Info: loading dependency UUIDs
[ Info: loading dependency DelimitedFiles
[ Info: loading dependency SharedArrays
[ Info: loading dependency Future
[ Info: loading dependency Missings
[ Info: loading dependency Reexport
[ Info: loading dependency FilePathsBase
[ Info: loading dependency DataFrames
[ Info: loading dependency Parsers
[ Info: loading dependency LoweredCodeUtils
[ Info: loading dependency JuliaInterpreter
[ Info: loading dependency CodeTracking
[ Info: loading dependency FileWatching
[ Info: loading dependency Requires
[ Info: loading dependency CUDAapi
[ Info: loading dependency AbstractFFTs
[ Info: loading dependency CEnum
[ Info: loading dependency CUDAdrv
[ Info: loading dependency TimerOutputs
[ Info: loading dependency CUDAnative
[ Info: loading dependency LLVM
[ Info: loading dependency Adapt
[ Info: loading dependency GPUArrays
[ Info: loading dependency NNlib
[ Info: loading dependency BinaryProvider
[ Info: Atom not stored on disc
[ Info: BenchmarkTools not stored on disc
[ Info: ZipFile not stored on disc
[ Info: IJulia not stored on disc
[ Info: Unrolled not stored on disc
[ Info: Feather not stored on disc
[ Info: loading dependency Profile
[ Info: loading dependency Media
[ Info: Query not stored on disc
[ Info: loading dependency SortingAlgorithms
[ Info: loading dependency InvertedIndices
[ Info: LanguageServer not stored on disc
[ Info: loading dependency HTTP
[ Info: loading dependency MbedTLS
[ Info: loading dependency Lazy
[ Info: loading dependency StringDistances
[ Info: loading dependency Distances
[ Info: loading dependency Observables
[ Info: loading dependency AssetRegistry
[ Info: loading dependency Pidfile
[ Info: loading dependency Widgets
[ Info: loading dependency Colors
[ Info: loading dependency ColorTypes
[ Info: loading dependency FixedPointNumbers
[ Info: loading dependency FunctionalCollections
[ Info: loading dependency Tokenize
[ Info: loading dependency SoftGlobalScope
[ Info: loading dependency Conda
[ Info: loading dependency VersionParsing
[ Info: loading dependency ZMQ
[ Info: loading dependency Parameters
[ Info: loading dependency DataValues
[ Info: loading dependency TableTraitsUtils
[ Info: loading dependency StaticLint
[ Info: loading dependency SymbolServer
[ Info: store set

**Comment by utotch** [comment]
same as me.
Thank you very much for implementing vscode-julia, but
almost nothing works except code highlighting for me.

## Doesn't work
* block code evaluation (opt + enter)
* plot pane (I've never seen)
* unicode imput (e.g. \lambda)

## my environment
* Julia 1.3.0
* VSCode 1.14.1
* vscode-julia v0.13.1
* mac OS 10.14.6 (Mojave)

I hope I can use these functions.

**Comment by cenkt** [comment]
Pls check output window in the console and make sure Julia Lang. Server does not produce any errors. Some packages do produce error and thus stop the server. Uninstall those packages. It worked for me.

**Comment by davidanthoff** [comment]
I'm going to close this. We rewrote much of the code that affects these parts for 0.14.x, please try that version once we have a beta out and if the problems are still there, open a new issue! Thanks for the original report.
