### ISSUE TITLE
"go to definition" does not work

### ISSUE THREAD

**Issue by drhouse82** [julia-vscode/julia-vscode#913]
For me (Windows 10 up to date, VSCode 1.41.1, Julia-extension 0.13.1) go to definition does not work.
The context menu contains no such entry, F12 doenst work, ctrl+click does also not work.

**Comment by reactgary** [comment]
v0.13.0-alpha.1 in Linux, with Julia 1.3 and vscode 1.41.0, "go to definition" works

**Comment by SyxP** [comment]
I know that this is not what you may have meant but I would like to also note that "go to definitions" doesn't work when asking for a function in the "standard libraries" (i.e. shipped with Base julia) for example, `norm` from `LinearAlgebra`, searching it only brings out the implementation in various libraries.

**Comment by drhouse82** [comment]
> 
> 
> I know that this is not what you may have meant but I would like to also note that "go to definitions" doesn't work when asking for a function in the "standard libraries" (i.e. shipped with Base julia) for example, `norm` from `LinearAlgebra`, searching it only brings out the implementation in various libraries.

Thanks

**Comment by drhouse82** [comment]
Turns out it is the same as with #912 and I had to wait for a long time until the indexing was finished. I was not aware of that there is something working in background.

**Comment by drhouse82** [comment]
So, technically, it does definitely work and the issue is not existing. However, UX-wise I dont see how a newbie user should understand this situation. After all, it is the same toppic as #912 .
