### ISSUE TITLE
Please, add debug option/ improve debug output

### ISSUE THREAD

**Issue by ufechner7** [julia-vscode/julia-vscode#915]
For me, version 0.13 doesnt work, but there is no message that indicates the reason. 
Suggestion: Add a debug option to the config file, that, if enabled prints debug information in the console like:
- language servers started
- progress report every 5s, xxx symbols indexed
- file xxx cannot be indexed
- module yyy not found

**Comment by ufechner7** [comment]
Partial solution: Next to the terminal click on "output", an then on the right there is a drop-down box where you can select "Julia Language Server".
So there is some output shown that reflects the progress, but what is missing is a. number of symbols indexed so far and b. warnings regarding modules that are not found

**Comment by ufechner7** [comment]
Related: #878

**Comment by davidanthoff** [comment]
There is also going to be a progress API in the next iteration of LS protocol that we should be able to use to indicate that indexing is still going on.

The real solution, though, of course is to just fix our indexing speed :)

**Comment by davidanthoff** [comment]
We now added a status bar item that reports indexing progress, and the output log also shows when indexing is finished. Closing for now.
