### ISSUE TITLE
multiline warning?

### ISSUE THREAD

**Issue by reactgary** [julia-vscode/julia-vscode#916]
Hi Guys,

As I am new to Julia I got myself in to some multiline bug, something like this. I wonder if the vscode extension could provide some warning for this?

I thought it will return 6, but 3 is returned.

> function aaa()
>     ret = 1 + 2
>     + 3
>     return ret
> end

**Comment by davidanthoff** [comment]
I don't think we can warn here, because this is valid Julia code.

**Comment by reactgary** [comment]
understood thanks
