### ISSUE TITLE
Language server started in non-Julia projects

### ISSUE THREAD

**Issue by jaens** [julia-vscode/julia-vscode#918]
Generally, VSCode extensions only start their language servers once you open a project/file containing that language (eg. the TypeScript, C/C++, OCaml, D etc. extensions do this).

The Julia extension though always starts the language server regardless of the languages in the project, so there's an unnecessary copy of the Julia server running for each VSCode window that is open, eg. with 5 non-Julia windows it's currently wasting what looks like ~1.4GB of memory on these language servers.

Can the language server be started lazily so the extension plays nicely with non-Julia projects?

**Comment by davidanthoff** [comment]
I can't replicate that, for me it only starts when there is some Julia file there.

**Comment by jaens** [comment]
Ah, interesting. I re-tested it, probably a VSCode issue actually, it only does that after an "Enable" command or an install, after a restart it works normally.
