### ISSUE TITLE
getPkgPath returns '/dev' instead of '/packages'

### ISSUE THREAD

**Issue by YongHee-Kim** [julia-vscode/julia-vscode#920]
Isn't [Open Package command](https://github.com/julia-vscode/julia-vscode/wiki/Commands) is meant to open folders in `.julia/packages`? but `getPkgPath`  returns `.julia/dev` so, open package command does not work the way it supposes to be

https://github.com/julia-vscode/julia-vscode/blob/daada866d10aa7e7ab61a0aa0a30dddb39c958ea/src/packagepath.ts#L23

**Comment by davidanthoff** [comment]
No, you should never edit the packages in `.julia/packages`, that is really best treated as a read-only copy of packages. When you want to edit a package, you dev it with `pkg> dev MyPackage`, and then the package manager will put it tino `.julia/dev` by default.
