### ISSUE TITLE
Trouble with VS Code remote development

### ISSUE THREAD

**Issue by oschulz** [julia-vscode/julia-vscode#921]
I'm having trouble running Julia with VS Code remote development (see #509).

I'm using `"julia.executablePath": "start-julia"` (I need a custom startup script, Julia runs in a Singularity container) - this works fine, locally. But in VS Code remote development mode (using SSH), VS code fails to start Julia. I get the error

```
Command failed: "/path/to/home/.local/bin/start-julia" --startup-file=no --history-file=no -e "using Pkg; println.(Pkg.depots())" `"/path/to/home/.local/bin/start-julia" --startup-file=no --history-file=no -e "using Pkg; println.(Pkg.depots())"` (exited with error code null)
```

Any ideas?

**Comment by davidanthoff** [comment]
Hm, is `start-julia` on the PATH? But I think generally I'm not sure whether we really support binary names that are different from `julia`...

**Comment by oschulz** [comment]
> Hm, is start-julia on the PATH?

It is, via "~/.profile" - and it seems to be found and run. I also tried with the absolute path to the script (not a good long-term option, since it differs between systems) and got the same result.

> But I think generally I'm not sure whether we really support binary names that are different from julia...

I think so - this works fine, locally (also with Julia in a Singularity container), and it also works remotely on another system that uses Shifter containers instead of Singularity containers.

The weird thing is that `start-julia` *is* being run, but only with `-e "using Pkg; println.(Pkg.depots())"` (been logging the call arguments). But it's not called with `.../terminalserver.jl...` and `.../languageserver/packages main.jl ...` afterwards, as it should be.

**Comment by oschulz** [comment]
I played around with this a bit more - the better approach seems to be to make the remote VS Code server run inside he remote container (where Julia is then globally available). Needs a bit of trickery right now, but it seems to be the better solution - so I'm closing this.

**Comment by oschulz** [comment]
I played around with this a bit more - the better approach seems to be to make the remote VS Code server run inside he remote container (where Julia is then globally available). Needs a bit of trickery right now, but it seems to be the better solution - so I'm closing this issue.
