### ISSUE TITLE
Julia Language Server crashes on start-up

### ISSUE THREAD

**Issue by RyckmanJ** [julia-vscode/julia-vscode#923]
New to this, let me know if there is more information I need to provide.

Using julia-vscode 0.13.1 with JuliaPro 1.2.0-1, on W10

I see this was a known bug in the past, but was said to have been fixed for many people with 0.13.1. Therefore I'm submitting this in case it is only happening now for a small subset of users, but you may already be aware that this problem is ongoing.

**Comment by davidanthoff** [comment]
The best thing is if you submit crash reports via the automated crash reporting!
