### ISSUE TITLE
`ErrorException` is not a keyword and will not be highlighted

### ISSUE THREAD

**Issue by singularitti** [julia-vscode/julia-vscode#928]
![image](https://user-images.githubusercontent.com/25192197/72182686-fa540c80-33b9-11ea-8045-e0b51636497d.png)

The reason is [here](https://github.com/julia-vscode/julia-vscode/blob/67d003517a1fb47f730f1347482866c5bde618b1/syntaxes/julia.json#L249). Please support this keyword!

**Comment by davidanthoff** [comment]
We periodically copy the language definition over from https://github.com/JuliaEditorSupport/atom-language-julia, so ideally you would open an issue over there.

`ErrorException` is not a keyword, so it should not be highlighted. The same is true for `AssertionError`, I think the correct fix here is to also not highlight that.

**Comment by singularitti** [comment]
> The same is true for `AssertionError`, I think the correct fix here is to also not highlight that.

I am curious about why `AssertionError` is not a keyword because I saw it is in that line.

**Comment by davidanthoff** [comment]
These are all types in Julia, I think none of them should be colored as keywords.
