### ISSUE TITLE
F5 does not add include(..) to REPL memory

### ISSUE THREAD

**Issue by MartinOtter** [julia-vscode/julia-vscode#935]
When clicking F5, the selected file is included in Julia and therefore executed.
After 0.11.6, the executed include command, e.g.
```
include("<path>test/runtests.jl")
```
is no longer stored in the REPL memory (under Windows 7 or 10), so it is no longer possible to use the arrow key to get the include command back (and re-execute or modify it).

**Comment by davidanthoff** [comment]
Yeah, we run code entirely differently for F5 now, we no longer use `include` at all, so I don't think we can bring that behavior back, I'm afraid...
