### ISSUE TITLE
Autocomplete issue with Unicode characters in file

### ISSUE THREAD

**Issue by ChrHorn** [julia-vscode/julia-vscode#955]
Autocomplete won't work correctly at the end of the file if Unicode characters exist in the code.

Example:
```julia
α, β, γ = 0, 0, 0
fun1(x) = abs(x)
 
 
 
```
Line 3: works fine
Line 4: no completion
Line 5: no completion for fun1, abs, but works for built in Julia functions

Version: 0.14.0-beta.2

**Comment by alexeypetrushin** [comment]
Not sure if related. Unicode autocomplete worked in my previous version of VSCode + Julia (don't remember the version sadly). But now with julia extension ` v. 0.13.1` it's not working. `\alpha + TAB` does nothing.
