### ISSUE TITLE
Linting issue with Base.@kwdef

### ISSUE THREAD

**Issue by ianfiske** [julia-vscode/julia-vscode#962]
I'm using 0.14.0-beta3 with Julia 1.3.  When a struct is declared with `Base.@kwdef`, then VSCode shows that the corresponding keyword-constructor has "An incorrect number of function arguments has been passed.Julia(Julia)".

Here's a minimal example:

```
module MyModule

Base.@kwdef struct A
    x::Float64
end

function make_A()
    A(x=5.0)
end

end
```

![image](https://user-images.githubusercontent.com/135570/73480610-313d9280-4368-11ea-8f32-928a8a811512.png)

**Comment by davidanthoff** [comment]
@ZacLN that probably just requires another set of special handling? I'm putting this on the milestone for v0.14.2, given that there is an endless list of additional macros we could support, and that we should ship something :)

**Comment by ZacLN** [comment]
Yep, this should be easily fixed. Thanks @ianfiske for the issue

**Comment by ianfiske** [comment]
Great, glad to hear it, @ZacLN
