### ISSUE TITLE
Process hogs 100%CPU on starting 0.14.0-beta3

### ISSUE THREAD

**Issue by laborg** [julia-vscode/julia-vscode#964]
When starting 0.14.0-beta3 a process comes up which runs forever with  ~100% CPU: 
```
gerhard  12790 94.0  2.6 984464 427680 ?       Rl   08:52   4:30 /home/gerhard/julia-1.4.0-rc1/bin/julia --startup-file=no --history-file=no --project=/home/gerhard/.vscode/extensions/julialang.language-julia-0.14.0-beta.3/scripts/languageserver/packages main.jl /home/gerhard/.julia/environments/v1.4 --debug=no /tmp/vscode-language-julia-lscrashreports-12589
```
### Observations
- Happens on Julia 1.3.1 and 1.4.0-rc1
- in vscode I can send expressions to the Julia terminal but other functionality of the extension does not work (hover information, linting,...)

- Indexing appears to finish (`jstore` files are created in `...scripts/languageserver/packages/SymbolServer/store`)
- My environment: Ubuntu 19.10
```
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

Any idea how to provide verbose information on whats going wrong?

**Comment by davidanthoff** [comment]
I'm pretty lost on this one... Presumably we are ending in some endless loop in the LS process, but I have no idea how to debug this, really...

For now I'm moving this off the 0.14.0 milestone, just because I don't know what to do, and we want to ship something.

**Comment by laborg** [comment]
On 0.14-rc this doesn't happen anymore. Should I close it?

**Comment by davidanthoff** [comment]
Yes, lets close it!
