### ISSUE TITLE
DataFrames join-method linting alert

### ISSUE THREAD

**Issue by ianfiske** [julia-vscode/julia-vscode#965]
With the 0.14-beta3 release, I receive a linting alert on number of arguments even though the method is correct:

```
using DataFrames
df1 = DataFrame(x = [1,2], y=["a", "b"])
df2 = DataFrame(x = [2,1], z=["c", "d"])
```
gives "An incorrect number of function arguments has been passed"

![image](https://user-images.githubusercontent.com/135570/73548230-6997ac00-440e-11ea-9a06-fb6edad66d96.png)

**Comment by ZacLN** [comment]
This is slightly fiddly and related to two issues.
1. DataFrames extends using a `Base.join(..)` expression. These aren't shown as modified by the module using `names(DataFrames)` so I'm not sure how we can know to note this modified method within the DataFrames cache.
2. There's an ordering issue when searching for method. There's currently no way to guarantee that we look across all imported packages for the relevant method (i.e. in the above we may search across `Base` first then stop as we've found a relevant function).

**Comment by ianfiske** [comment]
Thanks for looking into this.  To handle your issue 1, is there a way to leverage the `methods` function to get at generic methods that have been extended by other packages?

```
julia> methods(join)
# 8 methods for generic function "join":
[1] join(io::IO, strings) in Base at strings/io.jl:296
[2] join(io::IO, strings, delim) in Base at strings/io.jl:296
[3] join(io::IO, strings, delim, last) in Base at strings/io.jl:278
[4] join(df1::AbstractDataFrame, df2::AbstractDataFrame; on, kind, makeunique, indicator, validate) in DataFrames at /Users/ifiske/.julia/packages/DataFrames/uPgZV/src/abstractdataframe/join.jl:314
[5] join(df1::AbstractDataFrame, df2::AbstractDataFrame, dfs::AbstractDataFrame...; on, kind, makeunique, validate) in DataFrames at /Users/ifiske/.julia/packages/DataFrames/uPgZV/src/abstractdataframe/join.jl:438
[6] join(strings) in Base at strings/io.jl:303
[7] join(strings, delim) in Base at strings/io.jl:304
[8] join(strings, delim, last) in Base at strings/io.jl:305

julia> methods(join).ms[5]
join(df1::AbstractDataFrame, df2::AbstractDataFrame, dfs::AbstractDataFrame...) in DataFrames at /Users/ifiske/.julia/packages/DataFrames/uPgZV/src/abstractdataframe/join.jl:438
```

Hmmm... but then it's not clear how you would know to search `methods(join)` in the first place.  Oh, how about

```
julia> [x for x in methodswith(AbstractDataFrame) if x.name==:join]
[1] join(df1::AbstractDataFrame, df2::AbstractDataFrame) in DataFrames at /Users/ifiske/.julia/packages/DataFrames/uPgZV/src/abstractdataframe/join.jl:314
[2] join(df1::AbstractDataFrame, df2::AbstractDataFrame, dfs::AbstractDataFrame...) in DataFrames at /Users/ifiske/.julia/packages/DataFrames/uPgZV/src/abstractdataframe/join.jl:438
```
?

You could do a `methodswith` search on all types defined in a package.  This would work as long as there is no type piracy.

**Comment by ianfiske** [comment]
Actually, wouldn't the `methodswith` approach also address your issue 2?

**Comment by ZacLN** [comment]
I think your suggestion of a brute force search on methods is probably the best approach, I'll have a look

**Comment by ufechner7** [comment]
Same problem here.

**Comment by ufechner7** [comment]
In addition I get the (wrong) warning "wrong number of arguments" for the following functions:
DataFrames.order()
eval()
DataFrames.sort!()

**Comment by ufechner7** [comment]
on more of these issues:
using DataFrames

df = DataFrame(a = repeat([1, 2, 3, 4], outer=[2]),
                      b = repeat([2, 1], outer=[4]),
                      c = 1:8);

**Comment by ZacLN** [comment]
Hi, these are all the same issue (not recognizing extended methods). I've got a fix but it requires changes across LanguageServer, SymbolServer and StaticLint and will take a couple of days to ensure its robust

**Comment by davidanthoff** [comment]
Should we move this to v0.14.1? I think we should ship rather sooner than later, and can always do a follow up bug fix release.

**Comment by ZacLN** [comment]
I'm thinking that's probably best, I've made a PR to turn it off by default

**Comment by davidanthoff** [comment]
I moved it to v0.14.1, because we eventually still want a proper fix? Or not?

**Comment by ZacLN** [comment]
Yep, I should have that good to go tonight/tomorrow but it's not vital
