### ISSUE TITLE
interrupting loops inconsitency

### ISSUE THREAD

**Issue by drhouse82** [julia-vscode/julia-vscode#969]
I previously posted this on discourse:
https://discourse.julialang.org/t/interrupting-while-loops-in-vscode/34083/2

I'm confused by the behaviour of interrupting loops with Ctrl+C when running loops in REPL or from scripts.

The code:
```
while true
    println("foo")
    sleep(1)
end
```

When I type it into REPL, I can perfectly interrupt the loop by pressing Ctrl+C.
In contrast, when I run the code from a script file by pressing F5, I cannot properly interrput the excecution: There is a julia prompt ("julia>") displayed and also working, but the periodic foo-printing continues.

**Comment by ToucheSir** [comment]
Just wanted to add that inserting a `yield()` in the loop does not appear to help either. `include("script.jl")` does, however, so I've been using that as a workaround in the meantime.

**Comment by pfitzseb** [comment]
We can also look into a Juno-like solution that should give the best of both worlds.

**Comment by Cvikli** [comment]
Sorry for not opening another issue, but this seemed actual.

I observe the same with Julia 1.5.0 vs-code REPL:

Pressing Ctrl+C still act like:
The julia prompt ("julia>") displayed but the code doesn't stop, (the periodic foo-printing continues).

**Comment by pfitzseb** [comment]
We don't support interrupts for in-editor evaluation at this point at all.

**Comment by fgerick** [comment]
Is there any chance that this will change in the future?

**Comment by pfitzseb** [comment]
Pretty sure that already works in 1.0.10.
