### ISSUE TITLE
Unicode (\lambda, etc.) works in .jl, but not within Julia chunks in .jmd files

### ISSUE THREAD

**Issue by kliegl** [julia-vscode/julia-vscode#972]
The latex \lambda etc. (unicode) works fine in `.jl` files, but not in Julia chunks in `.jmd` files. Is there a way to enable this feature for .jmd files?  ( I had the same problem with keyboard shortcuts  (e.g., Julia: Execute Code) for Julia code in `.jmd` files, but they work for both types of files with user-defined key bindings.) (MacOS)

**Comment by kliegl** [comment]
Installing the extension `latex-input` takes care of the problem everywhere in `.jmd` files.

**Comment by pfitzseb** [comment]
This is fixed nowadays.
