### ISSUE TITLE
Memory Leak on 0.14-beta3

### ISSUE THREAD

**Issue by ianfiske** [julia-vscode/julia-vscode#973]
Just today, I started seeing the Language Server Julia process start to use an increasing amount of CPU and RAM over time.  Eventually, it was causing my entire machine to slowdown due to the memory consumption.  I killed the Julia process and you can see the LanguageServer output log here:  https://gist.github.com/ianfiske/535c79c8782b5d4cfdc7094faeeaa7a7.

**Comment by davidanthoff** [comment]
I wonder whether that is similar to https://github.com/julia-vscode/julia-vscode/issues/964... I don't really know how to get to the bottom of this... @ZacLN, any ideas?

**Comment by laborg** [comment]
Funnily enough, this started for me too today but on **0.13.1**! It might be something different than #964 (by time I'll compare those two bugs to be sure).

**Comment by ZacLN** [comment]
I'm not sure they're related (i.e. this clearly isn't getting locked into a loop) - definitely concerning though.  I suspect that somehow we're not clearing all references to past CST after an update, though its clearly only happening in very specific circumstances.

I'll have a think about how we can root this out.

**Comment by davidanthoff** [comment]
I'm putting this on the next milestone, I don't think it should block the v0.14.0 release.

**Comment by laborg** [comment]
I'm on 0.14-rc and this error doesn't happen. Not sure, but I think it stopped after one day after a couple of updates of my 1.3 environment (although, as I understand the vscode extension, those packages shouldn't interact with the default environment)

**Comment by davidanthoff** [comment]
Fantastic, I'll close.
