### ISSUE TITLE
Linter does not recognize extra methods provided by a package

### ISSUE THREAD

**Issue by cjdoris** [julia-vscode/julia-vscode#976]
For example in
```julia
using LogarithmicNumbers
LogarithmicNumbers.exp(Logarithmic, 12)
Base.exp(Logarithmic, 12)
exp(Logarithmic, 12)
```
lines 3 and 4 get lint warning "An incorrect number of function arguments has been passed" but line 2 does not, and they are all the same `exp` function because `LogarithmicNumbers` does `import Base: exp`.

**Comment by davidanthoff** [comment]
What version of the extension are you using?

**Comment by ZacLN** [comment]
This is the same as #965 so I'm going to close
