### ISSUE TITLE
Update vendored packages

### ISSUE THREAD

**Issue by ZacLN** [julia-vscode/julia-vscode#983]
We should update JSON/URIParser to versions that include Project.toml files

**Comment by davidanthoff** [comment]
Do we need to do this for 0.14.0, because julia 1.4.0 doesn't support REQUIRE files anymore?

**Comment by ZacLN** [comment]
It runs (I'm on master at the moment) but its a bit of a pain (I can't use `]resolve` in our vscode env to add dependencies)

**Comment by davidanthoff** [comment]
In that case I'll move it to 0.14.1. I'll cut a RC now!

**Comment by davidanthoff** [comment]
This is done on `master` yet.
