### ISSUE TITLE
Audit all packages for use of sizeof

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/julia-vscode#994]
I found at least one instance where the return value of `sizeof` was used to index into a string, which is generally a bug. Searching LanguageServer.jl for `sizeof` returned 39 instances. I think what we need to do is look at every use of `sizeof` in the code base and figure out whether it is correct, or whether `lastindex` should actually be used instead.

We can check packages that have been audited here:
- [x] CSTParser.jl (@ZacLN, you'll have to audit these, I took a look but I don't understand the code base enough)
- [x] DocumentFormat.jl
- [x] StaticLint.jl
- [x] LanguageServer.jl (same here, @ZacLN will have to do this)
- [x] SymbolServer.jl

**Comment by ZacLN** [comment]
I've had a look at LanguageServer (https://github.com/julia-vscode/LanguageServer.jl/pull/529/, this happens to revert the change you just made) and commented on your DocumentFormat PR. 

I'll just check through the Azure reports again to see if there's some useful info I missed

**Comment by davidanthoff** [comment]
@ZacLN are we good with this, i.e. can we close this issue?

**Comment by davidanthoff** [comment]
I think we are good on this, right?
