### ISSUE TITLE
Linting issues with the CSV & the Plots package

### ISSUE THREAD

**Issue by ogierm** [julia-vscode/julia-vscode#997]
_As a preface: I'm an absolute beginner so it could be that I'm either doing something wrong or misunderstand the source of the error._

I'm getting this issue where calls to functions with kwargs are being underlined with a squiggly line and the warning `An incorrect number of function arguments has been passed. Julia(Julia)` is being shown.

Example of my code:
![image](https://user-images.githubusercontent.com/29630575/74654006-a5aa6b00-5189-11ea-86dc-ab3e0b4f4dfb.png)

**Comment by davidanthoff** [comment]
I'm 99% certain this has been fixed on `master`. Just assigning this to @ZacLN  so that he can close if also thinks so :)

**Comment by ZacLN** [comment]
Not fixed on master but on a group of PRs
